### ISSUE TITLE
`Status.fromCodeValue(17)` throws `java.lang.IndexOutOfBoundsException`

### ISSUE THREAD

**Issue by colinmeek-db** [grpc/grpc-java#10142]
Manually reopening locked issue https://github.com/grpc/grpc-java/issues/2237, which was marked as fixed in https://github.com/grpc/grpc-java/pull/2238, a change that did not modify the offending method.

### What version of gRPC-Java are you using?

1.48.2

### What is your environment?

n/a (straightforward off-by-one bug)

### What did you expect to see?

`Status.Code.UNKNOWN.withDescription("Unknown code 17")`

### What did you see instead?

```
  java.lang.IndexOutOfBoundsException: Index 17 out of bounds for length 17
  at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
  at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
  at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
  at java.base/java.util.Objects.checkIndex(Objects.java:372)
  at java.base/java.util.ArrayList.get(ArrayList.java:459)
  at java.base/java.util.Collections$UnmodifiableList.get(Collections.java:1310)
  at io.grpc.Status.fromCodeValue(Status.java:309)
```

### Steps to reproduce the bug

`Status error = Status.fromCodeValue(17);`

See stack trace above.

**Comment by temawi** [comment]
Thanks for reporting the issue @colinmeek-db!

I have a fix incoming in #10155.

**Comment by colinmeek-db** [comment]
Thanks Terry!
