### ISSUE TITLE
Http2Test gracefulShutdown failure

### ISSUE THREAD

**Issue by tonyjongyoonan** [grpc/grpc-java#10277]
### What version of gRPC-Java are you using?
v1.55.1
### What is your environment?
MacOS, JDK8

### Steps to reproduce the bug
flaky error occurred when building

### Output
```
> Task :grpc-interop-testing:test
[jetty-alpn-agent][ info] alpn-boot not necessary for Java version: 1.8.0_372

io.grpc.testing.integration.Http2Test > gracefulShutdown[client=NETTY,server=NETTY] FAILED
    java.lang.AssertionError: expected:<payload {
      body: "\000\000\000"
    }
    > but was:<null>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at io.grpc.testing.integration.AbstractInteropTest.assertResponse(AbstractInteropTest.java:2462)
        at io.grpc.testing.integration.AbstractInteropTest.gracefulShutdown(AbstractInteropTest.java:1476)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:750)

527 tests completed, 1 failed, 30 skipped
```

**Comment by ejona86** [comment]
I've not seen a CI fail with this, and a 1000 runs inside Google on Linux didn't show any flakes. Considering this fixed. If we re-see it, we can reopen it or file a new issue.
