### ISSUE TITLE
How can I use Unix Domain Socket in Android ,both server and client 

### ISSUE THREAD

**Issue by BFELFISH** [grpc/grpc-java#10352]
I want to user Unix Domain Socket in android-java with grpc server.Here is my code:
```java
InetSocketAddress address = new InetSocketAddress("localhost", port); 
Server server = OkHttpServerBuilder.forPort(address,InsecureServerCredentials.create())
.socketFactory(new UnixDomainServerSocketFactory(socketFile)) .build().start()
```

And client is use flutter 
```dart
final socket = await Socket.connect(socketFile, 55041); 
channel = ClientChannel(
        socket.address.host,
        port: socket.remotePort,
        options: ChannelOptions(
            credentials: const ChannelCredentials.insecure(authority: ''),
            codecRegistry: CodecRegistry(
                codecs: [const CoreGzipCodec(), const IdentityCodec()])),
      );
```

**Comment by BFELFISH** [comment]
UnixDomainServerSocketFactory is from https://github.com/square/okhttp/blob/master/samples/unixdomainsockets/src/main/java/okhttp3/unixdomainsockets/UnixDomainServerSocketFactory.java
And I got this error:
`java.lang.ExceptionInInitializerError: Cannot determine cpu address size E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.calculateAddressSize(Platform.java:314) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.<init>(Platform.java:290) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.<init>(Platform.java:31) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform$Supported.<init>(Platform.java:582) E/AndroidRuntime(19579): 
at jnr.ffi.Platform$Linux.<init>(Platform.java:730) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.determinePlatform(Platform.java:193) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.determinePlatform(Platform.java:211) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.access$000(Platform.java:31) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform$SingletonHolder.<clinit>(Platform.java:40) E/AndroidRuntime(19579): 	
at jnr.ffi.Platform.getNativePlatform(Platform.java:327) E/AndroidRuntime(19579): 	
at jnr.unixsocket.SockAddrUnix.<clinit>(SockAddrUnix.java:34) E/AndroidRuntime(19579): 	
at jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:174) E/AndroidRuntime(19579): 	
at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:47) E/AndroidRuntime(19579): 	
at com.example.grpc_proxy.unixdomainsockets.UnixDomainServerSocketFactory$UnixDomainServerSocket.bind(UnixDomainServerSocketFactory.java:54) E/AndroidRuntime(19579): 	
at java.net.ServerSocket.bind(ServerSocket.java:331) E/AndroidRuntime(19579): 	
at io.grpc.okhttp.OkHttpServer.start(OkHttpServer.java:79) E/AndroidRuntime(19579): 	
at io.grpc.internal.ServerImpl.start(ServerImpl.java:185) E/AndroidRuntime(19579): 	
at io.grpc.internal.ServerImpl.start(ServerImpl.java:94)`

**Comment by BFELFISH** [comment]
> That error seems to be a problem with jnr-ffi. We don't support that project, and I don't know if the approach works with our code. You might double-check that you are using the most recent version of jnr-ffi.
> 
> On client-side we have [UdsChannelBuilder](https://github.com/grpc/grpc-java/blob/master/android/src/main/java/io/grpc/android/UdsChannelBuilder.java) as a stop-gap. But we don't have such a thing for server-side. It could follow the same approach and extend UdsSocketFactory to support ServerSocket LocalServerSocket. Not that hard, but also clearly not easy.

Thank you for your answer

**Comment by ejona86** [comment]
Cross-posting: https://stackoverflow.com/questions/76633574/how-can-i-use-unix-domain-socket-in-android-both-server-and-client-with-grpc

**Comment by BFELFISH** [comment]
> ```java
> UnixDomainServerSocketFactory
> ```

Should I build a UdsServerFactory to substitute OkhttpServerBuilder and return a Server, or replace UnixDomainServerSocketFactory as the parameter for socketFactory?

**Comment by BFELFISH** [comment]
> That error seems to be a problem with jnr-ffi. We don't support that project, and I don't know if the approach works with our code. You might double-check that you are using the most recent version of jnr-ffi.
> 
> On client-side we have [UdsChannelBuilder](https://github.com/grpc/grpc-java/blob/master/android/src/main/java/io/grpc/android/UdsChannelBuilder.java) as a stop-gap. But we don't have such a thing for server-side. It could follow the same approach and extend UdsSocketFactory to support ServerSocket LocalServerSocket. Not that hard, but also clearly not easy.

Should I build a UdsServerFactory to substitute OkhttpServerBuilder and return a Server, or replace UnixDomainServerSocketFactory as the parameter for socketFactory?

**Comment by BFELFISH** [comment]
I have solved this problem by following the same approach of UdsChannelBuilder.

**Comment by temawi** [comment]
I'm glad a solution was found. Closing the issue.
