### ISSUE TITLE
Bigtable - Default config is invalid [grpclb] [gke]

### ISSUE THREAD

**Issue by Naidile-P-N** [grpc/grpc-java#10377]
### What version of gRPC-Java are you using?

1.55.1

### What is your environment?

OS  -On GKE - Linux[gke-os-distribution - cos]
JDK 15 with maven

### What did you expect to see?
Connect to Bigtable instance in the same GCP project from the application.
I'm able to connect to Bigtable using my account running in local environment.

### What did you see instead?

Connection to bigtable fails with exception at this line

```
val settings: BigtableDataSettings =
                BigtableDataSettings.newBuilder().setProjectId(projectId).setInstanceId(instanceId).build()
val client = BigtableDataClient.create(settings)
```

Dependency used 

`<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigtable</artifactId>
            <version>2.24.1</version>
        </dependency>`

### Steps to reproduce the bug

1. Deploy the service in GKE
2. Attempt to connect to Bigtable

```
Caused by: java.lang.IllegalStateException: Default config is invalid: Status{code=UNKNOWN, description=None of [grpclb] specified by Service Config are available., cause=null}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:642)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:631)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:391)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:107)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:85)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:237)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:231)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:175)
	at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:165)
```

Note : Error still persists after modifications to service account and workload identity setup

**Comment by sanjaypujare** [comment]
I think this is an issue in Bigtable (or Google Cloud Java client libraries). They are not populating the service config in the builder correctly. Did you check with them?

**Comment by Naidile-P-N** [comment]
i have raised a issue with google-apis. 

Internally `Maven: io.grpc:grpc-grpclb:1.55.12 ` dependency is being used

**Comment by sanjaypujare** [comment]
`io.grpc:grpc-grpclb:1.55.12` doesn't exist - `io.grpc:grpc-grpclb:1.55.3` is the latest. May be a typo?

**Comment by Naidile-P-N** [comment]
typo sorry -  it's ` io.grpc:grpc-grpclb:1.55.1`

**Comment by Naidile-P-N** [comment]
Closing the issue here as it's an issue with the google-apis
