### ISSUE TITLE
Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x2a9df997]

### ISSUE THREAD

**Issue by MaeThird** [grpc/grpc-java#10408]
### What version of gRPC-Java are you using?
1.56.1
### What is your environment?

openjdk 20.0.2 2023-07-18
Linux  6.4.4-arch1-1 
### What did you expect to see?
In IntelliJ IDEA use ui to run the client code **it can connect to the server side and everything is OK**. 
But after I packaged it into a fat executable jar the RPC failed with UNAVAILABLE: io exception.

### What did you see instead?
Bootstrap - Unknown channel option 'SO_KEEPALIVE' for channel '[id: 0x3335a6f4]'

```
Status{code=UNAVAILABLE, description=io exception, cause=java.io.FileNotFoundException
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:153)
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.connect(Socket.java:351)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
	at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext
```
### Steps to reproduce the bug
 I found when run it with ui **in IntelliJ the grpc channel is the  instance of  `EpollSocketChannel` and there is an option SO_KEEPLIVE in `EpollSocketChannelConfig` but in fat jar execution the grpc channel is the instance of `EpollDoainSocketChannel `and there is no such option SO_KEEPALIVE in `EpollDomainSocketChannelConfig`**.

The `NettyChannelBuilder` is experimental  api I cannot import it. Is there a way to explicitly use EpollSocketChannel instead of EpollDoainSocketChannel ?

**Comment by MaeThird** [comment]
Yes, it' OK now. Thank you.
