### ISSUE TITLE
NullPointerException when serializing Metadata after calling onError

### ISSUE THREAD

**Issue by obarcelonap** [grpc/grpc-java#10418]
### What version of gRPC-Java are you using?
1.41.0

### What is your environment?
* Ubuntu 22.04
* Java 17.0.8
* Opentelemetry java agent 1.6

### What did you expect to see?
Metadata available or at least a null check to avoid crashing.

### What did you see instead?
Null pointer due to not able to serialize the metadata

### Steps to reproduce the bug

In a server streaming operation, `responseObserver.onError` is called due to validation failure,
```
public void myMethod(
            Request request,
            StreamObserver<OutDTO> responseObserver) {

        var something = findSomething(request);
        if (something.isEmpty()) {
            // this is the onError failing
            responseObserver.onError(StatusProto.toStatusRuntimeException(Status.newBuilder()
                    .setCode(Code.INVALID_ARGUMENT_VALUE)
                    .build()));
            return;
        }

      // do something when something is present
}
```

But this causes a NullPointerException when trying to serialize `Metadata`.

Afterwards the system is in an incosistent state: that call is closed but the connection is still opened and it timeouts after 15sec.

Stack trace:
```
java.lang.NullPointerException: Cannot invoke "io.grpc.Metadata$LazyValue.toBytes()" because "value" is null
	at io.grpc.Metadata.valueAsBytes(Metadata.java:180)
	at io.grpc.Metadata.serialize(Metadata.java:471)
	at io.grpc.InternalMetadata.serialize(InternalMetadata.java:78)
	at io.grpc.internal.TransportFrameUtil.toHttp2Headers(TransportFrameUtil.java:51)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.convertServerHeaders(Utils.java:240)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.convertTrailers(Utils.java:253)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerStream$Sink.writeTrailers(NettyServerStream.java:147)
	at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:126)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:218)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:202)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall.close(TracingServerInterceptor.java:104)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
	at com.test.MyInterceptor$1.close(MyInterceptor.java:48)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:39)
	at io.micrometer.core.instrument.binder.grpc.MetricCollectingServerCall.close(MetricCollectingServerCall.java:57)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onError(ServerCalls.java:374)
	at com.test.MyGrpcService.myMethod(MyGrpcService.java:100)
	at com.test.v1.MyGrpcService$MethodHandlers.invoke(MyGrpcService.java:550)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at com.test.GrpcExceptionHandler$ExceptionHandlingServerCallListener.onHalfClose(GrpcExceptionHandler.java:65)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.opentelemetry.javaagent.shaded.instrumentation.grpc.v1_6.TracingServerInterceptor$TracingServerCall$TracingServerCallListener.onHalfClose(TracingServerInterceptor.java:139)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:335)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by ejona86** [comment]
> 1.41.0

Use a newer version. You probably have a bug in your code. In v1.53.0 we added an earlier null-pointer check that will help you find the code that is passing null to gRPC.
