### ISSUE TITLE
IllegalStateException in binder HostServices

### ISSUE THREAD

**Issue by temawi** [grpc/grpc-java#10463]
We are seeing the Android interop test case fail occasionally because of an exception from Binder:

```
java.lang.RuntimeException: Unable to create service io.grpc.binder.HostServices$HostService1: java.lang.IllegalStateException
     FATAL EXCEPTION: main
Process: io.grpc.binder.test, PID: 10393
java.lang.RuntimeException: Unable to create service io.grpc.binder.HostServices$HostService1: java.lang.IllegalStateException
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
	at android.app.ActivityThread.-wrap4(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:496)
	at io.grpc.binder.HostServices$HostService.onCreate(HostServices.java:211)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
	... 8 more
```

https://firebase.corp.google.com/project/grpc-testing/testlab/histories/bh.6e2cfdde264f9eb3/matrices/4697526383710484192/executions/bs.31b64d23fbf1c590

**Comment by temawi** [comment]
@markb74 Do you have any idea on what might be going on here?

This used to work prior to July 21st. but there are also other failures we are looking into, so we don't exactly know when this started.

cc: @ejona86

**Comment by reylobo88azteca** [comment]
> We are seeing the Android interop test case fail occasionally because of an exception from Binder:
> 
> ```
> java.lang.RuntimeException: Unable to create service io.grpc.binder.HostServices$HostService1: java.lang.IllegalStateException
>      FATAL EXCEPTION: main
> Process: io.grpc.binder.test, PID: 10393
> java.lang.RuntimeException: Unable to create service io.grpc.binder.HostServices$HostService1: java.lang.IllegalStateException
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
> 	at android.app.ActivityThread.-wrap4(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5417)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: java.lang.IllegalStateException
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:496)
> 	at io.grpc.binder.HostServices$HostService.onCreate(HostServices.java:211)
> 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
> 	... 8 more
> ```
> 
> https://firebase.corp.google.com/project/grpc-testing/testlab/histories/bh.6e2cfdde264f9eb3/matrices/4697526383710484192/executions/bs.31b64d23fbf1c590
