### ISSUE TITLE
grpc_health_probe suddenly fails after upgrade to grpc-java 1.55.3 from 1.54.2

### ISSUE THREAD

**Issue by anders-brujordet** [grpc/grpc-java#10500]
So I'm running a [Bazel Buildfarm](https://github.com/bazelbuild/bazel-buildfarm) which depends on grpc-java. 
The bulidfarm create a HealthStatusManager in [BuildFarmServer.java#L150](https://github.com/bazelbuild/bazel-buildfarm/blob/main/src/main/java/build/buildfarm/server/BuildFarmServer.java#L150)

And I've been using [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe) to check that the service is up and running like so:

```
./grpc_health_probe -addr=:8980
status: SERVING
```

But when the dependency to grpc-java is bumped from `1.54.2` to `1.55.3` this check suddenly breaks:
```
./grpc_health_probe -addr=:8980
error: health rpc failed: rpc error: code = Internal desc = Failed to frame message
```

While the bulidfarm is logging a stack trace:
```
SEVERE: Exception while executing runnable io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall$4@71c820f9
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:212)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:207)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:44)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall.access$401(TransmitStatusRuntimeExceptionInterceptor.java:121)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall$4.run(TransmitStatusRuntimeExceptionInterceptor.java:170)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall.close(TransmitStatusRuntimeExceptionInterceptor.java:164)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)
	at io.grpc.protobuf.services.HealthServiceImpl.check(HealthServiceImpl.java:77)
	at io.grpc.health.v1.HealthGrpc$MethodHandlers.invoke(HealthGrpc.java:326)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$1.onHalfClose(TransmitStatusRuntimeExceptionInterceptor.java:74)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:346)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So I'm not posting this as a bug because I'm not sure the usage here is correct, and I'm mostly hoping for some input on what exactly could be going wrong.

Thanks

**Comment by larry-safran** [comment]
Can you please confirm that you only updated the grpc-java version, not the healthprobe, grpc-go or go versions?

**Comment by larry-safran** [comment]
Were there any other errors in the log besides the one posted above?

**Comment by anders-brujordet** [comment]
Yeah I only updated grpc-java version. No other errors unfortunately.

**Comment by ejona86** [comment]
The internal "Failed to frame message" error is being caught at:

https://github.com/grpc/grpc-java/blob/2b4f649b0ab4dbbe6e03dcc19b4f607a942de450/core/src/main/java/io/grpc/internal/ServerCallImpl.java#L171-L172

It looks like the bug is it should call `internalClose()` instead. That logs and avoids setting `closeCalled = true`, which is what is causing that follow-up error "call already closed". Although `internalClose()` is using cancel(), so the client will just see a RST.

**Comment by larry-safran** [comment]
Once 1.58 is released, please use that for the server which should give a better error message which hopefully will help us figure out why the server is having an issue sending the status message.

**Comment by brujoand** [comment]
Stack trace with 1.58:

```
SEVERE: Exception while executing runnable io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall$4@731868f6
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:212)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:207)
	at io.grpc.PartialForwardingServerCall.close(PartialForwardingServerCall.java:48)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:22)
	at io.grpc.ForwardingServerCall$SimpleForwardingServerCall.close(ForwardingServerCall.java:44)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall.access$401(TransmitStatusRuntimeExceptionInterceptor.java:121)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall$4.run(TransmitStatusRuntimeExceptionInterceptor.java:170)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:102)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:95)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall.close(TransmitStatusRuntimeExceptionInterceptor.java:164)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onCompleted(ServerCalls.java:395)
	at io.grpc.protobuf.services.HealthServiceImpl.check(HealthServiceImpl.java:77)
	at io.grpc.health.v1.HealthGrpc$MethodHandlers.invoke(HealthGrpc.java:326)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$1.onHalfClose(TransmitStatusRuntimeExceptionInterceptor.java:74)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:346)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Not much difference unfortunatly:
```
1c1
< SEVERE: Exception while executing runnable io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall$4@71c820f9
---
> SEVERE: Exception while executing runnable io.grpc.util.TransmitStatusRuntimeExceptionInterceptor$SerializingServerCall$4@731868f6
3c3
< 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
---
> 	at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
```

**Comment by ejona86** [comment]
I'm assuming the client still failed with the same thing when talking to a grpc-java 1.58 server:

> error: health rpc failed: rpc error: code = Internal desc = Failed to frame message

Why you aren't seeing more info about the error is quite the riddle. I'm growing suspicious of TransmitStatusRuntimeExceptionInterceptor, and it potentially complicating something. It _should_ be fine, but would you mind disabling TransmitStatusRuntimeExceptionInterceptor and re-testing?

**Comment by larry-safran** [comment]
The changes went into 1.59, not 1.58.

Please try it with 1.59 and you should see the line in the stacktrace
```
	at io.grpc.internal.ServerCallImpl.closeInternal(ServerCallImpl.java:212)
```
change to line `213`.

**Comment by temawi** [comment]
Maybe this is no longer an issue since there has been no update in several months? I will close it but it can be reopened if further discussion is required.
