### ISSUE TITLE
grpc-java: Server side can't get exception details from client side onError

### ISSUE THREAD

**Issue by CCint3** [grpc/grpc-java#10511]
in Bidirectional streaming RPC.

Client side call outbound StreamObserver.onError:

```java
        @Override
        public void onNext(@NonNull ActionReq req) {
            String actionId = req.getId();
            String actionName = req.getName();
            Log.d(TAG, String.format("onNext: id:%s,name:%s", actionId, actionName));
            if (!mActionId.equals(actionId)) {
                Metadata metadata = new Metadata();
                metadata.put(GrpcKeyUtil.sMetaActorActionIdKey, mActionId);
                StatusRuntimeException e = Status.INVALID_ARGUMENT
                        .withDescription("actionId is error! stream.id:" + mActionId + ",req.id:" + actionId)
                        .asRuntimeException(metadata);
                // the mPeer is Client side outbound StreamObserver!
                mPeer.onError(e);
                return;
            }
            // ...
        }
```

Server side receives error from inbound StreamObserver.onError:

```java
        @Override
        public void onError(Throwable t) {
            Log.e(TAG, "onError: ", t);
            if (t instanceof StatusRuntimeException e) {
                Metadata metadata = e.getTrailers();
                Log.d(TAG, "onError: metadata " + metadata);
            }
            actionResult.onError(t);
        }
```

The problem is that the server side onError received `io.grpc.StatusRuntimeException: CANCELLED: client canceled.`

That is to say, what the server receives is not `io.grpc.StatusRuntimeException: INVALID_ARGUMENT: actionId is error!`

the client side log:

```log
08-19 19:38:26.205 27030 27066 E ActorActionStream: io.grpc.StatusRuntimeException: CANCELLED: Cancelled by client with StreamObserver.onError()
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.Status.asRuntimeException(Status.java:539)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at java.lang.Thread.run(Thread.java:920)
08-19 19:38:26.205 27030 27066 E ActorActionStream: Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: actionId is error! stream.id:e7603444-f9d8-4597-9525-7f1bd4fccbb6,req.id:
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.Status.asRuntimeException(Status.java:539)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at agent.grpc.client.ActorChannelMgr$ActorActionStream.onNext(ActorChannelMgr.java:110)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at agent.grpc.client.ActorChannelMgr$ActorActionStream.onNext(ActorChannelMgr.java:86)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:474)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:660)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:647)
08-19 19:38:26.205 27030 27066 E ActorActionStream:   ... 5 more
```

the server side log:

```log
08-19 19:38:26.208 25243 27100 E ActorActionStream: onError:
08-19 19:38:26.208 25243 27100 E ActorActionStream: io.grpc.StatusRuntimeException: CANCELLED: client cancelled
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.Status.asRuntimeException(Status.java:530)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:291)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:365)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:354)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:909)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 19:38:26.208 25243 27100 E ActorActionStream:   at java.lang.Thread.run(Thread.java:920)
08-19 19:38:26.208 25243 27100 D ActorActionStream: onError: metadata null
```

I want to know how the server can correctly receive INVALID_ARGUMENT: actionId is error!

**Comment by larry-safran** [comment]
I'd like to understand why you are trying to get the exception details on the server.

The cause data is not sent over the wire intentionally, but there may be other ways to satisfy your use case.

**Comment by CCint3** [comment]
very thanks your answer. i want to print the exception cause detail in my server side.

**Comment by larry-safran** [comment]
The exception will be logged on the client side.  To get it to the server side, you would have to configure your method as bidirectional streaming with the client sending a message containing all of the details and an identifier to correlate with the corresponding server message.

**Comment by CCint3** [comment]
> 

thanks you. so i need add new gRPC interface? and define `message MyException { xxx }`?

When an exception occurs on the client side, convert the exception information to MyException and send it to the server through a new gRPC?

**Comment by larry-safran** [comment]
You can either do that or in your request message have a StatusRuntimeException field and send that before calling onError.
