### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0) on upgrading to gRPC 1.55.1 and JVM Property: jdk.tls.client.protocols="TLSv1.2" or "TLSv1.3"

### ISSUE THREAD

**Issue by sp736613** [grpc/grpc-java#10510]
### What version of gRPC-Java are you using?
1.55.1
### What is your environment?
    NAME="Red Hat Enterprise Linux"
    VERSION="8.8 (Ootpa)"
    OpenSSL Version: OpenSSL 1.1.1k  FIPS 25 Mar 2021
    Java Version : openjdk version "1.8.0_352", OpenJDK Runtime Environment (Temurin)(build 1.8.0_352-b08)

JVM Property: jdk.tls.client.protocols="TLSv1.2" 

### What did you expect to see?

```
TRACE io.grpc.ChannelLogger - [Subchannel<3>: (redacted.xyz-dev.redacted.com)] Subchannel for [[[/240.8.9.95:6001]/{}]] created
TRACE io.grpc.ChannelLogger - [Channel<1>: (aws://redacted)] Child Subchannel started
DEBUG io.grpc.ChannelLogger - [Subchannel<3>: (redacted.xyz-dev.redacted.com)] CONNECTING as requested
DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true
DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Creating allocator, preferDirect=true
DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Forcing maxOrder=8
DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.processId: 10427 (auto-detected)
DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.machineId: f6:ed:c3:ff:fe:2c:0e:2f (auto-detected)
[grpc-default-worker-ELG-1-2] TRACE io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.9.95:6001)] WaitUntilActive started
DEBUG io.grpc.ChannelLogger - [Subchannel<3>: (redacted.abc-dev.redacted.com)] Started transport NettyClientTransport<4>: (/240.8.9.95:6001)
DEBUG io.grpc.ChannelLogger - [Channel<1>: (aws://redacted)] Entering CONNECTING state with picker: EmptyPicker{status=Status{code=OK, description=null, cause=null}}
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.9.95:6001)] WaitUntilActive completed
[grpc-default-worker-ELG-1-2] TRACE io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.9.95:6001)] ClientTls started
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector@78744612
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler - [id: 0x585f2f7d, L:/240.8.23.196:42794 - R:240.8.9.95/240.8.9.95:6001] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_128_GCM_SHA256
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.ProtocolNegotiators - TLS negotiation succeeded.
SSLEngine Details: [
    OpenSSL, Version: 0x1010107f (BoringSSL), ALPN supported: true
    TLS Protocol: TLSv1.3
    Application Protocol: h2
    Need Client Auth: false
    Want Client Auth: false
    Supported protocols=[SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
    Enabled protocols=[SSLv2Hello, TLSv1.2, TLSv1.3]
    Supported ciphers=[ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-CHACHA20-POLY1305, ECDHE-RSA-CHACHA20-POLY1305, ECDHE-PSK-CHACHA20-POLY1305, ECDHE-ECDSA-AES128-SHA, ECDHE-RSA-AES128-SHA, ECDHE-PSK-AES128-CBC-SHA, ECDHE-ECDSA-AES256-SHA, ECDHE-RSA-AES256-SHA, ECDHE-PSK-AES256-CBC-SHA, AES128-GCM-SHA256, AES256-GCM-SHA384, AES128-SHA, PSK-AES128-CBC-SHA, AES256-SHA, PSK-AES256-CBC-SHA, DES-CBC3-SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, AEAD-AES128-GCM-SHA256, AEAD-AES256-GCM-SHA384, AEAD-CHACHA20-POLY1305-SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, SSL_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, SSL_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256, SSL_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA, SSL_ECDHE_PSK_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA, SSL_ECDHE_PSK_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, SSL_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, SSL_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_AES_128_CBC_SHA, TLS_PSK_WITH_AES_128_CBC_SHA, SSL_PSK_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_AES_256_CBC_SHA, TLS_PSK_WITH_AES_256_CBC_SHA, SSL_PSK_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, null]
    Enabled ciphers=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256]
]
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.9.95:6001)] ClientTls completed
```

### What did you see instead?

We see the following exception

javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)

```
TRACE io.grpc.ChannelLogger - [Subchannel<3>: (redacted.abc-dev.redacted.com)] Subchannel for [[[/240.8.23.172:6001]/{}]] created
TRACE io.grpc.ChannelLogger - [Channel<1>: (aws://redacted)] Child Subchannel started
DEBUG io.grpc.ChannelLogger - [Subchannel<3>: (redacted.abc-dev.redacted.com)] CONNECTING as requested
DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true
DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Creating allocator, preferDirect=true
DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Forcing maxOrder=8
DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.processId: 113835 (auto-detected)
DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 66:4c:75:ff:fe:ee:44:ec (auto-detected)
[grpc-default-worker-ELG-1-2] TRACE io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.23.172:6001)] WaitUntilActive started
DEBUG io.grpc.ChannelLogger - [Subchannel<3>: (redacted.abc-dev.redacted.com)] Started transport NettyClientTransport<4>: (/240.8.23.172:6001)
DEBUG io.grpc.ChannelLogger - [Channel<1>: (aws://redacted)] Entering CONNECTING state with picker: EmptyPicker{status=Status{code=OK, description=null, cause=null}}
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.23.172:6001)] WaitUntilActive completed
[grpc-default-worker-ELG-1-2] TRACE io.grpc.ChannelLogger - [NettyClientTransport<4>: (/240.8.23.172:6001)] ClientTls started
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector@398b5a76
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine - SSL_do_handshake failed with 1: OpenSSL error: 0 error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.ChannelLogger - [Subchannel<3>: (redacted.abc-dev.redacted.com)] NettyClientTransport<4>: (/240.8.23.172:6001) SHUTDOWN with UNAVAILABLE(io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0])[javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)]
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.ChannelLogger - [Subchannel<3>: (redacted.abc-dev.redacted.com)] TRANSIENT_FAILURE (UNAVAILABLE(io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0])[javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)]). Will reconnect after 776,038,882 ns
[grpc-default-worker-ELG-1-2] DEBUG io.grpc.ChannelLogger - [Channel<1>: (aws://redacted)] Entering TRANSIENT_FAILURE state with picker: EmptyPicker{status=Status{code=UNAVAILABLE, description=io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0], cause=javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1086)
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1070)
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake(ReferenceCountedOpenSslEngine.java:1981)
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.beginHandshake(ReferenceCountedOpenSslEngine.java:1864)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:2089)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:2006)
```

### Steps to reproduce the bug

We've had the JVM property jdk.tls.client.protocols="TLSv1.2" on previous gRPC versions and gRPC requests worked fine. 
After upgrading to 1.55.1, we see the following exception
`javax.net.ssl.SSLHandshakeException: error:00000000:invalid library (0):OPENSSL_internal:invalid library (0)` 
when a Java gRPC client tries to send a gRPC request to a gRPC server and the request fails. 

- We do not see this error on 1.55.1 when we don't set the JVM property.
- We still see the error if we set the property value to "TLSv1.3"

We also see this in the logs for both pods (when it tries to link the netty-tcnative library?) if it helps:
```
Pod running with grpc 1.52.1
DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Successfully loaded the library /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_648241571089384732565.so
DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Loaded library with name 'netty_tcnative_linux_x86_64'
DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: BoringSSL
DEBUG io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector - -Dio.grpc.netty.shaded.io.netty.leakDetection.level: simple
 
Pod running with grpc 1.55.1
DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Successfully loaded the library /tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_646664569250058866476.so
DEBUG io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Loaded library with name 'netty_tcnative_linux_x86_64'
DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: BoringSSL
DEBUG io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector - -Dio.grpc.netty.shaded.io.netty.leakDetection.level: simple
```

**Comment by larry-safran** [comment]
A similar behavior was reported in #2320.  The solution there was to upgrade to JRE 9.

The netty and netty-tcnative versions were updated in 1.54 which is probably a cause of the changed behavior.  The netty-tcnative library was updated again in 1.56, so you could check whether 1.56.1 or 1.57.2 fixes the problem.

**Comment by sp736613** [comment]
Thanks for the response. 

We tried an upgrade to grpc 1.56.1 and 1.57.2 (the latest), but that didn't resolve the issue. We figured out a way bypass setting the JVM property "jdk.tls.client.protocols", and it all works fine without the JVM property.
