### ISSUE TITLE
Why???  java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by baigod** [grpc/grpc-java#10532]
I constructed a GRPC bidirectional flow client using the following methods and parameters：

```
NettyChannelBuilder builder = NettyChannelBuilder
                .forAddress("192.168.1.1", 9090)
                .eventLoopGroup(new NioEventLoopGroup(Optional.ofNullable(rpcNettyEventLoop).orElse(Runtime.getRuntime().availableProcessors() * 2)))
                .compressorRegistry(CompressorRegistry.getDefaultInstance())
                .decompressorRegistry(DecompressorRegistry.getDefaultInstance())
                .enableFullStreamDecompression()
                .withOption(ChannelOption.SO_SNDBUF, 1048576)
                .withOption(ChannelOption.SO_RCVBUF, 1048576)
                .channelType(NioSocketChannel.class)
                .keepAliveTime(30, TimeUnit.SECONDS);
        if (sslEnabled) {
            try {
                SslContextBuilder sslContextBuilder = GrpcSslContexts.forClient();
                if (StringUtils.isNotEmpty(certResource)) {
                    sslContextBuilder.trustManager(ResourceUtils.getInputStream(this, certResource));
                }
                builder.sslContext(sslContextBuilder.build());
            } catch (SSLException e) {
                log.error("Failed to initialize channel!", e);
                throw new RuntimeException(e);
            }
        } else {
            builder.usePlaintext();
        }

        builder.defaultLoadBalancingPolicy("round_robin");

        channel = builder.build();
        IntegrationTransportGrpc.IntegrationTransportStub stub = IntegrationTransportGrpc.newStub(channel);
        this.inputStream = stub.handleMsgs(initOutputStream(integrationKey, onIntegrationUpdate, onConverterUpdate, onDownlink, onError));
```

But when I tried to send a large number of messages to the server during performance testing, I encountered the following error

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
	at io.grpc.netty.shaded.io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51)
	at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:226)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:168)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:141)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream.writeMessage(DelayedStream.java:278)
	at io.grpc.internal.RetriableStream.sendMessage(RetriableStream.java:542)
	at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:520)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:506)
	at io.grpc.internal.DelayedClientCall.sendMessage(DelayedClientCall.java:316)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:365)
```

I set 800M of out of heap memory：

```
JAVA_OPTS="-XX:+UseContainerSupport -XX:InitialRAMPercentage=20 -XX:MaxRAMPercentage=60 \
                      -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/gc/gc.log:time,uptime,level,tags:filecount=10,filesize=10M \
                      -XX:+PrintGCTimeStamps  -XX:+PrintGCDateStamps \
                      -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError \
                      -XX:HeapDumpPath=/var/log/gc/$(/bin/hostname).hprof \
                      -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark \
                      -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10 \
                      -Xss256k -XX:NewRatio=2 -XX:ConcGCThreads=1 -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=800M"
```

Please ask experts to help me see what caused the problem. Thank you very much!

my gprc version: 1.42.1
java version:jdk 11

**Comment by YifeiZhuang** [comment]
Did you use manual flow control? Sending large number of messages without flow control may overwhelm the transport.

To use manual flow control, you should cast the StreamObserver passed to the service to [ServerCallStreamObserver](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ServerCallStreamObserver.html). You can then use the methods isReady() and setOnReadyHandler() to react to flow control, where you generate messages faster than they are being sent.

**Comment by baigod** [comment]
Thank you very much for your answer. I would also like to add some background. Currently, I have 4 client replicas and 2 server replicas, and the resource configuration is basically the same. Is the client OOM caused by the server not receiving them in time?

> Did you use manual flow control? Sending large number of messages without flow control may overwhelm the transport.
> 
> To use manual flow control, you should cast the StreamObserver passed to the request to [ClientCallStreamObserver](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ClientCallStreamObserver.html). You can then use the methods isReady() and setOnReadyHandler() to react to flow control, where you generate messages faster than they are being sent.

**Comment by YifeiZhuang** [comment]
I imagine that server is not processing message fast enough, or the window update is not fast enough. Once server consumes the messages, it sends window update to the client to free up the window so client can send out more messages and set memory free. Otherwise client message is queued up, and when new messages are created it got OOM.

**Comment by baigod** [comment]
> I imagine that server is not processing message fast enough, or the window update is not fast enough. Once server consumes the messages, it sends window update to the client to free up the window so client can send out more messages and set memory free. Otherwise client message is queued up, and when new messages are created it got OOM.

Thank you. It was very rewarding

**Comment by baigod** [comment]
I'm going crazy. I'm doing a stress test with a tps of around 50000. My server machine configuration is 12 cores, 24G x 3, and the client is the same. However, the server can't handle it anymore, resulting in direct memory OOM on the client. My server-side operation only forwards messages to Kafka, without any other complex logic

**Comment by YifeiZhuang** [comment]
Closing due to no recent activity. If you need further help, re-open the issue.
