### ISSUE TITLE
Throw "DEADLINE_EXCEEDED: context timed out" although the duration call does not reach the configuration time

### ISSUE THREAD

**Issue by 81300988** [grpc/grpc-java#10624]
### What version of gRPC-Java are you using?
grpc version 1.22.1
### What is your environment?

- linux
- Call via headless service on k8s

### What did you expect to see?
Do not throw DEADLINE_EXCEEDED (because the reponse duration of client is very fast < dealine duration configuration)

### What did you see instead?
Throw DEADLINE_EXCEEDED

my peace of code:
<img width="612" alt="image" src="https://github.com/grpc/grpc-java/assets/29403358/7c1a1c5e-21ad-4048-987e-808c144051ff">

I set the dealine duration = 3s but it throws DEADLINE_EXCEEDED exception after < 3s (about ~100ms, can get this from log at line 11)
### Steps to reproduce the bug
Can not reproduce, just see it on production

**Comment by temawi** [comment]
First thing we should do is to determine if this error is originating from the client or the server. Could you please include the full error you see including any stack traces. We are looking for what may have caused the DEADLINE_EXCEEDED error you are seeing.

**Comment by 81300988** [comment]
Thanks for your response @temawi , I guess this issue comes from client side. Because I add monitoring for both client (method getData) and server (the api called by client), then I don' see any request that peak over than 3 second (as I configure for dealine time out)
Client (~100ms)
<img width="603" alt="image" src="https://github.com/grpc/grpc-java/assets/29403358/15a4e2eb-edfc-4821-80df-6e5df1da24c3">

Server (~100ms)
<img width="619" alt="image" src="https://github.com/grpc/grpc-java/assets/29403358/77bde27d-4342-46e7-a7fb-ce0fd3167cf3">

**Comment by 81300988** [comment]
this is full stack trace

2023-10-25 12:29:14.035 [grpc-default-executor-12266, 945577ef95cac9ed83008f4d7c6a9e48 ,1c257881f674e832] ERROR v.c.z.p.r.i.VoucherFilterIncludedUsedVoucherStatusRule - ExecuteAssessRule exception
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: context timed out
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at zalopay.grpc.protobuf.ZPBaseGrpc$ZPBaseBlockingStub.sendRequest(ZPBaseGrpc.java:211)
	at vn.com.zalopay.promotion.rule.client.voucher.VoucherClientImpl.getVoucherHistory(VoucherClientImpl.java:40)
	at vn.com.zalopay.promotion.rule.client.voucher.VoucherClientImpl$$FastClassBySpringCGLIB$$6497d9aa.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at vn.zalopay.utils.monitoring.interceptor.MetricMonitoringInterceptor.invokeUnderTrace(MetricMonitoringInterceptor.java:56)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateCheckedSupplier$82a9021a$1(CircuitBreaker.java:73)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.executeCheckedSupplier(CircuitBreaker.java:834)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.defaultHandling(CircuitBreakerAspect.java:188)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.proceed(CircuitBreakerAspect.java:135)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.circuitBreakerAroundAdvice(CircuitBreakerAspect.java:112)
	at sun.reflect.GeneratedMethodAccessor274.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137)
	at io.github.resilience4j.retry.Retry.executeCheckedSupplier(Retry.java:419)
	at io.github.resilience4j.retry.configure.RetryAspect.handleDefaultJoinPoint(RetryAspect.java:184)
	at io.github.resilience4j.retry.configure.RetryAspect.proceed(RetryAspect.java:141)
	at io.github.resilience4j.retry.configure.RetryAspect.retryAroundAdvice(RetryAspect.java:120)
	at sun.reflect.GeneratedMethodAccessor273.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at vn.com.zalopay.promotion.rule.client.voucher.VoucherClientImpl$$EnhancerBySpringCGLIB$$d065a6ef.getVoucherHistory(<generated>)
	at vn.com.zalopay.promotion.rule.client.voucher.VoucherServiceImpl.getAllVoucherByUserID(VoucherServiceImpl.java:36)
	at vn.com.zalopay.promotion.rule.impl.VoucherFilterIncludedUsedVoucherStatusRule.executeAssessRule(VoucherFilterIncludedUsedVoucherStatusRule.java:63)
	at vn.com.zalopay.promotion.rule.impl.VoucherFilterIncludedUsedVoucherStatusRule$$FastClassBySpringCGLIB$$434d3a37.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at vn.zalopay.utils.monitoring.interceptor.MetricMonitoringInterceptor.invokeUnderTrace(MetricMonitoringInterceptor.java:56)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at vn.com.zalopay.promotion.rule.impl.VoucherFilterIncludedUsedVoucherStatusRule$$EnhancerBySpringCGLIB$$21d49d02.executeAssessRule(<generated>)
	at vn.com.zalopay.promotion.rule.service.RuleNormalProcessorImpl.processCheckNormalRule(RuleNormalProcessorImpl.java:33)
	at vn.com.zalopay.promotion.rule.service.RuleProcessorImpl.processCheckAllRules(RuleProcessorImpl.java:158)
	at vn.com.zalopay.promotion.rule.service.RuleProcessorImpl.checkRules(RuleProcessorImpl.java:59)
	at vn.com.zalopay.promotion.rule.controller.RuleGrpcController.checkRuleSyncV2(RuleGrpcController.java:128)
	at vn.com.zalopay.promotion.rule.controller.RuleGrpcController$$FastClassBySpringCGLIB$$9177514.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at vn.zalopay.utils.monitoring.interceptor.MetricMonitoringInterceptor.invokeUnderTrace(MetricMonitoringInterceptor.java:56)
	at org.springframework.aop.interceptor.AbstractTraceInterceptor.invoke(AbstractTraceInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at vn.com.zalopay.promotion.rule.controller.RuleGrpcController$$EnhancerBySpringCGLIB$$8bac7fb9.checkRuleSyncV2(<generated>)
	at vn.com.zalopay.promotion.rule.entity.RuleEngineGrpc$MethodHandlers.invoke(RuleEngineGrpc.java:917)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at brave.grpc.TracingServerInterceptor$ScopingServerCallListener.onHalfClose(TracingServerInterceptor.java:156)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:808)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.TimeoutException: context timed out
	at io.grpc.Context$CancellableContext$1.run(Context.java:732)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:338)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 common frames omitted

**Comment by 81300988** [comment]
an additional question @temawi : what is different between **DEADLINE_EXCEEDED: context timed out** and **DEADLINE_EXCEEDED: deadline exceeded after** ?

**Comment by temawi** [comment]
Based on the stack trace it seems that your client is also a server and is making this call as a result of getting called itself. Is this the case? The context timing out here is probably a result of the deadline set by the initial client being passed. The deadline set by the initial client will be honored by an intermediary server. This is called deadline propagation, you can read more here: https://grpc.io/docs/guides/deadlines/

You would see "deadline exceeded after" if you are the original client, "context timed out" can happen if you are the middle-man.

**Comment by 81300988** [comment]
"Based on the stack trace it seems that your client is also a server and is making this call as a result of getting called itself. Is this the case?" => this is not my case

I've found the rootcause, I can brief here
**A** -> **B** -> **C** (A,B,C are services)

**A** call **B**: time out 1.5s
**B** call **C**: time out 3s

**B** has two logic: 
 1. Query database (L1)
 2. Call **C** (L2)

When **A** call **B** and L1 ~= 1.4s => if L2 > 100ms (0.1s) the total time **A** call **B** > 1.5s => **A** throw deadline exeed => at this time **B** is calling **C** but **B** recieve  deadline exeed from **A** => **B** cancles call **C** => **B** throw "DEADLINE_EXCEEDED: context timed out" (**but this point I think it should throw CANCELLED exception instead of DEADLINE_EXCEEDED exception**)

**Comment by larry-safran** [comment]
When B calls C in your example, the context would have a deadline in 100ms.  B & C would both hit the deadline at about the same time.  If the clocks were synchronized, the expected behavior would be that B times out and sends cancel to C while simultaneously C times out and returns a DEADLINE_EXCEEDED.  The cancel from B then shows up, but because the RPC has terminated the cancel is just ignored.
Note that what is passed between the services is a deadline time (in nanoseconds of epoch), not a duration.  Timeouts can happen either because the context deadline expired or the rpc's deadline expired.  The rpc's deadline is set based upon configured duration when the rpc starts.  The context deadline is set based upon duration, but only for the initiating call.

**Comment by 81300988** [comment]
ok got it, thanks @larry-safran @temawi we can close this issue
