### ISSUE TITLE
 java.lang.NoSuchMethodError: 'void io.grpc.googleapis.GoogleCloudToProdNameResolverProvider.<init>(java.lang.String)'  in 1.59.0

### ISSUE THREAD

**Issue by dharmaplay** [grpc/grpc-java#10796]
### What version of gRPC-Java are you using?
1.59.0
### What is your environment?

Windows, jdk 1.8 
### What did you expect to see?
It should run , but getting error 
### What did you see instead?
```
java.util.ServiceConfigurationError: io.grpc.NameResolverProvider: Provider io.grpc.googleapis.GoogleCloudToProdExperimentalNameResolverProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.NameResolverRegistry.getDefaultRegistry(NameResolverRegistry.java:115)
	at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:111)
	at io.grpc.internal.ManagedChannelImplBuilder.<init>(ManagedChannelImplBuilder.java:231)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:194)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forTarget(NettyChannelBuilder.java:164)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:149)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:42)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:28)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:350)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:105)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:83)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:236)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:230)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:201)
	at com.google.cloud.bigquery.storage.v1.stub.EnhancedBigQueryReadStub.create(EnhancedBigQueryReadStub.java:99)
	at com.google.cloud.bigquery.storage.v1.BigQueryReadClient.<init>(BigQueryReadClient.java:130)
	at com.google.cloud.bigquery.storage.v1.BigQueryReadClient.create(BigQueryReadClient.java:110)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.createBigQueryStorageClient(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.client.BQClient.authenticateAndTest(Unknown Source)
	at com.simba.googlebigquery.googlebigquery.core.BQConnection.connect(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.BaseConnectionFactory.doConnect(Unknown Source)
	at com.simba.googlebigquery.jdbc.common.AbstractDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at com.service_now.mid.connections.jdbc.JDBCConnection.establishConnection(JDBCConnection.java:150)
	at com.service_now.mid.connections.jdbc.JDBCConnection.lambda$connect$0(JDBCConnection.java:110)
	at com.glide.util.LogContext$Frame.run(LogContext.java:212)
	at com.service_now.mid.connections.jdbc.JDBCConnection.connect(JDBCConnection.java:108)
	at com.service_now.mid.connections.jdbc.JDBCConnectionFactory.create(JDBCConnectionFactory.java:72)
	at com.service_now.mid.connections.ConnectionCachePool.getAvailableConnection(ConnectionCachePool.java:83)
	at com.service_now.mid.connections.ConnectionCache.get(ConnectionCache.java:95)
	at com.service_now.mid.probe.JDBCProbe.getJDBCConnection(JDBCProbe.java:947)
	at com.service_now.mid.probe.JDBCProbe.probe(JDBCProbe.java:218)
	at com.service_now.mid.probe.AProbe.process(AProbe.java:154)
	at com.service_now.mid.queue_worker.AWorker.runWorker(AWorker.java:131)
	at com.service_now.mid.queue_worker.AWorkerThread.run(AWorkerThread.java:20)
	at com.service_now.mid.threadpool.ResourceUserQueue$RunnableProxy.run(ResourceUserQueue.java:649)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'void io.grpc.googleapis.GoogleCloudToProdNameResolverProvider.<init>(java.lang.String)'
	at io.grpc.googleapis.GoogleCloudToProdExperimentalNameResolverProvider.<init>(GoogleCloudToProdExperimentalNameResolverProvider.java:30)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl$2.run(ServiceLoader.java:788)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:793)

```
### Steps to reproduce the bug
I am getting this error while using bigquery simba driver (https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.5.2.1005.zip )

**Comment by ejona86** [comment]
It looks like two different versions of grpc-googleapis are on your classpath, and java is "randomly" selecting classes from each. Check your dependencies and make sure you aren't pulling it in via Maven and also pulling it in via those explicit jars. If you are using the simba driver and nothing else, you might need to open an issue with them.

**Comment by sergiitk** [comment]
Yes, @ejona86 is right. When only jars from the bigquery jdbc driver are used in the classpath, there's no conflicts:

```
❯ java -cp "./SimbaJDBCDriverforGoogleBigQuery42_1.5.2.1005/*" CheckBigtable.java
SELECT * FROM sergiitk-grpc.sergiitk_test.sergiitk_test_table LIMIT 1

columnName: name
columnTypeName: STRING
Data: yo
columnName: data
columnTypeName: JSON
Data: null
```
