### ISSUE TITLE
Address types of NameResolver 'unix' for 'localhost:8443' not supported by transport

### ISSUE THREAD

**Issue by sknick** [grpc/grpc-java#10826]
I have a Java 1.8 application that runs fine via the IntelliJ IDE via a run configuration that points at the main class. However, as soon as I build the application with Maven and then try to run it via `java -jar <jar file>`, an attempt to initialize the blocking stub for my gRPC API results in this stack trace, which I am absolutely baffled by. What at runtime could be changing to cause this?

```
Exception in thread "AWT-EventQueue-1" java.lang.IllegalArgumentException: Address types of NameResolver 'unix' for 'localhost:8443' not supported by transport
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:750)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:771)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:635)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:668)
	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:260)
	at com.mycompany.ui.LoginDialog.onLogin(LoginDialog.java:110)
	at com.mycompany.ui.LoginDialog.lambda$new$0(LoginDialog.java:59)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicRootPaneUI$Actions.actionPerformed(BasicRootPaneUI.java:208)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1668)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:250)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2974)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2966)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1958)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:834)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1102)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:973)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:799)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ejona86** [comment]
Most likely you aren't building the fat jar correctly. Or rather, the tool you are using probably requires special configuration to properly combine service files. See
https://github.com/grpc/grpc-java/issues/7124#issuecomment-645655090
https://github.com/grpc/grpc-java/issues/9770#issuecomment-1386227244

**Comment by sknick** [comment]
Ya, trick was to use the `maven-shade-plugin` to bundle everything. Thanks!

**Comment by ModAlpha** [comment]
the same thing happened to me, but in my ktor server app
when running through IntelliJ IDEA all fine but when running the jar file via ./gradlew runFatJar as per documentation
https://ktor.io/docs/fatjar.html
I got this exception
java.lang.IllegalArgumentException: Address types of NameResolver 'unix' for '...' not supported by transport
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:750)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:771)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:635)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:662)
        at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:254)
        at ai.pedant.infrastructure.services.DocumentService.connect(DocumentService.kt:83)
        at ai.pedant.infrastructure.services.DocumentService.<init>(DocumentService.kt:24)
        at ai.pedant.di.ServiceModuleKt$serviceModule$1$3.invoke(ServiceModule.kt:14)
        at ai.pedant.di.ServiceModuleKt$serviceModule$1$3.invoke(ServiceModule.kt:14)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
        at org.koin.core.scope.Scope.get(Scope.kt:210)
        at ai.pedant.di.ServiceModuleKt$serviceModule$1$1.invoke(ServiceModule.kt:21)
        at ai.pedant.di.ServiceModuleKt$serviceModule$1$1.invoke(ServiceModule.kt:12)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
        at org.koin.core.scope.Scope.get(Scope.kt:210)
        at ai.pedant.di.GrpcContollerModuleKt$grpcControllerModule$1$1.invoke(GrpcContollerModule.kt:19)
        at ai.pedant.di.GrpcContollerModuleKt$grpcControllerModule$1$1.invoke(GrpcContollerModule.kt:10)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:51)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:116)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:246)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
        at org.koin.core.scope.Scope.get(Scope.kt:210)
        at ai.pedant.GrpcServer$special$$inlined$inject$default$2.invoke(KoinComponent.kt:74)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at ai.pedant.GrpcServer.get_vendorWebController(GrpcServer.kt:19)
        at ai.pedant.GrpcServer.<init>(GrpcServer.kt:31)
        at ai.pedant.ApplicationKt.startGrpcServer(Application.kt:48)
        at ai.pedant.ApplicationKt.access$startGrpcServer(Application.kt:1)
        at ai.pedant.ApplicationKt$module$2.invokeSuspend(Application.kt:42)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by ModAlpha** [comment]
@ejona86 any thoughts

**Comment by neshkeev** [comment]
> Ya, trick was to use the `maven-shade-plugin` to bundle everything. Thanks!

@sknick , would you please share the working `maven-shade-plugin` configuration for packaging a gRPC service/client?

**Comment by sknick** [comment]
```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.3.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>my.Application</mainClass>
                  <manifestEntries>
                    <Implementation-Version>${version}</Implementation-Version>
                    <Main-Class>my.Application</Main-Class>
                  </manifestEntries>
                </transformer>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

**Comment by jaredrummler** [comment]
I am using [shadow](https://github.com/johnrengelman/shadow) for my KTor project which needs to build a fatJar to deploy on Google App Engine. Modifying the project's `build.gradle.kts` resolved the issue for me:

```kotlin
tasks.shadowJar {
  mergeServiceFiles() // https://github.com/grpc/grpc-java/issues/10853
  // other configs
}
```

**Comment by gegnhigwej227** [comment]
> ```
>       <plugin>
>         <groupId>org.apache.maven.plugins</groupId>
>         <artifactId>maven-shade-plugin</artifactId>
>         <version>3.3.0</version>
>         <executions>
>           <execution>
>             <phase>package</phase>
>             <goals>
>               <goal>shade</goal>
>             </goals>
>             <configuration>
>               <createDependencyReducedPom>false</createDependencyReducedPom>
>               <transformers>
>                 <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
>                   <mainClass>my.Application</mainClass>
>                   <manifestEntries>
>                     <Implementation-Version>${version}</Implementation-Version>
>                     <Main-Class>my.Application</Main-Class>
>                   </manifestEntries>
>                 </transformer>
>                 <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
>               </transformers>
>             </configuration>
>           </execution>
>         </executions>
>       </plugin>
> ```

thanks, it work for me
