### ISSUE TITLE
 Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception  Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /127.0.0.1:50051  Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol

### ISSUE THREAD

**Issue by tarokon** [grpc/grpc-java#10861]
### Issue Summary:
```
 Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
 Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /127.0.0.1:50051
 Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
```

### Description:
Using grpc for first time on a new pod and hitting error "Address family not supported by protocol". Verified that grpc server is running locally on 127.0.0.1 on 50051. gRpc client pod compiles and gets deployed successfully and upon initiating a gRpc connection to server a crash is observed with reason "Address family not supported by protocol: /127.0.0.1:50051". Used ManagedChannelBuilder and NettyChannelBuilder, both exhibit same behavior. Took a look at solutions provided on stackoverflow and elsewhere but none have worked till now. Hence this query / bug to get this issue resolved.

grpc: 1.59.0

Below we have 

1. complete stack trace
2. Sample code
3. maven pom.xml file
4. maven assembly file

complete stack trace
```
 org.apache.kafka.streams.errors.StreamsException: Exception caught in process. taskId=0_4, processor=KSTREAM-SOURCE-0000000000, topic=kafka.config.change.notify, partition=4, offset=161, stacktrace=io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
      at io.grpc.Status.asRuntimeException(Status.java:537)
      at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:631)
      at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
      at com.one.two.three.GrpcClient.ImAliveConfig(GrpcClient.java:81)
      at com.one.two.three.SIA$RecordProcessor.lambda$process$0(SIA.java:280)
      at java.base/java.lang.Iterable.forEach(Iterable.java:75)
      at com.one.two.three.SIA$RecordProcessor.process(SIA.java:238)
      at com.one.two.three.SIA$RecordProcessor.process(SIA.java:230)
      at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
      at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
      at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
      at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
      at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
      at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
      at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:810)
      at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
      at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:810)
      at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:741)
      at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:97)
      at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:78)
      at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1747)
      at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:807)
      at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:617)
      at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:579)
 Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /127.0.0.1:50051
 Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
      at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
      at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
      at io.grpc.netty.shaded.io.netty.channel.unix.Socket.connect(Socket.java:351)
      at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
      at io.grpc.netty.shaded.io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:144)
      at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
      at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
      at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
      at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
      at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
      at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
      at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
      at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
      at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
      at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
      at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.base/java.lang.Thread.run(Thread.java:833)

      at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:767)
      at org.apache.kafka.streams.processor.internals.TaskExecutor.processTask(TaskExecutor.java:97)
      at org.apache.kafka.streams.processor.internals.TaskExecutor.process(TaskExecutor.java:78)
      at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:1747)
      at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:807)
      at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:617)
      at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:579)
 Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
      at io.grpc.Status.asRuntimeException(Status.java:537)
      at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:631)
      at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
      at com.one.two.three.GrpcClient.ImAliveConfig(GrpcClient.java:81)
      at com.one.two.three.SIA$RecordProcessor.lambda$process$0(SIA.java:280)
      at java.base/java.lang.Iterable.forEach(Iterable.java:75)
      at com.one.two.three.SIA$RecordProcessor.process(SIA.java:238)
      at com.one.two.three.SIA$RecordProcessor.process(SIA.java:230)
      at org.apache.kafka.streams.processor.internals.ProcessorAdapter.process(ProcessorAdapter.java:71)
      at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:157)
      at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forwardInternal(ProcessorContextImpl.java:290)
      at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:269)
      at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:228)
      at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
      at org.apache.kafka.streams.processor.internals.StreamTask.lambda$doProcess$1(StreamTask.java:810)
      at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:872)
      at org.apache.kafka.streams.processor.internals.StreamTask.doProcess(StreamTask.java:810)
      at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:741)
      ... 6 common frames omitted
 Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /127.0.0.1:50051
 Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol
      at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
      at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
      at io.grpc.netty.shaded.io.netty.channel.unix.Socket.connect(Socket.java:351)
      at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
      at io.grpc.netty.shaded.io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:144)
      at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
      at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
      at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
      at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
      at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
      at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
      at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
      at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
      at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
      at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
      at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
      at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
      at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
      at java.base/java.lang.Thread.run(Thread.java:833)
```

Sample code
```
    private ServiceGrpc.ServiceBlockingStub blockingStub;
    private final ManagedChannel managedChannel;
    public GrpcClient(String gRpcServer, int gRpcPort) {
        String finalGrpcServer = "127.0.0.1" ;
        finalGrpcServer.trim();
        int finalGrpcPort = 50051 ;
//        managedChannel = ManagedChannelBuilder.forAddress(finalGrpcServer,finalGrpcPort)
//                .usePlaintext()
//                .build();
        managedChannel = NettyChannelBuilder.forAddress(finalGrpcServer,finalGrpcPort)
                .usePlaintext()
                .build();
        this.blockingStub = ServiceGrpc.newBlockingStub (managedChannel);
    }

    public void ImAliveConfig (String cid, long Cfgid) {
            partialConfigRequest gRpcpartialConfigRequest;
            gRpcpartialConfigRequest = partialConfigRequest
                    .newBuilder()
                    .setCid(cid)
                    .setCfgids(Cfgid)
                    .build();
            this.blockingStub.partialConfig(gRpcpartialConfigRequest)
                            .forEachRemaining( asdf -> System.out.println("##### cid: "+ asdf.getCid()));
    }
```

pom.xml
```
    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <version>1.59.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.59.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>1.59.0</version>
        </dependency>
        <dependency> <!-- necessary for Java 9+ -->
            <groupId>org.apache.tomcat</groupId>
            <artifactId>annotations-api</artifactId>
            <version>6.0.53</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.14.2</version>
        </dependency>
    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.1</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <descriptors>
                        <descriptor>src/assembly/dep.xml</descriptor>
                    </descriptors>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.one.two.three.four</mainClass>
                        </manifest>
                    </archive>
                </configuration>
                <executions>
                    <execution>
                        <id>assemble-all</id> <!-- this is used for inheritance merges -->
                        <phase>package</phase> <!-- bind to the packaging phase -->
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.basedir}/../target/classes</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>
                        com.google.protobuf:protoc:3.24.0:exe:${os.detected.classifier}
                    </protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>
                        io.grpc:protoc-gen-grpc-java:${grpc.java.version}:exe:${os.detected.classifier}
                    </pluginArtifact>
                    <protoSourceRoot>
                        ${basedir}/src/main/proto/
                    </protoSourceRoot>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

src/assembly/dep.xml:
```
<assembly xmlns="http://maven.apache.org/ASSEMBLY/2.2.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/ASSEMBLY/2.2.0 http://maven.apache.org/xsd/assembly-2.2.0.xsd">
    <id>my-assembly</id>
    <formats>
        <format>jar</format>
    </formats>
    <containerDescriptorHandlers>
        <containerDescriptorHandler>
            <handlerName>metaInf-services</handlerName>
        </containerDescriptorHandler>
    </containerDescriptorHandlers>
</assembly>

```

**Comment by tarokon** [comment]
@ejona86 - 
Requesting you to please take a look at this issue and suggest a solution.

**Comment by YifeiZhuang** [comment]
Does't look like grpc issue but maven packing issue, could you try the [stackoverflow solution](
https://stackoverflow.com/questions/73286776/grpc-unsupportedaddresstypeexception-but-only-when-packaged-with-shadowjar)?

**Comment by tarokon** [comment]
I did refer to the mentioned stackoverflow solution and for `maven-assembly-plugin` I have already included the below mentioned code in `assembly.xml`. The same has been provided as my current state in the original question.

How do I resolve this issue ?

```
  <containerDescriptorHandlers>
    <containerDescriptorHandler>
      <handlerName>metaInf-services</handlerName>
    </containerDescriptorHandler>
  </containerDescriptorHandlers>
```

**Comment by tarokon** [comment]
I was able to resolve this issue of "Address family not supported by protocol".

As part of debugging, I untarred my jar file into a directory.
`jar xvf <jarfile>   <<<< jarfile = ${project.artifactId}-${project.version}-jar-with-dependencies
`

Below was the content of Name Resolver.
```
cat META-INF/services/io.grpc.NameResolverProvider
io.grpc.netty.shaded.io.grpc.netty.UdsNameResolverProvider
```

I modified this file to manually to have 
`io.grpc.internal.DnsNameResolverProvider
`

Created a dummy jar file
`jar -v --create --file ../dummy.jar --manifest=META-INF/MANIFEST.MF .
`

and ran that jar file and observed that issue got fixed.
`java -jar ./path/dummy.jar
`

Next stage was how to get this code change automated. So to my `src/main/resources` I added folder `META-INF/services`

To this `META-INF/services` folder I added a file `io.grpc.NameResolverProvider` which has a single line content `io.grpc.internal.DnsNameResolverProvider`

Now in pom.xml I removed `maven-assembly-plugin` and added `maven-shade-plugin` whose contents are as below.

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.5.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <transformers>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                        <mainClass>one.two.three.four</mainClass>
                    </transformer>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                </transformers>
                <outputDirectory>${project.basedir}/../target/classes</outputDirectory>
                <finalName>${project.artifactId}-${project.version}-jar-with-dependencies</finalName>
            </configuration>
        </execution>
    </executions>
</plugin>
```

After generating fat jar a.k.a uber jar, the jar with dependencies now has the following content in the jar and this has helped solve my issue of "Address family not supported by protocol".

before changes
```
cat META-INF/services/io.grpc.NameResolverProvider
io.grpc.netty.shaded.io.grpc.netty.UdsNameResolverProvider
```

after changes
```
cat META-INF/services/io.grpc.NameResolverProvider
io.grpc.internal.DnsNameResolverProvider
io.grpc.netty.shaded.io.grpc.netty.UdsNameResolverProvider
```
