### ISSUE TITLE
testNoDeadlockOnShutdown flaky since DelayedStream

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1089]
As seen in https://travis-ci.org/grpc/grpc-java/builds/82854873 (rebuild fixed)
```
io.grpc.internal.ManagedChannelImplTest > testNoDeadlockOnShutdown FAILED
    java.lang.NullPointerException: mockTransport returned null stream
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
        at io.grpc.internal.ClientCallImpl$DelayedStream.createStream(ClientCallImpl.java:468)
        at io.grpc.internal.ClientCallImpl$DelayedStream.access$900(ClientCallImpl.java:380)
        at io.grpc.internal.ClientCallImpl$DelayedStream$StreamCreationTask.run(ClientCallImpl.java:432)
        at io.grpc.internal.ClientCallImpl$DelayedStream.<init>(ClientCallImpl.java:442)
        at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:164)
        at io.grpc.internal.ManagedChannelImplTest.testNoDeadlockOnShutdown(ManagedChannelImplTest.java:298)
```

**Comment by ejona86** [comment]
Flaked on https://travis-ci.org/grpc/grpc-java/builds/83191873 (but logs lost due to rebuilding)

**Comment by zhangkun83** [comment]
The cause is that this test doesn't stub `mockTransport.newStream()`, so it returns `null`.
The flakiness is due to 2 reasons:
 1. In the test, `call.cancel()` is called right after `call.start()`. Inside `ClientCallImpl`, `newStream()` is called from the executor. If `cancel()` was called first, `newStream()` won't be called so it won't trigger the check.
 2. The transport is provided to `ClientCallImpl` asynchronously. `newStream()` may either be called from the test thread, or from executor. If it is called from executor, the error is logged to stderr and won't fail the test.
