### ISSUE TITLE
transportFailsOnStart flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1094]
Seen in https://travis-ci.org/grpc/grpc-java/builds/83191873 (logs lost)

```
io.grpc.internal.ManagedChannelImplTest > transportFailsOnStart FAILED
    org.mockito.exceptions.verification.TooLittleActualInvocations: 
    mockTransportFactory.newClientTransport();
    Wanted 2 times:
    -> at io.grpc.internal.ManagedChannelImplTest.transportFailsOnStart(ManagedChannelImplTest.java:236)
    But was 1 time:
    -> at io.grpc.internal.TransportSet$1.run(TransportSet.java:159)
        at io.grpc.internal.ManagedChannelImplTest.transportFailsOnStart(ManagedChannelImplTest.java:236)
```

**Comment by ejona86** [comment]
Another flake from transportFailsOnStart:
```
io.grpc.internal.ManagedChannelImplTest > transportFailsOnStart FAILED
    Wanted but not invoked:
    clientStream.setDecompressionRegistry(
        isA(io.grpc.DecompressorRegistry)
    );
    -> at io.grpc.internal.ManagedChannelImplTest.transportFailsOnStart(ManagedChannelImplTest.java:240)
    Actually, there were zero interactions with this mock.
        at io.grpc.internal.ManagedChannelImplTest.transportFailsOnStart(ManagedChannelImplTest.java:240)
```

**Comment by zhangkun83** [comment]
#1096 should fix the second flake. I couldn't reproduce the first flake locally.

**Comment by ejona86** [comment]
Closing because we've not seen the first flake in a while. Will reopen if we do.
