### ISSUE TITLE
A best way to handle io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by rickyma** [grpc/grpc-java#10962]
```
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 299.999957740s. Name resolution delay 0.000000000 seconds. [closed=[], open=[[remote_addr=xxxxxx/xxxxxx:yyyyy]]]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at org.apache.uniffle.proto.ShuffleServerGrpc$ShuffleServerBlockingStub.reportShuffleResult(ShuffleServerGrpc.java:814)
	at org.apache.uniffle.client.impl.grpc.ShuffleServerGrpcClient.doReportShuffleResult(ShuffleServerGrpcClient.java:698)
	at org.apache.uniffle.client.impl.grpc.ShuffleServerGrpcClient.reportShuffleResult(ShuffleServerGrpcClient.java:667)
	at org.apache.uniffle.client.impl.ShuffleWriteClientImpl.reportShuffleResult(ShuffleWriteClientImpl.java:716)
	at org.apache.spark.shuffle.writer.RssShuffleWriter.stop(RssShuffleWriter.java:462)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:60)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1556)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

What's the best way to handle io.grpc.StatusRuntimeException?
Do we have a method to accurately know the cause of the failure of sending a request? Is it due to the GRPC client or the GRPC server? Is it because of network congestion, or the connection limit has been reached? Or is the machine's CPU full?

**Comment by larry-safran** [comment]
There actually is some information in the message indicating where the problem may be located.

- Name resolution - basically no time, so not there
- closed=[] - haven't received a response from the server (as opposed to the server sending the DEADLINE_EXCEEDED, no connection exists or flow control having blocked sending)

The HTTP / TCP connection hasn't been closed, so the client has no information about what happened after it sent the message, just that it hasn't received a response.

**Comment by temawi** [comment]
I'll mention these two user guides as well in case they are helpful:
- [Error handling](https://grpc.io/docs/guides/error/)
- [Status codes](https://grpc.io/docs/guides/status-codes/)

**Comment by sergiitk** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.

**Comment by prajjwal-epifi** [comment]
We're also experiencing the same issue 
Sometimes, during user sessions, all RPCs of the apps suddenly throw DEADLINE_EXCEEDED errors. When the user kills and reopens the apps, they start working again. It's important to note that this doesn't happen every time (not reproducible)

any possible solution for the fix? @larry-safran @temawi

**Comment by larry-safran** [comment]
@prajjwal-epifi You mention "apps", is it multiple apps having the problem or just one app?  If multiple, do they all start working when one is restarted or the others continue getting errors?  Have you looked at the server logs to see if anything is being recorded around the time of the problem?  It may be something related to Android networking which is outside my area of expertise.

**Comment by prajjwal-epifi** [comment]
@larry-safran It is just one app (sorry for the typo). When I checked the server logs in Kibana, I couldn't find any logs for RPC calls when the app received DEADLINE_EXCEEDED errors, indicating that RPC calls were not reaching the server.
Additionally, I don't think it was a network issue because killing and reopening the app resolved this problem.

Do you have any suggested fixes for this issue? 🙏

**Comment by rickyma** [comment]
Why did the problem get resolved when I reduced the gRPC thread pool from 2000 to 200, and I no longer encountered DEADLINE_EXCEEDED? What is the reason behind this? @larry-safran @sergiitk @temawi
