### ISSUE TITLE
Unexpected encoding type returns status CANCELED rather than INTERNAL

### ISSUE THREAD

**Issue by drice-buf** [grpc/grpc-java#10970]
### What version of gRPC-Java are you using?

1.61.1

### What is your environment?
MacOS 13.6.4, Oracle OpenJDK version 21.0.2

### What did you expect to see?

RPC should return an `internal`error (code 13)

### What did you see instead?

RPC returns a `canceled` error (code 1)

### Steps to reproduce the bug

Send a request with `Grpc-Encoding: identity`

The following stack trace is generated:

```
WARNING: Exception processing message
io.grpc.StatusRuntimeException: INTERNAL: Can't decode compressed gRPC message as compression not configured
	at io.grpc.Status.asRuntimeException(Status.java:525)
	at io.grpc.internal.MessageDeframer.getCompressedBody(MessageDeframer.java:430)
	at io.grpc.internal.MessageDeframer.processBody(MessageDeframer.java:411)
	at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:276)
	at io.grpc.internal.MessageDeframer.request(MessageDeframer.java:162)
	at io.grpc.internal.AbstractStream$TransportState$1RequestRunnable.run(AbstractStream.java:233)
	at io.grpc.netty.NettyServerStream$TransportState$1.run(NettyServerStream.java:188)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Note that the exception is marked with code `INTERNAL`, however the client is receiving `CANCELED`.

**Comment by jhump** [comment]
A little more info on this: this is an edge case where one of the message frames has the "compressed" flag set in its 5-byte preface but the current encoding is "identity".

The expectation of an "internal" error comes from the set of test cases at the bottom of this doc on gRPC compression: https://github.com/grpc/grpc/blob/master/doc/compression.md#test-cases:
> * An ill-constructed message with its [Compressed-Flag bit](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#compressed-flag) set but lacking a [grpc-encoding](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#message-encoding) entry different from _identity_ in its metadata MUST fail with `INTERNAL` status, its associated description indicating the invalid Compressed-Flag condition.

**Comment by jhump** [comment]
Also, the grpc-java server is not actually serializing any status exception to trailers in this scenario. Instead, it is sending a RST_STREAM HTTP/2 frame with code CANCEL, which results in the client observing a "CANCELLED" error code.
