### ISSUE TITLE
DNS Resolver returns same IP address for 2 different instances

### ISSUE THREAD

**Issue by DanchoIvanov** [grpc/grpc-java#10981]
### What version of gRPC-Java are you using?
1.60.2

### What is your environment?

Linux Alpine with Eclipse Temurin JDK 11. I use Docker to create 3 containers with my application.
We also reproduce the issue with Azure and AWS deployments. They use Ubuntu instead of Alpine.

Every instance creates 2 RPC Clients (one for every of the other instances it has to talk to) that uses 4 stubs (2 blocking, 1 async and 1 future). With the client initialization it creates 1 long lived channel shared by all of the stubs.

Every instance creates a server that listens for request at certain address using the NettyServerBuilder.forAddress()

### What did you expect to see?
I use the deployment to stress test the application. The test restarts some of the containers. 
What I expect is after the restart the instance that is not restarted to be able to send messages to the restarted instances through the already instantiated channels.

### What did you see instead?
Sometimes instance that is not restarted starts sending 2 messages to the same node instead of 1 to each of them.
An interesting detail is that if I shutdown the channel and initialize a new one everything starts working again.

What I have tried so far:
- I turned off the dns cache. That did not fix the issue.
- I created interceptor that sign every request with its recipient and another one that throws exception if the message has a wrong recipient. This way I know when to reinitialize the channel. This is more of a workaround rather than a solution. It adds unnecessary complexity and it is not very stable.

### Steps to reproduce the bug
Not 100% sure if restarting the containers is what causes the issue and it does not reproduce every single time, but from what I see It often happens after some of the containers are restarted.

The logs bellow show that the instance is trying to send messages to the other two that are currently unavailable. Somehow the addresses are the same for the two instances (172.20.0.7:7300)

```
[ERROR] 2024-01-25 22:53:07,583 [gdb-2-search:7300-rpc-client-0 | c.o.g.r.g.RpcNodeClient] Unable to send streaming entry to gdb-2-search:7300 due to: 
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at common.GraphDBMDCExecutorBuilder.lambda$wrap$1(GraphDBMDCExecutorBuilder.java:200)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: gdb-2-search/172.20.0.7:7300
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

[ERROR] 2024-01-25 22:53:08,281 [gdb-3-search:7300-rpc-client-0 | c.o.g.r.g.RpcNodeClient] Unable to send streaming entry to gdb-3-search:7300 due to: 
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:537)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at common.GraphDBMDCExecutorBuilder.lambda$wrap$1(GraphDBMDCExecutorBuilder.java:200)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: gdb-3-search/172.20.0.7:7300
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ejona86** [comment]
Based on the exception, it sounds like each instance has a name like `gdb-X-search`, where X is 1, 2, or 3. What decides what is which instance? It seems like it'd be easy for 2 and 3 to get "renamed" if 1 is restarted. Then you are at the mercy of DNS caches in order to learn about the new IP address. Yes, you disabled DNS caching _at once place_, but lots of places cache so it is hard to get them all.

Which dns cache did you disable? What decides each instances' integer id?

As a test, I expect if you enable `server.maxConnectionAge(45, TimeUnit.SECONDS)` on server-side that it'd fix itself given a little bit of time. If that's what you see, then I do think it is "dns is not atomic" trouble.

**Comment by DanchoIvanov** [comment]
To stop the dns cache I set networkaddress.cache.ttl property to 0. From what I see, if not set it only caches for 30 seconds.

The instance name is a property that is set with the start of every container. So if you restart one or multiple containers the application instances started in them would get the same names as before. In other words, no they can not get renamed if 1 is restarted.

I will put your suggestion to a test and write back once I have a result.

**Comment by ejona86** [comment]
If the instance name is chosen when starting and there is no renumbering, then I'm not sure how you'd see the behavior you are seeing. My test can still help us debug. There's no real way for channels to get "confused" about the hostname they are getting IPs for. It is much more likely that DNS was misconfigured for a small period of time.

**Comment by ejona86** [comment]
The channel requests DNS when it exits idle (generally, the first RPC). The LB then uses any returned addresses to make connection(s). You're probably using the default, `pick_first`, which stops trying addresses once one of them works. After startup, the LB policy can ask DNS to re-resolve addresses. This is generally done when a connection is shut down/dies.

One server going down won't impact connections to another server. But on the channel the server went down, it will re-resolve DNS and reconnect. Apparently it was getting the wrong IP address when re-resolving. It could certainly get _too old_ of an address. That wouldn't be surprising. But in that case it would attempt to make a connection, fail, and re-resolve DNS occasionally. The maxConnectionAge setting is essentially causing the client to re-resolve DNS periodically.

**Comment by DanchoIvanov** [comment]
If I understand it correctly, no meter if it connects to the right server or not the connection gets killed at some point forcing the channel to create a new one which forces re-resolving. 

What if I want to trigger re-resolving on demand?
I assume one way to solve the problem is to implement my own NameResolver. I wonder if the ManagedChannel.enterIdle() could get the job done too?

**Comment by ejona86** [comment]
Yes, `enterIdle()` shuts down all connections and the name resolver, so the next RPC will get a fresh DNS result. Since DNS does seem to return the wrong results for a period of time, you probably shouldn't call it again if you called it within the last ~10 seconds or some such.

**Comment by DanchoIvanov** [comment]
I have implemented solution that moves the channel to idle state if there is no connection to my app instance or if the message is sent to wrong instance. I left it running tests through the weekend. When I checked it this morning I found it clogged with 548 threads 340 of witch are I/O dispatchers from the sun.nio.ch

`"I/O dispatcher 2941" #4871 prio=5 os_prio=0 cpu=15513.67ms elapsed=221030.90s tid=0x000077a7db1f2800 nid=0x13d0 runnable  [0x000077a7d217e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.22/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.22/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.22/SelectorImpl.java:124)
	- locked <0x000000074ab7e600> (a sun.nio.ch.Util$2)
	- locked <0x000000074ab7e5a8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.22/SelectorImpl.java:136)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.22/Thread.java:829)`

I have similar solution that shuts downs the channels instead of setting them idle. It also ran the test the whole weekend and everything seems to be fine there. 
So I was wondering If setting the channels to idle state could lead to this issue?

**Comment by ejona86** [comment]
`org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor`. That's not gRPC. I don't know what would cause that. If RPCs hanging might cause that, then you might check if enabling keepalive on your channels (e.g., [`channelBuilder.keepAliveTime(5, MINUTES)`](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime(long,java.util.concurrent.TimeUnit))) changes anything?

**Comment by DanchoIvanov** [comment]
I've managed to find and fix the issue. One of the stub calls returns an Iterator which wasn't handled properly. It was working fine with my other solution because I reinitialize the whole rpc client (the stubs and the channel that it uses.)

**Comment by ejona86** [comment]
Glad to hear. Seems like this is resolved. If not, comment, and it can be reopened.
