### ISSUE TITLE
UNIMPLEMENTED Error when trying to run android app with C++ Server

### ISSUE THREAD

**Issue by JChunyu** [grpc/grpc-java#10996]
proto: 
```
syntax = "proto3";

import "service_version.proto";
import "mfw_common.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/descriptor.proto";

package Mfw.Api;

service ServiceRegistry {
  option (service_version).major = 2;
  option (service_version).minor = 2;

  rpc Connect(google.protobuf.Empty) returns(stream google.protobuf.Empty){}

  rpc RegisterAudioSourceProviderService(Common.ServiceReference) returns (Common.Result){}
  rpc RegisterBrowsingService(Common.ServiceReference) returns (Common.Result){}
  rpc RegisterSearchProviderService(Common.ServiceReference) returns (Common.Result){}

  rpc UnregisterAudioSourceProviderService(Common.ServiceReference) returns (Common.Result){}
  rpc UnregisterBrowsingService(Common.ServiceReference) returns (Common.Result){}
  rpc UnregisterSearchProviderService(Common.ServiceReference) returns (Common.Result){}
}
```
client code:
```
class ServiceRegistryClient {
    var mStub: ServiceRegistryGrpc.ServiceRegistryStub
    private var mServiceRegistryChannel: ManagedChannel? = null
    companion object {
        private val TAG = "GRPC"
    }
    init {
        initChannel()
        mStub = ServiceRegistryGrpc.newStub(mServiceRegistryChannel).withWaitForReady()
    }

    private fun initChannel() {
        mServiceRegistryChannel =
            NettyChannelBuilder.forAddress(SELF_GATEWAY_IP, MFW_SERVICE_REGISTRY_PORT)
                .keepAliveTime(KEEP_ALIVE_TIME.toLong(), TimeUnit.MILLISECONDS)
                .keepAliveTimeout(KEEP_ALIVE_TIMEOUT.toLong(), TimeUnit.MILLISECONDS)
                .keepAliveWithoutCalls(true)
                .usePlaintext()
                .build()
        Log.d(TAG, "Channel created for ServiceRegistryChannel")
    }

    fun connect() {
        Log.d(TAG, "Connect called")
        mStub.connect(Empty.newBuilder().build(), object : StreamObserver<Empty> {
            override fun onNext(value: Empty) {
                Log.d(TAG, "Connect onNext $value")
            }

            override fun onError(t: Throwable) {
                Log.d(TAG, "Connect onError " + t.message)
                t.printStackTrace()
            }

            override fun onCompleted() {
                Log.d(TAG, "Connect onCompleted")
            }
        })

    }
    // ....
}
```
call:
```
    private fun test() {
        val serviceRegistryClient = ServiceRegistryClient()
        serviceRegistryClient.connect()
    }
```
Gradle config(proto/grpc version):
```
protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.19.4' }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.45.2'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java {}
            }
            task.plugins {
                grpc {}
            }
        }
    }
}

dependencies {
    // grpc
    implementation 'javax.annotation:javax.annotation-api:1.2'
    implementation "io.grpc:grpc-android:1.45.2"
    implementation "io.grpc:grpc-okhttp:1.45.2"
    implementation 'io.grpc:grpc-netty:1.45.2'
    implementation "io.grpc:grpc-protobuf:1.45.2"
    implementation "io.grpc:grpc-stub:1.45.2"
    implementation "io.grpc:grpc-kotlin-stub:1.1.0"
    implementation "io.grpc:grpc-testing:1.45.2"
    implementation "org.mockito:mockito-core:1.9.5"
    testImplementation "androidx.arch.core:core-testing:2.1.0"
    // ... 
}
``` 
when I build a local java server, it success, but when I use this client to connect to C++ implement Server, it show some error:
```
io.grpc.StatusRuntimeException: UNIMPLEMENTED
at io.grpc.Status.asRuntimeException(Status.java:533)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
```

**Comment by temawi** [comment]
The first thing to address here is that you are directly using `NettyChannelBuilder` to create your managed channel. Netty is is not intended for Android, the OkHttp transport should be used instead. If you just use `ManagedChannelBuilder.forAddress()` the right type should get selected for you.

I would make that change first and then we can see if you have further issues.

**Comment by JChunyu** [comment]
> The first thing to address here is that you are directly using `NettyChannelBuilder` to create your managed channel. Netty is is not intended for Android, the OkHttp transport should be used instead. If you just use `ManagedChannelBuilder.forAddress()` the right type should get selected for you.
> 
> I would make that change first and then we can see if you have further issues.

thanks i will try it

**Comment by JChunyu** [comment]
the reason is server that do not implement full function，some api can call success
