### ISSUE TITLE
empty_stream interop tests fails against Go server

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-java#1113]
empty_stream, java client, go server

```
Running test empty_stream
Oct 09, 2015 10:59:50 PM io.grpc.internal.TransportSet$1 run
INFO: Created transport 'io.grpc.netty.NettyClientTransport@332c01ed
Oct 09, 2015 10:59:53 PM io.netty.util.internal.ThreadLocalRandom getInitialSeedUniquifier
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entropy?
Oct 09, 2015 10:59:53 PM io.grpc.internal.TransportSet$TransportListener transportReady
INFO: Transport 'io.grpc.netty.NettyClientTransport@332c01ed is ready
Oct 09, 2015 10:59:55 PM io.grpc.internal.TransportSet$TransportListener transportShutdown
INFO: Transport 'io.grpc.netty.NettyClientTransport@332c01ed is being shutdown
Exception in thread "main" Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractTransportTest.emptyStream(AbstractTransportTest.java:320)

However, there were other interactions with this mock:
streamObserver.onError(
    io.grpc.StatusRuntimeException: INTERNAL: Invalid content-type: null
);
-> at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:266)


	at io.grpc.testing.integration.AbstractTransportTest.emptyStream(AbstractTransportTest.java:320)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:228)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:207)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:80)
Shutting down

FLAKE: cloud_to_cloud:java:go_server:empty_stream [ret=1, pid=31237]
```

https://grpc-testing.appspot.com/job/gRPC_interop_master/180/console

**Comment by jtattermusch** [comment]
I see this one on almost all the test runs and it's one of 3 tests cases that are preventing the basic interop test suite from becoming green. Can we treat this as P0 or P1 as part of the effort to make our tests green?

**Comment by jtattermusch** [comment]
@ejona86, feel free to reassign.

**Comment by madongfly** [comment]
@iamqizhao
Seems the problem is that:
Java client requires content-type in trailer if there was no header received, but Go server only fill content-type in header.

So for empty-stream which only sends trailer to client, Java client failed.

But I'm not sure whether we should loose java's requirement, or make other languages stricter.

**Comment by ejona86** [comment]
Both Response-Headers and Trailers-Only require Content-Type. Go needs to be fixed. Filed grpc/grpc-go#398
