### ISSUE TITLE
Java Security Provider unsupported for SslProvider: OPENSSL

### ISSUE THREAD

**Issue by laglangyue** [grpc/grpc-java#11219]
my machine is `m2 apple`

```java
                builder.overrideAuthority(channelOptions.getAuthorityHost())
                        .sslContext(GrpcSslContexts.forClient()
                                .sslProvider(OPENSSL)
                                .trustManager(new ByteArrayInputStream(channelOptions.getCertChain()))
                                .build());
```

I get a excetpion

```java
java.lang.IllegalArgumentException: Java Security Provider unsupported for SslProvider: OPENSSL
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.verifyNullSslContextProvider(SslContext.java:488)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:826)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:576)
```

then I install openssl
```java
OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)
```
but I can't resolve the exception

**Comment by kannanjgithub** [comment]
Is that the actual code producing the exception, because the Netty SslContext created by calling GrpcSslContexts.forClient() doesn't have a SslContextProvider set. Unless you do something like

```
GrpcSslContexts.forClient()
            .sslProvider(OPENSSL)
            .trustManager(new ByteArrayInputStream(channelOptions.getCertChain()))
            **.sslContextProvider(someJavaContextProvider)**
            .build()

```
you shouldn't be facing that exception.
