### ISSUE TITLE
Pumping to version 1.65.2 from version 1.62.2 gave the following error 'failed with code: BACKEND_FAILURE_URL_UNREACHABLE'

### ISSUE THREAD

**Issue by EgHubs** [grpc/grpc-java#11414]
### What version of gRPC-Java are you using?
1.65.2
### What is your environment?

MacOS deployed to Gcloud 
`  implementation group: 'org.bouncycastle', name: 'bcprov-jdk18on', version: '1.78.1'`
### What did you expect to see?
No error as for the previous version with no other changes!
### What did you see instead?
The following error
```
WARNING 2024-07-26T13:33:33.447118Z Failed startup of context c.g.a.r.j.AppEngineWebAppContext@dfd184f{/,file:///workspace/,UNAVAILABLE}{/workspace} javax.servlet.ServletException: SmartHomeServlet==com.example.SmartHomeServlet@6f391afd{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///workspace/WEB-INF/quickstart-web.xml,STARTED} at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650) at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415) at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750) at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:774) at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.startWebapp(AppEngineWebAppContext.java:274) at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916) at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:218) at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) at com.google.apphosting.runtime.jetty9.AppVersionHandlerFactory.doCreateHandler(AppVersionHandlerFactory.java:225) at com.google.apphosting.runtime.jetty9.AppVersionHandlerFactory.createHandler(AppVersionHandlerFactory.java:125) at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:80) at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:226) at com.google.apphosting.runtime.Requ…
  {
    "textPayload": "Failed startup of context c.g.a.r.j.AppEngineWebAppContext@dfd184f{/,file:///workspace/,UNAVAILABLE}{/workspace}
javax.servlet.ServletException: SmartHomeServlet==com.example.SmartHomeServlet@6f391afd{jsp=null,order=1,inst=true,async=false,src=DESCRIPTOR:file:///workspace/WEB-INF/quickstart-web.xml,STARTED}
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.startWebapp(AppEngineWebAppContext.java:274)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doStart(AppEngineWebAppContext.java:218)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerFactory.doCreateHandler(AppVersionHandlerFactory.java:225)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerFactory.createHandler(AppVersionHandlerFactory.java:125)
	at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:80)
	at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:226)
	at com.google.apphosting.runtime.RequestRunner.dispatchServletRequest(RequestRunner.java:349)
	at com.google.apphosting.runtime.RequestRunner.dispatchRequest(RequestRunner.java:234)
	at com.google.apphosting.runtime.RequestRunner.run(RequestRunner.java:200)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:273)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.eclipse.jetty.server.handler.ContextHandler$StaticContext.createInstance(ContextHandler.java:2902)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createInstance(ServletContextHandler.java:1299)
	at org.eclipse.jetty.server.handler.ContextHandler$StaticContext.createServlet(ContextHandler.java:2919)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1202)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:592)
	... 27 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.example.MySmartHomeApp
	at com.example.SmartHomeServlet.<init>(SmartHomeServlet.java:46)
	... 37 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: io/grpc/InternalGlobalInterceptors [in thread \"Request\"]
	at io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors(ManagedChannelImplBuilder.java:684)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:672)
	at io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:272)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:462)
	at com.google.api.gax.grpc.ChannelPool.<init>(ChannelPool.java:107)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:85)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:256)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:250)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:226)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:152)
	at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:126)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:92)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:84)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:602)
	at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:413)
	at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:78)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:75)
	at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:68)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:582)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:55)
	at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:32)
	at com.google.firebase.cloud.FirestoreClient$FirestoreInstances.lambda$get$0(FirestoreClient.java:150)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at com.google.firebase.cloud.FirestoreClient$FirestoreInstances.get(FirestoreClient.java:150)
	at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:121)
	at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:98)
	at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:83)
	at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:68)
	at com.example.MyDataStore.<init>(MyDataStore.java:110)
	at com.example.MyDataStore.<clinit>(MyDataStore.java:37)
	at com.example.MySmartHomeApp.<clinit>(MySmartHomeApp.java:44)
	... 38 more
",
    "insertId": "66a3a5ad0006d28e11067646",
    "resource": {
      "type": "gae_app",
      "labels": {
        "version_id": "20240726t163131",
        "zone": "eu5",
        "project_id": "projName",
        "module_id": "default"
      }
    },
    "timestamp": "2024-07-26T13:33:33.447118Z",
    "severity": "WARNING",
    "labels": {
      "clone_id": "0087244a804b2fdc3ffc4454dc81c8bdbfd0b304e06734d53f6770e7620de3b5197d823bc59687ad7d8d227ec08241b7269b29d0b6d0322d5fe5289976ceccaff7"
    },
    "logName": "projects/projName/logs/%2Fvar%2Flog%2Fapp",
    "trace": "projects/projName/traces/3de3b6d90e8fe87fd83955074e253e72",
    "sourceLocation": {
      "file": "JettyLogger.java",
      "line": "45",
      "function": "com.google.apphosting.runtime.jetty9.JettyLogger.warn"
    },
    "receiveTimestamp": "2024-07-26T13:33:33.770704138Z",
    "spanId": "0c5ce8b3cf0c7876"
  }
failed with code: BACKEND_FAILURE_URL_UNREACHABLE
```

### Steps to reproduce the bug

only changed to the newer version from the old 1.62.2 one and this happened
also tried on 1.64.2 and the same error
1.63.2 works as 1.62.2
64 and 65 I get that error

**Comment by kannanjgithub** [comment]
The actual underlying error seen in the above stacktrace is 

java.lang.NoClassDefFoundError: io/grpc/InternalGlobalInterceptors [in thread "Request"]\n\tat io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors(ManagedChannelImplBuilder.java:684)

[io.grpc.InternalGlobalInterceptors](https://github.com/grpc/grpc-java/blob/v1.62.x/api/src/main/java/io/grpc/InternalGlobalInterceptors.java) [was there](https://github.com/grpc/grpc-java/blob/v1.62.x/api/src/main/java/io/grpc/InternalGlobalInterceptors.java) in 1.62.x but not in 1.65.x.  ManagedChannelImplBuilder [in 1.62.x](https://github.com/grpc/grpc-java/blob/v1.62.x/core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java) was using io.grpc.InternalGlobalInterceptors but not the ManagedChannelImplBuilder [in 1.65.x](https://github.com/grpc/grpc-java/blob/v1.65.x/core/src/main/java/io/grpc/internal/ManagedChannelImplBuilder.java).
You seem to have only bumped grpc-api version but not of grpc-core. That needs to be bumped also.
