### ISSUE TITLE
Header size exceeded max allowed size (10240)

### ISSUE THREAD

**Issue by naliniranjan82** [grpc/grpc-java#11430]
Hi ,

I am getting error when i am passing metadata around 16KB while doing GRPC API call.

I try all possible option like declaring  `grpc.server.maxInboundMetadataSize=30KB` into application.properties file 

write custom configuration like :    

 ```
@Configuration
public class GrpcServerConfig {

  @Autowired
  private GrpcServerProperties grpcServerProperties;

  @Bean
  public GrpcServerConfigurer grpcServerConfigurer() {
    return serverBuilder -> {
      if (serverBuilder instanceof ServerBuilder) {
        ((ServerBuilder<?>) serverBuilder).maxInboundMetadataSize(
            (int) grpcServerProperties.getMaxInboundMetadataSize().toBytes()
        );
      }
    };
  }
}
```

The value reflect when server start what i have define into properties file ..But we are getting error when we call GRPC API.

Error : 
```
o.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Header size exceeded max allowed size (10240)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:245)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader$HeadersBlockBuilder.headerSizeExceeded(DefaultHttp2FrameReader.java:684)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader$HeadersBlockBuilder.addFragment(DefaultHttp2FrameReader.java:700)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:474)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Can someone please help me to come out from this issue?

**Comment by ejona86** [comment]
> But we are getting error when we call GRPC API.

Where are you seeing that error you provided? If you are seeing it on the client, you need to set `maxInboundMetadataSize()` on the channel builder. The receiver has to allow the increased size, and both the client and server are receivers (at different times).

**Comment by naliniranjan82** [comment]
Thank you so much for your quick response.

Error i am seeing into server side. Client side I have define grpc.server.maxInboundMetadataSize=30KB. Is it not sufficient ?

In fact when i am testing  GRPC API through postman while passing metadata size around 16KB i am seeing error into server log like above one. 
 your quick response will help me to conclude ongoing issue.

**Comment by ejona86** [comment]
> Error i am seeing into server side. Client side I have define grpc.server.maxInboundMetadataSize=30KB. Is it not sufficient ?

The _receiver_ is what matters; both clients and servers receive metadata. If you see the error on server-side, the client is sending something too large or the server needs to have its maxInboundMetadataSize adjusted.

**Comment by naliniranjan82** [comment]
Thank for your response.

I am trying to test application through postman via GRPC request where i have pass Metadata more than 16k..in that case client is postman and our application gives above error. I have below configuration into my application.

`@Configuration
public class GrpcServerConfig {
  private static final int MAX_INBOUND_HEADER_SIZE = 60 * 1024;

  @Bean
  public GrpcServerConfigurer grpcServerConfigurer() {
    return serverBuilder -> {
      if (serverBuilder instanceof NettyServerBuilder) {
        ((NettyServerBuilder) serverBuilder).maxInboundMetadataSize(MAX_INBOUND_HEADER_SIZE);
      }
    };
  }
}`


**grpc-netty version 1.59.1**

**Comment by kannanjgithub** [comment]
Can you log the postman request sent along with the headers? It may be that the extra byes come from other headers that you not aware of that causes the 60 kb size to be exceeded.

**Comment by ejona86** [comment]
> in that case client is postman 

If your server is the sender then you need to configure postman. We don't know how to do that. You are needing to change HTTP/2's MAX_HEADER_LIST_SIZE for the postman grpc client.

**Comment by ejona86** [comment]
Seems like this is resolved as best as we are able. If not, comment, and it can be reopened.

**Comment by naliniranjan82** [comment]
Still i am facing same issue not able to figure out where we are doing wrong. I try to Intercept metadata with net.devh.boot.grpc.client.interceptor.GrpcGlobalClientInterceptor annotation not able to do so.
After that i try to intercept call with io.grpc.ClientInterceptor interface but not able to do so. 

Looking for your suggestion how can we override the grpc.server.maxInboundMetadataSize=30KB.

**Comment by ejona86** [comment]
This can't be fixed from the server-side, except for reducing the metadata size. You need to configure the client, postman. The receiver specifies the limit.

**Comment by naliniranjan82** [comment]
JIRA has been reported through client which is one of the JAVA application. For my debugging purpose i have start validating through postman.

And client will have below configuration 
Create manageChanel like
```
public ManagedChannel profileServiceManagedChannel(
      @Value("${grpc.client.profile-service.address}") String host) {
    return getManagedChannel(host);
  }

  ManagedChannel getManagedChannel(String host) {
    ManagedChannelBuilder<?> managedChannelBuilder = ManagedChannelBuilder.forTarget(host);
    if (host.contains(localHost)) {
      managedChannelBuilder.usePlaintext();
    }
    return managedChannelBuilder
        .keepAliveTime(keepAliveSeconds, TimeUnit.SECONDS)
        .maxRetryAttempts(maxRetryAttempts)
        .intercept(clientHeadersInterceptor)
        .maxInboundMetadataSize(maxInboundMetadataSize) // 60*1024
        .build();
  }
```
and that managedChannel we have used to create blocking stub object
```
profileAccessServiceBlockingStub =
        ProfileAccessServiceGrpc.newBlockingStub(profileServiceManagedChannel);
```

and with profileAccessServiceBlockingStub  object application call GRPC API 

Server application will have configuration like below:

```
@Configuration
public class GrpcServerConfig {
  private static final int MAX_INBOUND_HEADER_SIZE = 60 * 1024;

  @Bean
  public GrpcServerConfigurer grpcServerConfigurer() {
    return serverBuilder -> {
      if (serverBuilder instanceof NettyServerBuilder) {
        ((NettyServerBuilder) serverBuilder).maxInboundMetadataSize(MAX_INBOUND_HEADER_SIZE);
      }
    };
  }
}```

**Comment by ejona86** [comment]
What is the network flow from the client to the server? gRPC Java → gRPC Java? Or are there any proxies involved?

Have you confirmed your GrpcServerConfigurer is being executed?

**Comment by naliniranjan82** [comment]
client server communication gRPC-java--->gRPC Java via envoy, But envoy just decode metadata  value(which is base64 encoded)

Have you confirmed your GrpcServerConfigurer is being executed? --> yes when we start application during that time i could see that value associated with that object

**Comment by kannanjgithub** [comment]
>>> After that i try to intercept call with io.grpc.ClientInterceptor interface but not able to do so.

Can you elaborate what is the problem you faced here? I assume you were trying to log the headers being sent.

**Comment by naliniranjan82** [comment]
> > > > After that i try to intercept call with io.grpc.ClientInterceptor interface but not able to do so.
> 
> Can you elaborate what is the problem you faced here? I assume you were trying to log the headers being sent.

yes i am trying to log header size which client is sending while calling GRPC API. But actual issue is header size which i am not able to find solution.

**Comment by naliniranjan82** [comment]
log is not getting printed into server application.. I try all the way to print metadata into application side but not able to do so..

The reason to not do so it failed well before request coming to application interceptor.

**Comment by kannanjgithub** [comment]
You say you are logging the outgoing metadata header in the io.grpc.ClientInterceptor but say log is not getting printed into server application. ClientInterceptor is on the client application.

**Comment by naliniranjan82** [comment]
> You say you are logging the outgoing metadata header in the io.grpc.ClientInterceptor but say log is not getting printed into server application. ClientInterceptor is on the client application.

sorry about it if i am not able to put my concern appropriately. I mean to say trying to print client metadata into server application where i am not able to do  ..

**Comment by ejona86** [comment]
If "Header size exceeded max allowed size (10240)" is happening on the grpc server, then there are things happening in your application or a framework. gRPC defaults to 8 kB, so this error saying 10 kB means some configuration is taking place. A quick look at grpc-spring didn't show anything setting 10 kB by default, so I suspect your application is setting it to 10 kB. You might ask the grpc-spring folks where to look, but it still seems out of grpc-java's hands.

`serverBuilder.maxInboundMetadataSize()` is the correct call, and beyond that it is hard for us to help.

**Comment by naliniranjan82** [comment]
Thank you so much to all of you for  your support.

after adding grpc.netty-server.max-inbound-metadata-size=60KB it started working. I don't understand why it was not working with grpc.server.maxInboundMetadataSize= 60KB
