### ISSUE TITLE
Missing reflection configuration in GraalVM Native Image for sofa-jraft.

### ISSUE THREAD

**Issue by DioxideCN** [grpc/grpc-java#11515]
I am working with Nacos, which uses SOFA-JRaft for state synchronization and communication in a cluster. SOFA-JRaft relies on gRPC for asynchronous communication by creating a gRPC `Channel`. Previously, when building as a GraalVM Native Image, the channel could not be created due to a missing class `io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.class`. I have already resolved that issue.

Currently, the problem arises during communication. I am encountering the following exception, which suggests an issue in establishing a connection:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:564)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:72)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:729)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:736)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:680)
	at io.grpc.internal.RetriableStream$4.run(RetriableStream.java:843)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
	at io.grpc.internal.RetriableStream.safeCloseMasterListener(RetriableStream.java:838)
	at io.grpc.internal.RetriableStream.access$2200(RetriableStream.java:55)
	at io.grpc.internal.RetriableStream$Sublistener.closed(RetriableStream.java:1041)
	at io.grpc.internal.DelayedStream$DelayedStreamListener$4.run(DelayedStream.java:510)
	at io.grpc.internal.DelayedStream$DelayedStreamListener.drainPendingCallbacks(DelayedStream.java:535)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:187)
	at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
	at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:296)
	at io.grpc.internal.ManagedChannelImpl.updateSubchannelPicker(ManagedChannelImpl.java:810)
	at io.grpc.internal.ManagedChannelImpl.access$5000(ManagedChannelImpl.java:124)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1UpdateBalancingState.run(ManagedChannelImpl.java:1396)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:94)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:126)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:587)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyGracefulShutdown(ClientTransportLifecycleManager.java:64)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:70)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyTerminated(ClientTransportLifecycleManager.java:92)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:302)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientTransport$5.operationComplete(NettyClientTransport.java:296)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:110)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.failWrites(WriteBufferingAndExceptionHandler.java:243)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.access$100(WriteBufferingAndExceptionHandler.java:43)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:152)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler$1ConnectListener.operationComplete(WriteBufferingAndExceptionHandler.java:148)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.12/java.lang.Thread.run(Thread.java:842)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:885)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:860)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: nacos3/172.18.0.3:7848
Caused by: java.net.ConnectException: Connection refused
	at java.base@17.0.12/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base@17.0.12/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base@17.0.12/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.12/java.lang.Thread.run(Thread.java:842)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:885)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:860)
```

The error occurs after the `asyncUnaryCall` is invoked in JRaft. Here is the relevant code:

```java
@Override
public void invokeAsync(final Endpoint endpoint, final Object request, final InvokeContext ctx,
                        final InvokeCallback callback, final long timeoutMs) {
    Requires.requireNonNull(endpoint, "endpoint");
    Requires.requireNonNull(request, "request");

    final Executor executor = callback.executor() != null ? callback.executor() : DirectExecutor.INSTANCE;

    final Channel ch = getCheckedChannel(endpoint);
    if (ch == null) {
        executor.execute(() -> callback.complete(null, new RemotingException("Fail to connect: " + endpoint)));
        return;
    }
    LOG.info("[?] ch build success. ch type: {}, request type: {}",
            ch.getClass().getName(), request.getClass().getName());

    final MethodDescriptor<Message, Message> method = getCallMethod(request);
    LOG.info("[?] method, full name: {}, service name: {}",
            method.getFullMethodName(), method.getServiceName());
    final CallOptions callOpts = CallOptions.DEFAULT.withDeadlineAfter(timeoutMs, TimeUnit.MILLISECONDS);
    LOG.info("[?] callOpts, authority: {}, compressor: {}",
            callOpts.getAuthority(), callOpts.getCompressor());

    ClientCalls.asyncUnaryCall(ch.newCall(method, callOpts), (Message) request, new StreamObserver<Message>() {

        @Override
        public void onNext(final Message value) {
            LOG.info("[-] onNext");
            executor.execute(() -> callback.complete(value, null));
        }

        @Override
        public void onError(final Throwable throwable) {
            LOG.error("[!] onError", throwable);
            executor.execute(() -> callback.complete(null, throwable));
        }

        @Override
        public void onCompleted() {
            // NO-OP
            LOG.info("[*] onCompleted");
        }
    });
}
```

I suspect that the issue stems from gRPC using reflection during the channel creation process. However, I am unable to trace these processes fully, which prevents me from identifying which reflection classes need to be collected. I am seeking guidance from the gRPC community on how to address this issue and understand the reflection requirements during the connection creation in GraalVM Native Image. Any assistance would be greatly appreciated.

Thank you very much for your help.

**Comment by kannanjgithub** [comment]
Nothing in the stacktrace suggests an issue with reflecting the method classes. It is showing connection refused. Have you checked if the service you are trying to connect to is available?

**Comment by DioxideCN** [comment]
I am currently testing in an environment consisting of a cluster formed by three Java versions of Nacos and one Nacos compiled with native image. The three Java versions of Nacos can form a cluster normally, but the native image version of Nacos fails to join the cluster. Initially, I suspected that there might be an issue with the request message body transmitted via gRPC or that the response message body was not received, but after inspecting with tcpdump, these assumptions were ruled out. I tried to trace the code, and the response is received in the` onMessage` method of `io.grpc.stub.ClientCalls`, but I am unable to further debug using GDB to check whether it has been correctly converted into an object.

**Comment by DioxideCN** [comment]
Normally, the code `ListenableFuture<Payload> responseFuture = requestBlockingStub.request(grpcRequest);` sends a request to the gRPC channel, which then sends the request and receives the response. The response is received at the lowest level in the `onMessage` method of the `GrpcClient`. Since the request is a `ServerCheckRequest`, the expected response should be a `ServerCheckResponse`. In `ClientCalls`'s `onMessage` method, the `value` parameter should be this `ServerCheckResponse`, and subsequently, this `value` is set into the `AbstractFuture`'s `value` field (achieved through the casValue method). This value is eventually retrieved externally by calling `AbstractFuture.get`.

```java
@Override
public void onMessage(RespT value) {
	if ("com.alibaba.nacos.api.grpc.auto.Payload".equals(value.getClass().getName())) {
		try {
			Class<?> clazz = Class.forName("com.alibaba.nacos.common.remote.client.grpc.GrpcUtils");
			Method parseMethod = clazz.getDeclaredMethod("parse", value.getClass());
			parseMethod.setAccessible(true);
			Object invoked = parseMethod.invoke(null, value);
			// print log here
			logger.log(Level.INFO, "[?] response: " + invoked.getClass().getName() + "#" + invoked.toString());
		} catch (ClassNotFoundException | NoSuchMethodException | IllegalAccessException | InvocationTargetException ignored) {
		}
	} else {
       		System.out.println("[!] onMessage received not-Payload-type message: " + clazzName);
	}

	if (this.isValueReceived) {
		throw Status.INTERNAL.withDescription("More than one value received for unary call").asRuntimeException();
	}
	this.value = value;
	this.isValueReceived = true;
}
```

While I believe my understanding of the `onMessage` part is correct, I'm not entirely sure about the way `AbstractFuture` handles the `value`. However, I am certain that `onMessage` is a crucial step and must be called, as it is responsible for receiving the response. At a higher level, this method is called through `ClientCallImpl`'s `messagesAvailable`, which further relies on `MessageDeframer`'s `processBody` method to create listeners that repeatedly check if `message = producer.next()` is non-null and then forwards the message.

After the modification, during the normal startup process of Nacos, the corresponding logs would be printed as follows:

```log
INFO Nacos is starting...
INFO [?] response: com.alibaba.nacos.api.remote.response.ServerCheckResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
INFO [?] response: com.alibaba.nacos.api.remote.response.ServerCheckResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
INFO [?] response: com.alibaba.nacos.api.remote.response.ServerCheckResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
INFO Nacos is starting...
INFO Nacos is starting...
INFO [?] response: com.alibaba.nacos.naming.cluster.remote.response.DistroDataResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
INFO Nacos started successfully in cluster mode. use external storage
INFO [?] response: com.alibaba.nacos.api.remote.response.HealthCheckResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
INFO [?] response: com.alibaba.nacos.api.remote.response.HealthCheckResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
INFO [?] response: com.alibaba.nacos.core.cluster.remote.response.MemberReportResponse#Response{resultCode=200, errorCode=0, message='null', requestId='null'}
```

However, after packaging as a Native Image, the `onMessage` method from `io.grpc.stub.ClientCalls` at the lowest level is not being called (the expected log output defined inside `onMessage` is missing during startup). I have currently traced the issue to this step, but I am unable to further pinpoint the problem within the `io.grpc.internal` layer.

**Comment by DioxideCN** [comment]
Fixed with GraalVM problem.
