### ISSUE TITLE
Caused by: java.io.IOException: FRAME_SIZE_ERROR: 4740180

### ISSUE THREAD

**Issue by chengxuyuanxiaoka** [grpc/grpc-java#11516]
```
implementation 'io.grpc:grpc-protobuf:1.66.0'
implementation 'io.grpc:grpc-stub:1.66.0'
implementation 'com.google.protobuf:protobuf-java:1.66.0'
implementation 'com.google.protobuf:protobuf-java-util:3.21.8'
implementation 'io.grpc:grpc-okhttp:1.66.0'
```

error:
```
RPC failed: Status{code=INTERNAL, description=error in frame handler, cause=java.io.IOException: FRAME_SIZE_ERROR: 4740180
2024-09-09 20:31:02.589 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:599)
2024-09-09 20:31:02.589 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:49)
2024-09-09 20:31:02.589 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:139)
2024-09-09 20:31:02.589 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1107)
2024-09-09 20:31:02.590 10527-10615 System.err              com.demo               W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024-09-09 20:31:02.590 10527-10615 System.err              com.demo               W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-09-09 20:31:02.590 10527-10615 System.err              com.demo               W      at java.lang.Thread.run(Thread.java:1012)
2024-09-09 20:31:02.590 10527-10615 System.err              com.demo               W  }
2024-09-09 20:31:02.591 10527-10615 System.err              com.demo               W  io.grpc.StatusRuntimeException: INTERNAL: error in frame handler
2024-09-09 20:31:02.592 10527-10615 System.err              com.demo               W      at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
2024-09-09 20:31:02.593 10527-10615 System.err              com.demo               W      at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
2024-09-09 20:31:02.593 10527-10615 System.err              com.demo               W      at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
2024-09-09 20:31:02.594 10527-10615 System.err              com.demo               W      at com.demo.communication.protocol.CommunicationServiceGrpc$CommunicationServiceBlockingStub.authToken(CommunicationServiceGrpc.java:601)
2024-09-09 20:31:02.595 10527-10615 System.err              com.demo               W      at com.demo.GrpcClientUtils.callAuthToken(GrpcClientUtils.java:68)
2024-09-09 20:31:02.596 10527-10615 System.err              com.demo               W      at com.demo.MainActivity.doUserLogin(MainActivity.java:506)
2024-09-09 20:31:02.597 10527-10615 System.err              com.demo               W      at com.demo.MainActivity.access$300(MainActivity.java:98)
2024-09-09 20:31:02.598 10527-10615 System.err              com.demo               W      at com.demo.MainActivity$5.lambda$onSuccess$1$com-othe-vpnclient-sdk-MainActivity$5(MainActivity.java:260)
2024-09-09 20:31:02.598 10527-10615 System.err              com.demo               W      at com.demo.MainActivity$5$$ExternalSyntheticLambda2.run(Unknown Source:2)
2024-09-09 20:31:02.599 10527-10615 System.err              com.demo               W      at java.lang.Thread.run(Thread.java:1012)
2024-09-09 20:31:02.599 10527-10627 TrafficStats            com.demo               D  tagSocket(6) with statsTag=0xffffffff, statsUid=-1
2024-09-09 20:31:02.601 10527-10615 System.err              com.demo               W  Caused by: java.io.IOException: FRAME_SIZE_ERROR: 4740180
2024-09-09 20:31:02.602 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:599)
2024-09-09 20:31:02.603 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:49)
2024-09-09 20:31:02.603 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:139)
2024-09-09 20:31:02.604 10527-10615 System.err              com.demo               W      at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:1107)
2024-09-09 20:31:02.605 10527-10615 System.err              com.demo               W      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
2024-09-09 20:31:02.605 10527-10615 System.err              com.demo               W      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
2024-09-09 20:31:02.605 10527-10615 System.err              com.demo               W      ... 1 more
```

iOS colleagues and PC colleagues have run through, how can I correct it to run normally？

**Comment by chengxuyuanxiaoka** [comment]
This is a question many people close, but no workable answer is given. Let me write the answer here, which may help a lot of people. Generally, other clients are tuned, but when Android is not tuned, it is because it does not understand some network knowledge. The reason for this error is that the mobile side and the PC side need to ignore the certificate verification, instead of directly using usePlaintext(), which leads to the server is 2.x, and the mobile side is 1.x, so the correct code should be written in this way:

public ManagedChannel createUnsafeChannel(String host, int port) {
        try {
            TrustManager[] trustAllCerts = new TrustManager[]{
                    new X509TrustManager() {
                        @Override
                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                            return new java.security.cert.X509Certificate[]{};
                        }
                    }
            };

            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, trustAllCerts, new java.security.SecureRandom());

            return OkHttpChannelBuilder.forAddress(host, port)
                    .useTransportSecurity() 
                    .hostnameVerifier((hostname, session) -> true)
                    .sslSocketFactory(sslContext.getSocketFactory())
                    .build();

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

**Comment by kannanjgithub** [comment]
It is not recommended to blindly accept the server certificate without verification, although it is no worse than the plain text connection you were trying before. You should prefer to set a sslSocketFactory that uses a TrustManager initialized with a trust store which has the certificates of the Certifying Authorities that issue the server certificate (the server you are connecting to with the gRPC client).

**Comment by ejona86** [comment]
It is better to use TlsChannelCredentials than trying to create a secure ` sslSocketFactory` yourself.
