### ISSUE TITLE
 XdsSecurityClientServerTest.tlsClientServer_useSystemRootCerts_validationContext is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#11678]
@erm-g 
https://github.com/grpc/grpc-java/actions/runs/11745673719/job/32723647320?pr=11673

```
XdsSecurityClientServerTest > tlsClientServer_useSystemRootCerts_validationContext[enableSpiffe=true] FAILED
    io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
        at app//io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
        at app//io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
        at app//io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
        at app//io.grpc.testing.protobuf.SimpleServiceGrpc$SimpleServiceBlockingStub.unaryRpc(SimpleServiceGrpc.java:340)
        at app//io.grpc.xds.XdsSecurityClientServerTest.unaryRpc(XdsSecurityClientServerTest.java:668)
        at app//io.grpc.xds.XdsSecurityClientServerTest.tlsClientServer_useSystemRootCerts_validationContext(XdsSecurityClientServerTest.java:238)

        Caused by:
        javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
            at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1927)
            at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:848)
            at java.base/javax.net.ssl.SSLEngine.wrap(SSLEngine.java:564)
            at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1131)
            at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:975)
            at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1511)
            at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1338)
            at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1387)
            at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
            at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
            at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
            at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
            at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
            at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
            at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501)
            at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399)
            at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
            at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
            at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
            at java.base/java.lang.Thread.run(Thread.java:840)

            Caused by:
            sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
                at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
                at java.base/sun.security.validator.Validator.validate(Validator.java:264)
                at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:285)
                at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
                at io.netty.handler.ssl.EnhancingX509ExtendedTrustManager.checkServerTrusted(EnhancingX509ExtendedTrustManager.java:69)
                at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:235)
                at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:797)
                at io.netty.internal.tcnative.CertificateVerifierTask.runTask(CertificateVerifierTask.java:36)
                at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:48)
                at io.netty.internal.tcnative.SSLTask.run(SSLTask.java:42)
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.runAndResetNeedTask(ReferenceCountedOpenSslEngine.java:1533)
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.access$700(ReferenceCountedOpenSslEngine.java:94)
                at io.netty.handler.ssl.ReferenceCountedOpenSslEngine$TaskDecorator.run(ReferenceCountedOpenSslEngine.java:1505)
                at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1651)
                at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1497)
                ... 19 more

                Caused by:
                sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
                    at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
                    at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
                    at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
                    at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)

3079 tests completed, 1 failed, 7 skipped
                    ... 34 more
```

Given this code just went in, seems highly flaky.

**Comment by erm-g** [comment]
@ejona86 how these runs are executed (how to reproduce it locally)? 
I just ran the whole test class and then the failing test itself locally (cloudtop) few thousand times and didn't observe any issues.

**Comment by ejona86** [comment]
This run was in [Github Actions](https://github.com/grpc/grpc-java/blob/546efd79f1cf48aac7e5b6c9426d5fbfd7958fec/.github/workflows/testing.yml#L55), which [runs `gradle build`](https://github.com/grpc/grpc-java/blob/546efd79f1cf48aac7e5b6c9426d5fbfd7958fec/buildscripts/kokoro/unix.sh#L70).

Testing with blaze for the --runs_per_test, I saw a few different flakes with a total flake rate around 1%, all with `useSystemRootCerts` but a mix of `enableSpiffe` of `true` and `false`. Importantly, with 1000 runs I didn't see any flakes without #11627 nor any flakes with `--test_filter='XdsSecurityClientServerTest.tlsClientServer_useSystemRootCerts_validationContext'`. So somehow the tests are interacting with each other or causing a different execution speed.

(While it is a 1% flake rate with blaze, those are different machines than Github Actions, so it may be a much higher flake rate on Github Actions.)

http://sponge2/45c92135-104b-49fd-92cb-02899959ef7b
http://sponge2/510a9a83-1283-47a4-adda-06ae17ce6918

I'm suspected `@Parameterized` is the trigger more than the new spiffe code. To confirm, I added parameterized to the test _without_ PR #11627:

```diff
--- grpc/xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java	2024-10-29 09:51:25.000000000 -0700
+++ grpc/xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java	2024-11-09 06:59:07.000000000 -0800
@@ -96,12 +96,13 @@
 import org.junit.Test;
 import org.junit.runner.RunWith;
 import org.junit.runners.JUnit4;
+import org.junit.runners.Parameterized;
 
 /**
  * Unit tests for {@link XdsChannelCredentials} and {@link XdsServerBuilder} for plaintext/TLS/mTLS
  * modes.
  */
-@RunWith(JUnit4.class)
+@RunWith(Parameterized.class)
 public class XdsSecurityClientServerTest {
 
   @Rule public final GrpcCleanupRule cleanupRule = new GrpcCleanupRule();
@@ -115,6 +116,14 @@
   private FakeXdsClientPoolFactory fakePoolFactory = new FakeXdsClientPoolFactory(xdsClient);
   private static final String OVERRIDE_AUTHORITY = "foo.test.google.fr";
 
+  @Parameterized.Parameter
+  public boolean bool;
+
+  @Parameterized.Parameters(name = "thebool={0}")
+  public static List<Boolean> data() {
+    return Arrays.asList(new Boolean[] {true, false});
+  }
+
   @After
   public void tearDown() throws IOException {
     if (fakeNameResolverFactory != null) {
```

That gave me a .5% flake rate in 1000 runs. http://sponge2/3a854fc8-f335-4388-ac75-d1e7d9138cb4 . So it's possible to reproduce without the spiffe code.

@kannanjgithub

**Comment by erm-g** [comment]
Hmmm, if it's some side effect of `@Parameterized` I can try to isolate the new tests using subclasses like I did here - https://github.com/grpc/grpc-java/blob/master/core/src/test/java/io/grpc/internal/SpiffeUtilTest.java#L48

Trying to reproduce...

**Comment by erm-g** [comment]
Ok caught it using 
`./gradlew build :grpc-xds:jacocoTestReport -PtargetArch=x86_64 -Pcheckstyle.ignoreFailures=false -PfailOnWarnings=false -PerrorProne=true -Dorg.gradle.parallel=true -PskipAndroid=true -PskipCodegen=true
`
and 
```java
@Parameters(name = "enableSpiffe={0}")
public static Collection<Boolean> data() {
    return IntStream.range(0, 1000)
        .mapToObj(i -> i%2 == 0)
        .collect(toList());
  }
```
trick

**Comment by erm-g** [comment]
Ok, so the exception actually happens if we don't set trustStore System Property (just by commenting out https://github.com/grpc/grpc-java/blob/master/xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java#L226)
So I suspect that the rootcause is concurrent execution of the tests where one thread calls `clearTrustStoreSystemProperties` immediately after another calls `setTrustStoreSystemProperties`. However I don't see any gradle properties enabling parallel execution of test methods.

I see 3 possible options:

1. Add synchronization technique for the test. I used `trustStoreFilePath` as an object to sync on for `setTrustStoreSystemProperties`, `clearTrustStoreSystemProperties`, and `tlsClientServer_useSystemRootCerts_validationContext` - 1000 runs didn't produce the exception, 5k sometimes fail with non-related to this issue timeouts and OOM. So I can create a PR with that.
2. I introduced `Parameterized` here to avoid directl manipulation with System properties `(GRPC_EXPERIMENTAL_SPIFFE_TRUST_BUNDLE_MAP` flag), but since we do it anyway in this test, I can drop `Parameterized` in favor of a similar manipulation
3. Mark the test as 'known flaky' (aka do nothing) - once the flag is removed, we can remove `Parameterized` and the test should be fine.

@ejona86 WDYT?

**Comment by ejona86** [comment]
It shouldn't be concurrent tests. Lots would break if that was happening. I think it is more likely a resource is left around (not shutdown quickly enough) after some tests, as running that one test by itself didn't flake.

**Comment by ejona86** [comment]
Java 17 flake: https://github.com/grpc/grpc-java/actions/runs/11784034777/job/32828839541?pr=11682

**Comment by matthewstevenson88** [comment]
@rockspore is taking a look at this.

**Comment by rockspore** [comment]
@erm-g Did you confirm that `System.setProperty()` indeed didn't take effect soon enough such that `System.getProperty()` still returned null, thus entering your retry loop? Because if this is the case, maybe this can just be added inside `setTrustStoreSystemProperties()`.

**Comment by erm-g** [comment]
> @erm-g Did you confirm that `System.setProperty()` indeed didn't take effect soon enough such that `System.getProperty()` still returned null, thus entering your retry loop?`.

Didn't really get your q. `soon enough` for set/get Property is not applicable since it's just a Map with synchronized access - https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html

> Because if this is the case, maybe this can just be added inside `setTrustStoreSystemProperties()

Yeah, the same loop can also be created there.

**Comment by rockspore** [comment]
> > @erm-g Did you confirm that `System.setProperty()` indeed didn't take effect soon enough such that `System.getProperty()` still returned null, thus entering your retry loop?`.
> 
> Didn't really get your q. `soon enough` for set/get Property is not applicable since it's just a Map with synchronized access - https://docs.oracle.com/javase/7/docs/api/java/util/Properties.html
> 
> > Because if this is the case, maybe this can just be added inside `setTrustStoreSystemProperties()
> 
> Yeah, the same loop can also be created there.

Thanks for the info. My original question was basically if it's all synchronized, why did you have to create such a loop to check it was not null after you had set it at the top? I don't think by default we have those test cases run in parallel.

In fact, I still saw the same failures with this retry logic added inside `setTrustStoreSystemProperties()`

**Comment by erm-g** [comment]
> My original question was basically if it's all synchronized, why did you have to create such a loop to check it was not null after you had set it at the top?

Only calls to `setProperty()` and `getProperty()` are synchronized, but the behavior we observe here tells us that needed properties are cleared after https://github.com/grpc/grpc-java/blob/master/xds/src/test/java/io/grpc/xds/XdsSecurityClientServerTest.java#L226 after the lock is released.
Eric believes that it might be a resource not shutdown quickly enough after another test, so my loop just waits for some empiric time.

**Comment by ejona86** [comment]
Split out the certificate provider leak into #11692, to keep this issue just for the flake.

**Comment by erm-g** [comment]
@ejona86 You're absolutely right about 2 instances of `FileWatcherCertificateProvider` - they're started for most of the tests here (one is for client and another for server). That's why I'm confused about 

>If I put org.junit.Assume.assumeTrue(false); as the first line of tlsClientServer_Spiffe_noClientAuthentication_wrongServerCert, then tlsClientServer_useSystemRootCerts_validationContext stops flaking.

I'd expect it to still be flaky because of the next "neighboring" test with 2 FWCPs

One practical question: we never expect the client and server to be executed under the same JVM in the real world, correct? Because if they were, we might need to create a similar fix for the codebase itself, not just for the test.

**Comment by ejona86** [comment]
> I'd expect it to still be flaky because of the next "neighboring" test with 2 FWCPs

You're assuming a particular execution order. They aren't executed in a defined order. (Often the order is repeatable, but it is "random" based on hashing and such.)

> we never expect the client and server to be executed under the same JVM in the real world, correct?

The main issue was the test was changing the system properties which caused the cache to become invalidated. If there is no cache, then the code works fine.

**Comment by erm-g** [comment]
> > I'd expect it to still be flaky because of the next "neighboring" test with 2 FWCPs
> 
> You're assuming a particular execution order. They aren't executed in a defined order. (Often the order is repeatable, but it is "random" based on hashing and such.)
> 
> > we never expect the client and server to be executed under the same JVM in the real world, correct?
> 
> The main issue was the test was changing the system properties which caused the cache to become invalidated. If there is no cache, then the code works fine.

Got it - thank you!
