### ISSUE TITLE
When Client receive PING ACK after GO AWAY, client may still use the old channel, rather than create a new one leading to all request fail

### ISSUE THREAD

**Issue by qianye1001** [grpc/grpc-java#11771]
LOG 
143:8081] INBOUND GO_AWAY: lastStreamId=2147483647 errorCode=0 length=13 bytes=6170705f726571756573746564
11:00:59.367 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND PING: ack=false bytes=40715087873
11:00:59.367 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] OUTBOUND PING: ack=true bytes=40715087873
11:00:59.368 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND PING: ack=true bytes=1234
11:00:59.368 [grpc-default-worker-ELG-1-1] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x85d8d308, L:/10.0.0.149:34504 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND GO_AWAY: lastStreamId=2147483647 errorCode=0 length=13 bytes=6170705f726571756573746564
11:00:59.368 [grpc-default-worker-ELG-1-1] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x85d8d308, L:/10.0.0.149:34504 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND PING: ack=false bytes=40715087873
11:00:59.368 [grpc-default-worker-ELG-1-1] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x85d8d308, L:/10.0.0.149:34504 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] OUTBOUND PING: ack=true bytes=40715087873
11:00:59.369 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND GO_AWAY: lastStreamId=174933 errorCode=0 length=13 bytes=6170705f726571756573746564
11:00:59.370 [grpc-default-worker-ELG-1-1] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x85d8d308, L:/10.0.0.149:34504 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND GO_AWAY: lastStreamId=13 errorCode=0 length=13 bytes=6170705f726571756573746564
11:00:59.370 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND HEADERS: streamId=174933 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, x-mq-request-id: a5721276-4e7d-48b0-8416-c81e177618f6, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false
11:00:59.370 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND DATA: streamId=174933 padding=0 endStream=false length=103 bytes=00000000620a0808a09c0112024f4b12560a0808a09c0112024f4b1222303130303136334530383541323930384144303737413643364230303031453943391a...
11:00:59.370 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] OUTBOUND PING: ack=false bytes=1234
11:00:59.370 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND HEADERS: streamId=174933 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
11:00:59.373 [grpc-default-worker-ELG-1-4] DEBUG i.g.n.s.i.g.netty.NettyClientHandler - [id: 0x56197da3, L:/10.0.0.149:34490 - R:ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081] INBOUND PING: ack=true bytes=1234

ERROR like this
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: ep-wz9iad22324292c58736.epsrv-wz9d6klnzdmxpcpvz0qn.cn-shenzhen.privatelink.aliyuncs.com/10.0.0.143:8081
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:321)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:477)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by qianye1001** [comment]
[errorLog.log](https://github.com/user-attachments/files/18224840/errorLog.log)
ERROR appear again
