### ISSUE TITLE
missing io/netty/util/ByteString

### ISSUE THREAD

**Issue by LeeYeeze** [grpc/grpc-java#1300]
Hi
I am trying to made a simple Grpc client and a server for it.
And this is the code for the client
```java
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.netty.NettyChannelBuilder;

public class GrpcClient {
	ManagedChannel grpcChannel = NettyChannelBuilder.forAddress("127.0.0.1", 2009)
    		.usePlaintext(true)
    		.build();
	
	public GrpcClient() {	
	}
	public static void main(String[] args) {
		new GrpcClient();
	}	
}
```
And I get a error every time I run it.
And this is it
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/util/ByteString
	at io.grpc.netty.Utils.<clinit>(Utils.java:65)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:245)
	at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:217)
	at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:194)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:91)
	at com.alibaba.geabase.GrpcClient.<init>(GrpcClient.java:10)
	at com.alibaba.geabase.GrpcClient.main(GrpcClient.java:18)
Caused by: java.lang.ClassNotFoundException: io.netty.util.ByteString
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

The server had the same problem when I was using grpc-all-0.9.0, and turned back to normal when switch to grpc-all-0.9.0-2.jar. But client still fails. I also update netty to 4.1.0 to fix the problem.

I really needs your help. Thanks!

**Comment by robeden** [comment]
io.netty.util.ByteString appears to have been removed in 4.1.0.Beta8 (commit: https://github.com/netty/netty/commit/19658e9cd80b57340df58ae573fa9dcbd141416a)

It has been replaced by [AsciiString](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AsciiString.java).

**Comment by LeeYeeze** [comment]
I also look into the source code of GRPC, and find that ByteString is already replaced by AsciiString. Still don't know why it is like that.

**Comment by LeeYeeze** [comment]
Still need your help

**Comment by LeeYeeze** [comment]
It seems solved after I build a grpc-Java myself

**Comment by ejona86** [comment]
@LeeYeeze, yes, the currently-released version of grpc-java isn't compatible with 4.1.0.Beta8. You have to build from source at-the-moment.
