### ISSUE TITLE
Sporadic NullPointerException

### ISSUE THREAD

**Issue by trask** [grpc/grpc-java#1426]
I'm getting this sporadically on slow travis-ci machines.  Haven't seen it on other machines.  My guess is that the listener is being executed before the channel field assignment occurs so channel is null.

```
java.lang.NullPointerException: null
	at io.grpc.netty.NettyClientTransport$1.operationComplete(NettyClientTransport.java:168) ~[grpc-netty-0.12.0.jar:0.12.0]
	at io.grpc.netty.NettyClientTransport$1.operationComplete(NettyClientTransport.java:164) ~[grpc-netty-0.12.0.jar:0.12.0]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683) ~[netty-common-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:854) [netty-common-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.util.concurrent.DefaultPromise$LateListenerNotifier.run(DefaultPromise.java:882) [netty-common-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339) [netty-common-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356) [netty-transport-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-common-4.1.0.CR2.jar:4.1.0.CR2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
```

**Comment by nmittler** [comment]
Thanks for reporting @trask!

@ejona86 It seems that the [code in `NettyClientTransport`](https://github.com/grpc/grpc-java/commit/6236968d4b176929090a132edd997d17e4a4945d) it seems that the listener shouldn't be accessing `channel` in case it is notified immediately. WDYT?

**Comment by ejona86** [comment]
@nmittler, I think we should just get the `Channel` before calling `addListener` on the `ChannelFuture`.

**Comment by nmittler** [comment]
@ejona86 refresh my memory, does `b.connect(address).channel()` block? Also what happens if the connect fails? Will `channel()` return null or throw?

**Comment by ejona86** [comment]
@nmittler, no, it doesn't block. The channel is created immediately and `Bootstrap` has the plumbing in place to make sure you can write to it immediately without reordering events. The `ChannelFuture` is only for the connecting operation itself. Even if `connect()` fails, `channel()` will be available for our use.
