### ISSUE TITLE
TlsTest flakiness

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#1513]
Found on Travis linux when testing for #1508
```
io.grpc.testing.integration.TlsTest > noClientAuthFailure[OPENSSL] FAILED
    java.lang.AssertionError: expected:<UNAVAILABLE> but was:<UNKNOWN>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.TlsTest.noClientAuthFailure(TlsTest.java:235)
```

**Comment by ejona86** [comment]
And I just saw this on #1511:
```
io.grpc.testing.integration.TlsTest > serverRejectsUntrustedClientCert[OPENSSL] FAILED
    java.lang.AssertionError: expected:<UNAVAILABLE> but was:<UNKNOWN>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.TlsTest.serverRejectsUntrustedClientCert(TlsTest.java:195)
io.grpc.testing.integration.TlsTest > noClientAuthFailure[OPENSSL] FAILED
    java.lang.AssertionError: expected:<UNAVAILABLE> but was:<UNKNOWN>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.TlsTest.noClientAuthFailure(TlsTest.java:235)
```

**Comment by ejona86** [comment]
From #1505
```
io.grpc.testing.integration.TlsTest > clientRejectsUntrustedServerCert[OPENSSL] FAILED
    java.lang.AssertionError: expected:<UNAVAILABLE> but was:<UNKNOWN>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at io.grpc.testing.integration.TlsTest.clientRejectsUntrustedServerCert(TlsTest.java:278)
```

**Comment by ejona86** [comment]
Saw noClientAuthFailure in #1509

**Comment by carl-mastrangelo** [comment]
@ejona86  I can't imagine how #1505 might have caused that.  Another close by commit perhaps?

**Comment by ejona86** [comment]
I'm guessing [this change](https://github.com/grpc/grpc-java/commit/1170afd16844bfe8654dd8634ff026d02e77baa0#diff-0133adb8af67ea6848d382c6d47a936fR171) has exposed a pre-existing flake. Before we would randomly get a useless UNAVAILABLE Status without any description of what went wrong, but now it is showing up as UNKNOWN.

We could revert that one part of that CL and probably unflake ourselves. I'm investigating.
