### ISSUE TITLE
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place

### ISSUE THREAD

**Issue by thefallentree** [grpc/grpc-java#1578]
We are using latest GRPC java release, what could possbily be the reason?

Thanks

```
2016-03-23 13:58:51.999  WARN 1 --- [lt-worker-ELG-5] io.grpc.netty.NettyServerHandler         : Stream Error

io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:144) ~[netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.cancel(DefaultHttp2RemoteFlowController.java:464) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.cancel(DefaultHttp2RemoteFlowController.java:446) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:110) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:347) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1241) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:1183) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:533) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:516) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:389) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onRstStreamRead(Http2InboundFrameLogger.java:78) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:489) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:249) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:147) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:106) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:332) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:392) [netty-codec-http2-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) [netty-codec-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [netty-codec-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [netty-transport-4.1.0.CR3.jar!/:4.1.0.CR3]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-common-4.1.0.CR3.jar!/:4.1.0.CR3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by buchgr** [comment]
Did your client get shutdown/killed while it was actively issuing RPCs? What seems to have happened is that your client canceled an RPC call, while your server still had some outgoing data buffered (to send to the client).

Afaik, this is usually expected behaviour and nothing to worry about. Maybe we should have picked a different log level, though.

Leaving this open for @ejona86 @nmittler to confirm, as it's been some time since I looked at the HTTP/2 codec :-).

**Comment by ejona86** [comment]
Yeah, I think this alone is nothing to worry about. I'm hoping this sort of logging is less common after we update to the most recent Netty release, but it may take more effort to reduce its occurrence.

If you were experiencing a problem when receiving the log, then I'd expect there to be another log statement before this one that provides more information.

**Comment by thefallentree** [comment]
I don't think our code ever calls cancel() or shutdown() , but I will look into it.

we are running into issues that one of our channel will permanently go into DEADLINE_EXCEEEDED mode, but havn't been able to find the issue yet.

**Comment by thefallentree** [comment]
On second thought, could this be caused by client side timeout settings?

**Comment by buchgr** [comment]
@thefallentree yep!
