### ISSUE TITLE
DeadlineTest.shortDeadlineEventuallyExpires is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1617]
As seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/948/console
```
io.grpc.DeadlineTest > shortDeadlineEventuallyExpires FAILED
    java.lang.AssertionError: expected:<0.0> but was:<-6.401849E8>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:519)
        at org.junit.Assert.assertEquals(Assert.java:609)
        at io.grpc.DeadlineTest.shortDeadlineEventuallyExpires(DeadlineTest.java:73)
```

**Comment by buchgr** [comment]
this and #1616 might have something to do with my changes. So I ll fix them.

**Comment by ejona86** [comment]
I think @carl-mastrangelo already is as part of #1619.
