### ISSUE TITLE
CallOptionsTest.withDeadlineNanoTime is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1645]
```
io.grpc.CallOptionsTest > withDeadlineNanoTime FAILED
    java.lang.AssertionError: <-25128839 ns from now> and <-1322031 ns from now> should have been within <20000000ns> of each other
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
        at com.google.common.truth.Subject.failWithRawMessage(Subject.java:381)
        at io.grpc.testing.DeadlineSubject.access$400(DeadlineSubject.java:52)
        at io.grpc.testing.DeadlineSubject$1.of(DeadlineSubject.java:81)
        at io.grpc.CallOptionsTest.withDeadlineNanoTime(CallOptionsTest.java:161)
```

As seen (may have been restarted):
https://travis-ci.org/grpc/grpc-java/jobs/121289248
https://travis-ci.org/grpc/grpc-java/jobs/121487416
(<-33620603 ns from now> and <-2319629 ns from now> should have been within <20000000ns> of each other)

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121306337
<-31362816 ns from now> and <-1433587 ns from now> should have been within <20000000ns> of each other

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121581408
<-32981662 ns from now> and <-2647022 ns from now> should have been within <20000000ns> of each other

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121289248 (again)
<-48887404 ns from now> and <-2280743 ns from now> should have been within <20000000ns> of each other

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121757443
<-32549978 ns from now> and <-1435954 ns from now> should have been within <20000000ns> of each other

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121761316
<-21761389 ns from now> and <-1378367 ns from now> should have been within <20000000ns> of each other

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/121762868 (from before the fix)
<-26339591 ns from now> and <-19607344 ns from now> should have been within <20000000ns> of each other
