### ISSUE TITLE
protoc-gen-grpc-java crashed on MaxOS

### ISSUE THREAD

**Issue by AdoHe** [grpc/grpc-java#1683]
I meet this problem when I was trying to generate code based on my `.proto` file, and the error stack trace is:
```
[ERROR] PROTOC FAILED: --grpc-java_out: protoc-gen-grpc-java: Plugin killed by signal 11.

[ERROR] /Users/nankonami/Documents/etcd4j/src/main/proto/etcd.proto [0:0]: --grpc-java_out: protoc-gen-grpc-java: Plugin killed by signal 11.

ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile-custom (default) on project etcd4j: protoc did not exit cleanly. Review output for more information. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile-custom (default) on project etcd4j: protoc did not exit cleanly. Review output for more information.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException: protoc did not exit cleanly. Review output for more information.
	at org.xolstice.maven.plugin.protobuf.AbstractProtocMojo.execute(AbstractProtocMojo.java:539)
	at org.xolstice.maven.plugin.protobuf.AbstractProtocCompileMojo.execute(AbstractProtocCompileMojo.java:31)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
```
And my `pom.xml` content is:
```

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <artifactTargetPath>${project.build.directory}</artifactTargetPath>
		<maven.compiler.source>1.7</maven.compiler.source>
		<maven.compiler.target>1.7</maven.compiler.target>
    </properties>

    <distributionManagement>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2</url>
        </repository>
    </distributionManagement>

    <dependencies>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.0.0-beta-2</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-all</artifactId>
            <version>0.13.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpasyncclient</artifactId>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>14.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.2.4</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <version>8.1.16.v20140903</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-servlet</artifactId>
            <version>8.1.16.v20140903</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.4.1.Final</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.5.0</version>
                <configuration>
                    <!--
                      The version of protoc must match protobuf-java. If you don't depend on
                      protobuf-java directly, you will be transitively depending on the
                      protobuf-java version that grpc depends on.
                    -->
                    <protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:0.13.2:exe:${os.detected.classifier}</pluginArtifact>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
And `java -version` output is:
```
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)
```
`mvn -version` output is:
```
Apache Maven 3.0.3 (r1075438; 2011-03-01 01:31:09+0800)
Maven home: /usr/share/maven
Java version: 1.7.0_55, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.7.5", arch: "x86_64", family: "mac"
```
`protoc --version` is:
```
libprotoc 3.0.0
```

I have no idea how to fix this issue, and hope you guys can help me. Thanks~

**Comment by carl-mastrangelo** [comment]
Can you include the protoc output?  Also, your .proto file?

**Comment by AdoHe** [comment]
@carl-mastrangelo what you mean protoc output?

**Comment by carl-mastrangelo** [comment]
Protoc is the compiler that takes in the .proto file, and runs the grpc code generator.  It says in your error you pasted above:

    protoc did not exit cleanly. Review output for more information.

**Comment by AdoHe** [comment]
and this is my .proto file:
```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.xqbase.etcd4j";
option java_outer_classname = "EtcdJavaProto";
option objc_class_prefix = "ETCD4J";

package etcd4j;

service KV {
  // Range gets the keys in the range from the store.
  rpc Range(RangeRequest) returns (RangeResponse) {}

  // Put puts the given key into the store.
  // A put request increases the revision of the store,
  // and generates one event in the event history.
  rpc Put(PutRequest) returns (PutResponse) {}

  // Delete deletes the given range from the store.
  // A delete request increase the revision of the store,
  // and generates one event in the event history.
  rpc DeleteRange(DeleteRangeRequest) returns (DeleteRangeResponse) {}

  // Txn processes all the requests in one transaction.
  // A txn request increases the revision of the store,
  // and generates events with the same revision in the event history.
  // It is not allowed to modify the same key several times within one txn.
  rpc Txn(TxnRequest) returns (TxnResponse) {}

  // Compact compacts the event history in etcd. User should compact the
  // event history periodically, or it will grow infinitely.
  rpc Compact(CompactionRequest) returns (CompactionResponse) {}
}

service Watch {
  // Watch watches the events happening or happened. Both input and output
  // are stream. One watch rpc can watch for multiple keys or prefixs and
  // get a stream of events. The whole events history can be watched unless
  // compacted.
  rpc Watch(stream WatchRequest) returns (stream WatchResponse) {}
}

service Lease {
  // LeaseGrant creates a lease. A lease has a TTL. The lease will expire if the
  // server does not receive a keepAlive within TTL from the lease holder.
  // All keys attached to the lease will be expired and deleted if the lease expires.
  // The key expiration generates an event in event history.
  rpc LeaseGrant(LeaseGrantRequest) returns (LeaseGrantResponse) {}

  // LeaseRevoke revokes a lease. All the key attached to the lease will be expired and deleted.
  rpc LeaseRevoke(LeaseRevokeRequest) returns (LeaseRevokeResponse) {}

  // KeepAlive keeps the lease alive.
  rpc LeaseKeepAlive(stream LeaseKeepAliveRequest) returns (stream LeaseKeepAliveResponse) {}

  // TODO(xiangli) List all existing Leases?
  // TODO(xiangli) Get details information (expirations, leased keys, etc.) of a lease?
}

service Cluster {
  // MemberAdd adds a member into the cluster.
  rpc MemberAdd(MemberAddRequest) returns (MemberAddResponse) {}

  // MemberRemove removes an existing member from the cluster.
  rpc MemberRemove(MemberRemoveRequest) returns (MemberRemoveResponse) {}

  // MemberUpdate updates the member configuration.
  rpc MemberUpdate(MemberUpdateRequest) returns (MemberUpdateResponse) {}

  // MemberList lists all the members in the cluster.
  rpc MemberList(MemberListRequest) returns (MemberListResponse) {}
}

message ResponseHeader {
  uint64 cluster_id = 1;
  uint64 member_id = 2;
  // revision of the store when the request was applied.
  int64 revision = 3;
  // term of raft when the request was applied.
  uint64 raft_term = 4;
}

message RangeRequest {
  enum SortOrder {
	NONE = 0; // default, no sorting
	ASCEND = 1; // lowest target value first
	DESCEND = 2; // highest target value first
  }
  enum SortTarget {
	KEY = 0;
	VERSION = 1;
	CREATE = 2;
	MOD = 3;
	VALUE = 4;
  }

  // if the range_end is not given, the request returns the key.
  bytes key = 1;
  // if the range_end is given, it gets the keys in range [key, range_end)
  // if range_end is nonempty, otherwise it returns all keys >= key.
  bytes range_end = 2;
  // limit the number of keys returned.
  int64 limit = 3;
  // range over the store at the given revision.
  // if revision is less or equal to zero, range over the newest store.
  // if the revision has been compacted, ErrCompaction will be returned in
  // response.
  int64 revision = 4;

  // sort_order is the requested order for returned the results
  SortOrder sort_order = 5;

  // sort_target is the kv field to use for sorting
  SortTarget sort_target = 6;

  // range request is linearizable by default. Linearizable requests has a higher
  // latency and lower throughput than serializable request.
  // To reduce latency, serializable can be set. If serializable is set, range request
  // will be serializable, but not linearizable with other requests.
  // Serializable range can be served locally without waiting for other nodes in the cluster.
  bool serializable = 7;
}

message RangeResponse {
  ResponseHeader header = 1;
  repeated KeyValue kvs = 2;
  // more indicates if there are more keys to return in the requested range.
  bool more = 3;
}

message PutRequest {
  bytes key = 1;
  bytes value = 2;
  int64 lease = 3;
}

message PutResponse {
  ResponseHeader header = 1;
}

message DeleteRangeRequest {
  // if the range_end is not given, the request deletes the key.
  bytes key = 1;
  // if the range_end is given, it deletes the keys in range [key, range_end).
  bytes range_end = 2;
}

message DeleteRangeResponse {
  ResponseHeader header = 1;
  // Deleted is the number of keys that got deleted.
  int64 deleted = 2;
}

message RequestUnion {
  oneof request {
    RangeRequest request_range = 1;
    PutRequest request_put = 2;
    DeleteRangeRequest request_delete_range = 3;
  }
}

message ResponseUnion {
  oneof response {
    RangeResponse response_range = 1;
    PutResponse response_put = 2;
    DeleteRangeResponse response_delete_range = 3;
  }
}

message Compare {
  enum CompareResult {
    EQUAL = 0;
    GREATER = 1;
    LESS = 2;
  }
  enum CompareTarget {
    VERSION = 0;
    CREATE = 1;
    MOD = 2;
    VALUE= 3;
  }
  CompareResult result = 1;
  CompareTarget target = 2;
  // key path
  bytes key = 3;
  oneof target_union {
    // version of the given key
    int64 version = 4;
    // create revision of the given key
    int64 create_revision = 5;
    // last modified revision of the given key
    int64 mod_revision = 6;
    // value of the given key
    bytes value = 7;
  }
}

// If the comparisons succeed, then the success requests will be processed in order,
// and the response will contain their respective responses in order.
// If the comparisons fail, then the failure requests will be processed in order,
// and the response will contain their respective responses in order.

// From google paxosdb paper:
// Our implementation hinges around a powerful primitive which we call MultiOp. All other database
// operations except for iteration are implemented as a single call to MultiOp. A MultiOp is applied atomically
// and consists of three components:
// 1. A list of tests called guard. Each test in guard checks a single entry in the database. It may check
// for the absence or presence of a value, or compare with a given value. Two different tests in the guard
// may apply to the same or different entries in the database. All tests in the guard are applied and
// MultiOp returns the results. If all tests are true, MultiOp executes t op (see item 2 below), otherwise
// it executes f op (see item 3 below).
// 2. A list of database operations called t op. Each operation in the list is either an insert, delete, or
// lookup operation, and applies to a single database entry. Two different operations in the list may apply
// to the same or different entries in the database. These operations are executed
// if guard evaluates to
// true.
// 3. A list of database operations called f op. Like t op, but executed if guard evaluates to false.
message TxnRequest {
  repeated Compare compare = 1;
  repeated RequestUnion success = 2;
  repeated RequestUnion failure = 3;
}

message TxnResponse {
  ResponseHeader header = 1;
  bool succeeded = 2;
  repeated ResponseUnion responses = 3;
}

// Compaction compacts the kv store upto a given revision. All superseded keys
// with a revision less than the compaction revision will be removed.
message CompactionRequest {
  int64 revision = 1;
  // physical is set so the RPC will wait until the compaction is physically
  // applied to the local database such that compacted entries are totally
  // removed from the backing store.
  bool physical = 2;
}

message CompactionResponse {
  ResponseHeader header = 1;
}

message WatchRequest {
  oneof request_union {
    WatchCreateRequest create_request = 1;
    WatchCancelRequest cancel_request = 2;
  }
}

message WatchCreateRequest {
  // the key to be watched
  bytes key = 1;
  // if the range_end is given, keys in [key, range_end) are watched
  // NOTE: only range_end == prefixEnd(key) is accepted now
  bytes range_end = 2;
  // start_revision is an optional revision (including) to watch from. No start_revision is "now".
  int64 start_revision = 3;
  // if progress_notify is set, etcd server sends WatchResponse with empty events to the
  // created watcher when there are no recent events. It is useful when clients want always to be
  // able to recover a disconnected watcher from a recent known revision.
  // etcdsever can decide how long it should send a notification based on current load.
  bool progress_notify = 4;
}

message WatchCancelRequest {
  int64 watch_id = 1;
}

message WatchResponse {
  ResponseHeader header = 1;
  // watch_id is the ID of the watching the response sent to.
  int64 watch_id = 2;
  // If the response is for a create watch request, created is set to true.
  // Client should record the watch_id and prepare for receiving events for
  // that watching from the same stream.
  // All events sent to the created watching will attach with the same watch_id.
  bool created = 3;
  // If the response is for a cancel watch request, cancel is set to true.
  // No further events will be sent to the canceled watching.
  bool canceled = 4;
  // CompactRevision is set to the minimum index if a watching tries to watch
  // at a compacted index.
  //
  // This happens when creating a watching at a compacted revision or the watching cannot
  // catch up with the progress of the KV.
  //
  // Client should treat the watching as canceled and should not try to create any
  // watching with same start_revision again.
  int64 compact_revision  = 5;

  repeated Event events = 11;
}

message LeaseGrantRequest {
  // advisory ttl in seconds
  int64 TTL = 1;
  // requested ID to create; 0 lets lessor choose
  int64 ID = 2;
}

message LeaseGrantResponse {
  ResponseHeader header = 1;
  int64 ID = 2;
  // server decided ttl in second
  int64 TTL = 3;
  string error = 4;
}

message LeaseRevokeRequest {
  int64 ID = 1;
}

message LeaseRevokeResponse {
  ResponseHeader header = 1;
}

message LeaseKeepAliveRequest {
  int64 ID = 1;
}

message LeaseKeepAliveResponse {
  ResponseHeader header = 1;
  int64 ID = 2;
  int64 TTL = 3;
}

message KeyValue {
  bytes key = 1;
  // create_revision is the revision of last creation on this key.
  int64 create_revision = 2;
  // mod_revision is the revision of last modification on this key.
  int64 mod_revision = 3;
  // version is the version of the key. A deletion resets
  // the version to zero and any modification of the key
  // increases its version.
  int64 version = 4;
  bytes value = 5;
  // lease is the ID of the lease that attached to key.
  // When the attached lease expires, the key will be deleted.
  int64 lease = 6;
}

message Event {
  enum EventType {
    PUT = 0;
    DELETE = 1;
    EXPIRE = 2;
  }
  EventType type = 1;
  // A PUT event contains current kv pair.
  // A PUT event with kv.Version=1 indicates the creation of a key.
  // A DELETE/EXPIRE event contains the deleted key with
  // its modification revision set to the revision of deletion.
  KeyValue kv = 2;
}

message Member {
  uint64 ID = 1;
  // If the member is not started, name will be an empty string.
  string name = 2;
  repeated string peerURLs = 3;
  // If the member is not started, client_URLs will be an zero length
  // string array.
  repeated string clientURLs = 4;
}

message MemberAddRequest {
  repeated string peerURLs = 1;
}

message MemberAddResponse {
  ResponseHeader header = 1;
  Member member = 2;
}

message MemberRemoveRequest {
  uint64 ID = 1;
}

message MemberRemoveResponse {
  ResponseHeader header = 1;
}

message MemberUpdateRequest {
  uint64 ID = 1;
  repeated string peerURLs = 2;
}

message MemberUpdateResponse{
  ResponseHeader header = 1;
}

message MemberListRequest {
}

message MemberListResponse {
  ResponseHeader header = 1;
  repeated Member members = 2;
}
```

**Comment by AdoHe** [comment]
@carl-mastrangelo I use this command to generate code:
```
LinkedIn:proto nankonami$ protoc -I=/Users/nankonami/Documents/etcd4j/src/main/proto --java_out=/Users/nankonami/Documents/etcd4j/src/generated/main/java /Users/nankonami/Documents/etcd4j/src/main/proto/etcd.proto
```
and no error return. I checked the generated code, no *Grpc java generate. And if I run `mvn clean install` i just got this error.

**Comment by carl-mastrangelo** [comment]
Hmm, runnning locally shows that it does work.  Signal 11 is segfault.  That probably means a bug in your protoc binary.  Can you run this:

ldd `which protoc`

**Comment by AdoHe** [comment]
@carl-mastrangelo since mac os has no `ldd`, I just ran this commad:
```
LinkedIn:proto nankonami$ otool -L `which protoc`
/usr/bin/protoc:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by carl-mastrangelo** [comment]
@AdoHe Kind of short on ideas.  Not sure what can cause a segfault.  Are you running the latest protobuf?  Would it be possible for you to try with protoc from head?  The instructions to build it are here:

https://github.com/google/protobuf/blob/master/src/README.md

**Comment by ejona86** [comment]
@carl-mastrangelo, did you try to reproduce on a Mac or on Linux? I tried on Linux and wasn't able to reproduce.

Based on the snippet above, when running from maven it is using good versions:
```
<protocArtifact>com.google.protobuf:protoc:3.0.0-beta-2:exe:${os.detected.classifier}</protocArtifact>
<pluginId>grpc-java</pluginId>
<pluginArtifact>io.grpc:protoc-gen-grpc-java:0.13.2:exe:${os.detected.classifier}</pluginArtifact>
```

This makes it seem fairly plain that the grpc plugin crashed:
```
--grpc-java_out: protoc-gen-grpc-java: Plugin killed by signal 11.
```

**Comment by carl-mastrangelo** [comment]
I ran on linux.  Maybe it's a mac specific bug?

**Comment by ejona86** [comment]
I'd expect it is a general bug it just results in a _crash_ on OS X. @zhangkun83 or @nmittler, on your Mac you could throw [the proto](https://github.com/grpc/grpc-java/issues/1683#issuecomment-211441276) some place like compiler/src/test/proto and then run `./gradlew build` to see if it crashes?

**Comment by carl-mastrangelo** [comment]
Tried it out on a mac using

protoc-3.0.0-beta-2-osx-x86_64 and protoc-gen-grpc-java-0.13.2-osx-x86_64.exe

Seems to work fine with command line

```
protoc-3.0.0-beta-2-osx-x86_64/protoc  --plugin=protoc-gen-grpc=./protoc-gen-grpc-java-0.13.2-osx-x86_64.exe  -I. etcd.proto.txt --grpc_out=.
```

Maybe it fails at head?

**Comment by zhangkun83** [comment]
> ```
> LinkedIn:proto nankonami$ protoc -I=/Users/nankonami/Documents/etcd4j/src/main/proto --java_out=/Users/nankonami/Documents/etcd4j/src/generated/main/java /Users/nankonami/Documents/etcd4j/src/main/proto/etcd.proto
> ```
> and no error return. I checked the generated code, no *Grpc java generate. And if I run `mvn clean install` i just got this error.

@AdoHe You are using the `protoc` from system path, which may be different from what Maven has downloaded and running. You are not specifying the `protoc-gen-grpc-java` flag on the `protoc` command line (see @carl-mastrangelo's last comment) either, which is probably why you don't get any `*Grpc.java` generated. Can you download [protoc-3.0.0-beta-2-osx-x86_64.exe](https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.0.0-beta-2/protoc-3.0.0-beta-2-osx-x86_64.exe) and [protoc-gen-grpc-java-0.13.2-osx-x86_64.exe](https://repo1.maven.org/maven2/io/grpc/protoc-gen-grpc-java/0.13.2/protoc-gen-grpc-java-0.13.2-osx-x86_64.exe) (or find them under your `~/.m2`) and run:
```
./protoc-3.0.0-beta-2-osx-x86_64.exe --plugin=protoc-gen-grpc=./protoc-gen-grpc-java-0.13.2-osx-x86_64.exe  -I. etcd.proto --grpc_out=. --java_out=.
```

**Comment by AdoHe** [comment]
@zhangkun83 thanks very much and I will give a try.

**Comment by ejona86** [comment]
It seems like this may have been resolved and may not have been specific to grpc. Feel free to comment if that is not the case.
