### ISSUE TITLE
QpsWorker doesn't terminate after it has run a client and QuitWorker has been invoked.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-java#1685]
I was able to successfully run a benchmarking scenario using Java QPS woker, and the worker that was running the server terminates fine, but the worker that acted as a client doesn't terminate.

Output from the worker:
```
INFO: Client Config 
server_targets: "localhost:60164"
outstanding_rpcs_per_channel: 1
client_channels: 1
async_client_threads: 1
load_params {
  closed_loop {
  }
}
payload_config {
  simple_params {
  }
}
histogram_params {
  resolution: 0.01
  max_possible: 6.0E10
}

Apr 18, 2016 1:36:40 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@58d8050a] Created with target directaddress:///localhost/127.0.0.1:60164
Apr 18, 2016 1:37:25 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@58d8050a] Terminated
```

after printing "Terminated" the process never finishes.

**Comment by jtattermusch** [comment]
The stacktrace after it hangs:

```
"grpc-shared-destroyer-0" #17 daemon prio=5 os_prio=0 tid=0x00007f70a4056800 nid=0x45b waiting on condition [0x00007f70b4ffa000]
   java.lang.Thread.State: WAITING (parking)
	at (C/C++) __pthread_cond_wait( (/usr/grte/v4/lib64/libpthread.so.0))
	at (C/C++) Unsafe_Park( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000008c190090> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1107)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:835)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"ELG-0" #15 daemon prio=5 os_prio=0 tid=0x00007f70ac017000 nid=0x3e8 runnable [0x00007f70f842c000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:107)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:204)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:228)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

"threadDeathWatcher-3-1" #13 daemon prio=1 os_prio=0 tid=0x00007f70b8120000 nid=0x3e4 waiting on condition [0x00007f70f8a68000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at (C/C++) __pthread_cond_timedwait( (/usr/grte/v4/lib64/libpthread.so.0))
	at (C/C++) JVM_Sleep( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at java.lang.Thread.sleep(Native Method)
	at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:147)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)

"Attach Listener" #12 daemon prio=9 os_prio=0 tid=0x00007f70d4001000 nid=0x7fd8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"nioEventLoopGroup-2-1" #11 prio=10 os_prio=0 tid=0x00007f7118822000 nid=0x7f97 runnable [0x00007f70f9026000]
   java.lang.Thread.State: RUNNABLE
	at (C/C++) __GI_epoll_wait( (/usr/grte/v4/lib64/libc.so.6))
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000009f357900> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000009f3553d8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000009f358380> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:638)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:324)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f711847c000 nid=0x7f92 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=0 tid=0x00007f7118473800 nid=0x7f91 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=0 tid=0x00007f7118471000 nid=0x7f90 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #5 daemon prio=9 os_prio=0 tid=0x00007f711846d800 nid=0x7f8f runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x00007f711846b800 nid=0x7f8e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=10 os_prio=0 tid=0x00007f7118414000 nid=0x7f8d in Object.wait() [0x00007f70f9928000]
   java.lang.Thread.State: WAITING (on object monitor)
	at (C/C++) __pthread_cond_wait( (/usr/grte/v4/lib64/libpthread.so.0))
	at (C/C++) ObjectMonitor::wait(long, bool, Thread*)( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at (C/C++) JVM_MonitorWait( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000009f3654b8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x000000009f3654b8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:312)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f7118411800 nid=0x7f8c in Object.wait() [0x00007f70f9a2a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at (C/C++) __pthread_cond_wait( (/usr/grte/v4/lib64/libpthread.so.0))
	at (C/C++) ObjectMonitor::wait(long, bool, Thread*)( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at (C/C++) JVM_MonitorWait( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000009f365950> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:155)
	- locked <0x000000009f365950> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007f7118035800 nid=0x7f80 in Object.wait() [0x00007f711f854000]
   java.lang.Thread.State: WAITING (on object monitor)
	at (C/C++) __pthread_cond_wait( (/usr/grte/v4/lib64/libpthread.so.0))
	at (C/C++) ObjectMonitor::wait(long, bool, Thread*)( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at (C/C++) JVM_MonitorWait( (/usr/local/buildtools/java/jdk8-google-v7-64/jre/lib/amd64/server/libjvm.so))
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000009f35e668> (a java.lang.Object)
	at java.lang.Object.wait(Object.java:502)
	at io.grpc.internal.ServerImpl.awaitTermination(ServerImpl.java:211)
	- locked <0x000000009f35e668> (a java.lang.Object)
	at io.grpc.benchmarks.driver.LoadWorker.main(LoadWorker.java:118)

"VM Thread" os_prio=0 tid=0x00007f7118409000 nid=0x7f8b runnable 
```

**Comment by carl-mastrangelo** [comment]
The thread

"nioEventLoopGroup-2-1" #11 prio=10 os_prio=0 tid=0x00007f7118822000 nid=0x7f97 runnable [0x00007f70f9026000]


Is not a daemon, which is why it fails.

**Comment by jtattermusch** [comment]
@carl-mastrangelo  thanks for the help!
