### ISSUE TITLE
StressTestClientTest.gaugesShouldBeExported is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1695]
As seen at https://travis-ci.org/grpc/grpc-java/jobs/124416631 (since rebuilt):
```
io.grpc.testing.integration.StressTestClientTest > gaugesShouldBeExported FAILED
    java.lang.AssertionError: gauges: [/stress_test/server_0/channel_0/stub_1/qps]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.grpc.testing.integration.StressTestClientTest.gaugesShouldBeExported(StressTestClientTest.java:158)
```

Also seen at https://travis-ci.org/grpc/grpc-java/jobs/124340841 (since rebuilt)

**Comment by ejona86** [comment]
Again in https://travis-ci.org/grpc/grpc-java/jobs/124629541

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/126157650
https://travis-ci.org/grpc/grpc-java/jobs/126173335
