### ISSUE TITLE
Stress test failures in Java client

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc-java#1812]
### Steps to repro:###
(I repro'ed this using a docker image. This may repro without the docker image too - I am not sure)

1) Built a Docker image for stress test:
Get the `grpc` repo  (you don't have to build it. Just need it for the docker scripts)
``` bash
$ git clone https://github.com/grpc/grpc.git
$ cd grpc
$ export INTEROP_IMAGE=stress-test-java
$ export BASE_NAME=grpc_interop_stress_java
$ # Remember to be under the grpc directory
$ tools/run_tests/dockerize/build_interop_stress_image.sh
```
This will take a few minutes to build (if it fails in the middle, just retry one more time. Sometimes, it is flaky)

2) Start a docker container
``` bash
$ docker run -i -t stress-test-java bash
```

3) Run  java interop server in the background in the container:
``` bash
root@b44016cf1c83:/# /var/local/git/grpc-java/interop-testing/build/install/grpc-interop-testing/bin/test-server --port=8080 --use_tls=false &
```

4) Now run the interop client:
```
root@b44016cf1c83:/# /var/local/git/grpc-java/interop-testing/build/install/grpc-interop-testing/bin/stresstest-client --test_cases=empty_unary:1 --num_channels_per_server=5 --num_stubs_per_channel=5

```
You will see the following errors:

```
root@b44016cf1c83:/# /var/local/git/grpc-java/interop-testing/build/install/grpc-interop-testing/bin/stresstest-client --test_cases=empty_unary:1 --num_channels_per_server=5 --num_stubs_per_channel=5
May 10, 2016 2:04:14 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@7494e528] Created with target localhost:8080
May 10, 2016 2:04:14 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@5f282abb] Created with target localhost:8080
May 10, 2016 2:04:14 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@1786dec2] Created with target localhost:8080
May 10, 2016 2:04:14 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@4d41cee] Created with target localhost:8080
May 10, 2016 2:04:14 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@1b68ddbd] Created with target localhost:8080
[GC (Allocation Failure)  129024K->17912K(493056K), 0.0100072 secs]
[GC (Allocation Failure)  146936K->12744K(622080K), 0.0084358 secs]
[GC (Allocation Failure)  270792K->12672K(622080K), 0.0058763 secs]
[GC (Allocation Failure)  270720K->12664K(880128K), 0.0046501 secs]
[GC (Allocation Failure)  528760K->12704K(880128K), 0.0076892 secs]
[GC (Allocation Failure)  528800K->12744K(1392128K), 0.0086561 secs]
[GC (Allocation Failure)  1044936K->14822K(1392640K), 0.0067372 secs]
[GC (Allocation Failure)  1047014K->14902K(1330176K), 0.0009984 secs]
[GC (Allocation Failure)  1001526K->14982K(1286656K), 0.0008510 secs]
```

**Comment by carl-mastrangelo** [comment]
Those just mean a full GC started.  The only thing that message means is that garbage is being created too fast (perhaps due to lots of small requests).

For the stress test we probably need to set Xms and Xmx as well as ParNewGen

**Comment by buchgr** [comment]
@carl-mastrangelo it's actually a minor GC :-). Just a normal GC cycle. We explicitly turned on GC logging, which is why it's shown here. Pause times seem sufficiently low for us not to worry about them. I think this can be closed?

**Comment by sreecha** [comment]
Ok. I didn't realize these were just ParNew logs.
There are a lot of other exceptions being thrown by the stress clients. For example, I just saw that the most recent run failed with this error:

```
May 11, 2016 3:18:50 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Input Future failed with Error
Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.
        at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
        at io.grpc.testing.integration.StressTestClient$Worker.runTestCase(StressTestClient.java:441)
        at io.grpc.testing.integration.StressTestClient$Worker.run(StressTestClient.java:384)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
May 11, 2016 3:18:50 PM io.grpc.testing.integration.StressTestClient main
WARNING: The stress test client encountered an error!
java.util.concurrent.ExecutionException: Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
        at io.grpc.testing.integration.StressTestClient.blockUntilStressTestComplete(StressTestClient.java:239)
        at io.grpc.testing.integration.StressTestClient.main(StressTestClient.java:99)
Caused by: Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.

        at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
        at io.grpc.testing.integration.StressTestClient$Worker.runTestCase(StressTestClient.java:441)
        at io.grpc.testing.integration.StressTestClient$Worker.run(StressTestClient.java:384)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

May 11, 2016 3:18:50 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Input Future failed with Error
Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.

        at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
        at io.grpc.testing.integration.StressTestClient$Worker.runTestCase(StressTestClient.java:441)
        at io.grpc.testing.integration.StressTestClient$Worker.run(StressTestClient.java:384)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

May 11, 2016 3:18:50 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Input Future failed with Error
Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.

        at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
        at io.grpc.testing.integration.StressTestClient$Worker.runTestCase(StressTestClient.java:441)
        at io.grpc.testing.integration.StressTestClient$Worker.run(StressTestClient.java:384)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

May 11, 2016 3:18:50 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Input Future failed with Error
Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.

        at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
        at io.grpc.testing.integration.StressTestClient$Worker.runTestCase(StressTestClient.java:441)
        at io.grpc.testing.integration.StressTestClient$Worker.run(StressTestClient.java:384)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

May 11, 2016 3:18:50 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Input Future failed with Error
Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.

        at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
        at io.grpc.testing.integration.StressTestClient$Worker.runTestCase(StressTestClient.java:441)
        at io.grpc.testing.integration.StressTestClient$Worker.run(StressTestClient.java:384)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

May 11, 2016 3:18:51 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@4232c52b] Terminated
May 11, 2016 3:18:51 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@2bbf4b8b] Terminated
May 11, 2016 3:18:51 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@d44fc21] Terminated
May 11, 2016 3:18:52 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@2f943d71] Terminated
May 11, 2016 3:18:52 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@467aecef] Terminated
```

**Comment by sreecha** [comment]
I think it would be a lot easier if you can try to repro this by running the stress test framework yourself.  

There is a one-time setup you need to do (to set up a google cloud platform account and install some python libraries on your machine) but I think it is totally worth it to debug any future stress-related issues

The instructions are here:
https://github.com/grpc/grpc/blob/master/tools/run_tests/stress_test/README.md

**Comment by sreecha** [comment]
@buchgr, I just realized that you may not have a Google cloud platform account - so please ignore my previous comment for now. I'll chat with the java team here and get back to you.. thanks

**Comment by carl-mastrangelo** [comment]
@buchgr Ideally the heap will never change size.  All the advice internally is to lock NewSize and MaxNewSize to the same value, and also lock Xmx and Xms.

**Comment by buchgr** [comment]
@sreecha I believe the error messages are due to timeouts. See, the stress test client reuses the interop integration tests under hood, and these tests verify that e.g. [a call ends within 5 seconds](https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java#L340). That's where the error seems to come from.

```
Wanted but not invoked:
streamObserver.onCompleted();
-> at io.grpc.testing.integration.AbstractInteropTest.emptyStream(AbstractInteropTest.java:340)
Actually, there were zero interactions with this mock.
```

In your opinion, is it possible that for some calls the latency is > 5 seconds?

Also, yes I don't have a GCE account. I used to have one. Who should I talk to, to get one? I am happy to set up a test env.

In the meantime, I ll submit a PR to refactor the interop tests to exlude these timeouts when using the stress test client.

**Comment by buchgr** [comment]
@sreecha can you retry with current master please?
