### ISSUE TITLE
CascadingTest.testCascadingCancellationViaMethodTimeout is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1852]
As seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1389/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:160)
```

I think I've seen it flake on my own machine as well.

**Comment by ejona86** [comment]
As seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1402/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:160)
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1539/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:160)
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1540/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:160)
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1542/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:160)
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1543/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:160)
```

**Comment by ejona86** [comment]
I think these may be triggered when more than one job runs simultaneously.

https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1619/console
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:159)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/143555657 (since rebuilt)
```
io.grpc.testing.integration.CascadingTest > testCascadingCancellationViaMethodTimeout FAILED
    java.lang.AssertionError: expected:<3> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.testing.integration.CascadingTest.testCascadingCancellationViaMethodTimeout(CascadingTest.java:161)
```

**Comment by pgrosu** [comment]
Hi Eric,

Try building it without the `-Porg.gradle.parallel=true` argument for `gradle`.  I am not getting any errors when building it in the following way on a Windows machine:

```
$ set GRADLE_OPTS=-Xmx2048m
$ gradlew clean build
```

Currently in your builds that throw an error have  the parallelization enabled as such (on the last line):

```
 $ cmd.exe /C "c:\jenkins\workspace\gRPC-Java-PR-Windows\gradlew.bat 
-DghprbCommentBody=null -DghprbTriggerAuthorEmail= -DghprbTargetBranch=master 
-DghprbSourceBranch=test-contexts -DghprbCredentialsId=73e5d438-7287-4de6-b89c-36d27b4a01c3 
'"-DghprbActualCommitAuthor=Eric Anderson"' -Dsha1=origin/pr/1851/merge 
'"-DghprbPullLongDescription=CC @louiscryan "' 
-DghprbPullLink=https://github.com/grpc/grpc-java/pull/1851 
-DghprbActualCommit=42b8fd4b0bea7a58d2c90dca96c75510400e7f03 
-DghprbTriggerAuthorLoginMention= 
-DghprbAuthorRepoGitUrl=https://github.com/ejona86/grpc-java.git 
-DGIT_BRANCH=test-contexts -DghprbPullAuthorEmail=ejona86@gmail.com 
-DghprbPullAuthorLogin=ejona86 -DghprbGhRepository=grpc/grpc-java 
-DghprbTriggerAuthor= -DghprbActualCommitAuthorEmail=ejona@google.com 
-DghprbPullId=1851 -DghprbTriggerAuthorLogin= -DghprbPullAuthorLoginMention=@ejona86 
'"-DghprbPullTitle=core: Add unit test for Contexts.interceptCall"' 
'"-DghprbPullDescription=GitHub pull request #1851 of 
commit 42b8fd4b0bea7a58d2c90dca96c75510400e7f03, no merge conflicts."' 
-Porg.gradle.parallel=true clean build && exit %%ERRORLEVEL%%"
```

Hope it helps,
Paul

**Comment by ejona86** [comment]
@pgrosu, thanks. I've also noticed that I can trigger the bug pretty reliably when more than one build of grpc is occurring at the same time. I've since changed the Windows Jenkins machine to only run one grpc build concurrently. However, that just works around the problem. The test needs to be fixed and made reliable; we want to be able to build concurrently and use gradle parallel.

**Comment by pgrosu** [comment]
I understand, and hopefully we can find a nice solution with the assumption that the following projects are [all decoupled](https://docs.gradle.org/current/userguide/multi_project_builds.html#sec:decoupled_projects) for properly building in parallel:

```
Root project 'grpc'
+--- Project ':grpc-all' - gRPC: All
+--- Project ':grpc-auth' - gRpc: Auth
+--- Project ':grpc-benchmarks' - grpc Benchmarks
+--- Project ':grpc-core' - gRPC: Core
+--- Project ':grpc-examples' - grpc Examples
+--- Project ':grpc-grpclb' - gRPC: GRPCLB LoadBalancer plugin
+--- Project ':grpc-interop-testing' - gRPC: Integration Testing
+--- Project ':grpc-netty' - gRPC: Netty
+--- Project ':grpc-okhttp' - gRPC: OkHttp
+--- Project ':grpc-protobuf' - gRPC: Protobuf
+--- Project ':grpc-protobuf-lite' - gRPC: Protobuf Lite
+--- Project ':grpc-protobuf-nano' - gRPC: Protobuf Nano
+--- Project ':grpc-services' - gRPC: Services
+--- Project ':grpc-stub' - gRPC: Stub
\--- Project ':grpc-testing' - gRPC: Testing
```

Gradle also makes use of the `CountDownLatch`, which could be interfering and below is a link to all the parts of the code where `CountDownLatch` is used in Gradle:

https://github.com/gradle/gradle/search?p=2&q=CountDownLatch+&utf8=%E2%9C%93

Though `org.gradle.parallel` works along project boundaries, it's good to be aware of the concerns of parallelizing tasks (which I'm sure might already be known):

https://github.com/gradle/gradle/blob/master/design-docs/parallel-task-execution.md
