### ISSUE TITLE
{Netty,OkHttp}TransportTest.serverNotListening is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#1877]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/1439/console

```
io.grpc.okhttp.OkHttpTransportTest > serverNotListening FAILED
    Wanted but not invoked:
    listener.transportTerminated();
    -> at io.grpc.internal.testing.AbstractTransportTest.serverNotListening(AbstractTransportTest.java:178)
    Actually, there were zero interactions with this mock.
```

**Comment by ejona86** [comment]
Haven't seen it again, so removing from 1.0.

**Comment by ejona86** [comment]
Now I saw it for NettyTransportTest...

https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2193/console
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    Wanted but not invoked:
    listener.transportTerminated();
    -> at io.grpc.internal.testing.AbstractTransportTest.serverNotListening(AbstractTransportTest.java:242)
    Actually, there were zero interactions with this mock.
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2863/console
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    Wanted but not invoked:
    listener.transportTerminated();
    -> at io.grpc.internal.testing.AbstractTransportTest.serverNotListening(AbstractTransportTest.java:244)
    Actually, there were zero interactions with this mock.
```

**Comment by ejona86** [comment]
Three more failures for Netty (all since rebuilt):
https://travis-ci.org/grpc/grpc-java/jobs/205145076
https://travis-ci.org/grpc/grpc-java/jobs/205060433
https://travis-ci.org/grpc/grpc-java/jobs/205060281

This one looks is different. But there isn't an obvious commit that caused it.

```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by dapengzhang0** [comment]
seen on v1.1.x branch
https://travis-ci.org/grpc/grpc-java/jobs/207498172

**Comment by dapengzhang0** [comment]
seen at https://travis-ci.org/grpc/grpc-java/jobs/209419648
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/210641666 (since rebuilt)
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/213508734 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/213069545 (since rebuilt). It seems to be impacting OS X the most.

**Comment by carl-mastrangelo** [comment]
```
Mar 23, 2017 3:41:56 PM io.grpc.netty.NettyServerHandler onConnectionError
WARNING: Connection Error
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:412)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:823)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:167)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769)
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1138)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1079)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

Mar 23, 2017 3:41:56 PM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 3
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:127)
	at io.grpc.netty.FixedHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(FixedHttp2ConnectionDecoder.java:570)
	at io.grpc.netty.FixedHttp2ConnectionDecoder$FrameReadListener.onDataRead(FixedHttp2ConnectionDecoder.java:188)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:425)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.grpc.netty.FixedHttp2ConnectionDecoder.decodeFrame(FixedHttp2ConnectionDecoder.java:119)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:341)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

Mar 23, 2017 3:41:57 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:39949
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

As seen locally.  It manifests as 
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```


I don't know why Netty thinks Stream 3 does not exist.  I suspect it is a race somewhere.  Also, we probably shouldn't be letting the exception fall off the pipeline with `onUnhandledInboundException`.

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/215772265 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/219365166

**Comment by ejona86** [comment]
Seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3195/console

**Comment by ejona86** [comment]
Seen for Netty at https://travis-ci.org/grpc/grpc-java/jobs/222884790 (since rebuilt)

```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ejona86** [comment]
Seen for Netty at https://travis-ci.org/grpc/grpc-java/jobs/222858684
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ericgribkoff** [comment]
See for Netty at https://travis-ci.org/grpc/grpc-java/jobs/227711103

**Comment by dapengzhang0** [comment]
Seen at 
https://travis-ci.org/grpc/grpc-java/jobs/229179943

```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/232522900
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ericgribkoff** [comment]
Seen for Netty at https://travis-ci.org/grpc/grpc-java/jobs/233000089 (since rebuilt)

```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ejona86** [comment]
Seen for netty at https://travis-ci.org/grpc/grpc-java/jobs/234095664
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```

**Comment by ejona86** [comment]
Seen for netty at https://travis-ci.org/grpc/grpc-java/jobs/240094429

**Comment by zpencer** [comment]
Found some additional output related to the error:
```
Jun 20, 2017 5:52:17 PM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
java.lang.IllegalStateException: Stream 3 in unexpected state: HALF_CLOSED_LOCAL
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:167)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:146)
	at io.grpc.netty.NettyServerHandler.sendResponseHeaders(NettyServerHandler.java:558)
	at io.grpc.netty.NettyServerHandler.write(NettyServerHandler.java:495)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:112)
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32)
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)

Jun 20, 2017 5:52:17 PM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 3
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:524)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:185)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:116)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:353)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)

Jun 20, 2017 5:52:17 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:38057
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	... 11 more


java.lang.AssertionError:  <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at io.grpc.internal.testing.AbstractTransportTest.assertCodeEquals(AbstractTransportTest.java:1357)
	at io.grpc.internal.testing.AbstractTransportTest.assertCodeEquals(AbstractTransportTest.java:1362)
	at io.grpc.internal.testing.AbstractTransportTest.serverNotListening(AbstractTransportTest.java:273)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:168)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


```

**Comment by zpencer** [comment]
The problem occurs because of this line in NettyClientTransport.java:
```
    // Start the connection operation to the server.
    channel.connect(address).addListener(new ChannelFutureListener() {
      @Override
      public void operationComplete(ChannelFuture future) throws Exception {
        if (!future.isSuccess()) {
          ChannelHandlerContext ctx = future.channel().pipeline().context(handler);
          if (ctx != null) {
            // NettyClientHandler doesn't propagate exceptions, but the negotiator will need the
            // exception to fail any writes. Note that this fires after handler, because it is as if
            // handler was propagating the notification.
            ctx.fireExceptionCaught(future.cause());
          }
          future.channel().pipeline().fireExceptionCaught(future.cause());
        }
      }
    });
```

In our unit test, the server is shut down, so the `connect()` is expected to fail. The connection attempt happens inside a netty thread, which will eventually get a failure, and handle it by tearing down the pipeline (removing all handlers). The race happens when all this takes place before we have a chance to `addListener`. If the pipeline is torn down by the time we add the listener, the future will be allowed run right away and `fireExceptionCaught` will be applied on an empty pipeline without any handlers present.

**Comment by nicolasnoble** [comment]
This is basically a race condition within the code of the test. The problem lies within the fact that it's valid to connect to your own socket:

```
#include <unistd.h>
#include <assert.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip.h>

int main() {
  int r;

  int sock = socket(AF_INET, SOCK_STREAM, 0);
  assert(sock >= 0);

  int enable = 1;
  r = setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &enable, sizeof(enable));
  assert(r == 0);

  struct sockaddr_in addr;
  addr.sin_family = AF_INET;
  addr.sin_port = htons(12345);
  addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

  r = bind(sock, (struct sockaddr *) &addr, sizeof(addr));
  assert(r == 0);
  r = connect(sock, (struct sockaddr *) &addr, sizeof(addr));
  assert(r == 0);

  char data_out = 0x42;
  r = send(sock, &data_out, sizeof(data_out), 0);
  assert(r == 1);

  char data_in = 0;
  r = recv(sock, &data_in, sizeof(data_in), 0);
  assert(r == 1);
  assert(data_in == 0x42);

  r = close(sock);
  assert(r == 0);
}
```

That code works fine, and all asserts pass. So the race is that you are creating a server, grab its port, then shut the server down. The port is no longer in use, so it's valid for the kernel to give it to you as your ephemeral port. And connecting to yourself in loopback is basically the same as creating a pipe.

**Comment by carl-mastrangelo** [comment]
Interesting.  I had always known that the 4-tuple would have have to be unique for the connection to be uniquely identified, but apparently it is the *socket pair* that is uniquely identified:

https://books.google.com/books?id=ptSC4LpwGA0C&pg=PA52&dq=socket+pair+tuple#v=onepage&q=socket%20pair%20tuple&f=false

**Comment by ejona86** [comment]
Nice job @zpencer for managing to capture a packet trace of a failure. That's what led us down this path of discovering this bizarre setup.

Now that we know what we're looking for, it seems this is discussed [on StackOverflow](https://stackoverflow.com/questions/17584383/why-can-a-socket-connect-to-its-own-ephemeral-port). The answer mentions that this appears to be covered in page 32 of https://www.ietf.org/rfc/rfc793.txt

You learn something every day. Removing `SO_REUSEADDR` on client-side should fix the problem. Now we'll just get to figure out who is setting REUSEADDR on the client channel.

**Comment by ejona86** [comment]
It seems like Java [enables `SO_REUSEADDR` by default on client connections](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/nio/ch/AsynchronousSocketChannelImpl.java#l509). That's where we're getting the setting. For the test, we can just set the Netty SocketOption to disable it.

**Comment by zpencer** [comment]
Looks like the combination of #3137 and #3122 were enough to fix the flaky test. The issue root caused by @nicolasnoble is a legitimate problem that can occur, but in an actual test environment, it is unlikely to happen. The way I hit it was by having several processes execute `serverNotListening` test in a tight loop, in an attempt to trigger the flake.

**Comment by dapengzhang0** [comment]
Seen again at https://travis-ci.org/grpc/grpc-java/jobs/268231091
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
263 tests completed, 1 failed, 1 skipped
:grpc-netty:test FAILED
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/268545284
```
io.grpc.netty.NettyTransportTest > serverNotListening FAILED
    java.lang.AssertionError: expected:<Status{code=UNAVAILABLE, description=null, cause=null}> but was:<Status{code=UNKNOWN, description=null, cause=java.nio.channels.ClosedChannelException
    	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
    }>
```
