### ISSUE TITLE
ConcurrencyTest.serverStreamingTest is flaky

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#1879]
Build failed at ConcurrencyTest
https://travis-ci.org/grpc/grpc-java/jobs/133222725

Not sure if it is a known issue.

```
io.grpc.testing.integration.ConcurrencyTest > serverStreamingTest FAILED
    java.lang.Exception: test timed out after 10000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at io.grpc.testing.integration.ConcurrencyTest.serverStreamingTest(ConcurrencyTest.java:197)
205 tests completed, 1 failed
:grpc-interop-testing:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':grpc-interop-testing:test'.
```

**Comment by dapengzhang0** [comment]
No 2nd occurrence seen/reported for over a year.
