### ISSUE TITLE
java.lang.IllegalArgumentException when try to use ipv6

### ISSUE THREAD

**Issue by normanmaurer** [grpc/grpc-java#1883]
I guess this is caused by the scopeId:

```
java.lang.IllegalArgumentException: cannot find a NameResolver for directaddress:////0:0:0:0:0:0:0:0%0:10005 (Malformed escape pair at index 33: directaddress:////0:0:0:0:0:0:0:0%0:10005)
at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:238)
at io.grpc.internal.ManagedChannelImpl.(ManagedChannelImpl.java:159)
at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:205)
```

**Comment by normanmaurer** [comment]
This was version 0.14.0

**Comment by ejona86** [comment]
What's better, is in this case (directaddress) we're actually trying to circumvent the NameResolver, so the URI is mostly unused.

**Comment by ejona86** [comment]
@zhangkun83, do you want to take a look at this?

**Comment by normanmaurer** [comment]
@ejona86 haha ok :)
