### ISSUE TITLE
Errors with concurrent server push

### ISSUE THREAD

**Issue by trask** [grpc/grpc-java#1905]
Hi, I'm getting errors when making concurrent server pushes to the same client connection.

You can see simplified repro here https://github.com/trask/grpc-concurrent-server-push-issue-repro

Just clone and run mvn test to see repro.

It is supposed to send 100 messages, but generally the client does not receive 100, and there are errors logged in the process, e.g.

```
Exception in thread "pool-3-thread-2" java.lang.IllegalStateException: Cannot transition phase from MESSAGE to HEADERS
        at io.grpc.internal.AbstractStream.verifyNextPhase(AbstractStream.java:403)
        at io.grpc.internal.AbstractStream.outboundPhase(AbstractStream.java:395)
        at io.grpc.internal.AbstractServerStream.writeHeaders(AbstractServerStream.java:99)
        at io.grpc.internal.ServerCallImpl.sendHeaders(ServerCallImpl.java:148)
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:276)
        at com.github.trask.ConcurrentServerPushTest.sendServerRequest(ConcurrentServerPushTest.java:67)
        at com.github.trask.ConcurrentServerPushTest.access$400(ConcurrentServerPushTest.java:19)
        at com.github.trask.ConcurrentServerPushTest$1.run(ConcurrentServerPushTest.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

and

```
WARNING: Failed to release a message: SlicedAbstractByteBuf(freed)
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:111)
        at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:62)
        at io.netty.buffer.CompositeByteBuf$Component.freeIfNecessary(CompositeByteBuf.java:1616)
        at io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:1881)
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:116)
        at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:62)
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84)
        at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:109)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:265)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:346)
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:321)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:859)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:375)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:826)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1436)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:161)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:381)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1129)
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:234)
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:131)
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:48)
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:58)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment]
Thank you again for the great reproduction!

It looks like you are calling StreamObserver.onNext from multiple threads concurrently. However, StreamObserver is not thread-safe.

I wrapped the onNext call with a `synchronized (server.responseObserver)` and the test seemed to became reliable.

**Comment by trask** [comment]
Ah, yes, I should have read the javadoc!

```
Since individual {@code StreamObserver}s are not thread-safe, if multiple threads will be
writing to a {@code StreamObserver} concurrently, the application must synchronize calls
```

Thanks for the quick response.

**Comment by mwmitchell** [comment]
The info here saved me a ton of time, thanks!
