### ISSUE TITLE
IllegalStateException still happening for io.grpc.internal.TransportSet$TransportListener.transportTerminated on 0.15.SNAPSHOT 

### ISSUE THREAD

**Issue by hanlongwang** [grpc/grpc-java#1929]
After pulling in https://github.com/grpc/grpc-java/commit/13fe13bf9f672496d997b327ba33283e19c95846 still getting this exception happening in some clients.

```
java.lang.IllegalStateException: Listener is still attached to activeTransport. Seems transportTerminated was not called.
     at com.google.common.base.Preconditions.checkState(SourceFile:173)
     at io.grpc.internal.TransportSet$TransportListener.transportTerminated(SourceFile:391)
     at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(SourceFile:647)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
```

**Comment by ejona86** [comment]
I can't see how this is happening from OkHttpClientTransport, since transportTerminated is only called once place and before it is called startGoAway is called which is guaranteed to call transportShutdown and seems to be properly synchronized. Maybe there is a bug in TransportSet or a synchronization problem.

**Comment by hanlongwang** [comment]
After closer look at the clients causing issues, it was clients still using the old gRPC 0.13.2 version. The crash report missed a version check in reporting the crashes, some of the crashes still coming in were from old clients. The stacktrace points to error message only found in 0.13.2 code. https://github.com/grpc/grpc-java/commit/13fe13bf9f672496d997b327ba33283e19c95846 most likely fixes this issue as @ejona86 indicated.
