### ISSUE TITLE
grpc-netty on maven central depends on netty 4.1.2 but code assumes 4.1.1

### ISSUE THREAD

**Issue by alugowski** [grpc/grpc-java#2031]
I noticed that the grpc-netty v0.15 package on Maven Central suggests using netty-4.1.2Final. However, we get the following exception when we use it. The cause appears to be that the code uses a DefaultHttp2HeadersDecoder constructor that takes 3 parameters, as supplied by netty 4.1.1, but netty 4.1.2 added a 4th parameter, hence the NoSuchMethodError.

Everything appears to work fine for me with netty 4.1.1Final.

java.lang.RuntimeException: java.lang.NoSuchMethodError: io.netty.handler.codec.http2.DefaultHttp2HeadersDecoder.<init>(IIZ)V
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
    at com.turn.platform.message.grpc.ExecutorGrpc$ExecutorBlockingStub.doExec(ExecutorGrpc.java:171)
....(our calling code)....
Caused by: java.lang.NoSuchMethodError: io.netty.handler.codec.http2.DefaultHttp2HeadersDecoder.<init>(IIZ)V
    at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:118)
    at io.grpc.netty.NettyClientTransport.newHandler(NettyClientTransport.java:250)
    at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:140)
    at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:45)
    at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:206)
    at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java:179)
    at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:476)
    at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:432)
    at io.grpc.DummyLoadBalancerFactory$DummyLoadBalancer.pickTransport(DummyLoadBalancerFactory.java:105)
    at io.grpc.internal.ManagedChannelImpl$1.get(ManagedChannelImpl.java:149)
    at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:201)
    at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:248)
    at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:227)
    at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:186)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
    ... 10 more

**Comment by buchgr** [comment]
gRPC v0.15 does NOT depend on netty 4.1.2.Final, but on 4.1.1.Final. I suspect that your project is pulling in the the 4.1.2.Final dependency.

4.1.2.Final support is not merged yet https://github.com/grpc/grpc-java/pull/1999

**Comment by buchgr** [comment]
Also see the v0.15 source code https://github.com/grpc/grpc-java/blob/v0.15.0/build.gradle#L151

Closing this issue. Please reopen if I understood something wrong. Thanks!

**Comment by ejona86** [comment]
The real source-of-truth would be maven itself, [which does show 4.1.1](https://repo1.maven.org/maven2/io/grpc/grpc-netty/0.15.0/grpc-netty-0.15.0.pom).

**Comment by alugowski** [comment]
Gotcha, so my misinformation is due to Maven Central's funny UI:
http://mvnrepository.com/artifact/io.grpc/grpc-netty/0.15.0
Note how it lists 4.1.2 in the "Updates" column. It's entirely unclear to me what that column is supposed to be, I took it to mean "it's ok to use this newer version too".

(I'm doing dependency resolution manually due to the historical nature of my company's build system that predates maven/grade by a long ways).

Sorry for the false alarm!
