### ISSUE TITLE
TLS communication error between grpc-java client to golang server 

### ISSUE THREAD

**Issue by xspeedcruiser** [grpc/grpc-java#2068]
I get the following error when establishing a connection between a grpc-java client and a golang grpc server. 

```
Jul 19, 2016 5:52:49 PM io.grpc.internal.TransportSet$1 call
INFO: Created transport io.grpc.netty.NettyClientTransport@7e72c234(/127.0.0.1:30303) for /127.0.0.1:30303
Jul 19, 2016 5:52:49 PM io.grpc.internal.TransportSet$TransportListener transportShutdown
INFO: Transport io.grpc.netty.NettyClientTransport@7e72c234(/127.0.0.1:30303) for /127.0.0.1:30303 is being shutdown
Jul 19, 2016 5:52:49 PM io.grpc.internal.TransportSet$TransportListener transportTerminated
INFO: Transport io.grpc.netty.NettyClientTransport@7e72c234(/127.0.0.1:30303) for /127.0.0.1:30303 is terminated
Jul 19, 2016 5:52:49 PM io.netty.handler.codec.http2.Http2ConnectionHandler processGoAwayWriteResult
WARNING: [id: 0x065e63d9, L:0.0.0.0/0.0.0.0:60630 ! R:/127.0.0.1:30303] Sending GOAWAY failed: lastStreamId '0', errorCode '1', debugData 'First received frame was not SETTINGS. Hex dump for first 5 bytes: 1503010002'. Forcing shutdown of the connection.
java.io.IOException: Broken pipe
    at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
    at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
    at sun.nio.ch.IOUtil.write(IOUtil.java:148)
    at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
    at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:305)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:839)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:311)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:806)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1436)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:347)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:395)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:259)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:546)
    at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:216)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:392)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by carl-mastrangelo** [comment]
Can you provide a snippet of code where you setup your client?

**Comment by xspeedcruiser** [comment]
Here is the code snippet, 
```
	public ManagedChannel newPeerClientConnection() {
		NettyChannelBuilder builder = NettyChannelBuilder.forAddress(host, port);
		try {

			SslContext sslContext = GrpcSslContexts.forClient().trustManager(
					new File("/path/to/cert.pem")).build();
			builder.negotiationType(NegotiationType.TLS);
			builder.sslContext(sslContext);
		} catch (SSLException e) {
			logger.error("failed connect to peer with SSLException", e);
		}
	return builder.build();
}

```

**Comment by carl-mastrangelo** [comment]
Hmm, aside from ignoring the SSL error that seems right.  What about the Go server setup?

**Comment by xspeedcruiser** [comment]
@carl-mastrangelo The go server code is part of a larger codebase called fabric project under hyperledger.

The main crux is in the effect,
```
creds, err := credentials.NewServerTLSFromFile("cert/file", "key/file")
opts = []grpc.ServerOption{grpc.Creds(creds)}

grpcServer := grpc.NewServer(opts...)

lis, err := net.Listen("tcp", listenAddr)

serve := make(chan error)


	go func() {
		var grpcErr error
		if grpcErr = grpcServer.Serve(lis); grpcErr != nil {
			grpcErr = fmt.Errorf("grpc server exited with error: %s", grpcErr)
		} else {
			logger.Info("grpc server exited")
		}
		serve <- grpcErr
	}()
```

**Comment by rasmustrew** [comment]
@xspeedcruiser Did you find a solution? Having the same problem right now.

**Comment by michaeldowling** [comment]
@rasmustrew @xspeedcruiser Any of you discover a solution to this problem?  Having issues running into this exact error message while playing with the hyperledger/fabric-sdk-java library.

**Comment by xspeedcruiser** [comment]
@rasmustrew @michaeldowling I had to use a specific version of the grpc and protobuf to make it work. You can take a look at this commit https://github.com/hyperledger/fabric/commit/d39194ce97d8debc9e38b6eff0972a9404a5fd71

I think it was a problem with the handshake failing because of the version mismatch between different components.

**Comment by ejona86** [comment]
The "Broken pipe" could be ignored. The transport was being disconnected for other reasons. Based on the code linked, it appears `overrideAuthority()` was necessary, which makes sense and is "normal" in many situations. Doesn't seem there is any bug here. Closing.
