### ISSUE TITLE
HandlerRegistryBenchmark always fails

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#2088]
HandlerRegistryBenchmark always fails to run because MethodDescriptor expects a non-null request marshaller:

```
java.lang.NullPointerException: requestMarshaller
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
    at io.grpc.MethodDescriptor.<init>(MethodDescriptor.java:161)
    at io.grpc.MethodDescriptor.create(MethodDescriptor.java:151)
    at io.grpc.benchmarks.netty.HandlerRegistryBenchmark.setup(HandlerRegistryBenchmark.java:91)
    at io.grpc.benchmarks.netty.generated.HandlerRegistryBenchmark_lookupMethod_jmhTest._jmh_tryInit_f_handlerregistrybenchmark0_G(HandlerRegistryBenchmark_lookupMethod_jmhTest.java:395)
    at io.grpc.benchmarks.netty.generated.HandlerRegistryBenchmark_lookupMethod_jmhTest.lookupMethod_Throughput(HandlerRegistryBenchmark_lookupMethod_jmhTest.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:430)
    at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:412)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Probably easy enough to fix by adding one.

**Comment by carl-mastrangelo** [comment]
Fixed in #2625
