### ISSUE TITLE
Flaky CompressionTest

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#2157]
Found in https://travis-ci.org/grpc/grpc-java/jobs/151357545

```
io.grpc.testing.integration.CompressionTest > compression[23] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:369)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:217)
        Caused by:
        io.grpc.StatusRuntimeException: INTERNAL: Can't decode compressed frame as compression not configured.
```

**Comment by ejona86** [comment]
Also seen at:
https://travis-ci.org/grpc/grpc-java/jobs/149904961
https://travis-ci.org/grpc/grpc-java/jobs/156283171 (since rebuilt)

**Comment by kleinsch** [comment]
Just saw this in our client code that's using compression.

```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Can't decode compressed frame as compression not configured.
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/193463553
```
io.grpc.testing.integration.CompressionTest > compression[55] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:217)
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/194406178 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[53] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:217)
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/199772967 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[29] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by ejona86** [comment]
Saw locally
```
io.grpc.testing.integration.CompressionTest > compression[31] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/201671806 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[31] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[53] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/196727280 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[21] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by lukaszx0** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/202063556

```
io.grpc.testing.integration.CompressionTest > compression[63] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by carl-mastrangelo** [comment]
After looking at the code, I don't think this is a compression bug, it just looks like the message coding is "identity".  That should be allowed,

**Comment by ejona86** [comment]
I saw this again today. But trying to reproduce it reliably is proving difficult. We've run the tests 1000s of times hoping to see it fail, to not avail.

I did notice that the `stream.cancel()` [when decompressor isn't found](https://github.com/grpc/grpc-java/blob/89bc2cd3b23d583387d104bb1ca6ec86ad9816be/core/src/main/java/io/grpc/internal/ClientCallImpl.java#L440) would be racy because deframing continues (we should probably use `deframeFailed()` instead of `cancel()`), but it doesn't seem like that code path should be executed in these tests.

**Comment by ejona86** [comment]
I think we should include a nested exception [in the Status](https://github.com/grpc/grpc-java/blob/v1.1.0/core/src/main/java/io/grpc/internal/MessageDeframer.java#L376), so that we have a bit more of an idea of what the call-chain is. Unfortunately I think that won't be enough by itself.

Seen at https://travis-ci.org/grpc/grpc-java/jobs/205611861 (since rebuilt).

```
io.grpc.testing.integration.CompressionTest > compression[21] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[29] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[53] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[55] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by carl-mastrangelo** [comment]
The cause is explicitly dropped, and was raised in https://github.com/grpc/grpc-java/issues/2631

**Comment by ejona86** [comment]
No, that's not how it's intended to work. The Status itself should have a cause.

Seen at https://travis-ci.org/grpc/grpc-java/jobs/205173669 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[21] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[31] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[55] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[61] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/206266161 (since rebuilt)

```
io.grpc.testing.integration.CompressionTest > compression[21] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
io.grpc.testing.integration.CompressionTest > compression[29] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:214)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/207258712 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[29] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:215)
io.grpc.testing.integration.CompressionTest > compression[61] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$2: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:215)
```

**Comment by dapengzhang0** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/208287108

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/211504397

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/208306434 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/210696967 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/208264574 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/220664819

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/222158541 (since rebuilt)

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/226162932 (since rebuilt)

```
io.grpc.testing.integration.CompressionTest > compression[21] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:215)
io.grpc.testing.integration.CompressionTest > compression[53] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:215)
io.grpc.testing.integration.CompressionTest > compression[61] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:215)
io.grpc.testing.integration.CompressionTest > compression[63] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:215)
```

**Comment by dapengzhang0** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/226484553

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/234674642 (since rebuilt)

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/240589659

**Comment by ericgribkoff** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/242095619

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/242094277 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[23] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
io.grpc.testing.integration.CompressionTest > compression[55] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
io.grpc.testing.integration.CompressionTest > compression[61] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/241360564 (since rebuilt)
```
io.grpc.testing.integration.CompressionTest > compression[31] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
io.grpc.testing.integration.CompressionTest > compression[53] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
io.grpc.testing.integration.CompressionTest > compression[63] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
```

**Comment by dapengzhang0** [comment]
seen at https://travis-ci.org/grpc/grpc-java/jobs/243752250
the same stacktrace

**Comment by ericgribkoff** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/244753819

```
io.grpc.testing.integration.CompressionTest > compression[55] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
         io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)

io.grpc.testing.integration.CompressionTest > compression[63] FAILED
    io.grpc.StatusRuntimeException: INTERNAL: io.grpc.netty.NettyClientTransport$3: Can't decode compressed frame as compression not configured.
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
        at io.grpc.testing.integration.CompressionTest.compression(CompressionTest.java:200)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/244789035

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/248507697 (since rebuilt)

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/248515732 (since rebuilt) (on the v1.3.x branch)

**Comment by dapengzhang0** [comment]
seen at https://travis-ci.org/grpc/grpc-java/jobs/247754159
