### ISSUE TITLE
io.grpc.testing.integration.ProxyTest.smallLatency is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2176]
As seen at https://grpc-testing.appspot.com/job/gRPC-Java-master-windows/359/console

```
io.grpc.testing.integration.ProxyTest > smallLatency FAILED
    java.lang.AssertionError: expected:<1.0E7> but was:<2.65721E7>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:519)
        at org.junit.Assert.assertEquals(Assert.java:609)
        at io.grpc.testing.integration.ProxyTest.smallLatency(ProxyTest.java:94)
```

CC @mfcripps

**Comment by mfcripps** [comment]
Opened a PR, linked above

**Comment by ejona86** [comment]
I saw this again at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3128/console
```
io.grpc.testing.integration.ProxyTest > smallLatency FAILED
    java.lang.AssertionError: expected:<5.0E7> but was:<1.053576E8>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:519)
        at org.junit.Assert.assertEquals(Assert.java:609)
        at io.grpc.testing.integration.ProxyTest.smallLatency(ProxyTest.java:106)
```
