### ISSUE TITLE
Occasional IllegalStateException during shutdown after upgrading to 1.0.0

### ISSUE THREAD

**Issue by trask** [grpc/grpc-java#2188]
Hi, after upgrading from 0.15.0 to 1.0.0, I'm seeing occasional `IllegalStateException` during shutdown (makes my tests fail which is why I notice).  I had not seen this previously with 0.15.0.

```
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:159)
	at io.grpc.internal.DelayedClientTransport.startBackoff(DelayedClientTransport.java:323)
	at io.grpc.internal.TransportSet$2.run(TransportSet.java:281)
	at io.grpc.internal.TransportSet$TransportListener.transportShutdown(TransportSet.java:461)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:68)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyTerminated(ClientTransportLifecycleManager.java:84)
	at io.grpc.netty.NettyClientTransport$4.operationComplete(NettyClientTransport.java:181)
	at io.grpc.netty.NettyClientTransport$4.operationComplete(NettyClientTransport.java:175)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:488)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
	at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.fail(ProtocolNegotiators.java:436)
	at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.exceptionCaught(ProtocolNegotiators.java:376)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:266)
	at io.grpc.netty.NettyClientTransport$3.operationComplete(NettyClientTransport.java:165)
	at io.grpc.netty.NettyClientTransport$3.operationComplete(NettyClientTransport.java:156)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:129)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:588)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I was able to capture under a debugger and the existing `backoffStatus` was

```
Status{code=UNAVAILABLE, description=Channel in TRANSIENT_FAILURE state, cause=io.grpc.StatusRuntimeException: UNAVAILABLE}
```

Let me know if there's additional info I can provide to help diagnose.

Thanks,
Trask

**Comment by dapengzhang0** [comment]
This could be a race condition introduced in fixing issue #2152

**Comment by dapengzhang0** [comment]
we are looking into the issue. @trask the debugger information is very helpful for us to find the cause. There is a race condition for DelayedClientTransport.startBackoff introduced in 1.0.0, probably when multiple transports sharing the same DelayedTransport call TransportSet$TransportListener.transportShutdown and then schedule a back-off in which startBackoff does not run immediately, and endBackoff can possibly run ahead of it.
