### ISSUE TITLE
Android HelloWorld example release build is broken

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2207]
When trying to send the RPC it crashes with:

```
08-26 12:45:47.761  6837  6837 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'io.grpc.l io.grpc.l.a()' on a null object reference
08-26 12:45:47.761  6837  6837 E AndroidRuntime:    at io.grpc.helloworldexample.b.a(Unknown Source)
08-26 12:45:47.761  6837  6837 E AndroidRuntime:    at io.grpc.helloworldexample.b.onPostExecute(Unknown Source)
08-26 12:45:47.761  6837  6837 E AndroidRuntime:    at android.os.AsyncTask.finish(AsyncTask.java:651)
...
```

After fixing the NPE (caused by calling `shutdown()` on a `null` `ManagedChannel`), then it gracefully fails with:

```
Failed... :
io.grpc.p: No functional channel service provider found. Try adding a dependency on the grpc-okhttp or grpc-netty artifact
```

okhttp is not included after ProGuard. However, android-interop-testing doesn't suffer from the same issue, and I don't understand how. For android-interop-testing, I do see OkHttpChannelBuilder in mapping.txt, but I don't see OkHttpChannelProvider. Maybe it is being inlined. But I don't know why it would be included for one application but not for the other. I do know that android-interop-testing includes a cast to OkHttpChannelBuilder, but it seems like the provider should still break. The only reference to OkHttpChannelProvider in a `Class.forName()` in ManagedChannelProvider.

CC @zsurocking

**Comment by ejona86** [comment]
FYI, a workaround is to add this to the ProGuard configuration:
```
-keep class io.grpc.internal.DnsNameResolverProvider
-keep class io.grpc.okhttp.OkHttpChannelProvider
```

**Comment by ejona86** [comment]
I've been pointed to https://sourceforge.net/p/proguard/bugs/418/ , which confirmed a suspicion that ProGuard only handles the singe-arg version of Class.forName(). That is unfortunate, because it makes testing pretty painful, such that we may need to drop the tests.
