### ISSUE TITLE
Http2ChannelClosedException instead of actual failure

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2279]
This is similar to #1330, but for when the stream was never actually sent because of MAX_CONCURRENT_STREAMS.

In this case, we do know more information: the stream was never sent, so it is safe to retry. While that information is useful internally, the user probably would like to know the cause of connection closure. (In this case, I think it was a TCP timeout, because the network was flaky.) We should probably just swap out the exception in the same way we do with ClosedChannelException. At the very least, it should be UNAVAILABLE instead of INTERNAL.

This was seen in grpc-java v1.0.0:
```
Status{code=INTERNAL, description=null, cause=io.netty.handler.codec.http2.StreamBufferingEncoder$Http2ChannelClosedException: Connection closed}
io.netty.handler.codec.http2.StreamBufferingEncoder$Http2ChannelClosedException: Connection closed
	at io.netty.handler.codec.http2.StreamBufferingEncoder.close(StreamBufferingEncoder.java:224)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:176)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:372)
	at io.grpc.netty.NettyClientHandler.channelInactive(NettyClientHandler.java:298)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:234)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:723)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:234)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:255)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at java.lang.Thread.run(Thread.java:745)
```

CC @buchgr, any thoughts?

**Comment by buchgr** [comment]
> We should probably just swap out the exception in the same way we do with ClosedChannelException.

SGTM. This was triggered by channel inactive, so at this point we should already know about the real cause in the lifecycle manager.
