### ISSUE TITLE
Grpc server uses more memory than -Xmx

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#2289]
Sometimes Grpc server can use (couple of Gb) more memory than JVM max heap size. Does anyone know how could that happen? What is the recommended Jvm heap size configuration for Grpc servers?

**Comment by carl-mastrangelo** [comment]
There are a few other memory regions the JVM uses.  There is Meta space (previously permgen) where JIT'ed code gets placed.  This is usually small and not what you are looking for.  


gRPC uses a lot of off heap (a.k.a. "direct") memory for reading from and writing to the network.  You can limit this by setting `-XX:MaxDirectMemorySize=1024m`.  Direct memory is faster in Java, because it avoids an extra copy when reading data from the network.

**Comment by biran0079** [comment]
Hi @carl-mastrangelo, Thanks for the fast response!
I tried to set `-XX:MaxDirectMemorySize=1024m` in my application and I got `OutOfMemoryError: Direct buffer memory`.
I understand that 1024m is not the best limit for my application and I probably need to spend some time tuning it.

There are still things I really want to know.
How does grpc/netty allocate buffer pool memory? Is it fixed size pool per channel or per request or per thread or just allocate on demand? What's the best way to estimate the buffer pool size I need?

**Comment by carl-mastrangelo** [comment]
Please provide the stack traces of the OOM.

**Comment by biran0079** [comment]
```
ERROR [2016-09-21 15:07:43,063] io.grpc.internal.SerializingExecutor: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@4f325840 [req=null firm=null cred=null ip=null]
! java.lang.RuntimeException: java.lang.OutOfMemoryError: Direct buffer memory
! at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:164) ~[grpc-core.jar:0.14.0]
! at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:279) ~[grpc-stub.jar:0.14.0]
! at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_101]
! at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_101]
! at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_101]
! at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_101]
! at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_101]
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_101]
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_101]
! at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_101]
! at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_101]
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_101]
! at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_101]
! at com.addepar.services.snapshots.server.SnapshotServiceImpl.getSnapshots(SnapshotServiceImpl.java:161) ~[snapshots.jar:na]
! at com.addepar.services.snapshots.proto.SnapshotServiceGrpc$MethodHandlers.invoke(SnapshotServiceGrpc.java:547) ~[proto.jar:na]
! at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:151) ~[grpc-stub.jar:0.14.0]
! at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:48) ~[grpc-core.jar:0.14.0]
! at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:38) ~[grpc-core.jar:0.14.0]
! at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:55) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:259) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:464) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:54) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154) ~[grpc-core.jar:0.14.0]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
! Caused by: java.lang.OutOfMemoryError: Direct buffer memory
! at java.nio.Bits.reserveMemory(Bits.java:693) ~[na:1.8.0_101]
! at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.8.0_101]
! at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[na:1.8.0_101]
! at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:688) ~[netty-all.jar:4.1.0.CR7]
! at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237) ~[netty-all.jar:4.1.0.CR7]
! at io.netty.buffer.PoolArena.allocate(PoolArena.java:213) ~[netty-all.jar:4.1.0.CR7]
! at io.netty.buffer.PoolArena.allocate(PoolArena.java:141) ~[netty-all.jar:4.1.0.CR7]
! at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262) ~[netty-all.jar:4.1.0.CR7]
! at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) ~[netty-all.jar:4.1.0.CR7]
! at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115) ~[netty-all.jar:4.1.0.CR7]
! at io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:66) ~[grpc-netty.jar:0.14.0]
! at io.grpc.internal.MessageFramer.writeKnownLength(MessageFramer.java:188) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:147) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:124) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:172) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.AbstractServerStream.writeMessage(AbstractServerStream.java:110) ~[grpc-core.jar:0.14.0]
! at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:157) ~[grpc-core.jar:0.14.0]
! ... 25 common frames omitted
```

**Comment by carl-mastrangelo** [comment]
Hmm, I thought there was a memory limiter in Netty's code, but that does not appear to be the case.

I picked 1024m as a very big number, are you sending about that much data at a time?  Otherwise, that would imply a leak.  Also, it seems like you are using an older version of gRPC and Netty, can you try it with 1.0.0 ?

**Comment by biran0079** [comment]
We use GRPC to stream large amount of data.
The peak network out of one GRPC server can go up to over 600 of Mb/s. QPS is less than 10 most of the time.

**Comment by biran0079** [comment]
The root cause is found.
The server streams too much data without flow control, and  responses get buffered up faster then network can send.
The problem is fixed with flow control using `ServerCallStreamObserver#setOnReadyHandler`.
