### ISSUE TITLE
Flaky Test: io.grpc.netty.NettyTransportTest > openStreamPreventsTermination FAILED

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#2335]
Seen in https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2337/console

```
io.grpc.netty.NettyTransportTest > openStreamPreventsTermination FAILED
    java.io.IOException: Failed to bind

        Caused by:
        java.net.BindException: Address already in use: bind

    java.lang.AssertionError

187 tests completed, 1 failed, 3 skipped
:grpc-netty:test FAILED
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2389/console
```
io.grpc.netty.NettyTransportTest > openStreamPreventsTermination FAILED
    java.io.IOException: Failed to bind

        Caused by:
        java.net.BindException: Address already in use: bind
```

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2532/console
```
io.grpc.netty.NettyTransportTest > openStreamPreventsTermination FAILED
    java.io.IOException: Failed to bind

        Caused by:
        java.net.BindException: Address already in use: bind

    java.lang.AssertionError
```

**Comment by ejona86** [comment]
Comment from #2483:
> AbstractTransportTest does use port 0. However, some tests confirm that ports were released at appropriate times, so they manually re-use a selected port. Windows aggressively recycles ports when using 0; if you close a port and then something opens a new port 0, they are highly likely to get the same port. This rapid recycling of the same port means the test is much more flaky than we would want, because if any other service opens port 0, it will "steal" the selected port.

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3916/console

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4004/console

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4118/console

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/146/
```
java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:182)
	at io.grpc.internal.testing.AbstractTransportTest.openStreamPreventsTermination(AbstractTransportTest.java:353)
...
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
```

**Comment by ejona86** [comment]
https://kokoro2.corp.google.com/job/grpc/job/java/job/v1.7.x/job/windows/job/release/job/windows/4/

**Comment by ejona86** [comment]
https://kokoro2.corp.google.com/job/grpc/job/java/job/master/job/windows/job/presubmit/job/windows/347/

**Comment by ejona86** [comment]
https://kokoro2.corp.google.com/job/grpc/job/java/job/master/job/windows/job/presubmit/job/windows/508/

**Comment by ejona86** [comment]
https://kokoro2.corp.google.com/job/grpc/job/java/job/master/job/windows/87/

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/703f03ff-0baa-4f07-905a-64bed691c91d

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/b55b19b7-1b53-4859-b943-b0bd658f7c01

**Comment by carl-mastrangelo** [comment]
Some debugging:  It seems that the JVM sets `SO_EXCLUSIVEADDRUSE` which the docs say can prevent the socket from closing in time.  This doesn't explain why it doesn't *always* fail; it is surprising that it usually succeeds.
