### ISSUE TITLE
Include SETTINGS_MAX_HEADER_LIST_SIZE in initial SETTINGS.

### ISSUE THREAD

**Issue by buchgr** [grpc/grpc-java#2350]
We currently don't send `SETTINGS_MAX_HEADER_LIST_SIZE` as part of the initial `SETTINGS` frame, although we enforce it on the decoder. This is valid as of the H2 spec

> For any given request, a lower limit than what is advertised MAY be enforced. The initial value of this setting is unlimited.

However, we would argue that we should still include it in the initial `SETTINGS` frame, cause why not? If both endpoints are gRPC Java, it would also give us better error messages, as then the local encoder would enforce the remote decode limit [1]. However, we can't currently do that cause it seems like a bug in Netty that the encoder throws a connection error and not a stream error [1], bringing down the whole connection, while only the stream should fail. I ll open a issue/PR in Netty.

[1] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/internal/hpack/Encoder.java#L126

**Comment by buchgr** [comment]
Opened Netty PR netty/netty#5919

**Comment by ejona86** [comment]
Does anything need to be done here? Will the next update of Netty "just work"?

**Comment by buchgr** [comment]
@ejona86 We need to include the max header list value in the initial settings. So add one line in client handler and one line in server handler. [1]

```
initialSettings.maxHeaderListSize(maxHeaderListSize);
```

[1] https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L156

**Comment by lukaszx0** [comment]
For posterity and people that are using versions per `1.2.x`.

This fixes following stream error which gets thrown when header size is exceeded:

```Mar 14, 2017 3:53:36 PM io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException: Header size exceeded max allowed size (8192)
at io.netty.handler.codec.http2.Http2Exception.headerListSizeError(Http2Exception.java:169)
at io.netty.handler.codec.http2.Http2CodecUtil.headerListSizeExceeded(Http2CodecUtil.java:252)
at io.netty.handler.codec.http2.internal.hpack.Encoder.encodeHeadersEnforceMaxHeaderListSize(Encoder.java:128)
at io.netty.handler.codec.http2.internal.hpack.Encoder.encodeHeaders(Encoder.java:112)
at io.netty.handler.codec.http2.DefaultHttp2HeadersEncoder.encodeHeaders(DefaultHttp2HeadersEncoder.java:69)
at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeHeadersInternal(DefaultHttp2FrameWriter.java:435)
  ...```
