### ISSUE TITLE
Handle java.lang.IllegalStateException properly

### ISSUE THREAD

**Issue by ChangshinLee-NBT** [grpc/grpc-java#2363]
I'm currently using gRPC on Android, and it crashes due to the following exceptions:

Case 1: 

```
Fatal Exception: java.lang.IllegalStateException: activeTransport still points to the delayedTransport. Seems transportShutdown() was not called.
       at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
       at io.grpc.internal.TransportSet$TransportListener.transportTerminated(TransportSet.java:495)
       at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:759)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Case 2:

```
Fatal Exception: java.lang.IllegalStateException
       at com.google.common.base.Preconditions.checkState(Preconditions.java:159)
       at io.grpc.internal.DelayedClientTransport.startBackoff(DelayedClientTransport.java:324)
       at io.grpc.internal.TransportSet$2.run(TransportSet.java:297)
       at io.grpc.internal.TransportSet$TransportListener.transportShutdown(TransportSet.java:477)
       at io.grpc.okhttp.OkHttpClientTransport.startGoAway(OkHttpClientTransport.java:568)
       at io.grpc.okhttp.OkHttpClientTransport.access$1400(OkHttpClientTransport.java:98)
       at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:752)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Is there any way to handle these exceptions before crashing?

Thanks in advance.

**Comment by ejona86** [comment]
Those are bugs. What version of gRPC are you using?

**Comment by ChangshinLee-NBT** [comment]
I am using 1.0.1.

**Comment by xuguobiao** [comment]
I have the same problems like yours. And here is another case:

`io.grpc.StatusRuntimeException:INTERNAL: Failed to frame message
io.grpc.Status.io.grpc.StatusRuntimeException asRuntimeException()(SourceFile:536)
......
java.lang.IllegalStateException:Did not write as much data as expected.
com.google.protobuf.nano.CodedOutputByteBufferNano.void checkNoSpaceLeft()(SourceFile:907)
io.grpc.protobuf.nano.NanoProtoInputStream.int read(byte[],int,int)(SourceFile:89)
java.io.InputStream.read(InputStream.java:162)
com.google.common.io.ByteStreams.long copy(java.io.InputStream,java.io.OutputStream)(SourceFile:110)
io.grpc.internal.MessageFramer.int writeToOutputStream(java.io.InputStream,java.io.OutputStream)(SourceFile:232)
io.grpc.internal.MessageFramer.int writeKnownLength(java.io.InputStream,int,boolean)(SourceFile:193)
io.grpc.internal.MessageFramer.int writeUncompressed(java.io.InputStream,int)(SourceFile:149)
io.grpc.internal.MessageFramer.void writePayload(java.io.InputStream)(SourceFile:126)
io.grpc.internal.AbstractStream.void writeMessage(java.io.InputStream)(SourceFile:172)
io.grpc.internal.DelayedStream$3.void run()(SourceFile:201)
io.grpc.internal.DelayedStream.void drainPendingCalls()(SourceFile:121)
io.grpc.internal.DelayedStream.void setStream(io.grpc.internal.ClientStream)(SourceFile:90)
io.grpc.internal.DelayedClientTransport$PendingStream.void createRealStream(io.grpc.internal.ClientTransport)(SourceFile:383)
io.grpc.internal.DelayedClientTransport$PendingStream.access$100(SourceFile:370)
io.grpc.internal.DelayedClientTransport$2.void run()(SourceFile:262)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)`

**Comment by carl-mastrangelo** [comment]
@xuguobiao that looks like a different bug, something with the nano proto encoder.

**Comment by xuguobiao** [comment]
@carl-mastrangelo could you help me to figure out the crash logs i post in issue #2346. ( proguard, mutidex used in my app).

**Comment by ericgribkoff** [comment]
I'm marking this closed as obsolete; if the issue still persists (last commented upon in late 2016) we can re-open.
