### ISSUE TITLE
OutOfDirectMemoryError in fast stream objects generation

### ISSUE THREAD

**Issue by jonnyzzz** [grpc/grpc-java#2379]
I send a message to a bidi-stream method from a server to a client. 
Each message contains 1kb of bytes + several fields. 
Server implementation sends 2GB of such messages from a loop without delay
Client consumes messages without delay too. 

Currently it fails on the server with a netty error
```
INFO: [ManagedChannelImpl@39b43d60] Created with target 127.0.0.1:5656
java.lang.RuntimeException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3808428319, max: 3817865216)
	at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:153)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:287)
	at jetbrains.vcs.server.hosting.rpc.MockSSHServer$ssh$1$onNext$1.run(test.kt:152)
	at jetbrains.vcs.server.test.util.ThreadsUtil.lambda$catchAllAsRunnable$3(ThreadsUtil.java:77)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3808428319, max: 3817865216)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:613)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:567)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:686)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:675)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:213)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	at io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:66)
	at io.grpc.internal.MessageFramer.writeKnownLength(MessageFramer.java:190)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:149)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:126)
	at io.grpc.internal.AbstractStream2.writeMessage(AbstractStream2.java:70)
	at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:146)
	... 4 more
```

Quickly checked the code. Not sure if it is able to limit sending buffer by blocking a `StreamObserver#onNext` calls once sending buffer is full. 

macos 10.12, java 1.8.0_66, 16GB RAM

**Comment by jonnyzzz** [comment]
Duplicates https://github.com/grpc/grpc-java/issues/2247
