### ISSUE TITLE
Error on gradlew build

### ISSUE THREAD

**Issue by nagamanikandank** [grpc/grpc-java#2394]
I am getting the attached error on building the examples. I have `gradle.properties` file in `grpc-java\examples` folder that has one property , which is `skipCodegen=true`

```
C:\gRPC\grpc-java\examples>gradlew build --stacktrace
:extractIncludeProto UP-TO-DATE
:extractProto UP-TO-DATE
:generateProto UP-TO-DATE
:compileJava
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:299: error: illegal character: '\u2020'
      double ╧å1 = toRadians(lat1);
              ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:300: error: illegal character: '\u2020'
      double ╧å2 = toRadians(lat2);
              ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:301: error: illegal character: '\u201d'
      double ╬ö╧å = toRadians(lat2 - lat1);
              ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:301: error: illegal character: '\u2020'
      double ╬ö╧å = toRadians(lat2 - lat1);
                ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:301: error: not a statement
      double ╬ö╧å = toRadians(lat2 - lat1);
               ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:302: error: illegal character: '\u201d'
      double ╬ö╬╗ = toRadians(lon2 - lon1);
              ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:302: error: illegal character: '\u00bb'
      double ╬ö╬╗ = toRadians(lon2 - lon1);
                ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:302: error: not a statement
      double ╬ö╬╗ = toRadians(lon2 - lon1);
               ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u201d'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                      ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u2020'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                        ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: not a statement
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                       ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u201d'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                      ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u2020'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                        ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: not a statement
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                       ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u2020'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                      ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: not a statement
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                       ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: ';' expected
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                        ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u2020'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                 ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: not a statement
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                  ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: ';' expected
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                   ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u201d'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                            ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u00bb'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                              ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: not a statement
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                             ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u201d'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                                            ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: illegal character: '\u00bb'
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                                              ^
C:\gRPC\grpc-java\examples\src\main\java\io\grpc\examples\routeguide\RouteGuideServer.java:304: error: not a statement
      double a = sin(╬ö╧å / 2) * sin(╬ö╧å / 2) + cos(╧å1) * cos(╧å2) * sin(╬ö╬╗ / 2) * sin(╬ö╬╗ / 2);
                                                                                             ^
26 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more


BUILD FAILED

Total time: 7.853 secs
```

**Comment by carl-mastrangelo** [comment]
It looks like the files are corrupted.   Can you provide the `git` command you used to download  grpc?

**Comment by nagamanikandank** [comment]
@carl-mastrangelo , this is the command I used `git clone -b v1.0.0 https://github.com/grpc/grpc-java`

**Comment by carl-mastrangelo** [comment]
My guess is that either the clone command is mutating the file because of windows, or javac is misinterpretting the bytes.  Could you attach that file to this bug?

Alternatively, could you open up that file in an IDE (IntelliJ or Eclipse) and see if the characters are corrupted there?

**Comment by nagamanikandank** [comment]
@carl-mastrangelo , please find attachment


[RouteGuideServer.zip](https://github.com/grpc/grpc-java/files/565190/RouteGuideServer.zip)

**Comment by carl-mastrangelo** [comment]
It looks like git is rewriting the `\n` characters to `\r\n`, but aside from that the UTF-8 encoding is intact.  It seems like something is wrong with your environment or javac.  Perhaps you have some unusual language settings in your environment?  I don't have a Windows machine handy to try it out.

**Comment by ejona86** [comment]
This is a missing encoding option in the pom and build.gradle. See #2327

**Comment by nagamanikandank** [comment]
@ejona86  and @carl-mastrangelo  , thanks for your help,

Setting the following two successfully helped solve the issue

`gradle.properties` = `compileJava.options.encoding = 'UTF-8'`
`pom.xml `= `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`
