### ISSUE TITLE
Problem with interceptor

### ISSUE THREAD

**Issue by ericbets** [grpc/grpc-java#2428]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.1

### What JVM are you using (`java -version`)?
openjdk version "1.8.0_111"

### What did you do?
If possible, provide a recipe for reproducing the error.
Adding an interceptor on the server side of the app gives me:
java.lang.NoClassDefFoundError: io/netty/handler/codec/Headers
If I add the dependency: io.netty:nett-codec:4.1.3-Final to my app, then this happens on the client side after the remote procedure is called:
```shell
Exception in thread "grpc-default-executor-1" java.lang.IllegalAccessError: tried to access method io.netty.handler.logging.LogLevel.toInternalLevel()Lio/netty/util/internal/logging/InternalLogLevel; from class io.netty.handler.codec.http2.Http2FrameLogger
	at io.netty.handler.codec.http2.Http2FrameLogger.<init>(Http2FrameLogger.java:54)
	at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:140)
	at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:123)
	at io.grpc.netty.NettyClientTransport.newHandler(NettyClientTransport.java:251)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:140)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:45)
	at io.grpc.internal.TransportSet.startNewTransport(TransportSet.java:222)
	at io.grpc.internal.TransportSet.obtainActiveTransport(TransportSet.java:192)
	at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:637)
	at io.grpc.internal.ManagedChannelImpl$3.getTransport(ManagedChannelImpl.java:579)
	at io.grpc.DummyLoadBalancerFactory$DummyLoadBalancer$1.get(DummyLoadBalancerFactory.java:135)
	at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
### What did you expect to see?
Nothing.

### What did you see instead?
A Stacktrace.

**Comment by carl-mastrangelo** [comment]
Is there any way you can print out the classpath of the `java` invocation?

**Comment by ericbets** [comment]
Yes, I did. It's a conflict with the datastax cassandra driver which looks like it uses a different version of netty. Oh well. :/
