### ISSUE TITLE
error:  UNAVAILABLE  StatusRuntimeException

### ISSUE THREAD

**Issue by 09xuanjian** [grpc/grpc-java#2436]
Hi,
    I add grpc to my android project , But I meet some UNAVAILABLE problems.  I got some Message from the Excepiton  :   statusCode=14  , and  msg : "Channel shutdownNow invoked"  or  "End of stream or IOException".  It is  a bug  or  something would cause this  problem ? This Exception  is  not alway happen.  Looking forward to your reply.   Thank you.

**Comment by carl-mastrangelo** [comment]
@09xuanjian Can you include what the exception was?

**Comment by ejona86** [comment]
"Channel shutdownNow invoked" is normal, if there are RPCs in progress when shutdownNow is called for the channel. That's the entire point of shutdownNow.

For the "End of stream or IOException", that means the connection closed/died.

Those messages by themselves don't sound like bugs.

**Comment by 09xuanjian** [comment]
@ejona86  ,Thank you for your reply. 
 I meet another UNAVAILABLE problem. This problem happened many times.
ISomething would cause this problem ?   Looking forward to your reply. Thank you.


StackTrace:

java.io.IOException: FRAME_SIZE_ERROR: 4740180
                                                               at io.grpc.okhttp.internal.framed.Http2.ioException(SourceFile:589)
                                                               at io.grpc.okhttp.internal.framed.Http2.access$200(SourceFile:47)
                                                               at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(SourceFile:137)
                                                               at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(SourceFile:740)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                               at java.lang.Thread.run(Thread.java:833)

**Comment by carl-mastrangelo** [comment]
@09xuanjian That frame size error means that you are using HTTP/1.1.  4740180 in hex is 48 54 54, which is "H T T".  I believe you are connecting to the wrong server, or your server is not using gRPC.

**Comment by danieldesperado** [comment]
error: UNAVAILABLE StatusRuntimeException:"End of stream or IOException"
This problem happened many times.
Something would cause this problem ? Looking forward to your reply. Thank you.
