### ISSUE TITLE
Netty  proxy request grpc service error

### ISSUE THREAD

**Issue by yeyincai** [grpc/grpc-java#2465]
Use  netty  proxy request grpc service  , there  is  error
 
```
十一月 30, 2016 7:19:41 下午 io.grpc.netty.NettyServerHandler onStreamError
警告: Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received HEADERS frame for an unknown stream 3
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:127)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:567)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:299)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:442)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:449)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:247)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:155)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:113)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:333)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

why?

**Comment by ejona86** [comment]
Can you explain more about your environment? Are you using a custom Netty proxy between the grpc client and server?

**Comment by yeyincai** [comment]
Yeah,I  using a custom Netty proxy between the grpc client and server,the client (Android / ios) and proxies use a short connection,proxies  and servers use long connections.

**Comment by killjason** [comment]
@yeyincai did you follow the http2 spec, eg. first send the PREFACE ,then SETTINGS, then HEADERS and DATA?

**Comment by yeyincai** [comment]
@killjason  Yeah,based on Http/2 development, I do not know  the frame  streamId  rule,is that streamId =2N+1,N  is  client  request number  in   connection,  at the same time  grpc  server    N++

**Comment by killjason** [comment]
following is quoted from http2 spec doc:

> Streams are identified with an unsigned 31-bit integer. Streams initiated by a client MUST use odd-numbered stream identifiers; those initiated by the server MUST use even-numbered stream identifiers. A stream identifier of zero (0x0) is used for connection control messages; the stream identifier of zero cannot be used to establish a new stream.

You can refer to this link:https://http2.github.io/http2-spec/#StreamIdentifiers

**Comment by yeyincai** [comment]
@killjason  thank you!

**Comment by ejona86** [comment]
@yeyincai, was the stream id the problem? That stream looks client-created, which would be pretty normal because servers don't create streams with gRPC (PUSH_PROMISE is unsupported).

The most common case I'd expect to see that error is if there is a race during cancellation. The client will send RST_STREAM(streamId=3) to the server, but if the server was already sending HEADERS(streamId=3) then the client receives unexpected HEADERS. This is "okay", but it is hard to know if that is exactly what happened. If you don't see any strange behavior other than the log message and it happens rarely, then I'd just assume it is that non-important race. The race doesn't hurt anything.

You can read a little about the case in the [Netty comment](https://github.com/netty/netty/blob/540c26bb56067523e3a76eb484205997fa6727e7/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L553).

**Comment by yeyincai** [comment]
@ejona86   thank you  very mush ! The reason was found,  in  the  same  connection ,if client start  send request ,that  stream id  must use odd-numbered (first  request streamId=3),than grpc servers  response streamId=3, client send second request streamId=5,than servers  virify  streamId=5,I use netty proxy ,but client and proxies use   short connection,   proxies and servers use long connection, so if  create other client request ,the streamId is proxy  request servers number ,no  client send  streamId .
By  the  way,I come from  China the city guangzhou,english is  not  so  good,maybe you can not understand  what i  mean .

**Comment by ejona86** [comment]
Ah, yes. The proxy will have to keep track of two different ids for each stream: one from the client and one to the server. Glad you figured it out.
