### ISSUE TITLE
StatusRuntimeException with client

### ISSUE THREAD

**Issue by yashmuni** [grpc/grpc-java#2497]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.2 (but also tried with 0.15.0, 1.0.0, 1.0.1)

### What JVM are you using (`java -version`)?
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)

### What did you do?
I am creating a PredictClient to make a gRPC call to an inception model of Tenserflow serving. I am providing url and port of our environment, where it's being hosted.  

### What did you expect to see?
I expect to see PredictResponse output for the image I am sending.

### What did you see instead?
io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.Status.asRuntimeException(Status.java:536)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at tensorflow.serving.PredictionServiceGrpc$PredictionServiceBlockingStub.predict(PredictionServiceGrpc.java:144)

**Comment by yashmuni** [comment]
Sorry for the noise, I was passing constructing the PredictResponse object in wrong manner.
