### ISSUE TITLE
errors when doing bench-marking with http2-reverse-proxy

### ISSUE THREAD

**Issue by killjason** [grpc/grpc-java#2558]
### What version of gRPC are you using?
1.0.2
### What JVM are you using (`java -version`)?
1.8
### What did you do?
I did the benck-marking with my custom http2-reverse-proxy(based on Netty).
the benck-marking code is from "https://github.com/grpc/grpc-java/tree/master/benchmarks".
bench-mark client is:

> https://github.com/grpc/grpc-java/blob/master/benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncClient.java

bench-mark server is:

> https://github.com/grpc/grpc-java/blob/master/benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java

I call the Unary method with default params.
http2-reverse-proxy is a proxy I wrote using netty based on http2 protocol for reverse proxy using. in my case, the scenario is :
http2-client(grpc-java-client) make grpc request to http2-reverse-proxy, then http2-reverse-proxy pass the request to backend service which is based on grpc too. There are two handlers being used: Http2FrontendHandler and TcpBackendHandler:

> class Http2FrontendHandler extends Http2ConnectionHandler implements Http2FrameListener

> class TcpBackendHandler extends ChannelInboundHandlerAdapter

the Http2FrontendHandler is in ServerBootStrap which is used for accept http2 request from client,
the TcpBackendHandler is in BootStrap which is used for connect to backend service.
when ServerBootStrap started, I triggered channel.read(the channel contains Http2FrontendHandler), then
" io.netty.handler.codec.http2.Http2FrameListener.onHeadersRead(..)/onDataRead(..)"... methods are automatically triggered. then I pass the http2 frame to BootStrap channel to backend service.
when TcpBackendHandler read response(Byte) from backend service, it simply write the Byte to ServerBootStrap`s channel connected with client.
### What did you expect to see?
bench mark works fine with http2-reverse-proxy.
### What did you see instead?
the errors is captured in bench mark client(grpc-client)  as following:
> Encountered an error in unaryCall. Status is Status{code=INTERNAL, description=null, cause=io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384}
Encountered an error in unaryCall. Status is Status{code=INTERNAL, description=null, cause=io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384}
io.grpc.StatusRuntimeException: INTERNAL
at io.grpc.Status.asRuntimeException(Status.java:545)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384
at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processHeaderState(DefaultHttp2FrameReader.java:182)
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:143)
at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:335)
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:395)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
at java.lang.Thread.run(Thread.java:744)
io.grpc.StatusRuntimeException: INTERNAL
at io.grpc.Status.asRuntimeException(Status.java:545)
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by ejona86** [comment]
This error is all we really know: "Status{code=INTERNAL, description=null, cause=io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384}"

gRPC received an HTTP/2 frame that exceeded 16K, the HTTP/2 required minimum maximum (every http/2 library must support at least 16K frames). gRPC does not current increase the advertised maximum frame size. So either: 1) the other HTTP/2 implementation is faulty or 2) it isn't receiving HTTP/2 (or TLS vs non-TLS and similar confusions).

Since `processHeaderState` is in the backtrace, I'd suspect a broken HTTP/2 implementation, possibly caused by failure to implement CONTINUATION frames.

**Comment by killjason** [comment]
@ejona86 I think the problem is the I use encoder().writeHeader(context)/writeData(context) in the server type http2connectionhandler, and the context is the backed tcp type context.
