### ISSUE TITLE
nginx proxy

### ISSUE THREAD

**Issue by kaybinwong** [grpc/grpc-java#2559]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.2

### What JVM are you using (`java -version`)?
1.8

### What did you do?
i want to using nginx to proxy grpc server, but it got error

**nginx version**
```
[root@s168 ~]# nginx -v
nginx version: nginx/1.10.2
```
**nginx config**
```
[root@s168 ~]# cat /etc/nginx/sites-enabled/grpctest.conf
upstream grpc {
        server 127.0.0.1:50051;
}

server {
        listen       50055 http2;
        location / {
                proxy_pass http://grpc;
        }
}
```
**run grpc server**
grpc server start successfully, but it got error when the client connect.
```
[root@s168 examples]# mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldServer
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building examples 1.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ examples ---
Dec 28, 2016 11:33:01 PM io.grpc.examples.helloworld.HelloWorldServer start
INFO: Server started, listening on 50051
Dec 28, 2016 11:40:33 PM io.grpc.netty.NettyServerHandler onConnectionError
WARNING: Connection Error
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 504f5354202f68656c6c6f776f726c642e47726565746572
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:271)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:211)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:395)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

Dec 28, 2016 11:40:33 PM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 504f5354202f68656c6c6f776f726c642e47726565746572
        at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:271)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:211)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:395)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

```
**grpc client**
```
[root@s168 examples]# mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldClient
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building examples 1.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ examples ---
Dec 28, 2016 11:54:25 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@32033ad8] Created with target localhost:50055
Dec 28, 2016 11:54:25 PM io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Will try to greet world ...
Dec 28, 2016 11:54:26 PM io.grpc.examples.helloworld.HelloWorldClient greet
WARNING: RPC failed: Status{code=UNKNOWN, description=invalid content-type: null
headers: Metadata({:status=[000], server=[nginx/1.10.2], date=[Thu, 29 Dec 2016 07:54:26 GMT]})
DATA-----------------------------

���HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 504f5354202f68656c6c6f776f726c642e47726565746572, cause=null}
Dec 28, 2016 11:54:26 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@32033ad8] Terminated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.303 s
[INFO] Finished at: 2016-12-28T23:54:29-08:00
[INFO] Final Memory: 12M/138M
[INFO] ------------------------------------------------------------------------
```
**but it worked correctly without nginx proxy**
```
[root@s168 examples]# mvn exec:java -Dexec.mainClass=io.grpc.examples.helloworld.HelloWorldClient
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 7
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.classifier: linux-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building examples 1.0.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:java (default-cli) @ examples ---
Dec 28, 2016 11:52:45 PM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@59f2ffb7] Created with target localhost:50051
Dec 28, 2016 11:52:45 PM io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Will try to greet world ...
Dec 28, 2016 11:52:46 PM io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Greeting: Hello world
Dec 28, 2016 11:52:46 PM io.grpc.internal.ManagedChannelImpl maybeTerminateChannel
INFO: [ManagedChannelImpl@59f2ffb7] Terminated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.921 s
[INFO] Finished at: 2016-12-28T23:52:48-08:00
[INFO] Final Memory: 13M/169M
[INFO] ------------------------------------------------------------------------
```
### What did you expect to see?
is it possible using nginx proxy for grpc?
if can, what i should do ?

**Comment by carl-mastrangelo** [comment]
The hex dump '504f5354202f68656c6c6f776f726c642e47726565746572' looks like it is using HTTP/1.1.  I'm not sure nginx support http2 yet.

**Comment by killjason** [comment]
@kaybinwong  Nginx supports TCP level reverse proxy, it can work fine with gRPC/http2

**Comment by yeyincai** [comment]
@kaybinwong, @killjason,@carl-mastrangelo, We are developing grpc/http2 proxy,similar nginx,base on netty.  See   [](https://github.com/yeyincai/grpc-demo/tree/master/grpc-demo-proxy)

**Comment by Jacksgong** [comment]
@kaybinwong Did you fix such problem?

**Comment by GuaiShu** [comment]
@kaybinwong ,@Jacksgong  Have you solved this problem? I have encountered the same problem.

**Comment by rscorer** [comment]
I get this error in my logs too - my app is only serving gRPC calls, and as such when a client tries to do a health check using HTTP/1.x (or any other HTTP/1.x enquiry) this error is thrown:

`io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 474554202f20485454502f312e300d0a557365722d416765`

As pointed out earlier, the hex bytes decode to:

`GET / HTTP/1.0
User-Age`

Is there anything I can do in my app to catch this error to clean up my logging? The only server I have setup is Java 8 gRPC.

Thanks

**Comment by carl-mastrangelo** [comment]
You can mute it using java logging configs, but no you can't really disable it. The connection is destroyed by the time gRPC finds out about the error.   You can avoid it by using TLS, which does version negotiation in the ALPN string.

**Comment by rscorer** [comment]
Thanks - I'll take a look at using TLS, in the meantime I will change the logging configs.

Cheers

**Comment by ejona86** [comment]
nginx doesn't support HTTP/2 to the backend. That's the problem here. The only workaround is to use a different proxy, like nghttpx. Support for nginx HTTP/2 to the backend has "been coming" for a while, but I don't know if it's available yet.

**Comment by smartwjw** [comment]
good news, Ningx will support grpc at next release: https://www.nginx.com/blog/nginx-1-13-10-grpc/

**Comment by hebaceous** [comment]
@smartwjw But I got an exception
```
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: PROTOCOL_ERROR
Received Rst Stream
```
When I set grpc_send_timeout>60s,grpc_read_timeout>60s
Do you know how fix it?
Thanks
