### ISSUE TITLE
"An endpoint that receives a SETTINGS frame with any unknown or unsupported identifier MUST ignore that setting."

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-java#260]
I happened to send an invalid setting id (0x0) to a java server and saw the connection shutdown. The expected behavior as in http2 spec is

An endpoint that receives a SETTINGS frame with any unknown or unsupported identifier MUST ignore that setting.

instead of connection error.

Here is the stack trace:

Mar 31, 2015 5:58:51 PM io.grpc.transport.netty.NettyServerHandler onConnectionError
WARNING: Connection Error
io.netty.handler.codec.http2.Http2Exception: key
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:72)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame(DefaultHttp2FrameReader.java:496)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:235)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:130)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:99)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:276)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:183)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:317)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:316)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

**Comment by buchgr** [comment]
@iamqizhao Can you point to the spec where it says that?

AFAIK

> The stream identifier for a SETTINGS frame MUST be zero (0x0). If an endpoint receives a SETTINGS frame whose stream identifier field is anything other than 0x0, the endpoint MUST respond with a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

**Comment by ejona86** [comment]
This is in part coming from me, too. I was working with @iamqizhao investigating a SETTINGS related issue and found that both implementations were doing it wrong :-).

The 0x0 value was a setting key, not a stream id. From the [HTTP/2 spec](https://http2.github.io/http2-spec/#SettingValues):
> An endpoint that receives a SETTINGS frame with any unknown or unsupported identifier MUST ignore that setting.

The 0x0 value is obviously wrong, as such a thing is not defined. However, for forward compatibility we need to make sure that we properly ignore unknown SETTINGS frames. The fix looks pretty easy in Netty, although we get to decide where.

https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L496
https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Settings.java#L223

**Comment by iamqizhao** [comment]
On Tue, Mar 31, 2015 at 6:39 PM, Jakob Buchgraber <notifications@github.com>
wrote:

> @iamqizhao <https://github.com/iamqizhao> Can you point to the spec where
> it says that?
>
> AFAIK
>
> The stream identifier for a SETTINGS frame MUST be zero (0x0). If an
> endpoint receives a SETTINGS frame whose stream identifier field is
> anything other than 0x0, the endpoint MUST respond with a connection error
> (Section 5.4.1) of type PROTOCOL_ERROR.
>
> stream id is irrelevant here. I meant "setting id". I already pasted what
the spec say in my original post (and the subject of this issue is that
too. :-).

**Comment by buchgr** [comment]
@iamqizhao @ejona86 ahh I see. yeah settings id makes sense.

**Comment by nmittler** [comment]
I've raised https://github.com/netty/netty/issues/3560 to fix Netty.

**Comment by nmittler** [comment]
This was fixed in 11d0094
