### ISSUE TITLE
GRPC is logging NOT_FOUND errors as SEVERE and spamming the logs

### ISSUE THREAD

**Issue by r-tock** [grpc/grpc-java#2604]
gRPC = 1.0.3

We are using NOT FOUND to indicate that a resource is missing on the server. This is an ok response. However, this is getting logged as a SEVERE error on the client side and we can't find a way to control how to turn off logging for this particular error or reduce its severity to INFO.

Can someone help fix this/explain why NOT_FOUND is severe? 

cc: @jacob-tock

**Comment by r-tock** [comment]
```
com.tocktix.ssm.ServerSideStateManagerImplTest > handleTwoSequentialNotFoundErrors STANDARD_ERROR
    Jan 12, 2017 8:57:36 PM io.grpc.internal.ManagedChannelImpl <init>
    INFO: [ManagedChannelImpl@4f4af133] Created with target directaddress:///io.grpc.inprocess.InProcessSocketAddress@48eb32b9
    Jan 12, 2017 8:57:36 PM io.grpc.internal.SerializeReentrantCallsDirectExecutor execute
    SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2@2620b663
    io.grpc.StatusRuntimeException: NOT_FOUND
    	at com.tocktix.ssm.ServerSideStateManagerImplTest$DelegatingSsmService.query(ServerSideStateManagerImplTest.java:359)
    	at com.tocktix.messages.SsmServiceGrpc$MethodHandlers.invoke(SsmServiceGrpc.java:340)
    	at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:150)
    	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:261)
    	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:503)
    	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
    	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:65)
    	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:499)
    	at io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessClientStream.halfClose(InProcessTransport.java:530)
    	at io.grpc.internal.ClientCallImpl.halfClose(ClientCallImpl.java:363)
    	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:255)
    	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:189)
    	at com.tocktix.messages.SsmServiceGrpc$SsmServiceFutureStub.query(SsmServiceGrpc.java:300)
    	at com.tocktix.ssm.ServerSideStateManagerImpl.lambda$queryWithMaxRetries$2(ServerSideStateManagerImpl.java:136)
    	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
    	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
    	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
    	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
    	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
    	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:595)
    	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:96)
    	at com.google.common.util.concurrent.Futures.transformAsync(Futures.java:1108)
    	at com.tocktix.ssm.ServerSideStateManagerImpl.queryWithMaxRetries(ServerSideStateManagerImpl.java:136)
    	at com.tocktix.ssm.ServerSideStateManagerImpl.query(ServerSideStateManagerImpl.java:114)
    	at com.tocktix.ssm.ServerSideStateManagerImplTest.handleTwoSequentialNotFoundErrors(ServerSideStateManagerImplTest.java:234)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
    	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
    	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
```

**Comment by carl-mastrangelo** [comment]
That only happens if you have an uncaught exception in your client side stream observer.  Do you have a throw statement  in your observer by chance?  We log it because it doesn't have anywhere else to go.

**Comment by r-tock** [comment]
Thank you, that helps!
