### ISSUE TITLE
Client Error: io.grpc.StatusRuntimeException: UNKNOWN

### ISSUE THREAD

**Issue by wrightm** [grpc/grpc-java#2624]
### What version of gRPC are you using?

1.0.2

### What JVM are you using (`java -version`)?

1.8

### What did you do?

I am running a gRPC-java server with multiple grpc services defined.

When running multiple stubs and their multiple rpc calls simultaneously I am seeing this exception below thrown.

```
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This happens only when I have multiple stubs with their own channel defined and the occurrence of the exception seems to be more frequent when increasing the number of stubs/rpc calls. This looks to me like some sort of resource issue either client or server side. I have increased the thread count and seen no measurable improvements. Not sure where to go from here?

My server setup is as follows:

```
private final NettyServerBuilder builder;
private final NioEventLoopGroup workerGroup;
...
...

// The options are currently set to the defualt grpc settings. So in effect these should not change the default environment.
// NioEventLoopGroup( 2 * Runtime.getRuntime().availableProcessors() )
builder.workerEventLoopGroup( workerGroup )
                              // 1048576
				.flowControlWindow( options.getFlowControlWindow() ) 
                              // Integer.MAX_VALUE
				.maxConcurrentCallsPerConnection( options.getMaxConcurrentCallsPerConnection() )
                              // 8192
				.maxHeaderListSize( options.getMaxHeaderListSize() )
                              // 4 * 1024 * 1024
				.maxMessageSize( options.getMaxMessageSize() )
                              //ProtocolNegotiators.serverPlaintext()
				.protocolNegotiator( options.getProtocolNegotiator() ) 
                              // Executors.newFixedThreadPool(20)
				.executor( executor )
                              // CompressorRegistry.getDefaultInstance()
				.compressorRegistry( options.getCompressorRegistry() )
                               // DecompressorRegistry.getDefaultInstance()
				.decompressorRegistry( options.getDecompressorRegistry() );
```

My Client setup:

```
ManagedChannel channel = NettyChannelBuilder.forAddress( remote_host, remote_port )
				.usePlaintext( true )
				.build();

Runtime.getRuntime().addShutdownHook( new Thread( new Runnable() {
			@Override
			public void run() {
				channel.shutdown();
				try {
					channel.awaitTermination( 120, TimeUnit.SECONDS );
				} catch ( InterruptedException e ) {
					Thread.currentThread().interrupt();
				}
			}
		} ) );

CallOptions callOptions = CallOptions.DEFAULT.withCompression( "gzip" );
// Where stubClazz would be the grpc-proto stub
Constructor<Stub> constructor = stubClazz.getDeclaredConstructor( Channel.class,
				CallOptions.class );
constructor.setAccessible( true );
return constructor.newInstance( channel, callOptions );
```

### What did you expect to see?

I expect to get back the response object.

### What did you see instead?

Instead I received a ```io.grpc.StatusRuntimeException: UNKNOWN```

**Comment by ejona86** [comment]
The server probably threw an exception. The exception information is not safe to propagate to the client by default, so you get a useless error on client-side. Did you check the server logs to see if there were any uncaught exceptions?

**Comment by wrightm** [comment]
Can't see any exceptions server side...

**Comment by wrightm** [comment]
However, when I set the ```NettyChannelBuilder``` protocolNegotiator to ProtocolNegotiators.serverPlaintext() I am seeing a different exception...

```
ManagedChannel channel = NettyChannelBuilder.forAddress( host, port )
				.protocolNegotiator(ProtocolNegotiators.serverPlaintext() )
...
```

throws

```
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.fanduel.grpc.client.interceptor.GrpcClientInterceptor$2$1.onClose(GrpcClientInterceptor.java:77)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.fanduel.grpc.client.interceptor.GrpcClientContexts$ContextualizedClientCallListener.onClose(GrpcClientContexts.java:86)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.fanduel.grpc.client.interceptor.GrpcClientInterceptor$2$1.onClose(GrpcClientInterceptor.java:77)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.fanduel.grpc.client.interceptor.GrpcClientContexts$ContextualizedClientCallListener.onClose(GrpcClientContexts.java:86)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: unsupported message type: Object (expected: ByteBuf, FileRegion)
	at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:260)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:799)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1291)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:39)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1100)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1089)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
```

where there is an additional stacktrace

```
Caused by: java.lang.UnsupportedOperationException: unsupported message type: Object (expected: ByteBuf, FileRegion)
```

No idea why this would be producing a different exception. My first thoughts were race condition, but the class is immutable... strange.

I'll have a look at my server settings to see whats going on there.

**Comment by ejona86** [comment]
@wrightm, in the most recent post you're passing a server negotiator to a client. That's not going to work. You shouldn't need to use `protocolNegotiator()`. Instead use `NettyChannelBuilder.usePlaintext(true)`.

Now that I see you're setting `protocolNegotiator` on server-side as well, that may be part of the problem. Avoid `protocolNegotiator` and see if things improve. Since it's not clear what you are attempting to do with `protocolNegotiator`, I can't give more clear guidance.

**Comment by wrightm** [comment]
@ejona86 apologies typo, that sorts out the ```unsupported message type: Object (expected: ByteBuf, FileRegion)``` exception. Thank you.

And also looks like it was the server throwing an exception like you said. However, grpc is not logging this to my file appender with my current logging configuration. Using log4J, I can now look into why this is the case.

Good old sql util Date conflict... There isn't a ```Date.toInstant``` in sql.Date just a ```java.lang.UnsupportedOperationException```, there was me thinking java 8 sorted things like this out.
