### ISSUE TITLE
AbstractInteropTest.maxInboundSize_exact is too picky of the precise protobuf encoding

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2626]
If the client encodes protos ever-so-slightly differently than the server, the size the server sends won't match the computed size the client generates. If the server uses a more verbose encoding, it results in an error like:
```
io.grpc.StatusRuntimeException: INTERNAL: Frame size 7 exceeds maximum: 5. 
	at io.grpc.Status.asRuntimeException(Status.java:542)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:529)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.next(ClientCalls.java:536)
	at io.grpc.testing.integration.AbstractInteropTest.maxInboundSize_exact(AbstractInteropTest.java:800)
```

**Comment by ejona86** [comment]
Fixed by #3663
