### ISSUE TITLE
why my grpc-java client on version 1.0.3 threw io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by runfriends** [grpc/grpc-java#2647]
I'm testing the latest version of grpc-java which version is 1.0.3. The client always throws io.netty.util.internal.OutOfDirectMemoryError. why....
====================client code ======================

```java
    public static void main(String[] args) throws InterruptedException{
        ManagedChannelImpl channel = NettyChannelBuilder.forAddress("localhost", 10000)
                .negotiationType(NegotiationType.PLAINTEXT)
//                .eventLoopGroup(new NioEventLoopGroup())
                .executor(new ThreadPoolExecutor(128,1024,60,TimeUnit.SECONDS,new SynchronousQueue<Runnable>(),(r)->{
                    Thread t=new Thread(r);
                    t.setUncaughtExceptionHandler((Thread th,Throwable e)->{
                        e.printStackTrace();
                    });
                    return t;
                },new ThreadPoolExecutor.AbortPolicy()))
//                .idleTimeout(60,TimeUnit.SECONDS)
                .loadBalancerFactory(RoundRobinLoadBalancerFactory.getInstance())
                .build();
        Message msg=Message.newBuilder().addApid(1).addApid(2).addApid(3).setAge(23).setName("test").setTest(true).build();
        EchoStub stub=EchoGrpc.newStub(channel);
        
        long start=System.currentTimeMillis();
        int c=100_0000;
        CountDownLatch latch=new CountDownLatch(c);
        for(int i=0;i<c;i++){
            stub.echo(msg,new StreamObserver<Message>(){
                public void onCompleted(){
                    latch.countDown();
                }
                public void onError(Throwable t){
                    
                }
                public void onNext(Message m){
                }
            });
        }
        System.out.println("FFFFFFFFFFF");
        latch.await();
        System.out.println(System.currentTimeMillis()-start);
        channel.shutdownNow();
    }
```

====================exception stack=====================
```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 520093983, max: 536870912)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:709)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:698)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:213)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	at io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:66)
	at io.grpc.internal.MessageFramer.writeKnownLength(MessageFramer.java:190)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:149)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:126)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:172)
	at io.grpc.internal.DelayedStream$3.run(DelayedStream.java:201)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:121)
	at io.grpc.internal.DelayedStream.setStream(DelayedStream.java:90)
	at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:392)
	at io.grpc.internal.DelayedClientTransport$PendingStream.access$100(DelayedClientTransport.java:379)
	at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-48"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-50"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-58"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by carl-mastrangelo** [comment]
Are you checking `isReady` before sending on your stubs?

**Comment by ejona86** [comment]
isReady doesn't apply here, since they are unary RPCs.

Your getting an OutOfMemoryError, but because we use direct memory, you also see OutOfDirectMemoryError. Send fewer RPCs concurrently. Easy way with that test code: use a semaphore (instead of the latch) and only allow X RPCs concurrently.

**Comment by carl-mastrangelo** [comment]
All RPCs are subject to flow control.
