### ISSUE TITLE
AssertionError in OkHttpClientTransport from older Android devices

### ISSUE THREAD

**Issue by adrien-aubel** [grpc/grpc-java#2703]
When using gRPC on HTC M7 (2013), a crash occurs (`AssertionError`) that seems to be from the protocol negotiation in OkHttp transport.

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
HTC M7 (2013) - Android 4.3 (HTC Sense 5.0)

```
FATAL EXCEPTION: grpc-okhttp-0
                                                          java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=suggestions-api.invi.im/104.197.200.100,port=80,localPort=37661]
                                                              at io.grpc.okhttp.internal.OptionalMethod.invoke(OptionalMethod.java:114)
                                                              at io.grpc.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:135)
                                                              at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.getSelectedProtocol(OkHttpProtocolNegotiator.java:208)
                                                              at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:170)
                                                              at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:74)
                                                              at io.grpc.okhttp.OkHttpClientTransport$1.run(OkHttpClientTransport.java:425)
                                                              at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                              at java.lang.Thread.run(Thread.java:849)
```

Seems like if the `catch` clause here was catching `Throwable` (rather than `Exception`) it would not crash and return `null`: https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/okhttp/OkHttpProtocolNegotiator.java#L205

Not sure how gRPC behaves in this case but comments in the method seem to suggest that's a scenario that can be expected

Stock Web browser
![image](https://cloud.githubusercontent.com/assets/1900608/22667191/9ed73b9a-ec70-11e6-80f3-2d16fd904577.png)

Chrome browser
![image](https://cloud.githubusercontent.com/assets/1900608/22667203/aacde2fa-ec70-11e6-9c25-acb5417e1e5f.png)

**Comment by carl-mastrangelo** [comment]
Is Google Play Services installed?

**Comment by adrien-aubel** [comment]
It is installed, version 10.0.84

![image](https://cloud.githubusercontent.com/assets/1900608/22671640/318f91ea-ec84-11e6-8087-dfb18d84de00.png)

**Comment by adrien-aubel** [comment]
Ping :)

Is there any step planned to tackle this or any suggested fix?

**Comment by zsurocking** [comment]
Seems you're talking to port 80?

**Comment by ejona86** [comment]
In general, you should use the dynamic security provider: https://developer.android.com/training/articles/security-gms-provider.html

In this case, it is very weird you're connecting to port 80 of your server.
