### ISSUE TITLE
gRPC memory leak? when send ton of data

### ISSUE THREAD

**Issue by luoguohao** [grpc/grpc-java#2710]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

Client side just a simple for loop to invoke rpc method.

Server side , i also set the maxConcurrentCallsPerConnection to 5.

### What did you expect to see?
send at least 1M message frequently.

### What did you see instead?
There are two doubt I don't understand.
1) Within log file , i see lots of OutOfDirectMemoryError, show as following:
 Feb 08, 2017 12:41:13 AM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.DecoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658527, max: 255066112)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:252)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658527, max: 255066112)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:709)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:698)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
        at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:475)
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:88)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:246)
        ... 15 more

Feb 08, 2017 12:41:13 AM io.grpc.netty.NettyServerHandler onConnectionError
WARNING: Connection Error
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658527, max: 255066112)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:624)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:578)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:709)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:698)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)

2) when I using linux Top command to see the java process. I found that the RES memory size is much bigger than the jvm heap size plus the off-heap size. see as following,
   PID     USER      PR  NI    VIRT      RES       SHR  S %CPU  %MEM     TIME+        COMMAND                                                                                                                                                                                                   
 53709 hadoop    20   0 1470520 714356   5524  S  0.3        70.8         35:36.90         java 

and java jvm configuration show as following,
-Xms256M -Xmx256M -XX:-HeapDumpOnOutOfMemoryError -Xmn128M -Djava.net.preferIPv4Stack=true -Dio.netty.leakDetectionLevel=advanced -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -Xloggc:logs/gc.log -XX:+UseConcMarkSweepGC -XX:ParallelCMSThreads=2 -Djetty.logs=/home/hadoop/gp-service-bitmap/jetty-9.2.20/logs -Djetty.home=/home/hadoop/gp-service-bitmap/jetty-9.2.20 -Djetty.base=/home/hadoop/gp-service-bitmap/jetty-9.2.20 -Djava.io.tmpdir=/tmp

and the max direct memory size is 243.25 MB which is figured out by using PlatformDependent.maxDirectMemory().

thank you, can you make any suggestion ?

**Comment by ejona86** [comment]
Is it possible you are just sending RPCs too quickly? RPCs will queue waiting to be sent, and if you queue too many you will see such out of memory errors.

If you are doing unary RPCs, you may consider limiting yourself to `X` concurrent RPCs (note this is different from the server's max concurrent). If doing streaming RPCs you can observe flow control. I can point you to details if you are doing streaming.

**Comment by luoguohao** [comment]
yes , in my situation,rpc client will send  large messages with high frequency, when doing unary RPCs, my solution is just like what you said, limit the concurrent RPCs by myself . and while doing streaming RPCs, i also follow the official examples using flow control, that sounds good for me.
but, there is still a puzzle, why the RESIDENT MEMORY size never decrease which showed Using top command. and , i just wondering why not using pooled direct memory allocator when using Netty, and after setting the following configuration:
        System.setProperty("io.netty.allocator.tinyCacheSize", "0"); 
        System.setProperty("io.netty.allocator.smallCacheSize", "0");
        System.setProperty("io.netty.allocator.normalCacheSize", "0");
        System.setProperty("io.netty.allocator.type", "pooled");
the direct memory seems to more stable, but still not decrease.

**Comment by ejona86** [comment]
Java does not give free memory back to the OS (which would reduce RES) immediately. It gives it back slower over time, I think after GCs. That sounds like normal Java memory behavior.

**Comment by luoguohao** [comment]
I agree that ，but what I have encountered is that netty began to throw memory leak exception when the application throw out of memory error .and after that,the application still work well ,but the resident memory never drop down , i believe that it's memory leak

**Comment by ejona86** [comment]
If you ever see an out-of-memory error, all bets are off. We make no guarantees of what happens after an OOME. It is very difficult for code to handle the case correctly, and many times it is impossible. If there's some problem that _causes_ an OOME, then we're interested, but after an OOME you should probably restart your JVM. `System.exit(1)` is the only sane handling of OOME I've seen.
