### ISSUE TITLE
Failed to load any of the given libraries: [netty-tcnative-windows-x86_64, netty-tcnative]

### ISSUE THREAD

**Issue by manjunathshetty** [grpc/grpc-java#2761]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.1.2

### What JVM are you using (`java -version`)?
8

### What did you do?
If possible, provide a recipe for reproducing the error.
Trying the SSL on server side

here is my pom.xml

`.....
 <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>1.1.33.Fork16</version>
            <classifier>${os.detected.classifier}</classifier>
            <scope>compile</scope>
</dependency>
.....
`

### What did you expect to see?
SSL should work fine

### What did you see instead?
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:324)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:216)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:42)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:344)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:334)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:414)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:402)
	at com.nokia.nas.registration.main.Service.start(Service.java:49)
	at com.nokia.nas.registration.main.Bootstrap.main(Bootstrap.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-windows-x86_64, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:177)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:412)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:90)
	... 13 more

**Comment by carl-mastrangelo** [comment]
We depend on Fork26, can you please change to using it instead?

**Comment by manjunathshetty** [comment]
Thanks, it worked fine
