### ISSUE TITLE
NettyClientTransportTest.maxHeaderListSizeShouldBeEnforcedOnServer is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#2762]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/205610718 (since rebuilt)

```
io.grpc.netty.NettyClientTransportTest > maxHeaderListSizeShouldBeEnforcedOnServer FAILED
    java.lang.ClassCastException: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException cannot be cast to io.grpc.StatusException
        at io.grpc.netty.NettyClientTransportTest.maxHeaderListSizeShouldBeEnforcedOnServer(NettyClientTransportTest.java:313)
```

It looks like the problem is `getRootCause()` is over-eager and skips over the `StatusException`. So this is a bug in the test, which should be easy to fix.

**Comment by lukaszx0** [comment]
Looks like it's failing quite consistently now.

Seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/2974/testReport/junit/io.grpc.netty/NettyClientTransportTest/maxHeaderListSizeShouldBeEnforcedOnServer/

```
Error Message

java.lang.ClassCastException: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException cannot be cast to io.grpc.StatusException
Stacktrace

java.lang.ClassCastException: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException cannot be cast to io.grpc.StatusException
	at io.grpc.netty.NettyClientTransportTest.maxHeaderListSizeShouldBeEnforcedOnServer(NettyClientTransportTest.java:313)
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/205910708 (since rebuilt):
```
io.grpc.netty.NettyClientTransportTest > maxHeaderListSizeShouldBeEnforcedOnServer FAILED
    java.lang.ClassCastException: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException cannot be cast to io.grpc.StatusException
        at io.grpc.netty.NettyClientTransportTest.maxHeaderListSizeShouldBeEnforcedOnServer(NettyClientTransportTest.java:313)
```

Seen at https://travis-ci.org/grpc/grpc-java/jobs/205895577 (since rebuilt)
```
io.grpc.netty.NettyClientTransportTest > maxHeaderListSizeShouldBeEnforcedOnServer FAILED
    java.lang.ClassCastException: io.netty.handler.codec.http2.Http2Exception$HeaderListSizeException cannot be cast to io.grpc.StatusException
        at io.grpc.netty.NettyClientTransportTest.maxHeaderListSizeShouldBeEnforcedOnServer(NettyClientTransportTest.java:313)
```

It is still flaky, but started happening all of a sudden...  efe261ea4 looks like the earliest commit it flaked on. So something before then...

**Comment by dapengzhang0** [comment]
seen at 
https://travis-ci.org/grpc/grpc-java/jobs/206739995
same stack trace

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/207189505 (since rebuilt; some stack trace)

**Comment by ejona86** [comment]
Fixed by #2779
