### ISSUE TITLE
Possibly infinite loop

### ISSUE THREAD

**Issue by perlmonk** [grpc/grpc-java#2832]
I have some grpc instance, after several days running, one cpu may running into full load at unperdicate time. 
Usually one, and may be then grow to two or more.

![cpu-last-month](https://cloud.githubusercontent.com/assets/1897710/24027976/71424562-0b06-11e7-9860-b72fabd9c54b.png)

### What version of gRPC are you using?
1.0.3

### What JVM are you using (`java -version`)?
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

JvmTop result seems caused by netty.

```
JvmTop 0.8.0 alpha - 11:29:39,  amd64,  4 cpus, Linux 2.6.32-57, load avg 2.71
 http://code.google.com/p/jvmtop

 Profiling PID 32200:    xx.xx.SomeServer 

  99.97% (     0.90s) ...netty.handler.codec.http2.DefaultHttp2RemoteFlowContr()
   0.03% (     0.00s) net.spy.memcached.MemcachedConnection.handleIO()
   0.01% (     0.00s) io.netty.channel.nio.NioEventLoop.select()
   0.00% (     0.00s) im.cu.framework.thrift.ThriftBasedServiceServer$1.run()
```

and stack

```
"grpc-default-worker-ELG-3-4" #199 daemon prio=5 os_prio=0 tid=0x00007f4628015000 nid=0x7e9f runnable [0x00007f45ad90a000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(DefaultHttp2RemoteFlo
wController.java:360)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor$1.write(DefaultHttp2RemoteFlowCo
ntroller.java:550)
        at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.write(WeightedFairQueueByteDistributor.java:2
48)
        at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:15
1)
        at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(WeightedFairQueueByteDistribut
or.java:183)
        at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:13
0)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2Re
moteFlowController.java:631)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:255)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:161)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:787)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:779)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:760)
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:974)
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:244)
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:139)
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:49)
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:61)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment]
I think this was fixed in a latter netty version.
