### ISSUE TITLE
Reset connection by peer 

### ISSUE THREAD

**Issue by stringpeng** [grpc/grpc-java#2878]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.0.0

### What JVM are you using (`java -version`)?
1.8.0_40

### What did you do?
If possible, provide a recipe for reproducing the error.
add log in my web application, and deploy it to production sever. 
always get error message as below. we cannot know which/where method throw out.
after a lots of error message throwing out, we can get "out for memory" error message and server is down, need to restart to to recover it.  

error message is 
```
Transport failed
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:349)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by carl-mastrangelo** [comment]
You need to provide more detail about how this can be reproduced.  Right now it just looks like the connection dropped, which isn't unusual.

**Comment by stringpeng** [comment]
We implements CommandLineRunner and DisposableBean on startup class, initialize gRPC channel in "run" function, shutdown those channels on "destroy" function.

```
public class GrpcClientRunner implements CommandLineRunner,DisposableBean {
    public void run(String... args) throws Exception {
        client = new GrpcClient(clientHosts.getGoodsHost(), Integer.valueOf(clientHosts.getGoodsPort()));
        GrpcClientConfig.initClient(client.getChannel());
    }

    @Override
    public void destroy() throws Exception {
        client.shutdown();
    }
}
```

We initialize all of stubs on startup class and set them to global static varian, and use them on business invoke.
```
public class GrpcClientConfig {
    public static GoodsGrpc.GoodsBlockingStub goodsBlockingStub;
    public static void initClient(ManagedChannel channel)
    {
        goodsBlockingStub = GoodsGrpc.newBlockingStub(channel);
    }
}
```
@carl-mastrangelo 
I'm above usage is correct or incorrect. Does it effect "out of memory"? Please kindly address it.
if you need more info, please let me know. 
thanks a lot.

**Comment by carl-mastrangelo** [comment]
How are you constructing the ManagedChannel?

**Comment by ejona86** [comment]
What is `ddcb516`? That doesn't seem like a commit. v1.0.2 upgraded Netty that fixed some memory issues. You may try it out.

**Comment by ejona86** [comment]
The exception is a red herring; it is probably fine and isn't likely related to the out of memory.

**Comment by xiaojiejava** [comment]
I have the same problem，know the reason?

**Comment by mjdupertuis** [comment]
We're experiencing the same error (nearly identical stack trace). The odd thing is everything runs fine on Mac OSX 10.12.6 but fails every time on Ubuntu server 16.04. Server and client running on same host. Using gRPC 1.6.1 and Netty 14.1.14.

- Simple unary call, async and blocking exhibit same problem
- Server construction
             Server server = ServerBuilder
                    .forPort(port)
                    .addService(new ServiceEventResponderImpl())
                    .directExecutor()
                    .build();
- Client construction
             Channel channel = ManagedChannelBuilder
                            .forAddress(serverName(), serverPort())
                            .usePlaintext(true)
                            .build();

**Comment by ejona86** [comment]
@mjdupertuis, do you also see OutOfMemoryErrors? If so, you need to investigate the reason for running out of memory.
