### ISSUE TITLE
"StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR" ,"StatusRuntimeException:UNKNOWN"

### ISSUE THREAD

**Issue by kaiyangzhang** [grpc/grpc-java#2901]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.0.0, 1.2.0

### What JVM are you using (`java -version`)?
1.8

### What did you do?

I am running a gRPC-java server with multiple grpc services defined.

When running multiple stubs which multiple threads share, so multiple rpc calls simultaneously, I am seeing this exception below, the exception is only **_occasionally_** appear.

(1) io.grpc.statusRuntimeException: UNKNOWN
                 at  io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
                 at  io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
                 at  io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
                 ...............................
                 .................................
(2)  io.grpc.statusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
      Received Rst Stream
                 at  io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
                 at  io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
                 at  io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
                 ...............................
                 .................................

### What is benchmark scenario?

1. my benchmark is a distributed program: one  client to three servers.

2. client tps: 150k+ /s, each server receive message : 50k+ /s

### question:

1. why  the exception is only **_occasionally_** appear? Concurrency is too big?
2. mutiple thread can call the same stub object at the same time?

**Comment by carl-mastrangelo** [comment]
RST STREAM only happens on protocol level errors.  What version is the gRPC server running?

**Comment by ejona86** [comment]
Are the clients and servers both using grpc-java?

RST_STREAM with CANCEL happens in some other common cases. RST_STREAM with INTERNAL_ERROR can occur in some error cases. I'd expect a protocol error to have error code PROTOCOL_ERROR.

For the UNKNOWN, I'd expect a "caused by" exception for it. Was there? If not, then that came from the server. I'd expect the server threw an exception and it should be logged.

@kaiyangzhang, did you check the server logs at all? I'd expect that they logged something when this happened.

**Comment by carl-mastrangelo** [comment]
@ejona86:

> I am running a gRPC-java server with multiple grpc services defined.

and

> at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)

I believe this implies it is both Java client and server.

**Comment by kaiyangzhang** [comment]
@carl-mastrangelo @ejona86 
1.  Clients and servers both used grpc-java-1.0.0, and tried grpc-java-12.0.
2.  For the UNKNOWN, the client did not “caused by”exception, and the server did not throw exception.
3.  When the client catch these two exceptions, and then retry once or several times, then no more exceptions are thrown. Because these two exceptions is only occasionally appear, I temporarily use this retry strategy to avoid.
4. When the client concurrently sends data to the server, these two exception will not be thrown. But client concurrent query scene, the client concurrent receive data from servers, these two exception will be thrown.

**Comment by gurinderu** [comment]
Hey, I got a similar error with netty impl: 

```
io.grpc.StatusRuntimeException: INTERNAL
at io.grpc.Status.asRuntimeException(Status.java:540)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
at com.devim.common.grpc.ClientTracingInterceptor$$anon$1$$anon$2.onClose(ClientTracingInterceptor.scala:49)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)\nCaused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:309)
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:217)
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
```

**Comment by kaiyangzhang** [comment]
The problem has been solved, and the problem is caused by the server. The queue size of grpc server's thread pool is too small, resulting in tasks submit failed. the server throw exception below:

rejected execution of io.grpc.internal.SerializingExecutor$TaskRunner@5f207f61 on AsThreadPoolExecutor[GrpcServer_ASTERIA_SERVER, queue capacity=200, com.fiberhome.asteriadb.common.concurrent.AsthreadPoolExecutor@5dcfbbfe[Running, pool size=100, active threads =100, queued tasks =200, completed tasks =3473355]]
     at com.fiberhome.asteriadb.common.concurrent.AsAbortPolicy.rejectedExecution
     at java.util.concurrent.ThreadPoolExecutor.reject
     at java.util.concurrent.ThreadPoolExecutor.execute
     at com.fiberhome.asteriadb.common.current.AsThreadPoolExecutor.execute
     at io.grpc.internal.SerializingExecutor.execute
     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener
     at io.grpc.internal.AbstractServerStream$TransportState.closeListener
     at  io.grpc.internal.AbstractServerStream$TransportState.complete
     at io.grpc.nettyServerStream$TransportState.complete
     .............................
     .............................

**Comment by longbozhan** [comment]
I have the same problems when I send a bytes to server, the bytes's size is about 14Mb, and I have set  MAX_SIZE = 50*1024*1024;
channelBuilder.maxMessageSize(MAX_SIZE)         (NettyChannelBuilder)
nettyServerBuilder.maxMessageSize(MAX_SIZE); 
@ejona86
