### ISSUE TITLE
OkHttp only connects to "h2" ALPN protocol

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#293]
Values "h2-14", "h2-15", and "h2-16" result in [Protocol](https://github.com/square/okhttp/blob/293792c5ee66323c6070f9d88227d6579feaba47/okhttp/src/main/java/com/squareup/okhttp/Protocol.java#L87) throwing an error from [OkHttpTlsUpgrader](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/com/squareup/okhttp/OkHttpTlsUpgrader.java#L80).

We should support all those options, as we still are seeing them being used since the final HTTP/2 spec hasn't been published.

```
java.lang.RuntimeException: java.io.IOException: Unexpected protocol: h2-14
            at io.grpc.transport.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:300)
            at io.grpc.ChannelImpl.obtainActiveTransport(ChannelImpl.java:188)
            at io.grpc.ChannelImpl.access$600(ChannelImpl.java:55)
            at io.grpc.ChannelImpl$CallImpl.start(ChannelImpl.java:248)
            at io.grpc.ForwardingCall.start(ForwardingCall.java:45)
...
     Caused by: java.io.IOException: Unexpected protocol: h2-14
            at com.squareup.okhttp.Protocol.get(Protocol.java:94)
            at com.squareup.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:80)
```

**Comment by madongfly** [comment]
Let me guess what was wrong here, some internal users are doing ALPN by themselves, so when OkHttpTlsUpgrader is applied, the ALPN has already been Done, but the negotiated protocol is different than OkHttp 2.0's "h-16", right?

Can you confirm "h2-16" can actually work? otherwise my speculation is incomplete.
