### ISSUE TITLE
The Java performance tests are failing at master in Jenkins

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-java#2931]
Looking at https://grpc-testing.appspot.com/job/gRPC_performance_experiment/4065, for example, the log has multiple instances of

```
E0420 13:30:55.299856866    2975 driver.cc:509]              Worker 0 could not be properly quit because Received RST_STREAM with error code 8
E0420 13:30:55.310985673    2975 driver.cc:509]              Worker 1 could not be properly quit because Received RST_STREAM with error code 8
E0420 13:30:55.510445864    2975 driver.cc:509]              Worker 2 could not be properly quit because Received RST_STREAM with error code 8
```

followed by hundreds of megabytes of

```

Apr 20, 2017 3:35:16 PM io.grpc.benchmarks.driver.LoadClient$AsyncUnaryWorker$1 onError
INFO: Error in AsyncUnary call
io.grpc.StatusRuntimeException: INTERNAL: Thrown from handleResolvedAddresses(): java.lang.NullPointerException
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at io.grpc.internal.InternalSubchannel.<init>(InternalSubchannel.java:164)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.createSubchannel(ManagedChannelImpl.java:604)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.createSubchannel(ManagedChannelImpl.java:585)
	at io.grpc.PickFirstBalancerFactory$PickFirstBalancer.handleResolvedAddressGroups(PickFirstBalancerFactory.java:88)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1.run(ManagedChannelImpl.java:765)
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:87)
	at io.grpc.internal.ManagedChannelImpl$4.get(ManagedChannelImpl.java:359)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:218)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:270)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:237)
	at io.grpc.stub.ClientCalls.asyncUnaryCall(ClientCalls.java:77)
	at io.grpc.benchmarks.proto.BenchmarkServiceGrpc$BenchmarkServiceStub.unaryCall(BenchmarkServiceGrpc.java:150)
	at io.grpc.benchmarks.driver.LoadClient$AsyncUnaryWorker.run(LoadClient.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment]
Java hasn't changed at all since https://grpc-testing.appspot.com/job/gRPC_performance_experiment/4064 . Both were at commit a92b0488ed0ed.

The RST_STREAM existed in 4064 as well, so it is probably unrelated.

The line number for InternalSubchannel [doesn't make any sense](https://github.com/grpc/grpc-java/blob/a92b0488/core/src/main/java/io/grpc/internal/InternalSubchannel.java#L164). Nor does the [ManagedChannelImpl one](https://github.com/grpc/grpc-java/blob/a92b0488/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L604). That makes me think the commit that was checked out isn't actually running.

@murgatroid99, do you know what version of the code failed?

**Comment by ejona86** [comment]
@murgatroid99, is it still failing like this? It didn't look like it to me.
