### ISSUE TITLE
 Channel closed while performing protocol negotiation

### ISSUE THREAD

**Issue by patricia93sousa** [grpc/grpc-java#2962]
Please answer these questions before submitting your issue.

### What JVM are you using (`java -version`)?
java version "1.8.0_131"

### What did you do?
If possible, provide a recipe for reproducing the error.
If I do: 
➔ ./run-test-server.sh 
and then,
➔ ./run-test-client.sh --server_port=8080 

Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test empty_unary
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:463)
	at io.grpc.testing.integration.AbstractInteropTest.emptyUnary(AbstractInteropTest.java:273)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:209)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:197)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:81)
Shutting down

### What did you see instead?
The error:

Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test empty_unary
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:463)
	at io.grpc.testing.integration.AbstractInteropTest.emptyUnary(AbstractInteropTest.java:273)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:209)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:197)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:81)
Shutting down

**Comment by ejona86** [comment]
The server-side says:
> Using fake CA for TLS certificate. Test clients should expect host
*.test.google.fr and our test CA. For the Java test client binary, use:
--server_host_override=foo.test.google.fr --use_test_ca=true

Running `./run-test-client.sh --server_port=8080 --server_host_override=foo.test.google.fr --use_test_ca=true` succeeds.

I'm not sure why there isn't more error information included.

**Comment by patricia93sousa** [comment]
Ok I got this. Thanks.

Can I test a script from a true CA? Instead of localhost a self-signed certificate in this library?

I would like to establish a communication between server-client validating the certificates (which I already have and generated based on easypki by google) in a CA. Does this library support this? If so, how can I do it?

Thank you.

**Comment by patricia93sousa** [comment]
I ask this because this library only generates traffic in localhost, so, means that it does not test on a true CA in the network.

**Comment by ejona86** [comment]
The default host is simply localhost. You can change the hostname via [`--server_host`](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#client). If you don't use `--use_test_ca=true`, then it will use the default root CAs.

To use a publicly-trusted certificate, you would need to [modify the server](https://github.com/grpc/grpc-java/blob/v1.3.0/interop-testing/src/main/java/io/grpc/testing/integration/TestServiceServer.java#L139) or use grpc-test.sandbox.googleapis.com: `./run-test-client.sh --server_host=grpc-test.sandbox.googleapis.com --server_port=443` .

**Comment by kant111** [comment]
+1 Same error here
