### ISSUE TITLE
grpc-cli return Received an error when querying services endpoint.

### ISSUE THREAD

**Issue by SeriousMa** [grpc/grpc-java#2986]
grpc version 1.3.0

jdk 1.8

add ProtoReflectionService after my service 

```
private NettyServerBuilder initConfigServer() {
        Integer workers = Optional.fromNullable(providerSettingConfig.getIothreads()).or(0);
        NettyServerBuilder builder = NettyServerBuilder
                .forPort(registryConfig.getServicePort())
                .bossEventLoopGroup(create(Constants.NETTY_BOSS_EVEN_LOOP_GROUP, 1))
                .workerEventLoopGroup(create(Constants.NETTY_WORKER_EVEN_LOOP_GROUP, workers));
        logger.debug("server:netty boss:{} worker:{}", 1, workers);

        for (ServerServiceDefinition ssd : ssds) {
            builder.addService(ssd);
        }

        builder.addService(ProtoReflectionService.newInstance());

        return builder;
    }
```

then run 
```
./grpc_cli ls localhost:50053
```
return 
```
Received an error when querying services endpoint.
```

io.grpc.examples.helloworld.HelloWorldServer is the same problem too

**Comment by ejona86** [comment]
@yang-g, is there a way to get a better error message from grpc_cli?

**Comment by minorhacks** [comment]
I am also encountering a similar issue, with a trivial C++ server implementation. I can get a client to talk to the server, but I would like for grpc_cli to work as well.

One way to get a better error message is to set the GRPC_VERBOSITY environment variable:

```sh
$ export GRPC_VERBOSITY=DEBUG
$ grpc_cli ls 127.0.0.1:8082
I0524 12:17:11.377249569     658 ev_epollsig_linux.c:90]     epoll engine will be using signal: 40
D0524 12:17:11.377294531     658 ev_posix.c:121]             Using polling engine: epollsig
D0524 12:17:11.377329982     658 dns_resolver.c:316]         Using native dns resolver
I0524 12:17:11.377894936     658 proto_reflection_descriptor_database.cc:281] Error on GetServices() response type
	Expecting: 6
	Received: 0
Received an error when querying services endpoint.
I0524 12:17:11.377953670     658 proto_reflection_descriptor_database.cc:61] ServerReflectionInfo rpc failed. Error code: 12, details: 
```

@SeriousMa Are your failure details similar?

**Comment by SeriousMa** [comment]
@minorhacks 
I dont know why 。。my app return to normal

but i run
```
./grpc_cli ls localhost:50053
```
it just return 
```
D0525 14:30:54.195867000 140736132367296 ev_posix.c:107]               Using polling engine: poll
D0525 14:30:54.196922000 140736132367296 dns_resolver.c:316]           Using native dns resolver
grpc.reflection.v1alpha.ServerReflection
```
dosent include my grcp service...
@ejona86  can you check look at this？
my server build code
```

    private void createServer() {
        if (ssds != null && ssds.size() > 0) {
            NettyServerBuilder builder = initConfigServer();
            configThreadPool(builder);
            server = builder.build();
        }
    }
    private NettyServerBuilder initConfigServer() {
        Integer workers = Optional.fromNullable(providerSettingConfig.getIothreads()).or(0);
        NettyServerBuilder builder = NettyServerBuilder
                .forPort(registryConfig.getServicePort())
                .bossEventLoopGroup(create(Constants.NETTY_BOSS_EVEN_LOOP_GROUP, 1))
                .workerEventLoopGroup(create(Constants.NETTY_WORKER_EVEN_LOOP_GROUP, workers));
        logger.debug("server:netty boss:{} worker:{}", 1, workers);

        for (ServerServiceDefinition ssd : ssds) {
            builder.addService(ssd);
        }
        builder.addService(ProtoReflectionService.newInstance());
        return builder;
    }

    private void startServer() {
        Thread daemon = new Thread() {
            @Override
            public void run() {
                try {
                    server.start();
                    server.awaitTermination();
                } catch (IOException e) {
                    logger.error("servers start error @port:{}", registryConfig.getServicePort(), e);
                } catch (InterruptedException e) {
                    logger.error("blockUntilShutdown error ", e);
                }
            }
        };

        daemon.setDaemon(true);
        daemon.start();
    }
```

**Comment by ericgribkoff** [comment]
@SeriousMa Services are only visible to the reflection service if they implement the experimental `InternalNotifyOnServerBuild` interface (as the automatically generated services do) and are added to the `ServerBuilder` via the `addService(BindableService)` method: see http://www.grpc.io/grpc-java/javadoc/io/grpc/ServerBuilder.html#addService-io.grpc.BindableService-. Your code is using the `addService(ServerServiceDefinition)` method, which won't get picked up by the reflection service.

@minorhacks If the issue continues, you should report it at https://github.com/grpc/grpc, but you can also reference https://github.com/grpc/grpc/blob/master/doc/server_reflection_tutorial.md to double-check that you've enabled reflection on your C++ server

**Comment by SeriousMa** [comment]
@ericgribkoff  thanks for reply
in future would consider adding support for ServerServiceDefinition ？
or is there other solutions based on my code , plz let me know ..

**Comment by ericgribkoff** [comment]
I'm sorry, I actually gave you an incorrect diagnosis in my earlier message - the `InternalNotifyOnServerBuild` interface is only required for the `ProtoReflectionService` itself, not for the services that should be visible via reflection. Sorry for the mistake.

Your `ServerServiceDefinition ssds` should be visible in the reflection service, as long as their accompanying `ServiceDescriptor` contains an attached `ProtoFileDescriptorSupplier` - see https://github.com/grpc/grpc-java/blob/master/services/src/main/java/io/grpc/protobuf/services/ProtoReflectionService.java#L426 for how this is picked up by the reflection service. Attaching the proto file descriptor to the service definition is handled automatically by the generated service code. Are you using the generated code? If so, this is probably a bug in the reflection service - could you include the complete code you are using for the server to allow me to reproduce the error? If you are not using the generated code, you can look at existing generated code output to see an example of attaching the proto file descriptors to your service descriptors.

**Comment by SeriousMa** [comment]
yes i use protobuf-maven-plugin  generate  code

but the ServerServiceDefinition  is made by this code
serviceClass is interface
serviceRef is implementation class
```

public class RpcServerServiceDefinition {
    private static final Logger logger = LoggerFactory.getLogger(RpcServerServiceDefinition.class);
    private Map<String, DescriptorProtos.MethodDescriptorProto> methodDPs = ProtocUtlils.getMethodDPs();

    @SuppressWarnings({"ConstantConditions", "unchecked"})
    public ServerServiceDefinition createServiceDef(Class<?> serviceClass, Object serviceRef) {
        String serviceName = serviceClass.getName();

        ServerServiceDefinition.Builder serviceDefBuilder = ServerServiceDefinition.builder(serviceName);
        List<Method> methods = GrpcReflectUtil.findAllPublicMethods(serviceClass);
        if (methods.isEmpty()) {
            logger.error("serivce {} have not method {}", serviceName, serviceClass);
            throw new IllegalStateException("serivce " + serviceName + " have not method " + serviceClass);
        }

        for (Method method : methods) {
            MethodDescriptor<Message, Message> methodDes = createMethodDescriptor(serviceClass, method);
            MethodInvocation methodInvocation = new MethodInvocation(serviceRef, method);
            ServerCallHandler serverCallHandler;

            switch (methodDes.getType()) {
                case UNARY:
                    serverCallHandler = ServerCalls.asyncUnaryCall(methodInvocation);
                    break;
                case BIDI_STREAMING:
                    serverCallHandler = ServerCalls.asyncBidiStreamingCall(methodInvocation);
                    break;
                case CLIENT_STREAMING:
                    serverCallHandler = ServerCalls.asyncClientStreamingCall(methodInvocation);
                    break;
                case SERVER_STREAMING:
                    serverCallHandler = ServerCalls.asyncServerStreamingCall(methodInvocation);
                    break;
                case UNKNOWN:
                    throw new RpcException("unknown method type!");
                default:
                    throw new RpcException("unknown method type!");
            }
            if (null != serverCallHandler) {
                serviceDefBuilder.addMethod(methodDes, serverCallHandler);
            }
        }
        return serviceDefBuilder.build();
    }

    private MethodDescriptor<Message, Message> createMethodDescriptor(Class<?> clzz, Method method) {
        Message argsReq = buildDefaultInstance(GrpcReflectUtil.getTypedReq(method));
        Message argsRep = buildDefaultInstance(GrpcReflectUtil.getTypeRep(method));

        String fullMethodName = MethodDescriptor.generateFullMethodName(clzz.getName(), method.getName());

        Preconditions.checkArgument(methodDPs.size() > 0, "not method descriptorProto maps");

        DescriptorProtos.MethodDescriptorProto mdp = methodDPs.get(fullMethodName);
        if (mdp == null) {
            //兼容方法名大写
            fullMethodName = MethodDescriptor.generateFullMethodName(clzz.getName(), StringUtils.capitalize(method.getName()));
            mdp = methodDPs.get(fullMethodName);
        }
        MethodDescriptor.MethodType methodType;

        if (mdp.getClientStreaming()) {
            if (mdp.getServerStreaming()) {
                methodType = MethodDescriptor.MethodType.BIDI_STREAMING;
            } else {
                methodType = MethodDescriptor.MethodType.CLIENT_STREAMING;
            }
        } else {
            if (mdp.getServerStreaming()) {
                methodType = MethodDescriptor.MethodType.SERVER_STREAMING;
            } else {
                methodType = MethodDescriptor.MethodType.UNARY;
            }
        }

        return MethodDescriptor.create(methodType, fullMethodName,
                ProtoUtils.marshaller(argsReq), ProtoUtils.marshaller(argsRep));
    }

    @SuppressWarnings("unchecked")
    private Message buildDefaultInstance(Class<?> type) {
        Class<? extends Message> messageType = (Class<? extends Message>) type;
        Object obj = GrpcReflectUtil.classInstance(messageType);
        return (Message) obj;
    }
}
```

**Comment by ejona86** [comment]
@SeriousMa, I think @ericgribkoff was right. It looks like you don't call `ServiceDescriptor.Builder.setSchemaDescriptor()` with an instance of `ProtoFileDescriptorSupplier`. If you do that, the services should start showing up.

I think that means you will need to create the `ServiceDescriptor` separately and then pass it into `ServerServiceDefinition`. For simple use cases `ServerServiceDefinition` will auto-create the `ServiceDescriptor`.

**Comment by SeriousMa** [comment]
@ejona86  i use class.method.invoke to get ServiceDescriptor and create ServerServiceDefinition

```
String grpcClassName = serviceName+"Grpc";
        ServiceDescriptor serviceDescriptor = null;
        try {
            Class grpcClass = Class.forName(grpcClassName);
            Method method = grpcClass.getMethod("getServiceDescriptor");
            serviceDescriptor = (ServiceDescriptor) method.invoke(null);
        } catch (Exception e) {
            logger.warn("grpc class grpcClass:{} err", grpcClassName, e);
        }

        ServerServiceDefinition.Builder serviceDefBuilder;
        if (serviceDescriptor != null) {
            serviceDefBuilder = ServerServiceDefinition.builder(serviceDescriptor);
        } else {
            serviceDefBuilder = ServerServiceDefinition.builder(serviceName);
        }
```

but i get  this exception info
```
Caused by: java.lang.IllegalStateException: Bound method for demo.NewsService/add not same instance as method in service descriptor
	at io.grpc.ServerServiceDefinition$Builder.build(ServerServiceDefinition.java:157)
```

i check the ServerServiceDefinition.Build code 
```
 ServiceDescriptor serviceDescriptor = this.serviceDescriptor;
      if (serviceDescriptor == null) {
        List<MethodDescriptor<?, ?>> methodDescriptors
            = new ArrayList<MethodDescriptor<?, ?>>(methods.size());
        for (ServerMethodDefinition<?, ?> serverMethod : methods.values()) {
          methodDescriptors.add(serverMethod.getMethodDescriptor());
        }
        serviceDescriptor = new ServiceDescriptor(serviceName, methodDescriptors);
      }
```
it will create serviceDescriptor self 
so  I dont konw why you told me to create serviceDescriptor 


and i also dont konw about this exception message ..
can you help me figure out this issue? thanks

**Comment by ejona86** [comment]
> Caused by: java.lang.IllegalStateException: Bound method for demo.NewsService/add not same instance as method in service descriptor
> 	at io.grpc.ServerServiceDefinition$Builder.build(ServerServiceDefinition.java:157)

That is complaining that the ServerServiceDefinition differs from the ServiceDescriptor. You should use the same MethodDescriptors as ServiceDescriptor in the ServerServiceDefinition.

**Comment by SeriousMa** [comment]
thanks !
it is worked！

**Comment by allquantor** [comment]
@minorhacks have the same issue as you, did you found any approach for this?

**Comment by luckymagic7** [comment]
@minorhacks 
Did you solve your problem? I have the same issue as you too..
```sh
I1130 21:18:34.937238762    5664 proto_reflection_descriptor_database.cc:281] Error on GetServices() response type
	Expecting: 6
	Received: 0
Received an error when querying services endpoint.
I1130 21:18:34.937297674    5664 proto_reflection_descriptor_database.cc:61] ServerReflectionInfo rpc failed. Error code: 12, details:
```
