### ISSUE TITLE
SerializingExecutorBenchmark fails to run

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#3034]
It appears it was broken on the initial commit a4d698f7c1. It's not quite obvious to me what executor was intended to be used.

```
java.lang.NullPointerException: 'executor' must not be null.
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
        at io.grpc.internal.SerializingExecutor.<init>(SerializingExecutor.java:69)
        at io.grpc.internal.SerializingExecutorBenchmark.<init>(SerializingExecutorBenchmark.java:58)
        at io.grpc.internal.generated.SerializingExecutorBenchmark_jmhType_B1.<init>(SerializingExecutorBenchmark_jmhType_B1.java:3)
        at io.grpc.internal.generated.SerializingExecutorBenchmark_jmhType_B2.<init>(SerializingExecutorBenchmark_jmhType_B2.java:3)
        at io.grpc.internal.generated.SerializingExecutorBenchmark_jmhType_B3.<init>(SerializingExecutorBenchmark_jmhType_B3.java:2)
        at io.grpc.internal.generated.SerializingExecutorBenchmark_jmhType.<init>(SerializingExecutorBenchmark_jmhType.java:2)
        at io.grpc.internal.generated.SerializingExecutorBenchmark_oneRunnableLatency_jmhTest._jmh_tryInit_f_serializingexecutorbenchmark0_0(SerializingExecutorBenchmark_oneRunnableLatency_jmhTest.java:337)
        at io.grpc.internal.generated.SerializingExecutorBenchmark_oneRunnableLatency_jmhTest.oneRunnableLatency_SampleTime(SerializingExecutorBenchmark_oneRunnableLatency_jmhTest.java:207)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by zhangkun83** [comment]
It's already fixed by @ejona86.
