### ISSUE TITLE
grpc-netty:jar:1.3.0 is using a buggy netty package?

### ISSUE THREAD

**Issue by alexandnpu** [grpc/grpc-java#3056]
why client is using http2 when i want it to use socket to connect unix domain?
`
    public static void main(String[] args) throws Exception {

        HelloWorldClient client = new HelloWorldClient(
                NettyChannelBuilder.forAddress(new DomainSocketAddress("/tmp/grpc.sock"))
                .channelType(KQueueDomainSocketChannel.class)
                .eventLoopGroup(new KQueueEventLoopGroup())
                .usePlaintext(true)
        );
        try {
      /* Access a service running on the local machine on port 50051 */
            String user = "world";
            if (args.length > 0) {
                user = args[0]; /* Use the arg as the name to greet if provided */
            }
            client.greet(user);
        } finally {
            client.shutdown();
        }
    }
`

The above is how I setup my client to connect to the rpc server based-on unix domain.

But I got the following exception.

```
Jun 05, 2017 4:11:46 PM com.alex.grpctest.HelloWorldClient greet
INFO: Will try to greet world ...
Exception in thread "main" java.lang.RuntimeException: java.lang.InstantiationError: io.netty.util.internal.PriorityQueue
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
	at com.alex.grpctest.rpc.GreeterGrpc$GreeterBlockingStub.sayHello(GreeterGrpc.java:156)
	at com.alex.grpctest.HelloWorldClient.greet(HelloWorldClient.java:54)
	at com.alex.grpctest.HelloWorldClient.main(HelloWorldClient.java:80)
Caused by: java.lang.InstantiationError: io.netty.util.internal.PriorityQueue
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.<init>(WeightedFairQueueByteDistributor.java:244)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.<init>(WeightedFairQueueByteDistributor.java:57)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.<init>(DefaultHttp2RemoteFlowController.java:65)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.<init>(DefaultHttp2RemoteFlowController.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.<init>(DefaultHttp2ConnectionEncoder.java:52)
	at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:145)
	at io.grpc.netty.NettyClientHandler.newHandler(NettyClientHandler.java:124)
	at io.grpc.netty.NettyClientTransport.start(NettyClientTransport.java:190)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:44)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:216)
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:186)
	at io.grpc.internal.ManagedChannelImpl$SubchannelImplImpl.obtainActiveTransport(ManagedChannelImpl.java:812)
	at io.grpc.internal.GrpcUtil.getTransportFromPickResult(GrpcUtil.java:592)
	at io.grpc.internal.DelayedClientTransport.newStream(DelayedClientTransport.java:161)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:222)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:270)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:186)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
	... 3 more
```

I can I configure my client to connect to the unix domain?

## Update 1

After some digging, I found that at this line:

```
io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.<init>(WeightedFairQueueByteDistributor.java:244)
```
which is in package: netty-codec-http2-4.1.8.Final-sources.jar

it is using

```
        State(Http2Stream stream, int initialSize) {
            this.stream = stream;
            queue = new PriorityQueue<State>(initialSize);
        }
```

There PriorityQueue is an interface which cannot be instantiated.

This might be a netty bug?

## Update 2

after using `mvn dependency:tree`

```
➜  grpctest mvn dependency:tree
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building grpctest 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ grpctest ---
[INFO] com.alex:grpctest:jar:1.0-SNAPSHOT
[INFO] +- io.grpc:grpc-netty:jar:1.3.0:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.3.0:compile (version selected from constraint [1.3.0,1.3.0])
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.0.19:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.3.0:compile
[INFO] |  |  \- com.google.instrumentation:instrumentation-api:jar:0.3.0:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.8.Final:compile (version selected from constraint [4.1.8.Final,4.1.8.Final])
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.8.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.8.Final:compile
[INFO] |  |  \- io.netty:netty-handler:jar:4.1.8.Final:compile
[INFO] |  \- io.netty:netty-handler-proxy:jar:4.1.8.Final:compile
[INFO] |     \- io.netty:netty-codec-socks:jar:4.1.8.Final:compile
[INFO] +- io.grpc:grpc-protobuf:jar:1.3.0:compile
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.2.0:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.7:compile
[INFO] |  +- com.google.api.grpc:grpc-google-common-protos:jar:0.1.6:compile
[INFO] |  \- io.grpc:grpc-protobuf-lite:jar:1.3.0:compile
[INFO] +- io.grpc:grpc-stub:jar:1.3.0:compile
[INFO] +- com.google.protobuf:protobuf-java:jar:3.3.0:compile
[INFO] \- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.11.Final:compile
[INFO]    +- io.netty:netty-common:jar:4.1.11.Final:compile
[INFO]    +- io.netty:netty-buffer:jar:4.1.11.Final:compile
[INFO]    +- io.netty:netty-transport-native-unix-common:jar:4.1.11.Final:compile
[INFO]    \- io.netty:netty-transport:jar:4.1.11.Final:compile
[INFO]       \- io.netty:netty-resolver:jar:4.1.11.Final:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.951 s
[INFO] Finished at: 2017-06-05T16:53:13+08:00
[INFO] Final Memory: 15M/220M
[INFO] ------------------------------------------------------------------------
```

it is `io.grpc:grpc-netty:jar:1.3.0` that is using the buggy netty package.

## Update 3

This bug is introduced in this commit:

https://github.com/netty/netty/commit/904e70a4d4065a8e9da882e8319c7d05846c799d

and it was fixed in this commit:

https://github.com/netty/netty/commit/3482651e0c29edfa02f189751c704ebe4fe8f54c

which is supposed to be in 4.1.11.Final.

I donot know how to check whether that commit is in that release, it needs to confirm.

**Comment by carl-mastrangelo** [comment]
It's possible.  I plan on releasing 1.4.0 tomorrow; could you try your program out again with the new package and see if the problem is resolved?

**Comment by ejona86** [comment]
This doesn't looks like a bug, but a problem caused by mixing Netty versions. That is highly likely to break. KQueue wasn't supported in the version of Netty gRPC was using in 1.3.0.

It seems like you just need to wait for grpc-java 1.4.0 which updates netty to 4.1.11.

**Comment by alexandnpu** [comment]
@carl-mastrangelo, I will give it a try after you release 1.4.0

**Comment by alexandnpu** [comment]
@carl-mastrangelo , release 1.4.0 is verified. It is OK now.
