### ISSUE TITLE
Potential deadlock due to calling callbacks while holding a lock

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#3084]
`InProcessClientStream` and `InProcessServerStream` are synchronized on their own. `InProcessClientStream.serverStreamListener` is called under `synchronized (InProcessClientStream.this)`, and vice versa.

If the application tries to call methods on `ClientCall` or `ServerCall` from within the callbacks (assuming that it has already taken care of the thread-safety of the method calls on "Call" objects), a deadlock is possible when direct executor is used. For example:
- Thread1
  1. `InProcessClientStream.serverRequested` (locks `InProcessClientStream.this`)
  1. `InProcessClientStream.serverStreamListener.messageRead()`
  1. Eventually reaches application callback, which calls `ServerCall.close()`
  1. `InProcessServerStream.close()` (locks `InProcessServerStream.this`)

- Thread2
  1. `InProcessServerStream.clientRequested` (locks `InProcessServerStream.this`)
  1. `InProcessServerStream.clientStreamListener.messageRead()`
  1. Eventually reaches application callback, which calls `ClientCall.close()`
  1. `InProcessClientStream.close()` (locks `InProcessClientStream.this`)

As locks are acquired in reverse orders from two threads, a deadlock is possible.

The fundamental issue is that we should not call into application code while holding a lock, because we don't know what application code can do thus we can't control the order of subsequent locking.

OkHttp has the same issue, because `OkHttpClientStream.transportDataReceived()`, which will call into application code, is called under lock.

We could use `ChannelExecutor` (maybe renamed) to prevent calling into callbacks while holding a lock.

**Comment by ArvinDevel** [comment]
I recently ran into a problem which is related to `InProcessServerStream ` and `InProcessClientStream ` deadlock.  When my server app thread response to client request, it will first lock `InProcessServerStream`, then try to lock `InProcessClientStream` which is locked by grpc-thread which wants to lock  `InProcessServerStream` at the same time. 
Does this mean I can only use the same grpc thread to response?

**Comment by ArvinDevel** [comment]
Output of jstack related to deadlock is below.
===================================================
"grpc-default-executor-1":
	at io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessServerStream.request(InProcessTransport.java:324)
	- waiting to lock <0x00000007b7f8d6f8> (a io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessServerStream)
	at io.grpc.internal.ServerCallImpl.request(ServerCallImpl.java:83)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:252)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:682)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.messagesAvailable(ServerImpl.java:693)
	at io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessClientStream.writeMessage(InProcessTransport.java:563)
	- locked <0x00000007b7f8d3f8> (a io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessClientStream)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:36)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:434)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
	at org.apache.bookkeeper.common.grpc.proxy.ProxyCall$RequestProxy.onMessage(ProxyCall.java:56)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:682)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"storage-scheduler-OrderedScheduler-0-0":
	at io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessClientStream.request(InProcessTransport.java:515)
	- waiting to lock <0x00000007b7f8d3f8> (a io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessClientStream)
	at io.grpc.internal.ForwardingClientStream.request(ForwardingClientStream.java:31)
	at io.grpc.internal.ClientCallImpl.request(ClientCallImpl.java:381)
	at io.grpc.PartialForwardingClientCall.request(PartialForwardingClientCall.java:34)
	at io.grpc.ForwardingClientCall.request(ForwardingClientCall.java:22)
	at io.grpc.ForwardingClientCall$SimpleForwardingClientCall.request(ForwardingClientCall.java:44)
	at io.grpc.PartialForwardingClientCall.request(PartialForwardingClientCall.java:34)
	at io.grpc.ForwardingClientCall.request(ForwardingClientCall.java:22)
	at io.grpc.ForwardingClientCall$SimpleForwardingClientCall.request(ForwardingClientCall.java:44)
	at org.apache.bookkeeper.common.grpc.proxy.ProxyCall$ResponseProxy.onMessage(ProxyCall.java:112)
	- locked <0x00000007b7f8d2c0> (a org.apache.bookkeeper.common.grpc.proxy.ProxyCall$ResponseProxy)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:526)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.messagesAvailable(ClientCallImpl.java:543)
	at io.grpc.internal.ForwardingClientStreamListener.messagesAvailable(ForwardingClientStreamListener.java:44)
	at io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessServerStream.writeMessage(InProcessTransport.java:377)
	- locked <0x00000007b7f8d6f8> (a io.grpc.inprocess.InProcessTransport$InProcessStream$InProcessServerStream)
	at io.grpc.internal.ServerCallImpl.sendMessage(ServerCallImpl.java:139)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:341)
	at org.apache.bookkeeper.stream.storage.impl.stream.WriteSession.accept(WriteSession.java:148)
	at org.apache.bookkeeper.stream.storage.impl.stream.WriteSession.accept(WriteSession.java:40)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by carl-mastrangelo** [comment]
Looks legit.

**Comment by ArvinDevel** [comment]
@carl-mastrangelo Any suggestions? Is my usage wrong? I'm confused by that why `InProcessServerStream` is coupled with `InProcessClientStream` so tightly？I think the `InProcessServerStream` should only responsible for transfer client request response to client.

**Comment by carl-mastrangelo** [comment]
I think this an actual bug, and there isn't much you can do about it.  The tight coupling is to make InProcess as close to being thread-free as possible (i.e. in unit tests, where it may not be possible to have multiple threads).   The pattern we use to solve this elsewhere is serializing all transport accesses, but that will take time to implement.

**Comment by ejona86** [comment]
When this is fixed we should also fix the references to it in the examples, introduced in #5672.
