### ISSUE TITLE
GrpcServerRule with directExecutor creates extra thread during teardown

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#3162]
```
        at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:613)
	at com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(ThreadFactoryBuilder.java:162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:336)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:555)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.grpc.internal.SharedResourceHolder.releaseInternal(SharedResourceHolder.java:139)
	at io.grpc.internal.SharedResourceHolder.release(SharedResourceHolder.java:92)
	at io.grpc.internal.SharedResourcePool.returnObject(SharedResourcePool.java:41)
	at io.grpc.internal.ServerImpl.checkForTermination(ServerImpl.java:293)
	at io.grpc.internal.ServerImpl.access$700(ServerImpl.java:67)
	at io.grpc.internal.ServerImpl$ServerListenerImpl.serverShutdown(ServerImpl.java:333)
	at io.grpc.inprocess.InProcessServer.shutdown(InProcessServer.java:65)
	at io.grpc.internal.ServerImpl.shutdown(ServerImpl.java:201)
	at io.grpc.internal.ServerImpl.shutdown(ServerImpl.java:67)
	at io.grpc.testing.GrpcServerRule.after(GrpcServerRule.java:100)
```

**Comment by dapengzhang0** [comment]
this is where the `timeoutService` used in `InProcessServer` even if no deadline is set.

**Comment by dapengzhang0** [comment]
@ejona86 Is it really necessary to spawn a new thread to release GrpcUtil.TIMER_SERVICE? Can it be released like this?

```
synchronized <T> T releaseInternal(final Resource<T> resource, final T instance) {
    final Instance cached = instances.get(resource);
    if (cached == null) {
      throw new IllegalArgumentException("No cached instance found for " + resource);
    }
    Preconditions.checkArgument(instance == cached.payload, "Releasing the wrong instance");
    Preconditions.checkState(cached.refcount > 0, "Refcount has already reached zero");
    cached.refcount--;
    if (cached.refcount == 0) {
      if (GrpcUtil.IS_RESTRICTED_APPENGINE || resource == GrpcUtil.TIMER_SERVICE) {
        // AppEngine must immediately release shared resources, particularly executors
        // which could retain request-scoped threads which become zombies after the request
        // completes.

        // GrpcUtil.TIMER_SERVICE manges ExecutorService resources,
        // ExecutorService.shutdown() does not wait for previously submitted tasks to
        // complete execution.
        resource.close(instance);
        instances.remove(resource);
      } else {
        Preconditions.checkState(cached.destroyTask == null, "Destroy task already scheduled");
        // Schedule a delayed task to destroy the resource.
        if (destroyer == null) {
          destroyer = destroyerFactory.createScheduledExecutor();
        }
        cached.destroyTask = destroyer.schedule(new LogExceptionRunnable(new Runnable() {
          @Override
          public void run() {
            synchronized (SharedResourceHolder.this) {
              // Refcount may have gone up since the task was scheduled. Re-check it.
              if (cached.refcount == 0) {
                resource.close(instance);
                instances.remove(resource);
                if (instances.isEmpty()) {
                  destroyer.shutdown();
                  destroyer = null;
                }
              }
            }
          }
        }), DESTROY_DELAY_SECONDS, TimeUnit.SECONDS);
      }
    }
    // Always returning null
    return null;
  }

```

**Comment by dapengzhang0** [comment]
Ignore my previous comment. I see why waiting for 1 second - it can make use of the timer resource more economically, if there are another `getObject` from the pool right after a release. And it only spawns a new thread for the first time.

**Comment by ejona86** [comment]
There's a thread created before this one, but it isn't noticed.
