### ISSUE TITLE
java.lang.ClassNotFoundException when rebuild my connector

### ISSUE THREAD

**Issue by z0mb1ek** [grpc/grpc-java#3186]
Hi. I make grpc libs for project like connector. It contains server and client realizations. When I rebuild my jar lib, and restart my service with new jar, but other service keep old jar I see:
```java
Exception in thread "grpc-default-executor-401" java.lang.NoClassDefFoundError: tnt/club/feed/connector/GetSocialPostIdsResponse$PostId
	at tnt.club.feed.connector.GetSocialPostIdsResponse.toBuilder(GetSocialPostIdsResponse.java:972)
	at tnt.club.feed.connector.GetSocialPostIdsResponse.newBuilder(GetSocialPostIdsResponse.java:966)
	at tnt.club.feed.post.service.FeedPostService.getModeratorFeedPosts(FeedPostService.java:145)
	at tnt.club.feed.grpc.FeedServiceImpl.getSocialPostIds(FeedServiceImpl.java:32)
	at tnt.club.feed.connector.FeedGrpc$MethodHandlers.invoke(FeedGrpc.java:390)
	at io.grpc.stub.ServerCalls$1$1.onHalfClose(ServerCalls.java:148)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:267)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$2.runInContext(ServerImpl.java:573)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: tnt.club.feed.connector.GetSocialPostIdsResponse$PostId
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

I use java 1.8_131 and grpc 1.4.0
thx

**Comment by ejona86** [comment]
This is unrelated to grpc. If you're in development, rebuilding may be removing a .jar from the old service's class path causing the class to not be found.

**Comment by z0mb1ek** [comment]
No, old service class path has needed jars. It only happen when jar with grpc rebuild.

**Comment by ejona86** [comment]
In any case, we can't help you. This is an application-level compilation/running/classpath issue.
