### ISSUE TITLE
after network had closed over 30 seconds , client receive server stream problem  

### ISSUE THREAD

**Issue by SeriousMa** [grpc/grpc-java#3308]
server code
```
 @Override
        public void markStream(req request, StreamObserver<resp> responseObserver) {
            int i = request.getCount();
            while (true) {
                try {
                    Thread.currentThread().sleep(2000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                responseObserver.onNext(resp.newBuilder().setCount(i++).build());
            }
        }
```
client code
```
 public static void main(String[] args) throws InterruptedException, ExecutionException {
        ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 8080)
                .usePlaintext(true)
                .build();
        BenchServiceGrpc.BenchServiceBlockingStub stub = BenchServiceGrpc.newBlockingStub(channel);
        req req = demo.req.newBuilder().setCount(1).build();
        Iterator<resp> iterable = stub.markStream(req);
        while (iterable.hasNext()) {
            resp resp = iterable.next();
            System.out.println(resp.getCount());
        }
    }
```

client-side closed network  after 30 second
server throws exception 
```
java.io.IOException: Operation timed out
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```
but  client-side didn't get any further exception messages  before network recover or after
and didn't receive server-side any stream messages

**Comment by zpencer** [comment]
Are you saying this works for 30 seconds and then begins to time out?

**Comment by SeriousMa** [comment]
@zpencer  server side throw time out exception  and that can be acceptable，
but client side has nothing

**Comment by SeriousMa** [comment]
change ManagedChannelBuilder to NettyChannelBuilder add keepAliveTime  it is ok now
