### ISSUE TITLE
NettyFlowControlTest is flaky

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#3310]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/3956/console

```
io.grpc.testing.integration.NettyFlowControlTest > largeBdp FAILED
    java.lang.AssertionError: Window was 655140 expecting 314570
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.grpc.testing.integration.NettyFlowControlTest.doTest(NettyFlowControlTest.java:154)
        at io.grpc.testing.integration.NettyFlowControlTest.largeBdp(NettyFlowControlTest.java:106)

289 tests completed, 1 failed
:grpc-interop-testing:test FAILED
```

**Comment by ejona86** [comment]
https://kokoro.corp.google.com/job/grpc/job/java/job/master/job/windows/job/continuous/job/windows/147/
```
java.lang.AssertionError: Window was 131070 expecting 314570
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at io.grpc.testing.integration.NettyFlowControlTest.doTest(NettyFlowControlTest.java:156)
	at io.grpc.testing.integration.NettyFlowControlTest.largeBdp(NettyFlowControlTest.java:106)
```

**Comment by dapengzhang0** [comment]
Seen at
https://travis-ci.org/grpc/grpc-java/builds/328345893?utm_source=github_status&utm_medium=notification

io.grpc.testing.integration.NettyFlowControlTest > largeBdp FAILED
    java.lang.AssertionError: Window was 688124 expecting 314570
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at io.grpc.testing.integration.NettyFlowControlTest.doTest(NettyFlowControlTest.java:154)
        at io.grpc.testing.integration.NettyFlowControlTest.largeBdp(NettyFlowControlTest.java:106)

**Comment by ejona86** [comment]
Closing this issue in favor of #2297.
