### ISSUE TITLE
NettyServerHandlerTest keepalive tests are flaky since netty 4.1.14

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#3326]
https://travis-ci.org/grpc/grpc-java/jobs/262360341

```
io.grpc.netty.NettyServerHandlerTest > maxConnectionAgeGrace_channelClosedAfterGracePeriod FAILED
    java.nio.channels.ClosedChannelException
        at io.netty.channel.embedded.EmbeddedChannel.checkOpen(EmbeddedChannel.java:644)
        at io.netty.channel.embedded.EmbeddedChannel.ensureOpen(EmbeddedChannel.java:656)
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:310)
        at io.grpc.netty.NettyHandlerTestBase.channelRead(NettyHandlerTestBase.java:140)
        at io.grpc.netty.NettyServerHandlerTest.createStream(NettyServerHandlerTest.java:735)
        at io.grpc.netty.NettyServerHandlerTest.maxConnectionAgeGrace_channelClosedAfterGracePeriod(NettyServerHandlerTest.java:709)
260 tests completed, 1 failed, 3 skipped
:grpc-netty:test FAILED
```

**Comment by dapengzhang0** [comment]
seen from
https://travis-ci.org/grpc/grpc-java/jobs/262824421
and
https://travis-ci.org/grpc/grpc-java/jobs/262824422

Wonder if `io.netty.channel.embedded.EmbeddedChannel` had some behavior change since last netty upgrade.

**Comment by dapengzhang0** [comment]
seen at
https://travis-ci.org/grpc/grpc-java/jobs/262390704

```
io.grpc.netty.NettyServerHandlerTest > keepAliveManager_pingTimeout FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.grpc.netty.NettyServerHandlerTest.keepAliveManager_pingTimeout(NettyServerHandlerTest.java:485)
```

**Comment by dapengzhang0** [comment]
seen at
https://travis-ci.org/grpc/grpc-java/jobs/262899878

```
io.grpc.netty.NettyServerHandlerTest > maxConnectionAge_goAwaySent FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.grpc.netty.NettyServerHandlerTest.maxConnectionAge_goAwaySent(NettyServerHandlerTest.java:669)
```

**Comment by dapengzhang0** [comment]
seen at https://travis-ci.org/grpc/grpc-java/jobs/262824421

```
io.grpc.netty.NettyServerHandlerTest > maxConnectionAgeGrace_channelClosedAfterGracePeriod FAILED
    java.nio.channels.ClosedChannelException
        at io.netty.channel.embedded.EmbeddedChannel.checkOpen(EmbeddedChannel.java:644)
        at io.netty.channel.embedded.EmbeddedChannel.ensureOpen(EmbeddedChannel.java:656)
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:310)
        at io.grpc.netty.NettyHandlerTestBase.channelRead(NettyHandlerTestBase.java:140)
        at io.grpc.netty.NettyServerHandlerTest.manualSetUp(NettyServerHandlerTest.java:163)
        at io.grpc.netty.NettyServerHandlerTest.maxConnectionAgeGrace_channelClosedAfterGracePeriod(NettyServerHandlerTest.java:708)
io.grpc.netty.NettyServerHandlerTest > maxConnectionIdle_activeThenRst FAILED
    java.nio.channels.ClosedChannelException
        at io.netty.channel.embedded.EmbeddedChannel.checkOpen(EmbeddedChannel.java:644)
        at io.netty.channel.embedded.EmbeddedChannel.ensureOpen(EmbeddedChannel.java:656)
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:310)
        at io.grpc.netty.NettyHandlerTestBase.channelRead(NettyHandlerTestBase.java:140)
        at io.grpc.netty.NettyServerHandlerTest.manualSetUp(NettyServerHandlerTest.java:163)
        at io.grpc.netty.NettyServerHandlerTest.maxConnectionIdle_activeThenRst(NettyServerHandlerTest.java:624)
```

and https://travis-ci.org/grpc/grpc-java/jobs/262824422

```
io.grpc.netty.NettyServerHandlerTest > maxConnectionAgeGrace_channelClosedAfterGracePeriod FAILED
    java.nio.channels.ClosedChannelException
        at io.netty.channel.embedded.EmbeddedChannel.checkOpen(EmbeddedChannel.java:644)
        at io.netty.channel.embedded.EmbeddedChannel.ensureOpen(EmbeddedChannel.java:656)
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:310)
        at io.grpc.netty.NettyHandlerTestBase.channelRead(NettyHandlerTestBase.java:140)
        at io.grpc.netty.NettyServerHandlerTest.manualSetUp(NettyServerHandlerTest.java:163)
        at io.grpc.netty.NettyServerHandlerTest.maxConnectionAgeGrace_channelClosedAfterGracePeriod(NettyServerHandlerTest.java:708)

```

**Comment by ericgribkoff** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/264532763

```
io.grpc.netty.NettyServerHandlerTest > maxConnectionAge_goAwaySent FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.grpc.netty.NettyServerHandlerTest.maxConnectionAge_goAwaySent(NettyServerHandlerTest.java:698)
```
