### ISSUE TITLE
Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]

### ISSUE THREAD

**Issue by septyy** [grpc/grpc-java#3336]
Please answer these questions before submitting your issue.

I've tried to use grpc-java library to connect sever side with SSL successfully in one lab, but when I change another lab to test that it was failure. I don't know whether the lab need to be set some environment variables or installed some rpms.

### What version of gRPC are you using?
<grpc.version>1.2.0</grpc.version>

### What JVM are you using (`java -version`)?
```
[root@bryan-appos-1709-1 ~]# java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)
```

### What did you do?
If possible, provide a recipe for reproducing the error.

Try to connection with SSL.

Here is my netty pom.xml
```
       ...... 
       <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>1.1.33.Fork26</version>
        </dependency>
        ......
```

### What did you expect to see?

Connection with SSL works fine.

### What did you see instead?

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
         at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:324)
         at serviceconfiguration.Test.main(Test.java:44)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]
         at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:177)
         at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:412)
         at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:90)
         at serviceconfiguration.Test.main(Test.java:40)
```

**Comment by ejona86** [comment]
Hmm... that's strange. The configuration looks fine.

It looks like its running on Linux. Which Linux distribution and versions were you trying (generally `cat /etc/os-release` will tell you)?

**Comment by septyy** [comment]
[root@septyy ~]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"

**Comment by septyy** [comment]
Hi, we would like to ask what grpc-java underlying implementation would check in openssl? Are there some dependencies rpms installed on OS, or some jar packages? We would like to check the difference between the two vlabs environments(one is successful, the other is failure). Or could you please share what should be done to check under the two vlabs?

**Comment by ejona86** [comment]
@septyy, is that `os-release` the working or broken environment? Is the other environment also RHEL 7.3?

`netty-tcnative-boringssl-static` doesn't have any dependencies other than glibc (so it breaks on Alpine which uses musl).

**Comment by septyy** [comment]
We used netty logging to debug our project. Then throwed exception as belows:

2017-08-16 01:48:06  [ io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:278) ] - [ DEBUG ]  Unable to load the library '/tmp/libnetty-tcnative-linux-x86_646785502292542875803.so', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative-linux-x86_646785502292542875803.so: /tmp/libnetty-tcnative-linux-x86_646785502292542875803.so: failed to map segment from shared object: Operation not permitted
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:296)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:287)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:275)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:249)
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:174)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:412)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:90)
	at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:158)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:139)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:109)
	at com.nokia.csf.sdc.SdcClient.sdcConnection(SdcClient.java:214)
	at com.nokia.csf.sdc.SdcClient.<init>(SdcClient.java:170)
	at serviceconfiguration.TestEtcd.main(TestEtcd.java:22)

Do you know the reason why throws exception like this?
We would appreciate you spend time checking our error info.
Thanks.

**Comment by ejona86** [comment]
Is your `/tmp` mounted with `noexec` (`mount | grep /tmp`)? If so, I guess set your `TMPDIR` environment variable to `/var/tmp`?

**Comment by septyy** [comment]
Thanks for your info. But it didn't work after we reset the TMPDIR to other folder like /root/tmp. But we managed to find a way to fix this issue. After we ran "mount /tmp -o remount,exec", the .so library could be found and loaded successfully.
