### ISSUE TITLE
springboot startup with java.lang.ClassNotFoundException: com.google.instrumentation.trace.TraceComponentImpl

### ISSUE THREAD

**Issue by wangzhenxyz1** [grpc/grpc-java#3337]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.3.0 1.4.0 1.5.0

### What JVM are you using (`java -version`)?
jdk6 jdk7 jdk8

### What did you do?
If possible, provide a recipe for reproducing the error.
startup springboot with log debug level

### What did you expect to see?
not output debug exception.

### What did you see instead?
```
2017-08-11 10:18:54.111 DEBUG 9000 --- [           main] com.google.instrumentation.trace.Tracer  : Using default implementation for TraceComponent.

java.lang.ClassNotFoundException: com.google.instrumentation.trace.TraceComponentImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_121]
	at com.google.instrumentation.trace.Tracing.loadTraceComponent(Tracing.java:51) [instrumentation-api-0.4.3.jar:0.4.3]
	at com.google.instrumentation.trace.Tracing.<clinit>(Tracing.java:25) [instrumentation-api-0.4.3.jar:0.4.3]
	at io.grpc.internal.AbstractServerImplBuilder.getTracerFactories(AbstractServerImplBuilder.java:209) [grpc-core-1.5.0.jar:1.5.0]
	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:189) [grpc-core-1.5.0.jar:1.5.0]
	at cn.enncloud.ceres.spring.ServiceBean.createServer(ServiceBean.java:185) [ceres-1.0.3-SNAPSHOT.jar:1.0.3-SNAPSHOT]
	at cn.enncloud.ceres.spring.ServiceBean.onApplicationEvent(ServiceBean.java:98) [ceres-1.0.3-SNAPSHOT.jar:1.0.3-SNAPSHOT]
	at cn.enncloud.ceres.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58) [ceres-1.0.3-SNAPSHOT.jar:1.0.3-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) [spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.demo.boot.CeresBootServerApplication.main(CeresBootServerApplication.java:10) [classes/:na]
```

grpc dependency:
```
<dependency>
    <groupId>com.google.instrumentation</groupId>
    <artifactId>instrumentation-api</artifactId>
    <version>0.4.3</version>
</dependency>
```
not exist TraceComponentImpl.java

now new alternatives:
census-instrumentation/opencensus-java
impl/src/main/java/io/opencensus/trace/TraceComponentImpl.java

**but not release**

**Comment by ejona86** [comment]
@zhangkun83, do you know what is going wrong here?

**Comment by zhangkun83** [comment]
Nothing is wrong. It's a debug log from census when no implementation is found:
https://github.com/census-instrumentation/opencensus-java/blob/v0.4.3/core/src/main/java/com/google/instrumentation/trace/Tracing.java

**Comment by ejona86** [comment]
Oh, you're right. I see the `DEBUG` there now.

@wangzhenxyz1, since DEBUG isn't enabled by default, did you turn on finer-grained logging or could this be related to #3033?

**Comment by wangzhenxyz1** [comment]
@ejona86  ok, i close the issue.
