### ISSUE TITLE
NullPointerException: trailers

### ISSUE THREAD

**Issue by mfirry** [grpc/grpc-java#3347]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0

### What JVM are you using (`java -version`)?
1.8.0

### What did you do?
Running my grpc services on [DC/OS](https://dcos.io/)... it works just fine but on the error log I sometimes see this NullPointerException.

### What did you see instead?
```
Aug 14, 2017 8:04:46 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1@567724e8
java.lang.NullPointerException: trailers
  at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
  at io.grpc.internal.AbstractServerStream.close(AbstractServerStream.java:125)
  at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:173)
  at ascoli.api.server.grcp.AuthInterceptor.interceptCall(AuthInterceptor.scala:29)
  at io.grpc.ServerInterceptors$InterceptCallHandler.startCall(ServerInterceptors.java:229)
  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:485)
  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1500(ServerImpl.java:346)
  at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1.runInContext(ServerImpl.java:429)
  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by dapengzhang0** [comment]
Is the ServerInterceptor `ascoli.api.server.grcp.AuthInterceptor.interceptCall(AuthInterceptor.scala:29)` calling `serverCall.close(status, null)`?

**Comment by mfirry** [comment]
Yes it is. `call.close(Status.UNAUTHENTICATED, null)`

**Comment by dapengzhang0** [comment]
If you own the interceptor code, you can call `call.close(Status.UNAUTHENTICATED, new Metadata())` instead.
