### ISSUE TITLE
gRPC throws `io.grpc.StatusRuntimeException: UNKNOWN` with netty-4.1.14

### ISSUE THREAD

**Issue by NathanHowell** [grpc/grpc-java#3358]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.5.0

### What JVM are you using (`java -version`)?

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What did you do?

Depend on Netty 4.1.14 instead of 4.1.11

Sample project demonstrating the issue: https://github.com/NathanHowell/spanner-test

### What did you expect to see?

A more obvious success or error message

### What did you see instead?

There is a rather large set of exceptions being raised on a 200 response from the server. The same project runs successfully if I downgrade netty to 4.1.13.

```
17:11:18.029 [grpc-default-worker-ELG-2-1] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x5de32e1f, L:/172.25.44.46:58714 - R:spanner.googleapis.com/172.217.5.74:443] INBOUND PRIORITY: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Fri, 18 Aug 2017 00:11:18 GMT, alt-svc: quic=":443"; ma=2592000; v="39,38,37,35"] padding=0 endStream=false

<trimmed>

	at io.grpc.netty.AbstractHttp2Headers.status(AbstractHttp2Headers.java:555)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:288)
```

Full exception:

```
17:11:18.029 [grpc-default-worker-ELG-2-1] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x5de32e1f, L:/172.25.44.46:58714 - R:spanner.googleapis.com/172.217.5.74:443] INBOUND PRIORITY: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-disposition: attachment, content-type: application/grpc, date: Fri, 18 Aug 2017 00:11:18 GMT, alt-svc: quic=":443"; ma=2592000; v="39,38,37,35"] padding=0 endStream=false
17:11:18.031 [grpc-default-worker-ELG-2-1] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x5de32e1f, L:/172.25.44.46:58714 - R:spanner.googleapis.com/172.217.5.74:443] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=2 length=0 bytes=
17:11:18.032 [grpc-default-worker-ELG-2-1] DEBUG io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0x5de32e1f, L:/172.25.44.46:58714 - R:spanner.googleapis.com/172.217.5.74:443] Sent GOAWAY: lastStreamId '0', errorCode '2', debugData ''. Forcing shutdown of the connection.
Exception in thread "main" com.google.cloud.spanner.SpannerException: UNKNOWN: io.grpc.StatusRuntimeException: UNKNOWN
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:71)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:58)
	at com.google.cloud.spanner.SessionPool$Waiter.take(SessionPool.java:413)
	at com.google.cloud.spanner.SessionPool$Waiter.access$3300(SessionPool.java:399)
	at com.google.cloud.spanner.SessionPool.getReadSession(SessionPool.java:754)
	at com.google.cloud.spanner.DatabaseClientImpl.singleUse(DatabaseClientImpl.java:42)
	at Main.main(Main.java:17)
Caused by: com.google.cloud.spanner.SpannerException: UNKNOWN: io.grpc.StatusRuntimeException: UNKNOWN
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:71)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:58)
	at com.google.cloud.spanner.SessionPool$4.run(SessionPool.java:1072)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.spanner.SpannerException: UNKNOWN: io.grpc.StatusRuntimeException: UNKNOWN
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:119)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:43)
	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:80)
	at com.google.cloud.spanner.spi.v1.GrpcSpannerRpc.get(GrpcSpannerRpc.java:414)
	at com.google.cloud.spanner.spi.v1.GrpcSpannerRpc.createSession(GrpcSpannerRpc.java:332)
	at com.google.cloud.spanner.SpannerImpl$2.call(SpannerImpl.java:221)
	at com.google.cloud.spanner.SpannerImpl$2.call(SpannerImpl.java:218)
	at com.google.cloud.spanner.SpannerImpl.runWithRetries(SpannerImpl.java:200)
	at com.google.cloud.spanner.SpannerImpl.createSession(SpannerImpl.java:217)
	at com.google.cloud.spanner.SessionPool$4.run(SessionPool.java:1063)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479)
	at com.google.cloud.spanner.spi.v1.GrpcSpannerRpc.get(GrpcSpannerRpc.java:408)
	... 13 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.spanner.spi.v1.WatchdogInterceptor$MonitoredCall$1.onClose(WatchdogInterceptor.java:190)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	... 3 more
Caused by: java.lang.UnsupportedOperationException
	at io.grpc.netty.AbstractHttp2Headers.status(AbstractHttp2Headers.java:555)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:288)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:269)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:483)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:491)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:354)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:414)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1336)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
```

**Comment by carl-mastrangelo** [comment]
@NathanHowell alas, grpc is mostly lock step with netty, due to the netty http2 being unstable.  We will be releasing 1.6 in about a week and a half, which will work with the latest netty.

**Comment by NathanHowell** [comment]
Fair enough, ran into this trying to work through the infamous `Jetty ALPN/NPN has not been properly configured.` error... finally managed to get past it by upgrading to gRPC 1.5, neither 1.2 or 1.4 worked with any of the workarounds. Lots of fun trying to get the Spanner client working in a Beam project 😞

**Comment by carl-mastrangelo** [comment]
I assume netty tcnative is not feasible on one of the older versions?

**Comment by NathanHowell** [comment]
I tried about a dozen variations of older versions of gRPC, netty-tcnative and netty-tcnative-boringssl-static and nothing worked until gRPC-1.5.0 and netty-tcnative-boringssl-static-2.0.5.Final. This is on my laptop running OSX 10.12.6, I don't know if the same problem exists on the Cloud Dataflow image.

**Comment by carl-mastrangelo** [comment]
Netty tcnative includes really helpful debug messages.  Did you turn on fine / debug / verbose logging and see why it failed to load?

Some back ground:  Netty tcnative works by including 3 different compiled versions of itself, for windows linux and mac.  On load it unzips the correct one to your temp folder and tries to load it using System.loadLibrary.

**Comment by NathanHowell** [comment]
I had debug logs enabled (see the Spanner logs) but didn't notice anything related to tcnative, but I also didn't know what I was looking for. There were a handful of other issues related to netty and protobuf versions in Beam that I had to sort through first and just wanted to get a simple Pubsub->Spanner beam job running. If this comes up again I'll have the other devs look specifically at the tcnative logs.

**Comment by ejona86** [comment]
This seems to be old/outdated mixing of Netty/gRPC versions. Error details have improved there, although it's never guaranteed to be possible. Things seem fixed here as well as they can be.
