### ISSUE TITLE
Seeing lots of "failed to mark a promise as failure because it has succeeded already" warnings

### ISSUE THREAD

**Issue by lalithsuresh** [grpc/grpc-java#3364]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.0-SNAPSHOT (master branch, 8d6ff4c9b4c2fe42bcb71ae694fbe697511a2a6a)

### What JVM are you using (`java -version`)?

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

Only appears at high load (one node sending a unary RPC each to a ~1000 other nodes).

### What did you see instead?

A lot of log spam with the following:

WARN [elg-rapid-97:1234-3-1] (Slf4JLogger.java:146) - Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@6ac7d732(success)
java.lang.UnsupportedOperationException
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ConnectionStream.resetSent(DefaultHttp2Connection.java:606)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.resetStream(Http2ConnectionHandler.java:732)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.resetStream(Http2ConnectionHandler.java:710)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeRstStream(DefaultHttp2ConnectionEncoder.java:243)
        at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeRstStream(DecoratingHttp2FrameWriter.java:65)
        at io.netty.handler.codec.http2.StreamBufferingEncoder.writeRstStream(StreamBufferingEncoder.java:174)
        at io.grpc.netty.NettyClientHandler.cancelStream(NettyClientHandler.java:472)
        at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:236)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1030)
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
        at io.grpc.netty.WriteQueue$AbstractQueuedCommand.run(WriteQueue.java:186)
        at io.grpc.netty.WriteQueue.flush(WriteQueue.java:124)
        at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32)
        at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)

**Comment by zhangkun83** [comment]
@ejona86 this sounds like a legitimate bug.

**Comment by ejona86** [comment]
We're trying to send a RST_STREAM on stream 0, which is invalid. This could be caused by `NettyClientStream.cancel()` being called before `NettyClientStream..sendHeaders()` (which is called by `AbstractClientStream.start()`.

It looks like `ClientCall.cancel()` is being called before `ClientCall.start()`. We're supposed to support that case, so this needs to be fixed, but that shouldn't happen too frequently. I wonder if DelayedStream could contribute in the case of deadlines.

**Comment by lalithsuresh** [comment]
Does this happen because the deadline for a request expires before ClientCall.start()?

**Comment by ejona86** [comment]
@lalithsuresh, we don't think so. We see the deadline scheduling happening after `start()`. That does raise the question why you are seeing it so frequently. The stubs can call `cancel()` before `start()`, but only only if an exception is thrown (unlikely/rare), which would also be thrown up to your application.

So there is still a bit of an open question why you are seeing this so frequently.

It may be that the channel has encountered a failure or is being shut down. That's [avoid the `setId()`](https://github.com/grpc/grpc-java/blob/fe1583c/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L398). But it didn't sound like you were shutting down the channel to trigger the problem.

**Comment by zhangkun83** [comment]
This isn't making it to 1.9. Deferring to 1.10.

**Comment by ejona86** [comment]
#3807 is another instance of this issue. It has separate but similar (at a glance) investigation.

**Comment by sleoniy** [comment]
Any update? Still experiencing this

**Comment by ejona86** [comment]
This hasn't been seen in many years, so seems to have been fixed.
