### ISSUE TITLE
grpc client sometimes stuck after connection reset

### ISSUE THREAD

**Issue by hhclam** [grpc/grpc-java#3427]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.2

### What JVM are you using (`java -version`)?

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.

We run the services in kubernetes load balanced by a kubernetes. The servers are running grpc java server with TLS. Clients are also running grpc java. After we have changed a kubernetes setting of --conntrack-tcp-timeout-close-wait duration from default 1h0m0s to 60s and --conntrack-tcp-timeout-established duration from default 24h0m0s to 15m. We have started to see a lot of stuck clients where all calls timed out after seeing this exception:

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

### What did you expect to see?

All our calls are unary calls. I expect them they will go through even after seeing the connection reset.

### What did you see instead?

About 0.5% of clients are stuck (we have about 10k clients running). And inspecting the heap dump of a stuck client after the calls is made revealed the state 2 instances of InternalSubchannel and activeTransport and pendingTransport are null in them. Forcing the client call did not change the state of the InternalSubchannel, the client was stuck indefinitely until the process was killed and restarted. After restarting the process it became normal again.

**Comment by carl-mastrangelo** [comment]
@hhclam There have been a LOT of bug fixes since 1.2.   Can you try with 1.6.1 to see if the problem persists?

**Comment by hhclam** [comment]
Yeah we're upgrading to 1.6 to see this solves the problem. Our upgrade cycle is slow.. I'll let you know.

**Comment by ejona86** [comment]
hhclam and I [went back-and-forth on IRC](https://botbot.me/freenode/grpc/2017-07-24/?msg=88991126&page=1).

The symptom is that the `InternalSubchannel` is IDLE with `activeTransport=null` and some RPCs are hung and new RPCs are hung.

**Comment by ejona86** [comment]
Oh, and it seems to be triggered by a iptables-based kube-proxy lowering its settings for --conntrack-tcp-timeout-close-wait and --conntrack-tcp-timeout-established. This triggered more connection resets, which may have tickled something.

**Comment by schmohlio** [comment]
is this an issue in 6.1?

**Comment by immrleung** [comment]
excuse me, upgrading could fix this problem? @ejona86
