### ISSUE TITLE
Https with grpc

### ISSUE THREAD

**Issue by yangliucheng** [grpc/grpc-java#3456]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6

### What JVM are you using (`java -version`)?
1.8

### What did you do?
If possible, provide a recipe for reproducing the error.

I create a HTTPS with grpc use code as follow:

https://github.com/grpc/grpc-java/blob/master/interop-testing/src/test/java/io/grpc/testing/integration/TlsTest.java

### What did you see instead?
But i got this 
Exception in thread "main" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:159)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at Demo.grpcSSLetcd(Demo.java:144)
	at Demo.main(Demo.java:64)

**Comment by yangliucheng** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at Demo.grpcSSLetcd(Demo.java:212)
	at Demo.main(Demo.java:75)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:427)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:419)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:60)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:493)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$500(ClientCallImpl.java:422)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:525)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zpencer** [comment]
It sounds like you copied some of the existing code to a new project. Can you confirm that you have included the required security libraries in the new project?
https://github.com/grpc/grpc-java/blob/master/SECURITY.md

**Comment by carl-mastrangelo** [comment]
@yangliucheng   it looks like the issue can be fixed by adding the security libraries like @zpencer suggests.

I'm closing this, but feel free to reopen if that doesn't work.
