### ISSUE TITLE
Cannot compile C++ code on WIndows (VisualCpp)

### ISSUE THREAD

**Issue by magx2** [grpc/grpc-java#346]
Hi, 

I'm trying to build project under Windows. To do this I added tool chain with *visualCpp(VisualCpp)* (*compiler/build.gradle*):

	toolChains {
	    visualCpp(VisualCpp) {
	      installDir "c:/path/Microsoft Visual Studio 12.0"
	    }
	    gcc(Gcc) {
	      target("x86_64") {
		cppCompiler.withArguments { args ->
		  args << "-m64"
		}
		linker.withArguments { args ->
		  args << "-m64"
		}
	      }
	      target("x86_32") {
		cppCompiler.withArguments { args ->
		  args << "-m32"
		}
		linker.withArguments { args ->
		  args << "-m32"
		}
	      }
	      target('local_arch') { }
	    }
	    [...]

Sadly VisualCpp plugin does not support ```target``` and I get error:

	* Exception is:
	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':grpc-compiler:compileLocal_archJava_pluginExecutableJava_pluginCpp'.
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
		at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
		at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
		at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
		at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
		at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
		at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
		at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
		at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
		at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
		at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
		at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
		at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
		at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
		at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
		at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
		at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
		at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
		at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
		at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
		at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
		at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
		at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	       at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
		at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
		at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
		at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
		at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
		at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
		at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
		at org.gradle.launcher.Main.doAction(Main.java:33)
		at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
		at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
		at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
		at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
		at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
		at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
		at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
	Caused by: org.gradle.api.GradleException: No tool chain is available to build for platform 'local_arch':
	  - Tool chain 'visualCpp' (Visual Studio): Don't know how to build for platform 'local_arch'.
	  - Tool chain 'gcc' (GNU GCC): Could not find C compiler 'gcc' in system path.
	  - Tool chain 'clang' (Clang): Could not find C compiler 'clang' in system path.
		at org.gradle.nativeplatform.toolchain.internal.UnavailablePlatformToolProvider.failure(UnavailablePlatformToolProvider.java:47)
		at org.gradle.nativeplatform.toolchain.internal.UnavailablePlatformToolProvider.newCompiler(UnavailablePlatformToolProvider.java:71)
		at org.gradle.language.nativeplatform.tasks.AbstractNativeCompileTask.compile(AbstractNativeCompileTask.java:83)
		at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:235)
	 
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:222)
		at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
		... 47 more

**Comment by magx2** [comment]
This was introduced in commit: da3c3f8ced6b3630eb72cc5b9ff2cf8d31efadac (https://github.com/grpc/grpc-java/commit/da3c3f8ced6b3630eb72cc5b9ff2cf8d31efadac) @zhangkun83

**Comment by magx2** [comment]
Also there is a bug in platforms, there is no such platform ```x86_32```, instead use ```x86``` (http://gradle.org/docs/current/userguide/nativeBinaries.html *55.14.2.*).

    x86_32 {
      architecture "x86_32" <- use "x86"
    }

Next think *visualCpp* does not now how to build platform ```local_arch``` and I get an error while running ```gradlew install```. Quick fix in this case is change it to ```osdetector.arch``` but this is not good for long term, i.e. I cannot build on my pc (x86_62) native 64 bit app, because I don't have binaries in this arch. In this case I'm always build 32 bits (by TARGET_ARCH)

**Comment by ejona86** [comment]
@magx2, are you using Gradle 2.2? With zhangkun83's change we swapped to Gradle 2.3. Using the gradlew script would make sure you are using the correct version.

**Comment by ejona86** [comment]
@magx2, nevermind. Yeah, you are right, it does look like we've got some issues.

**Comment by magx2** [comment]
@ejona86 using gradle wrapper so everything is working great (suck it maven ;) )

**Comment by zhangkun83** [comment]
@magx2 can you share your working build.gradle?

**Comment by magx2** [comment]
@zhangkun83  You want all file or only diff?

**Comment by zhangkun83** [comment]
Diff is fine :)

**Comment by magx2** [comment]
@ Poland is 23:42 so I will post this to you tomorrow ;) (from work)

More or less I did this (written from memory):

	model {
	  toolChains 
	    // added new vcpp toolchain
	    visualCpp(VisualCpp) {
	    	installDir "dir"
	    }
	    gcc(Gcc) {
	      target("x86_64") {
		cppCompiler.withArguments { args ->
		  args << "-m64"
		}
		linker.withArguments { args ->
		  args << "-m64"
		}
	      }
	      target("x86_32") {
		cppCompiler.withArguments { args ->
		  args << "-m32"
		}
		linker.withArguments { args ->
		  args << "-m32"
		}
	      }
	      target('local_arch') { }
	    }
	    clang(Clang) {
	      target("x86_64") {
		cppCompiler.withArguments { args ->
		  args << "-m64"
		}
		linker.withArguments { args ->
		  args << "-m64"
		}
	      }
	      target('local_arch') { }
	    }
	  }
	  platforms {
	    x86_32 {
	      architecture "x86" // removed '_32'
	    }
	    x86_64 {
	      architecture "x86_64"
	    }
	    local_arch {
	      architecture 'x86' // changed 'local_arch' to 'x86'; this is just dirty quick fix :(
	    }
	  }
