### ISSUE TITLE
manual flow control enabled not worked effectively

### ISSUE THREAD

**Issue by conanchen** [grpc/grpc-java#3484]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.6.1

### What JVM are you using (`java -version`)?
java 8 

### What did you do?

I have a server side stream api and on client side I have manual flow control enabled. 
```java
        public void onNext(ImageOuterClass.ImageResponse response) {
                 // process response
                 requestStream.request(1);
        }
```
If I send multiple messages without pause between response.onNext(), 
```java
for (Image im : images) {
  if (serverCallStreamObserver.isReady()) {
    response.onNext(imageResponse);
  }
  //Thread.sleep(100);
}
```
got exception:-
```
,Quote 912017-09-22 00:01:09.800  INFO 39104 --- [dPoolExecutor-2] org.ditto.sexyimage.grpc.ImageService    : SendImages onNext url=[https://imgcache.cjmx.com/star/201512/20151201213056390.jpg]
,Quote 922017-09-22 00:01:09.799  INFO 39104 --- [dPoolExecutor-1] org.ditto.sexyimage.grpc.ImageService    : SendImages onNext url=[https://imgcache.cjmx.com/star/201512/20151201213056390.jpg]
,Quote 932017-09-22 00:01:09.800  WARN 39104 --- [-worker-ELG-3-1] io.netty.util.ReferenceCountUtil         : Failed to release a message: UnpooledSlicedByteBuf(freed)

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:101) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:89) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:89) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:85) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.CompositeByteBuf$Component.freeIfNecessary(CompositeByteBuf.java:1672) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:1937) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:106) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:89) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:89) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:85) ~[netty-buffer-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:84) ~[netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:109) ~[netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:256) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:337) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:448) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:362) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:823) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1304) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:172) [netty-codec-http2-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:982) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:244) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:124) [grpc-netty-1.6.1.jar:1.6.1]
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32) [grpc-netty-1.6.1.jar:1.6.1]
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44) [grpc-netty-1.6.1.jar:1.6.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [netty-transport-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.14.Final.jar:4.1.14.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

2017-09-22 00:01:09.800  INFO 39104 --- [dPoolExecutor-3] org.ditto.sexyimage.grpc.ImageService    : SendImages onNext url=[https://imgcache.cjmx.com/star/201512/20151201213056390.jpg]
,Quote 942017-09-22 00:01:09.800  INFO 39104 --- [dPoolExecutor-4] org.ditto.sexyimage.grpc.ImageService    : SendImages onNext url=[https://imgcache.cjmx.com/star/201512/20151201213056390.jpg]
```

**Comment by carl-mastrangelo** [comment]
Do you have any more context here?   With the code listed I am not sure where to start looking.

**Comment by zpencer** [comment]
For examples of what the build file should look like, look at the examples directory.

**Comment by ejona86** [comment]
This seems like a reference counting issue and not a flow control issue. But there's really no information for us to go on.
