### ISSUE TITLE
Unexpected RST_STREAM(CANCEL) and subsequent RPC-call cancelling

### ISSUE THREAD

**Issue by crazyproger** [grpc/grpc-java#3508]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.5.0 on both sides

### What JVM are you using (`java -version`)?
On both sides
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### What did you do?
I have GRPC server(aka service) and GRPC client, both in java. Client is doing some frequent task. Earlier client was using only one rpc-call per task, but today I've add second subsequent rpc-call to task processing. Rpc-calls are different - goes to different `Service.method`s). After adding second call I started to catch  `io.grpc.StatusRuntimeException: CANCELLED` in **second** subsequent rpc-call on rpc client-side. Exception is not so frequent, it was only two times per day, but reason of cancelling is unknown.
One maybe important thing: thread in which rpc-client work - is a GRPC-server rpc processing thread(so client is also a GRPC-server but I think it should not be relevant). 
There is no timeouts or cancellations in my code. Channel created as(this is kotlin, sorry):
```Kotlin
val sslContext: SslContext
val serverCA = loadResourceAsStream("${config.certsPath}serverCA.crt")
val clientCert = loadResourceAsStream("${config.certsPath}client.crt")
val clientKey = loadResourceAsStream("${config.certsPath}client.key")
sslContext = GrpcSslContexts.configure(SslContextBuilder.forClient(), SslProvider.OPENSSL)
         .trustManager(serverCA)
         .keyManager(clientCert, clientKey)
         .clientAuth(ClientAuth.REQUIRE)
          .build()
builder = NettyChannelBuilder.forAddress(config.host, config.port).sslContext(sslContext)
builder.build()
```
This is how rpc-call is made:
```Kotlin
val request = OnlineInfoRequestDto.newBuilder().setPlayerId(playerId.toString()).build()
val response = OnlineInfoServiceGrpc.newBlockingStub(channel)
                    .info(request)
```
In task processing code calls are going in this order(code is synchronous):
1. MatchmakingInfoService.Info
2. OnlineInfoService.Info

This is log of exception:
```
ERROR 2017-09-26 22:22:41,258 mm.public.rpc-60 (b.m.r.RemoteOnlineInfoService:?  ) - On request online info
io.grpc.StatusRuntimeException: CANCELLED
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:212)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:193)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:126)
        at base.rpc.profile.mm.OnlineInfoServiceGrpc$OnlineInfoServiceBlockingStub.info(OnlineInfoServiceGrpc.java:172)
        at base.mm.rpc.RemoteOnlineInfoService$info$1.invoke(RemoteOnlineInfoService.kt:24)
        at base.mm.rpc.RemoteOnlineInfoService$info$1.invoke(RemoteOnlineInfoService.kt:17)
```
From this log we can see the time and stub - `CANCEL` was triggered for `OnlineInfoService` call.
But in GRPC logs I didn't find any call to this rpc(OnlineInfoService) with CANCEL, instead I've found call with RST_STREAM for **previous** call
Logs from client, stream with RST_STREAM:
```
DEBUG 2017-09-26 22:22:41,196 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] HEADERS: streamId=821, headers=GrpcHttp2OutboundHeaders[:authority: SERVER_DOMAIN:50050, :path: /base.rpc.profile.mm.MatchmakingInfoService/Info, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.5.0, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
--
DEBUG 2017-09-26 22:22:41,197 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] DATA: streamId=821, padding=0, endStream=true, length=51, bytes=000000002e0a06313331373531122438376263343334612d626533612d346436612d383239382d613039343738313963666638
--
DEBUG 2017-09-26 22:22:41,254 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] HEADERS: streamId=821, headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
--
DEBUG 2017-09-26 22:22:41,256 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] DATA: streamId=821, padding=0, endStream=false, length=13, bytes=00000000081802200128023001
--
DEBUG 2017-09-26 22:22:41,256 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] HEADERS: streamId=821, headers=GrpcHttp2ResponseHeaders[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
--
DEBUG 2017-09-26 22:22:41,257 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] RST_STREAM: streamId=821, errorCode=8
```
What we can see here:
1. The call is base.rpc.profile.mm.MatchmakingInfoService/Info
2. RST_STREAM is sent after receiving response(reason?)

Right after that going normal call to second service - OnlineInfoService:
```
DEBUG 2017-09-26 22:22:41,319 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] HEADERS: streamId=825, headers=GrpcHttp2OutboundHeaders[:authority: SERVER_DOMAIN:50050, :path: /base.rpc.profile.mm.OnlineInfoService/Info, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.5.0, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
--
DEBUG 2017-09-26 22:22:41,319 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] DATA: streamId=825, padding=0, endStream=true, length=13, bytes=00000000080a06313331373531
--
DEBUG 2017-09-26 22:22:41,372 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] HEADERS: streamId=825, headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
--
DEBUG 2017-09-26 22:22:41,372 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] DATA: streamId=825, padding=0, endStream=false, length=50, bytes=000000002d08cff58cfdeb2b1a2438376263343334612d626533612d346436612d383239382d613039343738313963666638
--
DEBUG 2017-09-26 22:22:41,372 grpc-default-worker-ELG-3-18 (i.g.n.NettyClientHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0x670e3d3c, L:/CLIENT_IP:56240 - R:SERVER_DOMAIN/SERVER_IP:50050] HEADERS: streamId=825, headers=GrpcHttp2ResponseHeaders[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
```

BUT timestamp of call is after exception was thrown.
Logs from server(server is -1 hour from client) for streamId=821:
```
DEBUG 2017-09-26 21:22:41,223 grpc-default-worker-ELG-4-20 (i.g.n.NettyServerHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0xc59e81bf, L:/SERVER_IP:50050 - R:/CLIENT_IP:56240] HEADERS: streamId=821, headers=GrpcHttp2RequestHeaders[:path: /base.rpc.profile.mm.MatchmakingInfoService/Info, :authority: SERVER_DOMAIN:50050, :method: POST, :scheme: https, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.5.0, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
--
DEBUG 2017-09-26 21:22:41,223 grpc-default-worker-ELG-4-20 (i.g.n.NettyServerHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0xc59e81bf, L:/SERVER_IP:50050 - R:/CLIENT_IP:56240] DATA: streamId=821, padding=0, endStream=true, length=51, bytes=000000002e0a06313331373531122438376263343334612d626533612d346436612d383239382d613039343738313963666638
--
DEBUG 2017-09-26 21:22:41,228 grpc-default-worker-ELG-4-20 (i.g.n.NettyServerHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0xc59e81bf, L:/SERVER_IP:50050 - R:/CLIENT_IP:56240] HEADERS: streamId=821, headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=false
--
DEBUG 2017-09-26 21:22:41,228 grpc-default-worker-ELG-4-20 (i.g.n.NettyServerHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0xc59e81bf, L:/SERVER_IP:50050 - R:/CLIENT_IP:56240] DATA: streamId=821, padding=0, endStream=false, length=13, bytes=00000000081802200128023001
--
DEBUG 2017-09-26 21:22:41,228 grpc-default-worker-ELG-4-20 (i.g.n.NettyServerHandler:71 ) [] -
----------------OUTBOUND--------------------
[id: 0xc59e81bf, L:/SERVER_IP:50050 - R:/CLIENT_IP:56240] HEADERS: streamId=821, headers=GrpcHttp2OutboundHeaders[grpc-status: 0], streamDependency=0, weight=16, exclusive=false, padding=0, endStream=true
--
DEBUG 2017-09-26 21:22:41,283 grpc-default-worker-ELG-4-20 (i.g.n.NettyServerHandler:71 ) [] -
----------------INBOUND--------------------
[id: 0xc59e81bf, L:/SERVER_IP:50050 - R:/CLIENT_IP:56240] RST_STREAM: streamId=821, errorCode=8
```
So, two questions:
1. Why is RST_STREAM(CANCEL) was triggered after response is received?
2. Why cancelled was **next after RST_STREAM** call?

This situation was under load like one task per minute(so no load at all).

**Comment by crazyproger** [comment]
Today I've updated to 1.6.1(on both sides). After some minutes from start two CANCELLED was thrown. In this case exception source and rpc-all from logs are matched, so exception logs will be omitted.
First exception case client log:
```
DEBUG 2017-09-27 15:12:20,438 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND PRIORITY: streamId=45 headers=GrpcHttp2OutboundHeaders[:authority: SERVER_DOMAIN:50050, :path: /base.rpc.profile.mm.OnlineInfoService/Info, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.6.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
DEBUG 2017-09-27 15:12:20,441 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND PRIORITY: streamId=45 padding=0 endStream=true length=11 bytes=00000000060a0434393531
DEBUG 2017-09-27 15:12:20,442 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND RST_STREAM: streamId=45 errorCode=8
DEBUG 2017-09-27 15:12:20,498 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] INBOUND RST_STREAM: streamId=45 errorCode=8
DEBUG 2017-09-27 15:12:20,498 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] INBOUND RST_STREAM: streamId=45 errorCode=8
```
Client send RST_STREAM after 1 millisecond from *endStream* - this is unexpected.
Server logs for this case(-1 hour):
```
DEBUG 2017-09-27 14:12:20,468 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND PRIORITY: streamId=45 headers=GrpcHttp2RequestHeaders[:path: /base.rpc.profile.mm.OnlineInfoService/Info, :authority: SERVER_DOMAIN:50050, :method: POST, :scheme: https, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.6.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
DEBUG 2017-09-27 14:12:20,469 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND PRIORITY: streamId=45 padding=0 endStream=true length=11 bytes=00000000060a0434393531
DEBUG 2017-09-27 14:12:20,469 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND RST_STREAM: streamId=45 errorCode=8
DEBUG 2017-09-27 14:12:20,471 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] OUTBOUND RST_STREAM: streamId=45 errorCode=8
DEBUG 2017-09-27 14:12:20,473 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] OUTBOUND RST_STREAM: streamId=45 errorCode=8
```

Second exception case client log:
```
DEBUG 2017-09-27 15:12:27,994 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND PRIORITY: streamId=57 headers=GrpcHttp2OutboundHeaders[:authority: SERVER_DOMAIN:50050, :path: /base.rpc.profile.mm.OnlineInfoService/Info, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.6.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
DEBUG 2017-09-27 15:12:27,994 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND PRIORITY: streamId=57 padding=0 endStream=true length=11 bytes=00000000060a0434393531
DEBUG 2017-09-27 15:12:28,019 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND RST_STREAM: streamId=57 errorCode=8
DEBUG 2017-09-27 15:12:28,048 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] INBOUND PRIORITY: streamId=57 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
DEBUG 2017-09-27 15:12:28,050 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND RST_STREAM: streamId=57 errorCode=5
DEBUG 2017-09-27 15:12:28,050 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] INBOUND PRIORITY: streamId=57 padding=0 endStream=false length=50 bytes=000000002d08f187fc99ec2b1a2464383835323737652d333534622d343366372d623331612d663139373839623639366137
DEBUG 2017-09-27 15:12:28,051 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND RST_STREAM: streamId=57 errorCode=5
DEBUG 2017-09-27 15:12:28,051 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] INBOUND PRIORITY: streamId=57 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
DEBUG 2017-09-27 15:12:28,052 grpc-default-worker-ELG-3-19 (i.g.n.NettyClientHandler:86 ) [] - [id: 0x126f64a1, L:/CLIENT_IP:41906 - R:SERVER_DOMAIN/SERVER_IP:50050] OUTBOUND RST_STREAM: streamId=57 errorCode=5
```
In this case there is 25 millis from *endStream* to *RST_STREAM*.
Server log:
```
DEBUG 2017-09-27 14:12:28,021 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND PRIORITY: streamId=57 headers=GrpcHttp2RequestHeaders[:path: /base.rpc.profile.mm.OnlineInfoService/Info, :authority: SERVER_DOMAIN:50050, :method: POST, :scheme: https, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.6.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
DEBUG 2017-09-27 14:12:28,022 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND PRIORITY: streamId=57 padding=0 endStream=true length=11 bytes=00000000060a0434393531
DEBUG 2017-09-27 14:12:28,023 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] OUTBOUND PRIORITY: streamId=57 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
DEBUG 2017-09-27 14:12:28,023 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] OUTBOUND PRIORITY: streamId=57 padding=0 endStream=false length=50 bytes=000000002d08f187fc99ec2b1a2464383835323737652d333534622d343366372d623331612d663139373839623639366137
DEBUG 2017-09-27 14:12:28,023 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] OUTBOUND PRIORITY: streamId=57 headers=GrpcHttp2OutboundHeaders[grpc-status: 0] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
DEBUG 2017-09-27 14:12:28,046 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND RST_STREAM: streamId=57 errorCode=8
DEBUG 2017-09-27 14:12:28,077 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND RST_STREAM: streamId=57 errorCode=5
DEBUG 2017-09-27 14:12:28,078 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND RST_STREAM: streamId=57 errorCode=5
DEBUG 2017-09-27 14:12:28,079 grpc-default-worker-ELG-4-3 (i.g.n.NettyServerHandler:86 ) [] - [id: 0xed23eff5, L:/SERVER_IP:50050 - R:/CLIENT_IP:41906] INBOUND RST_STREAM: streamId=57 errorCode=5
```

If necessary I can attach full log file which contains all another calls which was before or after.

**Comment by ejona86** [comment]
I agree things look a bit weird. Some of this looks believable and just doesn't matter much in practice.

> One maybe important thing: thread in which rpc-client work - is a GRPC-server rpc processing thread(so client is also a GRPC-server but I think it should not be relevant).

Do you do the second RPC after the service has already responded? You may be getting bit by io.grpc.Context. When an inbound RPC is completed the Context is cancelled, so any RPCs made in callback threads that are in progress or done after that point will fail. You can use Context.fork() if you need to do background work.

Note also that Context allows propagation of cancellations from inbound RPCs to outbound RPCs. If a service is servicing "RPC1" by doing "RPC2" and "RPC1" is cancelled by the client, the cancellation signal will propagate to "RPC2" and the service processing "RPC2".

**Comment by crazyproger** [comment]
Hmm, sounds like propagation is my case.
Rpc calls is looks like:
```
Task processing call {
   RPC call 1(MatchmakingInfoService)
   RPC call 2(OnlineInfoService)
}
``` 
In most cases all is going fine, but outer RPC cancellation can occur in some times.
@ejona86 Thank you for clarifying, could you point me to some info about cancellation propagation from Server context to Client?

**Comment by crazyproger** [comment]
I will close issue, if smth unexpected will be finded - I'll reopen it.
