### ISSUE TITLE
ManagedChannelImplTest.orphanedChannelsAreLogged is flaky

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#3534]
https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC-Java-PR-Windows/4294/console
 
> io.grpc.internal.ManagedChannelImplTest > orphanedChannelsAreLogged FAILED
    java.lang.AssertionError: Not true that <2> is at most <0>
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
        at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
        at com.google.common.truth.Subject.failComparingToStrings(Subject.java:295)
        at com.google.common.truth.Subject.fail(Subject.java:272)
        at com.google.common.truth.ComparableSubject.isAtMost(ComparableSubject.java:104)
        at io.grpc.internal.ManagedChannelImplTest.orphanedChannelsAreLogged(ManagedChannelImplTest.java:1425)

Insufficient attempt at a fix and some comments in https://github.com/grpc/grpc-java/pull/3490

**Comment by ericgribkoff** [comment]
Seen at https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4367/

> java.lang.AssertionError: Not true that <2> is at most <0>
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:24)
	at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:20)
	at com.google.common.truth.Subject.failComparingToStrings(Subject.java:295)
	at com.google.common.truth.Subject.fail(Subject.java:272)
	at com.google.common.truth.ComparableSubject.isAtMost(ComparableSubject.java:104)
	at io.grpc.internal.ManagedChannelImplTest.orphanedChannelsAreLogged(ManagedChannelImplTest.java:1425)

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4413/console

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4414/console (1.7 branch)

**Comment by ejona86** [comment]
https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4415/console (1.7 branch)

**Comment by ericgribkoff** [comment]
No longer seen - I think the root cause was fixed in https://github.com/grpc/grpc-java/pull/4093
