### ISSUE TITLE
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream

### ISSUE THREAD

**Issue by hzariv** [grpc/grpc-java#3548]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
gRPC Server
<gRPC.version>1.5.0</gRPC.version>
<netty.version>4.1.12.Final</netty.version>

gRPC Client
<gRPC.version>1.6.0</gRPC.version>
<netty.version>4.1.8.Final</netty.version>

### What JVM are you using (`java -version`)?
java 8

We are seeing a lot of warning messages from Netty shown below on gRPC server side. Could someone shed some light on why we are seeing these warnings?

```
2017-10-04 19:21:08,485 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5

2017-10-04 19:21:08,488 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5

2017-10-04 19:21:08,489 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5

2017-10-04 19:53:07,139 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 145

2017-10-04 19:53:07,169 WARN [ForkJoinPool-1-worker-2]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 145

2017-10-05 07:38:08,033 WARN [ForkJoinPool-1-worker-1]io.grpc.netty.NettyServerHandler[423] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 123
```

**Comment by hzariv** [comment]
Here is full stacktrace for this warning:

2017-10-05 13:52:41,268 [31mWARN [0;39m [ForkJoinPool-1-worker-3] [32mi.g.n.NettyServerHandler[0;39m[423] - Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 59
at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:524) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:185) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160) ~[netty-all-4.1.12.Final.jar!/:4.1.12.Final]...```

**Comment by carl-mastrangelo** [comment]
any chance you could try with a more recent version?  1.6.1 is the latest, and next week it will be 1.7.0

**Comment by hzariv** [comment]
@carl-mastrangelo  sorry I didn't have the right version of gRPC info when I filed. I have update the version info for grpc and netty on client and server.

**Comment by hzariv** [comment]
Upon further investigation, this is a cancel stream error most likely because of deadline being set at the client. In rare cases, it seems the server reacts to this deadline before the client does and that results in this behavior.

**Comment by carl-mastrangelo** [comment]
This still shouldn't happen though.

**Comment by dapengzhang0** [comment]
Same issue was observed by https://groups.google.com/forum/#!topic/grpc-io/gaFmBDOmYE0

**Comment by dapengzhang0** [comment]
Also the same stacktrace seen here
grpc/grpc#9083

**Comment by ejona86** [comment]
This seems like what we experienced in the performance testing environment, but then disappeared: https://github.com/grpc/grpc-java/issues/2372#issuecomment-258216611

**Comment by ejona86** [comment]
A fix for this problem is being worked on in netty/netty#8028

**Comment by Randgalt** [comment]
Note: looks like this was moved to a new Netty issue and is fixed for the next release of Netty: https://github.com/netty/netty/pull/9402

**Comment by PSNRigner** [comment]
This ticket can be closed, it got fixed in Netty 4.1.44.Final and grpc-java is now using 4.1.48.Final.

**Comment by ejona86** [comment]
Ah, yes. This was fixed by netty/netty#9798 which was part of 4.1.44.Final.

**Comment by lezwon** [comment]
Hi guys, I receive this error when I try to send multiple images via GRPC. I basically want to do batch inference using torchserve. I try to send multiple images from the python client using this code:

```python
imgs = [cv2.imencode('.jpg', im)[1] for im in images]
pickled_images = pickle.dumps(imgs, 0)
input_data = {'data': pickled_images}
response = stub.Predictions(
    inference_pb2.PredictionsRequest(model_name=model_name, input=input_data))
```

This ends up receiving the error: `Received RST_STREAM with error code 8`
Server shows: 
```
Mar 12, 2021 8:07:51 AM io.grpc.netty.shaded.io.grpc.netty.NettyServerHandler onStreamError
WARNING: Stream Error
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 1
```

Any help would be appreciated. :)

**Comment by dapengzhang0** [comment]
@lezwon Can you try grpc client of other languages? This can tell whether it's a netty problem or it's the server/proxy's problem.
