### ISSUE TITLE
Many java cloud_to_cloud and cloud_to_prod interop tests failling: " No ServerStreamTracer found"

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-java#3562]
```
2017-10-09 16:53:03,682 START: cloud_to_cloud:node:csharpcoreclr_server:unimplemented_method
2017-10-09 16:53:03,686 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar
Running test status_code_and_message
Exception in thread "main" java.lang.AssertionError: No ServerStreamTracer found
	at io.grpc.testing.integration.AbstractInteropTest.assertServerMetrics(AbstractInteropTest.java:1828)
	at io.grpc.testing.integration.AbstractInteropTest.assertMetrics(AbstractInteropTest.java:1709)
	at io.grpc.testing.integration.AbstractInteropTest.assertMetrics(AbstractInteropTest.java:1717)
	at io.grpc.testing.integration.AbstractInteropTest.statusCodeAndMessage(AbstractInteropTest.java:1395)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:282)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:189)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:66)

2017-10-09 16:53:03,686 TIMEOUT: cloud_to_cloud:java:java_server:status_code_and_message [pid=30665, time=180.4sec]
```

cloud_to_cloud:
https://sponge.corp.google.com/target?id=23de9377-477a-4cf9-876c-20df54eb5e83&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

cloud_to_prod:
https://sponge.corp.google.com/target?id=3fc281f5-0428-4d03-bc10-8fb9b3a7d035&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment]
Thanks for the fix!

**Comment by zhangkun83** [comment]
It's still failing with a different error:
```
java.lang.AssertionError: expected:<314167> but was:<314169>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.grpc.testing.integration.AbstractInteropTest.checkTracerMetrics(AbstractInteropTest.java:1881)
	at io.grpc.testing.integration.AbstractInteropTest.assertClientMetrics(AbstractInteropTest.java:1740)
	at io.grpc.testing.integration.AbstractInteropTest.assertMetrics(AbstractInteropTest.java:1712)
	at io.grpc.testing.integration.AbstractInteropTest.largeUnary(AbstractInteropTest.java:355)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:211)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:190)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:67)
```


https://sponge.corp.google.com/invocation?id=afae434c-7966-4954-a63e-190c78ba572f&searchFor=
https://sponge.corp.google.com/invocation?id=6f91d461-b5a1-4567-894c-77dc0e9ac7b8&searchFor=

**Comment by zhangkun83** [comment]
Only Java-Go test is broken. Java-Java and Java-C++ are fine.
Talked with @dfawley. Looks like Go is using proto2 in interop test.
Since Java and C++ are using proto3, and according to Protobuf team, proto2 and proto3 wire format are not identical, the 2-byte difference is probably because of it.
Switching Go interop test to proto3 should be the right thing to do. I am going to disable the metrics checking in the Java client for now, and file an issue to grpc-go.
