### ISSUE TITLE
InProcessTest is flaky

### ISSUE THREAD

**Issue by zhangkun83** [grpc/grpc-java#3571]
https://travis-ci.org/grpc/grpc-java/jobs/286166891
```
:grpc-interop-testing:checkstyleTest
:grpc-interop-testing:test
io.grpc.testing.integration.InProcessTest > statusCodeAndMessage FAILED
    java.lang.AssertionError: expected:<UNKNOWN> but was:<CANCELLED>
```

Also on: https://grpc-testing.appspot.com/job/gRPC-Java-PR-Windows/4421/console
```
:grpc-interop-testing:test
io.grpc.testing.integration.InProcessTest > unimplementedService FAILED
    java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<CANCELLED>
```

**Comment by ejona86** [comment]
Seen at https://travis-ci.org/grpc/grpc-java/jobs/290593867
```
io.grpc.testing.integration.InProcessTest > unimplementedService FAILED
 java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<CANCELLED>
```

This is pretty strange... Could it be related to the upgrade of JUnit in 5e36a8deb51d008f699a70de8e375e535c642cce?

**Comment by dapengzhang0** [comment]
To reproduce the issue, add a sleep in `InProcessTransport.InProcessStream.InProcessServerStream#close(Status status, Metadata trailers)`:

```java
      @Override
      public void close(Status status, Metadata trailers) {
        Status clientStatus = stripCause(status);
        synchronized (this) {
          if (closed) {
            return;
          }
          if (clientReceiveQueue.isEmpty()) {
            closed = true;
            clientStream.statsTraceCtx.streamClosed(clientStatus);
            clientStreamListener.closed(clientStatus, trailers);
          } else {
            clientNotifyStatus = clientStatus;
            clientNotifyTrailers = trailers;
          }
        }

        // Add a sleep here.
        try {
          Thread.sleep(2000);
        } catch (InterruptedException e) {
          // ignore
        }

        clientStream.serverClosed(Status.OK, status);
        streamClosed();
      }
```
Then run the test:
```
./gradlew :grpc-interop-testing:test -PskipCodegen=true  --tests io.grpc.testing.integration.InProcessTest.unimplementedService
```

The test failure is 
```
io.grpc.testing.integration.InProcessTest > unimplementedService FAILED
 java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<CANCELLED>
```

```
java.lang.AssertionError: expected:<UNIMPLEMENTED> but was:<CANCELLED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.grpc.testing.integration.AbstractInteropTest.assertServerStatsTrace(AbstractInteropTest.java:1827)
	at io.grpc.testing.integration.AbstractInteropTest.assertStatsTrace(AbstractInteropTest.java:1718)
	at io.grpc.testing.integration.AbstractInteropTest.assertStatsTrace(AbstractInteropTest.java:1726)
	at io.grpc.testing.integration.AbstractInteropTest.unimplementedService(AbstractInteropTest.java:1449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ejona86** [comment]
https://travis-ci.org/grpc/grpc-java/jobs/291671753
