### ISSUE TITLE
Stress test client hangs

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc-java#3578]
With the inclusion of `io.opencensus:opencensus-impl:0.7.0` as a runtime dependency (added to our interop test clients in https://github.com/grpc/grpc-java/commit/8edead08510ccd382087f114fb4833b8170698d5#diff-dbbdfba18c8958c51b031ef112a6fa7cR29), our stress test client hangs.

### Run interop server:

`build/install/grpc-interop-testing/bin/test-server`

### Run stress client:

`build/install/grpc-interop-testing/bin/stresstest-client --server_addresses=localhost:8080 --server_host_override=foo.test.google.fr --use_tls=true --use_test_ca=true --test_cases=empty_unary:100 --metrics_port=0 --test_duration_secs=1 --num_channels_per_server=1 --num_stubs_per_channel=1`

The client will finish its 1 second of testing and successfully terminate the channel, its metrics server, and its own threadpool, but the client process does not terminate; it just hangs. jstack output includes the following:

```
"ExportComponent.ServiceExporterThread" #13 daemon prio=5 os_prio=31 tid=0x00007fbc0c8f2000 nid=0x5803 in Object.wait() [0x0000700004730000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076eb28190> (a java.lang.Object)
	at io.opencensus.implcore.trace.export.SpanExporterImpl$WorkerThread.run(SpanExporterImpl.java:171)
	- locked <0x000000076eb28190> (a java.lang.Object)
```

@zhangkun83 I looked at the code in https://github.com/grpc/grpc-java/pull/3517 and didn't see any obvious cause for this issue. Do you have some insight into whether this is an error in our stress client, a problem in gRPC, or a bug within the Census library?

**Comment by zhangkun83** [comment]
That thread is daemon, thus not blocking the termination. The culprit is a different thread, which is not daemon:
```
"pool-1-thread-1" #12 prio=5 os_prio=0 tid=0x00007f9530441800 nid=0x14a17 runnable [0x00007f94fdc7f000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at (C/C++) 0x00007f953808d9f2 (Unknown Source)
	at (C/C++) 0x00007f9537166f52 (Unknown Source)
	at (C/C++) 0x00007f95376a446d (Unknown Source)
	at (C/C++) 0x00007f953717cdee (Unknown Source)
	at (C/C++) 0x00007f95371ff091 (Unknown Source)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.lmax.disruptor.SleepingWaitStrategy.applyWaitMethod(SleepingWaitStrategy.java:82)
	at com.lmax.disruptor.SleepingWaitStrategy.waitFor(SleepingWaitStrategy.java:55)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:124)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Turns out it's also created by Census in [io.opencensus.impl.internal.DisruptorEventQueue.java](https://github.com/census-instrumentation/opencensus-java/blob/v0.7.0/impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java#L144)
