### ISSUE TITLE
c++ server and java client communications issue

### ISSUE THREAD

**Issue by yudov-maksim** [grpc/grpc-java#363]
Hello.
I try write gRPC communication with java client and c++ server on linux. 
But i have exception (below) in client when it runs RPC procedure.
Logs shows that server processed request, sended answer and continues its work. 
For test i wrote same client on c++ and same server on java. All communication versions works. And only client(java) with server(c++) failed.
I hope you can help me. Thanks.

Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: io.grpc.Status$OperationRuntimeException: INTERNAL: 
Headers(path=null,authority=null,metadata={grpc-status=[0]})
DATA-----------------------------

     at io.grpc.stub.Calls.getUnchecked(Calls.java:117)
     at io.grpc.stub.Calls.blockingUnaryCall(Calls.java:129)
     at rpc_test.ManagerServiceGrpc$ManagerServiceBlockingStub.doGet(ManagerServiceGrpc.java:274)
     at rpc_test.Client.testRPC(Client.java:53)
     at rpc_test.Client.main(Client.java:64)
Caused by: io.grpc.Status$OperationRuntimeException: INTERNAL: 
Headers(path=null,authority=null,metadata={grpc-status=[0]})
DATA-----------------------------

     at io.grpc.Status.asRuntimeException(Status.java:428)
     at io.grpc.stub.Calls$UnaryStreamToFuture.onClose(Calls.java:324)
     at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$3.run(ChannelImpl.java:373)
     at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     at java.lang.Thread.run(Thread.java:745)

**Comment by yang-g** [comment]
This is the issue shows up in the interop test. Eric filed issue #359 to improve the error message to help solve the real problem.

**Comment by yudov-maksim** [comment]
Ok. I will wait a solving.
Thank you.

**Comment by piccolodream** [comment]
We are having the same issue here trying to implement a bi-directional communication between a Java program and a c++ program.  The communication from Java to c++ only works when the message field is empty.

A fix will be highly appreciated. Thanks again for this cool library.

**Comment by GrgrLmml** [comment]
The  problem disappears (at least for me on OSX) when updating to master on both grpc and grpc-java.

**Comment by ejona86** [comment]
We've seen the problem go away on integration tests as well. I'm not fully certain what change caused it to be introduced or fixed, but it seems resolved at this point.
