### ISSUE TITLE
java.lang.NoClassDefFoundError: io/grpc/BindableService for Java app.

### ISSUE THREAD

**Issue by wingoku** [grpc/grpc-java#3702]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.7.0

### What JVM are you using (`java -version`)?
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### What did you do?
If possible, provide a recipe for reproducing the error.
Running the Java app module in Android Studio 3.0. Upon running the java app, it throws the following error:

```
"C:\Program Files\Android\Android Studio\jre\bin\java" "-javaagent:C:\Program Files\Android\Android Studio\lib\idea_rt.jar=56978:C:\Program Files\Android\Android Studio\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\Android Studio\jre\jre\lib\charsets.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\cldrdata.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\dnsns.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\jaccess.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\localedata.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\nashorn.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunec.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunmscapi.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\zipfs.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\jce.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\jsse.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\management-agent.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\resources.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\rt.jar;C:\Users\Umer\AndroidStudioProjects\android\GRPC_Android\simpleserver\build\classes\java\main" com.wingoku.grpc.MyGrpcServer
java.lang.NoClassDefFoundError: io/grpc/BindableService
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.grpc.BindableService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1
```
Since I don't really understand why this problem is occuring, I've been different methods to get the project working but it keeps throwing the same error. Things I have tried so far are, changing the grpc dependency versions. Setting `option 'enable_deprecated=false'` to true as well. Cleaning the project to regenerate the generated sources.

**Java App build.gradle:**

```
apply plugin: 'java'
apply plugin: 'com.google.protobuf'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        // ASSUMES GRADLE 2.12 OR HIGHER. Use plugin version 0.7.5 with earlier
        // gradle versions
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.2'
    }

}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.4.0"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.7.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {
                // To generate deprecated interfaces and static bindService method,
                // turn the enable_deprecated option to true below:
                option 'enable_deprecated=false'
            }
        }
    }
}

// Inform IDEs like IntelliJ IDEA, Eclipse or NetBeans about the generated code.
sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}

apply plugin: 'idea'

// Allow intellij projects to refer to generated-sources
idea {
    module {
        // The whole build dir is excluded by default, but we need build/generated-sources,
        // which contains the generated proto classes.
        excludeDirs = [file('.gradle')]
        if (buildDir.exists()) {
            excludeDirs += files(buildDir.listFiles())
            excludeDirs -= file("$buildDir/generated")
        }
    }
}
//apply plugin: 'java'

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    

    compile group: 'io.grpc', name: 'grpc-protobuf', version: "1.7.0"
    compile group: 'io.grpc', name: 'grpc-netty', version: "1.7.0"
    compile group: 'io.grpc', name: 'grpc-core', version: "1.7.0"
    compile group: 'io.grpc', name: 'grpc-all', version: "1.7.0"
}
sourceCompatibility = "1.7"
targetCompatibility = "1.7"

```

### What did you expect to see?

The Java app to run on my Windows 10 computer using Android Studi 3.0 IDE. Android Studio is able to install Android app on an Android device (Nexus 7 in this case), but since there is no server, it doesn't have any thing to communicate with.

### What did you see instead?

I got this error upon running the java app

```
"C:\Program Files\Android\Android Studio\jre\bin\java" "-javaagent:C:\Program Files\Android\Android Studio\lib\idea_rt.jar=57063:C:\Program Files\Android\Android Studio\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\Android Studio\jre\jre\lib\charsets.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\cldrdata.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\dnsns.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\jaccess.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\localedata.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\nashorn.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunec.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunmscapi.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\ext\zipfs.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\jce.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\jsse.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\management-agent.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\resources.jar;C:\Program Files\Android\Android Studio\jre\jre\lib\rt.jar;C:\Users\Umer\AndroidStudioProjects\android\GRPC_Android\simpleserver\build\classes\java\main" com.wingoku.grpc.MyGrpcServer
java.lang.NoClassDefFoundError: io/grpc/BindableService
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: io.grpc.BindableService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
Process finished with exit code 1

```

Looking forward to help from you guys. The entire project can found [here](https://github.com/wingoku/GRPC_Android).

**Comment by duelinmarkers** [comment]
I don't know anything about gradle, but the java command line you shared shows the entire classpath, and it doesn't include any grpc jars.

Here's your classpath in a more readable form:
```
C:\Program Files\Android\Android Studio\jre\jre\lib\charsets.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\access-bridge-64.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\cldrdata.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\dnsns.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\jaccess.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\localedata.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\nashorn.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunec.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunjce_provider.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunmscapi.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\sunpkcs11.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\ext\zipfs.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\jce.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\jsse.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\management-agent.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\resources.jar
C:\Program Files\Android\Android Studio\jre\jre\lib\rt.jar
C:\Users\Umer\AndroidStudioProjects\android\GRPC_Android\simpleserver\build\classes\java\main
```

**Comment by kshafiee** [comment]
@ejona86 any reason you closed this Issue? I'm having the exact same issue
@wingoku did you find any solution to this problem? Thx!

**Comment by kshafiee** [comment]
I don't know why, but [this](https://stackoverflow.com/questions/42540531/bindableservice-issue-with-grpc-java) resolved the issue!

**Comment by ejona86** [comment]
I closed it because:
> the java command line you shared shows the entire classpath, and it doesn't include any grpc jars

This wasn't a gradle issue or a grpc issue. It was just being run incorrectly.

**Comment by kshafiee** [comment]
But the guy who opened the issue did not confirm that
"the java command line you shared shows the entire classpath, and it doesn't include any grpc jars" resolved his issue. 

Besides, turns out when I add shadow plugin, `'com.github.jengelman.gradle.plugins:shadow:1.2.4'` , to build.gradle it fixes the issue. So, it could in fact be a gradle issue!

**Comment by ejona86** [comment]
It had been over a month with no response. If the original poster responds and says it didn't work then we could reopen.

> So, it could in fact be a gradle issue!

It's more of a "you're holding is wrong" issue. Gradle produces a JAR but does not include all the dependencies in that JAR. The same is true for Maven and Ant.

Using shadow plugin would work, but you could also use the ["application" plugin](https://docs.gradle.org/current/userguide/application_plugin.html) to create an executable script. We do a more complex version (because we produce multiple binaries) of that in our examples. It really depends on what you want your output to be.
