### ISSUE TITLE
grpc mutual authentication issue

### ISSUE THREAD

**Issue by shank9918** [grpc/grpc-java#3788]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
<grpc.version>1.7.0</grpc.version>
<netty-tcnative.version>2.0.6.Final</netty-tcnative.version>

### What did you expect to see?

To enable ssl mutual authentication

**Actual behavior**

Using PKCS11 as keystore provider and loading certs from HSM.
Client fails during mutual authentication with following error and stacktrace

```
[DEBUG] 2017-11-22 00:34:21.484 [grpc-default-worker-ELG-2-2] ReferenceCountedOpenSslClientContext - request of key failed
javax.net.ssl.SSLException: java.lang.NullPointerException
at io.netty.handler.ssl.OpenSslKeyMaterialManager.keyMaterial(OpenSslKeyMaterialManager.java:121) ~[netty-handler-4.1.16.Final.jar!/:4.1.16.Final]
at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslCertificateRequestedCallback.requested(ReferenceCountedOpenSslClientContext.java:249) [netty-handler-4.1.16.Final.jar!/:4.1.16.Final]
at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[netty-tcnative-boringssl-static-2.0.6.Final.jar!/:2.0.6.Final]
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:482) [netty-handler-4.1.16.Final.jar!/:4.1.16.Final]

at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [netty-transport-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.16.Final.jar!/:4.16.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at io.netty.buffer.Unpooled.wrappedBuffer(Unpooled.java:154) ~[netty-buffer-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.handler.ssl.PemPrivateKey.toPEM(PemPrivateKey.java:62) ~[netty-handler-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.toBIO(ReferenceCountedOpenSslContext.java:771) ~[netty-handler-4.1.16.Final.jar!/:4.1.16.Fal]
```

**Steps to reproduce**

Works with JKS store provider but while using PKCS11 it fails.
While debugging it finds 4 matching aliases but it is not able to respond to the server.

Minimal yet complete reproducer code (or URL to code)

Client code:
```
ManagedChannel channel = null;
try {

channel = NettyChannelBuilder.forAddress(host, port)
		.sslContext(GrpcSslContexts.forClient()
				.keyManager(this.keyManagerFactory)
				.trustManager(this.trustManagerFactory)
				.build())
		.overrideAuthority(this.authority)
		.build();
} catch (SSLException e) {
throw new IllegalStateException("gRPC client cannot be started", e);
}
```

Server Code:
```
Server server = NettyServerBuilder.forPort(Integer.valueOf(environment.getProperty("grpc.port")))
.sslContext(GrpcSslContexts.configure(SslContextBuilder.forServer(sslUtil.keyManagerFactory())
.trustManager(sslUtil.trustManagerFactory()))
.clientAuth(ClientAuth.REQUIRE)
.build())
.addService(grpcServer)
.build();
```

**Comment by ejona86** [comment]
This is being handled upstream in netty/netty#7431
