### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE

### ISSUE THREAD

**Issue by jiandanshihun** [grpc/grpc-java#3854]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
build a connection to go gRPC server, using ver. 1.8.0

I tried to run a Helloworld demo on android platform, but only got exceptions :

 io.grpc.StatusRuntimeException: UNAVAILABLE
 at io.grpc.Status.asRuntimeException(Status.java:526)
 at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
 at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
 at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
 at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
 at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
 at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
 at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
 at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:761)
 Caused by: java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
at java.net.Socket.connect(Socket.java:605)
at java.net.Socket.connect(Socket.java:554)
at java.net.Socket.<init>(Socket.java:431)
at java.net.Socket.<init>(Socket.java:241)
at io.grpc.okhttp.OkHttpClientTransport$1.run(OkHttpClientTransport.java:423)

can anybody give me some advice.
Thank you so much

**Comment by ejona86** [comment]
"Connection timed out." You're having a general networking problem. You're android device may not be able to access the machine running the server.

**Comment by jiandanshihun** [comment]
I tried to ping my server, and there's no problem...I have no idea about that

**Comment by jiandanshihun** [comment]
Got it，caused by the proxy of my phone
