### ISSUE TITLE
Throw StatusRuntimeException in gRPC Proxy

### ISSUE THREAD

**Issue by schulz-m** [grpc/grpc-java#3884]
### What version of gRPC are you using?
1.7.0

### What JVM are you using?
1.8.0_144

### What did you do?
I would like to throw a StatusRunTimeException inside an interceptor, the relevant code piece is:

```java
private class RequestProxy extends ServerCall.Listener<byte[]> {
    private final ClientCall<byte[], ?> clientCall;

    public RequestProxy(ClientCall<byte[], ?> clientCall) {
        this.clientCall = clientCall;
    }

    @Override 
    public void onMessage(byte[] message) {
        clientCall.cancel(null, new StatusRuntimeException(Status.INVALID_ARGUMENT));
    }
}
```

### What did you expect to see?
I expected the same as if I use 
```java
responseObserver.onError(new StatusRuntimeException(Status.INVALID_ARGUMENT))
```
within a gRPC stub, i.e. the client can catch the exception with status and description

### What did you see instead?
Once a message is intercepted, I get an `IllegalStateException` from the `SerializingExecutor`:
```bash
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@2fd60e13
java.lang.IllegalStateException: call was cancelled
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:405)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:52)
	at sila_tools.bridge.utils.GrpcProxy$CallProxy$RequestProxy.onMessage(GrpcProxy.java:96)
	at sila_tools.bridge.utils.GrpcProxy$CallProxy$RequestProxy.onMessage(GrpcProxy.java:46)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:251)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:592)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any recommendations how to tackle this?

**Comment by zpencer** [comment]
Based on the stack trace and the code snippet, it looks cancel was called and then some other code was calling sendMessage after cancel was called. The code triggered a IllegalStateException because sendMessage can not be called after cancel.

**Comment by zpencer** [comment]
We need more information to figure out what's going on. Please reopen if you are still seeing the problem.

**Comment by schulz-m** [comment]
@zpencer You are completely correct with your diagnosis, now I still don't know a solution as I don't understand how `StatusRuntimeException` exactly work under the hood. 

My target is to validate calls in a gRPC proxy according to some pre-defined rules before they reach the original gRPC Server and then throw a custom `StatusRuntimeException` with the same behaviour as using `responseObserver.onError` on the Server side - could you point me in a direction to achieve this?

**Comment by schulz-m** [comment]
The same problem would be with a `ServerInterceptor`, I would basically like to know how to throw well-behaved Errors by invoking the `ServerCall` correctly - I assume ^^
