### ISSUE TITLE
When grpc program is ran using intellij+gradle, will fail to `libnetty-tcnative` resulting in: "OpenSSL is not installed on the system."

### ISSUE THREAD

**Issue by nddipiazza** [grpc/grpc-java#3990]
I have a grpc program that uses OpenSSL netty + netty-tcnative to implement TLS. 

When I run it using the bundled product via command line, works fine.

When I try to run it within IntelliJ+Gradle... it fails to find the `libnetty-tcnative-linux-x86_64.so` leading to 

```
Exception in thread "main" java.lang.IllegalArgumentException: OpenSSL is not installed on the system.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:163)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
```

### What version of gRPC are you using?

grpc: 1.6.1
netty tcnative 2.0.5.Final

### What did you expect to see?

Expected it to be able to find that `so` and thus be able to run with openssl on the gradle/intellij build.

**Comment by nddipiazza** [comment]
Fixed in gRPC 1.9.0 / netty-tcnative-2.0.7.Final
