### ISSUE TITLE
Protocol Buffer Stream testing gRPC for a million messages in java

### ISSUE THREAD

**Issue by romanamunhoz** [grpc/grpc-java#4001]
### What version of gRPC are you using?
1.9.0

I am testing gRPC with a list of a million of items and sending this million of item by an stream.
But when I have sent a big amount of messages I have an exception for memory used, the single messages are short.
There is anyway to solve it?, In netty there are a way to send messages and flush the data. Did I have that opcion in gRPC?

in proto3:
`message MessageValue{
	string sendmessage = 1;
	string user = 2;
	int32 rights = 3;
	enum MSGType{
		ONE = 0;
		TWO = 1;
		THREE = 2;
	}
 	MSGType smessageType = 4;
}`

I have this code on client:

on my test host: "Localhost", ipPort = 7777

using this code:
```
ManagedChannel comunicationChanel = ManagedChannelBuilder.forAddress(host, ipPort)
                .enableFullStreamDecompression().compressorRegistry(CompressorRegistry.getDefaultInstance())
                .decompressorRegistry(DecompressorRegistry.getDefaultInstance()).usePlaintext(true)
                .maxInboundMessageSize(200888896).build();
ListMessageSRVStub asyncStub = ListMessageSRVGrpc.newStub(comunicationChanel);
List<MessageValue> millionMessages = new ArrayList<MessageValue>();
        for (long i = 0l; i < 1000000; i++) {
            millionMessages.add(MessageValue.newBuilder().build());
        }

long before = System.currentTimeMillis();
        StreamObserver<MessageValue> requestObserver = asyncStub.recievetonm(responseObserverTonMessages);
        long i = 0;
        for (MessageValue messageValue : millionMessages) {
            requestObserver.onNext(messageValue);
            i++;
            if (i % 50000 == 0) {
                LOG.info("Sended: " + i);
            }
        }
        requestObserver.onCompleted();
        long total = System.currentTimeMillis() - before;
        LOG.info("Time = " + total);

```
I have this exception

```
Exception in thread "main" io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1879048487, max: 1894252544)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
    at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:121)
    at io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51)
    at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:226)
    at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:167)
    at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:140)
    at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:52)
    at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:438)
    at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:52)
    at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:52)
    at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:320)
    at com.oesia.grpgtest.server.TestClient.tonsofMSG(TestClient.java:130)
    at com.oesia.grpgtest.server.TestClient.main(TestClient.java:146)
```

**Comment by ejona86** [comment]
You need to observe outbound flow control via isReady/onReady. Take a look at the manualflowcontrol example, although note you don't have to deal with request/disableAutoInboundFlowControl.

**Comment by romanamunhoz** [comment]
Lots of thanks.
I solve it creating this class:
```
class OwnClientResponseObserver implements ClientResponseObserver<MessageValue, MessageValue> {

		private ClientCallStreamObserver<MessageValue> requestStream;
		private CountDownLatch countDownLatch;
		Iterator<MessageValue> iterator;

		public OwnClientResponseObserver(CountDownLatch countDownLatch, final Iterator<MessageValue> iterator) {
			this.countDownLatch = countDownLatch;
			this.iterator = iterator;
		}

		@Override
		public void onNext(MessageValue value) {
			LOG.info(value.toString());

		}

		@Override
		public void onError(Throwable t) {
			LOG.log(Level.SEVERE, "An savage error apears", t);

		}

		@Override
		public void onCompleted() {
			LOG.info("Finalized!!!");

		}

		@Override
		public void beforeStart(ClientCallStreamObserver<MessageValue> requestStream) {
			this.requestStream = requestStream;
			this.requestStream.disableAutoInboundFlowControl();

			this.requestStream.setOnReadyHandler(new Runnable() {
				@Override
				public void run() {

					long i = 1L;
					while (requestStream.isReady()) {
						if (iterator.hasNext()) {
							requestStream.onNext(iterator.next());
							if (i % 1000 == 0) {
								LOG.info("En mi ronda voy por el" + i);
							}
							i++;
						} else {
							requestStream.onCompleted();
							countDownLatch.countDown();
						}
					}

				}
			});

		}
```
