### ISSUE TITLE
Getting grpc exception `java.lang.NullPointerException: runnable is null` 

### ISSUE THREAD

**Issue by nddipiazza** [grpc/grpc-java#4077]
### What version of gRPC are you using?

1.8.0

### What did you expect to see?

We have an app with dozens of bi-directional grpc streams.

When cancelling one of our jobs (but leaving the bi-directional streams open), we sometimes see:

```
java.lang.NullPointerException: runnable is null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at io.grpc.internal.ChannelExecutor.executeLater(ChannelExecutor.java:86)
	at io.grpc.internal.ManagedChannelImpl$3.run(ManagedChannelImpl.java:347)
	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

We aren't sure what exactly is causing it. 

Perhaps an executor service is getting shutdown without proper cleanup. 

Or perhaps a channel's bidirectional activity is being interrupted due to our attempt to cancel the work being done. 

# Expected

Is it possible for grpc-java to handle this NPE better and provide a cause of issue?

**Comment by zpencer** [comment]
I think https://github.com/grpc/grpc-java/commit/9ed84258aa3ead42747ce87fa5a7b428bda72626 eliminates this problem, I'll look into back porting.

**Comment by ejona86** [comment]
If we think "add a final local variable" would fix it, let's not backport a 300+ line change.

**Comment by zpencer** [comment]
Closing because https://github.com/grpc/grpc-java/commit/9ed84258aa3ead42747ce87fa5a7b428bda72626 fixes this in master, the backport fixes will be the simpler solution described above.
