### ISSUE TITLE
Getting random "io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked" when stress testing

### ISSUE THREAD

**Issue by nddipiazza** [grpc/grpc-java#4102]
My team has the following setup, where we have multiple Client nodes connecting to Multiple Server nodes with a channel from client to server of each node, where each channel comprises of multiple persistent streams left open for the lifetime of the process:

https://lh3.googleusercontent.com/-w4zGuLUg7vg/WodG7p2mMKI/AAAAAAAAALg/Wz5L145PE_YRVx9qR8xrAPF9uvw9HQudgCLcBGAs/s1600/Selection_021.bmp

When stress testing the system, we see a *random* sudden shutdown of all the bi-directional streams:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[client-support-4.0.0-SNAPSHOT-shadow.jar:?]
     at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418) [grpc-stub-1.8.0.jar:1.8.0]
       at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
      at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
       at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
      at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
 at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
  at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
      at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
 at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
   at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2018-02-16T14:15:41,314 - ERROR - [grpc-default-executor-190:com.lucidworks.fusion.service.connector.ConnectorServerStreamObserver:service.connector.ConnectorServerStreamObserver@298] - {} - Plugin connection error / disconnected
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
     at io.grpc.Status.asRuntimeException(Status.java:517) ~[client-support-4.0.0-SNAPSHOT-shadow.jar:?]
     at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.8.0.jar:1.8.0]
   at com.lucidworks.fusion.grpc.interceptors.BroadcastingInterceptor$1.onCancel(BroadcastingInterceptor.java:63) [classes/:?]
     at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:38) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
       at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
     at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
  at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:281) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:679) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
   at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
2018-02-16T14:15:41,314 - ERROR - [grpc-default-executor-190:com.lucidworks.fusion.service.connector.controller.endpoints.ConnectEndpoint:controller.endpoints.ConnectEndpoint@49] - {} - connect() error: Received error from plugin: com.lucidworks.fusion.service.connector.ConnectorServerStreamObserver@596aba80
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
     at io.grpc.Status.asRuntimeException(Status.java:517) ~[client-support-4.0.0-SNAPSHOT-shadow.jar:?]
     at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272) [grpc-stub-1.8.0.jar:1.8.0]
   at com.lucidworks.fusion.grpc.interceptors.BroadcastingInterceptor$1.onCancel(BroadcastingInterceptor.java:63) [classes/:?]
     at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:38) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
       at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
     at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
  at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:281) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:679) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
       at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
   at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [client-support-4.0.0-SNAPSHOT-shadow.jar:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

We then have to reconnect each channel + reestablish the streams in order to continue.

This only happens when stress testing. Does not appear to happen in typical lower load situations.

To our knowledge, we are *not* shutting down the channels at any point. they need to remain open for the program to live happily. 

But something is shutting them down somehow. 

What are common ways to troubleshoot this behavior? 

Is there some sort of timeout that we are victim of causing these sudden shutdowns?

**Comment by ejona86** [comment]
"Channel shutdownNow invoked": the RPC was cancelled because someone called `ManagedChannel.shutdownNow()`. This is exactly what you'd expect when calling `shutdownNow()`. The only way source of this string in grpc-java `shutdownNow()`. Maybe your server sees that status when contacting another backend and is propagating the status its client?

"CANCELLED: cancelled before receiving half close" The RPC was cancelled. This can be normal, especially in the presence of deadlines. If you aren't using cancellation/deadline or if you don't expect connections to die, then there could be a problem

**Comment by nddipiazza** [comment]
That's the same thing I said to another member of my team. I figured for sure we are calling `shutdownNow` on accident somewhere causing this. I will use debugger to confirm this is/isnot the case.

> Maybe your server sees that status when contacting another backend and is propagating the status its client?

Interesting idea I will test that theory as well. 

Bottom line I think if I put a breakpoint inside this method I might get some valuable insight.

**Comment by nddipiazza** [comment]
found this cranking up the netty logging:
`2018-02-28T16:17:18,944 - DEBUG - [grpc-default-worker-ELG-3-22:io.grpc.netty.NettyClientHandler:grpc.netty.NettyClientHandler@339] - {} - Network channel being closed by the application.`
somewhere somehow we must be calling shutdown now. still haven't proved it with a breakpoint yet.

**Comment by ejona86** [comment]
@nddipiazza, I'm not sure I would trust that debug message. It looks suspect (as in it claims more than is guaranteed; I've seen netty call the close() method by itself).

**Comment by nddipiazza** [comment]
This one was our code doing scheduled task that was watching for services being unregistered and automatically calling shutdown on the channel. Problem was, the service wasn't down so that part of the check was a bug. And bam there's your shutdownNow interrupting the work. not a grpc-java issue.
