### ISSUE TITLE
How to write code when network is unreachable? 

### ISSUE THREAD

**Issue by dingrui37** [grpc/grpc-java#4188]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.8.0

### What did you expect to see?
I wirte a bi-directional rpc,  when the client try to connect to server，but the server is not ready， it will
give an exception ` io.grpc.StatusRuntimeException: UNAVAILABLE` 
```
          StreamObserver<TelemetryStreamRequest> requestStreamObserver =
                  asyncStub.report(new StreamObserver<TelemetryStreamResponse>() {
                      @Override
                      public void onNext(TelemetryStreamResponse telemetryStreamResponse) {...}
 
                      @Override
                      public void onError(Throwable throwable) {
                       ////io.grpc.StatusRuntimeException: UNAVAILABLE
                      }
 
                      @Override
                      public void onCompleted() {...}
                  });
```
After a few seconds, the server is ready, and the tcp connection is established finally.
When calling `requestStreamObserver.onNext`, there is no exception, **but no data transfer**, **I want to know why?** Do I need to get another **requestStreamObserver** and then call `requestStreamObserver.onNext`?

protobuf:
```
 service Telemetry {
      rpc report(stream TelemetryStreamRequest) returns (TelemetryStreamResponse) {};
 }
```

```
opendaylight-user@root>io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:418)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:50051
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:633)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        ... 1 more
Caused by: java.net.ConnectException: Connection refused
        ... 11 more
log:d
```

**Comment by ejona86** [comment]
A bidi stream is "done"/"dead" after onError/onComplete. To receive more data, you need to create a new stream.

Any messages sent after onError/onComplete will just be thrown away. This is because the sending and receiving can happen on different threads and we want to avoid random/spurious exceptions when possible.

**Comment by dingrui37** [comment]
Do you mean after response stream observer onErr/onComplete, the request observer  will not take effect (client side)? 
```
          StreamObserver<TelemetryStreamRequest> requestStreamObserver =
                  asyncStub.report(new StreamObserver<TelemetryStreamResponse>() {
                      @Override
                      public void onNext(TelemetryStreamResponse telemetryStreamResponse) {...}
 
                      @Override
                      public void onError(Throwable throwable) {
                       ////io.grpc.StatusRuntimeException: UNAVAILABLE 

                       ////This is response stream observer
                      }
 
                      @Override
                      public void onCompleted() {...}
                  });
```

**Comment by ejona86** [comment]
Yes, after the `onError()`/`onCompleted()` callback, any messages sent on `requestStreamObserver` will not be received by the server.

**Comment by dingrui37** [comment]
Thank you @ejona86 .
