### ISSUE TITLE
Can not connect to Server after enabling TLS

### ISSUE THREAD

**Issue by danhcc** [grpc/grpc-java#4218]
I'm using gRPC version __1.7.0__

I designed my services as follow:
- A backend (gRPC) server
- HAProxy
- A simple gRPC Client

My HAProxy is configured with TLS, HTTP2. gRPC Client connect to gRPC Server via HAProxy so there only need to be TLS between HAProxy and gRPC Client, between gRPC Server and HAProxy, it's raw data.

The problem is, I can't connect to my gRPC Server if I set 

```java
usePlainText(false)
```

But if I set:

```java
usePlainText(true)
```
Then I receive this Error:

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
```

Back then with gRPC version __1.0.3__, I managed to connect my Client and Server via HAProxy successfully but this time, I can't. I use the same configuation for my HAProxy so I wonder if there something wrong with my library. Here's my dependencies for gRPC Client:

```xml
<dependencies>
        <!-- https://mvnrepository.com/artifact/io.grpc/grpc-all -->
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-all</artifactId>
            <version>1.7.0</version>
        </dependency>

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.6.Final</version>
        </dependency>

        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.3.7</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/ch.qos.logback/logback-classic -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>

    </dependencies>
```

**Comment by ejona86** [comment]
> But if I change usePlaintext from false to true (disable TLS)

That's not what that argument means. Any time you call `usePlaintext()` you're going to use plaintext. The boolean is whether to do an HTTP/1 to HTTP/2 upgrade or assume HTTP/2. You should not be calling usePlaintext.

Note that if you have continued problems, the HAProxy configuration becomes very important. Like whether you're doing TCP-based or HTTP/2-based proxying and whether you've configured HTTP/2 to the backend.

**Comment by danhcc** [comment]
Back then with gRPC version 1.0.3, I managed to connect to server succesfully with the same HAProxy configuation so I think HAProxy configuation is not the problem.
I remove `usePlaintext` and still can not connect to server.
Is there any way to test if my domain (HAProxy) is configured correctly?

**Comment by danhcc** [comment]
FYI, this is my HAProxy config:

```bash
frontend mydomain.com
        bind *:8404 ssl crt /path/to/file/cert.pem alpn h2,http/1.1
        mode tcp
        timeout client 2h
        use_backend backend1 if { ssl_fc_alpn -i h2 }
backend backend1
        mode tcp
        timeout connect 2h
        timeout server 2h
        server pc-671.11 10.60.7.10:8210 check port 8210 maxconn 2048 inter 5s weight 50
```

**Comment by ejona86** [comment]
If you had a working configuration with v1.0.3, what changes did you make? Did you _only_ upgrade to gRPC to v1.7.0. Or did you swap from plaintext to TLS or some such as well?

Okay, so it seems you are doing tcp-based proxying in haproxy and using haproxy as a TLS terminator. In that configuration you should not call `useTransportSecurity` for the gRPC server and you should not call `usePlaintext` for the gRPC client.

> I remove usePlaintext and still can not connect to server.

What error message did you see? Or did it just hang?

**Comment by danhcc** [comment]
I don't have `useTransportSecurity` for gRPC server and as you mentioned ealier, I remove `usePlaintext` for gRPC client.

This is my ServerBuilder:
```java
ServerBuilder serverBuilder = NettyServerBuilder.forPort(port)
                .bossEventLoopGroup(this.bossEventGroup)
                .workerEventLoopGroup(this.workerEventGroup)
                .channelType(EpollServerSocketChannel.class)
                .maxConnectionIdle(maxConnectionIdleSecond, TimeUnit.SECONDS)
                .maxConnectionAgeGrace(maxConnectionAgeGraceSecond, TimeUnit.SECONDS)
                .maxMessageSize(maxMessageSizeByte)
                .addService(ServerInterceptors.intercept(serviceImpl, interceptor))
                .executor(this.executor);
```
This is my ChannelBuilder (gRPC Client)
```java
channel = ManagedChannelBuilder
                .forAddress(domain, port)
                .build();

interceptChannel = ClientInterceptors.intercept(channel, new ClientHeaderInterceptor());

asyncStub = GatewayServiceGrpc.newStub(interceptChannel);

blockingStub = GatewayServiceGrpc.newBlockingStub(interceptChannel);
```
I actually tried using version 1.0.3 and I couldn't connect either. And this is error message:

```java
io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: engine closed
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshake()(Unknown Source)
```
