### ISSUE TITLE
Can't run benchmark with --tls mode

### ISSUE THREAD

**Issue by truyet** [grpc/grpc-java#4223]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.10.0

### What did you expect to see?
Server run success in tls mode

I run AsyncServer with option --tls=true but java throw error:

Exception in thread "main" java.lang.IllegalArgumentException: ALPN is not configured properly. See https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting for more information.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:166)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.benchmarks.qps.AsyncServer.newServer(AsyncServer.java:106)
	at io.grpc.benchmarks.qps.AsyncServer.run(AsyncServer.java:76)
	at io.grpc.benchmarks.qps.AsyncServer.main(AsyncServer.java:61)
Caused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
	... 4 more

**Comment by danhcc** [comment]
I think some library is missing because of this line:

```java
java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
```
Can you post your pom.xml file?

**Comment by truyet** [comment]
I use gradle to build. Here is gradle file:

https://github.com/grpc/grpc-java/blob/master/benchmarks/build.gradle

**Comment by ejona86** [comment]
@truyet, what environment (OS and Java version) did you execute the server on? How did you run the server (e.g., the scripts generated with `:installDist`)?

**Comment by truyet** [comment]
Hi @ejona86 ,
I run benchmark on Intellij IDE, java version 1.8, MacOSX 10.13.
I added to VM options -Xbootclasspath/p:alpn-boot-8.1.9.v20160720.jar (https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html) for server and client. It worked good. So you're missing that ?

**Comment by ejona86** [comment]
@truyet, we're not missing anything. Running via an IDE frequently requires configuring the IDE; there's no per-binary configuration read by the IDE. Note that it shouldn't need alpn-boot and we discourage its usage (it is necessary for okhttp testing today, but we're working away from that). We run these from the scripts generated from `../gradlew :installDist`, as mentioned in benchmarks/README.md.

It seems in this case the need for Jetty ALPN is because [the code is mistakenly hard-coded to use it](https://github.com/grpc/grpc-java/blob/v1.10.0/benchmarks/src/main/java/io/grpc/benchmarks/qps/AsyncServer.java#L106). It looks like it mistook tcnative as having something to do with epoll or abused the option. We should simply delete lines 105-110.
