### ISSUE TITLE
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation

### ISSUE THREAD

**Issue by amanda2015** [grpc/grpc-java#4286]
Please answer these questions before submitting your issue.
I've tried to use grpc-java library to connect sever side with SSL,  but it was failure. 

What version of gRPC are you using?
1.2.0

What JVM are you using (java -version)?
1.8.0_111

```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>1.1.33.Fork26</version>
</dependency>
```

What did you expect to see?
Connection with SSL works fine.

What did you see instead?
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.nokia.csdc.KVResponse.GetResponse(KVResponse.java:47)
	at com.nokia.csdc.SdcClient.get(SdcClient.java:269)
	at com.nokia.csdc.SdcClient.adjustPath(SdcClient.java:1193)
	at com.nokia.csdc.SdcClient.constructFullPath(SdcClient.java:1248)
	at com.nokia.csdc.SdcClient.setKeyValue(SdcClient.java:363)
	at com.nokia.csdc.SdcClient.setKeyValue(SdcClient.java:335)
	at com.nokia.csdc.TestApi.main(TestApi.java:37)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.coreos.jetcd.internal.impl.Util.lambda$2(Util.java:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	... 3 more
```

**Comment by dapengzhang0** [comment]
@amanda2015 can you enable log levels with the following logging.properties and show the log?

```
.level = ALL
io.netty.level = INFO
io.netty.handler.codec.http2.Http2FrameLogger.level = FINE
io.grpc.netty.NettyClientHandler = ALL
io.grpc.netty.NettyServerHandler = ALL
io.grpc.netty.ProtocolNegotiators = ALL
```

**Comment by amanda2015** [comment]
I tried it according to what you said, But There was the same error log.

**Comment by ericgribkoff** [comment]
@amanda2015 Just to confirm - when using the `logging.properties` suggested in @dapengzhang0's comment, where you also running with the JVM flag `-Djava.util.logging.config.file=logging.properties`? I'd expect more output in the error logs with this configuration, but perhaps not.

Are you able to try running with a more recent version of gRPC? Ideally, v1.11.0. This might result in a successful connection, or a more useful error message, depending on what problem you're running into.

**Comment by ejona86** [comment]
@amanda2015, could you tell us a bit more about the server? It'd be easy to see that failure if the client or server was actually trying to talk plaintext. Clients default to using TLS whereas Java servers default to plaintext (you can use `useTransportSecurity()` to enable TLS).

If you have openssl installed, you can try contacting the server with `openssl s_client -connect host:port` and it should display certificate information (try using it with `example.com:80` and `example.com:443` to see what the output should look like).

**Comment by amanda2015** [comment]
I updated the new version, and now work well. Thank you.
