### ISSUE TITLE
NettyServerTest.channelzListenSocket is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4299]
https://travis-ci.org/grpc/grpc-java/jobs/361809081 (since rebuilt)
```
io.grpc.netty.NettyServerTest > channelzListenSocket FAILED
    java.lang.NullPointerException
        at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:301)
        at io.grpc.netty.NettyServerTest.channelzListenSocket(NettyServerTest.java:216)
```

**Comment by zpencer** [comment]
Fixed by https://github.com/grpc/grpc-java/commit/49c8bdb60ac8783eda098aa42375b837342edde3
