### ISSUE TITLE
NoSuchMethodError when creating connection to the server

### ISSUE THREAD

**Issue by mayooran99** [grpc/grpc-java#4423]
I have a GRPC server running and I'm trying to establish connection to that. When the client tries to execute the below code,

` this.managedChannel = ManagedChannelBuilder.forAddress(this.hostName, this.port)
                .usePlaintext().build();`
it's throwing the below mentioned exception.

`java.lang.NoSuchMethodError: io.grpc.okhttp.OkHttpChannelProvider.isAndroid()Z

	at io.grpc.okhttp.OkHttpChannelProvider.priority(OkHttpChannelProvider.java:47)
	at io.grpc.ManagedChannelProvider$1.getPriority(ManagedChannelProvider.java:49)
	at io.grpc.ManagedChannelProvider$1.getPriority(ManagedChannelProvider.java:41)
	at io.grpc.ServiceProviders$1.compare(ServiceProviders.java:78)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5178)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:75)
	at io.grpc.ServiceProviders.load(ServiceProviders.java:42)
	at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:37)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:36)
	at com.test.ci.metricsManager.ColumnsServiceTest.setup(ColumnsServiceTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.TestRunner.beforeRun(TestRunner.java:529)
	at org.testng.TestRunner.run(TestRunner.java:497)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)`

This was working fine for some time now. What am I doing wrong here? Below are the versions I'm using.

`<dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>trivago.ti.metricsmanager</groupId>
            <artifactId>ti-metrics-manager</artifactId>
            <version>LATEST</version>
            <classifier>all</classifier>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-alts</artifactId>
            <version>1.11.0</version>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-testing</artifactId>
            <version>1.11.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.8.Final</version>
        </dependency>
        <dependency>
            <groupId>com.google.api.grpc</groupId>
            <artifactId>proto-google-common-protos</artifactId>
            <version>1.0.0</version>
        </dependency>`

**Comment by lcb1208** [comment]
me too,version 1.10.0 is ok
