### ISSUE TITLE
Compile grpc-java using Bazel in another repo

### ISSUE THREAD

**Issue by oferb** [grpc/grpc-java#4443]
### What version of gRPC are you using?
v1.11.0
Using this Bazel dependency:
```
git_repository(
  name = "io_grpc_grpc_java",
  remote = "https://github.com/grpc/grpc-java",
  tag = "v1.11.0",
)
```

### What did you expect to see?
A successful compilation :)
I ran `bazel build //tools/local_server:local_server` on the code in this Pull Request: https://github.com/google/startup-os/pull/47

I had this issue: 
```
ERROR: /home/oferb/devel/startup-os_diff_in_server/tools/reviewer/service/BUILD:16:1: no such package 'protobuf': BUILD file not found on package path and referenced by '//tools/reviewer/service:code_review_java_grpc'
```

I then switched to head, since I saw that you fixed relative to absolute paths for some dependencies (can't find that commit now). Head was at commit 46079fff8aa50b5a9222b79f9ea01472fcd5b44f when I tried. I got the following error:
```
ERROR: /home/oferb/.cache/bazel/_bazel_oferb/d1a1bc2fb585e22d4f266eccbec87245/external/com_google_protobuf/BUILD:612:1: no such target '//external:gson': target 'gson' not declared in package 'external' defined by /home/oferb/devel/startup-os_diff_in_server/WORKSPACE and referenced by '@com_google_protobuf//:protobuf_java_util'
ERROR: /home/oferb/.cache/bazel/_bazel_oferb/d1a1bc2fb585e22d4f266eccbec87245/external/com_google_protobuf/BUILD:612:1: no such target '//external:guava': target 'guava' not declared in package 'external' (did you mean 'java'?) defined by /home/oferb/devel/startup-os_diff_in_server/WORKSPACE and referenced by '@com_google_protobuf//:protobuf_java_util'
```

I then added the following bindings to WORKSPACE:
```
bind(
    name = "gson",
    actual = "//third_party/maven/com/google/code/gson",
)
bind(
    name = "guava",
    actual = "//third_party/maven/com/google/guava",
)
```

I then got the following error:
```
ERROR: /home/oferb/.cache/bazel/_bazel_oferb/d1a1bc2fb585e22d4f266eccbec87245/external/io_grpc_grpc_java/stub/BUILD.bazel:18:1: no such package '@javax_annotation_api//file': BUILD file not found on package path and referenced by '@io_grpc_grpc_java//stub:javax_annotation'
```

General note:
My main goal here is to be able to compile and run a grpc java server, built with Bazel.
The code in the `startup-os` repo serves as a collection of examples for how to use different Google Open Source technologies together. Once this bug is solved, you can point people to that repo for a working example.
Thanks!

**Comment by oferb** [comment]
Small update:
I also tried `v1.10.1` and it compiled (server and client), and I could run the server, but when I ran the client, I got:
```
java.lang.NoSuchMethodError: io.grpc.StreamTracer.outboundMessage()V
	at io.grpc.internal.StatsTraceContext.outboundMessage(StatsTraceContext.java:161)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:131)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:52)
	at io.grpc.internal.DelayedStream$5.run(DelayedStream.java:218)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:132)
	at io.grpc.internal.DelayedStream.setStream(DelayedStream.java:101)
	at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:414)
	at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:397)
	at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:355)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:626)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:122)
	at com.google.startupos.tools.reviewer.service.CodeReviewServiceGrpc$CodeReviewServiceBlockingStub.getFile(CodeReviewServiceGrpc.java:290)
	at com.google.startupos.tools.reviewer.service.TestTool.getFile(TestTool.java:50)
	at com.google.startupos.tools.reviewer.service.TestTool.run(TestTool.java:69)
	at com.google.startupos.tools.reviewer.service.TestTool.main(TestTool.java:74)
```

**Comment by dapengzhang0** [comment]
It seems  `@org_pubref_rules_protobuf//java:rules.bzl` does not work very well with `@io_grpc_grpc_java//:java_grpc_library.bzl`. They both call `java_proto_library` but refer to different things. The former is
[`load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")`](https://github.com/pubref/rules_protobuf/blob/master/java/rules.bzl#L75) whereas the latter is
https://docs.bazel.build/versions/master/be/java.html#java_proto_library

**Comment by dapengzhang0** [comment]
@oferb now tag v.1.12.0 is out (although release 12 is not completed), it fixed io_grpc_ prefix, able to build with this version?

**Comment by oferb** [comment]
Right, so I removed `pubref` completely, and switched to v1.12.0. It needed some more dependencies to compile, which I added. It then compiled and ran the server, compiled and failed to run the client (like before).
I tried adding more dependencies, since it's a `NoSuchMethodError`, I figured maybe it's missing a dep (but actually, maybe it's using an older version of a dep that's missing that method). That still didn't help.

I pushed a new commit with these changes:
https://github.com/google/startup-os/pull/47

**Comment by dapengzhang0** [comment]
>  maybe it's using an older version of a dep that's missing that method

That's the reason. You have 
```
# WORKSPACE
load("//third_party/maven:workspace.bzl", "maven_dependencies")
maven_dependencies()
```

and
```
# third_party/maven/workspace.bzl
{"artifact": "io.grpc:grpc-auth:1.9.0", "lang": "java", "sha1": "d2eadc6d28ebee8ec0cef74f882255e4069972ad", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_auth", "actual": "@io_grpc_grpc_auth//jar", "bind": "jar/io/grpc/grpc_auth"},
    {"artifact": "io.grpc:grpc-context:1.9.0", "lang": "java", "sha1": "28b0836f48c9705abf73829bbc536dba29a1329a", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_context", "actual": "@io_grpc_grpc_context//jar", "bind": "jar/io/grpc/grpc_context"},
    {"artifact": "io.grpc:grpc-core:1.9.0", "lang": "java", "sha1": "cf76ab13d35e8bd5d0ffad6d82bb1ef1770f050c", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_core", "actual": "@io_grpc_grpc_core//jar", "bind": "jar/io/grpc/grpc_core"},
    {"artifact": "io.grpc:grpc-netty:1.9.0", "lang": "java", "sha1": "8157384d87497dc18604a5ba3760763fe643f16e", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_netty", "actual": "@io_grpc_grpc_netty//jar", "bind": "jar/io/grpc/grpc_netty"},
    {"artifact": "io.grpc:grpc-protobuf-lite:1.9.0", "lang": "java", "sha1": "9dc9c6531ae0b304581adff0e9b7cff21a4073ac", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_protobuf_lite", "actual": "@io_grpc_grpc_protobuf_lite//jar", "bind": "jar/io/grpc/grpc_protobuf_lite"},
    {"artifact": "io.grpc:grpc-protobuf:1.9.0", "lang": "java", "sha1": "94ca247577e4cf1a38d5ac9d536ac1d426a1ccc5", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_protobuf", "actual": "@io_grpc_grpc_protobuf//jar", "bind": "jar/io/grpc/grpc_protobuf"},
    {"artifact": "io.grpc:grpc-stub:1.9.0", "lang": "java", "sha1": "20e310f888860a27dfa509a69eebb236417ee93f", "repository": "https://repo.maven.apache.org/maven2/", "name": "io_grpc_grpc_stub", "actual": "@io_grpc_grpc_stub//jar", "bind": "jar/io/grpc/grpc_stub"},
```
To load the right dependencies for grpc, it is recommended to call
```
load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")
grpc_java_repositories() 
# grpc_java_repositories(omit_some_dup_deps = True, ...) 
```

**Comment by oferb** [comment]
Looks like it's working on v1.12.0 (!)
Will clean up and push the fix.
Thanks!

**Comment by oferb** [comment]
Ok, it's working! and pushed.
For anyone looking for how to do this, here's the relevant commit:
https://github.com/google/startup-os/commit/3d0c0cc27bc2cc8c175de8b022b47369741f00e0
