### ISSUE TITLE
No functional server found with gRPC v1.11 and 1.12 on Android

### ISSUE THREAD

**Issue by Houf** [grpc/grpc-java#4513]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
This work on Android with the following dependencies:
    implementation 'io.grpc:grpc-netty:1.10.1'
    implementation 'io.grpc:grpc-protobuf:1.10.1'
    implementation 'io.grpc:grpc-stub:1.10.1'
    implementation 'io.grpc:grpc-okhttp:1.10.1'

However, with gRPC version 1.11 and 1.12 of those libraries, the following exception is thrown when a gRPC server is started:

 java.lang.RuntimeException: Unable to start service **@c7238b7 with Intent { cmp=** }: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty artifact

### What did you expect to see?

I was expecting the server to start with latest version. The same build configuration and the same application code is used for each gRPC dependencies version. It only works when using version 1.10.1

Our application is running on Google Pixel device with Android 7.x and 8.x, We're using Java 8.

**Comment by zpencer** [comment]
Are you trying to start the server on the android device?

Looking at the exception, the error message seems wrong. If `io.grpc.ManagedChannelProvider` detects a dependency problem it should report that a `channel service provider` is not found. Can you confirm that the error does not originate from `io.grpc.ServerProvider`?

**Comment by Houf** [comment]
Yes, it originate from io.grpc.ServerProvider

The full stacktrace is:

05-29 11:41:02.982 25909-25909/***.***.*** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ***.***.***, PID: 25909
    java.lang.RuntimeException: Unable to start service ***.***.***@aa68825 with Intent { cmp=***.***.***/.services.*** }: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty artifact
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3491)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: io.grpc.ManagedChannelProvider$ProviderNotFoundException: No functional server found. Try adding a dependency on the grpc-netty artifact
        at io.grpc.ServerProvider.provider(ServerProvider.java:55)
        at io.grpc.ServerBuilder.forPort(ServerBuilder.java:40)
        at ***.***.***.grpc.BaseGrpcService.start(BaseGrpcService.java:22)
        at ***.***.***.grpc.***.***Receiver.start(***Receiver.java:35)
        at ***.***.***.services.***.startService(***.java:88)
        at ***.***.***.services.***.onStartCommand(***.java:63)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3474)
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 


The code in BaseGrpcService is as follow:
		
import java.io.IOException;
import io.grpc.BindableService;
import io.grpc.Server;
import io.grpc.ServerBuilder;
	
public abstract class BaseGrpcService
{
    private static final Logger LOGGER = Logger.getLogger(BaseGrpcService.class);

    protected Server _server;

    public void start(
        final String name,
        final int port,
        final BindableService bindableService) throws IOException
    {
        _server = ServerBuilder.forPort(port).addService(bindableService).build().start();
        LOGGER.debug(name + " Server started, listening on port " + port);

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            LOGGER.debug("*** Shutting down gRPC server since JVM is shutting down.");
            _server.shutdown();
            LOGGER.debug("*** Server shut down");
        }));
    }
}

**Comment by zpencer** [comment]
That makes more sense. At the moment, running gRPC Java servers on Android is not supported. There are reports that it does work with some manual work though. I would suggest following the debugging steps of these past threads and see if it resolves the issue for you:
https://github.com/grpc/grpc-java/issues/2227
https://github.com/grpc/grpc-java/issues/3356

We do intend to support C++ servers on Android as mentioned in https://github.com/grpc/grpc-java/issues/4407.
