### ISSUE TITLE
examples/helloworldtls: SSLHandshakeException when using ClientAuth.REQUIRE with two hosts

### ISSUE THREAD

**Issue by DmPanov** [grpc/grpc-java#4515]
I am trying to configure TLS with required mutual authentication between two hosts in LAN without DNS-server using https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/helloworldtls.
In my configuration server is accessed by IP so I've added subjectAltName to certificate generation script, see https://github.com/DmPanov/grpc-java/commit/0db1778c450d30d4470e92cec6ae3493d8eeb979

### What version of gRPC are you using?
1.12.0

### What did you expect to see?
I expect that this is a valid configuration

### What I get?

```
WARNING: RPC failed: Status{code=UNAVAILABLE, description=io exception, cause=javax.net.ssl.SSLHandshakeException: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:862)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1110)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1066)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1132)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1175)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1257)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1203)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by carl-mastrangelo** [comment]
cc @ejona86

**Comment by ericgribkoff** [comment]
@ejona86, who would be best suited to answer this question, is out of office until next week

**Comment by DmPanov** [comment]
I have found a solution looking into `HelloWorldClientTls/HelloWorldServerTls` traffic tcpdump.
### What was the problem
* Server IP is S, it's certificate issued for S by S
* Client IP is C, it's certificate issued for C by S
* When performing mutual auth Server sends `CertificateRequest` with C in `Distinguished Name` 
* Latter happens because Server's trust store is initialised with `client.crt` which is issued for C who is not a Certificate Authority
* Client response is empty `Certificate` packet because Client is unable to find certificate issued by C
### How to fix
Replace `client.crt` in start command `hello-world-server-tls <host> <port> server.crt server.pem client.crt` with proper Certificate Authority which is `ca.crt`
### Is it bug in docs?
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#mutual-tls says:
> .trustManager(clientCertChainFile)

which supposed to let server to trust `clientCertChainFile` but instead server demands client cert to be signed by  `clientCertChainFile`. Am I missing something in configuration?
Problem is not present when using localhost for both client and server.

**Comment by ejona86** [comment]
Yeah, instead of `.trustManager(clientCertChainFile)` it should likely be `.trustManager(clientCAsFile)`. Although if the cert chain includes the client's CA, then it should still function. The change for the hello-world-server-tls execution also looks correct.

**Comment by DmPanov** [comment]
Created https://github.com/grpc/grpc-java/pull/4561, please review

**Comment by dapengzhang0** [comment]
The above PR resolved the issue.
