### ISSUE TITLE
Dynamically linked netty-tcnative is compiled against OpenSSL 1.0.1

### ISSUE THREAD

**Issue by sebtomba** [grpc/grpc-java#4520]
On Ubuntu 16.04 LTS `NettyChannelBuilder` with dynamic `netty-tcnative` (`linux-x86_64` classifier) throws

```
io.netty.channel.ChannelPipelineException: io.grpc.netty.ProtocolNegotiators$TlsNegotiator$1.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:626) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:287) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.channelRegistered(ProtocolNegotiators.java:435) ~[grpc-netty-1.10.0.jar:1.10.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1332) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:829) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
Caused by: java.lang.Exception: hostname verification requires OpenSSL 1.0.2+
	at io.netty.internal.tcnative.SSL.setHostNameValidation(Native Method) ~[netty-tcnative-2.0.8.Final-linux-x86_64.jar:2.0.8.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setSSLParameters(ReferenceCountedOpenSslEngine.java:1828) ~[netty-handler-4.1.17.Final.jar:4.1.17.Final]
	at io.grpc.netty.ProtocolNegotiators$TlsNegotiator$1.handlerAdded(ProtocolNegotiators.java:309) ~[grpc-netty-1.10.0.jar:1.10.0]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:287) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.channelRegistered(ProtocolNegotiators.java:435) ~[grpc-netty-1.10.0.jar:1.10.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1332) ~[netty-transport-4.1.17.Final.jar:4.1.17.Final]
```
Installed version of OpenSSL: `OpenSSL 1.0.2g`

This is related to
https://github.com/netty/netty-tcnative/issues/269
https://github.com/netty/netty-tcnative/issues/265#issuecomment-297593386
https://github.com/netty/netty-tcnative/issues/273

Is there any workaround for this problem? Is it possible to disable hostname verification in `grpc-java`? (I know, this question has been asked before)

**Comment by ejona86** [comment]
You should not disable hostname validation. I also don't think there is a way to disable it with grpc-netty today.

This seems like a netty-tcnative problem. I'd suggest opening an issue on netty/netty-tcnative, but do can CC me on it.

**Comment by sebtomba** [comment]
@ejona86 @ericgribkoff  I have one question that bothers me. Since the dynamically linked version of `netty-tcnative` is broken, is everyone out there using `netty-tcnative-boringssl-static` in production?

**Comment by ejona86** [comment]
It's unclear to me what is going wrong on this. In the past people have used dynamically linked versions of netty-tcnative with gRPC, because in the past the static version didn't exist. But we do tend to suggest people to use the boringssl-static because it works in a wide variety of deployment scenarios.
