### ISSUE TITLE
Receive UNKNOWN: Exception was thrown by handler

### ISSUE THREAD

**Issue by OlegZhilo** [grpc/grpc-java#4546]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
Version: 1.12

### What did you expect to see?
I'm using BI stream on Android. 
Channel: 
OkHttpChannelBuilder.forAddress(host, port)
                .intercept(metadataClientInterceptor, grpcLoggingInterceptor)
                .build()
But after get first bunch of values, I get UNKNOWN: Exception was thrown by handler

My ios colleagues have same problem. But they have solved it by using:
https://github.com/grpc/grpc/blob/master/src/objective-c/RxLibrary/GRXBufferedPipe.m

What am I doing wrong?

**Comment by ericgribkoff** [comment]
I don't see where that string ("Exception was thrown by handler") would be generated by the gRPC library; is it possible your interceptors are throwing the exception? Can you post the stack trace?

**Comment by OlegZhilo** [comment]
io.grpc.StatusRuntimeException: UNKNOWN: Exception was thrown by handler.
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
        at com.twim.trading.interactor.common.grpc.GrpcLoggingInterceptor$interceptCall$1$start$1.onClose(GrpcLoggingInterceptor.kt:51)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by OlegZhilo** [comment]
`
io.grpc.StatusRuntimeException: UNKNOWN: Exception was thrown by handler.
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
        at com.twim.trading.interactor.common.grpc.GrpcLoggingInterceptor$interceptCall$1$start$1.onClose(GrpcLoggingInterceptor.kt:51)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
`

**Comment by ericgribkoff** [comment]
gRPC servers can return a status code and message to the client. It appears that "UNKNOWN: Exception was thrown by handler" is the status code and message sent from your server. This doesn't indicate a gRPC client library issue; rather, you should check with the server itself to see what is triggering this response.

**Comment by OlegZhilo** [comment]
@ericgribkoff 
I've found this message ingrpc repo
https://github.com/grpc/grpc/blob/b74e050112fbdcb2cfdf475a167aa326e9bf26b9/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs
**line 340**

I still don't understand source of problem

**Comment by ericgribkoff** [comment]
I'm not familiar with C#, but it looks like the server is likely logging the following warning before returning the UNKNOWN status code: "Exception occurred in the handler or an interceptor." (see [code here](https://github.com/grpc/grpc/blob/b74e050112fbdcb2cfdf475a167aa326e9bf26b9/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L204) prior to calling the `GetStatusFromExceptionAndMergeTrailers` method you linked to).

If I had to guess, the server-side code is throwing an exception, which gets caught by gRPC C#. If you can provide a reproduction of the error that is caused by the gRPC library itself (rather than an issue in the server application code), please file an issue along with the reproduction instructions on the grpc/grpc repository at https://github.com/grpc/grpc.

I'm going to mark this closed, as there doesn't seem to be anything to be done on the Java client side here. Feel free to reopen if you have additional questions regarding the gRPC Java library.

**Comment by OlegZhilo** [comment]
@ericgribkoff do u now, how to enable flow controll for OkHttpChannelBuilder?

**Comment by ericgribkoff** [comment]
Flow control is enabled by default for OkHttp. You can see the example code in https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/manualflowcontrol if you want to manually handle flow control.

**Comment by OlegZhilo** [comment]
@ericgribkoff Much thanks!
