### ISSUE TITLE
StreamObservers.copyWithFlowControl calls StreamObserver.onComplete twice

### ISSUE THREAD

**Issue by biran0079** [grpc/grpc-java#4558]
Client stream observer on ready handler is invoked after stream is half closed.
```java
      StreamObserver<HelloReply> resp = new ClientResponseObserver<HelloRequest, HelloReply>() {
        @Override
        public void onNext(HelloReply value) {

        }

        @Override
        public void onError(Throwable t) {
          t.printStackTrace();
        }

        @Override
        public void onCompleted() {
        }

        @Override
        public void beforeStart(ClientCallStreamObserver<HelloRequest> requestStream) {
          StreamObservers.copyWithFlowControl(
              ImmutableList.of(HelloRequest.newBuilder().setName(payload).build()), 
              requestStream);
        }
      };
     stub.sayHello(resp);
```
Following error is found:

```
> io.grpc.StatusRuntimeException: CANCELLED: Failed to call onReady.
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamOnReady.runInContext(ClientCallImpl.java:613)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: call already half-closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:501)
	at io.grpc.internal.ClientCallImpl.halfClose(ClientCallImpl.java:418)
	at io.grpc.PartialForwardingClientCall.halfClose(PartialForwardingClientCall.java:43)
	at io.grpc.ForwardingClientCall.halfClose(ForwardingClientCall.java:22)
	at io.grpc.ForwardingClientCall$SimpleForwardingClientCall.halfClose(ForwardingClientCall.java:44)
	at io.grpc.PartialForwardingClientCall.halfClose(PartialForwardingClientCall.java:43)
	at io.grpc.ForwardingClientCall.halfClose(ForwardingClientCall.java:22)
	at io.grpc.ForwardingClientCall$SimpleForwardingClientCall.halfClose(ForwardingClientCall.java:44)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onCompleted(ClientCalls.java:330)
	at io.grpc.stub.StreamObservers$1FlowControllingOnReadyHandler.run(StreamObservers.java:52)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onReady(ClientCalls.java:426)
	at io.grpc.PartialForwardingClientCallListener.onReady(PartialForwardingClientCallListener.java:42)
	at io.grpc.ForwardingClientCallListener.onReady(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onReady(ForwardingClientCallListener.java:40)
	at io.grpc.PartialForwardingClientCallListener.onReady(PartialForwardingClientCallListener.java:42)
	at io.grpc.ForwardingClientCallListener.onReady(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onReady(ForwardingClientCallListener.java:40)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamOnReady.runInContext(ClientCallImpl.java:608)
```

`payload` is a string of  1 million char.
This error does not happen with small payload.

### What version of gRPC are you using?
1.11.0

### What did you expect to see?
`onComplete()` should only be called once for request stream.

**Comment by carl-mastrangelo** [comment]
Hmm, seems tricky.  The `StreamObservers` doesn't know if the call is completed out of band.

**Comment by biran0079** [comment]
One thing I noticed is that `requestStream.isReady()` returns `false` when on ready handler is called the last time (which calls onComplete the 2nd time), which seems wrong to me.

**Comment by carl-mastrangelo** [comment]
@biran0079 That's certainly possible.  isReady can change spuriously, and its only a hint.  Consider the case where another RPC consumers the last of the flow control window between the time you get the onReadyCallback, and when you check isReady.

**Comment by carl-mastrangelo** [comment]
@biran0079 TBH I am not sure what to do there.  Since StreamObservers allows outside code to call onCompleted and OnError, I don't know what StreamObservers should do with the provided observer.

Do you have any ideas?

**Comment by biran0079** [comment]
In this case `onComplete` are invoked twice by `StreamObservers.copyWithFlowControl`.
I think it is ok to let `StreamObservers.copyWithFlowControl` own all observer callbacks, as long as `onCompleted` or `onError` don't get called more than once.

**Comment by biran0079** [comment]
I am not sure I understand the description of https://github.com/grpc/grpc-java/pull/4592.
I don't see `onComplete` or `onError` being called outside StreamObservers.copyWithFlowControl.

I think what happened is, client stream on ready handler is invoked after channel is half-closed (when `target.onCompleted()` is called). 
Server side flow control doesn't have this problem because on ready handler is never invoked after channel is fully closed.

**Comment by carl-mastrangelo** [comment]
@biran0079 Are you saying that onready is invoked after the iterator returns `false` for `hasNext()` ?

**Comment by biran0079** [comment]
@carl-mastrangelo Exactly.
