### ISSUE TITLE
DnsNameResolver not work with Docker in user-defined bridge network

### ISSUE THREAD

**Issue by alx696** [grpc/grpc-java#4564]
### Version
```
  compile group: 'io.netty', name: 'netty-all', version: '4.1.22.Final'
  compile 'io.netty:netty-tcnative-boringssl-static:2.0.7.Final'
  compile('io.grpc:grpc-netty:1.11.0') {
    exclude group: 'io.netty'
  }
  compile 'io.grpc:grpc-protobuf:1.11.0'
  compile 'io.grpc:grpc-stub:1.11.0'
```
### Env

1.  grpc application run in Docker Container A(--name dydl_impush) with user-defined bridge network.
2.  b application run in Docker Container B(--name dydl) with the same user-defined bridge network.

#### Differences between user-defined bridges and the default bridge
https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
>  So i can communicate each other with Container Name.

I confirm that B to communicate with A is ok.
```
u@server-2:~/dydl/DATA$ docker exec -it dydl bash
root@1b5fd0b0bff8:/server# wget dydl_impush:7000
--2018-06-13 11:45:29--  http://dydl_impush:7000/
Resolving dydl_impush (dydl_impush)... 172.18.0.3
Connecting to dydl_impush (dydl_impush)|172.18.0.3|:7000... connected.
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
Length: unspecified
Saving to: ‘index.html’

index.html              [ <=>                ]      92  --.-KB/s    in 0.004s  

2018-06-13 11:45:29 (25.6 KB/s) - ‘index.html’ saved [92]
```
But grpc can not know `dydl_impush`.

Try:
```
NettyChannelBuilder.forTarget(dydl_impush:7000)
```
Exception:
```
java.lang.NullPointerException: host
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
	at io.grpc.internal.DnsNameResolver.<init>(DnsNameResolver.java:104)
	at io.grpc.internal.DnsNameResolverProvider.newNameResolver(DnsNameResolverProvider.java:55)
	at io.grpc.internal.DnsNameResolverProvider.newNameResolver(DnsNameResolverProvider.java:39)
	at io.grpc.NameResolverProvider$NameResolverFactory.newNameResolver(NameResolverProvider.java:103)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:633)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:554)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:399)
	at util.ImPushGrpc.getManagedChannel(ImPushGrpc.java:86)
	at service.organization.Person.login(Person.java:1194)
	at auto.grpc.organization.person.PersonServiceGrpc$MethodHandlers.invoke(PersonServiceGrpc.java:1211)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:698)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Try:
```
NettyChannelBuilder.forTarget(http://dydl_impush:7000)
```
Exception:
```
java.lang.IllegalArgumentException: cannot find a NameResolver for http://dydl_impush:7000
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:638)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:554)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:399)
	at util.ImPushGrpc.getManagedChannel(ImPushGrpc.java:86)
	at service.organization.Person.login(Person.java:1194)
	at auto.grpc.organization.person.PersonServiceGrpc$MethodHandlers.invoke(PersonServiceGrpc.java:1211)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:698)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Try:
```
NettyChannelBuilder.forAddress(dydl_impush, 7000)
```
Exception:
```
java.lang.IllegalArgumentException: Invalid host or port: dydl_impush 7000
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:479)
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:115)
	at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:101)
	at util.ImPushGrpc.getManagedChannel(ImPushGrpc.java:83)
	at service.organization.Person.login(Person.java:1194)
	at auto.grpc.organization.person.PersonServiceGrpc$MethodHandlers.invoke(PersonServiceGrpc.java:1211)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:698)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 6: //dydl_impush:7000
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseHostname(URI.java:3387)
	at java.net.URI$Parser.parseServer(URI.java:3236)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:673)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:477)
	... 17 more
```

Try:
```
NettyChannelBuilder.forAddress(http://dydl_impush, 7000)
```
Exception:
```
java.lang.IllegalArgumentException: Invalid host or port: http://dydl_impush 7000
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:479)
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:115)
	at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:101)
	at util.ImPushGrpc.getManagedChannel(ImPushGrpc.java:83)
	at service.organization.Person.login(Person.java:1194)
	at auto.grpc.organization.person.PersonServiceGrpc$MethodHandlers.invoke(PersonServiceGrpc.java:1211)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:698)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 8: //[http://dydl_impush]:7000
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parseServer(URI.java:3231)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:673)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:477)
	... 17 more
```

Sorry, i don`t know whats the reason.

**Comment by alx696** [comment]
Now, Now, I solved with this:
```
java.net.InetAddress inetAddress = java.net.InetAddress.getByName("dydl_impush");
String ip = inetAddress.getHostAddress();
```
ip is `172.18.0.3`

**Comment by ejona86** [comment]
The dydl_impush variable should not include the "http://"

**Comment by alx696** [comment]
@ejona86 `dydl_impush` is Docker Container Name, not a variable. With out `http://` not work too:

```
java.lang.IllegalArgumentException: Invalid host or port: dydl_impush 7000
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:479)
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:115)
	at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:101)
	at util.ImPushGrpc.getManagedChannel(ImPushGrpc.java:83)
	at service.organization.Person.login(Person.java:1194)
	at auto.grpc.organization.person.PersonServiceGrpc$MethodHandlers.invoke(PersonServiceGrpc.java:1211)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:33)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:698)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 6: //dydl_impush:7000
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseHostname(URI.java:3387)
	at java.net.URI$Parser.parseServer(URI.java:3236)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:673)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:477)
	... 17 more
```

**Comment by ejona86** [comment]
Oh, I see, and you did have that in one of the examples you tried initially. Hostnames with `_` are invalid, which is what the "illegal character" thing is talking about. DNS does not allow `_` in hostnames and some RFCs disallow it in URLs as well, although other's don't. The disallowing of `_` is Java's behavior.
