### ISSUE TITLE
Insanely cryptic AbstractMethodError thrown when making any kind of request to the gRPC server [v0.12, Scala]

### ISSUE THREAD

**Issue by Nickersoft** [grpc/grpc-java#4566]
### What version of gRPC are you using?
v1.12.0

### What did you expect to see?
So I'm trying to create an incredibly simple server in Scala:

```scala
import java.io.IOException
import io.grpc.{Server, ServerBuilder}

class HelloWorldServer()  {
    private var server: Server = _

    @throws(classOf[IOException])
    def start(): Unit = {
        this.server = ServerBuilder.forPort(8980).build()

        this.server.start()

        Runtime.getRuntime.addShutdownHook(new Thread() {
            override def run(): Unit = {
                HelloWorldServer.this.stop()
            }
        })
    }

    def stop(): Unit = {
        if (this.server != null) this.server.shutdown()
    }

    def blockUntilShutdown(): Unit = {
        if (this.server != null) this.server.awaitTermination()
    }
}
```

and starting the server:

```scala
val server = new HelloWorldServer()
server.start()
server.blockUntilShutdown()
```

Yet trying to make any kind of request to it _at all_, even in just a web browser, instantly throws this super cryptic error:

```
[grpc-default-worker-ELG-3-3] WARN io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x0d8c8994, L:/0:0:0:0:0:0:0:1:8980 - R:/0:0:0:0:0:0:0:1:55705]
java.lang.AbstractMethodError
        at io.grpc.internal.Channelz.add(Channelz.java:222)
        at io.grpc.internal.Channelz.addServerSocket(Channelz.java:95)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.init(ServerImpl.java:385)
        at io.grpc.internal.ServerImpl$ServerListenerImpl.transportCreated(ServerImpl.java:331)
        at io.grpc.netty.NettyServer$1.initChannel(NettyServer.java:186)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
```

And I have absolutely no idea what it could be. At first I thought my service class wasn't being initialized properly, but after removing the `addService()` call the issue persisted. It doesn't seem to be a service-level abstraction issue, but more so an abstraction issue when trying to open any kind of socket at all. I've based this implementation directly off of what I found in the docs, but perhaps I'm missing something. Any reason this could be happening? Is this a bug?

**Comment by carl-mastrangelo** [comment]
cc: @zpencer

**Comment by dapengzhang0** [comment]
> at io.grpc.netty.NettyServer$1.initChannel(NettyServer.java:186)

It seems [line 186](https://github.com/grpc/grpc-java/blob/v1.12.0/netty/src/main/java/io/grpc/netty/NettyServer.java#L186) in `NettyServer` in v1.12.0 does not invoke 

` io.grpc.internal.ServerImpl$ServerListenerImpl.transportCreated(ServerImpl.java:331)`

So probably the your `io.grpc.netty` package is from a jar in a different release, and that creates a `ServerTransport` with incompatible API signatures and thus `AbstractMethodError` occurred.

**Comment by Nickersoft** [comment]
Thanks for the replies! Unfortunately, it would seem it was simply a dependency issue, as I think I originally suspected. I'm using Bazel for my project, and the fact that dependencies aren't transitively resolved for Bazel resulted in me missing some pretty core dependencies in my RPC server. For those who are curious and may come across this issue in the future, here's how I set up this library with Bazel:

`WORKSPACE`
```python
http_archive(
    name = "io_grpc_grpc_java",
    url = "https://github.com/grpc/grpc-java/archive/v1.12.0.zip",
    strip_prefix = "grpc-java-1.12.0"
)
load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")
grpc_java_repositories()
```

`BUILD`
```python
load("@io_grpc_grpc_java//:java_grpc_library.bzl", "java_grpc_library")

proto_library(
    name = "proto_schema",
    srcs = ["myschema.proto"]
)

java_proto_library(
    name = "proto_core",
    deps = [":proto_schema"],
    visibility = ["//visibility:public"]
)

java_grpc_library(
    name = "proto_grpc",
    srcs = [":proto_schema"],
    deps = [":proto_core"],
    visibility = ["//visibility:public"]
)
```

and then in my library dependencies I also added:

```
"@io_grpc_grpc_java//core:core",
"@io_grpc_grpc_java//netty:netty",
"@io_grpc_grpc_java//protobuf:protobuf",
"@io_grpc_grpc_java//stub:stub",
"//:proto_core",
"//:proto_grpc"
```

This was enough to give me all the classes I needed to spin up the gRPC Java server, as well as the generated Protobuf classes + gRPC ImplBase class. Managed to do this by poking around the codebase. I found it discouraging that despite using Bazel, using this library with Bazel projects did not seem well documented (unless I overlooked something). Anyway, my issue is resolved. Hope this helps someone in the future. Closing for now.
