### ISSUE TITLE
gae-interop jdk7 timeoutOnSleepingServer is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4626]
It looks like a bug may be hiding the real failure information.

https://source.cloud.google.com/results/invocations/cd881f61-681b-4b0c-a98b-f8f28a60a792
```
  Test method: public void io.grpc.testing.integration.AbstractInteropTest.timeoutOnSleepingServer() throws java.lang.Exception
  java.lang.reflect.InvocationTargetException
  	at com.google.appengine.runtime.Request.process-4550ff4321345ce4(Request.java)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:42)
  	at io.grpc.testing.integration.OkHttpClientInteropServlet.doGet(OkHttpClientInteropServlet.java:90)
  	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
  	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
  	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
  	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
  	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
  	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
  	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
  	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
  	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
  	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
  	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
  	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
  	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
  	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
  	at org.mortbay.jetty.Server.handle(Server.java:326)
  	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
  	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
  	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
  	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
  	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
  	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
  	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
  	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
  	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.NullPointerException: t
  	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:799)
  	at io.grpc.Status.fromThrowable(Status.java:390)
  	at io.grpc.testing.integration.AbstractInteropTest.timeoutOnSleepingServer(AbstractInteropTest.java:1583)
  	... 30 more
```

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/e7a7ecf5-5ecc-4c8a-8cf2-72d0e3ebfc2b

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/9b53de9f-9ecd-4c1f-91e0-95c38f5e4c47/log
```
ERROR: (gcloud.app.deploy) Your deployment has succeeded, but promoting the new version to default failed. You may not have permissions to change traffic splits. Changing traffic splits requires the Owner, Editor, App Engine Admin, or App Engine Service Admin role. Please contact your project owner and use the `gcloud app services set-traffic --splits <version>=1` command to redirect traffic to your newly deployed version.
Original error: ABORTED: Cannot operate on apps/grpc-testing/services/java-gae-interop-test/versions/kokoro-gcp-ubuntu-prod-1079413535 because an operation is already in progress for d9ada564-3f8d-47c4-866c-58838775d637 by 9261b109-bcc9-4caf-97e4-fcf6a136932b.
```

**Comment by ericgribkoff** [comment]
https://source.cloud.google.com/results/invocations/19c0aa68-a35a-452a-b812-9cd84c55e580

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/120238d3-cba8-4f94-851f-e67ec886a316/log

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/2c80cfa9-9c98-431f-ba01-f4fb372236b1/log

**Comment by ejona86** [comment]
@carl-mastrangelo pointed out the recent failures are because a test is failing. You have to look closely at the output to notice. The root cause is specialStatusMessage is broken for grpc-test.sandbox.googleapis.com. I'll send out a PR to disable the test.

**Comment by ejona86** [comment]
Fixing with #4688

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/99936f6f-8ecd-4bcc-a60f-20b0633cd9fd/log

timeoutOnSleepingServer. jdk7

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/cfaf6146-d4d2-48e5-9ee4-dd403847630e/log

timeoutOnSleepingServer. jdk7

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/6f1a4cf0-c21a-4596-b8dc-e3a6687cd1bf/log

timeoutOnSleepingServer. jdk7

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/9daa4796-7197-4238-aba1-d872cb0e4edc/log

timeoutOnSleepingServer. jdk7

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/d0580b3a-b199-4a1c-a618-2a782dd173b4/log

timeoutOnSleepingServer. jdk7

**Comment by creamsoup** [comment]
https://source.cloud.google.com/results/invocations/7fd2793e-c63f-4272-9fdb-925d267c053e/log

timeoutOnSleepingServer. jdk7

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/7341d2ed-77a7-4fce-aa5f-8faf38be11d5/log

timeoutOnSleepingServer. jdk7

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/0e419b3a-5e24-4901-813a-93bbb75a81c7/log

timeoutOnSleepingServer. jdk7

**Comment by zpencer** [comment]
Looking at the GAE [server side logs](https://pantheon.corp.google.com/logs/viewer?src=ac&pli=1&project=grpc-testing&folder=&organizationId=433637338589&minLogLevel=0&expandAll=false&timestamp=2018-08-15T20:45:10.321000000Z&customFacets=&limitCustomFacetWidth=true&dateRangeEnd=2018-08-15T20:45:04.606Z&interval=PT1H&resource=gae_app%2Fmodule_id%2Fjava-gae-interop-test%2Fversion_id%2Fkokoro-gcp-ubuntu-prod-1613192288&dateRangeUnbound=backwardInTime&scrollTimestamp=2018-08-14T18:31:21.099574000Z&logName=projects%2Fgrpc-testing%2Flogs%2Fappengine.googleapis.com%252Frequest_log) for these invocations I see a lot of these errors:
```
io.grpc.internal.ChannelExecutor handleUncaughtThrowable: Runnable threw exception in ChannelExecutor (ChannelExecutor.java:105)
java.lang.IllegalStateException: Each request cannot exceed 50 active threads.
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThread.start(ApiProxyImpl.java:1168)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:972)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
	at io.grpc.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:427)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
	at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
	at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:246)
	at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:206)
	at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1432)
	at io.grpc.PickFirstBalancerFactory$PickFirstBalancer.handleResolvedAddressGroups(PickFirstBalancerFactory.java:74)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddressGroups(AutoConfiguredLoadBalancerFactory.java:106)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1300)
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:73)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:1234)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1304)
	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:605)
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThreadFactory$1$1.run(ApiProxyImpl.java:1235)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThreadFactory$1.run(ApiProxyImpl.java:1229)
	at java.lang.Thread.run(Thread.java:745)
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThread.run(ApiProxyImpl.java:1196)
```

On passing runs, I do not see these errors. Maybe once we hit the thread limit, the deadline task's scheduled executor stops functioning.

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/3bc6302a-b313-4298-96b4-80381468cd57/log

**Comment by ejona86** [comment]
I've tracked down a problem where failing Assumes were causing leaks. I'm going to send out a PR to fix it, but it may actually make the problem worse since previously there would be some thread-reuse. I'm questioning if the docs lie and we aren't limited to 50 "live" threads, but 50 "new" threads per request.

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/f3cbb041-d34e-4c4d-901f-75e040ae89e0/log

timeoutOnSleepingServer and deadlineExceeded

**Comment by ejona86** [comment]
In my own environment, I printed out the number of threads after each test:
```java
        sb.append(
            "active thread count: " + Thread.currentThread().getThreadGroup().activeCount() + "\n");
```

Normal operation has 4 at the end of `emptyUnary()` (the first test) and 5 at the end of each test after that. Even with that few of threads I still saw frequent failures of `timeoutOnSleepingServer()` (4 out of 5, and the 5th is the too-many-threads failure below). So that means `timeoutOnSleepingServer()` is failing for a different reason.

I also did see another case where the thread count increased each test:

```
Test invoked at: 
2018/08/17 19:43:40 +0000
FAILED! Tests ran 28, tests failed 12, tests ignored 0
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.emptyUnary() throws java.lang.Exception
active thread count: 6
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.largeUnary() throws java.lang.Exception
active thread count: 9
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.serverCompressedUnary() throws java.lang.Exception
active thread count: 12
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.serverStreaming() throws java.lang.Exception
active thread count: 16
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.clientStreaming() throws java.lang.Exception
active thread count: 20
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.pingPong() throws java.lang.Exception
active thread count: 24
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.emptyStream() throws java.lang.Exception
active thread count: 28
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.cancelAfterBegin() throws java.lang.Exception
active thread count: 31
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.cancelAfterFirstResponse() throws java.lang.Exception
active thread count: 35
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.fullDuplexCallShouldSucceed() throws java.lang.Exception
active thread count: 39
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.halfDuplexCallShouldSucceed() throws java.lang.Exception
active thread count: 43
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.serverStreamingShouldBeFlowControlled() throws java.lang.Exception
active thread count: 47
================
PASS: Test method: public void io.grpc.testing.integration.AbstractInteropTest.veryLargeRequest() throws java.lang.Exception
active thread count: 50
================
FAILED: Test method: public void io.grpc.testing.integration.AbstractInteropTest.deadlineNotExceeded()
active thread count: 51
java.lang.reflect.InvocationTargetException
        at com.google.appengine.runtime.Request.process-ad5bb7f7530d6b5a(Request.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:42)
        at io.grpc.testing.integration.OkHttpClientInteropServlet.doGetHelper(OkHttpClientInteropServlet.java:134)
        at io.grpc.testing.integration.OkHttpClientInteropServlet.doGet(OkHttpClientInteropServlet.java:87)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:455)
        at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:462)
        at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:320)
        at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:321)
        at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:313)
        at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:459)
        at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
        at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:622)
        at io.grpc.testing.integration.AbstractInteropTest.deadlineNotExceeded(AbstractInteropTest.java:1058)
        ... 31 more
Caused by: java.lang.IllegalStateException: Each request cannot exceed 50 active threads.
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:972)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
        at io.grpc.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:428)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
        at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:246)
        at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:206)
        at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1432)
        at io.grpc.PickFirstBalancerFactory$PickFirstBalancer.handleResolvedAddressGroups(PickFirstBalancerFactory.java:74)
        at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddressGroups(AutoConfiguredLoadBalancerFactory.java:106)
        at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1300)
        at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:73)
        at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:1234)
        at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1304)
        at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:247)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:605)
================

<snip. the rest fail>

Server side java.util.logging messages:
Aug 17, 2018 7:44:13 PM io.grpc.internal.ChannelExecutor handleUncaughtThrowable
WARNING: Runnable threw exception in ChannelExecutor
java.lang.IllegalStateException: Each request cannot exceed 50 active threads.
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:972)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
        at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
        at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
        at io.grpc.okhttp.OkHttpClientTransport.start(OkHttpClientTransport.java:428)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
        at io.grpc.internal.ForwardingConnectionClientTransport.start(ForwardingConnectionClientTransport.java:32)
        at io.grpc.internal.InternalSubchannel.startNewTransport(InternalSubchannel.java:246)
        at io.grpc.internal.InternalSubchannel.obtainActiveTransport(InternalSubchannel.java:206)
        at io.grpc.internal.ManagedChannelImpl$SubchannelImpl.requestConnection(ManagedChannelImpl.java:1432)
        at io.grpc.PickFirstBalancerFactory$PickFirstBalancer.handleResolvedAddressGroups(PickFirstBalancerFactory.java:74)
        at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddressGroups(AutoConfiguredLoadBalancerFactory.java:106)
        at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl$1NamesResolved.run(ManagedChannelImpl.java:1300)
        at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:73)
        at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.runSerialized(ManagedChannelImpl.java:1234)
        at io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl.onAddresses(ManagedChannelImpl.java:1304)
        at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:247)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1168)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:605)

<snip. more such errors>
```

**Comment by zpencer** [comment]
It seems like with a 0 timeout, that particular test seems reliable. I also tried with 10msec and the test is flakey.

**Comment by ejona86** [comment]
The test was disabled. We're not going to spend any more time on it, so closing.
