### ISSUE TITLE
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close

### ISSUE THREAD

**Issue by dingrui37** [grpc/grpc-java#4767]
### What version of gRPC are you using?
1.8.0

### What did you expect to see?
I created 100 clients on the same machine， then the client calls the bi-directional stream RPC 
just like the following pseudo-code.

```
while(true) {
    for(client:clients) {
        client.xxxx();
    }
}
```
It always gives a runtime exception on the server side after a period of time. I want to know what the problem is?

```
io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
        at io.grpc.Status.asRuntimeException(Status.java:517)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:272)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:281)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:679)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by zpencer** [comment]
What are you seeing is not indicative of a grpc bug by itself. The server is just reporting that the RPC was cancelled and that it never observed a half close from the client. A cancellation can happen for a variety of reasons (network error, deadline exceeded). Do you see any more clues on client side or server side about what might be causing the cancellations?

**Comment by dingrui37** [comment]
Thanks @zpencer, I think it is due to network reasons.
