### ISSUE TITLE
gae-interop jdk7 is flaky with "Each request cannot exceed 50 active threads."

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4784]
https://source.cloud.google.com/results/invocations/ee9dc173-9c21-4792-8f3a-f8e5b6b07ba5/log
```
Caused by: java.lang.IllegalStateException: Each request cannot exceed 50 active threads.
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:972)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1394)
	at io.grpc.internal.SerializingExecutor.schedule(SerializingExecutor.java:93)
	at io.grpc.internal.SerializingExecutor.execute(SerializingExecutor.java:86)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:588)
	at io.grpc.internal.FailingClientStream.start(FailingClientStream.java:54)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:273)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1.start(CensusTracingModule.java:398)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1.start(CensusStatsModule.java:673)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:308)
	at io.grpc.stub.ClientCalls.asyncStreamingRequestCall(ClientCalls.java:296)
	at io.grpc.stub.ClientCalls.asyncClientStreamingCall(ClientCalls.java:86)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceStub.streamingInputCall(TestServiceGrpc.java:550)
	at io.grpc.testing.integration.AbstractInteropTest.clientStreaming(AbstractInteropTest.java:567)
	... 31 more
```

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/5a5c6ec9-1c83-4d2e-aec7-99fae22d261b/log

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/466069ea-86d5-4d3c-a094-aa5a45c332de/log

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/3dbc89ed-aca9-4022-a820-37f71868daa4/log
