### ISSUE TITLE
OkHttp: INTERNAL: Flow control error Rst Stream

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4809]
Our android-interop test failed: https://source.cloud.google.com/results/invocations/ed2d6385-7608-437e-84ed-f8e34cdb35f7/log

```
junit.framework.ComparisonFailure: very_large_request failed expected:<[Failed... : INTERNAL: Flow control error
Rst Stream
io.grpc.StatusRuntimeException: INTERNAL: Flow control error
Rst Stream
  at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
  at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
  at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
  at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:624)
  at io.grpc.testing.integration.AbstractInteropTest.veryLargeRequest(AbstractInteropTest.java:959)
  at io.grpc.android.integrationtest.InteropTask.runTest(InteropTask.java:113)
  at io.grpc.android.integrationtest.InteropTask.doInBackground(InteropTask.java:62)
  at io.grpc.android.integrationtest.InteropTask.doInBackground(InteropTask.java:31)
  at android.os.AsyncTask$2.call(AsyncTask.java:305)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at java.lang.Thread.run(Thread.java:764)
]> but was:<[Success!]>
  at junit.framework.Assert.assertEquals(Assert.java:85)
  at io.grpc.android.integrationtest.InteropInstrumentationTest.runTest(InteropInstrumentationTest.java:134)
  at io.grpc.android.integrationtest.InteropInstrumentationTest.interopTests(InteropInstrumentationTest.java:99)
  at java.lang.reflect.Method.invoke(Native Method)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  snip
```

Note that the "expected" and "actual" appear reversed in the code, so ignore that "problem" in the message:
```
assertEquals(testCase + " failed", result, InteropTask.SUCCESS_MESSAGE);
```

"Flow control error" seems to be caused by a [ErrorCode.FLOW_CONTROL_ERROR](https://github.com/grpc/grpc-java/blob/30a4bfb2f0d1daf38d3b59e633f300b8edba9faf/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java#L116), via a RST_STREAM. That should never happen in proper operation. This seems highly likely a bug, somewhere. 

@ericgribkoff, what server are we using in this test?

**Comment by ericgribkoff** [comment]
These are using the `grpc-test.sandbox.googleapis.com` server, and running on Firebase emulators. I'll turn on more logging and try to reproduce the error to get some more information - the same emulator tests have been running internally for some time with no issues, albeit those spin up a local server instead of accessing the network.

**Comment by ericgribkoff** [comment]
Here are the relevant logs from a failure on the `very_large_request` test case:

```
08-28 20:15:04.582: I/GrpcInteropTask(6442): Running test case: very_large_request
08-28 20:15:04.605: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.internal.ManagedChannelImpl exitIdleMode
08-28 20:15:04.605: W/System.err(6442): FINE: [io.grpc.internal.ManagedChannelImpl-45] Exiting idle mode
08-28 20:15:04.606: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.internal.DnsNameResolver$1 run
08-28 20:15:04.606: W/System.err(6442): FINE: No TXT records found for grpc-test.sandbox.googleapis.com
08-28 20:15:04.606: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.internal.ManagedChannelImpl$NameResolverListenerImpl onAddresses
08-28 20:15:04.606: W/System.err(6442): FINE: [io.grpc.internal.ManagedChannelImpl-45] resolved address: [[addrs=[grpc-test.sandbox.googleapis.com/108.177.11.81:443], attrs={}]], config={}
08-28 20:15:04.606: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.internal.ManagedChannelImpl$LbHelperImpl createSubchannel
08-28 20:15:04.606: W/System.err(6442): FINE: [io.grpc.internal.ManagedChannelImpl-45] io.grpc.internal.InternalSubchannel-47 created for [[addrs=[grpc-test.sandbox.googleapis.com/108.177.11.81:443], attrs={}]]
08-28 20:15:04.607: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.internal.InternalSubchannel startNewTransport
08-28 20:15:04.607: W/System.err(6442): FINE: [io.grpc.internal.InternalSubchannel-47] Created io.grpc.okhttp.OkHttpClientTransport-48 for grpc-test.sandbox.googleapis.com/108.177.11.81:443
08-28 20:15:04.623: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer connectionPreface
08-28 20:15:04.623: W/System.err(6442): FINE: >> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
08-28 20:15:04.623: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.623: W/System.err(6442): FINE: >> 0x00000000     0 SETTINGS      
08-28 20:15:04.624: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.624: W/System.err(6442): FINE: << 0x00000000    18 SETTINGS      
08-28 20:15:04.624: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.internal.InternalSubchannel$TransportListener transportReady
08-28 20:15:04.624: W/System.err(6442): FINE: [io.grpc.internal.InternalSubchannel-47] io.grpc.okhttp.OkHttpClientTransport-48 for grpc-test.sandbox.googleapis.com/108.177.11.81:443 is ready
08-28 20:15:04.624: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.624: W/System.err(6442): FINE: << 0x00000000     4 WINDOW_UPDATE 
08-28 20:15:04.625: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.625: W/System.err(6442): FINE: << 0x00000000     0 SETTINGS      ACK
08-28 20:15:04.639: I/hwcomposer(1839): Sent 3606 syncs in 60s
08-28 20:15:04.704: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.704: W/System.err(6442): FINE: >> 0x00000000     0 SETTINGS      ACK
08-28 20:15:04.705: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.705: W/System.err(6442): FINE: >> 0x00000003   199 HEADERS       END_HEADERS
08-28 20:15:04.705: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.705: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.707: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.708: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.709: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.709: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.709: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.709: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.710: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.710: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.710: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.710: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.711: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.711: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.711: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.711: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.712: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.712: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.712: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.713: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.713: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.713: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.713: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.713: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.714: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.714: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.715: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.715: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.726: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.726: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.727: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.727: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.727: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.727: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.728: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.728: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.728: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.728: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.729: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.729: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.730: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.730: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.731: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.731: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.731: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.731: W/System.err(6442): FINE: << 0x00000000     4 WINDOW_UPDATE 
08-28 20:15:04.732: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.732: W/System.err(6442): FINE: << 0x00000000     6 SETTINGS      
08-28 20:15:04.734: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.734: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.734: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.734: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.735: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.735: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.735: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.735: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.736: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.736: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.736: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.736: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.737: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.737: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.737: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.737: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.740: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.740: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.741: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.741: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.741: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.741: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.742: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.742: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.742: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.742: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.743: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.743: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.743: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.743: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.744: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.744: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.744: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.744: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.745: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.745: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.745: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.745: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.746: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.746: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.746: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.746: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.747: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.747: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.747: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.747: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.748: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.748: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.748: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.748: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.750: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.750: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.751: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.752: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.752: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.752: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.752: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.752: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.753: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.753: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.753: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.753: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.755: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.755: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.756: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.756: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.757: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.757: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.757: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.757: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.758: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.758: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.758: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.758: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.759: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.759: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.760: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.760: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.761: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.761: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.761: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.761: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.762: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.762: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.762: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.762: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.763: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.763: W/System.err(6442): FINE: << 0x00000003     4 WINDOW_UPDATE 
08-28 20:15:04.765: I/Remoter(1828): Saved screenshot to '/data/screenshots/__pmv__-0108.jpg'
08-28 20:15:04.765: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.765: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.766: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Writer frameHeader
08-28 20:15:04.766: W/System.err(6442): FINE: >> 0x00000003 16384 DATA          
08-28 20:15:04.766: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.766: W/System.err(6442): FINE: << 0x00000003     4 RST_STREAM    
08-28 20:15:04.766: W/System.err(6442): Aug 28, 2018 8:15:04 PM io.grpc.okhttp.internal.framed.Http2$Reader nextFrame
08-28 20:15:04.766: W/System.err(6442): FINE: << 0x00000003     4 WINDOW_UPDATE 
08-28 20:15:04.767: W/System.err(6442): io.grpc.StatusRuntimeException: INTERNAL: Flow control error
08-28 20:15:04.767: W/System.err(6442): Rst Stream
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:624)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.testing.integration.AbstractInteropTest.veryLargeRequest(AbstractInteropTest.java:949)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.android.integrationtest.InteropTask.runTest(InteropTask.java:113)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.android.integrationtest.InteropTask.doInBackground(InteropTask.java:62)
08-28 20:15:04.767: W/System.err(6442): 	at io.grpc.android.integrationtest.InteropTask.doInBackground(InteropTask.java:31)
08-28 20:15:04.767: W/System.err(6442): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-28 20:15:04.767: W/System.err(6442): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-28 20:15:04.767: W/System.err(6442): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
08-28 20:15:04.767: W/System.err(6442): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-28 20:15:04.767: W/System.err(6442): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-28 20:15:04.767: W/System.err(6442): 	at java.lang.Thread.run(Thread.java:818)
```

`AbstractInteropTest#veryLargeRequest()` only actually sends an RPC on a device with [enough available memory](https://github.com/grpc/grpc-java/blob/fd73209e0c2bdfc6dc454825ba281b9c8039ce99/interop-testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.java#L945). It looks like the Nexus 6 emulator on Firebase *has* enough memory and so the test runs, and hits this error. I believe that we were not running this test (other than in our own gradle test runs, so not with an external server process and not on Android) with the OkHttp transport previously: this test case is apparently not included in those run by [`run_interop_tests.py`](https://github.com/grpc/grpc/blob/ceecf80283e6ca184df587f76ed053f1f5295b7f/tools/run_tests/run_interop_tests.py#L606) over in grpc/grpc (actually, I guess it's not even an "official" test case from https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md), and the emulator images we use to test with OkHttp on Android internally do not have sufficient memory and this test gets skipped.

I will see if I can replicate the error outside of an Android environment by running our interop client with OkHttp against the grpc-test.sandbox.googleapis.com server.

**Comment by ericgribkoff** [comment]
It's reproducible on my desktop (modified the interop client to include the very_large_request test case). Netty seems to work reliably, but using OkHttp fails roughly one-half of the time. 

I don't think there's enough info in the log output to determine/verify if the client is violating flow control protocol; working on better log output to help identify the cause of the failure.

**Comment by ejona86** [comment]
Running against a local server is a different server. When using sandbox we're hitting GFE.

**Comment by ericgribkoff** [comment]
With #4816 patched in, this can be reproduced reliably (>=50% of runs) with the following command, which also configures verbose logging:

```
JAVA_OPTS=-Djava.util.logging.config.file=logging.properties \
JAVA_HOME=<path_to_jdk_compatible_with_jetty_alpn> \
build/install/grpc-interop-testing/bin/test-client \
    --server_host=grpc-test.sandbox.googleapis.com \
    --server_port=443 \
    --use_okhttp=true \
    --test_case=very_large_request
```

Where `logging.properties` is a file containing:

```
handlers=java.util.logging.ConsoleHandler
io.grpc.level=FINE
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
```

The following patch to OkHttp will also log the value of the inbound window update, something currently missing (modifying OkHttp's logging cleanly to include this information probably needs a bit of thought, this was just quickly put together for debugging):

```
diff --git a/okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Http2.java b/okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Http2.java
index 20eed3c3b..540538038 100644
--- a/okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Http2.java
+++ b/okhttp/third_party/okhttp/main/java/io/grpc/okhttp/internal/framed/Http2.java
@@ -358,6 +358,9 @@ public final class Http2 implements Variant {
       if (length != 4) throw ioException("TYPE_WINDOW_UPDATE length !=4: %s", length);
       long increment = (source.readInt() & 0x7fffffffL);
       if (increment == 0) throw ioException("windowSizeIncrement was 0", increment);
+      if (logger.isLoggable(FINE)) {
+        logger.fine(format("<< 0x%08x windowSizeIncrement: %d", streamId, increment));
+      }
       handler.windowUpdate(streamId, increment);
     }
```
