### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.

### ISSUE THREAD

**Issue by tripathysa** [grpc/grpc-java#4850]
I am trying to use grpc Java to use a service.

Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.1.2

### What did you expect to see?
Successful connection via grpc 

Full Error log:

```
Exception in thread "main" java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:159)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
	at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
	at com.ibm.watson.sentimentanalysis.fe.service.pipeline.customization.TestGrpcTrain.getSslContext(TestGrpcTrain.java:158)
	at com.ibm.watson.sentimentanalysis.fe.service.pipeline.customization.TestGrpcTrain.main(TestGrpcTrain.java:143)
```
at this line in my java grpc client code:

```
public static SslContext getSslContext(File certFile) throws SSLException {
        return GrpcSslContexts.forClient()
                .trustManager(certFile)
                .build();
    }
```

Java Version: 1.8
Gradle dependencies: 
```
dependencies {

    //GRPC
    compile 'io.grpc:grpc-netty:1.1.2'
    compile 'io.grpc:grpc-protobuf:1.1.2'
    compile 'io.grpc:grpc-stub:1.1.2'
    compile 'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork26'
```
Here's my gradle dependency tree:
https://gist.github.com/tripathysa/7966ddb1e3c6751c19e7b9777a5a0419

Tried the troubleshooting guide: Used the same combination of 

grpc-netty version | netty-handler version | netty-tcnative-boringssl-static version as mentioned here:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#troubleshooting

But still getting the error. Any help would be appreciated.

**Comment by dapengzhang0** [comment]
The line numbers in the stack trace
```
at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
```

do not match the v1.1.2 source file
https://github.com/grpc/grpc-java/blob/v1.1.2/netty/src/main/java/io/grpc/netty/GrpcSslContexts.java#L94

Can you please double check it is executing `io.grpc:grpc-netty:1.1.2` in the runtime?
