### ISSUE TITLE
NettyServer awaitTermination() returns before the shared EventLoopGroups are released

### ISSUE THREAD

**Issue by Hithran** [grpc/grpc-java#4893]
### What version of gRPC are you using?
1.12

### What did you expect to see?
Expected to not see the NoClassDefFoundErrors because of a closed classloader after the call to awaitTermination returned.

In our application we load jars using the URLClassloader that communicate using gRPC and the NettyServer. When the module needs to be unloaded we block on the _[awaitTermination](https://github.com/grpc/grpc-java/blob/v1.12.0/core/src/main/java/io/grpc/Server.java#L136)_ before closing the URLClassLoader.
The logs are filled with NoClassDefFoundErrors on various classes after the classloader was closed.
This is caused by the NettyServer implementation calling _[eventLoopReferenceCounter.release()](https://github.com/grpc/grpc-java/blob/v1.12.0/netty/src/main/java/io/grpc/netty/NettyServer.java#L289)_ after the ServerListener has been notified through _[listener.serverShutdown()](https://github.com/grpc/grpc-java/blob/v1.12.0/netty/src/main/java/io/grpc/netty/NettyServer.java#L287)_ (which in turn causes _awaitTermination_ to return) .

The NoClassDefFoundErrors do not cause any problems, but I would like to prevent them from piling up in the log files, making it harder to spot any real problems.
In short I would like to know if there is a way to determine I can close the classloader without causing the NoClassDefFoundErrors appearing in the log files.

Example of exceptions raised:
```[grpc-default-boss-ELG-1-1] WARN  i.n.util.concurrent.DefaultPromise --- An exception was thrown by io.grpc.netty.NettyServer$3.operationComplete()
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ThreadFactoryBuilder
	at io.grpc.internal.GrpcUtil.getThreadFactory(GrpcUtil.java:558)
	at io.grpc.internal.SharedResourceHolder$1.createScheduledExecutor(SharedResourceHolder.java:51)
	at io.grpc.internal.SharedResourceHolder.releaseInternal(SharedResourceHolder.java:137)
	at io.grpc.internal.SharedResourceHolder.release(SharedResourceHolder.java:92)
	at io.grpc.netty.NettyServer$EventLoopReferenceCounter.deallocate(NettyServer.java:327)
	at io.netty.util.AbstractReferenceCounted.release0(AbstractReferenceCounted.java:82)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:71)
	at io.grpc.netty.NettyServer$3.operationComplete(NettyServer.java:289)
	at io.grpc.netty.NettyServer$3.operationComplete(NettyServer.java:276)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

[grpc-default-boss-ELG-1-1] WARN  i.n.util.concurrent.DefaultPromise --- An exception was thrown by io.grpc.netty.NettyServer$3.operationComplete()
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/ThreadFactoryBuilder$1
	at com.google.common.util.concurrent.ThreadFactoryBuilder.build(ThreadFactoryBuilder.java:159)
	at com.google.common.util.concurrent.ThreadFactoryBuilder.build(ThreadFactoryBuilder.java:146)
	at io.grpc.internal.GrpcUtil.getThreadFactory(GrpcUtil.java:561)
	at io.grpc.internal.SharedResourceHolder$1.createScheduledExecutor(SharedResourceHolder.java:51)
	at io.grpc.internal.SharedResourceHolder.releaseInternal(SharedResourceHolder.java:137)
	at io.grpc.internal.SharedResourceHolder.release(SharedResourceHolder.java:92)
	at io.grpc.netty.NettyServer$EventLoopReferenceCounter.deallocate(NettyServer.java:327)
	at io.netty.util.AbstractReferenceCounted.release0(AbstractReferenceCounted.java:82)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:71)
	at io.grpc.netty.NettyServer$3.operationComplete(NettyServer.java:289)
	at io.grpc.netty.NettyServer$3.operationComplete(NettyServer.java:276)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by carl-mastrangelo** [comment]
The EventLoopGroups may be used by other NettyServer's in your program, (we don't know), so we can't really shut them down.    Also, we can't shut them down while the Server is not shut down (even if it is in the process), because they may still be executing.

I suggest providing your own ELGs to the server, and shut them down after the server is shutdown, but before releasing the class loader.

**Comment by carl-mastrangelo** [comment]
@Hithran The gRPC ELG is hidden, but it is always `null` unless you set it.   By default Netty will create a default (see ServerBootstrap in the netty project).   

As for Dos and Don'ts, The important thing is to not shut them down before the gRPC server has shut down.  For example, timers still execute while the server is in the process of shutting down.  Also, you need to set the ELG based on the channel type, though I think netty prevents you from mixing EpollEventLoopGroup with NioSocketChannel, for instance.  The same applies for building a ManagedChannel.

Generally speaking, gRPC does most of the work on the `Executor` passed in to the server rather than the ELG.   Because of this, Netty's default of a thread count of 2x #cores is usually too high.  I have been experimenting with bringing it down to 1 or 2 threads max.   Lastly, it is almost always a good idea to make both the Worker and boss the same ELG.

**Comment by Hithran** [comment]
Thank you for the insights, providing the ELG solved the NoClassDefFoundErrors 😄
