### ISSUE TITLE
DnsNameResolverTest is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#4998]
https://source.cloud.google.com/results/invocations/8a2a2e6e-ca37-4948-b8c8-9abf4452da44/log (macos)

```
io.grpc.internal.DnsNameResolverTest > resolve_cacheExpired FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainDatagramSocketImpl.peekData(Native Method)
        at java.net.DatagramSocket.receive(DatagramSocket.java:787)
        at com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:418)
        at com.sun.jndi.dns.DnsClient.query(DnsClient.java:208)
        at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
        at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
        at com.sun.jndi.toolkit.url.GenericURLDirContext.getAttributes(GenericURLDirContext.java:103)
        at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
        at io.grpc.internal.JndiResourceResolverFactory$JndiResourceResolver.getAllRecords(JndiResourceResolverFactory.java:211)
        at io.grpc.internal.JndiResourceResolverFactory$JndiResourceResolver.resolveSrv(JndiResourceResolverFactory.java:135)
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:375)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:269)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225)
        at io.grpc.internal.FakeClock.runDueTasks(FakeClock.java:224)
        at io.grpc.internal.DnsNameResolverTest.resolve_cacheExpired(DnsNameResolverTest.java:377)
```

CC @creamsoup

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/19869a2a-a441-4550-8e61-36f3bed6cf8e/log
```
io.grpc.internal.DnsNameResolverTest > resolve_noPropertyValue FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainDatagramSocketImpl.peekData(Native Method)
        at java.net.DatagramSocket.receive(DatagramSocket.java:787)
        at com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:418)
        at com.sun.jndi.dns.DnsClient.query(DnsClient.java:208)
        at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
        at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
        at com.sun.jndi.toolkit.url.GenericURLDirContext.getAttributes(GenericURLDirContext.java:103)
        at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
        at io.grpc.internal.JndiResourceResolverFactory$JndiResourceResolver.getAllRecords(JndiResourceResolverFactory.java:211)
        at io.grpc.internal.JndiResourceResolverFactory$JndiResourceResolver.resolveSrv(JndiResourceResolverFactory.java:135)
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:375)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:269)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:225)
        at io.grpc.internal.FakeClock.runDueTasks(FakeClock.java:248)
        at io.grpc.internal.DnsNameResolverTest.resolveDefaultValue(DnsNameResolverTest.java:412)
        at io.grpc.internal.DnsNameResolverTest.resolve_noPropertyValue(DnsNameResolverTest.java:396)
```

**Comment by creamsoup** [comment]
https://source.cloud.google.com/results/invocations/fed93e1c-3b55-4bf4-b74f-7dc1ab1ef8d4/log (macos)
```
io.grpc.internal.DnsNameResolverTest > resolveAll_failsOnEmptyResult FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.net.PlainDatagramSocketImpl.peekData(Native Method)
        at java.net.DatagramSocket.receive(DatagramSocket.java:787)
        at com.sun.jndi.dns.DnsClient.doUdpQuery(DnsClient.java:418)
        at com.sun.jndi.dns.DnsClient.query(DnsClient.java:208)
        at com.sun.jndi.dns.Resolver.query(Resolver.java:81)
        at com.sun.jndi.dns.DnsContext.c_getAttributes(DnsContext.java:434)
        at com.sun.jndi.toolkit.ctx.ComponentDirContext.p_getAttributes(ComponentDirContext.java:235)
        at com.sun.jndi.toolkit.ctx.PartialCompositeDirContext.getAttributes(PartialCompositeDirContext.java:141)
        at com.sun.jndi.toolkit.url.GenericURLDirContext.getAttributes(GenericURLDirContext.java:103)
        at javax.naming.directory.InitialDirContext.getAttributes(InitialDirContext.java:142)
        at io.grpc.internal.JndiResourceResolverFactory$JndiRecordFetcher.getAllRecords(JndiResourceResolverFactory.java:261)
        at io.grpc.internal.JndiResourceResolverFactory$JndiResourceResolver.resolveSrv(JndiResourceResolverFactory.java:144)
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:375)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:269)
        at io.grpc.internal.DnsNameResolverTest.resolveAll_failsOnEmptyResult(DnsNameResolverTest.java:277)
```

**Comment by ejona86** [comment]
Can maybe use the testing `RecordFetcher` interface I added in #5006 to avoid the I/O in these tests.
