### ISSUE TITLE
Netty throws exception when creating > 1 TLS transport.

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#504]
When attempting to create multiple TLS transports from the same builder, Netty throws an exception:

```
io.netty.channel.ChannelPipelineException: io.grpc.transport.netty.ProtocolNegotiators$SslBootstrapHandler is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:564)
	at io.netty.channel.DefaultChannelPipeline.addFirst0(DefaultChannelPipeline.java:114)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:108)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:291)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:246)
	at io.grpc.transport.netty.ProtocolNegotiators$AbstractBufferingHandler.channelRegistered(ProtocolNegotiators.java:192)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelRegisteredNow(ChannelHandlerInvokerUtil.java:32)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRegistered(DefaultChannelHandlerInvoker.java:50)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:114)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:833)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:487)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:401)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment]
@nmittler and I agree, the fix for this issue is important enough to backport to 0.7

**Comment by nmittler** [comment]
I have a fix pending ... stay tuned.

**Comment by ejona86** [comment]
It seems this bug is not as easy to trigger as it originally seemed. Creating more than one transport does work, but if the previous transport failed before negotiation completed then the exception seems possible.

A bigger issue it seems is that some failures that occur before negotiation completes may not be handled.
