### ISSUE TITLE
Proxy settings when TLS is disabled

### ISSUE THREAD

**Issue by idelvall** [grpc/grpc-java#5097]
### What version of gRPC are you using?
1.13.1

### What did you expect to see?
I was testing a GRPC client over a plain transport (no TLS enabled), and I did expect this test https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java#L110 to work if using `http.proxyHost` and `http.proxyPort` instead of their secure counterparts (`https.*`).

but I got this error :
```
 io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
<< 	at io.grpc.Status.asRuntimeException(Status.java:526)
<< 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420)
<< 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
<< 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
<< 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
<< 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
<< 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
<< 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
<< 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
<< 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
<< 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
<< 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
<< 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
<< 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
<< 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
<< 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
<< 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
<< 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<< 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<< 	at java.lang.Thread.run(Thread.java:748)

```

This line here makes me doubt this is even possible: https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ProxyDetectorImpl.java#L161

Thanks in advance

**Comment by idelvall** [comment]
Seems like my direct TLS connection is indeed the one failing. Sorry

**Comment by carl-mastrangelo** [comment]
Adding @ejona86 whom I overheard talking about this recently.

**Comment by ejona86** [comment]
So... the short answer is "use the https variable".

Is this impacting you negatively? Do you need gRPC to use the plain-text configuration? Could you explain why? (We know the protocols, but have less experience with all the uses/expectations for proxying.)

Things are a bit confusing because plain text HTTP uses a different proxy protocol than HTTPS. With plain-text HTTP proxying, the proxy is speaking HTTP/1 directly for caching and other goo. HTTPS proxying uses HTTP CONNECT (via a brief HTTP/1 exchange) to "punch a hole" through the proxy and then talks TLS through the connection.

gRPC only supports using HTTP CONNECT; it does not support the classic plain-text HTTP proxying protocol via HTTP/1. Even with plain-text gRPC. Because of that, we always use the HTTPS settings, because we know the HTTPS proxy supports HTTP CONNECT; plain-text HTTP servers don't need to support HTTP CONNECT.

So using the https configuration is "wrong" for plain-text gRPC, but using the http configuration would also be "wrong." The only "right" way is to go through a proxy with plain-text HTTP is to use HTTP/1, which isn't really acceptable to us.

**Comment by ejona86** [comment]
Ah, okay. Yeah, you can document only https.proxyHost/Port is supported, but that it works for both plain-text and TLS gRPC.
