### ISSUE TITLE
Unable to load LoadBalancerProvider in the runtime for Bazel apps

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#5114]
### What version of gRPC are you using?
v1.17.0

Bazel apps if not having a (transparent) dependency for `@io_grpc_grpc_java//core:util` will fail with the following error in the runtime:

```
Exception in thread "main" java.util.ServiceConfigurationError: io.grpc.LoadBalancerProvider: Provider io.grpc.util.SecretRoundRobinLoadBalancerProvider$Provider not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
        at io.grpc.LoadBalancerRegistry.getDefaultRegistry(LoadBalancerRegistry.java:102)
        at io.grpc.internal.AutoConfiguredLoadBalancerFactory.<clinit>(AutoConfiguredLoadBalancerFactory.java:42)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:534)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:428)
        at io.grpc.examples.helloworld.HelloWorldClient.<init>(HelloWorldClient.java:41)
        at io.grpc.examples.helloworld.HelloWorldClient.main(HelloWorldClient.java:73)
```

A temporary workaround is adding a runtime dependency in the BUILD file
```
runtime_deps = [
        "@io_grpc_grpc_java//core:util",
    ],
```

**Comment by dapengzhang0** [comment]
cc @zhangkun83
