### ISSUE TITLE
 Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by harini2191** [grpc/grpc-java#5224]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
    //  GRPC dependencies
    implementation 'io.grpc:grpc-okhttp:1.0.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.0.0'
    implementation 'io.grpc:grpc-stub:1.0.0'
    implementation 'javax.annotation:javax.annotation-api:1.2'

### What did you expect to see?
**Getting the following Error:**

 **io.grpc.StatusRuntimeException: UNAVAILABLE**
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
        at io.grpc.examples.helloworld.EchoServiceGrpc$EchoServiceBlockingStub.echo(EchoServiceGrpc.java:135)
        at example.com.grpc_jav_sample.MstSampleActivity$GrpcTask.doInBackground(MstSampleActivity.java:87)
        at example.com.grpc_jav_sample.MstSampleActivity$GrpcTask.doInBackground(MstSampleActivity.java:66)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     **Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:286)**
        at io.grpc.okhttp.OkHttpProtocolNegotiator.negotiate(OkHttpProtocolNegotiator.java:106)
        at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:172)
        at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:74)
        at io.grpc.okhttp.OkHttpClientTransport$1.run(OkHttpClientTransport.java:400)
        at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     **Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x71fb794d88: Failure in SSL library, usually a protocol error**
    **error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER** (external/boringssl/src/ssl/tls_record.cc:242 0x7207777e07:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)

**My app.gradle is:**

apply plugin: 'com.android.application'
apply plugin: 'com.google.protobuf'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "example.com.grpc_jav_sample"
        minSdkVersion 15
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.4.0'
    }
    plugins {
        javalite {
            artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0"
        }
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.0.1'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc {
                    // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
}

/*protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.0.0'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.0.0-pre2'
        }
        javalite {
            artifact = 'com.google.protobuf:protoc-gen-javalite:3.0.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            javalite {}
        }
        ofNonTest()*.plugins {
            grpc {
                // Options added to --grpc_out
                option 'lite'
            }
        }
    }
}*/

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    // implementation files('libs/protobuf-java-3.6.1.jar')
    //  GRPC dependencies
    implementation 'io.grpc:grpc-okhttp:1.0.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.0.0'
    implementation 'io.grpc:grpc-stub:1.0.0'
    implementation 'javax.annotation:javax.annotation-api:1.2'
   // implementation files('libs/protobuf-java-3.6.1.jar')
    //  dialog library
    implementation 'com.github.d-max:spots-dialog:0.7@aar'
   implementation 'com.google.api.grpc:googleapis-common-protos:0.0.3'
   // protobuf 'com.google.protobuf:protobuf-java:3.6.1'
   // # https://mvnrepository.com/artifact/com.google.protobuf/protobuf-lite

}
configurations {
    compile.exclude group: 'com.google.protobuf', module: 'protobuf-lite'
}

**Comment by ejona86** [comment]
We need to know more about how the channel and server were constructed. However, based on https://github.com/envoyproxy/envoy/issues/2168 it sounds like this error happens when the server is plaintext while the client is using TLS.
