### ISSUE TITLE
NullPointerExceptions: okio.Sink.write() and okio.Sink.close()

### ISSUE THREAD

**Issue by bubenheimer** [grpc/grpc-java#5256]
### What version of gRPC are you using?
1.18.0

I am seeing some exceptions in the client logs on Android when I try to connect to a server that's down. The exceptions show repeated attempts to write to a sink and close it, even though the sink does not exist. Maybe related to the recent buffering refactors? The channel state cycles between `CONNECTING` and `TRANSIENT_FAILURE`, and every time it gets to `TRANSIENT_FAILURE` this set of exceptions occurs. I don't see an impact on my process, so if it's not a real problem then those exceptions may need to be swallowed somewhere.

```
E/SerializingExecutor: Exception while executing runnable io.grpc.okhttp.AsyncSink$2@a83c985
        java.lang.NullPointerException: Attempt to invoke interface method 'void okio.Sink.write(okio.Buffer, long)' on a null object reference
            at io.grpc.okhttp.AsyncSink$2.run(AsyncSink.java:125)
            at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at java.lang.Thread.run(Thread.java:764)
E/SerializingExecutor: Exception while executing runnable io.grpc.okhttp.AsyncSink$3@b4dc00b
        java.lang.NullPointerException: Attempt to invoke interface method 'void okio.Sink.close()' on a null object reference
            at io.grpc.okhttp.AsyncSink$3.run(AsyncSink.java:150)
            at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
            at java.lang.Thread.run(Thread.java:764)
```

**Comment by creamsoup** [comment]
thanks for reporting this issue. it wasn't handle the connection error correctly. it shouldn't affect functionality other than spamming the log though.
