### ISSUE TITLE
gRPC appengine executor hangs on async call

### ISSUE THREAD

**Issue by arunthirupathi** [grpc/grpc-java#5286]
### What version of gRPC are you using?
1.17.1

### What did you expect to see?
I am using gRPC client in the appengine standard java8 runtime. I want to supply appengine thread factory for the async calls. But when I specify that gRPC call hangs. I created an appengine servlet which does this and the servlet never returns any response. AppEngine logs does not show this request either.

When I specify, a normal executor the async call works. I can see the request in the appengine logs. It seems like gRPC is doing some operation that is not allowed on the appengine thread which causes it to crash. 

```
 getFutureStub()
                        .withExecutor(Executors.newCachedThreadPool()) // this works as expected
```

But when I specify an AppEngine specific thread factory, the gRPC call hangs. 
```
getFutureStub()                     
        .withExecutor(Executors.newCachedThreadPool(ThreadManager.currentRequestThreadFactory())) // this hangs , though there is a deadline specified on the call.
```

In https://github.com/grpc/grpc-java/pull/3382 @ejona86 Mentioned that appengine executor can be specified to do appengine specific calls. But that does not work. Are there tests to cover this use case ?

I started this thread https://groups.google.com/forum/#!topic/grpc-io/HVBx6Ef7y4g on discussion group, but after spending more time, I believe the issue is caused by this bug.

**Comment by ejona86** [comment]
Are you returning from your request? The currentRequestThreadFactory() only works while the request is in progress.

So I wouldn't be surprised if this works:
```
Future<?> future = getFutureStub()
        .withExecutor(Executors.newCachedThreadPool(ThreadManager.currentRequestThreadFactory()))
        .fooCall(fooRequest);
future.get(); // this being the important line
```

If that works but removing the `future.get()` breaks, then that means that the current request scope is killed before the response is received. Essentially, you either have to use a background thread or keep the request alive.

**Comment by arunthirupathi** [comment]
Request thread is waiting for the response from the gRPC. So that can't be the issue. I suspect gRPC is doing some operation that is not permitted on the sandboxed thread. I also opened up a google support case with appengine team. (It is under my company and not everyone will have access to it). I will see what the support says.

For example, in Java7 appengine thread pool waiting for shutdown never completes. It could be one of the weird google appengine thread limitations. I am not sure what limitation appengine has on java8 threads/pools.

**Comment by ejona86** [comment]
The problem may be that since `newCachedThreadPool()` creates threads lazily grpc is triggering thread creation from the Event Loop. But `currentRequestThreadFactory()` can only create new threads while on a request thread (as otherwise it may not know which request to create it for). This is in the documentation:
```
java.lang.NullPointerException - if the calling thread is not associated with a request.
```

As an experiment, try:
```
ThreadPoolExecutor executor = new ThreadPoolExecutor(
    1, 1, 0, TimeUnit.SECONDS, new LinkedBlockingQueue<Runnable>(),
    ThreadManager.currentRequestThreadFactory());
executor.prestartAllCoreThreads();
getFutureStub()                     
        .withExecutor(executor)
        ...;
```

**Comment by arunthirupathi** [comment]
I see, completely makes sense. Let me create threads and pass in to it to see if that solves the problems.

**Comment by arunthirupathi** [comment]
Also when the thread creation fails, can the gRPC gracefully fail the request, instead of hanging the request ? The scenario will be easy to generate with a mocked ThreadPoolExecutor which throws NPE.

**Comment by arunthirupathi** [comment]
I can confirm that was indeed the issue. Thanks @ejona86 for your help. Really appreciate that. Spent a week chasing around this issue. An exception on the future would have made it easier to troubleshoot.

**Comment by ejona86** [comment]
gRPC should already be logging an error/warning when the NPE occurs. But App Engine is apparently making that hard to see.

The problem is how does gRPC notify the application of the failed RPC? It has no thread to do it on... There was the idea we could have a secondary executor, say `fallbackExecutor()`, which we would only use to notify the application of killed RPCs in the case the normal executor failed. Although a NPE is a bit of a hard case, because we won't be 100% sure that our Runnable will never run.

**Comment by arunthirupathi** [comment]
I am specifying the per async request, executor now. Create an executor per call and shut down after the response is received. But from time to time, I see the RejectedExecutionException on the sync all.

I have created the sync and async stub from the same channel. ( I have abstracted away the application code path for now, but can give a full stack in the private message if that is required).

```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at com.ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at ApplicationSpecificCallStack.........
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.ServletScopes$3.call(ServletScopes.java:232)
	at ApplicationSpecificCallStack.........
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThreadFactory$1$1.run(ApiProxyImpl.java:1233)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThreadFactory$1.run(ApiProxyImpl.java:1227)
	at java.lang.Thread.run(Thread.java:748)
	at com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThread.run(ApiProxyImpl.java:1194)
Caused by: java.util.concurrent.RejectedExecutionException: Task io.grpc.internal.DelayedClientTransport$5@2cd8639a rejected from java.util.concurrent.ThreadPoolExecutor@b90e5ce[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:302)
	at io.grpc.internal.ManagedChannelImpl.updateSubchannelPicker(ManagedChannelImpl.java:742)
	at io.grpc.internal.ManagedChannelImpl.access$5200(ManagedChannelImpl.java:97)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1UpdateBalancingState.run(ManagedChannelImpl.java:1113)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:101)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportReady(InternalSubchannel.java:574)
	at io.grpc.netty.ClientTransportLifecycleManager.notifyReady(ClientTransportLifecycleManager.java:43)
	at io.grpc.netty.NettyClientHandler$FrameListener.onSettingsRead(NettyClientHandler.java:759)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:419)at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:637)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onSettingsRead(Http2InboundFrameLogger.java:93)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame(DefaultHttp2FrameReader.java:542)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:263)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:390)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:254)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1429)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Please let me know if you think it is a bug. It is happening at 0.001% of the times, so not happening often but not sure why the sync call is looking for an executor that is used in the async code path.

Javdoc seems to be indicating this should not be the case.
https://grpc.io/grpc-java/javadoc/io/grpc/CallOptions.html#withExecutor-java.util.concurrent.Executor-

**Comment by ejona86** [comment]
@arunthirupathi, panic mode applies to the channel; if the channel has a panic, all future RPCs should fail. Blocking stubs don't use the Channel's Executor. Instead, they use the calling thread's executor.

What's probably happening is you are closing the executor while it is still being used. You are probably closing it after `onNext()`, but you should wait until `onCompleted()`.

**Comment by ejona86** [comment]
When the channel panics it saves the exception that caused the panic and fails all future calls, with the panic exception in the cause. This makes it much easier to see the original cause of failure.

Hmmm... That future code looks fine. Are you sure that _all_ RPCs using `executor` are complete when that future is complete?

**Comment by arunthirupathi** [comment]
Both sync and async sends one request and receives one response from the server.

But from what you say, it is plausible that if the gRPC futures are created during onNext and onCompleted happens later, there is a race condition.

Other thing, I find interesting is, all of the call stacks had `io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame` method.  If that is general message that is not tied to a request/response, trying to use the executor specified for a call will fail.

Do you think moving it to a scheduled thread pool executor and scheduling shutdown may be after a second will do it

**Comment by arunthirupathi** [comment]
One other case I forgot to mention is, when the client does not receive a response within deadline ( 10 seconds), the client shutsdown the executor to prevent the executor leak. 

In AppEngine a response can't be send until the executor is shutdown. Could this cause the channel to panic ?

**Comment by ejona86** [comment]
Do you create a new Channel each request? It's possible the failure is coming from a previous request. However, I do agree it is weird that sync is broken but async isn't.

So the readSettingsFrame method is when we determine that the connection is good. That eventually triggers DelayedClientTransport.reprocess which is [trying to start the call](https://github.com/grpc/grpc-java/blob/v1.17.1/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L302). To start the call we jump back to the application's executor to do some work like serializing the request message.

> One other case I forgot to mention is, when the client does not receive a response within deadline ( 10 seconds), the client shutsdown the executor to prevent the executor leak.

Ah, that's the problem. You need to cancel the RPC (and wait for the RPC to be cancelled; it'll be fast) before shutting down the executor. Easiest way to do that is to specify the deadline on the RPC itself via `stub.withDeadlineAfter(10, TimeUnit.SECONDS)`. gRPC will cancel after the deadline, and then the call will have "completed" for your cleanup of the executor.

**Comment by arunthirupathi** [comment]
The channel is created once and two stubs (sync and async) are created from the same channel. Sync stub for each calls specifies an interceptor. Async stub for each call, creates an executor starts all the thread and specifies this executor and interceptor. The interceptor writes the result to the Memcache.

 >So the readSettingsFrame method is when we determine that the connection is good. That eventually triggers DelayedClientTransport.reprocess which is [trying to start the call](https://github.com/grpc/grpc-java/blob/v1.17.1/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L302). To start the call we jump back to the application's executor to do some work like serializing the request message.

Does the sync request, tries to use the executor specified in the async call ? Sync stub does not specify any executor.

> You need to cancel the RPC (and wait for the RPC to be cancelled; it'll be fast) before shutting down the executor. Easiest way to do that is to specify the deadline on the RPC itself via `stub.withDeadlineAfter(10, TimeUnit.SECONDS)`

Current code specifies the deadline on both sync and async stubs. For the async stub, the shutdown is handled in the following way.

```
Futures.get(asyncFuture, 10, TimeUnit.Seconds);
executor.shutdown();
```

So theoretically there is a race condition that cancel and the shutdown might be racing. I can try increasing the timeout to Futures.get to 11 seconds to wait for the future to fail/cancelled before shutting down the executor. But I had the same error when I had Future.get() without any timeout as well. So don't think that will help.

**Comment by ejona86** [comment]
> Does the sync request, tries to use the executor specified in the async call ? Sync stub does not specify any executor.

No, it [uses the current thread](https://github.com/grpc/grpc-java/blob/v1.17.1/stub/src/main/java/io/grpc/stub/ClientCalls.java#L124-L125).

> I can try increasing the timeout to Futures.get to 11 seconds to wait for the future to fail/cancelled before shutting down the executor. But I had the same error when I had Future.get() without any timeout as well.

Using Future.get() should have worked with my theory. Waiting for 10 seconds has obvious limits though, so at the very least use an increased deadline there.

The problem could be in your memcached interceptor. If it gets a cache hit, it should not be calling `next`.

**Comment by arunthirupathi** [comment]
Currently I use the Memcache interceptor only for writing the response. Before doing the grpc request, application code checks the cache first. 
I am in the process of removing the intercetpor for writing to memcache and adding it as FutureCallback. This will avoid passing in an executor to the gRPC altogether and avoid this complex topic. I will keep this thread updated on whether it reduces the RejectedExecutionException from gRPC.

**Comment by ejona86** [comment]
Okay. Sorry that it's not been more obvious what the problem is.

The only other thing to say is that you may want to double-check you get the same exception when using `future.get()`. I'd sort of expect the backtrace for the `RejectedExecutionException` to be different.

**Comment by arunthirupathi** [comment]
No worries, and really appreciate your detailed help.

We are running this system at scale. I have instrumented the errors and from what I can say, I see the RejectedExecutionException only on the sync portion of the call. Async fails, but very rarely with the RejectedExecutionException. I have never been able to see them in the appengine logs, as appengine logs are not always there 100% of the times.

Really appreciate your help, without your help other solution of moving to the callback would not have been possible. I was lost on pre-starting all the appengine threads.

**Comment by arunthirupathi** [comment]
I moved writing to cache in the Futures.Transform from the async stub and rejectedExecutionException completely stopped. It almost seems like gRPC might use the async executor specified on the call, for more time than the deadline or the future returns.  This is definitely a corner case and imposed by appengine sandbox. 

Thanks for all your help @ejona86 . You can consider this case closed. The approach is working for couple of days without issues.
