### ISSUE TITLE
CompositeReadableBuffer: Failed executing read operation

### ISSUE THREAD

**Issue by MGathier** [grpc/grpc-java#5292]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

gRPC version 1.13.1 - Java version 8

### What did you expect to see?

Occasionally we see the following error:

```
Exception in thread "grpc-default-executor-9" java.lang.AssertionError: Failed executing read operation	
	at io.grpc.internal.CompositeReadableBuffer.execute(CompositeReadableBuffer.java:189)	
	at io.grpc.internal.CompositeReadableBuffer.readBytes(CompositeReadableBuffer.java:91)	
	at io.grpc.internal.ReadableBuffers$BufferInputStream.read(ReadableBuffers.java:327)	
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)	
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)	
	at java.io.FilterInputStream.read(FilterInputStream.java:107)	
	at io.grpc.internal.IoUtils.copy(IoUtils.java:47)	
	at io.grpc.internal.MessageFramer.writeToOutputStream(MessageFramer.java:272)	
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:170)	
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:140)	
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:53)	
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)	
	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:229)	
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:143)	
	at io.grpc.internal.DelayedStream.setStream(DelayedStream.java:112)	
	at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:362)	
	at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:345)	
	at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:303)	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)	
	at java.lang.Thread.run(Thread.java:748)

```
According to the comment in CompositeReadableBuffer this assertion error should never happen.
When the error occurs there is no feedback to the client.

**Comment by carl-mastrangelo** [comment]
Does it still happen on 1.18.0?

**Comment by MGathier** [comment]
Found the cause of the issue. I was using an InputStream as input in the operation, and in some specific cases the operation was executed asynchronously. By the time the operation started using the input stream it was already closed and cleared (small issue in the close operation as it does not reset the readable bytes, causing the initial check in the execute to succeed even if there are no buffers left).

Slightly changing the implementation to always read the input stream before further processing solved the issue.
