### ISSUE TITLE
Running gRPC service in docker container

### ISSUE THREAD

**Issue by mauraborean** [grpc/grpc-java#5376]
I'm trying to run a few micro-services inside a docker container using `docker-compose`. One of this services is a gRPC-Java with auth credentials that will work as a server. When I'm creating the `ManagedChannel` I build it as follows:
`ManagedChannelBuilder.forAddress(host, port).build();` 
But when running locally with docker-compose I need to use `usePlaintext()` because the server is not expecting any auth or I'll get:
```
Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:443
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	... 11 more
```

### What version of gRPC are you using?
1.18.0

### What did you expect to see?
Successful communication without adding specific `usePlaintext()` for local run and removing it for other environment. 
Is there a way to set a default `ManagedChannel` that would set the  `usePlaintext()` if necessary ?

**Comment by carl-mastrangelo** [comment]
Plaintext determines the type of encryption use, not the credentials passed with each RPC.  You'll need to provide a `CallCredentials` to your stub.

**Comment by mauraborean** [comment]
I am providing the credentials to the stub already. Using `withCallCredentials(myCallCredentials) ` method.

**Comment by carl-mastrangelo** [comment]
You are doing something unusual.  Why is your server using port 443, which is reserved for SSL (i.e. not plaintext), while your channel is trying to do plaintext?    gRPC picks SSL by default because it is needed to do protocol selection (commonly known as ALPN).  We don't know ahead of time if the server is plaintext or SSL, so we pick the secure option by default.

If you want to run in insecure mode, you will need to explicitly disable it (by running in plaintext mode).

**Comment by mauraborean** [comment]
The 443 port was just a test.. Initially it was 8080.

How would you suggest running a service that uses SSL encryption (in environments like test, stage, production) locally using docket, then?

**Comment by carl-mastrangelo** [comment]
You can generate certificates, add them to your trust manager client-side, and use them when constructing the server.   We have examples on how to do this in our `HelloWorldClientTls` example class.

I am going to close this, since I don't think it is a bug; more of a question.
