### ISSUE TITLE
How to close ServerCall in ServerCall.Listener?

### ISSUE THREAD

**Issue by gzcf** [grpc/grpc-java#5414]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?

1.17.1

### What did you expect to see?

I am writing a `ServerInterceptor` which will inspect one field of request message and determine whether current user can do this operation, If not, server will send `Status.PERMISSION_DENIED` to client and close. Now I almost approach it, below is reduced code 

```java
public class AuthInterceptor implements ServerInterceptor {

    @Override
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(final ServerCall<ReqT, RespT> call, final Metadata metadata,
                                                                 ServerCallHandler<ReqT, RespT> next) {

        return new ForwardingServerCallListener.SimpleForwardingServerCallListener<ReqT>(next.startCall(call, metadata)) {
            @Override
            public void onMessage(ReqT message) {
                Authoriser.Result authorizedResult = Authoriser.pass(metadata, message);
                if (!authorizedResult.allowed) {
                    call.close(Status.PERMISSION_DENIED
                            .withDescription(String.format("Not allowed to invoke %s on %s", methodName, authorizedResult.table)), metadata);
                    return;
                }
                super.onMessage(message);
            }

        };

    }
}

```

But this code will raise exception in server

```
Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3d89f77c
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.grpc.internal.ServerCallImpl.close(ServerCallImpl.java:172)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:165)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:710)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

I looked at some source codes, and found that seems like there is not a simple API exposed I can use to close `ServerCall` in `ServerCall.Listener`. And I don't sure how I can implement custom `ServerCall.Listener`, `ServerCall` or something else to achieve this. And how much work I need to do. If it is too much work to do, I think I have to put this permission check into every handlers in `MyServiceImplBase`.

Could someone give advices?

**Comment by zhangkun83** [comment]
Because `ServerCall` is not thread-safe, you will need to synchronize it externally if you want to call it from the listener, because it may race with application's invocations on `ServerCall`. And you will have to avoid calling `close()` more than once too.

If you want to look at the first request for authorization, it's better to delay `next.startCall()` until you received the first message. Something like this:
```java
return new ForwardingServerCallListener<ReqT>() {
  ServerCall.Listener<ReqT> delegate = NOOP_LISTENER;

  @Override
  protected ServerCall.Listener<ReqT> delegate() {
    return delegate;
  }

  @Override
  public void onMessage(ReqT message) {
    if (delegate == NOOP_LISTENER) {
      Authoriser.Result authorizedResult = Authoriser.pass(metadata, message);
      if (!authorizedResult.allowed) {
          call.close(Status.PERMISSION_DENIED
                  .withDescription(String.format("Not allowed to invoke %s on %s", methodName, authorizedResult.table)), metadata);
          return;
      }
      delegate = next.startCall(call, metadata);
    }
    onMessage(message);
  }
}
```

The github issues are only for reporting issues. Next time, please post usage questions on our mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by gzcf** [comment]
Sorry for bother here. My requirement is to authorize every messages, I have decided to put this check into handler method. Anyway, thank you for reply.
