### ISSUE TITLE
exception at runtime when trying to start the server

### ISSUE THREAD

**Issue by avnerbarr** [grpc/grpc-java#5458]
getting this exception when running my application at startup. Not sure what is the root cause for it

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:83)
	at io.grpc.internal.AbstractServerImplBuilder.<clinit>(AbstractServerImplBuilder.java:59)
	at com.dy.affinity.grpc.Service$.delayedEndpoint$com$dy$affinity$grpc$Service$1(Service.scala:33)
	at com.dy.affinity.grpc.Service$delayedInit$body.apply(Service.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.dy.affinity.grpc.Service$.main(Service.scala:13)
	at com.dy.affinity.grpc.Service.main(Service.scala)
```

**Comment by carl-mastrangelo** [comment]
Can you print the classpath of your program?  It looks like Guava isn't being included.

**Comment by elharo** [comment]
Or perhaps a very old version of Guava is being included instead.

**Comment by zhangkun83** [comment]
Closing due to inactivity. Feel free to re-open with more information.
