### ISSUE TITLE
connection waiting for very long time grpc v13.1

### ISSUE THREAD

**Issue by mehmoodz** [grpc/grpc-java#5487]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
I am using old version v13.1 grpc java client
JDK11 , GRPC Service fronted by Load balancer

### What did you expect to see?
We use unary blocking call for sending the request like,
```
try { 
  response = stub.withDeadlineAfter(timeoutMillis, TimeUnit.MILLISECONDS).callFunction(request);
} catch (StatusRuntimeException e) {
  throw new RuntimeException(e);
}
```
I observed some requests are waiting even past the configured deadline, currently 300ms 
From the thread dump I see,
```
"jetty-pool-8" #116 prio=5 os_prio=0 cpu=310575.69ms elapsed=23818.02s tid=0x00007f48142f8000 nid=0x655 waiting on condition  [0x00007f46fbffd000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.1/Native Method)
        - parking to wait for  <0x00007f4e6b02d9f8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.1/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.1/AbstractQueuedSynchronizer.java:2081)
        at java.util.concurrent.LinkedBlockingQueue.take(java.base@11.0.1/LinkedBlockingQueue.java:433)
        at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:629)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:123)
        at com.xxx.$SomeBlockingStub.callFn(ServiceGRPC.java:152)
```
and this waits on the waitAndDrain for more than 12 hours.

I tried upgrading to v1.19, seems the problem go away, still monitoring it. But want to understand does this any resolved issue from earlier versions? 

I see lot of issues reported in the older versions regarding stream close and connection waiting  https://github.com/grpc/grpc-go/issues/1462 , https://github.com/grpc/grpc/issues/11643 but ```withDeadline``` not being honored seems a little concerning to me.

**Comment by carl-mastrangelo** [comment]
@mehmoodz did you see any other errors or warnings before this?  it's usually indicative of a dropped callback.

**Comment by mehmoodz** [comment]
I see but for an unrelated thread that I pasted above
```
[xxx] (jetty-pool-17) ERROR - XX grpc call failed : Status{code=UNAVAILABLE, description=HTTP/2 error code: NO_ERROR
Received Goaway
max_age, cause=null}

Caused by: java.lang.RuntimeException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
max_age
        at XXX.YYY.client.grpcClientOutput(ServiceClient.java:141)
        ... 33 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
max_age
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132)
        at com.XXX.ServiceGrpc$BlockingStub.callFunction(GRPCClient.java:152)
        at XXX.YYY.ranking.grpc.GRPCClient.grpcOutput(GRPCServiceClient.java:135)
        ... 38 more 
```

but not sure is this the cause, because I need to wait for long time this to happen so it's hard to tie what was the last error status attached to the thread.

When you say " dropped callback " as I understand the stream has a callback and there is DeadlineExecutor, why deadline is not interrupting the requests here?

**Comment by mehmoodz** [comment]
Ok I take it back v1.19 also seems to have same issue, I will followup with more details. Let me know if you guys have any thoughts on this.

**Comment by mehmoodz** [comment]
@carl-mastrangelo any pointers how can I provide useful info?

**Comment by carl-mastrangelo** [comment]
> When you say " dropped callback " as I understand the stream has a callback and there is DeadlineExecutor, why deadline is not interrupting the requests here?

In gRPC the `ClientCall` object is how your application interacts with the gRPC library.   When the gRPC library wants to interact with your code, it uses `ClientCall.Listener`.   Your application provides a ClientCall.Listener when calling `ClientCall.start()`, which is how the two are bound together.   Callbacks from the library are the invocations on ClientCall.Listener, such as `onMessage`, and `onHeaders`.   

In the case of deadlines, `ClientCall.start` also starts a timer (via a ScheduledFuture, see `ClientCallImpl`).  The timer either is canceled when the RPC completes, or is run which calls `ClientCall.cancel()`.  In the latter case, cancel has to propagate down through the network thread (the "transport") and then comes back up as a `onClose`  invocation on the Listener.   

With that background in mind, what I am guessing happened was that an exception was thrown sometime between the deadline timer firing and the onClose callback being invoked.  This is why I asked if there were any error logs just before.     The ThreadlessExecutor is a red herring, and not related to the hang.

The best thing you can do is provide a reproducing example of it happen, even if it only happens 1/1000 of the time.  The next thing you can do is show how you set up the stub.  Do you set waitForReady?

**Comment by mehmoodz** [comment]
@carl-mastrangelo thanks for providing the info very helpful, I am still trying to reproduce this issue on our side to provide you some details.
and we don't do waitForReady(), since we wanted to fail fast.

" run which calls ClientCall.cancel(). In the latter case, cancel has to propagate down through the network thread (the "transport") and then comes back up as a onClose invocation on the Listener."

Will look into this direction too.

"The next thing you can do is show how you set up the stub"

```
ManagedChannelBuilder<?> channelBuilder =
                ManagedChannelBuilder.forAddress(host, port).usePlaintext();

//stub and channel are instantiated only once not per request
this.stub = ServiceGrpc.newBlockingStub(channelBuilder.build());
```
sample request call would be like

```
try { 
  response = stub.withDeadlineAfter(timeoutMillis, TimeUnit.MILLISECONDS).callFunction(request);
} catch (StatusRuntimeException e) {
  throw new RuntimeException(e);
}
```

**Comment by mehmoodz** [comment]
I was not able to get the exact error logs that you wanted, I solved the issue by having FutureStub and do with .get(timeout) , now I don't see any call back issues anymore.
As you mentioned earlier, the callback is broken from Netty transport layer I believe.

**Comment by carl-mastrangelo** [comment]
Is it possible at all that you shutdown your netty event loops early?  That might cause deadlines to not get triggered.

**Comment by mehmoodz** [comment]
this is a backend server where each request calls out grpc service, how netty event loops can be shutdown, I guess the event loop will be alive until the server is running isn't?

**Comment by mehmoodz** [comment]
also with grpc future stub, I see ~10% high CPU utilization with default configs
I have done few optimizations
1. Set DirectExecutor as per https://github.com/grpc/grpc-java/issues/368, we have blocking call scenario  so this works out for us
2. We have marked tracing disabled by setting retryEnabled() and maxRetry to 0 as per https://github.com/grpc/grpc-java/blob/1c276a823bc1691f899a496975fe7faeb0ec2ff0/core/src/main/java/io/grpc/internal/AbstractManagedChannelImplBuilder.java#L356
3. Replace default NIOEventLoop with native EpollEventLoop for netty

your thoughts?

**Comment by ejona86** [comment]
Using DirectExecutor should be rare. If you are using blocking, then direct executor doesn't do anything (as it isn't using the executor you chose).

To make sure you don't shut down executors/event loops too early, wait until the channel is terminated, generally with awaitTermination(). If it is taking a long time to terminate, that's because RPCs are still happening. If you use shutdownNow() to cancel those RPCs the channel should terminate quickly.

Using Epoll instead of Nio is fine. We've seen marginal gains from doing so.

**Comment by carl-mastrangelo** [comment]
@mehmoodz I haven't had time to reproduce this, but I still think this may be an issue.  If you can provide a reproducing example I can investigate further.

**Comment by zhangkun83** [comment]
@mehmoodz, did you have a chance to work on a repro example?

**Comment by zhangkun83** [comment]
Closing due to inactivity. Can be reopened if a repro example is provided.
