### ISSUE TITLE
Why is startup so slow?

### ISSUE THREAD

**Issue by rubensayshi** [grpc/grpc-java#5519]
### What version of gRPC are you using?
1.19.0

### What did you expect to see?
Using the example code there's a ~5second gap during the startup of the server, which seems odd...

I assume this isn't normal / intended, but it's unclear what is causing this and what could solve it ...

```
[00] 11:33:05.698 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
[00] 11:33:05.702 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - Platform: MacOS
[00] 11:33:05.704 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
[00] 11:33:05.704 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - Java version: 11
[00] 11:33:05.706 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
[00] 11:33:05.706 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
[00] 11:33:05.707 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
[00] 11:33:05.709 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
[00] java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
[00] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:212)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:80)
[00] 	at io.grpc.netty.shaded.io.netty.util.AbstractReferenceCounted.<clinit>(AbstractReferenceCounted.java:39)
[00] 	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.<init>(NettyServer.java:91)
[00] 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.buildTransportServers(NettyServerBuilder.java:468)
[00] 	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:223)
[00] 11:33:05.710 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
[00] 11:33:05.711 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
[00] java.lang.IllegalAccessException: class io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @3246fb96
[00] 	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
[00] 	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
[00] 	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:334)
[00] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:325)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:212)
[00] 	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:80)
[00] 	at io.grpc.netty.shaded.io.netty.util.AbstractReferenceCounted.<clinit>(AbstractReferenceCounted.java:39)
[00] 	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.<init>(NettyServer.java:91)
[00] 	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.buildTransportServers(NettyServerBuilder.java:468)
[00] 	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:223)
[00] 11:33:05.711 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
[00] 11:33:05.711 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
[00] 11:33:05.730 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - maxDirectMemory: 4294967296 bytes (maybe)
[00] 11:33:05.731 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/w1/jztswldd2v77s23x6nnzhx5r0000gn/T (java.io.tmpdir)
[00] 11:33:05.731 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
[00] 11:33:05.731 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
[00] 11:33:05.732 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
[00] 11:33:05.732 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
[00] 11:33:05.732 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
[00] 11:33:05.743 [main] DEBUG io.grpc.netty.shaded.io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 24
[00] 11:33:05.757 [main] DEBUG io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
[00] 11:33:05.757 [main] DEBUG io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
[00] 11:33:05.764 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available

#
# 5 seconds between previous log line and next ....
#

[00] 11:33:10.800 [main] DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.processId: 31342 (auto-detected)
[00] 11:33:10.802 [main] DEBUG io.grpc.netty.shaded.io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
[00] 11:33:10.802 [main] DEBUG io.grpc.netty.shaded.io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
[00] 11:33:10.806 [main] DEBUG io.grpc.netty.shaded.io.netty.util.NetUtil - Loopback interface: [lo0, lo0, 0:0:0:0:0:0:0:1%lo0] ([lo0, lo0, 0:0:0:0:0:0:0:1%lo0], {})
[00] 11:33:10.806 [main] DEBUG io.grpc.netty.shaded.io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
[00] 11:33:10.809 [main] DEBUG io.grpc.netty.shaded.io.netty.channel.DefaultChannelId - -Dio.netty.machineId: f0:18:98:ff:fe:0c:9f:75 (auto-detected)
[00] 11:33:10.812 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
[00] 11:33:10.812 [main] DEBUG io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
[00] 11:33:10.818 [main] DEBUG io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector - -Dio.grpc.netty.shaded.io.netty.leakDetection.level: simple
[00] 11:33:10.818 [main] DEBUG io.grpc.netty.shaded.io.netty.util.ResourceLeakDetector - -Dio.grpc.netty.shaded.io.netty.leakDetection.targetRecords: 4
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 24
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 24
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
[00] 11:33:10.836 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
[00] 11:33:10.841 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
[00] 11:33:10.841 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
[00] 11:33:10.841 [main] DEBUG io.grpc.netty.shaded.io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
```

**Comment by carl-mastrangelo** [comment]
DEBUG level is going to be very noisy, so don't take it as seriously.  As for the delay, is the CPU fully active during those 5 seconds?

**Comment by dapengzhang0** [comment]
5 seconds is still too big even DEBUG level is noisy, but this seems more of an issue of netty rather than grpc. 

@rubensayshi Can you replace
```
runtimeOnly "io.grpc:grpc-netty-shaded:${grpcVersion}"
```

in `build.gradle` with 
```
runtimeOnly "io.grpc:grpc-netty:${grpcVersion}"
```

If the issue persists, could you file an issue at [netty](https://github.com/netty/netty)?

**Comment by rubensayshi** [comment]
CPU is more or less idle, was using mvn, I tried without -shaded and it's still taking 5s, it's fairly consistent, as if there's an actual 5s sleep somewhere ...

it comes from this block:
```java
    // Bind and start to accept incoming connections.
    ChannelFuture future = b.bind(address);
    try {
      future.await();
    } catch (InterruptedException ex) {
      Thread.currentThread().interrupt();
      throw new RuntimeException("Interrupted waiting for bind");
    }
```

so you're probably right that the issue is more netty than grpc related.

**Comment by dapengzhang0** [comment]
I saw a netty issue is filed ( https://github.com/netty/netty/issues/8993 ). Closing. Please reopen if it turns out to be grpc's problem not netty's.
