### ISSUE TITLE
open ssl error-  help: No ALPN negotiated after enabling useTransportSecurity to grpc server

### ISSUE THREAD

**Issue by callapatel** [grpc/grpc-java#5608]
Please answer these questions before submitting your issue.
```
openssl s_client -connect myservice:myport
CONNECTED(00000003)
4529235564:error:140040E5:SSL routines:CONNECT_CR_SRVR_HELLO:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.240.1/libressl-2.6/ssl/ssl_pkt.c:585:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
   Protocol  : TLSv1.2
   Cipher    : 0000
   Session-ID:
   Session-ID-ctx:
   Master-Key:
   Start Time: 1555369018
   Timeout   : 7200 (sec)
   Verify return code: 0 (ok)
```

### What version of gRPC are you using?
1.12.0
also have: 
```
 <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.7.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.22.Final</version>
        </dependency>
```

### What did you expect to see?
Should be able to use OpenSSL command to our server, but after adding useTransportSecurity I haven't been able to ping my server:
```
        server = NettyServerBuilder.forPort(grpcProperties.port)
            .let {
                if (serverConfig.enabled) {
                    log.info { "this session is enabled for ssl execution" }
                    try {
                        it.useTransportSecurity(File(serverConfig.certchain), File(serverConfig.privatekeyfile))
                    } catch (e: Exception) {
                        log.error(e) { "Unable to setup ssl security, skip ssl setup. " }
                        it
                    }
                } else {
                    it
                } }
            .addService(ServerInterceptors.intercept(myServiceImpl, headeeMetadataServerInterceptor))
            .maxConnectionAge(grpcProperties.maxConnectionAgeInSeconds, TimeUnit.SECONDS)
            .build()
            .start()
```

Locally, when I try to run a request seeing:
```
io.grpc.StatusRuntimeException: UNKNOWN: channel closed

	at io.grpc.Status.asRuntimeException(Status.java:532)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:699)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1500)
		
Caused by: java.nio.channels.ClosedChannelException
	at io.grpc.netty.Utils.statusFromThrowable(Utils.java:166)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.exceptionCaught(WriteBufferingAndExceptionHandler.java:84)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.fail(ProtocolNegotiators.java:597)
	at io.grpc.netty.ProtocolNegotiators$BufferUntilTlsNegotiatedHandler.userEventTriggered(ProtocolNegotiators.java:686)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.ssl.SslUtils.handleHandshakeFailure(SslUtils.java:318)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1532)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1005)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
```

Any tips as to how to trouble shoot this?

**Comment by callapatel** [comment]
also using java 8 for our applicaiton so added ALPN to the pom:   
<dependency>
            <groupId>org.mortbay.jetty.alpn</groupId>
            <artifactId>alpn-boot</artifactId>
            <version>8.1.11.v20170118</version>
        </dependency>

**Comment by callapatel** [comment]
looks like we don't have any enabled ciphers: Enabled ciphers=[]__] do you know if theres a way we can explicitly enable them?

**Comment by ejona86** [comment]
_Please_ don't use alpn-boot. Just adding a dependency on it doesn't enable it, FYI.

Why are you suspecting ALPN is broken? Is it only openssl that is showing no ALPN negotiated? It does that if you don't specify `-alpn` on the command line. Consider something closer to `openssl s_client -connect myservice:myport -alpn h2`.

1.12 is pretty old; I think I fixed a few more places to provide more information instead of the not-very-helpful ClosedChannelException. Also, Netty 4.1.34 added a feature where it will remember more details about the exception, so the grpc exception would be a lot easier to diagnose with grpc-java 1.20.

It also seems like you could use ServerBuilder instead of NettyServerBuilder, which would allow you to swap from grpc-netty to grpc-netty-shaded. With grpc-netty-shaded you don't need to worry about version of tcnative, etc.

**Comment by areliszxz** [comment]
checa haber si esto te ayuda
Check if this helps you
https://github.com/areliszxz/grpcs-grpc-nginx-go-node-java
