### ISSUE TITLE
grpc java.lang.IllegalStateException: call was half-closed                                                                             at

### ISSUE THREAD

**Issue by hbhongyi** [grpc/grpc-java#5620]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
implementation 'io.grpc:grpc-okhttp:1.7.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.7.0'
    implementation 'io.grpc:grpc-stub:1.7.0'

### What did you expect to see?

```
04-21 02:41:56.954 9232-9232/com.neolix E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.neolix, PID: 9232
java.lang.IllegalStateException: call was half-closed
    at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
    at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:406)
    at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:52)
    at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:286)
    at com.neolix_self_checking.communication.OpenApiOnboardProtoManager$5.handleMessage(OpenApiOnboardProtoManager.java:412)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by creamsoup** [comment]
"call was half-closed" usually means `onCompleted()` was called which doesn't allow any other methods (`onNext()` for example). @hbhongyi, can you check` onCompleted` is called?

**Comment by ejona86** [comment]
Closing since this seems like a user bug. Created #5652 to make the error message more clear.
