### ISSUE TITLE
java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not found

### ISSUE THREAD

**Issue by JacobCrofts** [grpc/grpc-java#5794]
_Using grpc 1.21.0._

I have a gRPC Java client that should connect to a gRPC server and make a simple request – which it does, successfully, in a unit test I wrote. However, when I package my jar and run it in a different environment outside of IntelliJ, I get this stack trace when I try to initialize the gRPC client:

<details><summary>stack trace</summary>

```txt
java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Provider io.grpc.netty.NettyChannelProvider not found
at java.util.ServiceLoader.fail(ServiceLoader.java:239) ~[?:1.8.0_77]
at java.util.ServiceLoader.access$300(ServiceLoader.java:185) ~[?:1.8.0_77]
at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372) ~[?:1.8.0_77]
at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[?:1.8.0_77]
at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[?:1.8.0_77]
at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67) ~[?:?]
at io.grpc.ServiceProviders.load(ServiceProviders.java:42) ~[?:?]
at io.grpc.ManagedChannelProvider.<clinit>(ManagedChannelProvider.java:37) ~[?:?]
at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[?:?]
at net.admininabox.spigot.internal.client.ServiceClients.<init>(ServiceClients.java:19) ~[?:?]

// the rest is almost certainly irrelevant, but I'm leaving it here anyway because
// I have been stung by hasty assumptions many times before
// net.admininabox.spigot.internal is my project, some of the source code of which I have shared

at net.admininabox.spigot.internal.plugin.AdminInABoxSpigotInternalPluginLoader.<init>(AdminInABoxSpigotInternalPluginLoader.java:13) ~[?:?]
at net.admininabox.spigot.internal.AdminInABoxSpigotInternalPlugin.onEnable(AdminInABoxSpigotInternalPlugin.java:12) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

</details>

<br>
I have two thoughts about what might be going on. First, my maven shading configuration may be wrong. I am not an expert on Java dependency management and could easily have made a mistake:

<br><details><summary>pom.xml</summary>

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>net.admininabox.spigot.internal</groupId>
    <artifactId>admininabox-spigot-internal</artifactId>
    <packaging>jar</packaging>
    <version>0.1.0</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <grpc.version>1.22.0-SNAPSHOT</grpc.version><!-- CURRENT_GRPC_VERSION -->
        <protobuf.version>3.7.1</protobuf.version>
        <protoc.version>3.7.1</protoc.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <!-- shade dependencies https://maven.apache.org/plugins/maven-shade-plugin/ -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <minimizeJar>true</minimizeJar>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <directory>${basedir}</directory>
                <includes>
                    <include>plugin.yml</include>
                    <include>config.yml</include>
                </includes>
            </resource>

            <!-- adds the properties defined in src/main/resources to be loaded to classpath -->
            <!-- https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-bom</artifactId>
                <version>1.21.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-stub</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-protobuf</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.2</version>
            <scope>provided</scope> <!-- not needed at runtime -->
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-testing</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java-util</artifactId>
            <version>${protobuf.version}</version>
        </dependency>


        <!--https://www.spigotmc.org/wiki/spigot-maven/-->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.13.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>craftbukkit</artifactId>
            <version>1.13.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.admininabox.service</groupId>
            <artifactId>admininabox-service</artifactId>
            <version>0.19.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/org.fusesource.jansi/jansi -->
        <dependency>
            <groupId>org.fusesource.jansi</groupId>
            <artifactId>jansi</artifactId>
            <version>1.14</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>RELEASE</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.mockito/mockito-all -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-all</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>myMavenRepoWrite</id>
            <url>${myMavenRepoWriteUrl}</url>
        </repository>
        <snapshotRepository>
            <id>myMavenRepoWrite</id>
            <url>${myMavenRepoWriteUrl}</url>
        </snapshotRepository>
    </distributionManagement>
</project>

```

</details>

<br>

I decompiled the jarfile generated during the `package` phase, and it seems to indicate that the Netty stuff may be missing or misplaced. I expected to see see the class `io.grpc.netty.NettyChannelProvider` from my stack trace in the `netty` directory here:

<details><summary>screenshot of my decompiled jarfile</summary>
<img width="315" alt="Screen Shot 2019-05-27 at 8 25 29 PM" src="https://user-images.githubusercontent.com/13839679/58448753-99dbbd80-80bd-11e9-89ba-878637d1e65a.png">
</details>

<br>

Second, the server logs indicate to me that Spigot is probably also using Netty, and it's possible that its Netty version is conflicting with the one in my project.

<details><summary>server logs</summary>

```txt
➜  test git:(link_account_command) ✗ bin/start spigot
Loading libraries, please wait...
Loaded 0 recipes
>[19:33:17 INFO]: Loaded 0 recipes
[19:33:17 INFO]: Starting minecraft server version 1.13.2
[19:33:17 INFO]: Loading properties
[19:33:17 INFO]: Default game type: SURVIVAL
[19:33:17 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[19:33:18 INFO]: Debug logging is disabled
[19:33:18 INFO]: Server Ping Player Sample Count: 12
[19:33:18 INFO]: Using 4 threads for Netty based IO <----- !!!!!!
[19:33:18 INFO]: Generating keypair
[19:33:18 INFO]: Starting Minecraft server on *:25565
[19:33:18 INFO]: Using default channel type
[19:33:32 INFO]: [admininabox-spigot-internal] Loading admininabox-spigot-internal v0.1.0
[19:33:32 INFO]: Preparing level "world"
[19:33:32 INFO]: Reloading ResourceManager: Default, bukkit
(...)
```

</details>

<br>

The applications using my project, which I do not own, run Spigot in their own Runtimes, so I declare this dependency in the `provided` scope.

Finally, here is my source code where I am initializing the gRPC client. I don't think this is causing the problem, but it can't hurt to check:

<details><summary>ServiceClients.java</summary>

```java
package net.admininabox.spigot.internal.client;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.Metadata;
import net.admininabox.service.MCAdminToolsExternalServiceGrpc;
import net.admininabox.service.MCAdminToolsExternalServiceGrpc.MCAdminToolsExternalServiceBlockingStub;
import net.admininabox.service.MCAdminToolsExternalServiceGrpc.MCAdminToolsExternalServiceStub;

import java.util.concurrent.TimeUnit;

public class ServiceClients {

    private final ManagedChannel channel;
    private final MCAdminToolsExternalServiceBlockingStub blockingClient;
    private final MCAdminToolsExternalServiceStub asyncClient;

    public ServiceClients() {
        this(ManagedChannelBuilder.forTarget("localhost:9093").usePlaintext());
    }

    private ServiceClients(ManagedChannelBuilder<?> channelBuilder) {
        channel = channelBuilder.build();
        blockingClient = MCAdminToolsExternalServiceGrpc.newBlockingStub(channel);
        asyncClient = MCAdminToolsExternalServiceGrpc.newStub(channel);
    }

    public MCAdminToolsExternalServiceBlockingStub getBlockingClient() {
        return blockingClient;
    }

    public MCAdminToolsExternalServiceStub getAsyncClient() {
        return asyncClient;
    }

    void shutdown() throws InterruptedException {
        channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
    }
}
```

</details>

<br>

My question here is: what am I doing wrong and what else can I do to debug?

**Comment by dapengzhang0** [comment]
You probably should either depend on `io.grpc:grpc-netty` or `io.grpc:grpc-netty-shaded` (preferred), but not both

```
<dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty</artifactId>
        </dependency>
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-netty-shaded</artifactId>
            <scope>runtime</scope>
        </dependency>
```

**Comment by dapengzhang0** [comment]
Also I noticed that you used maven shade plugin, then you might also need to transform all the resources files of every package that is shaded, see https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#ManifestResourceTransformer

**Comment by JacobCrofts** [comment]
@dapengzhang0, thanks for the tips. I will try these and report back.

**Comment by JacobCrofts** [comment]
I gave it a shot, unsuccessfully, but I find the shade plugin's documentation on resource transformation during shading to be inscrutable. Would you please help me understand why it's necessary to transform resource files for the grpc-netty-shaded jar but not the others? Additionally, in my decompiled jarfile, why is `package-info.class` the only file in there? Will resource transformation fix that?

**Comment by JacobCrofts** [comment]
Just figured it out. All I needed to do was remove `<minimizeJar>true</minimizeJar>` from the shade plugin configuration. It's not super clear to me why that was omitting some dependencies, but everything works exactly as I was expecting it to now.

This was definitely a me problem and not a grpc problem, so sorry for bothering you guys about this.
