### ISSUE TITLE
Should rawConfig include policy name?

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-java#5804]
#5397 assumed that rawConfig includes policy name, but the constructor 
`LbConfig(String policyName, Map<String, ?> rawConfigValue)` is never passing `rawConfigValue` with the policy name. That ends up a bug

```
FINEST: [Channel<7>: (test_service.test_namespace.gslb.googleprod.com)] Resolved address: [[[/0:0:0:0:0:0:0:1:21607]/{io.grpc.grpclb.lbAddrAuthority=fake-authority-that-is-always-the-same}]], config={service-config={loadBalancingConfig=[{xds_experimental={balancerName=[::1]:21607}}, {grpclb={}}, {xds={balancerName=[::1]:21607}}], healthCheckConfig={serviceName=}}}
May 29, 2019 5:11:20 PM io.grpc.ChannelLogger log
FINEST: [Channel<7>: (test_service.test_namespace.gslb.googleprod.com)] Address resolved: [[[/0:0:0:0:0:0:0:1:21607]/{io.grpc.grpclb.lbAddrAuthority=fake-authority-that-is-always-the-same}]]
May 29, 2019 5:11:20 PM io.grpc.internal.ClientCallImpl logIfContextNarrowedTimeout
FINE: Call timeout set to '4998908748' ns, due to context deadline. Explicit call timeout was not set.
May 29, 2019 5:11:20 PM io.grpc.ChannelLogger log
FINEST: [Channel<7>: (test_service.test_namespace.gslb.googleprod.com)] Service config changed
May 29, 2019 5:11:20 PM io.grpc.internal.ClientCallImpl logIfContextNarrowedTimeout
FINE: Call timeout set to '4997013555' ns, due to context deadline. Explicit call timeout was not set.
May 29, 2019 5:11:20 PM io.grpc.ChannelLogger log
FINEST: [Channel<7>: (test_service.test_namespace.gslb.googleprod.com)] Load balancer changed from PickFirstLoadBalancer to XdsLoadBalancer
May 29, 2019 5:11:20 PM io.grpc.ChannelLogger log
FINEST: [Channel<7>: (test_service.test_namespace.gslb.googleprod.com)] Load-balancing config: {balancerName=[::1]:21607}
May 29, 2019 5:11:20 PM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<7>: (test_service.test_namespace.gslb.googleprod.com)] Uncaught exception in the SynchronizationContext. Panic!
io.grpc.StatusRuntimeException: UNKNOWN: Failed to parse config value '[::1]:21607' for key 'balancerName' in '{balancerName=[::1]:21607}' is not object
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.xds.XdsLoadBalancer.handleResolvedAddresses(XdsLoadBalancer.java:133)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.handleResolvedAddresses(AutoConfiguredLoadBalancerFactory.java:152)
	at io.grpc.internal.ManagedChannelImpl$NameResolverListener$1NamesResolved.run(ManagedChannelImpl.java:1346)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:120)
	at com.google.net.grpc.nameresolver.EnvelopeNameResolver$EnvelopeStreamListener.onResponse(EnvelopeNameResolver.java:306)
	at com.google.net.rpc.messenger.NettyMessengerClient$Stream$1Receiver.run(NettyMessengerClient.java:265)
	at com.google.common.util.concurrent.SequentialExecutor$1.run(SequentialExecutor.java:120)
	at com.google.common.util.concurrent.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:227)
	at com.google.common.util.concurrent.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:171)
	at com.google.net.eventmanager.AbstractFutureTask$Sync.innerRun(AbstractFutureTask.java:260)
	at com.google.net.eventmanager.AbstractFutureTask.run(AbstractFutureTask.java:121)
	at com.google.net.eventmanager.EventManagerImpl.runTask(EventManagerImpl.java:618)
	at com.google.net.eventmanager.EventManagerImpl.internalRunWorkerLoop(EventManagerImpl.java:1036)
	at com.google.net.eventmanager.EventManagerImpl.runWorkerLoop(EventManagerImpl.java:916)
	at com.google.net.eventmanager.WorkerThreadInfo.runWorkerLoop(WorkerThreadInfo.java:160)
	at com.google.net.eventmanager.EventManagerImpl$WorkerThread.run(EventManagerImpl.java:1903)
Caused by: java.lang.ClassCastException: value '[::1]:21607' for key 'balancerName' in '{balancerName=[::1]:21607}' is not object
	at io.grpc.internal.ServiceConfigUtil.getObject(ServiceConfigUtil.java:458)
	at io.grpc.internal.ServiceConfigUtil.unwrapLoadBalancingConfig(ServiceConfigUtil.java:364)
	at io.grpc.xds.XdsLoadBalancerProvider.parseLoadBalancingConfigPolicy(XdsLoadBalancerProvider.java:77)
	at io.grpc.xds.XdsLoadBalancer.handleResolvedAddresses(XdsLoadBalancer.java:131)
	... 16 more
```

**Comment by dapengzhang0** [comment]
cc @zhangkun83

**Comment by zhangkun83** [comment]
By "rawConfig" I think meant the input of `ServiceConfigUtil.unwrapLoadBalancingConfig()`. As its javadoc says

> The input is a JSON object (map) with exactly one entry, where the key is the policy name and the value is a config object for that policy.

From the stack-trace, that method is called from

> io.grpc.xds.XdsLoadBalancerProvider.parseLoadBalancingConfigPolicy(XdsLoadBalancerProvider.java:77)

with the input `{balancerName=[::1]:21607}`. This is not what `unwrapLoadBalancingConfig()` expects.

I think the call to `unwrapLoadBalancingConfig()` is unnecessary here. All the related method that expect input to be `LbConfig {policyName=<ignored>, rawConfigValue="{balancerName=[::1]:21607, ...}" should instead expect input to be `"{balancerName=[::1]:21607, ...}"`.
