### ISSUE TITLE
Received unexpected EOS on DATA frame from server esf

### ISSUE THREAD

**Issue by nwbirnie** [grpc/grpc-java#5944]
When response trailers are quite large (likely around 1MB of trailers) we receive an internal error from gRPC rather than the original trailers.

This is affecting Google Ads users - who are unable to debug their failed requests, see googleads/google-ads-java/issues/100.

The error is generated in [Http2ClientStreamTransportState](https://github.com/grpc/grpc-java/blob/v1.21.0/core/src/main/java/io/grpc/internal/Http2ClientStreamTransportState.java#L150) where it appears that the EOS flag is set while still receiving data. 

Is it possible that this is a race condition where the server has already sent the response and closed the stream before the client finishes receiving the headers, data and trailers? I suppose that could happen if the response is sent in several packets, and `Http2ClientStreamTransportState` is running at the packet level, rather than message level?

### What version of gRPC are you using?
v1.21.0

### What did you expect to see?

Response trailers which contain a detailed failure message.

**Comment by nwbirnie** [comment]
[Link to detailed logs](https://gist.github.com/nwbirnie/347c9fd2843f9ad87de6b2d0d8d585d1)

Stacktrace follows:

```
Exception in thread "main" com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1030)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:871)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:716)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.ads.googleads.lib.logging.LoggingInterceptor$1$1.onClose(LoggingInterceptor.java:111)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at com.google.ads.googleads.v1.services.GoogleAdsServiceClient.mutate(GoogleAdsServiceClient.java:513)
		at com.google.ads.googleads.v1.services.GoogleAdsServiceClient.mutate(GoogleAdsServiceClient.java:449)
		at com.google.api.ads.googleads.randomtests.EosTests.main(EosTests.java:94)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server.
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 27 more
```

**Comment by carl-mastrangelo** [comment]
That error usually means the server sent back a non-grpc response, possibly some HTTP error.   Do you know the server software you are connecting to?

**Comment by dapengzhang0** [comment]
This seems the server couldn't send extremely large trailers and EOS correctly. What language is the grpc server?

**Comment by nwbirnie** [comment]
This is connecting to ESF proxy (I believe Java).
