### ISSUE TITLE
Extension file 'java_grpc_library.bzl' has errors

### ISSUE THREAD

**Issue by Auzahn** [grpc/grpc-java#6001]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
I don't know but I am using Bazel version 0.27.2

### What did you expect to see?

I am trying to install ONOS following the Developer Guide. The site says install Bazel first, and I did install Bazel first - version 0.27.2. Then, I installed Java version 201 manually because of the new licence issues. Finally, I cloned the git repository for ONOS version 2.1 and tried to build it using "$ bazel build onos" command. As it was trying to install the software, the process was interrupted with the final message:

------------------------------------------------------------------------------------------------------------------------------
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
ERROR: /home/ozan/.cache/bazel/_bazel_ozan/fd5ffe9eac342503820c7307da86d315/external/io_grpc_grpc_java/java_grpc_library.bzl:41:17: Traceback (most recent call last):
	File "/home/ozan/.cache/bazel/_bazel_ozan/fd5ffe9eac342503820c7307da86d315/external/io_grpc_grpc_java/java_grpc_library.bzl", line 39
		rule(attrs = {"srcs": attr.label_list...")}, <2 more arguments>)
	File "/home/ozan/.cache/bazel/_bazel_ozan/fd5ffe9eac342503820c7307da86d315/external/io_grpc_grpc_java/java_grpc_library.bzl", line 41, in rule
		attr.label_list(mandatory = True, non_empty = True, ..."])
'non_empty' is no longer supported. use allow_empty instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: Skipping 'onos': error loading package '': in /home/ozan/onos/tools/build/bazel/osgi_java_library.bzl: Extension file 'java_grpc_library.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package '': in /home/ozan/onos/tools/build/bazel/osgi_java_library.bzl: Extension file 'java_grpc_library.bzl' has errors
INFO: Elapsed time: 12.963s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: 
--------------------------------------------------------------------------------------------------------------------------------

I tried to install different versions of jdk and onos but it did not help. I do not understand why I am getting this problem. Can someone help?

**Comment by ran-su** [comment]
Looks like a bazel version problem, from https://github.com/opennetworkinglab/onos/tree/onos-2.1 , ONOS v2.1 uses bazel 0.17 .

**Comment by ran-su** [comment]
Closing due to inactivity.

**Comment by DanielTimLee** [comment]
```
sdn@NR4:~$ bazel version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/sdn/.cache/bazel/_bazel_sdn/install/28c1d2ace0add449e21862ae9f2d2289/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
Build label: 0.17.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 14 10:39:25 2018 (1536921565)
Build timestamp: 1536921565
Build timestamp as int: 1536921565
sdn@NR4:~$ cd onos/
sdn@NR4:~/onos$ bazel build onos
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
WARNING: Waiting for server process to terminate (waited 10 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
ERROR: /home/sdn/onos/WORKSPACE:5:1: Traceback (most recent call last):
	File "/home/sdn/onos/WORKSPACE", line 5
		check_bazel_version()
	File "/home/sdn/onos/tools/build/bazel/bazel_version.bzl", line 26, in check_bazel_version
		fail(("\nBazel version %s is not supp...))

Bazel version 0.17.1 is not supported; please use 0.19.* official release!

ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'repositories.bzl': no such package '@io_grpc_grpc_java//': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'repositories.bzl': no such package '@io_grpc_grpc_java//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 1.790s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
sdn@NR4:~/onos$ git status
HEAD detached at 2.1.0
nothing to commit, working tree clean
```

Seems `bazel 0.17` is not working for building `onos 2.1.0`.

**Comment by Auzahn** [comment]
Yes, I think it explicitly says on Bazel's website that the minimum version
required is 0.27.0.

However, later on, with another person's advice who works in the same lab
with me, I managed to install it using Bazel version 0.21.0.

Hope it helps

**Comment by ran-su** [comment]
This might be a very useful information for new ONOS users. If the information on ONOS repo is incorrect, you should consider help them to fix it.
