### ISSUE TITLE
SslContext creation failed

### ISSUE THREAD

**Issue by rameshpasunoori** [grpc/grpc-java#6009]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.4.0

### What did you expect to see?

Created sample application to run grpc server in SSL mode.
Same set of code and certificates working on windows but failing in Linux

```
Jul 25, 2019 02:10:40.762 - trustCertCollectionFilePath : cert/ca.pem
serverCertChainFilePath : cert/server0.pem
serverPrivateKeyFilePath : cert/server0.key
javax.net.ssl.SSLException: failed to set certificate and key
        at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:134)
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:352)
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:335)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:421)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441)
        at SSLJavaContext.getServerSslContext(SSLJavaContext.java:103)
        at HelloWorldServerTls.start(HelloWorldServerTls.java:485)
        at HelloWorldServerTls.main(HelloWorldServerTls.java:606)
Caused by: java.security.KeyStoreException: Cannot get key bytes, not PKCS#8 encoded
        at sun.security.provider.KeyProtector.protect(KeyProtector.java:174)
        at sun.security.provider.JavaKeyStore.engineSetKeyEntry(JavaKeyStore.java:267)
        at sun.security.provider.JavaKeyStore$JKS.engineSetKeyEntry(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:117)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineSetKeyEntry(JavaKeyStore.java:70)
        at java.security.KeyStore.setKeyEntry(KeyStore.java:1140)
        at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:982)
        at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1141)
        at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1132)
        at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:124)
        ... 7 more
```

**Comment by rameshpasunoori** [comment]
Linux pasra08-rh76vm1 3.10.0-957.12.2.el7.x86_64 #1 SMP Fri Apr 19 21:09:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rameshpasunoori** [comment]
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by carl-mastrangelo** [comment]
You need to convert to the format java wants ("Cannot get key bytes, not PKCS#8 encoded").   If you have openssl installed, you can use the command here: https://gist.github.com/carl-mastrangelo/71e0b24248c5dff88df747dfd79e92b2

**Comment by rameshpasunoori** [comment]
I did same command to convert to PKCS8.
Still I am getting the error.
If you have complete set of commands to generate the Self Signed SSL Certs for GRPC, It would be great help.

**Comment by ejona86** [comment]
If this is just for testing, we recommend using our pre-created certs: https://github.com/grpc/grpc-java/tree/master/testing/src/main/resources/certs . [TlsTesting.loadCert()](https://grpc.github.io/grpc-java/javadoc/io/grpc/testing/TlsTesting.html) is a convenience method for loading them at runtime.

If you really need to generate your own certs, I'd recommend using the wider ecosystem's tools for generating them, like [certstrap](https://github.com/square/certstrap). Generating certs is hard, and is a bit outside the scope of gRPC itself.

**Comment by ST-DDT** [comment]
@ramaraochavali I use the following command to generate my self-signed certificates:

https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/tests/src/test/resources/certificates/generateCertificates.sh

**Comment by ramaraochavali** [comment]
probably intended for @rameshpasunoori
