### ISSUE TITLE
Transport failed with go grpc client

### ISSUE THREAD

**Issue by xpunch** [grpc/grpc-java#6011]
### What version of gRPC are you using?
grpcVersion = '1.22.1'
protobufVersion = '3.7.1'

### What did you expect to see?
No transport failed error.

I'm running the helloworld example of grpc-java, but request with a go client.
The request is successful in go client, but the grpc-java server throw an transport failed error.
```java
io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated
Info: Transport failed
java.io.IOException: Remote connection was closed by force.
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.grpc.netty.shaded.io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125)
        at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ran-su** [comment]
Hi, I tried to reproduce the issue with grpc-java "v1.22.1" and grpc-go "master", the HelloWorld example ran just fine. Could you please give us more information about your environment and steps to reproduce?

**Comment by xpunch** [comment]
I tried grpc-java as server and grpc-go as client too, but get the same error.

**Environment:**
Win10
grpc-java: master branch
grpcVersion = '1.22.1'
protobufVersion = '3.7.1'

grpc-go: master branch
github.com/golang/protobuf v1.2.0
```
./build/install/examples/bin/hello-world-server

July 26, 2019 9:49:10 io.grpc.examples.helloworld.HelloWorldServer start
Info: Server started, listening on 50051
July 26, 2019 9:53:11 io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated
Info: Transport failed
java.io.IOException: The remote host forcibly closed an existing connection.
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.grpc.netty.shaded.io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1125)
        at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
The grpc-go client works fine.
```
go run examples/helloworld/greeter_client/main.go
2019/07/26 09:53:11 Greeting: Hello world
```

**Comment by xpunch** [comment]
@ran-su above is my environment info, I tried grpc-java and grpc-go, but failed too.

**Comment by xpunch** [comment]
It works fine when I use grpc-go server and grpc-java client, no exception is return in both side.

**Comment by ran-su** [comment]
Have tried java server with java client? 
What do you mean by `I tried grpc-java and grpc-go, but failed too.`
I think I need more information like JDK version, Golang version and steps to reproduce.

**Comment by xpunch** [comment]
@ran-su Yeah, java server and java client, it works fine, only fails when used java server with go client.
```
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```
```
go version go1.12 windows/amd64
```

**Comment by ejona86** [comment]
In discussing this in-person, @carl-mastrangelo noticed that the RPC seems successful to the client. So the problem is just the shutdown of the connection, which is not actually a problem. We should add this error message to QUIET_ERRORS. We missed squelching this message because it was on Windows.

https://github.com/grpc/grpc-java/blob/188b4d1e51c81eaaa59f20eb454038e684c3dc6e/netty/src/main/java/io/grpc/netty/NettyServerTransport.java#L54-L57

**Comment by xpunch** [comment]
@ejona86 Thank you very much, I've tested grpc-java server in docker container, and it work fine with my grpc-go client on windows, there is no errors any more.
By the way, my operation system is not in English version, and the error string is not exactly "An existing connection was forcibly closed by the remote host"(it's in Chinese) , so maybe this is the reason when I can see this error message.
