### ISSUE TITLE
Error message when connecting with TLS to closed port unhelpful

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#602]
When I connect to a random port that is not open, the error message is not helpful.

```
$ ./run-test-client.sh --server_port=1234
Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen' after any changes.
-PskipCodegen=true is optional, but requires less setup.
Running test empty_unary
Jul 07, 2015 11:02:03 AM io.grpc.transport.netty.ProtocolNegotiators$AbstractBufferingHandler fail
SEVERE: Transport failed during protocol negotiation
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel closed while performing protocol negotiation
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.transport.netty.ProtocolNegotiators.unavailableException(ProtocolNegotiators.java:175)
	at io.grpc.transport.netty.ProtocolNegotiators.access$000(ProtocolNegotiators.java:72)
	at io.grpc.transport.netty.ProtocolNegotiators$AbstractBufferingHandler.close(ProtocolNegotiators.java:261)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeCloseNow(ChannelHandlerInvokerUtil.java:133)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeClose(DefaultChannelHandlerInvoker.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:238)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:197)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:987)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:200)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:56)
	at io.netty.channel.ChannelFutureListener$2.operationComplete(ChannelFutureListener.java:52)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:276)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:105)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:115)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:257)
	at io.grpc.testing.integration.AbstractTransportTest.emptyUnary(AbstractTransportTest.java:148)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:203)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:192)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:79)
Caused by: io.netty.channel.ChannelException: Pending write on removal of SslHandler
	at io.netty.handler.ssl.SslHandler.handlerRemoved0(SslHandler.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:209)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:627)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:621)
	at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:450)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:898)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:867)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:859)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:843)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:696)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment]
I believe this was fixed in #697.
