### ISSUE TITLE
Error using Java 11/12

### ISSUE THREAD

**Issue by jacobg** [grpc/grpc-java#6029]
Please answer these questions before submitting your issue.

### What did you expect to see?

I have the following code in order to use the PubSub Emulator:
```scala
    val channel: ManagedChannel = ManagedChannelBuilder
      .forTarget("127.0.0.1:8086")
      .usePlaintext()
      .build()
```

When I run it in IntelliJ, it works fine. However, when I build a fat jar with sbt-assembly and run it, I get this exception:

```
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
        at io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
        at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
        at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
        at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:213)
        at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81)
        at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:222)
        at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:209)
        at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401)
        at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:47)
        at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:67)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:76)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:42)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForTarget(NettyChannelProvider.java:23)
        at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:73)
```

I checked when running in IntelliJ, and it also uses the `NettyChannelProvider` as the `ManangedChannelBuilder`'s provider.

So what would be happening differently when running in a release jar?

**Comment by jacobg** [comment]
I've narrowed down that the error occurs when using Java 12, and works fine in Java 8.

**Comment by jacobg** [comment]
https://github.com/grpc/grpc-java/issues/4933

**Comment by carl-mastrangelo** [comment]
@jacobg  can you confirm that this isn't just a debug log statement?   Does gRPC still work regardless of how you build it?

**Comment by jacobg** [comment]
@carl-mastrangelo Yes you're right, it does appear that it's just a DEBUG log statement of an exception. I guess I'll close this issue then. Thanks.
