### ISSUE TITLE
when create multi client for difference server, throw such exception java.lang.RuntimeException: ManagedChannel allocation site

### ISSUE THREAD

**Issue by hk-lrzy** [grpc/grpc-java#6032]
Please answer these questions before submitting your issue.

```
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:514)
```

### What version of gRPC are you using?
version: 1.21.0

### What did you expect to see?

How to maintain multi client in our service,

**Comment by creamsoup** [comment]
the error message trying to say that the application is leaking the channel (channel is not properly cleaned up).
