### ISSUE TITLE
INTERNAL: Received unexpected EOS on DATA frame from server (Android)

### ISSUE THREAD

**Issue by bingoo** [grpc/grpc-java#6095]
When doing a blocking call from a java/kotlin client I am getting the following error:

```
io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server.
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
```

When doing a non-blocking async call the onNext is called correctly, and the response proto is succesfully sent. Yet after this the same error occurs and onCompleted is not executed. When I do a stack trace on the exception I see the following result:

```
io.grpc.Status.asRuntimeException(Status.java:533)
io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
```

Wrapping the Service on the server with try-catch blocks does not show any exceptions on the server. If necessary I can post the code of the server Service and the client calls.

### What version of gRPC are you using?

**Server: .NET Core 3.0 (3.0.0-preview8.19405.7)**
Grpc.AspNetCore.Server 0.1.22-pre3

**Client: Android/Kotlin**
io.grpc:grpc-okhttp:1.23.0
io.grpc:grpc-protobuf-lite:1.23.0
io.grpc:grpc-stub:1.23.0
com.google.protobuf:protoc:3.9.1
io.grpc:protoc-gen-grpc-java:1.23.0
com.google.protobuf:protoc-gen-javalite:3.0.0

### What did you expect to see?

No errors or more detailed error information.

**Comment by bingoo** [comment]
The problem is in IIS, which I was using to host gRPC. IIS does not support response trailers.

More information: https://github.com/aspnet/AspNetCore/issues/9020
