### ISSUE TITLE
cpu running into full load,Possibly infinite loop

### ISSUE THREAD

**Issue by kivn2014** [grpc/grpc-java#6101]
Problem representation ：https://github.com/grpc/grpc-java/issues/2832
i hava same Problem.

```
$ thread -n 3
"grpc-default-worker-ELG-3-4" Id=102 cpuUsage=97% RUNNABLE
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(DefaultHttp2RemoteFlowController.java:374)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.write(DefaultHttp2RemoteFlowController.java:547)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.write(WeightedFairQueueByteDistributor.java:604)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:292)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(WeightedFairQueueByteDistributor.java:325)
    at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:273)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:627)
    at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:267)
    at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:200)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:739)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:731)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:978)
    at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:253)
    at io.grpc.netty.WriteQueue.flush(WriteQueue.java:124)
    at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:32)
    at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:44)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```

What version of gRPC are you using?
    1.20.0
What JVM are you using (java -version)?
   openjdk version "1.8.0_222"
netty version
    4.1.34

**Comment by ejona86** [comment]
Hmmm... Are you absolutely sure you are using Netty 4.1.34? If using Maven, you can run `mvn dependency:tree` and look for the version of `netty-codec-http2`. If it is easy, try swapping to `io.grpc:grpc-netty-shaded`, since it has its own copy of Netty.

The line number of `DefaultHttp2RemoteFlowController.java:374` seems suspect for being Netty 4.1.34. Could you provide some other line numbers seen during the infinite loop?

**Comment by ejona86** [comment]
Closing due to inactivity and it seems the user was most likely running an older version of Netty with the bug.
