### ISSUE TITLE
Classpath clash between protobuf-java & protobuf-lite

### ISSUE THREAD

**Issue by SButterfly** [grpc/grpc-java#6332]
Hello, there are some equal classes in protobuf-java and protobuf-lite:

```
There are clashed archives:
com/google/protobuf/protobuf-java/3.6.1/protobuf-protobuf-java-3.6.1.jar
com/google/protobuf/protobuf-lite/3.0.1/protobuf-protobuf-lite-3.0.1.jar
Conflicted classes:
    com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream
    com.google.protobuf.AbstractMessageLite$Builder
    com.google.protobuf.AbstractMessageLite
    and 137 more
```

And both these libraries are used in grpc-protobuf: 
```
|-->contrib/java/io/grpc/grpc-protobuf/1.24.0
|   |-->contrib/java/io/grpc/grpc-api/1.24.0 (*)
|   |-->contrib/java/com/google/protobuf/protobuf-java/3.9.0 (omitted because of confict with 3.6.1)
|   |-->contrib/java/com/google/guava/guava/23.0 (*)
|   |-->contrib/java/com/google/api/grpc/proto-google-common-protos/1.12.0
|   |   |-->contrib/java/com/google/protobuf/protobuf-java/3.5.1 (omitted because of confict with 3.6.1)
|   |-->contrib/java/io/grpc/grpc-protobuf-lite/1.24.0
|   |   |-->contrib/java/io/grpc/grpc-api/1.24.0 (*)
|   |   |-->contrib/java/com/google/protobuf/protobuf-lite/3.0.1
|   |   |-->contrib/java/com/google/guava/guava/23.0 (*)
```

It would be great to fix dublicated classes at grpc-protobuf.
Thank you

**Comment by ran-su** [comment]
You should not use `grpc-protobuf` and `grpc-protobuf-lite` at the same time. The `protobuf-lite` is mainly for Android and the `protobuf` is for all other uses.

**Comment by SButterfly** [comment]
I don't use. `grpc-protobuf-lite` come as dependency of `grpc-protobuf`
See dependency tree in my first comment.

**Comment by ran-su** [comment]
We have some exclusion to make sure our dependency is right. In your case, it looks like the conflict is introduced somewhere else in your project. We do not using `protobuf 3.6.1` in `grpc-java 1.24.0` but `3.6.1` shows in your log.

**Comment by SButterfly** [comment]
Hello @ran-su 
I found out that `protobuf` has dependency on `protobuf-lite`:

ProtoUtils: https://github.com/grpc/grpc-java/blob/93ead9d666faae89d77e41b9ac134dc2c5705f3b/protobuf/src/main/java/io/grpc/protobuf/ProtoUtils.java#L57

ProtoLiteUtils: https://github.com/grpc/grpc-java/blob/e526891a2ba4404396edec7deafa8963cc2a6b0d/protobuf-lite/src/main/java/io/grpc/protobuf/lite/ProtoLiteUtils.java#L84

And `ProtoUtils.marshaller()` is called in generated gRPC proto compiler (version 1.9.1) stubs.
If I manually exclude` protobuf-lite` from classpath, I get an error:

```
2019-11-27 17:46:57,341 ERROR [SpringApplication main] Application run failed
java.lang.NoClassDefFoundError: io/grpc/protobuf/lite/ProtoLiteUtils
	at io.grpc.protobuf.ProtoUtils.marshaller(ProtoUtils.java:44) ~[grpc-protobuf-1.9.1.jar:1.9.1]
	at com.coreos.jetcd.api.KVGrpc.getRangeMethod(KVGrpc.java:51) ~[jetcd-core-0.0.2.jar:?]
	at com.coreos.jetcd.api.KVGrpc.<clinit>(KVGrpc.java:33) ~[jetcd-core-0.0.2.jar:?]
	at com.coreos.jetcd.internal.impl.ClientConnectionManager.newStub(ClientConnectionManager.java:142) ~[jetcd-core-0.0.2.jar:?]
	at com.coreos.jetcd.internal.impl.KVImpl.<init>(KVImpl.java:54) ~[jetcd-core-0.0.2.jar:?]
	at com.coreos.jetcd.internal.impl.ClientImpl.newClient(ClientImpl.java:132) ~[jetcd-core-0.0.2.jar:?]
	at com.coreos.jetcd.internal.impl.ClientImpl.getKVClient(ClientImpl.java:74) ~[jetcd-core-0.0.2.jar:?]
	at ru.yandex.market.application.properties.etcd.grpc.EtcdClientImpl.kvClient(EtcdClientImpl.java:71) ~[market-application-etcd-properties.jar:?]
	at ru.yandex.market.application.properties.etcd.grpc.EtcdClientImpl.getKeysPrefixedBy(EtcdClientImpl.java:99) ~[market-application-etcd-properties.jar:?]
	at ru.yandex.market.application.properties.etcd.grpc.EtcdClientImpl.getProperties(EtcdClientImpl.java:87) ~[market-application-etcd-properties.jar:?]
	at ru.yandex.market.application.properties.etcd.resources.RemoteEtcdResource.getProperties(RemoteEtcdResource.java:39) ~[market-application-etcd-properties.jar:?]
	at ru.yandex.market.application.properties.etcd.resources.EtcdResource.getInputStream(EtcdResource.java:51) ~[market-application-etcd-properties.jar:?]
	at ru.yandex.market.application.properties.etcd.resources.VirtualFileEtcdResource.getInputStream(VirtualFileEtcdResource.java:64) ~[market-application-etcd-properties.jar:?]
	at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:159) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:99) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:73) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:59) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:86) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at ru.yandex.market.clab.common.props.AppPropertySourcesContextInitializer.initialize(AppPropertySourcesContextInitializer.java:33) ~[content-lab-common.jar:?]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at ru.yandex.market.clab.ui.main.ContentLabUIApplication.main(ContentLabUIApplication.java:59) ~[content-lab-ui-main.jar:?]
Caused by: java.lang.ClassNotFoundException: io.grpc.protobuf.lite.ProtoLiteUtils
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 23 more
```

How can I disable protobuf-lite from classpath and still make code work?
