### ISSUE TITLE
TLS support for Android with server's certificate signed by a trusted CA

### ISSUE THREAD

**Issue by IrvingMg** [grpc/grpc-java#6413]
I have an Android client which I'm trying to connect to my server via TLS. The server already has a certificate signed by a trusted CA and I was able to connect to the server using TLS with gRPC-Swift, so I think the server it's working properly. However, with Android I'm having troubles to establish the secure connection. 

I saw the example from the [documentation](https://grpc.io/docs/guides/auth/) which uses :
`ManagedChannel channel = ManagedChannelBuilder.forAddress("myservice.example.com", 443)
    .build();`

But It didn't work. I also tried out with code from this another [example](https://github.com/grpc/grpc-java/blob/015b2fffa31995ff7923b4076f9324d464b7d827/android-interop-testing/app/src/main/java/io/grpc/android/integrationtest/TesterOkHttpChannelBuilder.java) : 

```
ManagedChannelBuilder channelBuilder = ManagedChannelBuilder.forAddress(host, port);
((OkHttpChannelBuilder) channelBuilder).useTransportSecurity();
((OkHttpChannelBuilder) channelBuilder).sslSocketFactory((SSLSocketFactory) SSLSocketFactory.getDefault());
this.channel = channelBuilder.build();
```

But it didn't work neither.

Finally, I added Conscrypt like the [README](https://github.com/grpc/grpc-java/blob/v1.24.0/SECURITY.md#tls-on-android) said using this line before the channel creation:

`Security.insertProviderAt(Conscrypt.newProvider(), 1);`

But I'm not sure if I'm using it properly. 

Additionally, when I see my logcat I can't see an error related to TLS, so I can't find what error is happening.
My gradle file has these dependencies:

```
implementation 'org.conscrypt:conscrypt-android:2.2.1'
implementation 'io.grpc:grpc-okhttp:1.25.0'
implementation 'io.grpc:grpc-protobuf-lite:1.25.0'
implementation 'io.grpc:grpc-stub:1.25.0'
```

I have tested my code with unsecure connections and all works fine but now with TLS I can't find what is casuing the error. So, my question is how can I connect to my server via TLS from an Android client? Do I need to add another thing?

**Comment by dapengzhang0** [comment]
>  when I see my logcat I can't see an error related to TLS, so I can't find what error is happening.

Can you turn on grpc java log level to FINE and print more logs?
```
io.grpc.okhttp.level = FINE
io.grpc.internal.level = FINE
```

**Comment by IrvingMg** [comment]
@dapengzhang0  Thanks for your reply. I enable the log level following this [answer](https://stackoverflow.com/a/35558201) so I added to my code this:

```
AndroidLoggingHandler.reset(new AndroidLoggingHandler());
java.util.logging.Logger.getLogger("io.grpc.okhttp").setLevel(Level.FINE);
java.util.logging.Logger.getLogger("io.grpc.internal").setLevel(Level.FINE);
```

Then I tried out establish the connection using:

```
this.channel = OkHttpChannelBuilder.forAddress(host, port)
                        .useTransportSecurity()
                        .build();
```

And I see this new message:

```
2019-11-11 16:35:05.470 14460-14493/com.sdks.test D/.grpc.internal.DnsNameResolver: JndiResourceResolverFactory not available, skipping.
2019-11-11 16:35:05.473 14460-14493/com.sdks.test D/.grpc.internal.DnsNameResolver: java.lang.ClassNotFoundException: javax.naming.directory.InitialDirContext
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at io.grpc.internal.JndiResourceResolverFactory.initJndi(JndiResourceResolverFactory.java:67)
        at io.grpc.internal.JndiResourceResolverFactory.<clinit>(JndiResourceResolverFactory.java:52)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at io.grpc.internal.DnsNameResolver.getResourceResolverFactory(DnsNameResolver.java:685)
        at io.grpc.internal.DnsNameResolver.<clinit>(DnsNameResolver.java:121)
        at io.grpc.internal.BaseDnsNameResolverProvider.newNameResolver(BaseDnsNameResolverProvider.java:48)
        at io.grpc.internal.BaseDnsNameResolverProvider.newNameResolver(BaseDnsNameResolverProvider.java:30)
        at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:711)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:593)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
        at com.sdks.low.storage.V1Client.<init>(V1Client.java:80)
        at com.sdks.low.storage.V1ClientTest.setUpClient(V1ClientTest.java:97)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.naming.directory.InitialDirContext" on path: DexPathList[[zip file "/data/app/com.sdks.test-YUkp4dH9pe0-yY8iS3WpWw==/base.apk"],nativeLibraryDirectories=[/data/app/com.sdks.test-YUkp4dH9pe0-yY8iS3WpWw==/lib/x86, /data/app/com.sdks.test-YUkp4dH9pe0-yY8iS3WpWw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at io.grpc.internal.JndiResourceResolverFactory.initJndi(JndiResourceResolverFactory.java:67) 
        at io.grpc.internal.JndiResourceResolverFactory.<clinit>(JndiResourceResolverFactory.java:52) 
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at io.grpc.internal.DnsNameResolver.getResourceResolverFactory(DnsNameResolver.java:685) 
        at io.grpc.internal.DnsNameResolver.<clinit>(DnsNameResolver.java:121) 
        at io.grpc.internal.BaseDnsNameResolverProvider.newNameResolver(BaseDnsNameResolverProvider.java:48) 
        at io.grpc.internal.BaseDnsNameResolverProvider.newNameResolver(BaseDnsNameResolverProvider.java:30) 
        at io.grpc.NameResolverRegistry$NameResolverFactory.newNameResolver(NameResolverRegistry.java:154) 
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:711) 
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:593) 
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524) 
        at com.sdks.low.storage.V1Client.<init>(V1Client.java:80) 
        at com.sdks.low.storage.V1ClientTest.setUpClient(V1ClientTest.java:97) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) 
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) 
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) 
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) 
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) 
        at org.junit.runners.Suite.runChild(Suite.java:128) 
        at org.junit.runners.Suite.runChild(Suite.java:27) 
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) 
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) 
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) 
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) 
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) 
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) 
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56) 
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392) 
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189) 
2019-11-11 16:35:05.578 14460-14496/com.sdks.test D/.grpc.internal.DnsNameResolver: Address resolution failure
```

**Comment by dapengzhang0** [comment]
Anything after the last line
```
2019-11-11 16:35:05.578 14460-14496/com.sdks.test D/.grpc.internal.DnsNameResolver: Address resolution failure
```
 (I expect some exception detail or stack trace of it)?
(The log before this line is normal, it just skips JNDI, which is not available for all android)

**Comment by IrvingMg** [comment]
I also get this but I'm not sure if it's useful.

```
2019-11-11 17:24:16.295 15156-15192/? W/pc.internal.ManagedChannelImpl: [{0}] Failed to resolve name. status={1}
2019-11-11 17:24:16.302 15156-15189/? W/com.sdks.test: Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
2019-11-11 17:24:16.304 15156-15189/? E/TestRunner: failed: servers(com.sdks.low.storage.V1ClientTest)
2019-11-11 17:24:16.304 15156-15189/? E/TestRunner: ----- begin exception -----
2019-11-11 17:24:16.304 15156-15189/? E/TestRunner: java.lang.AssertionError: Values should be different. Actual: 0
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failEquals(Assert.java:185)
        at org.junit.Assert.assertNotEquals(Assert.java:199)
        at org.junit.Assert.assertNotEquals(Assert.java:211)
        at com.sdks.low.storage.V1ClientTest.servers(V1ClientTest.java:127)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
2019-11-11 17:24:16.304 15156-15189/? E/TestRunner: ----- end exception -----
2019-11-11 17:24:16.305 15156-15189/? I/TestRunner: finished: servers(com.sdks.low.storage.V1ClientTest)
2019-11-11 17:24:16.308 15156-15156/? I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
2019-11-11 17:24:16.311 15156-15189/? I/TestRunner: run finished: 1 tests, 1 failed, 0 ignored
2019-11-11 17:24:16.482 8886-8941/? I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
2019-11-11 17:24:16.482 8886-8941/? W/ErrorReporter: reportError [type: 211, code: 393244, bug: 0]: errorCode: 393244, engine: 0
2019-11-11 17:24:16.483 8886-8941/? I/MicroDetector: Keeping mic open: false
2019-11-11 17:24:16.483 8886-8941/? I/MicroDetectionWorker: #onError(false)
2019-11-11 17:24:16.560 1792-2546/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2019-11-11 17:24:16.560 1792-2546/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2019-11-11 17:24:16.581 15156-15189/? I/MonitoringInstr: waitForActivitiesToComplete() took: 0ms
2019-11-11 17:24:16.581 15156-15156/? I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
2019-11-11 17:24:16.582 2063-3114/? I/ActivityManager: Force stopping com.sdks.test appid=10134 user=0: finished inst
2019-11-11 17:24:16.582 2063-3114/? I/ActivityManager: Killing 15156:com.sdks.test/u0a134 (adj 0): stop com.sdks.test
2019-11-11 17:24:16.582 2063-15199/? W/Binder: Outgoing transactions from this process must be FLAG_ONEWAY
    java.lang.Throwable
        at android.os.BinderProxy.transact(BinderProxy.java:480)
        at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
        at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
2019-11-11 17:24:16.583 15143-15143/? D/AndroidRuntime: Shutting down VM
2019-11-11 17:24:16.635 1777-1777/? I/Zygote: Process 15156 exited due to signal 9 (Killed)
2019-11-11 17:24:16.652 2063-5692/? W/ActivityManager: Invalid packageName: com.sdks
2019-11-11 17:24:16.661 2063-2094/? I/libprocessgroup: Successfully killed process cgroup uid 10134 pid 15156 in 78ms
2019-11-11 17:24:17.560 1792-2546/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
```

**Comment by dapengzhang0** [comment]
There should be some stack trace of the `addressesException` printed, based on this line of source code 
https://github.com/grpc/grpc-java/blob/v1.25.0/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L438
but it seems it's not showing up.

Anyway, I suspect there was no internet available on your device/emulator at that moment so you saw "Address resolution failure". The code is not running okhttp transport or TLS handshake yet.

**Comment by IrvingMg** [comment]
Actually I had that message because I had a typo in my hostname :sweat:. So the message that I get now is this:

`2019-11-11 19:32:33.190 7709-7745/com.sdks.test D/.grpc.internal.DnsNameResolver: No TXT records found for {0}`

What does it mean?

**Comment by sanjaypujare** [comment]
Seems harmless based on the [code](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L321) and it came out only because of increased log level.

**Comment by IrvingMg** [comment]
@sanjaypujare  Thanks for your reply. I thought that message might help to find the problem... So what else I could do? Because I see almost the same logs that I showed above

**Comment by sanjaypujare** [comment]
Someone else recently reported TLS issue (https://github.com/grpc/grpc-java/issues/6412) on Android and they are making progress based on the tips given. Could you take a look at that?

**Comment by dapengzhang0** [comment]
@IrvingMg After fixing the typo in your hostname, what error did you see? `No TXT records found for {0}` was harmless as @sanjaypujare said.

**Comment by IrvingMg** [comment]
Now I can see this error:

```
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err: io.grpc.StatusRuntimeException: UNAVAILABLE
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at authgate.V1Grpc$V1BlockingStub.servers(V1Grpc.java:432)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at com.sdks.low.storage.V1Client.servers(V1Client.java:193)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at com.sdks.low.storage.V1ClientTest.servers(V1ClientTest.java:126)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:128)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.Suite.runChild(Suite.java:27)
2019-11-12 12:12:27.577 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err: Caused by: java.lang.RuntimeException: TLS ALPN negotiation failed with protocols: [grpc-exp, h2]
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at io.grpc.okhttp.OkHttpProtocolNegotiator.negotiate(OkHttpProtocolNegotiator.java:96)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:147)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:568)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-11-12 12:12:27.579 7293-7327/com.sdks.test W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

It seems that my issue is related to #3277  [](url)

**Comment by dapengzhang0** [comment]
@IrvingMg So this error
```
2019-11-12 12:12:27.578 7293-7327/com.sdks.test W/System.err: Caused by: java.lang.RuntimeException: TLS ALPN negotiation failed with protocols: [grpc-exp, h2]
```

means your conscrypt may not load (successfully). 

Can you move 
```java
Security.insertProviderAt(Conscrypt.newProvider(), 1);
```
to an earliest place to execute, e.g. in a static block of the main class?

**Comment by IrvingMg** [comment]
I'm running Android Instrumented Unit Tests and I have my test file in this way:

```
@BeforeClass
 public static void setUp {
        Security.insertProviderAt(Conscrypt.newProvider(), 1);
        ...
    }

@Test
public void servers() {
   // Here I'm trying to establish the connection and make a request
}
```

Is that enough time to load Conscrypt?

**Comment by dapengzhang0** [comment]
I'm not sure for Android Instrumented Unit Tests `setUp()` uses the same class loader for your Android app (suppose you run grpc client in an app). You might also add this line in your app.

**Comment by IrvingMg** [comment]
Finally the issue was solved. The problem was that the server wasn't support ALPN and HTTP2 and they're mandatory for gRPC-Java.  So now, the server has enabled them and the Android client works creating the channel like this:

`ManagedChannel channel = ManagedChannelBuilder.forAddress(host, port).build();`

@sanjaypujare @dapengzhang0 Thanks a lot for your help!

**Comment by dapengzhang0** [comment]
@IrvingMg Oh that's interesting. Glad to know you fixed by yourself. I don't know how grpc-swift over TLS worked, did grpc-swift use HTTP/2 but ignore ALPN or just use HTTP 1.1?

**Comment by IrvingMg** [comment]
I seems that gRPC-Swift tries to use HTTP/2 with ALPN at first but if the server doesn't support them (like in my case), then it uses HTTP 1.1. Now that the server has enabled HTTP/2 and ALPN, gRPC-Swift is using them too.
