### ISSUE TITLE
gRPC Server Exception : Connection reset

### ISSUE THREAD

**Issue by halimpuckjava** [grpc/grpc-java#6423]
hi

why each time client send request to serer, sever respond with internal exeption: 
```
INFO: Transport failed
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)

```

**Comment by dapengzhang0** [comment]
From the above stack trace there is little information we can find. Apparently the connection is broken, but we can't see details. 
Can you turn on java logging on both the client and server side?

```
.level = ALL
io.grpc.netty.level = FINE
io.netty.handler.codec.http2.Http2FrameLogger.level = FINE
io.grpc.netty.NettyClientHandler = ALL
io.grpc.netty.NettyServerHandler = ALL
```

**Comment by AngerM** [comment]
I'm seeing similar messages using for the grpc-health-probe.

```
 Nov 19, 2019 5:23:25 PM io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport notifyTerminated 
INFO: Transport failed 
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer 
```

These happen every time grpc-health-probe calls my apps health check. Which is a fairly straightforward implementation running grpc 1.25


```
  private class HealthCheck() : HealthGrpc.HealthImplBase() {
    private val log = LoggerFactory.getLogger(this.javaClass.name)

    private val isHealthy: HealthCheckResponse
      get() {
        return if (DBConnection.read != null && DBConnection.write != null) healthy else unhealthy
      }

    @Trace
    override fun check(req: HealthCheckRequest?, resp: StreamObserver<HealthCheckResponse>) {
      log.info("health check called")
      resp.onNext(isHealthy)
      resp.onCompleted()
    }

    @Trace
    override fun watch(request: HealthCheckRequest?, resp: StreamObserver<HealthCheckResponse>) {
      log.info("health watch called")
      resp.onNext(isHealthy)
      resp.onCompleted()
    }

    companion object {
      private val healthy = HealthCheckResponse.newBuilder()
        .setStatus(HealthCheckResponse.ServingStatus.SERVING)
        .build()
      private val unhealthy = HealthCheckResponse.newBuilder()
        .setStatus(HealthCheckResponse.ServingStatus.NOT_SERVING)
        .build()
    }
  }
}
```

**Comment by AngerM** [comment]
Note: I wasn't seeing these with grpc 1.24 so it appears to be either a breaking change or regression

**Comment by dapengzhang0** [comment]
Didn't get reply from OP @halimpuckjava .

>Note: I wasn't seeing these with grpc 1.24 so it appears to be either a breaking change or regression

@AngerM Not sure if your problem is exactly the same as the OP's. We didn't observe this regression yet. grpc 1.25 bumped netty to 4.1.42.Final from 4.1.38.Final (and netty-tcnative to 2.0.26.Final from 2.0.25.Final if using TLS). Can you exclude the transitive dependency of netty from grpc and specify the old netty version explicitly in your gradle file and test? Appreciate it if you could help.

**Comment by AngerM** [comment]
@dapengzhang0 so it looks like the netty upgrade broke the filtering added by https://github.com/grpc/grpc-java/pull/5873/files

So those error messages are being logged at INFO instead of FINE

**Comment by dapengzhang0** [comment]
> @dapengzhang0 so it looks like the netty upgrade broke the filtering added by https://github.com/grpc/grpc-java/pull/5873/files
So those error messages are being logged at INFO instead of FINE

@creamsoup As offline discussed, would you fix the issue reported by @AngerM ? (Note that this may not be the original issue reported by @halimpuckjava).

**Comment by dapengzhang0** [comment]
Close due to being not active.
