### ISSUE TITLE
Fix flaky OkHttp test

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#646]
We're seeing an OkHttp test fail randomly, with the output below.

```
io.grpc.transport.okhttp.OkHttpClientTransportTest > outboundFlowControl FAILED
    Argument(s) are different! Wanted:
    frameWriter.data(
        false,
        3,
        <any>,
        32773
    );
    -> at io.grpc.transport.okhttp.OkHttpClientTransportTest.outboundFlowControl(OkHttpClientTransportTest.java:462)
    Actual invocation has different arguments:
    frameWriter.data(
        false,
        3,
        Buffer[size=16384 md5=c975385526568787c9110176db80e1ca],
        16384
    );
    -> at io.grpc.transport.okhttp.AsyncFrameWriter$9.doRun(AsyncFrameWriter.java:160)
        at sun.reflect.GeneratedConstructorAccessor3.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at io.grpc.transport.okhttp.OkHttpClientTransportTest.outboundFlowControl(OkHttpClientTransportTest.java:462)

    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at io.grpc.transport.okhttp.OkHttpClientTransportTest.tearDown(OkHttpClientTransportTest.java:170)
```

**Comment by ejona86** [comment]
Having seen it in a while. I think the machine we were able to reproduce it on isn't running the tests any more. Closing, but it should be reopened if we notice it again.
