### ISSUE TITLE
exception is raised "java.lang.IllegalStateException: listener unset" - depends on executor?

### ISSUE THREAD

**Issue by mazurkin** [grpc/grpc-java#6486]
### What version of gRPC-Java are you using?

grpc-version=1.24.2
protobuf-version=3.9.2

### What is your environment?

Linux with Java 11 in a Docker contaoner (openjdk:11.0.5)

### What did you expect to see?

no exceptions

### What did you see instead?

I see 2-3 exceptions per second:

```
[04 Dec 2019 14:13:39,288][ERROR][SerializingExecutor,gRPC-pool-32] - Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed@6e3b9e72
java.lang.IllegalStateException: listener unset
    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.getListener(ServerImpl.java:743) ~[grpc-core-1.24.2.jar:1.24.2]
    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.access$2900(ServerImpl.java:720) ~[grpc-core-1.24.2.jar:1.24.2]
    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:864) ~[grpc-core-1.24.2.jar:1.24.2]
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.24.2.jar:1.24.2]
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.24.2.jar:1.24.2]
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
```

### Steps to reproduce the bug

Use `io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder` and assign `ThreadPoolExecutor` with some pretty small queue (I have `ArrayBlockingQueue` with capacity 1024). Then create some incoming traffic (I have ~ 12K incoming requests per seconds).

After I increased the queue to 8096 the problem has gone.

**Comment by mazurkin** [comment]
and I have set `ThreadPoolExecutor.AbortPolicy()` there

**Comment by ejona86** [comment]
Before the IllegalStateException, was there a RejectedExecutionException? That would be the "bug" here: #636.

**Comment by mazurkin** [comment]
yes, it was `RejectedExecutionException` before `IllegalStateException`

I was really surprised to find out that the default executor is `Executors.newCachedThreadPool()` which potentially could lead to unlimited number of threads.

So my motivation was to set some executor with limiter number of thread and limited queue. To "fail fast" and reject a request if the server is not able to handle all incoming load.

**Comment by mazurkin** [comment]
I faced the same problem on client side but I've already found https://github.com/grpc/grpc-java/issues/4544

So for now I set a larger queue and switched to `ThreadPoolExecutor.CallerRunsPolicy()` both on server and client side

**Comment by ejona86** [comment]
We do encourage setting a fixed-size thread pool when able. We use cached by default because we don't know what concurrency level the application needs (which is especially important if it is blocking).

It does seem #636 is the problem here. If grpc handled RejectedExecutionException better then this would have been fine.
