### ISSUE TITLE
android client can't work in release

### ISSUE THREAD

**Issue by 1wayticket** [grpc/grpc-java#6612]
grpc version:1.26.0
When I update from 1.11.0 to 1.26.0, I can work in debug mode,but when I build in relase mode and open proguard_rule,It can't work and I get these error;
 ```java
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err: 01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err: java.lang.RuntimeException: Field playbookId_ for com.mszmapp.detective.g$cc not found. Known fields are [private java.lang.String com.mszmapp.detective.g$cc.a, private java.lang.String com.mszmapp.detective.g$cc.b, private java.lang.String com.mszmapp.detective.g$cc.c, private static final com.mszmapp.detective.g$cc com.mszmapp.detective.g$cc.d, private static volatile com.google.protobuf.Parser com.mszmapp.detective.g$cc.e]
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.MessageSchema.reflectField(MessageSchema.java:608)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:502)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:221)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:85)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:171)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:391)
01-16 17:22:22.429 31439-31439/com.mszmapp.detective W/System.err:     at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:399)
```
and these are build.gradle
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.11.0"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.26.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                java { option 'lite' }
            }
            task.plugins {
                grpc { // Options added to --grpc_out
                    option 'lite'
                }
            }
        }
    }
}


dependencies{
...
    // You need to build grpc-java to obtain these libraries below.
    implementation 'io.grpc:grpc-okhttp:1.26.0'
    // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-protobuf-lite:1.26.0'
    // CURRENT_GRPC_VERSION
    implementation 'io.grpc:grpc-stub:1.26.0'
...
}
```
Is there anything wrong or I lost the proguard_rules?

**Comment by ericgribkoff** [comment]
I don't think this is an issue with gRPC itself, at least based on the stack track provided. It looks like you are running into the same, or a similar, issue as reported here: https://github.com/protocolbuffers/protobuf/issues/6463. This [comment](https://github.com/protocolbuffers/protobuf/issues/6463#issuecomment-553183215) links to a proguard config that may workaround the issue. Can you try that and see if it helps?

**Comment by 1wayticket** [comment]
I

> I don't think this is an issue with gRPC itself, at least based on the stack track provided. It looks like you are running into the same, or a similar, issue as reported here: [protocolbuffers/protobuf#6463](https://github.com/protocolbuffers/protobuf/issues/6463). This [comment](https://github.com/protocolbuffers/protobuf/issues/6463#issuecomment-553183215) links to a proguard config that may workaround the issue. Can you try that and see if it helps?

I have change the build.gradle as the android expample and it works
```
 protobuf {
    protoc { artifact = 'com.google.protobuf:protoc:3.10.0' }
    plugins {
        javalite { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.25.0'
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                javalite {}
                grpc { option 'lite' }
            }
        }
    }
}
```
I have tried the proguard_rules in the demo but still useless,I will try the issue later and show the result later.Anywhere,thanks a lot.

**Comment by 1wayticket** [comment]
> I don't think this is an issue with gRPC itself, at least based on the stack track provided. It looks like you are running into the same, or a similar, issue as reported here: [protocolbuffers/protobuf#6463](https://github.com/protocolbuffers/protobuf/issues/6463). This [comment](https://github.com/protocolbuffers/protobuf/issues/6463#issuecomment-553183215) links to a proguard config that may workaround the issue. Can you try that and see if it helps?

It works when I add the proguard below
```
-keep class * extends com.google.protobuf.GeneratedMessageLite { *; }
```
I will change the proguard in the next version.Thanks a lot.
