### ISSUE TITLE
INTERNAL: gRPC frame header malformed: reserved bits not zero

### ISSUE THREAD

**Issue by MostafaRamadan1** [grpc/grpc-java#6720]
Version:
Grpc 1.20

Environment:
Window 10, Java 8

I sending punch of files through grpc, I send the files as chucks in form of bytes, the programs runs well, but when I send too much file chunks it gives me these error:

```
Feb 15, 2020 9:04:05 PM io.grpc.netty.NettyServerStream$TransportState deframeFailed
WARNING: Exception processing message
io.grpc.StatusRuntimeException: INTERNAL: gRPC frame header malformed: reserved bits not zero
	at io.grpc.Status.asRuntimeException(Status.java:523)
	at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:377)
	at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:267)
	at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:177)
	at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:193)
	at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:266)
	at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:198)
	at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:466)
	at io.grpc.netty.NettyServerHandler.access$800(NettyServerHandler.java:99)
	at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:735)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:236)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
```

**Sometimes give these error also** 

```
Feb 15, 2020 9:04:05 PM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@6367084e
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:523)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:289)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:263)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:737)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1184)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:881)
```

Any ideas that could help, it seems that the netty server not able to handle too much data to received or what?

**Comment by ericgribkoff** [comment]
The error indicates that requests are not being serialized properly by the client. What language and gRPC version are you using on the client side?

**Comment by ejona86** [comment]
Closing because we don't have enough information. Can be reopened if we get back information about the client-side.
