### ISSUE TITLE
java.lang.IllegalStateException: lbHelper is null

### ISSUE THREAD

**Issue by malgun-gothic** [grpc/grpc-java#6842]
### What version of gRPC-Java are you using?
1.12.0
### What is your environment?

ubuntu 18.04.4 LTS, openJdk version 1.8.0_242

### What did you expect to see?
no exception error
### What did you see instead?
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
Caused by: java.lang.IllegalStateException: lbHelper is null

```
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:419)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:591)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: lbHelper is null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:319)
	at io.grpc.internal.ManagedChannelImpl.enterIdleMode(ManagedChannelImpl.java:376)
	at io.grpc.internal.ManagedChannelImpl.access$1000(ManagedChannelImpl.java:81)
	at io.grpc.internal.ManagedChannelImpl$IdleModeTimer.run(ManagedChannelImpl.java:311)
	at io.grpc.internal.Rescheduler$ChannelFutureRunnable.run(Rescheduler.java:106)
	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:73)
	at io.grpc.internal.ManagedChannelImpl$1AutoDrainChannelExecutor.execute(ManagedChannelImpl.java:561)
	at io.grpc.internal.Rescheduler$FutureRunnable.run(Rescheduler.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	... 3 more
```

**Comment by voidzcy** [comment]
Can you provide more background for this? Like a brief description of your use case, how you triggered this error, any investigations you did, etc. It would be best if you can provide a minimal reproducible example.

**Comment by creamsoup** [comment]
`1.12.0` is very old. can you try in a newer version?

**Comment by ejona86** [comment]
This sounds familiar. `enterIdleMode`, yeah... I can't find it, but I'm pretty certain this was fixed already. I don't think it is #4630.

v1.12.0 is far too old, so closing. If you experience the problem with a newer version of gRPC this can be reopened.
