### ISSUE TITLE
Problem with TLS,Cert,Sec?

### ISSUE THREAD

**Issue by elmartinno** [grpc/grpc-java#6849]
Hello all,

Im student from Slovakia and I try to create my first app.

I have app app deployed on Openshift. I cant resolve the following error on client side:

```
2020-03-22 18:57:52.063 ERROR 1 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]] with root cause
java.security.cert.CertificateException: No subject alternative DNS name matching foo.test.google.fr found.
	at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:214) ~[na:1.8.0_242]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:96) ~[na:1.8.0_242]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:462) ~[na:1.8.0_242]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:428) ~[na:1.8.0_242]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:261) ~[na:1.8.0_242]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144) ~[na:1.8.0_242]
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslTlsv13X509ExtendedTrustManager.checkServerTrusted(OpenSslTlsv13X509ExtendedTrustManager.java:223) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:255) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:701) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:594) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1175) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1292) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:200) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1324) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[grpc-netty-shaded-1.28.0.jar!/:1.28.0]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

Client code:
```
    ManagedChannel channel = NettyChannelBuilder.forAddress("grpc-server-rest11.192.168.42.59.nip.io", 443)
            .sslContext(
                    GrpcSslContexts.forClient()
                            .trustManager(TlsTesting.loadCert("ca.pem"))
                            .sslProvider(SslProvider.OPENSSL)
                            .build())
            .overrideAuthority("foo.test.google.fr")
            .build();
```

Server part:
```
		Server server = ServerBuilder.forPort(9111)
				.useTransportSecurity(
						TlsTesting.loadCert("server1.pem"),
						TlsTesting.loadCert("server1.key"))
				.addService(new AccountController())
				.addService(new TurnoverController())
				.build();
		server.start();
		System.out.println("Started");
```

Thanks for all answers. Ports are different because Openshift work curious

**Comment by sanjaypujare** [comment]
Your cert was created with hostname `foo.test.google.fr` whereas you are accessing it as `grpc-server-rest11.192.168.42.59.nip.io` . Make sure they match - take a look at SECURITY.md in the repo.

**Comment by elmartinno** [comment]
I used testing cert from io.grpc.testing.TlsTesting. I thought that cert will work without issues - locally on localhost it work fine. How do you think "make sure they match"? I have on both side (client - server) certs from io.grpc.testing.TlsTesting. It should work, shouldnt?
Thanks for answers

**Comment by sanjaypujare** [comment]
TLS certificate checks have to be satisfied as part of security so you can't expect "cert will work without issues" unless you ensure certs satisfy those checks.

I don't have the reference handy but I think it was mentioned somewhere how you can modify `/etc/hosts` on your client machine to point `foo.test.google.fr` to your actual server (in your case  `grpc-server-rest11.192.168.42.59.nip.io`). Take a look at https://webmasters.stackexchange.com/questions/17562/host-change-what-is-a-good-method-for-testing-ssl-before-pointing-dns-at-new-h

**Comment by elmartinno** [comment]
Hi,
I found out that: .overrideAuthority("foo.test.google.fr") will add it to /etc/hosts: https://stackoverflow.com/questions/54575904/grpc-ssl-no-subject-alternative-names-present
But thanks for point

**Comment by sanjaypujare** [comment]
Yes, if you are willing (or able) to modify the source code you should use `overrideAuthority()`. But note that "overrideAuthority" does not add it to `/etc/hosts` . It is an alternative to it and it's changes the check logic within the gRPC library.

**Comment by elmartinno** [comment]
I used .overrideAuthority("foo.test.google.fr") and no news. Unfortunatelly it looks that in openshft pods i cannot modify /etc/hosts. Is there other way how to do it? Change of certs will fix it?

**Comment by sanjaypujare** [comment]
`overrideAuthority` should actually do it and it a better alternative because of all the issues you mentioned. You will have to debug why it is not working for you. Cannot be a problem in gRPC if gRPC tests/examples are working.

**Comment by ejona86** [comment]
Everything looks in-place from what I can tell. `overrideAuthority()` does not modify `/etc/hosts`; it works just within the library, but it is conceptually _like_ you modified `/etc/hosts`.

The best way to solve this is to look at the certificate the server is exposing. `server1.pem` totally has a Subject Alternative Name (SAN) that matches (note that the Subject doesn't matter, I'm only including it here since it easily identifies the cert):
```
$ openssl x509 -in testing/src/main/resources/certs/server1.pem -text
Certificate:
    Data:
...
        Subject: C = US, ST = Illinois, L = Chicago, O = "Example, Co.", CN = *.test.google.com
...
            X509v3 Subject Alternative Name: 
                DNS:*.test.google.fr, DNS:waterzooi.test.google.be, DNS:*.test.youtube.com, IP Address:192.168.1.3
...
```

So I'm suspicious of whether the cert we think is being used is actually being used. Maybe there is a proxy in the middle. That seems especially likely given the host name is "grpc-server-rest", emphasis on REST.

You can access `https//grpc-server-rest11.192.168.42.59.nip.io/` in a web browser and see what certificate is used. You can reference an [old presentation](https://drive.google.com/file/d/1n512QqAqvQdJnyfBV-MAgs0v7W5CiXdw/view?usp=sharing) starting on page 39 on how to do that. But it is easiest for me to tell you how to do it on the command line:
```sh
$ # This should dump out stuff including -----END CERTIFICATE----- and then hang
$ # Press Ctrl-C once it hangs
$ openssl s_client grpc-server-rest11.192.168.42.59.nip.io:443
$ # copy the text starting at -----BEGIN CERTIFICATE----- and ending with
$ # -----END CERTIFICATE----- (including that header/footer) to a new file
$ # (say, grpc-server-rest.pem)
$ # Then dump the details about the cert
$ openssl x509 -in grpc-server-rest.pem -text
```

**Comment by ejona86** [comment]
Closing since there's not much more we can do. If we get more info, we can reopen.
