### ISSUE TITLE
An Authentication object was not found in the SecurityContext

### ISSUE THREAD

**Issue by ajayyuvraj** [grpc/grpc-java#6922]
How do we fix this ?  Issue when adding @PreAuthorize in gRPC Method... For rest it works fine...
Note: : Application is deployed in wildfly

```
Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@527ca940: org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:379)
        at org.springframework.security.access.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:223)
        at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
```

**Comment by sanjaypujare** [comment]
This article https://eng.revinate.com/2017/11/07/grpc-spring-security.html might be helpful. Couple of things I can think of:

- use gRPC interceptor(s) as described in the article above
- use  `@RequestMapping` to map the incoming gRPC method to a request path.

The gRPC Spring Boot Starter module also might be helpful.

**Comment by ejona86** [comment]
We don't have Spring expertise, so can't help much more than we already have. Closing due to inability to help and lack of activity.
