### ISSUE TITLE
Mutual TLS with chained (root ca -> intermediate ca -> client) certificates

### ISSUE THREAD

**Issue by enguerrand** [grpc/grpc-java#6934]
I can't get mutual tls to run with a certificate **chain** on the client side.

I ran https://github.com/grpc/grpc-java/tree/master/examples/example-tls successfully with mutual tls enabled but the client's certificate file ../../testing/src/main/resources/certs/client.pem is just a plain certificate without the full chain. 

I tried to get this to run with a client cert that was signed by an intermediate cert which is in turn signed by a (self-signed) root ca cert.

The client is using a chained certificate file that contains (in this order) its own cert, the intermediate's cert and the root's cert.

Both server and client use the root ca cert.pem as their trustCertCollectionFile.

Both server and client have the ip address 127.0.0.1 in there subject alternative names and in the client I changed the line  
 `.overrideAuthority("foo.test.google.fr")  /* Only for using provided test certs. */`  
to  
`.overrideAuthority("127.0.0.1")  /* Only for using provided test certs. */`

I am getting the following error: 
```
Apr 16, 2020 5:32:27 PM io.grpc.examples.helloworldtls.HelloWorldClientTls greet
INFO: Will try to greet 127.0.0.1 ...
Apr 16, 2020 5:32:27 PM io.grpc.examples.helloworldtls.HelloWorldClientTls greet
WARNING: RPC failed: Status{code=UNAVAILABLE, description=io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0], cause=javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1003)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1267)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1221)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1292)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1335)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:205)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1324)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
Is this supposed to work? I can generate test certificates to reproduce the problem if needed but note that the following openssl command line claims that my certs are ok:
```bash
openssl verify -CAfile rootca/certs/ca.cert.pem\
 -untrusted intermediate/<MY_INTERM_CA>/certs/ca.cert.pem\
 intermediate/<MY_INTERM_CA>/certs/<HOST>.cert.pem
```

Note also that the sample runs fine with my certs when I do not use mutual TLS although the server also uses a full chain certificate.

**Comment by sanjaypujare** [comment]
> I ran https://github.com/grpc/grpc-java/tree/master/examples/example-tls successfully with mutual tls enabled but the client's certificate file ../../testing/src/main/resources/certs/client.pem is just a plain certificate without the full chain.

It still has the root so it is a chain albeit without an intermediate.

> 
> I tried to get this to run with a client cert that was signed by an intermediate cert which is in turn signed by a (self-signed) root ca cert.

It should work.

> Both server and client have the ip address 127.0.0.1 in there subject alternative names and in the client I changed the line
> `.overrideAuthority("foo.test.google.fr") /* Only for using provided test certs. */`
> to
> `.overrideAuthority("127.0.0.1") /* Only for using provided test certs. */`

I am assuming this change with the original set of certs works? So that we can isolate problems.

> 
> I am getting the following error:
> 
> ```
> ...
cause=javax.net.ssl.SSLHandshakeException: error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
> 	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1003)

Are you able to see anything on the server side? May be increase logging level on both to get more details?


> ```
> 
> Is this supposed to work? I can generate test certificates to reproduce the problem if needed but note that the following openssl command line claims that my certs are ok:
> 
> ```shell
> openssl verify -CAfile rootca/certs/ca.cert.pem\
>  -untrusted intermediate/<MY_INTERM_CA>/certs/ca.cert.pem\
>  intermediate/<MY_INTERM_CA>/certs/<HOST>.cert.pem
> ```
> 
> Note also that the sample runs fine with my certs when I do not use mutual TLS although the server also uses a full chain certificate.

Things I would try:
- change only one thing at a time and see where it breaks
- switch the certs i.e. use your client certs on the server side and try just TLS to see if it works. That would tell us if this is a cert issue.

**Comment by enguerrand** [comment]
> Are you able to see anything on the server side? May be increase logging level on both to get more details?

Thanks a lot for this hint!  
After increasing the log level on the server side using instructions given in this [stackoverflow post] I saw that the certificate was rejected with the following reason:

`Extended key usage does not permit use for TLS client authentication`

I was using an [openssl configuration based on an openssl ca tutorial] and had used the wrong section to sign the client's key.
Using "-extensions usr_cert" instead of "-extensions server_cert" in the "openssl ca..." command during certificate creation solved the problem.

Thanks again!


[stackoverflow post]: https://stackoverflow.com/questions/50243717/grpc-logger-level/50377418#50377418
[openssl configuration based on an openssl ca tutorial]: https://jamielinux.com/docs/openssl-certificate-authority/appendix/intermediate-configuration-file.html
