### ISSUE TITLE
Double-closure of call during interop tests

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#694]
I find it in the stderr of the test report of Netty, Netty local channel, and OkHttp. I see it printed out to my console once, so I think that may be from the InProcess test.

This exception very likely means we have a bug and are double-closing.

```
java.lang.IllegalStateException: call already closed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at io.grpc.ServerImpl$ServerCallImpl.close(ServerImpl.java:507)
	at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:65)
	at io.grpc.testing.TestUtils$1$1.close(TestUtils.java:109)
	at io.grpc.stub.ServerCalls$ResponseObserver.onError(ServerCalls.java:237)
	at io.grpc.testing.integration.TestServiceImpl$ResponseDispatcher.dispatchChunk(TestServiceImpl.java:277)
	at io.grpc.testing.integration.TestServiceImpl$ResponseDispatcher.access$000(TestServiceImpl.java:207)
	at io.grpc.testing.integration.TestServiceImpl$ResponseDispatcher$1.run(TestServiceImpl.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ejona86** [comment]
I've confirmed that I've also seen the output in the stderr of the test report for the InProcess test.

**Comment by ejona86** [comment]
This appears to be a bug in `TestServiceImpl`. I modified ServerCallImpl (so ignore its line numbers) to get a backtrace when close() was called and report that backtrace if close is called again. You can see below that they are the same. In examining `TestServiceImpl`, it's obvious that it doesn't handle cancellations properly, as `ResponseDispatcher.run()` doesn't prevent future chunks for the call from being processed if the call is closed, yet dispatchChunk will repeatedly call onError because each message sent will throw an exception.

```
java.lang.IllegalStateException: Already closed, cause is previous close
       at io.grpc.ServerImpl$ServerCallImpl.close(ServerImpl.java:521)
        at io.grpc.ForwardingServerCall.close(ForwardingServerCall.java:65)
        at io.grpc.testing.TestUtils$1$1.close(TestUtils.java:111)
        at io.grpc.stub.ServerCalls$ResponseObserver.onError(ServerCalls.java:242)
        at io.grpc.testing.integration.TestServiceImpl$ResponseDispatcher.dispatchChunk(TestServiceImpl.java:277)
        at io.grpc.testing.integration.TestServiceImpl$ResponseDispatcher.access$000(TestServiceImpl.java:207)
        at io.grpc.testing.integration.TestServiceImpl$ResponseDispatcher$1.run(TestServiceImpl.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: closed here before
        at io.grpc.ServerImpl$ServerCallImpl.close(ServerImpl.java:525)
        ... 13 more
```
