### ISSUE TITLE
Error when building OkHttpChannelBuilder: "No enum constant" TLS_CHACHA20_POLY1305_SHA256

### ISSUE THREAD

**Issue by bshaffer** [grpc/grpc-java#7093]
### What version of gRPC-Java are you using?

v1.29 (the latest at the time of writing)

### What is your environment?
OS: Both Linux and OSX experience this error
JDK: Only happening on 1.11

### What did you expect to see?
Creating an `OkHttpChannelBuilder` using `grpc/okhttp` should work

### What did you see instead?

```
java.lang.IllegalArgumentException: No enum constant com.squareup.okhttp.CipherSuite.TLS_CHACHA20_POLY1305_SHA256
    at java.base/java.lang.Enum.valueOf(Enum.java:240)
    at com.squareup.okhttp.CipherSuite.valueOf(CipherSuite.java:32)
    at com.squareup.okhttp.CipherSuite.forJavaName(CipherSuite.java:373)
    at com.squareup.okhttp.ConnectionSpec.cipherSuites(ConnectionSpec.java:104)
    at io.grpc.okhttp.Utils.convertSpec(Utils.java:83)
    at io.grpc.okhttp.OkHttpChannelBuilder.connectionSpec(OkHttpChannelBuilder.java:304)
    at io.grpc.testing.integration.Http2OkHttpTest.createChannelBuilder(Http2OkHttpTest.java:97)

```
### Steps to reproduce the bug

I have noticed this constant exists in `okhttp` ([here](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cipher-suite/-t-l-s_-c-h-a-c-h-a20_-p-o-l-y1305_-s-h-a256/)) but not [here](https://square.github.io/okhttp/3.x/okhttp/). I believe the difference is one is okhttp3 (`4.x`) and one is not. Any idea how to resolve this?

Here is the code used to build the object:

```java
import com.squareup.okhttp.ConnectionSpec;
import io.grpc.internal.GrpcUtil;
import io.grpc.internal.testing.TestUtils;
import io.grpc.okhttp.OkHttpChannelBuilder;
import io.grpc.testing.integration.AbstractInteropTest;
import java.net.InetSocketAddress;

int port = ((InetSocketAddress) getListenAddress()).getPort();
OkHttpChannelBuilder builder = OkHttpChannelBuilder.forAddress("localhost", port)
    .maxInboundMessageSize(AbstractInteropTest.MAX_MESSAGE_SIZE)
    .connectionSpec(new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
        .cipherSuites(TestUtils.preferredTestCiphers().toArray(new String[0]))
        .build())
    .overrideAuthority(GrpcUtil.authorityFromHostAndPort(
        TestUtils.TEST_SERVER_HOST, port));
```

Any help is appreciated!

**Comment by bshaffer** [comment]
I was able to fix this by removing the call to `TestUtils.preferredTestCiphers()`:

```java
    .connectionSpec(new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
        .build())
```
