### ISSUE TITLE
Please add "s" in domain name

### ISSUE THREAD

**Issue by ppgutkus** [grpc/grpc-java#7123]
Not sure why I got wrong domain name "dialogflow.googleapi.com" instead of "dialogflow.googleapi**s**.com".

Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedSockeException: Network is unreachable: no further information: **dialogflow.googleapi.com**/2404:6800:4001:800:0:0:0:200a:443

`com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNVAILABLE: io exception 
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptonFactory.java:69) 
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptonFactory.java:72) 
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptonFactory.java:60) 
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFture.onFailure(GrpcExceptionCallable.java:97) 
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) 
at com.google.common.util.concurrent.Futures$CallbackListener.run(Futurs.java:1050) 
at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecuor.java:30) 
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbsractFuture.java:1176) 
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuure.java:969) 
at com.google.common.util.concurrent.AbstractFuture.setException(AbstratFuture.java:760) 
at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:52) 
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.jav:501) 
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:42) 
at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClienCallImpl.java:689) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(lientCallImpl.java:577) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosd.runInternal(ClientCallImpl.java:751) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosd.runInContext(ClientCallImpl.java:740) 
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) 
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:12) 
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
at java.util.concurrent.FutureTask.run(Unknown Source) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTaskaccess$201(Unknown Source) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTaskrun(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source) Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous tas failed  
at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiExcetion(ApiExceptions.java:57)  
at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java112)  
at com.google.cloud.dialogflow.v2.SessionsClient.detectIntent(SssionsClient.java:251)  
at com.google.cloud.dialogflow.v2.SessionsClient.detectIntent(SssionsClient.java:187)  
at org.javacord.examplebot.command.Command.onMessageCrate(Command.java:291)  
at org.javacord.core.util.event.EventDispatcher.lambda$dispatchessageCreateEvent$95(EventDispatcher.java:3413)  
at org.javacord.core.util.event.EventDispatcherBase.lambda$disptchEvent$10(EventDispatcherBase.java:197)  
at org.javacord.core.util.event.EventDispatcherBase.lambda$checRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:265)  
at java.util.concurrent.Executors$RunnableAdapter.call(Unknownource)  
at java.util.concurrent.FutureTask.run(Unknown Source)  ... 3 moreCaused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception 
at io.grpc.Status.asRuntimeException(Status.java:533) ... 16 moreCaused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedSockeException: Network is unreachable: no further information: dialogflow.googleapi.com/2404:6800:4001:800:0:0:0:200a:443Caused by: java.net.SocketException: Network is unreachable: no further informaion 
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) 
at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) 
at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doinishConnect(NioSocketChannel.java:330) 
at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstracNioUnsafe.finishConnect(AbstractNioChannel.java:334) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectdKey(NioEventLoop.java:702) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectdKeysOptimized(NioEventLoop.java:650) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectdKeys(NioEventLoop.java:576) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLop.java:493) 
at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecuor$4.run(SingleThreadEventExecutor.java:989) 
at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(hreadExecutorMap.java:74) 
at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnabl.run(FastThreadLocalRunnable.java:30) 
at java.lang.Thread.run(Unknown Source)`

**Comment by ppgutkus** [comment]
For now, correct domain name but still got the same error.

`com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception 
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:69) 
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72) 
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60) 
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) 
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68) 
at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1050) 
at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30) 
at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1176) 
at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:969) 
at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:760) 
at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:526) 
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:501) 
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) 
at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) 
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) 
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) 
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) 
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
at java.util.concurrent.FutureTask.run(Unknown Source) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.lang.Thread.run(Unknown Source)Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed 
at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) 
at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) 
at com.google.cloud.dialogflow.v2.SessionsClient.detectIntent(SessionsClient.java:251) 
at com.google.cloud.dialogflow.v2.SessionsClient.detectIntent(SessionsClient.java:187) 
at org.javacord.examplebot.command.Command.onMessageCreate(Command.java:291) 
at org.javacord.core.util.event.EventDispatcher.lambda$dispatchMessageCreateEvent$95(EventDispatcher.java:3413) 
at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$10(EventDispatcherBase.java:197) 
at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$18(EventDispatcherBase.java:265) 
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
at java.util.concurrent.FutureTask.run(Unknown Source)... 3 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception 
at io.grpc.Status.asRuntimeException(Status.java:533)... 16 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: no further information: dialogflow.googleapis.com/2404:6800:4001:804:0:0:0:200a:443
Caused by: java.net.SocketException: Network is unreachable: no further information 
at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) 
at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source) 
at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) 
at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) 
at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) 
at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
at java.lang.Thread.run(Unknown Source)`

**Comment by voidzcy** [comment]
Can you describe more details about your use case, what you are running and what you expect to achieve? This looks like something wrong in client libraries or gax, or the application configuration. I don't see things abnormal on gRPC side, you may want to file issues on dialogflow client library repository.

**Comment by ppgutkus** [comment]
I've created issue in dialogflow in repositoriy I will close this.
