### ISSUE TITLE
Executing a jar-with-dependencies built with maven-assembly-plugin 3.2+ throws "java.lang.IllegalStateException"

### ISSUE THREAD

**Issue by kurtisvg** [grpc/grpc-java#7124]
### What version of gRPC-Java are you using?
`io.grpc:grpc-core:jar:1.30.0`

### What is your environment?

OS: Linux
JDK: tested with both OpenJDK 8 (1.8.0_232) and 11 (11.0.7)

### What did you expect to see?

A perfect, flawless execution of a jar-with-dependencies that would be spoken of for generations to come. 

### What did you see instead?

```
Jun 17, 2020 2:01:34 PM io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<1>: (dlp.googleapis.com:443)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:94)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:65)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:375)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:469)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:473)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:253)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:210)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:94)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:314)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:288)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:200)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:86)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.dlp.v2.DlpServiceClient.redactImage(DlpServiceClient.java:302)
	at dlp.snippets.RedactImageFile.redactImageFile(RedactImageFile.java:79)
	at dlp.snippets.RedactImageFile.main(RedactImageFile.java:44)

Exception in thread "main" com.google.api.gax.rpc.InternalException: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:67)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1050)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1176)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:719)
	at com.google.common.util.concurrent.ForwardingListenableFuture.addListener(ForwardingListenableFuture.java:45)
	at com.google.api.core.ApiFutureToListenableFuture.addListener(ApiFutureToListenableFuture.java:52)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1023)
	at com.google.api.core.ApiFutures.addCallback(ApiFutures.java:63)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:67)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:86)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.dlp.v2.DlpServiceClient.redactImage(DlpServiceClient.java:302)
	at dlp.snippets.RedactImageFile.redactImageFile(RedactImageFile.java:79)
	at dlp.snippets.RedactImageFile.main(RedactImageFile.java:44)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		... 4 more
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:94)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:65)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:375)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:469)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:473)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:253)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:210)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.google.api.gax.grpc.GrpcHeaderInterceptor$1.start(GrpcHeaderInterceptor.java:94)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:314)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:288)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:200)
	at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:58)
	at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:86)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.tracing.TracedUnaryCallable.futureCall(TracedUnaryCallable.java:75)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.api.gax.rpc.UnaryCallable.futureCall(UnaryCallable.java:87)
	at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
	at com.google.cloud.dlp.v2.DlpServiceClient.redactImage(DlpServiceClient.java:302)
	at dlp.snippets.RedactImageFile.redactImageFile(RedactImageFile.java:79)
	at dlp.snippets.RedactImageFile.main(RedactImageFile.java:44)

```

### Steps to reproduce the bug

1. `git clone https://github.com/GoogleCloudPlatform/java-docs-samples`
2. `cd java-docs-samples/dlp`
3. `git checkout 24c0de4cea54900e12bb6156d55fbe8ddbff4038`
3. `mvn -DskipTests clean compile package`
4. ` java -cp target/dlp-samples-1.0-jar-with-dependencies.jar dlp.snippets.RedactImageFile`

Using any version of `maven-assemble-plugin` `3.2.0` or higher seems to introduce the problem, so the issue is likely related to some change there. There was a similar error reported in #5493 - not sure if it's related to what's happening here.

/cc @lesv

**Comment by ejona86** [comment]
The error information has been truncated. There is another exception in the stacktrace that provides more information. Please provide the exception that the StatusRuntimeException was "caused by."

**Comment by ejona86** [comment]
```
$ git clone https://github.com/GoogleCloudPlatform/java-docs-samples
$ cd java-docs-samples/dlp
$ patch -p2 <<EOF
diff --git a/dlp/pom.xml b/dlp/pom.xml
index 97246c9d..1f86d67f 100644
--- a/dlp/pom.xml
+++ b/dlp/pom.xml
@@ -73,5 +73,18 @@
     </dependency>
   </dependencies>
 
+  <build>
+    <plugins>
+      <plugin>
+        <artifactId>maven-assembly-plugin</artifactId>
+        <configuration>
+          <descriptorRefs>
+            <descriptorRef>jar-with-dependencies</descriptorRef>
+          </descriptorRefs>
+        </configuration>
+      </plugin>
+    </plugins>
+  </build>
+
 </project>
 <!-- [END dlp_pom] -->
EOF
$ mvn -DskipTests=true compile assembly:single
$ GOOGLE_APPLICATION_CREDENTIALS=... java -cp target/dlp-samples-1.0-jar-with-dependencies.jar dlp.snippets.RedactImageFile
... hangs, nothing printed
```

This was a horrible reproduction experience. Every step was wrong, and it did not reproduce the issue. Since this is a public example, please provide the full, untrimmed exception chain with backtraces.

**Comment by kurtisvg** [comment]
@ejona86 Sorry about that - the branch was updated to remove uberjar instructions, and I intended (yet somehow failed spectacularly) to reference that specific commit.

Repro instructions and full trace were updated.

**Comment by ejona86** [comment]
@kurtisvg, thanks, that's much better. It appears maven-assembly-plugin is not merging service files. I'm not familiar with maven-assembly-plugin, but maybe https://stackoverflow.com/a/49689041/4690866 is helpful. I know that for maven-shade-plugin you have to use `<transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>`.

**Comment by kurtisvg** [comment]
Ok, I'll marked this as closed since it seems like the issue is entirely due to a change in behavior from the `maven-assembly-plugin`.
