### ISSUE TITLE
migrating thread deframer breaks weighted_round_robin_test_cpp_java

### ISSUE THREAD

**Issue by creamsoup** [grpc/grpc-java#7168]
importing MigratingThreadDeframer(#5820), we discovered that some OkHttp users have a race with following stack trace. 

```
java.lang.IllegalStateException: Headers should be received prior to messages.
at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
at io.grpc.internal.RetriableStream$Sublistener.messagesAvailable(RetriableStream.java:952)
at io.grpc.internal.DelayedStream$DelayedStreamListener$1.run(DelayedStream.java:438)
at io.grpc.internal.DelayedStream$DelayedStreamListener.drainPendingCallbacks(DelayedStream.java:510)
at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:168)
at io.grpc.internal.DelayedStream.setStream(DelayedStream.java:132)
at io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:358)
at io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:341)
at io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:300)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

MigratingThreadDeframer is disabled in OkHttp via #7167. We believe the disabled code pass improved the performance.

cc @ejona86

**Comment by creamsoup** [comment]
even with #7167, there is a test that fails with following stack trace.

```
java.lang.IllegalStateException: Headers should be received prior to messages.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at io.grpc.internal.RetriableStream$Sublistener.messagesAvailable(RetriableStream.java:952)
        at io.grpc.internal.DelayedStream$DelayedStreamListener.messagesAvailable(DelayedStream.java:433)
        at io.grpc.internal.ForwardingClientStreamListener.messagesAvailable(ForwardingClientStreamListener.java:44)
        at io.grpc.internal.AbstractStream$TransportState.messagesAvailable(AbstractStream.java:184)
        at io.grpc.internal.ForwardingDeframerListener.messagesAvailable(ForwardingDeframerListener.java:32)
        at io.grpc.internal.SquelchLateMessagesAvailableDeframerListener.messagesAvailable(SquelchLateMessagesAvailableDeframerListener.java:49)
        at io.grpc.internal.MigratingThreadDeframer$1.run(MigratingThreadDeframer.java:125)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ejona86** [comment]
We believe this was not a problem with OkHttp but with retries. We're looking into fixing the retry problem. Once done we'd reenable the migrating deframer for okhttp.

**Comment by creamsoup** [comment]
> We believe this was not a problem with OkHttp but with retries. We're looking into fixing the retry problem. Once done we'd reenable the migrating deframer for okhttp.

confirmed with ConcurrencyTest with retry using netty

**Comment by creamsoup** [comment]
## steps to reproduce

enable MigratingThreadDeframer
`git revert c6bd97245c4bf21e423c5ee7740e9635ab8f1646`

modify `ConcurrencyTest.java`
```
diff --git a/interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java b/interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java
index 2b6e0b690..1c38e771c 100644
--- a/interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java
+++ b/interop-testing/src/test/java/io/grpc/testing/integration/ConcurrencyTest.java
@@ -61,7 +61,7 @@ import org.junit.runners.JUnit4;
 @RunWith(JUnit4.class)
 public class ConcurrencyTest {
 
-  @Rule public final Timeout globalTimeout = Timeout.seconds(60);
+  @Rule public final Timeout globalTimeout = Timeout.seconds(15);
   
   /**
    * A response observer that signals a {@code CountDownLatch} when the proper number of responses
@@ -221,6 +221,7 @@ public class ConcurrencyTest {
         .overrideAuthority(TestUtils.TEST_SERVER_HOST)
         .negotiationType(NegotiationType.TLS)
         .sslContext(sslContext)
+        .enableRetry()
         .build();
   }
 }
```

Test should fail
`./gradlew :grpc-interop-testing:{cleanTest,test} --tests="io.grpc.testing.integration.ConcurrencyTest"`

**Comment by dapengzhang0** [comment]
Reopened by the revert #7198

**Comment by ejona86** [comment]
I've dug into weighted_round_robin_test_cpp_java and I think the problem may be triggered when the server closes before half-close. But I'm also seeing on server-side: "INTERNAL: Encountered end-of-stream mid-frame". Some brief running with a race detector makes me think there's a threading issue.

I'm going to have to come back to this later, just due to time constraints. So I'm going to close this issue and reopen the original #6696.
