### ISSUE TITLE
Received DATA frame for an unknown stream xxxxx

### ISSUE THREAD

**Issue by gongziyiyi** [grpc/grpc-java#7182]
### What version of gRPC-Java are you using?
1.30.2
### What is your environment?
oraclejdk1.8
### What did you expect to see?
no unnecessary exception logs
### What did you see instead?
no unnecessary exception logs
### Steps to reproduce the bug
a client-side streaming rpc such as:
`rpc battleMsg (stream SCProto) returns (stream CSProto) {}`
```java
StreamObserver<SCProto> obClient = stub.battleMsg(new StreamObserver<CSProto>() {
            @Override
            public void onNext(CSProto request) {
                // do sth    
            }

            @Override
            public void onError(Throwable throwable) {
            }

            @Override
            public void onCompleted() {
                obClient.onCompleted();
            }
        });
```
when I closed stream on server side, client-side reacted `obClient.onCompleted()`. And then server-side print a excption:
```
WARN [grpc-default-worker-ELG-1-2] Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 73
at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:596) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:239) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.50.Final.jar:4.1.50.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
``` 
in netty/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java
```java
private boolean shouldIgnoreHeadersOrDataFrame(ChannelHandlerContext ctx, int streamId, Http2Stream stream, 
String frameName) throws Http2Exception {
    if (stream == null) {
        if (streamCreatedAfterGoAwaySent(streamId)) {
            logger.info("{} ignoring {} frame for stream {}. Stream sent after GOAWAY sent",
                    ctx.channel(), frameName, streamId);
            return true;
        }

        // Make sure it's not an out-of-order frame, like a rogue DATA frame, for a stream that could
        // never have existed.
        verifyStreamMayHaveExisted(streamId);

        // Its possible that this frame would result in stream ID out of order creation (PROTOCOL ERROR) and its
        // also possible that this frame is received on a CLOSED stream (STREAM_CLOSED after a RST_STREAM is
        // sent). We don't have enough information to know for sure, so we choose the lesser of the two errors.
        throw streamError(streamId, STREAM_CLOSED, "Received %s frame for an unknown stream %d",
                            frameName, streamId);
    } else if (stream.isResetSent() || streamCreatedAfterGoAwaySent(streamId)) {
        // If we have sent a reset stream it is assumed the stream will be closed after the write completes.
        // If we have not sent a reset, but the stream was created after a GoAway this is not supported by
        // DefaultHttp2Connection and if a custom Http2Connection is used it is assumed the lifetime is managed
        // elsewhere so we don't close the stream or otherwise modify the stream's state.

        if (logger.isInfoEnabled()) {
            logger.info("{} ignoring {} frame for stream {}", ctx.channel(), frameName,
                    stream.isResetSent() ? "RST_STREAM sent." :
                        ("Stream created after GOAWAY sent. Last known stream by peer " +
                            connection.remote().lastStreamKnownByPeer()));
        }

        return true;
    }
    return false;
}
```
Maybe this is the case `its also possible that this frame is received on a CLOSED stream`.
In addition, if I don't do `obClient.onCompleted()`, there will be a memory leak.

**Comment by voidzcy** [comment]
The logged stream error seems to be legit. The client reacts with `obClient.onCompleted()` (client sends trailers) when the server side already fully closed the stream, the server considers the stream as unknown. You would not need to do `obClient.onCompleted()` in response observer's `onComplete()` callback. What's the memory leak observation you get? After the call is ended, you are still supposed to shut down the channel.

**Comment by gongziyiyi** [comment]
It was my fault,without a deep understanding of the system.
