### ISSUE TITLE
Http2 exception while connecting gRPC server running on cloud 

### ISSUE THREAD

**Issue by kanistha** [grpc/grpc-java#7236]
### What version of gRPC-Java are you using?
java.version: 1.8

### What is your environment?

- Linux  operating system
- Currently gRPC server is running on cloud using a docker image openjdk:8-jre-alpine on port 9090
- gRPC Client is running on my machine currently and trying to connect to server using plaintext.
java.version: 1.8
io.grpc.version: 1.16.1
protobuf-maven-plugin.version: 0.6.1

### What did you expect to see?
Response from cloud GRPC server based on proto response object 

### What did you see instead?
I see following exception:
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

### Steps to reproduce the bug

Both gRPC server and client  either locally and running on cloud then it works, just fails when accessing from local to Azure cloud using AKS.

```
Request started from gRPC client
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at org.grpc.SpeechRecognitionGrpc$SpeechRecognitionBlockingStub.perform(SpeechRecognitionGrpc.java:138)
	at client.SpeechGrpcClient.runGrpcClient(SpeechGrpcClient.java:29)
	at client.SpeechGrpcClient.main(SpeechGrpcClient.java:36)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1
```

Client Code:
```java
 ManagedChannel channel = ManagedChannelBuilder
            //.forAddress("speech-grpc.azurewebsites.net", 80)
            .forAddress("XX.XXX.XXX.XXX", 80)
            .usePlaintext()
            .build();
```

**Comment by ejona86** [comment]
I we look at the error, `Hex dump for first 5 bytes: 485454502f`, we can convert the hex "485454502f" to ASCII, which becomes "HTTP/". So the server is trying to speak HTTP/1.

It seems like you are using an L7 (HTTP) proxy when connecting from local to AKS. You may check to see if it has an "assume HTTP/2" mode for plain-text. You may also check for an L4 (TCP) proxy mode.

**Comment by ericgribkoff** [comment]
I'm going to go ahead and mark this closed. @kanistha, if you have any additional questions or information to add, please feel free to comment and we can reopen.
