### ISSUE TITLE
xxxClient error:  io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found!

### ISSUE THREAD

**Issue by YeSei** [grpc/grpc-java#7263]
Version：

```
<io.grpc.version>1.15.0</io.grpc.version>
<protobuf.version>3.6.1</protobuf.version>
```

proto：

```protobuf
service Action {
    rpc Start (StartRequest) returns (StartReply) {}
}

message StartRequest {
    string cmd = 1;
    int64 timeout = 2;
    string exec_user = 3;
    string working_dir = 4;
    string call_back_http_endpoint = 5;
}


message StartReply {
    string unique_id = 1;
}
```

Client:

```java
public class AgentClient {
    private ActionBlockingStub blockingStub;

    public AgentClient() {
    }

    public String start(AgentRequestParam requestParam) throws InterruptedException {
        ManagedChannel channel = ManagedChannelBuilder
                .forTarget(requestParam.getHostAddress())
                .usePlaintext()
                .build();
        try {
            this.blockingStub = ActionGrpc.newBlockingStub(channel);
            StartRequest request = StartRequest.newBuilder()
                    .setCmd(requestParam.getCommand())
                    .setTimeout(requestParam.getTimeout())
                    .setExecUser(requestParam.getExecUser())
                    .setWorkingDir(requestParam.getWorkingDir())
                    .setCallBackHttpEndpoint(requestParam.getEndPoint())
                    .build();
            StartReply reply = this.blockingStub.start(request);
            return reply.getUniqueId();
        } catch (Exception e) {
            log.error("error,", e);
            return "error";
        } finally {
            channel.shutdownNow();
        }
    }
}
```

Test：

```java
public class AgentClientTest {
    @Test
    public void test() throws InterruptedException {
        AgentClient client = new AgentClient();
        String res = client.start(AgentRequestParam.builder()
                .hostAddress("xxxxxx:50051")
                .command("xx")
                .execUser("admin")
                .workingDir("/tmp/112/112/112")
                .timeout(20L)
                .endPoint("")
                .build());
        System.out.println(res);
    }
}
```

Error:

```java
23:00:07.143 [main] ERROR com.alibaba.tesla.appmanager.channel.common.agent.AgentClient - error,
io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.alibaba.tesla.appmanager.channel.common.agent.action.ActionGrpc$ActionBlockingStub.start(ActionGrpc.java:419)
	at com.alibaba.tesla.appmanager.channel.common.agent.AgentClient.start(AgentClient.java:52)
	at com.alibaba.tesla.appmanager.channel.common.agent.AgentClientTest.test(AgentClientTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
23:00:07.145 [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0x44806949, L:/30.225.4.72:51961 - R:/11.164.62.97:50051] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
error
```

I already know that the remote server is available。but I can't find the error answer。

**Comment by ericgribkoff** [comment]
The `UNIMPLEMENTED` response code indicates that the server you're connecting to does not implement the `start` method of your `Action` service.  However, the "!" exclamation mark in your error code's status doesn't seem to match what a gRPC server would actually produce, assuming you are using a Java server at least (https://github.com/grpc/grpc-java/blob/613439c97e8ab3a62670411fd9367aa126fed2cf/core/src/main/java/io/grpc/internal/ServerImpl.java#L547). Is it possible your service implementation is purposefully returning an `UNIMPLEMENTED` status code with this message?

**Comment by YeSei** [comment]
The `Action` service is implemented by `python`, and the `python` client can work well. So I assume that the server is fine. 
The error message told that `[main] ERROR com.alibaba.tesla.appmanager.channel.common.agent.AgentClient - error,` something wrong in my `AgentClient`, and I can not debug out what wrong with this.

**Comment by ericgribkoff** [comment]
Ok, it looks the like the "Method not found!" message - with "!" - is standard from the gRPC Python [server implementation](https://github.com/grpc/grpc/blob/598e171746576c5398388a4c170ddf3c8d72b80a/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi#L734).

Are you sure that your Python code and Java code are using the same protobuf file, with the same definition of your `Action` service? A discrepancy here would be the simplest explanation for the server failing to find the method your client is calling.

You can enable verbose logging for the Java client via a `logging.properties` file containing something like:

```
handlers=java.util.logging.ConsoleHandler
io.grpc.level=FINE
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
```

And including `-Djava.util.logging.config.file=logging.properties` in your JVM options, probably easiest to do if you can run the code as a Java application rather than within a junit test. For one of our examples included in the grpc-java repo, the command line would look like `JAVA_OPTS='-Djava.util.logging.config.file=logging.properties' build/install/examples/bin/hello-world-client`.

A specific thing to look for in the output would be the `:path` being sent by your client in the headers of the request, which should look something like this: 

```
OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:50051, :path: /helloworld.Greeter/SayHello, ...
```

If you can run your Python client with the environment variables set to enable additional logging, like `GRPC_VERBOSITY=debug GRPC_TRACE=http python greeter_client.py`, then you should also get some output that contains the `:path` header:

```
chttp2_transport.cc:1336]   HTTP:0:HDR:CLI: :path: /helloworld.Greeter/SayHello
```

Specifically we are looking for the path in your Java and Python client to be identical, as in the excerpts above. If they are different than it would seem the two languages are using different definitions of the service.

**Comment by YeSei** [comment]
Thank you! Through your suggestions, I found that the package name defined by my protobuf is inconsistent with the package name of the server.

**Comment by ouaouat** [comment]
I had the same problem and it was for that I extend  2 class from protoServiceGrpc
