### ISSUE TITLE
java.lang.NullPointerException at NettyServerHandler.java:486 using nodejs client

### ISSUE THREAD

**Issue by papirosko** [grpc/grpc-java#7307]
invoking any method with a client, generated with `"protobufjs": "^6.10.1",` and initialized with`"@grpc/grpc-js": "^1.1.3",` results with `java.lang.NullPointerException at NettyServerHandler.java:486` on server side

### What version of gRPC-Java are you using?
1.30.2

### What is your environment?

ubuntu, java 1.8

### What did you see instead?
```
2020-08-10 13:44:36,869 WARN [grpc-nio-worker-ELG-1-2] io.grpc.netty.NettyServerHandler |  Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: 
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:167)
	at io.grpc.netty.NettyServerHandler.newStreamException(NettyServerHandler.java:774)
	at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:495)
	at io.grpc.netty.NettyServerHandler.access$800(NettyServerHandler.java:101)
	at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:797)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onDataRead(DefaultHttp2ConnectionDecoder.java:658)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:242)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:486)
	... 32 common frames omitted
```

**Comment by papirosko** [comment]
hmm. creating a client as described here: https://grpc.github.io/docs/tutorials/basic/node.html, seems working

**Comment by papirosko** [comment]
resolved the issue.

you should provide full package name + method in invokation with leading slashes:

```
        const rpcImpl = function(method, requestData, callback) {
            client.makeUnaryRequest(
                `/full.package/${method.name}`,
                arg => arg,
                arg => arg,
                requestData,
                callback
            )
        };
```

(this example is from https://github.com/protobufjs/protobuf.js?files=1#using-services)

**Comment by sanjaypujare** [comment]
@papirosko could you close the issue if it is resolved? Thanks

**Comment by papirosko** [comment]
Yes. Close please. Btw the exception should say that method was not found, instead of npe. But there is already an issue for this

**Comment by sanjaypujare** [comment]
> Yes. Close please. Btw the exception should say that method was not found, instead of npe. But there is already an issue for this
