### ISSUE TITLE
io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: string is too large

### ISSUE THREAD

**Issue by YeSei** [grpc/grpc-java#7329]
When I use `BlockingStub` call two operations and then close。

```java
//build a client,have a BlockingStub.
client = agentClientFactory.buildAgentClient(requestParam);
detailReply = client.actionDetail(requestParam);
stdoutReply = client.actionStdout(requestParam);
//close channel
client.shutdownNow();
```

it throws Exceptions like this：

```java
io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: string is too large
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.alibaba.tesla.appmanager.channel.common.agent.action.ActionGrpc$ActionBlockingStub.stdout(ActionGrpc.java:455)
	at com.alibaba.tesla.appmanager.channel.common.agent.AgentClient.actionStdout(AgentClient.java:149)
	at com.alibaba.tesla.appmanager.channel.service.exec.ChannelTaskHostExecutorImpl.lambda$processQueryDetail$2(ChannelTaskHostExecutorImpl.java:257)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: string is too large
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.alibaba.tesla.appmanager.channel.common.agent.action.ActionGrpc$ActionBlockingStub.stdout(ActionGrpc.java:455)
	at com.alibaba.tesla.appmanager.channel.common.agent.AgentClient.actionStdout(AgentClient.java:149)
	at com.alibaba.tesla.appmanager.channel.service.exec.ChannelTaskHostExecutorImpl.lambda$processQueryDetail$2(ChannelTaskHostExecutorImpl.java:257)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
io.grpc.StatusRuntimeException: UNKNOWN: Exception calling application: string is too large
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at com.alibaba.tesla.appmanager.channel.common.agent.action.ActionGrpc$ActionBlockingStub.stdout(ActionGrpc.java:455)
	at com.alibaba.tesla.appmanager.channel.common.agent.AgentClient.actionStdout(AgentClient.java:149)
	at com.alibaba.tesla.appmanager.channel.service.exec.ChannelTaskHostExecutorImpl.lambda$processQueryDetail$2(ChannelTaskHostExecutorImpl.java:257)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by YeSei** [comment]
`GRPC server` is implemented by `python`

**Comment by ejona86** [comment]
Looks like that is being generated by the Python server. https://github.com/grpc/grpc/blob/9eebb6d13d7c1188ca27cb7b77150d77790d1a44/src/python/grpcio_testing/grpc_testing/_server/_rpc.py#L89-L95

It looks like the service implementation fails with the error "string is too large":
https://github.com/grpc/grpc/blob/c683d803306ec3b64bb2e868f8f5118bdecb27ea/src/python/grpcio_testing/grpc_testing/_server/_service.py#L46-L52

So any investigation should probably happen on the Python-side; the Java client doesn't know anything more than it already reported.

**Comment by YeSei** [comment]
> Looks like that is being generated by the Python server. https://github.com/grpc/grpc/blob/9eebb6d13d7c1188ca27cb7b77150d77790d1a44/src/python/grpcio_testing/grpc_testing/_server/_rpc.py#L89-L95
> 
> It looks like the service implementation fails with the error "string is too large":
> https://github.com/grpc/grpc/blob/c683d803306ec3b64bb2e868f8f5118bdecb27ea/src/python/grpcio_testing/grpc_testing/_server/_service.py#L46-L52
> 
> So any investigation should probably happen on the Python-side; the Java client doesn't know anything more than it already reported.

Yes, The server limits the transfer size. Thank you!
