### ISSUE TITLE
Intermitent errors under load: INTERNAL: Invalid protobuf byte sequence

### ISSUE THREAD

**Issue by mbwhite** [grpc/grpc-java#7336]
Under a load test, I'm seeing the errors below, with the grpc-java.  There is a single service RPC that has bi-directional streams. The errors only occur under load. 

https://github.com/grpc/grpc-java/issues/5997 and others appeared similar, but as far as I can tell I'm synronizing access to the streamObservers.  And this is observed, (only I think) when the message is coming from the server.. not when the response is going back. 

### What version of gRPC-Java are you using?

    compile 'io.grpc:grpc-netty-shaded:1.31.1'
    compile 'io.grpc:grpc-protobuf:1.31.1'
    compile 'io.grpc:grpc-stub:1.31.1'

### What is your environment?

Linux AdoptOpenJDK 11

### What did you expect to see?
No failures :-)

### What did you see instead?

```
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50)
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:822)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:40)
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:273)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:676)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:661)
	... 5 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1258)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:912)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage.<init>(ChaincodeShim.java:190)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage.<init>(ChaincodeShim.java:123)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage$1.parsePartialFrom(ChaincodeShim.java:1835)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage$1.parsePartialFrom(ChaincodeShim.java:1829)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	... 9 more
```

Also sometimes  

```
io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:273)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:676)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:661)
	... 5 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:102)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:627)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage.<init>(ChaincodeShim.java:164)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage.<init>(ChaincodeShim.java:123)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage$1.parsePartialFrom(ChaincodeShim.java:1835)
	at org.hyperledger.fabric.protos.peer.ChaincodeShim$ChaincodeMessage$1.parsePartialFrom(ChaincodeShim.java:1829)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	... 9 more
```

**Comment by mbwhite** [comment]
Follow-up I've since simplified my test such that on the client side (when the error is being seen). There is a single thread that reads the stream, and passes the data to another thread, that then replies. There are the same two threads.

Usual error is 

`com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).`

**Comment by voidzcy** [comment]
The error usually means the message is corrupted. Did you check your sever side logic and see if there is any chance it could corrupt the message? Do you have any proxy in the middle? Also make sure client and server are checking out the same proto definitions if there are changes made recently (we did see users getting this error when their service deployment forgot to pull the latest protos).

**Comment by mbwhite** [comment]
Thanks for the comment @voidzcy 

- there's no proxy, all on the same box
- They *should* be the same proto definitions - as they are coming from the same project with a single source of protos. Apart from a sequence number the data that is being sent is the same everytime.

- Checking the server!

Q:  StreamObservers need to used in a thread-safe manner; does this apply to both streamobservers in the bidirectional case? i.e. you can only use 1 at a time. (I don't think it does - but checking everything :) )

**Comment by mbwhite** [comment]
Guess what... server didn't have a lock around the `streamObserver.onNext()` ... sorry.. feel like a numpty now.
