### ISSUE TITLE
NioEventLoop - Unexpected exception in the selector loop. java.io.IOException: Invalid argument

### ISSUE THREAD

**Issue by mfateev** [grpc/grpc-java#7351]
### What version of gRPC-Java are you using?
    classpath 'com.google.protobuf:protobuf-gradle-plugin:0.8.13'
    api 'io.grpc:grpc-protobuf:1.31.1'
    api 'io.grpc:grpc-stub:1.31.1'
    implementation 'io.grpc:grpc-netty-shaded:1.31.1'
    implementation group: 'com.google.protobuf', name: 'protobuf-java-util', version: '3.13.0'

    JVM:          1.8.0_265 (AdoptOpenJDK 25.265-b01)

### What is your environment?
MacBook Pro15,1
macOS 10.15.6 (19G73)
Darwin 19.6.0

### What did you expect to see?
Either no exception or exception that makes sense to the library consumer.

### What did you see instead?
The following exceptions in my logs:

```
11:08:41.503 [grpc-nio-worker-ELG-1-16] INFO  i.g.n.s.i.n.channel.nio.NioEventLoop - Migrated 0 channel(s) to the new Selector.
11:08:41.505 [grpc-nio-worker-ELG-1-16] WARN  i.g.n.s.i.n.channel.nio.NioEventLoop - Unexpected exception in the selector loop.
java.io.IOException: Invalid argument
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.grpc.netty.shaded.io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:807)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

### Steps to reproduce the bug

I'm able to reproduce it reliably running an integration test for[ my project](https://github.com/temporalio/java-sdk). It the problem is not obvious I can give instructions on executing it in your environment.

**Comment by ejona86** [comment]
This is pretty strange. I wonder if it could be related to https://bugs.openjdk.java.net/browse/JDK-8165000 . How easy would it be to test on Java 9 just to see if it goes away?

**Comment by dapengzhang0** [comment]
ping @mfateev , would the problem go away with Java 9+?

**Comment by ejona86** [comment]
Since we believe this to be a JDK bug, there's not much we can do. gRPC should eventually reconnect, but it's unclear if this exception would then happen again. If you see things hang, we would want to fix that. But if you just see RPCs fail, then this may be about the best we can do.

**Comment by ejona86** [comment]
Seems to be a problem with Java itself and not much to be done about it. If not, comment, and it can be reopened.
