### ISSUE TITLE
Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@7c7357a4 java.lang.NullPointerException

### ISSUE THREAD

**Issue by lamaxiyali** [grpc/grpc-java#7421]
windows10:fabric-gateway-sdk -->grpc-->ubuntu18:fabric1.4 
```
Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed@7c7357a4
java.lang.NullPointerException
	at org.hyperledger.fabric.sdk.Channel.getExecutorService(Channel.java:2032)
	at org.hyperledger.fabric.sdk.Peer.getExecutorService(Peer.java:139)
	at org.hyperledger.fabric.sdk.Peer.reconnectPeerEventServiceClient(Peer.java:394)
	at org.hyperledger.fabric.sdk.PeerEventServiceClient$1.onError(PeerEventServiceClient.java:313)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sanjaypujare** [comment]
This looks like something in the Hyperledger code. Looking at the Hyperledger code for Channel https://github.com/hyperledger/fabric-sdk-java/blob/release-1.4/src/main/java/org/hyperledger/fabric/sdk/Channel.java#L2032 
```
return client.getExecutorService();
```
looks like `client` is null. Can you open this issue there?

**Comment by ejona86** [comment]
Seems like this is not a grpc issue. If not, comment, and it can be reopened.

**Comment by lamaxiyali** [comment]
Thanks, i have solved this problem

**Comment by Davsen39** [comment]
@lamaxiyali Hi please, i'm doing my thesis and i'm here with the same problem. Can you tell me how you solved it? Thank you so much
