### ISSUE TITLE
Crash due to use of getAlpnSelectedProtocol on Android 11

### ISSUE THREAD

**Issue by eleventigerssc** [grpc/grpc-java#7519]
### What version of gRPC-Java are you using?
1.25.0

### What is your environment?
Android 11, target API level 30.

### What did you expect to see?
Possibility to use `grpc-java` in apps targeting API 30 on Android 11 devices.

### What did you see instead?
```
E  java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=redacted,port=443,localPort=40924]
E      at io.grpc.okhttp.internal.OptionalMethod.invoke(OptionalMethod.java:114)
E      at io.grpc.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:135)
E      at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.getSelectedProtocol(OkHttpProtocolNegotiator.java:183)
E      at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:145)
E      at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
E      at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:568)
E      at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E      at java.lang.Thread.run(Thread.java:923)
```
### Steps to reproduce the bug

Use `io.grpc:grpc-okhttp:1.25` transport and issue a gRPC request in an app compiled to target API 30 on Android 11. This happens due to outdated OkHttp while it seems the graylisted `getAlpnSelectedProtocol` method issue was fixed in https://square.github.io/okhttp/changelog_3x/#version-3147 (more info in: https://github.com/square/okhttp/issues/3980). It is not possible to force `grpc-okhttp` to use 3x OkHttp as there are breaking changes, it also seems that the https://github.com/grpc/grpc-java/issues/6119 has stalled.

I am not sure if there is any workaround to this?

**Comment by eleventigerssc** [comment]
This seems to be fixed by https://github.com/grpc/grpc-java/commit/5803dfd9dcca0fba4483fccf724efc1c853a3ada, upgrading to `1.32.2` has solved the issue.
