### ISSUE TITLE
Getting grpc-netty-shaded working in a GraalVM Native Image Build?

### ISSUE THREAD

**Issue by dzou** [grpc/grpc-java#7534]
Hello, I'm working on trying to get client libraries which depend on `grpc-netty-shaded` working with GraalVM native image builds with the Quarkus framework.

I've gotten to the point where I can succesfully compile an application, but at runtime I encountered an error that looks like this and am curious what conditions might cause this:

```
Caused by: java.util.ServiceConfigurationError: io.grpc.NameResolverProvider: Provider io.grpc.internal.DnsNameResolverProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.grpc.ServiceProviders.getCandidatesViaServiceLoader(ServiceProviders.java:111)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:64)
	at io.grpc.NameResolverRegistry.getDefaultRegistry(NameResolverRegistry.java:101)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(AbstractManagedChannelImplBuilder.java:107)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:147)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:142)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:128)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:280)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:166)
	at com.google.cloud.pubsub.v1.stub.GrpcPublisherStub.create(GrpcPublisherStub.java:195)
	at com.google.cloud.pubsub.v1.stub.PublisherStubSettings.createStub(PublisherStubSettings.java:219)
	at com.google.cloud.pubsub.v1.TopicAdminClient.<init>(TopicAdminClient.java:165)
	at com.google.cloud.pubsub.v1.TopicAdminClient.create(TopicAdminClient.java:147)
	at com.google.cloud.pubsub.v1.TopicAdminClient.create(TopicAdminClient.java:139)
```

One tricky point is that Quarkus also pulls in their version of Netty. And I was wondering if `grpc-netty-shaded` can co-exist with another version of Netty on the classpath; I was wondering if this error might be related to this complication.

Curious if you might give some hints for what might be wrong. I.e. Are these providers discovered via reflection for example?

cc/ @meltsufin

**Comment by sanjaypujare** [comment]
Yes, it uses reflection for `DnsNameResolverProvider`. Look at [`io.grpc.NameResolverRegistry.getHardCodedClasses`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolverRegistry.java#L141).

I do see the shaded and unshaded Netty versions together causing a problem although I don't see this problem related.

**Comment by dzou** [comment]
Many thanks for this hint; this was able to unblock me.
