### ISSUE TITLE
Thread Leak

### ISSUE THREAD

**Issue by Cr4fter** [grpc/grpc-java#7581]
### What version of gRPC-Java are you using?
1.33.0
### What is your environment?

OpenJRE 15 on Linux and Windows

### What did you expect to see?
I'm trying to receive chat messages via a long running stream.

### What did you see instead?
GRPC permanently spawns new threads while reading from the stream without closing them.

My function which i use to receive the messages looks like the following:
```
    @Override
    public void run() {
        if (receivingIterator == null) receivingIterator = chatSync.beginReceive(Empty.newBuilder().build());
        try {
            if (receivingIterator.hasNext()) {
                ChatMessage message = receivingIterator.next();
                lockedQueue.Put(message);
            }
        } catch (io.grpc.StatusRuntimeException e) {
            receivingIterator = chatSync.beginReceive(Empty.newBuilder().build());
            Bukkit.getLogger().info("Chat Sync Connection Failed created new one!");
        }
    }
```

All threads have the same stack trace:

```
"Craft Scheduler Thread - 0@13830" prio=5 tid=0x42 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	  at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:731)
	  at io.grpc.stub.ClientCalls$BlockingResponseStream.waitForNext(ClientCalls.java:622)
	  at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:643)
	  at HausSheepPlugin.GRPCMessageReceiver.run(GRPCMessageReceiver.java:26)
	  at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
	  at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	  at java.lang.Thread.run(Thread.java:832)
```

**Comment by ejona86** [comment]
Why do you say that gRPC spawned that thread? "Craft Scheduler Thread" makes it pretty obvious that gRPC didn't spawn it.

That code snippet is using the blocking API. It blocks waiting on responses from the server. That code looks like it is part of an infinite loop receiving chat messages. This seems to be how HausSheepPlugin was implemented.

**Comment by Cr4fter** [comment]
receivingIterator.hasNext() blocks the Thread until a new message arrives which prompts the server to create a new thread for the next execution of run(). I did not look deep enough into the Stack trace I just saw that the last calls where GRPC waiting for the next element.
Thanks for taking the Time to Help out.
