### ISSUE TITLE
okhttp: using pending stream to queue writings before the connection is connected.

### ISSUE THREAD

**Issue by madongfly** [grpc/grpc-java#759]
Currently we use the serializing executor to implicitly queue writings before the connection is connected.

As we've added an obvious queue inside pending stream, using it to queue writings during connecting makes more sense.

**Comment by zhangkun83** [comment]
I just rolled back #792 because it broke OkHttpClientTransportTest:

```
io.grpc.okhttp.OkHttpClientTransportTest > shouldBeInitiallyReady FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.grpc.okhttp.OkHttpClientTransportTest.shouldBeInitiallyReady(OkHttpClientTransportTest.java:920)
```
