### ISSUE TITLE
Non-recoverable status when the client executor has rejected tasks (INTERNAL: Panic! This is a bug!)

### ISSUE THREAD

**Issue by valinha** [grpc/grpc-java#7599]
### What version of gRPC-Java are you using?
Head (1.33.1)

### What is your environment?

Operation system: Linux / Windows
Jdk: OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

### What did you expect to see?
In the case of using a channel with an executor that has a maximum pool size and an "Abort" rejection policy. Using a stub based on "AbstractAsyncStub" when a sufficient concurrency is created for rejected in the executor then occurs:
"io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!" due to "Caused by: java.util.concurrent.RejectedExecutionException: Task io.grpc.internal.DelayedClientTransport$5@363c30da rejected from java.util.concurrent.ThreadPoolExecutor". 

### What did you see instead?
After this point the system does not recover until the reboot and the requests always produce the last panic error.

### Steps to reproduce the bug

Using a simple grpc server:
```java
public class MyGrpcServer {

  static public void main(String[] args) throws IOException, InterruptedException {
    Server server = ServerBuilder.forPort(6061)
        .addService(new GreetingServiceImpl()).build();
    server.start();
    server.awaitTermination();
  }
  public static class GreetingServiceImpl extends GreeterImplBase {
    @Override
    public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
      try {
        Thread.sleep(200);
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
      String greeting = "Hello there, " + request.getName();
      HelloReply response = HelloReply.newBuilder().setMessage(greeting).build();
      responseObserver.onNext(response);
      responseObserver.onCompleted();
    }
  }

}
```

Creating a client that simulates concurrent request:
```java
public class GrpcClientTest {

    private static final int MAX_EXECUTOR_POOL_SIZE = 2;
    private static ThreadPoolExecutor executor;
    private static ManagedChannel channel;
    private static GreeterStub stub;

    private static List<CountDownLatch> executions = Collections.synchronizedList(new ArrayList<>());


    static public void main(String[] args) throws ExecutionException, InterruptedException, TimeoutException {
        setup();
        try {
            testConcurrentRequest();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            clean();
        }

    }

    static void setup() {
        ThreadFactory threadFactory = new ThreadFactoryBuilder()
            .setDaemon(true)
            .setNameFormat("testgrpcclientexecutor-%d")
            .build();
        RejectedExecutionHandler rejectedExecutionHandler = new AbortPolicy();
        BlockingQueue queue = new SynchronousQueue<Runnable>();
        executor = new ThreadPoolExecutor(MAX_EXECUTOR_POOL_SIZE, MAX_EXECUTOR_POOL_SIZE,
            60L, TimeUnit.SECONDS,
            queue,
            threadFactory, rejectedExecutionHandler);
        channel = ManagedChannelBuilder.forAddress("localhost", 6061)
            .usePlaintext().executor(executor)
            .build();

        stub = GreeterGrpc.newStub(channel);
    }

    static void clean() {
        executor.shutdown();
        channel.shutdown();
        System.exit(0);
    }


    public static void doRequest() {
        final CountDownLatch countDownLatch = new CountDownLatch(1);
        executions.add(countDownLatch);

        System.out.println("Thread " + Thread.currentThread().getName() + " do request");
        try {

            stub.sayHello(HelloRequest.newBuilder().setName("Hello").build(),
                new StreamObserver<HelloReply>() {
                    @Override
                    public void onNext(HelloReply value) {
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        System.out.println(Thread.currentThread().getName() + " -> " + value.getMessage());

                    }

                    @Override
                    public void onError(Throwable t) {
                        t.printStackTrace();
                        countDownLatch.countDown();
                    }

                    @Override
                    public void onCompleted() {
                        System.out.println(Thread.currentThread().getName() + " completed");
                        countDownLatch.countDown();

                    }
                });


        } catch (Exception e) {
            e.printStackTrace();
            countDownLatch.countDown();
        }


    }


    public static void testConcurrentRequest() throws ExecutionException, InterruptedException, TimeoutException {
        System.out.println("Starting...");
        //do request
        doRequest();
        waitForExecutions(1000);
        System.out.println("First request done");

        int concurrency = 70;
        ExecutorService executorService = Executors.newFixedThreadPool(concurrency);
        List<Future> executions = new ArrayList<>(concurrency);
        Random random = new Random();
        for (int i = 0; i < concurrency; i++) {
            Thread.sleep(random.nextInt(100));
            executions.add(executorService.submit(() -> doRequest()));
        }

        //wait for all executions
        executions.stream().forEach((r) -> {
            try {
                r.get(3000, TimeUnit.MILLISECONDS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            } catch (TimeoutException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }

        });
        waitForExecutions(3000);

        System.out.println("Concurrent request done");

        //after panic check simple request
        try {

            Thread.sleep(1000);
            System.out.println(
                "*****Try Last request.... Active count of executor is: '" + executor.getActiveCount() + "' ****\n\n");
            doRequest();
            waitForExecutions(1000);
            System.out.println("Last request done");

        } catch (Exception e) {
            e.printStackTrace();
        }


    }

    public static void waitForExecutions(int waitTimeoutMs) {
        executions.forEach((e) -> {
            try {
                e.await(waitTimeoutMs, TimeUnit.MILLISECONDS);
            } catch (InterruptedException interruptedException) {
                Thread.currentThread().interrupt();
                interruptedException.printStackTrace();
            }
        });
    }

}
```
The errors that the pool is saturated appear:

```java
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task io.grpc.internal.DelayedClientTransport$5@363c30da rejected from java.util.concurrent.ThreadPoolExecutor@42fdeaee[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 13]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at io.grpc.internal.DelayedClientTransport.reprocess(DelayedClientTransport.java:297)
	at io.grpc.internal.ManagedChannelImpl.updateSubchannelPicker(ManagedChannelImpl.java:851)
	at io.grpc.internal.ManagedChannelImpl.access$5100(ManagedChannelImpl.java:111)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1UpdateBalancingState.run(ManagedChannelImpl.java:1332)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportReady(InternalSubchannel.java:546)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyReady(ClientTransportLifecycleManager.java:43)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$FrameListener.onSettingsRead(NettyClientHandler.java:876)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:479)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:702)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onSettingsRead(Http2InboundFrameLogger.java:93)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame(DefaultHttp2FrameReader.java:542)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:263)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:242)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
```

After this, and knowing that the pool is no longer saturated, the system does not recover and always returns the previous error:

*****Try Last request.... Active count of executor is: '0' ****

Thread main do request
```java
INTERNAL: Panic! This is a bug!
io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task io.grpc.internal.DelayedClientTransport$5@363c30da rejected from java.util.concurrent.ThreadPoolExecutor@42fdeaee[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 13]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
...
...
...
```

**Comment by valinha** [comment]
Note: instead of using an Abortpolicy rejection policy, CallRunsPolicy is used, the system makes the correct closing of the requests (as this closing can be done in the thread that invokes the executor) and it does not remain in a panic state. Although this is really a simple workaround that changes the desired behavior, abort and don’t execute the request.

**Comment by ericgribkoff** [comment]
I'm pretty sure this is expected behavior. The gRPC library uses (or, in this case, tries to use) the user-provided executor to perform work involved in setting up the channel/connection, specifically right [here](https://github.com/grpc/grpc-java/blob/beb3232c0a6c2873292da7d24fb9f678a7f5a650/core/src/main/java/io/grpc/internal/DelayedClientTransport.java#L297) when establishing that a subchannel is ready to use. This fails, since the executor rejects the runnable, and at this point the channel is indeed left in a broken state and there's nothing else the gRPC channel can do.

cc @ejona86 in case I'm mistaken in the above, as I couldn't seem to find anything in the javadoc about when (if ever) we expect to be able to recover from a rejected execution exception

**Comment by ejona86** [comment]
This would be expected behavior today. Handling executors throw exceptions is #636. The problem is we need an executor, even if just to inform the application the RPC was cancelled.

This is _very_ strange to see on client-side. Why would a client issue RPCs if it isn't able to receive the replies? Buffering seems much more appropriate than killing the RPC after the response arrives.

Server-side has extra complexities, like you can't currently specify a different executor per service, so executor-driven resource limits are sort of impossible to tune with a variety of services.

**Comment by valinha** [comment]
@ejona86, @ericgribkoff I use grpc for internal communication between microservices. For example, microservice A calls microservice B using grpc, it may be that microservice A, due to the fact that the destination responds slowly in a punctual moment or an excessive load of requests comes, makes more requests than the executor can bear and therefore will enter a "Panic" state from which it cannot recover. This can be extremely serious in a microservices architecture. On the other hand, using an executor with a very high max pool size (default executor that comes with grpc) is also a bad idea if the client runs in a container environment (e.g. docker) with a resource limit, the limits could easily be reached and the process could die.
That's why, having a public api to use an executor in a client, it would be a good idea for grpc client to be resilient to possible problems with this executor. Solutions could be:
A) Perform an error management on RejectedExecutionException. In case of this type of errors, cancel the requests in a MoreExecutors.directExecutor for example (in the thread where you want to submit the runnable).
B) That the api allows to configure 2 executors, an executor for the callbacks of the requests and an executor for the processing and communication channel - request. Somehow to be able to separate channel management errors to processing errors of the request.
C) That grpc client offers the configuration of error handlers. The error handling that can be done in the project that uses grpc. That is, the service in question that needs not to enter Panic due to the saturated pool that can handle the error before entering that mode and be able to give a solution to the error (for example, execute the tasks of closing the request in another executor).

The example code I have put in the issue tries to simulate the micro service environment I was talking about, where the client would be micro service A and the server would be micro service B.

Any solution you see to this? Does it suit you to make this case more resilient?

**Comment by ejona86** [comment]
> On the other hand, using an executor with a very high max pool size (default executor that comes with grpc) is also a bad idea if the client runs in a container environment (e.g. docker) with a resource limit, the limits could easily be reached and the process could die.

I'd expect the executor to queue. You don't have to start more threads, just queue the runnables until you can get to them. That's what `Executors.newFixedThreadPool()` does. I don't see why you went out of your way to use the `SynchronousQueue`.

It is also possible to manage some of this from an interceptor; when the number of outbound RPCs exceeds some limit, close the RPC before it is even sent. Don't send more requests than you are willing to receive responses.

> Solutions could be

If you're trying to make gRPC handle executors throw exceptions, please discuss that on #636 and read it. (A) is not possible; we must never call user callbacks from the network thread; bad things happen if they happen to block and we don't trust user callbacks. Something akin to (B) was already mentioned in #636. (C) is really little different than (A), unless we put strong words of warning on it, but I don't see any advantage over (B) since it seems the only thing to do is call the callback on a different thread.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
