### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE

### ISSUE THREAD

**Issue by Elshad1** [grpc/grpc-java#7619]
Good afternoon. I ran your example on android (https://github.com/grpc/grpc-java/tree/master/examples/android/helloworld) but got the error. 

Server start

![image](https://user-images.githubusercontent.com/29523939/99042032-d3540180-25ad-11eb-8a8d-aac8e2e6859a.png)

Client start

![Screenshot_1605252399](https://user-images.githubusercontent.com/29523939/99042040-d6e78880-25ad-11eb-962e-4654c3866396.png)

```
2020-11-13 10:30:43.482 14227-14296/io.grpc.helloworldexample D/LOG: io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
        at io.grpc.examples.helloworld.GreeterGrpc$GreeterBlockingStub.sayHello(GreeterGrpc.java:189)
        at io.grpc.helloworldexample.HelloworldActivity$GrpcTask.doInBackground(HelloworldActivity.java:91)
        at io.grpc.helloworldexample.HelloworldActivity$GrpcTask.doInBackground(HelloworldActivity.java:73)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 50051) from /:: (port 39582): connect failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.connect(IoBridge.java:143)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at java.net.Socket.connect(Socket.java:570)
        at java.net.Socket.<init>(Socket.java:450)
        at java.net.Socket.<init>(Socket.java:250)
        at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:285)
        at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:556)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
        at libcore.io.Linux.connect(Native Method)
        at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:136)
        at libcore.io.ForwardingOs.connect(ForwardingOs.java:95)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:157)
        at libcore.io.IoBridge.connect(IoBridge.java:135)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) 
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390) 
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230) 
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212) 
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436) 
        at java.net.Socket.connect(Socket.java:621) 
        at java.net.Socket.connect(Socket.java:570) 
        at java.net.Socket.<init>(Socket.java:450) 
        at java.net.Socket.<init>(Socket.java:250) 
        at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:285) 
        at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:556) 
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)
```

Everything works on java, but not on android
Please tell me why I might get this error

**Comment by voidzcy** [comment]
Are you running on emulator? If you are, you should use 10.0.2.2 for localhost.

**Comment by Elshad1** [comment]
Thanks)
