### ISSUE TITLE
NettyServerTest failed

### ISSUE THREAD

**Issue by pinxiong** [grpc/grpc-java#7794]
### What version of gRPC-Java are you using?

- version: `v1.34.x`

### What is your environment?

- operating system: `MacOS Catalina 10.15.7`
- JDK: `1.8.0_271`

### What did you expect to see?

I hope all test cases run successfully

### What did you see instead?

An exception of `TestTimedOutException` occurred

### Steps to reproduce the bug

```java
test timed out after 60000 milliseconds
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at io.grpc.netty.NettyServerTest.connectionSettingsPropagated(NettyServerTest.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

io.grpc.netty.NettyServerTest > connectionSettingsPropagated FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at io.grpc.netty.NettyServerTest.connectionSettingsPropagated(NettyServerTest.java:247)
Disconnected from the target VM, address: 'localhost:54811', transport: 'socket'
4 tests completed, 1 failed
> Task :grpc-netty:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':grpc-netty:test'.
```

**Comment by ejona86** [comment]
There's probably some details logged in the test report. Open up `./netty/build/reports/tests/test/index.html` and see what you find.

**Comment by pinxiong** [comment]
It sounds good. Now, I had a new problem after running `./gradlew build` and then do `./gradlew publishToMavenLocal` in the same way. Cloud you help me again? Or we need to open a new issue?

```
******** grpc-java % `./gradlew publishToMavenLocal`
  * Skipping the build of Android projects because skipAndroid=true

> Configure project :grpc-compiler
*** Building codegen requires Protobuf version 3.12.0
*** Please refer to https://github.com/grpc/grpc-java/blob/master/COMPILING.md#how-to-build-code-generation-plugin

> Task :grpc-compiler:checkArtifacts FAILED

Checking format of build/artifacts/java_plugin/protoc-gen-grpc-java.exe
Format=x86_64

Checking dependencies of build/artifacts/java_plugin/protoc-gen-grpc-java.exe
Checking for expected dependencies ...
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
Checking for unexpected dependencies ...
        /usr/local/opt/protobuf/lib/libprotoc.25.dylib (compatibility version 26.0.0, current version 26.0.0)
        /usr/local/opt/protobuf/lib/libprotobuf.25.dylib (compatibility version 26.0.0, current version 26.0.0)
ERROR: found unexpected dependencies (listed above).


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/pinxiong/Documents/workspace/grpc-java/compiler/build.gradle' line: 206

* What went wrong:
Execution failed for task ':grpc-compiler:checkArtifacts'.
> Process 'command 'bash'' finished with non-zero exit value 99

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
109 actionable tasks: 15 executed, 94 up-to-date
```

**Comment by ejona86** [comment]
What are you trying to accomplish, precisely? Is there a reason not to use the pre-built artifacts?

The libprotoc.25.dylib and libprotobuf.25.dylib listing means the binary is dynamically linked against protobuf. We typically don't want that, but it isn't much of a problem for local development. If you build protobuf with `--disable-shared` then it should fix that problem. You may find https://github.com/grpc/grpc-java/blob/master/buildscripts/make_dependencies.sh useful; that's what we use in our CI environment to build protobuf.

If you don't care, you can workaround the problem by replacing [`builtBy checkArtifacts`](https://github.com/grpc/grpc-java/blob/b66d182bb9aafe8d88ac56c282d09b0b8be4ced7/compiler/build.gradle#L257) with `builtBy buildArtifacts` or just [commenting out the check-artifact.sh section of checkArtifacts](https://github.com/grpc/grpc-java/blob/b66d182bb9aafe8d88ac56c282d09b0b8be4ced7/compiler/build.gradle#L206-L212) or modifying `check-artifact.sh` directly (e.g., comment out the last line).

**Comment by ericgribkoff** [comment]
Marking this closed since there hasn't been a response from the initial poster in 2 weeks. @pinxiong if there's anything else to follow up on here let us know and we can always reopen this.

**Comment by pinxiong** [comment]
> What are you trying to accomplish, precisely? Is there a reason not to use the pre-built artifacts?
> 
> The libprotoc.25.dylib and libprotobuf.25.dylib listing means the binary is dynamically linked against protobuf. We typically don't want that, but it isn't much of a problem for local development. If you build protobuf with `--disable-shared` then it should fix that problem. You may find https://github.com/grpc/grpc-java/blob/master/buildscripts/make_dependencies.sh useful; that's what we use in our CI environment to build protobuf.
> 
> If you don't care, you can workaround the problem by replacing [`builtBy checkArtifacts`](https://github.com/grpc/grpc-java/blob/b66d182bb9aafe8d88ac56c282d09b0b8be4ced7/compiler/build.gradle#L257) with `builtBy buildArtifacts` or just [commenting out the check-artifact.sh section of checkArtifacts](https://github.com/grpc/grpc-java/blob/b66d182bb9aafe8d88ac56c282d09b0b8be4ced7/compiler/build.gradle#L206-L212) or modifying `check-artifact.sh` directly (e.g., comment out the last line).

Thanks for your help. All problems have been solved.

Very sorry for not telling you in time. Now, we can close this issue.

**Comment by pinxiong** [comment]
> Marking this closed since there hasn't been a response from the initial poster in 2 weeks. @pinxiong if there's anything else to follow up on here let us know and we can always reopen this.

@ericgribkoff All of problems have been solved, you can close this issue. Thank you!
