### ISSUE TITLE
./run-test-server.sh and ./run-test-client.sh don't work (Therefore `Basics tutorial` is also broken)

### ISSUE THREAD

**Issue by ben-xD** [grpc/grpc-java#7867]
I was only following this guide https://grpc.io/docs/platforms/android/java/basics/
It looks like its outdated as the paths in the guide are already wrong. I found the relevant files/ directories and built the library and also the Android app. It turns out even the 2 basic test scripts don't work.

### What version of gRPC-Java are you using?
gRPC-Java: Master branch (`f0cf435b85a851ed8b2fa5ddcf8b2d1bc06f2984`) and also tried 1.35.0 (`remotes/origin/v1.35.0`)
JDK: openjdk64-11.0.9.1 and also tried separately with openJDK@8 (installed via homebrew)
I am using jenv though

### What is your environment?
macOS 11.2 Beta (20D5029f) (Intel x86_64, not M1)

### What did you expect to see?
The intro scripts work. I start server script, then client script:

### What did you see instead?
When running client script for Java 1.8/ JDK8 version"
```
./run-test-client.sh 
[jetty-alpn-agent][ info] alpn-boot not necessary for Java version: 1.8.0_282
Running test empty_unary
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.emptyCall(TestServiceGrpc.java:614)
	at io.grpc.testing.integration.AbstractInteropTest.emptyUnary(AbstractInteropTest.java:383)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:219)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:207)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:65)
Caused by: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.handshakeException(ReferenceCountedOpenSslEngine.java:1772)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:777)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:511)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1079)
	at io.netty.handler.ssl.SslHandler.wrapNonAppData(SslHandler.java:970)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1443)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
	at sun.security.validator.Validator.validate(Validator.java:271)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:278)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:261)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:698)
	at io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:596)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1203)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1325)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:201)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380)
	... 21 more
	Suppressed: javax.net.ssl.SSLHandshakeException: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
		at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1288)
		at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1249)
		... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
	... 34 more
```

### Steps to reproduce the bug
- Build the library: `./gradlew installDist`
- `./run-test-server.sh`
- `./run-test-client.sh`

**Comment by ben-xD** [comment]
I think this is caused because gRPC-Java does not support jenv. Jenv does some weird things to `JAVA_HOME`. I'll continue to investigate

**Comment by sanjaypujare** [comment]
This clearly looks like a cert validation problem.
```
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

As far as I know the basic example should be using plaintext, so I don't understand why yours is trying to use TLS. What certs are you using? Is it possible they are expired or don't match the hostname you are using?

**Comment by ben-xD** [comment]
I was just running the 2 scripts 😅, I did not change anything.

**Comment by sanjaypujare** [comment]
This  https://github.com/grpc/grpc-java/blob/master/run-test-client.sh is the wrong client - that's not part of the examples. You should not be running anything in that directory. For the Android app you should be in  https://github.com/grpc/grpc-java/tree/master/examples/android  (i.e. `./examples/android directory` in your downloaded repo).

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
