### ISSUE TITLE
Wrong buffer size

### ISSUE THREAD

**Issue by zhouwenbin00** [grpc/grpc-java#7988]
My program is bound to have this bug.I don't know why.
This is an error message:
```
io.grpc.netty.shaded.io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:637)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:945)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:519)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:189)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.flush(AbstractChannel.java:242)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.flush(WriteQueue.java:147)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue.access$000(WriteQueue.java:34)
	at io.grpc.netty.shaded.io.grpc.netty.WriteQueue$1.run(WriteQueue.java:46)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: index: 0, length: 16384 (expected: range(0, 14113))
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1425)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1432)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1419)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBuf.duplicateInternalNioBuffer(PooledByteBuf.java:194)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBuf.nioBuffer(PooledByteBuf.java:211)
	at io.grpc.netty.shaded.io.netty.buffer.CompositeByteBuf.nioBuffers(CompositeByteBuf.java:1668)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractUnpooledSlicedByteBuf.nioBuffers(AbstractUnpooledSlicedByteBuf.java:440)
	at io.grpc.netty.shaded.io.netty.channel.unix.IovArray.add(IovArray.java:102)
	at io.grpc.netty.shaded.io.netty.channel.unix.IovArray.processMessage(IovArray.java:210)
	at io.grpc.netty.shaded.io.netty.channel.ChannelOutboundBuffer.forEachFlushedMessage(ChannelOutboundBuffer.java:780)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:506)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:422)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	... 22 common frames omitted

```
Buffer size should not be 14113.Can someone help me with this?

**Comment by voidzcy** [comment]
Which gRPC/netty version are you using? Also, we need more details for how this was triggered. Please describe your usages or provide us a minimal reproducible example.

**Comment by ejona86** [comment]
This looks _very_ strange, as I wouldn't expect this sort of bug in the I/O vector code in Netty. Is this a consistent problem for you, or did you just see it once? If you saw it more than one we'd _love_ to have a reproduction of this.

**Comment by zhouwenbin00** [comment]
just I write in multiple threads cause this problem.I'm sorry for the trouble
