### ISSUE TITLE
Latest build seems to require Java 8

### ISSUE THREAD

**Issue by nmittler** [grpc/grpc-java#805]
When building the latest from master, I see an error in the stacktrace indicating that it's looking for Java 8 classes:

```
Caused by: org.gradle.api.GradleException: Could not generate a proxy class for class com.google.protobuf.gradle.ProtobufSourceDirectorySet.
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:204)
	at org.gradle.api.internal.AbstractClassGenerator.generate(AbstractClassGenerator.java:67)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:106)
	at com.google.protobuf.gradle.ProtobufPlugin$_addSourceSetExtensions_closure4.doCall(ProtobufPlugin.groovy:124)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
	at org.gradle.api.DomainObjectCollection$all$1.call(Unknown Source)
	at com.google.protobuf.gradle.ProtobufPlugin.addSourceSetExtensions(ProtobufPlugin.groovy:123)
	at com.google.protobuf.gradle.ProtobufPlugin.apply(ProtobufPlugin.groovy:82)
	at com.google.protobuf.gradle.ProtobufPlugin.apply(ProtobufPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RulesCapablePluginApplicator.applyImperative(RulesCapablePluginApplicator.java:42)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:133)
	... 59 more
Caused by: java.lang.NoClassDefFoundError: java/util/Spliterator
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:265)
	at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:220)
	at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:98)
	... 73 more
```

**Comment by ejona86** [comment]
Could you share the full stack trace?

**Comment by zhangkun83** [comment]
I can reproduce it with JDK7. The problem is that protobuf-gradle-plugin 0.6.1 requires JDK8 to run. The protobuf-gradle-plugin artifact was built on JDK8, but the build file has `targetCompatibility = 1.6` in it. While I don't know why, building it on JDK7 seems to resolve the problem. I will make a 0.6.2 release under JDK7.

**Comment by ejona86** [comment]
`targetCompatibility` only guarantees bytecode compatibility. It won't prevent/find something like using classes or methods that weren't previously supported. That's what we use animal sniffer for.
