### ISSUE TITLE
[HELP] Runtime exception when execute ManagedChannelBuilder.forAddress()

### ISSUE THREAD

**Issue by LeagueLugas** [grpc/grpc-java#8094]
I have some problems when i create grpc ManagedChannel.
when i run jar file, I keep getting the following error..

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.github.kodomo.maalysmith.core.global.bean.GRPCContainer.registerStub(GRPCContainer.java:23)
	at com.github.kodomo.maalysmith.core.MALLYSmithCore.setup(MALLYSmithCore.java:34)
	at com.github.kodomo.maalysmith.core.MALLYSmithCore.onEnable(MALLYSmithCore.java:21)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:881)
	at org.bukkit.Bukkit.reload(Bukkit.java:651)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:748)
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Error reading configuration file
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.parse(ServiceLoader.java:309)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at io.grpc.ServiceProviders.getCandidatesViaServiceLoader(ServiceProviders.java:111)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:64)
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:96)
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.github.kodomo.maalysmith.core.global.stub.UserGrpcStub.<init>(UserGrpcStub.java:13)
	... 24 more
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/io.grpc.ManagedChannelProvider not found in C:\Users\user\Desktop\Other\Server\MALLYSmith\plugins\MALLYSmith-Core.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at java.net.URL.openStream(URL.java:1045)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	... 34 more
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.github.kodomo.maalysmith.core.global.bean.GRPCContainer.registerStub(GRPCContainer.java:23)
	at com.github.kodomo.maalysmith.core.MALLYSmithCore.setup(MALLYSmithCore.java:35)
	at com.github.kodomo.maalysmith.core.MALLYSmithCore.onEnable(MALLYSmithCore.java:21)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:881)
	at org.bukkit.Bukkit.reload(Bukkit.java:651)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:748)
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: Error reading configuration file
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.parse(ServiceLoader.java:309)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at io.grpc.ServiceProviders.getCandidatesViaServiceLoader(ServiceProviders.java:111)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:64)
	at io.grpc.ManagedChannelRegistry.getDefaultRegistry(ManagedChannelRegistry.java:96)
	at io.grpc.ManagedChannelProvider.provider(ManagedChannelProvider.java:41)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.github.kodomo.maalysmith.core.global.stub.BankGrpcStub.<init>(BankGrpcStub.java:13)
	... 24 more
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/io.grpc.ManagedChannelProvider not found in C:\Users\user\Desktop\Other\Server\MALLYSmith\plugins\MALLYSmith-Core.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at java.net.URL.openStream(URL.java:1045)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	... 34 more
```

this is my code on github - https://github.com/kodomomo/MALLYSmith-Core

**Comment by LeagueLugas** [comment]
Incidentally, this is an msa service using grpc on a minecraft server

**Comment by sergiitk** [comment]
Could you clarify how you run the jar? It appears that you're building a plugin? Could it be that minecraft server implementation registers custom Channel implementation? Take a look at this note: https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelProvider.html

> Implementations can be automatically discovered by gRPC via Java's SPI mechanism. For automatic discovery, the implementation must have a zero-argument constructor and include a resource named META-INF/services/io.grpc.ManagedChannelProvider in their JAR. The file's contents should be the implementation's class name.

**Comment by sergiitk** [comment]
Also, take a look at this issue. Looks fairly similar: https://github.com/grpc/grpc-java/issues/5794

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
