### ISSUE TITLE
grpc hang due to the ELG thread placement of NameResolver refresh method

### ISSUE THREAD

**Issue by MingsenXu** [grpc/grpc-java#8190]
**What version of gRPC are you using?**
grpc v1.32.1

**What operating system (Linux, Windows, …) and version?**
Both Linux and Windows

**What did you do?**
Implement a customized NameResolver which extends [NameResolver](https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/api/src/main/java/io/grpc/NameResolver.java), let's call it "_**CustomizedNameResolver**_".  In the override refresh() method, it makes a grpc call to service discovery agent to retrieve a list of service instances and then resolve them.

**What did you expect to see?**
Expect the customized namer resolver works whenever being called and not hang in the existing grpc call.

**What did you see instead?**
grpc calls hang in the customized name resolver, particularly on the grpc calling inside overridden refresh() method. 

We did a thread dump analysis, the problem is the grpc call inside overridden refresh() method is placed in gRPC ELG thread instead of worker thread, which in turns blocks all gRPC traffic causing grpc call hang indefinitely. 
According to comment on [refresh() method](https://github.com/grpc/grpc-java/blob/d4fa0ecc07495097453b0a2848765f076b9e714c/api/src/main/java/io/grpc/NameResolver.java#L118), the document does not clearly states that you must delegate a grpc call to a worker/background thread to not block other grpc calls. 

First, is the placement of grpc call inside overridden refresh() method on the grpc ELG thread an expected behavior? Why cannot we delegate it to worker thread by default? 

Second, some guides and explanations could be added to the document on NameResolver to further clarify. 

Attach a thread dump on ELG for your reference. Thank you.

```
"grpc-default-worker-ELG-1-6" - Thread t@428
   java.lang.Thread.State: WAITING
	at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
	- parking to wait for <41c8f5eb> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
	at java.base@11.0.9.1/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:642)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:130)
    ...
	at com.xxx.xxx.CustomizedNameResolver.refresh(com.xxx.xxx.CustomizedNameResolver.refresh:59)
	at io.grpc.internal.ManagedChannelImpl.refreshNameResolution(ManagedChannelImpl.java:447)
	at io.grpc.internal.ManagedChannelImpl.refreshAndResetNameResolution(ManagedChannelImpl.java:441)
	at io.grpc.internal.ManagedChannelImpl.access$3900(ManagedChannelImpl.java:99)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.handleInternalSubchannelState(ManagedChannelImpl.java:1046)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl.access$4500(ManagedChannelImpl.java:1040)
	at io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1ManagedInternalSubchannelCallback.onStateChange(ManagedChannelImpl.java:1084)
	at io.grpc.internal.InternalSubchannel$2.run(InternalSubchannel.java:362)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:88)
	at io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:621)
	at io.grpc.netty.shaded.io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:53)
	at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.goingAway(NettyClientHandler.java:703)
```

**Comment by sanjaypujare** [comment]
Take a look at the `DnsNameResolver`, specifically how it uses the `offloadExecutor` inside [`resolve()`](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/DnsNameResolver.java#L389) that is called by `refresh()`.

The documentation for [`NameResolver.Args.getOffloadExecutor()`](https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/NameResolver.java#L354) does say this:

> Returns the Executor on which this resolver should execute long-running or I/O bound work.

implying that in your case where you are making a gRPC call (which is a long running or I/O operation) you should have used the `offloadExecutor`. The `ManagedChannelImpl` does use an `offloadExecutor` for the `DnsNameResolver` it creates as you can see [here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L647).

I suggest using the latest gRPC release 1.38 and also model your `CustomizedNameResolver` on the `DnsNameResolver`.

**Comment by fangxlmr** [comment]
@MingsenXu @sanjaypujare

**Great thanks** to this issue and the reply. I encoutered the same issue and I spent almost **two weeks** to find out the root cuase. What a long-term shot on this bug!

It happenes from time to time which in turn blocks ALL grpc call inside the service. It's EXTREMELY HARD to debug since I have no clue about why ALL grpc calls are blocking. Outout of `jstack` does gives information but it's almost impossible to find it out after taking a glance.

**Comment by ejona86** [comment]
I think in the future we may try to re-evaluate whether the name resolver should run within the synchronization context of the channel, and whether it could use other threads. But there's some LB API changes that need to happen before that can be considered, and I expect it is more of a long-shot unless the LBs themselves swap to using different threads.

I'll just update the docs for now, since that is a pretty big oversight and would be painful for NR implementors.

**Comment by sanjaypujare** [comment]
> I'll just update the docs for now, since that is a pretty big oversight and would be painful for NR implementors.

For this issue there is the additional consideration that if you use gRPC in your NameResolver there is a strong possibility of deadlock without the offload executor. Is that worth mentioning?

**Comment by ejona86** [comment]
I'd rather not mention it now. There's only a handful of NRs that use gRPC, like etcd, gsd. If you are making a NR that uses gRPC, you should really be using the async API anyway to avoid consuming a thread. In my mind the more common problem is really the "I have to use an existing client API and it is blocking" cases, which seems pretty common.
