### ISSUE TITLE
 Failed to start bean 'shadedNettyGrpcServerLifecycle' while spring boot application startup in a kubernetes pod with openjdk 8 alpine base image

### ISSUE THREAD

**Issue by vishal662** [grpc/grpc-java#8249]
Following exception is coming during the startup of spring boot application:

```
org.springframework.context.ApplicationContextException: Failed to start bean 'shadedNettyGrpcServerLifecycle'; nested exception is java.lang.ExceptionInInitializerError
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.2.RELEASE.jar!/:2.3.2.RELEASE]
        at com.commscope.gnb.networkservice.configdb.ConfigDBSpringbootApp.main(ConfigDBSpringbootApp.java:30) [classes!/:1.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [config-db-service-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) [config-db-service-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [config-db-service-1.0.0.jar:1.0.0]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [config-db-service-1.0.0.jar:1.0.0]
Caused by: java.lang.ExceptionInInitializerError: null
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:78) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.newServerBuilder(ShadedNettyGrpcServerFactory.java:66) ~[grpc-server-spring-boot-autoconfigure-2.12.0.RELEASE.jar!/:2.12.0.RELEASE]
        at net.devh.boot.grpc.server.serverfactory.ShadedNettyGrpcServerFactory.newServerBuilder(ShadedNettyGrpcServerFactory.java:47) ~[grpc-server-spring-boot-autoconfigure-2.12.0.RELEASE.jar!/:2.12.0.RELEASE]
        at net.devh.boot.grpc.server.serverfactory.AbstractGrpcServerFactory.createServer(AbstractGrpcServerFactory.java:66) ~[grpc-server-spring-boot-autoconfigure-2.12.0.RELEASE.jar!/:2.12.0.RELEASE]
        at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.createAndStartGrpcServer(GrpcServerLifecycle.java:100) ~[grpc-server-spring-boot-autoconfigure-2.12.0.RELEASE.jar!/:2.12.0.RELEASE]
        at net.devh.boot.grpc.server.serverfactory.GrpcServerLifecycle.start(GrpcServerLifecycle.java:61) ~[grpc-server-spring-boot-autoconfigure-2.12.0.RELEASE.jar!/:2.12.0.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
        ... 21 common frames omitted
Caused by: java.lang.IllegalArgumentException: availableProcessors: 0 (expected: > 0)
        at io.grpc.netty.shaded.io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:44) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.<init>(Utils.java:394) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:84) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        ... 28 common frames omitted
```

grpc-bom version : 1.30.0 (also tried 1.29.0 and 1.38.0)
kernel version of host machine: Linux controller-0 3.10.0-1127.rt56.1093.el7.tis.2.x86_64 #1 SMP PREEMPT RT Sat Jun 27 20:22:47 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Same spring boot application works with kernel version : Linux controller-1 4.18.0-147.3.1.rt24.96.el8_1.tis.8.x86_64 #1 SMP PREEMPT RT Wed Aug 5 06:21:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by voidzcy** [comment]
This doesn't seem to be directly gRPC-related. We don't have enough expertise in spring boot. I'd suggest seeking help from Spring.

**Comment by ejona86** [comment]
I improved the formatting of the exception and it is more obvious now that this isn't a Spring issue:

```
Caused by: java.lang.IllegalArgumentException: availableProcessors: 0 (expected: > 0)
        at io.grpc.netty.shaded.io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:44) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:44) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.netty.util.NettyRuntime$AvailableProcessorsHolder.availableProcessors(NettyRuntime.java:70) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
        at io.grpc.netty.shaded.io.netty.util.NettyRuntime.availableProcessors(NettyRuntime.java:98) ~[grpc-netty-shaded-1.29.0.jar!/:1.29.0]
```

That is... surprising. `Runtime.availableProcessors()` is ["never smaller than one"](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#availableProcessors--), so either this is a bug in the JRE/environment or you are passing `-Dio.grpc.netty.shaded.io.netty.availableProcessors=0` to the binary.

**Comment by ejona86** [comment]
Closing since it does not seem to be directly a gRPC bug and there's not been any more discussion as far as how we can help. If there's additional questions/comments go ahead and comment and we can reopen.
