### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]

### ISSUE THREAD

**Issue by navin6698** [grpc/grpc-java#8307]
I'm trying to run google translate API which depends on netty-shaded, but getting this exception:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative],
I have seen some of the articles related to this couldn't find the proper asnwer. netty-shaded is available in class path

I'm using Java 8

	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:590)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:230)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:594)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:500)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:171)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:611)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:327)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1700(InstantiatingGrpcChannelProvider.java:74)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:220)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:227)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:210)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.cloud.translate.v3.stub.GrpcTranslationServiceStub.create(GrpcTranslationServiceStub.java:174)
	at com.google.cloud.translate.v3.stub.TranslationServiceStubSettings.createStub(TranslationServiceStubSettings.java:261)
	at com.google.cloud.translate.v3.TranslationServiceClient.<init>(TranslationServiceClient.java:143)
	at com.google.cloud.translate.v3.TranslationServiceClient.create(TranslationServiceClient.java:124)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.googleTranslate(GoogleTranslationServiceImpl.java:72)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.translate(GoogleTranslationServiceImpl.java:47)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationProvider.processOrgDataSyncItem(GoogleTranslationProvider.java:54)
	at com.network.service.common.anappsbusinesslogic.translation.TranslationProviderFactory.processOrgDataSyncItem(TranslationProviderFactory.java:70)
	at com.network.service.apps.anorgdatasyncdispatcher.processor.OrgTranslationProcessor.process(OrgTranslationProcessor.java:22)
	at com.network.service.apps.anorgdatasyncdispatcher.ANOrgDataSyncQueueWorkItem.handle(ANOrgDataSyncQueueWorkItem.java:62)
	at com.network.common.andispatcher.Worker.handleWorkItem(Worker.java:271)
	at com.network.common.andispatcher.Worker.run(Worker.java:135)

	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative_linux_x86_64
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 29 more
		Suppressed: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.io_grpc_netty_shaded_netty_tcnative_linux_x86_64")
			at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
			at java.security.AccessController.checkPermission(AccessController.java:884)
			at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
			at java.lang.SecurityManager.checkLink(SecurityManager.java:835)
			at java.lang.Runtime.loadLibrary0(Runtime.java:864)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 30 more
	Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary./tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_645362444146938961358.so")
		at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
		at java.security.AccessController.checkPermission(AccessController.java:884)
		at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
		at java.lang.SecurityManager.checkLink(SecurityManager.java:835)
		at java.lang.Runtime.load0(Runtime.java:803)
		at java.lang.System.load(System.java:1086)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205)
		... 30 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative_linux_x86_64_fedora
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 29 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libio_grpc_netty_shaded_netty_tcnative_linux_x86_64_fedora.so
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 30 more
		Suppressed: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.io_grpc_netty_shaded_netty_tcnative_linux_x86_64_fedora")
			at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
			at java.security.AccessController.checkPermission(AccessController.java:884)
			at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
			at java.lang.SecurityManager.checkLink(SecurityManager.java:835)
			at java.lang.Runtime.loadLibrary0(Runtime.java:864)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 30 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative_x86_64
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 29 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libio_grpc_netty_shaded_netty_tcnative_x86_64.so
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 30 more
		Suppressed: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.io_grpc_netty_shaded_netty_tcnative_x86_64")
			at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
			at java.security.AccessController.checkPermission(AccessController.java:884)
			at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
			at java.lang.SecurityManager.checkLink(SecurityManager.java:835)
			at java.lang.Runtime.loadLibrary0(Runtime.java:864)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 30 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:96)
		... 29 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libio_grpc_netty_shaded_netty_tcnative.so
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 30 more
		Suppressed: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary.io_grpc_netty_shaded_netty_tcnative")
			at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
			at java.security.AccessController.checkPermission(AccessController.java:884)
			at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
			at java.lang.SecurityManager.checkLink(SecurityManager.java:835)
			at java.lang.Runtime.loadLibrary0(Runtime.java:864)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 30 more

Jul 05, 2021 10:38:26 PM io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Conscrypt not found (this may be normal)

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.grpc.internal.ConscryptLoader.newProvider(ConscryptLoader.java:78)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts$ConscryptHolder.<clinit>(GrpcSslContexts.java:295)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:268)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:234)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:594)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:500)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:171)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:611)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:327)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1700(InstantiatingGrpcChannelProvider.java:74)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:220)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:227)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:210)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.cloud.translate.v3.stub.GrpcTranslationServiceStub.create(GrpcTranslationServiceStub.java:174)
	at com.google.cloud.translate.v3.stub.TranslationServiceStubSettings.createStub(TranslationServiceStubSettings.java:261)
	at com.google.cloud.translate.v3.TranslationServiceClient.<init>(TranslationServiceClient.java:143)
	at com.google.cloud.translate.v3.TranslationServiceClient.create(TranslationServiceClient.java:124)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.googleTranslate(GoogleTranslationServiceImpl.java:72)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.translate(GoogleTranslationServiceImpl.java:47)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationProvider.processOrgDataSyncItem(GoogleTranslationProvider.java:54)
	at com.network.service.common.anappsbusinesslogic.translation.TranslationProviderFactory.processOrgDataSyncItem(TranslationProviderFactory.java:70)
	at com.network.service.apps.anorgdatasyncdispatcher.processor.OrgTranslationProcessor.process(OrgTranslationProcessor.java:22)
	at com.network.service.apps.anorgdatasyncdispatcher.ANOrgDataSyncQueueWorkItem.handle(ANOrgDataSyncQueueWorkItem.java:62)
	at com.network.common.andispatcher.Worker.handleWorkItem(Worker.java:271)
	at com.network.common.andispatcher.Worker.run(Worker.java:135)
Caused by: java.lang.ExceptionInInitializerError
	at org.conscrypt.Conscrypt.checkAvailability(Conscrypt.java:119)
	at org.conscrypt.Conscrypt.newProvider(Conscrypt.java:133)
	... 34 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessUserInformation")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at sun.nio.fs.UnixFileAttributeViews$Posix.checkReadExtended(UnixFileAttributeViews.java:148)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:214)
	at sun.nio.fs.UnixFileAttributeViews$Posix.readAttributes(UnixFileAttributeViews.java:131)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.getPosixFilePermissions(Files.java:2004)
	at org.conscrypt.Platform.canExecuteExecutable(Platform.java:171)
	at org.conscrypt.NativeLibraryLoader.loadFromWorkdir(NativeLibraryLoader.java:190)
	at org.conscrypt.NativeLibraryLoader.load(NativeLibraryLoader.java:162)
	at org.conscrypt.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
	at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:50)
	at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:64)
	... 36 more

Jul 05, 2021 10:38:26 PM io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts defaultSslProvider
INFO: Jetty ALPN unavailable (this may be normal)
java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.shaded.io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:254)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:234)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:594)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:500)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:171)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:611)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:327)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1700(InstantiatingGrpcChannelProvider.java:74)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:220)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:227)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:210)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.cloud.translate.v3.stub.GrpcTranslationServiceStub.create(GrpcTranslationServiceStub.java:174)
	at com.google.cloud.translate.v3.stub.TranslationServiceStubSettings.createStub(TranslationServiceStubSettings.java:261)
	at com.google.cloud.translate.v3.TranslationServiceClient.<init>(TranslationServiceClient.java:143)
	at com.google.cloud.translate.v3.TranslationServiceClient.create(TranslationServiceClient.java:124)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.googleTranslate(GoogleTranslationServiceImpl.java:72)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.translate(GoogleTranslationServiceImpl.java:47)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationProvider.processOrgDataSyncItem(GoogleTranslationProvider.java:54)
	at com.network.service.common.anappsbusinesslogic.translation.TranslationProviderFactory.processOrgDataSyncItem(TranslationProviderFactory.java:70)
	at com.network.service.apps.anorgdatasyncdispatcher.processor.OrgTranslationProcessor.process(OrgTranslationProcessor.java:22)
	at com.network.service.apps.anorgdatasyncdispatcher.ANOrgDataSyncQueueWorkItem.handle(ANOrgDataSyncQueueWorkItem.java:62)
	at com.network.common.andispatcher.Worker.handleWorkItem(Worker.java:271)
	at com.network.common.andispatcher.Worker.run(Worker.java:135)

Mon Jul 05 22:38:26 PDT 2021 (T10) (Misc:error): java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available

	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:594)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:500)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:171)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:611)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:327)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1700(InstantiatingGrpcChannelProvider.java:74)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:220)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:227)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:210)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.cloud.translate.v3.stub.GrpcTranslationServiceStub.create(GrpcTranslationServiceStub.java:174)
	at com.google.cloud.translate.v3.stub.TranslationServiceStubSettings.createStub(TranslationServiceStubSettings.java:261)
	at com.google.cloud.translate.v3.TranslationServiceClient.<init>(TranslationServiceClient.java:143)
	at com.google.cloud.translate.v3.TranslationServiceClient.create(TranslationServiceClient.java:124)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.googleTranslate(GoogleTranslationServiceImpl.java:72)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationServiceImpl.translate(GoogleTranslationServiceImpl.java:47)
	at com.network.service.common.anappsbusinesslogic.translation.google.GoogleTranslationProvider.processOrgDataSyncItem(GoogleTranslationProvider.java:54)
	at com.network.service.common.anappsbusinesslogic.translation.TranslationProviderFactory.processOrgDataSyncItem(TranslationProviderFactory.java:70)
	at com.network.service.apps.anorgdatasyncdispatcher.processor.OrgTranslationProcessor.process(OrgTranslationProcessor.java:22)
	at com.network.service.apps.anorgdatasyncdispatcher.ANOrgDataSyncQueueWorkItem.handle(ANOrgDataSyncQueueWorkItem.java:62)
	at com.network.common.andispatcher.Worker.handleWorkItem(Worker.java:271)
	at com.network.common.andispatcher.Worker.run(Worker.java:135)

**Comment by sanjaypujare** [comment]
Did you follow the recommendations at https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-netty-tcnative-on-boringssl ?

**Comment by sanjaypujare** [comment]
Also looking closely at the stack trace, I see this:

```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "loadLibrary./tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_645362444146938961358.so")
```

Questions:
- is it possible your `/tmp` is mounted with noexec? (https://superuser.com/questions/728127/what-does-noexec-flag-mean-when-mounting-directories-on-rhel)
- do you see the file like `/tmp/libio_grpc_netty_shaded_netty_tcnative_linux_x86_645362444146938961358.so` in the file system that is marked executable?

**Comment by navin6698** [comment]
As I seen in some articles if netty shaded is being used then TC native dependency is not required. I'll try adding tc native and see if it works.

In my local it works fine, I'm running on Mac os, but in Dev lab services I'm facing this issue, those are run on Linux OS.

As per your latest comment looks like there is no permission for that particular file or it's not marked as executable. Will check this as well.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
