### ISSUE TITLE
gRPC SSL Examples

### ISSUE THREAD

**Issue by dasotong** [grpc/grpc-java#842]
Hi, 

Please advise on where I can find  java examples on client-server authentication for SSL?

Thank you.

**Comment by madongfly** [comment]
Please take a look at the [SECURITY.md](https://github.com/grpc/grpc-java/blob/master/SECURITY.md)

**Comment by dasotong** [comment]
Hi,

With regard to this statement, "If the issuing certificate authority for a server is not known to the client then a similar process should be followed on the client to load it so that it may validate the certificate issued to the server.".

What does  "similar process should be followed on the client to load it?" means?

I have tried to install the cert manually on my client's java trust store (cacert) but the following error keep appearing:

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certific
ation path to requested target
        at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at sun.security.validator.Validator.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 25 more


Any advice will be appreciated. Thank you.

**Comment by madongfly** [comment]
In that document, we give the example of loading the certificate chain and key for a Server, loading the certificate on client is very similar, see [this test](https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/TestServiceClient.java#L262) for a concrete example.

**Comment by dasotong** [comment]
Hi, 

Thanks for the help, it seems that the SSL handshake is successful when the client try to establish a connection to the server.

However, the RPC methods does not seemed to be invoked and there are no errors/logs to indicate any issues.

 Is there something that I have missed out?
