### ISSUE TITLE
Received DATA frame for an unknown stream in bi stream

### ISSUE THREAD

**Issue by Kircheisser** [grpc/grpc-java#8431]
I have a grpc bistream in my application. In the happy path, the server will call onCompleted() of the response stream and then the client will call onCompleted() of the request stream.

Most of the times things work fine, but every once in a while I am getting a big scary stack trace like

`io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 54
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:535)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:187)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421)
...
`

What does this mean, is it not appropriate for me to call onCompleted() of the request stream after onCompleted() of the response stream? 

In my testing, it seems as though it is acceptable to have the requestStream closed but the responseStream open, i.e. the client call onComplete but the server continue to call onNext, in that these messages are received by the client. But the reverse is not acceptable, i.e. the server calling onComplete and then the client calling onNext in that these messages are not received by the server. So that in grpc the stream can only be half closed in one way? Is this correct?

**Comment by sanjaypujare** [comment]
Interesting because I thought the server has to wait for the client to "complete" its request stream before the server can "complete" its response stream as intuitively implied by the client-server model. But when I searched the documentation I found this https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-termination which says "It’s also possible for a server to decide to complete before a client has sent all its requests." which agrees with the issue you are raising (assuming it means "messages" and not "requests" which is what a request-stream consists of).

I don't know how other languages behave: if their server behavior matches what Java does then we should fix the text I cited or if this is an issue only in Java which needs to be fixed. @ejona86 do you think this is a bug in Java?

BTW: can you also provide more context around the stack trace? Client or server side? And actual gRPC code stack frames in the stack trace?

**Comment by Kircheisser** [comment]
Have updated my question with the full stack trace. I actually do not know which side the exception is, for convoluted reasons in my instance, at present, the client and server are in the same application and the logs don't reveal which side has the error.

Some context - the actual result of the call is fine, i.e. I get the data I wanted. My use case is basically that the client is contacting the server to ask for information, the server responds, the client processes the response and then asks for the next lot of information. 

When the server determines it has sent all the information, it calls onCompleted. The client knows after onCompleted has been called its side to not make any onNext calls (though I do see that conceptually the server could send onCompleted and the client onNext at the same time, not sure if this is a problem?)

Is this wrong? Am I supposed to have the server wait to be called again, have the server tell the client via onNext that it is done, have the client call onCompleted and then have the server call onCompleted ?

Through reading of the code and manually testing behaviour, I have been able to reasonably convince myself of the behaviour of things, but it must be written down somewhere, right? Not actually knowing anything of substance about the rpc protocol has me anxious. whether what I am doing is correct.

**Comment by sanjaypujare** [comment]
> Have updated my question with the full stack trace. I actually do not know which side the exception is, for convoluted reasons in my instance, at present, the client and server are in the same application and the logs don't reveal which side has the error.

Would it be possible to split this into 2 programs or use the existing program but 2 different instances one each for client and server side so we can clearly see the client and server side logs?

> 
> Some context - the actual result of the call is fine, i.e. I get the data I wanted. My use case is basically that the client is contacting the server to ask for information, the server responds, the client processes the response and then asks for the next lot of information.
> 
> When the server determines it has sent all the information, it calls onCompleted. The client knows after onCompleted has been called its side to not make any onNext calls (though I do see that conceptually the server could send onCompleted and the client onNext at the same time, not sure if this is a problem? In reality it won't happen as the server knows immediately if it is done, while the client has quite a bit of processing to do before it will do the next ask)
> 
> Is this wrong? Am I supposed to have the server wait to be called again, have the server tell the client via onNext that it is done, have the client call onCompleted and then have the server call onCompleted ?

Based on the reference I provided (https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-termination) it does look like what you are doing is supported and ought to work.

> 
> Through reading of the java grpc code and manually testing behaviour, I have been able to reasonably convince myself of the behaviour of things, but it must be written down somewhere, right? Not actually knowing anything of substance about the rpc protocol has me anxious regarding whether what I am doing is correct.

Let me do some more research/discussion and I will post my findings here. In the mean time it will be good if you can split the client and server so we get separate logs.

**Comment by ejona86** [comment]
I need to read this issue still, but I'll note that "Received DATA frame for an unknown stream X" tends to occur most often with cancellation. But it can happen in bidi cases where the server closes before the client. It is almost certainly benign.

I'm a bit surprised to see this still being logged. I thought the log levels had been reduced. Maybe we haven't upgraded to a new enough Netty yet.

Some quick details would be helpful: what version of grpc were you using? Is it correct to say you saw this logged on the server-side? Could you share the log line information itself (which has the code location logging and the log level)?

**Comment by Kircheisser** [comment]
I split the server and client up and can tell you that the log is indeed on the server side. 

We are using 1.33.0 of grpc. I can't see any explicit configuration of the log line information. So it means that the log level is INFO.

Good to hear it is almost certainly benign, for the time being I've had the client not call onCompleted when the server calls onCompleted, as it prevents the error appearing and seems appropriate given the server fully closes the connection anyway.

**Comment by sanjaypujare** [comment]
@Kircheisser in that case can this be closed?

**Comment by Kircheisser** [comment]
Conceptually yes, ideally I would still like to have a document I can point to as assurance that I haven't written code that is going to leave a stream open, i.e. a specification of the behaviour of onCompleted from the server side when the client does not call onCompleted in response. 

It sounds like what I am doing is OK, and that this exception when I was calling onCompleted was spurious. If that is so then I think it can be closed.
