### ISSUE TITLE
HTTP/2 error code: COMPRESSION_ERROR

### ISSUE THREAD

**Issue by ssaltin** [grpc/grpc-java#8453]
When I run the basic example on our k8s cluster, I'm getting the following error:

**Client stacktrace**
```
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: COMPRESSION_ERROR
Received Goaway
decode only works with an entire header block! PooledSlicedByteBuf(ridx: 108, widx: 195, cap: 195/195, unwrapped: PooledUnsafeDirectByteBuf(ridx: 209, widx: 230, cap: 1024))
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at 
```
**Server stacktrace**
```
java.lang.IllegalArgumentException: decode only works with an entire header block! PooledSlicedByteBuf(ridx: 108, widx: 195, cap: 195/195, unwrapped: PooledUnsafeDirectByteBuf(ridx: 209, widx: 230, cap: 1024))
at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
```

Client call is very simple:
```
ManagedChannel channel = ManagedChannelBuilder.forAddress("10.199.87.212", 8080)
            .usePlaintext()
            .build();

        EvaluationServiceGrpc.EvaluationServiceBlockingStub stub =
            EvaluationServiceGrpc.newBlockingStub(channel);
        List<Integer> ids = new ArrayList<>();
        ids.add(1);
        ids.add(2);
        ids.add(3);
        ids.add(4);
        ids.add(5);
        int successCount = 0;
        int failedCount = 0;

        for (int i = 0; i < 20; i++) {
            try {
                EvaluationResponse hello = stub.hello(EvaluationRequest.newBuilder()
                    .addAllIds(ids)
                    .build());

                successCount++;
                System.out.println("Response received from server:\n" + hello.getEvaluationItemsList().size());
            } catch (Exception e) {
                failedCount++;
            }
        }
```

and after code runs, `successCount` is 10 and `failedCount` is 10. When I run the client call, it works fine and server returns data fine, but when I run it again, it fails and sends this error.

When I try code agains local server, it works fine without any problem, it happens when I deploy the service to k8s.

Is there any bug around this? Or am I doing something very wrong?

PS: I'm following this guideline https://grpc.io/docs/languages/java/basics/ and https://www.baeldung.com/grpc-introduction, I searched for `COMPRESSION_ERROR` but unfortunately I cannot find any information about the issue.

**Comment by ejona86** [comment]
Which version of grpc and Netty does the client/server use? It seems you are using `grpc-netty` and not `grpc-netty-shaded`, so the Netty version is important.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
