### ISSUE TITLE
Panic! This is a bug!

### ISSUE THREAD

**Issue by wangweilica** [grpc/grpc-java#8455]
### What version of gRPC-Java are you using?
io.grpc 1.23.0
### What is your environment?

Red Hat 4.8.5-28  jdk1.8
 this project deploy in k8s
### What did you see instead?
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
```
.21:01:49.271 [http-nio-18080-exec-4] INFO c.i.m.c.pool.GrpcChannelPoolManager - --> Engine service pool info: key:IMEEP-GANDALFS:1.0, engine resource name:[IMEEP-GANDALFS:1.0], service id:[imeep-gandalfs:1.0.0000.demo], tags:[imeep]
.21:01:49.272 [http-nio-18080-exec-4] ERROR c.i.m.c.s.ImeepGrpcClientConnectionService - --> exception: Request grpc server exception. error message:INTERNAL: Panic! This is a bug!
.21:01:49.272 [http-nio-18080-exec-4] ERROR c.i.m.c.s.ImeepGrpcClientConnectionService - --> exception: Request grpc server exception. error message:INTERNAL: Panic! This is a bug!
.21:01:49.273 [http-nio-18080-exec-4] ERROR com.iflytek.proxy.BccEngineProxy - --> Retry grpc connection error
com.iflytek.medical.client.exception.ImeepClientException: Process Grpc request exception
at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.processHandler(ImeepGrpcClientConnectionService.java:222)
at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.lambda$processRetryHandler$0(ImeepGrpcClientConnectionService.java:196)
at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.processRetryHandler(ImeepGrpcClientConnectionService.java:191)
at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.process(ImeepGrpcClientConnectionService.java:168)
at com.iflytek.medical.client.service.ImeepGrpcClientService.sendGrpcRequest(ImeepGrpcClientService.java:134)
at com.iflytek.proxy.BccEngineProxy.process(BccEngineProxy.java:53)
at com.iflytek.service.impl.KieServiceImpl.getKieEngineOutputHandler(KieServiceImpl.java:88)
at com.iflytek.web.GandalfCotroller.kie(GandalfCotroller.java:46)
at com.iflytek.web.GandalfCotroller$$FastClassBySpringCGLIB$$5053a9ac.invoke()
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
at com.iflytek.web.GandalfCotroller$$EnhancerBySpringCGLIB$$fec55415.kie()
at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.iflytek.spas.common.filter.VersionLabelFilter.doFilter(VersionLabelFilter.java:74)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
at com.iflytek.medical.imeep.ImeepApiGrpc$ImeepApiBlockingStub.process(ImeepApiGrpc.java:179)
```
### Steps to reproduce the bug
Only twice in recent months, in addition 。I can not reproduce the bug

**Comment by ejona86** [comment]
The `StatusRuntimeException` should have a cause itself, and _that_ describes the bug. Somehow that is being lost (or wasn't included here by accident). Is the exception being sent over the wire or anything funny like that (such that it would be serialized/deserialized)?

I'll note that when this bug triggers, there should be a SEVERE log with the text "Uncaught exception in the SynchronizationContext. Panic!" and it will also include the exception.

**Comment by ejona86** [comment]
Oh, grpc version 1.23.0. That's two years old. I don't think there's much point for us to look into this with such an old grpc version. It was probably already fixed.

**Comment by wangweilica** [comment]
> The `StatusRuntimeException` should have a cause itself, and _that_ describes the bug. Somehow that is being lost (or wasn't included here by accident). Is the exception being sent over the wire or anything funny like that (such that it would be serialized/deserialized)?
> 
> I'll note that when this bug triggers, there should be a SEVERE log with the text "Uncaught exception in the SynchronizationContext. Panic!" and it will also include the exception.

complete error stack ：
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at com.iflytek.medical.imeep.ImeepApiGrpc$ImeepApiBlockingStub.process(ImeepApiGrpc.java:179)
	at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.processHandler(ImeepGrpcClientConnectionService.java:216)
	... 88 more
Caused by: java.lang.NullPointerException
	at com.iflytek.medical.client.provider.ConsulClientProvider.getConsulClient(ConsulClientProvider.java:78)
	at com.iflytek.medical.client.consul.ConsulNameResolver.start(ConsulNameResolver.java:57)
	at io.grpc.NameResolver.start(NameResolver.java:101)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:385)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:473)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider.get(ManagedChannelImpl.java:477)
	at io.grpc.internal.ManagedChannelImpl$ChannelTransportProvider$1RetryStream.newSubstream(ManagedChannelImpl.java:535)
	at io.grpc.internal.RetriableStream.createSubstream(RetriableStream.java:206)
	at io.grpc.internal.RetriableStream.start(RetriableStream.java:311)
	at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:290)
	at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:190)
	at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
	at com.iflytek.medical.client.intercept.ImeepIntercept$1.start(ImeepIntercept.java:23)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:310)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:282)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:129)
	at com.iflytek.medical.imeep.ImeepApiGrpc$ImeepApiBlockingStub.process(ImeepApiGrpc.java:179)
	at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.processHandler(ImeepGrpcClientConnectionService.java:216)
	at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.lambda$processRetryHandler$0(ImeepGrpcClientConnectionService.java:196)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
	at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.processRetryHandler(ImeepGrpcClientConnectionService.java:191)
	at com.iflytek.medical.client.service.ImeepGrpcClientConnectionService.process(ImeepGrpcClientConnectionService.java:168)
	at com.iflytek.medical.client.service.ImeepGrpcClientService.sendGrpcRequest(ImeepGrpcClientService.java:134)
	at com.iflytek.proxy.BccEngineProxy.process(BccEngineProxy.java:44)
	at com.iflytek.service.impl.KieServiceImpl.getKieEngineOutputHandler(KieServiceImpl.java:88)
	at com.iflytek.web.GandalfCotroller.kie(GandalfCotroller.java:46)
	at com.iflytek.web.GandalfCotroller$$FastClassBySpringCGLIB$$5053a9ac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.iflytek.web.GandalfCotroller$$EnhancerBySpringCGLIB$$fec55415.kie(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	... 64 more

**Comment by ejona86** [comment]
Ah, excellent. Thanks for the full causal chain. Looks like a custom NameResolver is failing with NPE:

```
Caused by: java.lang.NullPointerException
	at com.iflytek.medical.client.provider.ConsulClientProvider.getConsulClient(ConsulClientProvider.java:78)
	at com.iflytek.medical.client.consul.ConsulNameResolver.start(ConsulNameResolver.java:57)
	at io.grpc.NameResolver.start(NameResolver.java:101)
```

That is out of gRPC's hands. But I imagine that should be enough to track down the code and figure out why it is failing.
