### ISSUE TITLE
gRPC xDS client returned an unusable name resolver error with xDS server

### ISSUE THREAD

**Issue by BuddhiWathsala** [grpc/grpc-java#8592]
I tried a gRPC xDS client implementation with a [go-control-plane](https://github.com/envoyproxy/go-control-plane/tree/main/internal/example) implementation. Go clients that I implemented works without an issue, however, the Java client returned the following error. 

Note that, I've correctly imported the relevant xDS libraries as in this [documentation](https://cloud.google.com/traffic-director/docs/prepare-proxyless-grpc).

```sh
Oct 12, 2021 4:14:36 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (xds:///be-srv)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=NameResolver returned no usable address. addrs=[], attrs={}
WARNING: [Channel<1>: (xds:///be-srv)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=NameResolver returned no usable address. addrs=[], attrs={}

io.grpc.xds.XdsNameResolver@543728dc was used, cause=null}
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: NameResolver returned no usable address. addrs=[], attrs={}
io.grpc.xds.XdsNameResolver@543728dc was used
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at HelloWorldServiceGrpc$HelloWorldServiceBlockingStub.hello(HelloWorldServiceGrpc.java:154)
	at HelloWorldClient.main(HelloWorldClient.java:48)
```

Then, I tried it with a java-control-plane, but I encountered  the same issue.

**Comment by BuddhiWathsala** [comment]
I am able to solve this by changing the go-control-plane implementation as mentioned [here](https://github.com/grpc/grpc-go/issues/4863#issuecomment-941124496). Thanks for your concern.
