### ISSUE TITLE
Client Side Streaming OutOfDirectMemoryError: failed to allocate direct memory

### ISSUE THREAD

**Issue by Jalr4ever** [grpc/grpc-java#8672]
### What version of gRPC-Java are you using?

1.34.1.

### What is your environment?

- macOs Big Sur 11.2.3.
- IDEA 2020.1
- java version "1.8.0_271"
- Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
- Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

### What did you expect to see?

Running upload logic without any error。

### What did you see instead?

Client side occurred OutOfDirectMemoryError: failed to allocate direct memory.

### Steps to reproduce the bug

**It's actually a mock to test how would gRPC do when endpoint process speed is in huge imbalance.** 

I use gRPC Client Side Streaming to implement Upload Business in my project lately. Well this issue would not happend when I do uploading things by HTTP 1.1 using Serverlet, which put data in http request payload, in java back end, retrive payload data steaming using api like javax.servlet.http.HttpServletRequest#getInputStream()

First of all, client and server configuration are:

```java
// Server
public void start() throws IOException {
    this.server = NettyServerBuilder
            .forPort(getServerPort())
            .permitKeepAliveWithoutCalls(true)
            .bossEventLoopGroup(new NioEventLoopGroup(1))
            .workerEventLoopGroup(new NioEventLoopGroup(8))
            .channelType(NioServerSocketChannel.class)
            .addService(new StorageService()).build().start();
    log.info("Server started at port: {}", getServerPort());
    Runtime.getRuntime().addShutdownHook(new Thread(StorageServiceRpcServer.this::stop));
}

// Client
public static StorageServiceRpcClient defaultClient() {
    Integer port = PropsUtil.get("application.properties").getInt("client-storage-upload-service.port");
    String host = PropsUtil.get("application.properties").getStr("client-storage-upload-service.host");
    StorageServiceRpcClient client = new StorageServiceRpcClient();
    ManagedChannel channel = NettyChannelBuilder.forAddress(host, port)
            .eventLoopGroup(new NioEventLoopGroup(1))
            .channelType(NioSocketChannel.class)
            .usePlaintext() 
            .build();
    client.storageServiceStub = StorageServiceGrpc.newStub(channel);
    return client;
}
```

I make client send  3MB message per ms, something like:

```
// request chunk data info
byte[] buffer = new byte[3 * 1024 * 1024];
int length;
length = is.read(buffer);
int time = 0;
while (time < 10000) {
    requestObserver.onNext(uploadChunkRequest(buffer, length));
    time++;
    try {
        Thread.sleep(5);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```

Server handle message per 5s:

```java
@Override
public void onNext(ClientSideStreamingRpcService.UploadRequest value) {
    switch (value.getDataCase()) {
        case REQUEST:
            log.info("Server handle file {}, metadata", fileName);
            break;
        case CHUNK:
            log.info("Server handle file chunk");
            try {
                Thread.sleep(5000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            break;
        default:
            log.error("Server handle error onNext()");
            break;
    }
}
```

Running the server and client, and then client occurred exception, segment like below:

```java
[2021-11-08 10:44:47] [INFO] com.wayland.server.StorageService: Server handle file chunk
[2021-11-08 10:44:52] [INFO] com.wayland.server.StorageService: Server handle file chunk
Exception in thread "main" io.grpc.netty.shaded.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 7633633559, max: 7635730432)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
	at io.grpc.netty.shaded.io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51)
	at io.grpc.internal.MessageFramer.writeRaw(MessageFramer.java:287)
	at io.grpc.internal.MessageFramer.access$400(MessageFramer.java:43)
	at io.grpc.internal.MessageFramer$OutputStreamAdapter.write(MessageFramer.java:377)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.write(CodedOutputStream.java:3005)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeLazy(CodedOutputStream.java:3013)
	at com.google.protobuf.ByteString$LiteralByteString.writeTo(ByteString.java:1392)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytesNoTag(CodedOutputStream.java:2801)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.writeBytes(CodedOutputStream.java:2775)
	at com.wayland._grpc.client_side_streaming_rpc.ClientSideStreamingRpcService$UploadRequest.writeTo(ClientSideStreamingRpcService.java:1152)
	at com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:83)
	at io.grpc.protobuf.lite.ProtoInputStream.drainTo(ProtoInputStream.java:52)
	at io.grpc.internal.MessageFramer.writeToOutputStream(MessageFramer.java:269)
	at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:230)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:168)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:141)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream.writeMessage(DelayedStream.java:252)
	at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:580)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:564)
	at io.grpc.internal.DelayedClientCall.sendMessage(DelayedClientCall.java:317)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:364)
	at com.wayland.client.StorageServiceRpcClient.upload(StorageServiceRpcClient.java:98)
	at com.wayland.client.StorageServiceRpcClient.upload(StorageServiceRpcClient.java:132)
	at com.wayland.client.StorageServiceRpcClientTest.upload(StorageServiceRpcClientTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

For now my temporary solution is:

- client sending data thread send a chunk to server, await
- server receive a chunk, send a `LOADING Message` to client
- client receive `LOADING Message` , signal sending data thread to send next chunk
- ...

My question is, am I configured gRPC in a wrong way? If is, what's the correct way to do?

**Comment by sergiitk** [comment]
Looks like the client is sending requests faster than server can accept: client sends every 5ms (`Thread.sleep(5);`) and the server takes 5s (`Thread.sleep(5000);`) to process.

Instead of the temporary solution you describe, a better approach would be to observe onReady() / isReady(): https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ClientCallStreamObserver.html#setOnReadyHandler-java.lang.Runnable-

> If true, indicates that the observer is capable of sending additional messages without requiring excessive buffering internally. This value is just a suggestion and the application is free to ignore it, however doing so may result in excessive buffering within the observer.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
