### ISSUE TITLE
Crash in OkHttpClientTransport

### ISSUE THREAD

**Issue by bangarharshit** [grpc/grpc-java#8673]
### What version of gRPC-Java are you using?
1.32.2
### What is your environment?

android
### What did you expect to see?
The library should instantiate 
### What did you see instead?
The library crashes with the following stack-trace:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/HttpUrl$Builder;
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxyRequest(OkHttpClientTransport.java:711)
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxySocket(OkHttpClientTransport.java:663)
	at io.grpc.okhttp.OkHttpClientTransport.access$000(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$302(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$702(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1100(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1502(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1600(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1702(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1802(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$2200(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$2702(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:559)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.HttpUrl$Builder
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxyRequest(OkHttpClientTransport.java:711)
	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxySocket(OkHttpClientTransport.java:663)
	at io.grpc.okhttp.OkHttpClientTransport.access$000(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$302(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$702(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1100(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1502(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1600(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1702(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$1802(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$2200(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport.access$2702(OkHttpClientTransport.java:109)
	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:559)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

### Steps to reproduce the bug
Not fully reproducible but happening on Android 10/11 and mostly on Xiaomi/Realme

**Comment by sergiitk** [comment]
Could this be that affected phones are the only ones configured to use a proxy? `createHttpProxySocket` hits this could be a case that the problem is _always_ in the build, but is only revealed when a proxy is used.
Try to reproduce by configuring a proxy on a phone that does work, and see if it breaks.

**Comment by bangarharshit** [comment]
you are right. I am able to repro the crash for proxies. Let me upgrade and verify.

**Comment by bangarharshit** [comment]
it is also crashing with latest GRPC master.

**Comment by sergiitk** [comment]
Thanks for confirming. Could you double check your setup then? Is this possible that you excluded the okhttp dependency from grpc-okhttp thinking it wasn't necessary?

**Comment by bangarharshit** [comment]
you are right. we are not bundling okhttp2 which is required by grpc-okhttp. added it and the crash is resolved
