### ISSUE TITLE
Race condition in idleTimer & ManagedChannel#enterIdle - refactor needed

### ISSUE THREAD

**Issue by Spikhalskiy** [grpc/grpc-java#8714]
**Edit (2021/12/15):** The following bug is fixed with a hot patch #8746. However, the logic of `idleTimer` in `ManagedChannel` is complex, delicate, and bug-prone. Refactoring is needed to make it more robust and easy to understand.

### What version of gRPC-Java are you using?

1.41.0, current master: 8382bd8e04347478bcf483319fb0b376f726023d

### What is your environment?

Java 11/16, MacOS. Original user report is probably from a Linux  server.

### What did you expect to see?

We trigger `ManagedChannel#enterIdle` API periodically while also keeping `ManagedChannelImpl#idleTimer` with default settings. We expect `ManagedChannelImpl` to work properly and not to end up in panic.

### What did you see instead?

```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Panic! This is a bug!\
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)\
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)\
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)\
...

Caused by: java.lang.IllegalStateException: nameResolver is not started\
at com.google.common.base.Preconditions.checkState(Preconditions.java:502)\
at io.grpc.internal.ManagedChannelImpl.shutdownNameResolverAndLoadBalancer(ManagedChannelImpl.java:360)\
at io.grpc.internal.ManagedChannelImpl.enterIdleMode(ManagedChannelImpl.java:422)\
at io.grpc.internal.ManagedChannelImpl.access$900(ManagedChannelImpl.java:118)\
at io.grpc.internal.ManagedChannelImpl$IdleModeTimer.run(ManagedChannelImpl.java:352)\
at io.grpc.internal.Rescheduler$ChannelFutureRunnable.run(Rescheduler.java:103)\
at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)\
at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)\
at io.grpc.internal.Rescheduler$FutureRunnable.run(Rescheduler.java:80)\
at io.grpc.netty.shaded.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)\
at io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)\
```

The channel is broken after it.

### Steps to reproduce the bug

1. Apply the change to `io.grpc.testing.integration.XdsTestClient`:
https://github.com/Spikhalskiy/grpc-java/commit/86a000095bd0632a3b9c54d82097f9d85d2c350a
2. Start `io.grpc.testing.integration.XdsTestServer#main`
3. Start `io.grpc.testing.integration.XdsTestClient#main` with `--num_channels=1000`
4. Find the reported exception in `XdsTestClient` logs

### Relevant report

The original user report in Temporal JavaSDK: https://github.com/temporalio/sdk-java/issues/863
According to the report, the issue happened after a long period of channel inactivity (> idleTimer period). 
My best guess is that our periodic `#enterIdle` shuts down the `nameResolver` while still-scheduled (`cancel(permanent=false)`) idleTimer sees a stale `enabled=true` and performs the action. But I don't see how this can happen.

**Comment by dapengzhang0** [comment]
@ejona86 This seems a bug. Looking at the code, I don't really understand the comment
https://github.com/grpc/grpc-java/blob/v1.42.1/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L418-L422

It seems not true if `enterIdle()` is call even before the resolver gets started.

**Comment by Spikhalskiy** [comment]
Also, kinda irrelevant, but to work around this I have to disable idleTimer and found this code:

```
    if (unit.toDays(value) >= IDLE_MODE_MAX_TIMEOUT_DAYS) {
      // This disables idle mode
      this.idleTimeoutMillis = ManagedChannelImpl.IDLE_TIMEOUT_MILLIS_DISABLE;
```

So, to disable the idleTimer, I need to pass a value larger than 30 days. Passing ManagedChannelImpl.IDLE_TIMEOUT_MILLIS_DISABLE which is -1 doesn't work and leads to an exception.
Would we great if ManagedChannelBuilder provides a better interface for it.

**Comment by ejona86** [comment]
> It seems not true if enterIdle() is called even before the resolver gets started.

Why do you say that? NameResolver is initialized in the constructor.
https://github.com/grpc/grpc-java/blob/408ffe86b0414b8dede350b86be9d53a7785a449/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L662

It looks like this is a timer bug. The timer firing is racing with the channel being forced into idle by the outside caller.

`enterIdle()` has a check to avoid re-entering idle mode (`lbHelper == null`):
https://github.com/grpc/grpc-java/blob/408ffe86b0414b8dede350b86be9d53a7785a449/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L1353-L1366

But the idle timer doesn't, nor does Rescheduler, as it just treats the SynchronizationContext as an Executor.
https://github.com/grpc/grpc-java/blob/408ffe86b0414b8dede350b86be9d53a7785a449/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L348-L354

We need to either make the timer cancellation non-racy, or we need to add double-check behavior in IdleModeTimer. I generally prefer making timer cancellation non-racy, but Rescheduler will probably make that more annoying.

------

For disabling idleTimeout, the expectation is you'd pass Long.MAX_VALUE or the like. Seems we are missing language like we have on keepAliveTime. We should add something similar to idleTimeout:
> Long.MAX_VALUE nano seconds or an unreasonably large value will disable keepalive

**Comment by dapengzhang0** [comment]
>> It seems not true if enterIdle() is called even before the resolver gets started.

> Why do you say that? NameResolver is initialized in the constructor.

Sorry, I mixed up NameResolver being null, and NameResolver not started. The comment is correct, the NameResolver is not null. My comment should have been:

The following checkState seems not true if `enterIdle()` is called even before the resolver gets started:

https://github.com/grpc/grpc-java/blob/408ffe86b0414b8dede350b86be9d53a7785a449/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L360

**Comment by ejona86** [comment]
> The following checkState seems not true if enterIdle() is called even before the resolver gets started:

If the resolver is not started then the channel is IDLE, thus there's no point in calling enterIdle(). That's why the current semantics are enterIdle() should only be called if non-IDLE. If it is being called when already IDLE (which is a bug in the caller), there are two possible approaches: 1) stop doing that; fix the code that is calling it inappropriately or 2) change its semantics to allow calling even when IDLE.

**Comment by Spikhalskiy** [comment]
@ejona86 
Calling `enterIdle` is already fine if the channel is already IDLE. So, we are at option 2 already.
There is a check there for lb==null that makes sure it does nothing. 
The problem is that check is absent in `idleTimer` and probably cancelation of `idleTimer` inside `enterIdle` races with its scheduling/executing?

Solution 1 will not help, because if this is actually the race, `enterIdle` is called before `idleTimer` and race condition happens most likely after it's called.
 
Also, what the caller even supposed to use for synchronization to make solution 1 happen? `idleTimer` is not exposed to the caller anyhow other than the period config option.
Also, ManagedChannel supposed to be thread safe. Requirement to perform a check for IDLE under some synchronization before calling `enterIdle` makes it non-thread safe.

**Comment by Spikhalskiy** [comment]
This fixes the race and saves all the current contracts:
https://github.com/Spikhalskiy/grpc-java/commit/6d260b80318e6d75cdaef8ecacb43b291d885ff9

I'm not sure if it's the right fix though and if the race should be addressed this way or somewhere inside the `io.grpc.internal.Rescheduler`. Because I would expect a memory barrier somewhere between a call to 
  `Rescheduler#cancel(boolean permanent)` that sets `enabled=false` and a thread that picks up the task from the queue and checks the `enabled` var.

**Comment by dapengzhang0** [comment]
The channel is initially IDLE and if the [idleTimer](https://github.com/grpc/grpc-java/blob/v1.42.1/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L701) expires too soon, it will try to `enterIdleMode()` at the initial IDLE state.

I think Spikhalskiy@6d260b8 is the right fix.

@ejona86 what do you think?

**Comment by ejona86** [comment]
@dapengzhang0, I think checking for `lbHelper == null` would fix this bug. It does make some parts of the code unclear (e.g., why wouldn't `enterIdleMode()` just do the check?) and can hide other bugs. But it is fast and easy and seems a fair initial fix.

**Comment by dapengzhang0** [comment]
> But I'm not sure if it's the right fix or the race should be addressed somewhere inside the `io.grpc.internal.Rescheduler` or `io.grpc.SynchronizationContext`. 
Because I would expect that 
> 1. `Rescheduler#cancel(permanent = false)` call that sets `enabled=false` for `idleTimer` inside `enterIdle` and 
> 2. `idleTimer`'s check of the `enabled` flag inside `ChannelFutureRunnable#run` 

> don't race with each other. Because they both are run under `SynchronizationContext#execute`.


I think the cause of `enabled` spuriously becoming to `true` might be:

When `enterIdleMode()`, the `ManagedChannelImpl.inUseStateAggregator` was not checking

https://github.com/grpc/grpc-java/blob/df4ac5973c6d382175feea609d684c26f467bc2f/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L429 

the in-use status of the `InternalSubchannel`, unlike [`exitIdleMode()`](https://github.com/grpc/grpc-java/blob/df4ac5973c6d382175feea609d684c26f467bc2f/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L392).  So even though `Rescheduler#cancel(permanent = false)` sets `enabled=false`,  when `InternalSubchannel` becomes not in-use, `rescheduleIdleTimer()`, namely `Rescheduler.enabled=true`, can be called by 

https://github.com/grpc/grpc-java/blob/df4ac5973c6d382175feea609d684c26f467bc2f/core/src/main/java/io/grpc/internal/ManagedChannelImpl.java#L2199-L2205

**Comment by ejona86** [comment]
We believe this is a regression introduced by #8425, which was part of 1.41.

**Comment by ejona86** [comment]
Fixed by #8746
