### ISSUE TITLE
Connection closed while performing protocol negotiation for 

### ISSUE THREAD

**Issue by sodaRyCN** [grpc/grpc-java#8778]
when build grpc client use h2c protocol.
`NettyChannelBuilder.forTarget().negotiationType(NegotiationType.PLAINTEXT_UPGRADE).build();`

and build grpc server like following:

`NettyServerBuilder.forPort().addService(xxx).build().start(); `
and then client request server , I got  grpc RuntimeException:

```
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed while performing protocol negotiation for [HttpClientCodec#0, HttpClientUpgradeHandler#0, ProtocolNegotiators$Http2UpgradeAndGrpcHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:557)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:69)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:738)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:717)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
```

I know it's seem like unreasonable: why use H2C instead of H2. I only  have to say it's business needs.

So, i want to know server-side how to support PLAINTEXT_UPGRADE. 
I note NettyServerbuilder has .protocolNegotiator() api, but I not found how to get the param of protocolNegotiator()

**Comment by dapengzhang0** [comment]
Cross-lining this issue with SO question https://stackoverflow.com/questions/70445193/server-side-how-to-support-h2c-protocol

**Comment by dapengzhang0** [comment]
We don't have a grpc server implementation in gRPC-_Java_ that supports h2c upgrade as of now. You might use go server or a proxy to support h2c upgrade.

**Comment by ejona86** [comment]
To be clear, the grpc java server supports plaintext HTTP/2, just not the HTTP/1 to HTTP/2 upgrade. The API on client-side was before we knew whether it'd be important and was in case it was needed for compatibility with a proxy.

**Comment by sodaRyCN** [comment]
@ejona86 @dapengzhang0
Because I saw that the client support H2C protocol, I mistakenly thought that the server also has such capabilities. Is there any plan to supporting H2C, if not  I have to do like @dapengzhang0 said.

**Comment by ejona86** [comment]
@sodaRyCN, there's been no plan on supporting H2C as we've not been aware of any need and no other gRPC language supports H2C (excepting those that are built on a full-blown HTTP stack, like .Net). H2C mainly just adds complications and issues for gRPC.

To consider support, we'd really need to know more than "business needs" on why it is important.

**Comment by sodaRyCN** [comment]
yeah, i got it. thanks for your replay
