### ISSUE TITLE
Some question about UNKNOWN StatusRuntimeException

### ISSUE THREAD

**Issue by horizonzy** [grpc/grpc-java#8831]
stack info.
```
io.grpc.StatusRuntimeException: UNKNOWN
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closedInternal(ClientCallImpl.java:696)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.closed(ClientCallImpl.java:646)
        at io.grpc.internal.ForwardingClientStreamListener.closed(ForwardingClientStreamListener.java:39)
        at io.grpc.internal.InternalSubchannel$CallTracingTransport$1$1.closed(InternalSubchannel.java:658)
        at io.grpc.internal.AbstractClientStream$TransportState.closeListener(AbstractClientStream.java:471)
        at io.grpc.internal.AbstractClientStream$TransportState.access$400(AbstractClientStream.java:233)
        at io.grpc.internal.AbstractClientStream$TransportState$1.run(AbstractClientStream.java:454)
        at io.grpc.internal.AbstractClientStream$TransportState.deframerClosed(AbstractClientStream.java:290)
        at io.grpc.internal.Http2ClientStreamTransportState.deframerClosed(Http2ClientStreamTransportState.java:31)
        at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:229)
        at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191)
        at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:183)
        at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:457)
        at io.grpc.internal.AbstractClientStream$TransportState.transportReportStatus(AbstractClientStream.java:413)
        at io.grpc.internal.AbstractClientStream$TransportState.inboundTrailersReceived(AbstractClientStream.java:396)
        at io.grpc.internal.Http2ClientStreamTransportState.transportTrailersReceived(Http2ClientStreamTransportState.java:177)
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientStream$TransportState.transportHeadersReceived(NettyClientStream.java:373)
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.onHeadersRead(NettyClientHandler.java:361)
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler.access$1200(NettyClientHandler.java:89)
        at io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler$FrameListener.onHeadersRead(NettyClientHandler.java:855)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:373)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:457)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:464)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:254)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
        at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

Hi, I used grpc to communicate between server and server. But I found that exception 'UNKNOWN' occur when server qps is largest. 

So I traced that why this error happen.  
I found that the status from trailers is `Status.UNKNOWN`. The io.grpc.Metadata namesAndValues showed that 
```
@ArrayList[
    @byte[][
        @Byte[58],
        @Byte[115],
        @Byte[116],
        @Byte[97],
        @Byte[116],
        @Byte[117],
        @Byte[115],    
        ],
    @byte[][
        @Byte[50],
        @Byte[48],
        @Byte[48],
    ],
    @byte[][
        @Byte[99],
        @Byte[111],
        @Byte[110],
        @Byte[116],
        @Byte[101],
        @Byte[110],
        @Byte[116],
        @Byte[45],
        @Byte[116],
        @Byte[121],
        @Byte[112],
        @Byte[101],
    ],
    @byte[][
        @Byte[97],        
        @Byte[112],
        @Byte[112],
        @Byte[108],
        @Byte[105],
        @Byte[99],        
        @Byte[97],
        @Byte[116],
        @Byte[105],
        @Byte[111],
        @Byte[110],
        @Byte[47],
        @Byte[103],
        @Byte[114],
        @Byte[112],
        @Byte[99],
    ],
    @byte[][
        @Byte[103],
        @Byte[114],
        @Byte[112],
        @Byte[99],
        @Byte[45],
        @Byte[115],
        @Byte[116],
        @Byte[97],
        @Byte[116],
        @Byte[117],
        @Byte[115],
    ],
    @byte[][
        @Byte[50],
    ],
]
```

The `Status.CODE_KEY` ascii is `[103,114,112,99,45,115,116,97,116,117,115]`, the value is [50]. not \[48](`Status.SUCCESS`).

I want to know the cause of the problem And how to solve it. 
@ejona86  eric, could you give some advice?

**Comment by ejona86** [comment]
It sounds like the server returned UNKNOWN with no additional information. If that is a gRPC Java server, that could be caused by the server throwing an exception. I'd suggest looking at the server logs and debugging on server-side. The client has no information as to what went wrong.

**Comment by horizonzy** [comment]
It means that the status `UNKNOWN` return by server directly? not some abnormal cases?

**Comment by ejona86** [comment]
Abnormal cases on the client should all have a cause. The library (client and server) should never generate a status without a cause or description. (The library could have a bug since there's no compilation failure if we do that wrong, but we take it pretty seriously.) But since causes are dropped from server to client (to avoid leaking too many server details), abnormal cases on the server commonly don't tell the client much. This is the gRPC equivalent of the "dreaded" HTTP 500 error without any additional details.

It is pretty easy with a server interceptor to copy the cause to the Metadata (although, you'd need to make sure to truncate it to avoid exceeding the 8 KB header limit). But that approach isn't generally applicable.

**Comment by horizonzy** [comment]
> Abnormal cases on the client should all have a cause. The library (client and server) should never generate a status without a cause or description. (The library could have a bug since there's no compilation failure if we do that wrong, but we take it pretty seriously.) But since causes are dropped from server to client (to avoid leaking too many server details), abnormal cases on the server commonly don't tell the client much. This is the gRPC equivalent of the "dreaded" HTTP 500 error without any additional details.
> 
> It is pretty easy with a server interceptor to copy the cause to the Metadata (although, you'd need to make sure to truncate it to avoid exceeding the 8 KB header limit). But that approach isn't generally applicable.

Fine. But at the server side, I didn't find any error log info... Thanks for your advice, I will trace unknow status generation at server side later.
