### ISSUE TITLE
io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR

### ISSUE THREAD

**Issue by anuragk-sportsbet** [grpc/grpc-java#8856]
gRPC Client  in Java 11 with below versions
```
grpc-java:1.39.0
io.grpc:grpc-core:1.42.2
```

gRPC server with Scala with below version
```
akka http (v10.2.6) for grpc
```

Client configuration
```
    @Bean
    public ManagedChannel getChannel() {
        // https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html
        this.channel = ManagedChannelBuilder
                .forAddress(address, port)
                .useTransportSecurity()
                // setup 50 mb of max message size
                .maxInboundMessageSize(50 * 1024 * 1024)
                .idleTimeout(idleTimeoutInMinutes, 60)
                .keepAliveTime(keepAliveTimeInMinutes, 2)
                .keepAliveTimeout(keepAliveTimeoutInMinutes, 1)
                .defaultLoadBalancingPolicy("round_robin")
                .maxRetryAttempts(3)
                .build();
        return this.channel;
    }
```
Above channel is used to create Asynchronous/non-blocking stubs to interact with the gRPC server.
Communication RPC is Server-side Streaming

StreamObserver is attached to the non-blocking stub and we get the below Exception in the `onError` function
```
io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR
at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479) ~[grpc-stub-1.42.2.jar!/:1.42.2]
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562) ~[grpc-core-1.42.2.jar!/:1.42.2]
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.42.2.jar!/:1.42.2]
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743) ~[grpc-core-1.42.2.jar!/:1.42.2]
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722) ~[grpc-core-1.42.2.jar!/:1.42.2]
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.42.2.jar!/:1.42.2]
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.42.2.jar!/:1.42.2]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: INTERNAL_ERROR
at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.42.2.jar!/:1.42.2]
... 10 common frames omitted
```

Would appreciate any help on the issue.

**Comment by ejona86** [comment]
The client doesn't know what is wrong. You need to check server logs.

The server is akka and it is what is generating the error, so you should probably discuss the issue with the akka project; the client has already provided all the information it knows. However, given you have `maxInboundMessageSize(50 * 1024 * 1024)` and if I assume akka behaves similarly to the grpc-java server, I expect the problem is you are sending too large of a _request_. `channelBuilder.maxInboundMessageSize()` only controls what _response_ sizes are allowed. The server has to opt-in to receiving larger _requests_ via `serverBuilder.maxInboundMessageSize()`.
