### ISSUE TITLE
UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR

### ISSUE THREAD

**Issue by fgarsombke** [grpc/grpc-java#8930]
### What version of gRPC-Java are you using?

io.grpc 1.42.2 on both client and server
io.netty 4.1.73.Final on both client and server

### What is your environment?
Client: Java 8 running on 64bit Amazon Linux/2.6.6
Server: AWS Fargate 1.4.0, JVM version: 1.8.0_322
Load Balancer for Fargate Server: AWS ALB HTTP/2 enabled

### What did you expect to see?

No GOAWAY errors

### What did you see instead?
10-20 GOAWAY errors per hour over a few hundred thousand requests, even with using the below service config with retry policy.

```
io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed after GOAWAY. HTTP/2 error code: NO_ERROR
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at com.xxxxx.user.api.user.UserServiceGrpc$UserServiceBlockingStub.getEventTokensForAccount(UserServiceGrpc.java:4561)
	at com.xxxxx.event.service.core.GRPCServiceClientPackage.getEventTokensForAccount(GRPCServiceClientPackage.java:21)
```

```

    NettyChannelBuilder nettyChannelBuilder =  NettyChannelBuilder.forAddress(host, port)
      .sslContext(GrpcSslContexts
        .forClient()
        .trustManager(cert)
        .build())
      .negotiationType(NegotiationType.TLS)
      .defaultLoadBalancingPolicy(ROUND_ROBIN_LOAD_BALANCING_POLICY)
      .maxInboundMessageSize(MAX_SECURE_INBOUND_MESSAGE_SIZE);

    applyServiceConfig(serviceName, nettyChannelBuilder);
    return nettyChannelBuilder.build();
  }

  private void applyServiceConfig(String serviceName, NettyChannelBuilder nettyChannelBuilder) {
    if(StringUtils.isNotBlank(serviceName)) {
      nettyChannelBuilder
        .defaultServiceConfig(getServiceConfig(getServiceName()))
        .maxRetryAttempts((int) RETRY_MAX_ATTEMPTS)
        .enableRetry();
    }
  }

  private Map<String, Object> getServiceConfig(String serviceName) {
    Map<String, Object> retryPolicy = new HashMap<>();
    retryPolicy.put("maxAttempts", RETRY_MAX_ATTEMPTS);
    retryPolicy.put("initialBackoff", RETRY_INITIAL_BACKOFF);
    retryPolicy.put("maxBackoff", RETRY_MAX_BACKOFF);
    retryPolicy.put("backoffMultiplier", RETRY_BACKOFF_MULTIPLIER);
    retryPolicy.put("retryableStatusCodes", Arrays.<Object>asList("UNAVAILABLE"));
    Map<String, Object> methodConfig = new HashMap<>();
    Map<String, Object> name = new HashMap<>();
    name.put("service", serviceName);
    methodConfig.put("name", Collections.<Object>singletonList(name));
    methodConfig.put("retryPolicy", retryPolicy);
    Map<String, Object> serviceConfig = new HashMap<>();
    serviceConfig.put("methodConfig", Collections.<Object>singletonList(methodConfig));
    return serviceConfig;
  }
```

We were seeing a lot more GOAWAY errors before we put the retry policy in place, but are still seeing enough errors to be concerned.

Are there any other things we can try to suppress this issue?

Thank you!

**Comment by ejona86** [comment]
Cross-linking with Gitter. I had a single reply for the rough idea of what is going on there. https://gitter.im/grpc/grpc?at=6212ccebc61ef0178e3a764a

**Comment by fgarsombke** [comment]
Thanks @ejona86, do you recommend I close this out and just have the conversation in Gitter? Thanks again for your help!

**Comment by ejona86** [comment]
There's some debugging back-and-forth here that is well-suited to Gitter, so we're continuing there. Closing, for the while at least.
