### ISSUE TITLE
how to avoid java.net.SocketException: Connection reset 

### ISSUE THREAD

**Issue by faculbsz-sg** [grpc/grpc-java#8995]
Hi people, im posting here looking for some guidance.

my setup:
1 grpc-java server (using kotlin - but afaik underlying server is grpc-java) - CUSTOMER
1 grpc-java server - DATA1
1 grpc-python server - DATA2

Running in gcp cloud run

My issue:

I have no much traffic and from time to time my CUSTOMER service acting as a client gets a `java.net.SocketException: Connection reset` whenever calling DATA1 or DATA2 server:
```

description=io exception, cause=java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

CUSTOMER is an always-on CPU allocated service, DATA1 and DATA2 normal non-always-on service.

CUSTOMER and DATA1 service use grpc 1.42.1 and io.netty:netty-tcnative-boringssl-static:2.0.38.Final:
```
runtimeClasspath
...
+--- io.grpc:grpc-netty:1.42.1
|    +--- io.grpc:grpc-core:1.42.1
|    |    \--- io.grpc:grpc-api:1.42.1
|    |         +--- io.grpc:grpc-context:1.42.1
|    |         \--- com.google.code.findbugs:jsr305:3.0.2
|    \--- io.netty:netty-codec-http2:4.1.63.Final
|         +--- io.netty:netty-common:4.1.63.Final
|         +--- io.netty:netty-buffer:4.1.63.Final
|         |    \--- io.netty:netty-common:4.1.63.Final
|         +--- io.netty:netty-transport:4.1.63.Final
|         |    +--- io.netty:netty-common:4.1.63.Final
|         |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|         |    \--- io.netty:netty-resolver:4.1.63.Final
|         |         \--- io.netty:netty-common:4.1.63.Final
|         +--- io.netty:netty-codec:4.1.63.Final
|         |    +--- io.netty:netty-common:4.1.63.Final
|         |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|         |    \--- io.netty:netty-transport:4.1.63.Final (*)
|         +--- io.netty:netty-handler:4.1.63.Final
|         |    +--- io.netty:netty-common:4.1.63.Final
|         |    +--- io.netty:netty-resolver:4.1.63.Final (*)
|         |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|         |    +--- io.netty:netty-transport:4.1.63.Final (*)
|         |    \--- io.netty:netty-codec:4.1.63.Final (*)
|         \--- io.netty:netty-codec-http:4.1.63.Final
|              +--- io.netty:netty-common:4.1.63.Final
|              +--- io.netty:netty-buffer:4.1.63.Final (*)
|              +--- io.netty:netty-transport:4.1.63.Final (*)
|              +--- io.netty:netty-codec:4.1.63.Final (*)
|              \--- io.netty:netty-handler:4.1.63.Final (*)
```
Both services exclude netty-shaded:
`exclude group: 'io.grpc', module: 'grpc-netty-shaded'`

I am expecting to have more traffic soon, and i am worried that these reset connections could become a bigger issue quite fast.

I understand that some configuration can be done to ensure the connections behind the channels are healthy and minimise these resets, but im struggling to find the correct one.

So far my client channels are configured as bellow:
ManagedChannelBuilder.forAddress(host, 443).build()
 
What would you recommend? 

Thanks!

**Comment by faculbsz-sg** [comment]
I enabled `io.grpc.netty.NettyClientHandler` on client and im getting these before connection reset:

```
2022-03-20 19:56:00.689 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}"
2022-03-20 19:56:00.690 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041"
2022-03-20 19:56:00.691 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=65536}"
2022-03-20 19:56:00.691 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND SETTINGS: ack=true"
2022-03-20 19:56:00.691 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041"
2022-03-20 19:56:00.691 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND SETTINGS: ack=true"
2022-03-20 19:56:00.692 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: my-server.a.run.app:443, :path: /myGrpcMethod, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.42.1, traceparent: 00-861e63e4b8aa52f08f77be594dcd1d72-a367b544d5b2c858-01, grpc-accept-encoding: gzip, authorization: Bearer <a_token>] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false"
2022-03-20 19:56:00.692 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=28 bytes=00000000170a0f70726f706572746965732f6765726f100118016200"

2022-03-20 19:56:02.381 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-accept-encoding: identity,deflate,gzip, accept-encoding: identity,gzip, date: Sun, 20 Mar 2022 19:56:02 GMT, server: Google Frontend, x-cloud-trace-context: 861e63e4b8aa52f08f77be594dcd1d72/2209793641622134333;o=1, traceparent: 00-861e63e4b8aa52f08f77be594dcd1d72-1eaac39bebcdde3d-01, alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"] padding=0 endStream=false"
2022-03-20 19:56:02.381 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND DATA: streamId=3 padding=0 endStream=false length=5 bytes=0000000000"
2022-03-20 19:56:02.381 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND PING: ack=false bytes=1234"
2022-03-20 19:56:02.381 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND HEADERS: streamId=3 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true"
2022-03-20 19:56:02.381 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND PING: ack=false bytes=0"
2022-03-20 19:56:02.381 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND PING: ack=true bytes=0"
2022-03-20 19:56:02.382 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] INBOUND PING: ack=true bytes=1234"

2022-03-20 19:58:01.170 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND HEADERS: streamId=5 headers=GrpcHttp2OutboundHeaders[:authority: my-server.a.run.app:443, :path: /myGrpcMethod, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.42.1, traceparent: 00-3ea09f87922639909342605439972dd6-d6691ce5e7156a37-01, grpc-accept-encoding: gzip, authorization: Bearer <a_token>] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false"
2022-03-20 19:58:01.171 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND DATA: streamId=5 padding=0 endStream=true length=26 bytes=00000000150a0f70726f706572746965732f6765726f10011801"
2022-03-20 19:58:01.172 GMT "[id: 0xbd6e5b56, L:/xxx.xxx.x.1:18813 - R:my-server.a.run.app/www.www.ww.ww:443] OUTBOUND GO_AWAY: lastStreamId=2147483647 errorCode=2 length=16 bytes=436f6e6e656374696f6
```

As you can see, 2 minutes before last call, the service call was successful but later failed with errorCode=2

**Comment by ejona86** [comment]
I'd suggest using `channelBuilder.keepaliveTime(5, TimeUnit.MINUTES)` or similar. [gRFC A8](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md) has more background. Essentially TCP requires writes to detect broken connections.

Keepalive can help avoid the connection from breaking in certain circumstances. In those cases you commonly need a keepalive between 30s-1m. Since the connection was broken after 2 minutes, you may be in this situation. And that requires coordination with the server to permit keepalives at greater frequency. Those APIs on server-side are on NettyServerBuilder, so for server-side this issue would be similar to #8991.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
