### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object Exception

### ISSUE THREAD

**Issue by rubykv** [grpc/grpc-java#9026]
### What version of gRPC-Java are you using?
1.45.0
### What is your environment?
Mac OS, Java 17
### What did you expect to see?
Java grpc Server running
### What did you see instead?
error
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'
	at io.grpc.Metadata$Key.validateName(Metadata.java:754)
	at io.grpc.Metadata$Key.<init>(Metadata.java:762)
	at io.grpc.Metadata$Key.<init>(Metadata.java:671)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:971)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:966)
	at io.grpc.Metadata$Key.of(Metadata.java:708)
	at io.grpc.Metadata$Key.of(Metadata.java:704)
	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:84)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:83)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder.<clinit>(NettyServerBuilder.java:84)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:40)
	at io.grpc.netty.shaded.io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:25)
	at io.grpc.ServerBuilder.forPort(ServerBuilder.java:44)
	at com.code_examples.grpc.service.ServerApp.main(ServerApp.java:11)
```
### Steps to reproduce the bug
1. Add grpc-netty-shaded, grpc-protobuf, grpc-stub, annotations-api to the pom file
2. Write server side code
3. Run the app -> Above error message will be thrown.

*Work around* -> Add guava dependency explicitly which overwrites the default gauva: 16.0-rc1 of grpc-netty-shaded.
Can we update the default version of gauva?

**Comment by ejona86** [comment]
I assume you are using Maven? Maven happily downgrades dependencies. We suggest using Maven Enforcer's `requireUpperBoundDeps` to detect these situations, and then you resolve the issue by rearranging dependencies or adding explicit dependencies. See [our example](https://github.com/grpc/grpc-java/blob/master/examples/pom.xml).

> Add guava dependency explicitly which overwrites the default gauva: 16.0-rc1 of grpc-netty-shaded.

That is coming elsewhere from your dependency tree. [grpc-netty-shaded 1.45.0 depends on Guava 31.0.1-android.](https://repo1.maven.org/maven2/io/grpc/grpc-netty-shaded/1.45.0/grpc-netty-shaded-1.45.0.pom)

**Comment by rubykv** [comment]
Thanks for the help. gauva: 16.0-rc1  was coming from a different dependency.
