### ISSUE TITLE
LoadWorkerTest is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#9121]
https://source.cloud.google.com/results/invocations/8cc33ef8-b2cb-49e2-9404-9dee746fd5c5/targets

In this case, LoadWorkerTest.runUnaryBlockingClosedLoop failed, but I suspect it isn't limited to this one test case.
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.grpc.benchmarks.driver.LoadWorkerTest.assertWorkOccurred(LoadWorkerTest.java:198)
	at io.grpc.benchmarks.driver.LoadWorkerTest.runUnaryBlockingClosedLoop(LoadWorkerTest.java:90)
```

**Comment by SreeramdasLavanya** [comment]
Hi @kannanjgithub, 

I tried running LoadWorkerTest and LoadWorkerTest.runUnaryBlockingClosedLoop individually multiple(10+) times on my local environment with the latest code but I don't see any test case is getting failed. 
Unable to repro this issue locally, kindly suggest.

**Comment by ejona86** [comment]
I failed to reproduce this inside Google with `--runs_per_test=1000` and all runs passed. The machine may matter. Although I can't say I've seen this recently. So let's close it until we see it again.
