### ISSUE TITLE
Upgrading to grpc 1.45.0 from 1.40.1 causes too much time for the server to start

### ISSUE THREAD

**Issue by vvenka57** [grpc/grpc-java#9150]
### What version of gRPC and what language are you using?
Upgraded to 1.45.0 from 1.40.1. 
Java/Kotlin

### What operating system (Linux, Windows,...) and version?
Linux

### What did you do?
We upgraded our grpc version from 1.40.1 to 1.45.0

### What did you expect to see?
Our server starts in approximately 2 minutes after grpc 1.45.0 upgrade without any exceptions.

### What did you see instead?
After upgrade, it takes more than 3 minutes for some pods to start and eventually tries restarting multiple times and ends up in backoff state. This also happens with our liveliness probe eventually causing our apps to get restarted in PROD.

Also getting BouncyCastle ALPN class not found exception. This error did not occur with 1.40.1 version.

Reverting back to 1.40.1 solves the problem in lower environment.

**Comment by sanjaypujare** [comment]
> Also getting BouncyCastle ALPN class not found exception. 

Can you paste the stack trace? Do you think this is related to the startup delay or is this an unrelated issue?

**Comment by vvenka57** [comment]
Hello, thanks for the quick response.

Here is the error:

`i.g.n.s.i.n.h.s.BouncyCastleAlpnSslUtils : Unable to initialize BouncyCastleAlpnSslUtils.
java.lang.ClassNotFoundException: org.bouncycastle.jsse.BCSSLEngine
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.lang.Class.forName0(Class.java)
	at java.lang.Class.forName(Class.java:315)
	at io.grpc.netty.shaded.io.netty.handler.ssl.BouncyCastleAlpnSslUtils.<clinit>(BouncyCastleAlpnSslUtils.java:63)
	at java.lang.Class.forName0(Class.java)
	at java.lang.Class.forName(Class.java:315)
	at com.autonomic.ftcpcommandrelay.server.FtcpCommandRelayServerRunner.loadClassesForPackages(FtcpCommandRelayServerRunner.kt:132)
	at com.autonomic.ftcpcommandrelay.server.FtcpCommandRelayServerRunner.run(FtcpCommandRelayServerRunner.kt:78)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.autonomic.ftcpcommandrelay.server.FtcpCommandRelayServerApplicationKt.main(FtcpCommandRelayServerApplication.kt:43)`

With 1.40.1 version, we do not see this error. Other than this we do not see any difference in the log between 1.40.1 and 1.45.0 versions. I wanted to test by excluding the BouncyCastleAlpnSslUtils class but not able to do so. So I cant confirm if this is just a side effect or the cause for server startup delay issue. 

We also tried the official versions from here - https://github.com/grpc/grpc-java/blob/master/SECURITY.md#:~:text=1.44.x,2.0.46.Final. It also produces the same error and we do see the server start up delay.

**Comment by sanjaypujare** [comment]
The error may not be related to your server startup time issue. It could be caused by changes in netty (from version 4.1.52.Final to 4.1.72.Final which correspond to gRPC upgrade from 1.40.1 to 1.45.0).

It seems your liveness probe is also failing for the same reason i.e. the grpc server takes time to start up so liveness fails. Can you increase the logging level and dump the logs so that might give a clue?

**Comment by ejona86** [comment]
How long did it previously take to start? It sounds like it was slow before and is now just slower still. I think you'd need to explain how much slower (e.g., 2 minutes 35 seconds became 3 minutes 15 seconds). It looks like you have custom behavior in `loadClassesForPackages` to pre-load classes. Minutes is certainly slow, but you don't say how beefy your machines are. I don't have any concept for how slow loading all classes (including ones that are otherwise unused) would take.

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen. I suspect there's nothing special going on here and instead `loadClassesForPackages` is not scaling.
