### ISSUE TITLE
Hit the frame size limit of 100MB. Any way to increase this limit?

### ISSUE THREAD

**Issue by kevinsi4508** [grpc/grpc-java#917]
2015-09-01 16:14:57 WARN  ResumingStreamingResultScanner:103 - IOExceptionWithStatus: 
com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:66)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner$ResponseQueueReader.getNextMergedRow(StreamingBigtableResultScanner.java:75)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:136)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:1)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:90)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:1)
	at com.google.cloud.bigtable.hbase.ReadFirstRow.getRow(ReadFirstRow.java:60)
	at com.google.cloud.bigtable.hbase.ReadFirstRow.main(ReadFirstRow.java:109)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Exception deframing message
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:264)
	at io.grpc.ClientCallImpl$ClientStreamListenerImpl$3.run(ClientCallImpl.java:317)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Frame size 155458981 exceeds maximum: 104857600, 
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:336)
	at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:239)
	at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:175)
	at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:270)
	at io.grpc.internal.AbstractClientStream.inboundDataReceived(AbstractClientStream.java:154)
	at io.grpc.internal.Http2ClientStream.transportDataReceived(Http2ClientStream.java:134)
	at io.grpc.netty.NettyClientStream.transportDataReceived(NettyClientStream.java:119)
	at io.grpc.netty.NettyClientHandler.onDataRead(NettyClientHandler.java:219)
	at io.grpc.netty.NettyClientHandler.access$800(NettyClientHandler.java:79)
	at io.grpc.netty.NettyClientHandler$LazyFrameListener.onDataRead(NettyClientHandler.java:546)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:234)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:46)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:392)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:223)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:130)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:100)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:293)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1069)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:944)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)

**Comment by ejona86** [comment]
Set maxMessageSize() on the Channel/Server builder.

**Comment by kevinsi4508** [comment]
thanks! works like a charm!

**Comment by tobegit3hub** [comment]
Great. It works for us 👍
