### ISSUE TITLE
Q: DEADLINE_EXCEEDED & transient failure handling

### ISSUE THREAD

**Issue by lmcdasi** [grpc/grpc-java#9229]
I'm facing an issue where I'm getting a DEADLINE_EXCEEDED after a certain number of seconds. My service is on prem & talks to services on Azure cloud. The Azure cloud is set to close tcp connections after an inactivity timer of 5 mins.

The communication goes through Ambassador(Envoy proxy).

When the deadline exceeded occurs I went on the envoy proxy and looked at the access log. There is no log related to the grpc call that gives the deadline error.

The stack trace is: 
```
2022-06-01T16:05:21.359740743-04:00 2022-06-01T20:05:21.359Z <> {session=,trace=,span=,client=,thread=pool-5-thread-2} INFO: [....] Sending ConnectorMessage connector_command_response {_  command_id: "e096d8ad-23df-4004-ba53-6d447c92cb7b"_  status: OK_  command_response {_    type_url: "type.googleapis.com/...."_    value: "\b\002\"3R\027\n\023recordingsCompleted\020\006R\030\n\024recordingsInProgress\020\000"_  }_}_ 
2022-06-01T16:05:21.701860889-04:00 2022-06-01T20:05:21.701Z <> {session=,trace=,span=,client=,thread=pool-5-thread-1} ERROR: [..... Error handling command 
2022-06-01T16:05:21.701860889-04:00 io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 14.999450101s. [closed=[], open=[[remote_addr=......./40.86.252.122:443]]]
2022-06-01T16:05:21.701860889-04:00 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
2022-06-01T16:05:21.701860889-04:00 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
2022-06-01T16:05:21.701860889-04:00 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
....
```

I have set an idle timeout of 30 sec to avoid keeping the pipes open & ending having bad connections. No keepalives since they are not supposed to be live long sessions.

So - from that deadline exceeded is there anything that I can do to see if the connection is in a transient failure state ?!?

I do not want to recreate the connection at each deadline exceeded ... since normally they would indicate that the server is busy.

Any suggestions ?!? Thx !

**Comment by lmcdasi** [comment]
I think you meant: GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA

**Comment by ejona86** [comment]
GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA has nothing to do with grpc-java. Assuming you are talking about my mention of MAX_CONCURRENT_STREAMS, no I meant MAX_CONCURRENT_STREAMS (maxCallsPerConnection in grpc-java).

Idle timeout only protects against issues while no RPCs are in progress. If the network has a problem while an RPC is in progress you need active monitoring like keepalive to detect. I generally expect both options to be used in situations like yours (e.g., https://stackoverflow.com/a/57930958/4690866). I do suggest having conservative keepalive, no less than 30-45 seconds or so and most of the time measured in minutes.

Enabling keepalive also enables TCP_USER_TIMEOUT, which can also detect connection failures more rapidly.

For further reading, try the Background and Basic Keepalive sections in [gRFC A8](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md). It doesn't cover idle timeout, but the two complement each other.

**Comment by lmcdasi** [comment]
Would this config help/improve on the channel idle timeout?

**client**:

GRPC_ARG_KEEPALIVE_TIME_MS: 10s
GRPC_ARG_KEEPALIVE_TIMEOUT_MS: 5s
GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA: 2
GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS: 1

**server**:
GRPC_ARG_KEEPALIVE_TIME_MS: 10s
GRPC_ARG_KEEPALIVE_TIMEOUT_MS: 5s
GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA: 2
GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS: 1
GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS: 10s
GRPC_ARG_HTTP2_MAX_PING_STRIKES: 1
