### ISSUE TITLE
Grpc request does not response when an uncaught exception is handled in the SynchronizationContext

### ISSUE THREAD

**Issue by hikoma** [grpc/grpc-java#9257]
### What version of gRPC-Java are you using?
1.47.0

### What is your environment?
macOS 12.3.1
Corretto 11.0.15.9.1
Gradle 7.4.2

### What did you expect to see?
When an uncaught exception is handled in the SynchronizationContext, grpc request throws an exception.

### What did you see instead?
Grpc request does not response.

### Steps to reproduce the bug

Main.java

```java
public class Main {
    public static void main(String[] args) throws Exception {
        ServerBuilder.forPort(6565).addService(new HealthStatusManager().getHealthService()).build().start();

        var channel = ManagedChannelBuilder.forAddress("localhost", 6565).usePlaintext().build();
        var stub = HealthGrpc.newBlockingStub(channel);
        try {
            stub.check(HealthCheckRequest.getDefaultInstance());
        } finally {
            System.out.println("Finish");
        }
    }
}
```

build.gradle

```gradle
plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("io.grpc:grpc-services:1.47.0")
    runtimeOnly("io.grpc:grpc-netty:1.47.0")
}

application {
    mainClass.set("Main")
}

// mergeServiceFiles() is required to suppress uncaughtException
//shadowJar {
//    mergeServiceFiles()
//}
```

Build and run.

```sh
% ./gradlew shadowJar
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :shadowJar

BUILD SUCCESSFUL in 1s

% java -jar build/libs/grpc-test-all.jar                   
Jun 10, 2022 4:57:55 PM io.grpc.internal.ManagedChannelImpl$2 uncaughtException
SEVERE: [Channel<4>: (localhost:6565)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:92)
	at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:63)
	at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:409)
	at io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:984)
	at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:981)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:923)
	at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:150)
	at io.grpc.health.v1.HealthGrpc$HealthBlockingStub.check(HealthGrpc.java:252)
	at Main.main(Main.java:14)
```

Uncaught exception was handled, but the program did not finished.
I expect that `stub.check()` throws an exception.

**Comment by ejona86** [comment]
pick_first is required and your build was just busted. We can't guarantee busted builds will exit cleanly. However, this does show that we don't clear the ConfigSelector, which could be a source of errors while in panic mode.

**Comment by hikoma** [comment]
@ejona86 Thanks for fixing!
