### ISSUE TITLE
name resolution broken in 1.47.0

### ISSUE THREAD

**Issue by morgwai** [grpc/grpc-java#9367]
### What version of gRPC-Java are you using?
1.47.0
### What is your environment?

Linux, openjdk 17.0.3 and 11.0.15
### What did you expect to see?
client code should correctly resolve target specifications and connect to servers just as it used to in 1.46.0 and earlier
### What did you see instead?
exceptions related to target name resolution / parsing after migration to 1.47.0
### Steps to reproduce the bug

given the following client code:
````java
public static void main(String[] args) throws Exception {
	final var channel = ManagedChannelBuilder
			.forTarget(args[0])
			.usePlaintext()
			.build();  // line 21
	final var storageService = RecordStorageGrpc.newBlockingStub(channel)
			.withDeadlineAfter(10, TimeUnit.SECONDS);
	final NewRecordId recordIdResponse = storageService.store(  // line 24
			Record.newBuilder().setContent("contents").build());
	channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
}
````
depending on the format of the target specification, the following exceptions occur:

`dns://127.0.53/localhost:6666` or `dns:/localhost:6666` :
> Exception in thread "main" java.lang.IllegalArgumentException: cannot find a NameResolver for dns://127.0.53/localhost:6666
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:776)
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:785)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:665)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at pl.morgwai.samples.grpc.scopes.grpc.RecordStorageClient.main(RecordStorageClient.java:21)

`localhost:6666`  or `localhost` (this one is incorrect in my setup, but should result in `Connection refused` instead) :
> Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at pl.morgwai.samples.grpc.scopes.grpc.RecordStorageGrpc$RecordStorageBlockingStub.store(RecordStorageGrpc.java:263)
	at pl.morgwai.samples.grpc.scopes.grpc.RecordStorageClient.main(RecordStorageClient.java:24)
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: /localhost:6666
Caused by: java.net.ConnectException: connect(..) failed: Invalid argument
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.connect(Socket.java:312)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:138)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.grpc.netty.shaded.io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
	at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

All the above target specifications work ok with 1.46.0

**Comment by morgwai** [comment]
ok, it seems it was my mistake: I've built a `jar-with-dependencies` using maven assembly plugin and since there's now a new `io.grpc.NameResolverProvider` SPI registration file with `UdsNameResolverProvider`, the plugin arbitrarily included only the new file, discarding the default with DNS based provider...
