### ISSUE TITLE
why connection is auto disconnected

### ISSUE THREAD

**Issue by XiaoWeiKIN** [grpc/grpc-java#9425]
I established a grpc connection and created several streams, but the connection was auto disconnected after a period of time. How can I ensure that the connection is not disconnected.
```
1] [2022-08-02 20:55:46.183] [ERROR] [grpc-default-executor-8] reactor.core.publisher.Operators [TID: N/A] Operator called default onErrorDropped

io.grpc.StatusRuntimeException: CANCELLED: client cancelled

at io.grpc.Status.asRuntimeException(Status.java:526)

at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:291)

at io.grpc.PartialForwardingServerCallListener.onCancel(PartialForwardingServerCallListener.java:40)

at io.grpc.ForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:23)

at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onCancel(ForwardingServerCallListener.java:40)

at io.grpc.Contexts$ContextualizedServerCallListener.onCancel(Contexts.java:96)

at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:362)

at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:350)

at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:913)

at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by sanjaypujare** [comment]
Check if this [ManagedChannelBuilder.html.keepAliveWithoutCalls()](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveWithoutCalls-boolean-) works for you.

**Comment by XiaoWeiKIN** [comment]
hi@sanjaypujare,  I checked the Keeplive proposal, I used the default keeplive configuration, but there is an outstanding stream on my connection, it is long-live, why is the client still disconnected.

**Comment by XiaoWeiKIN** [comment]
After I configure the following properties, I find that the connection is automatically disconnected after 2 minutes. Why 
```
    managedChannelBuilder.keepAliveTime(60L, TimeUnit.SECONDS);
    managedChannelBuilder.keepAliveTimeout(20L, TimeUnit.SECONDS);
    managedChannelBuilder.keepAliveWithoutCalls(true);
```
this is log
```
// connect
[v1] [2022-08-03 18:20:17.787] [INFO ] [lettuce-epollEventLoop-5-1] com.xx.lse.service.grpc.InstanceInfoGrpcService [TID: N/A] Service [lsf-samplex-2.2.x-dev] instance [10.248.30.117] info is ServiceInfo.Instance(ip=127.0.0.1, port=8888, env=dev, vdc=huabei, domain=N/A, language=ServiceInfo.Language(name=JAVA, version=11.0.15), registry=ServiceInfo.Registry(type=eureka, address=http://eureka1-dev.chj.cloud:8000/eureka/,http://eureka2-dev.chj.cloud:8000/eureka/,http://eureka3-dev.chj.cloud:8000/eureka/, instanceId=10.248.30.117:lsf-samplex-2.2.x-dev:8888), extra={lse-agent-version=1.0.0, otel-agent-version=1.16.0}, extraGroups={jvm=ServiceInfo.ExtraGroup(extra={start.time=1659522010837, gc.name=G1 Young Generation-G1 Old Generation, G1 Old Gen=430MB, heap.memory=1024MB, jvm.args=-javaagent:/Users/wangxiaowei1/xiaowei/lse-otel-agent/agent/build/libs/lse-otel-javaagent-1.0.0.jar -Dotel.service.name=otel-lsf -Xms1024m -Xmx1024m -Denv=dev -Dotel.apollo.refresh.init-delay=10 -Dotel.apollo.refresh.period=10 -XX:TieredStopAtLevel=1 -Xverify:none -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=61233:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8, G1 Survivor Space=33MB, Compressed Class Space=10MB, Metaspace=79MB, G1 Eden Space=561MB})}, createTime=1659522017579), store result is [true]
// disconnect
[v1] [2022-08-03 18:22:17.893] [INFO ] [lettuce-epollEventLoop-5-2] com.xxx.lse.config.GRpcConfiguration [TID: N/A] gRpc transport terminated, remove route lsf-samplex-2.2.x-dev:127.0.0.1
```

**Comment by XiaoWeiKIN** [comment]
```
[v1] [2022-08-03 18:33:31.266] [WARN ] [grpc-nio-worker-ELG-1-2] io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler Received GOAWAY with ENHANCE_YOUR_CALM. Debug data: too_many_pings
[v1] [2022-08-03 18:33:31.268] [WARN ] [grpc-nio-worker-ELG-1-2] io.grpc.internal.AtomicBackoff Increased keepalive time nanos to 120,000,000,000
[v1] [2022-08-03 18:33:31.274] [WARN ] [grpc-default-executor-5] com.lixiang.lsf.duplexer.DefaultGRpcDuplexer Failed to request featuress. Server responded with gRPC status code 8. Error message: Connection closed after GOAWAY. HTTP/2 error code: ENHANCE_YOUR_CALM (Bandwidth exhausted), debug data: too_many_pings
[v1] [2022-08-03 18:33:31.274] [WARN ] [grpc-default-executor-4] com.lixiang.lsf.duplexer.DefaultGRpcDuplexer Failed to request log_levels. Server responded with gRPC status code 8. Error message: Connection closed after GOAWAY. HTTP/2 error code: ENHANCE_YOUR_CALM (Bandwidth exhausted), debug data: too_many_pings

```

**Comment by ejona86** [comment]
Both `keepAliveTime()` and `keepAliveWithoutCalls()` have [in their documentation](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#keepAliveTime-long-java.util.concurrent.TimeUnit-):
> Clients must receive permission from the service owner before enabling this option.

The ENHANCE_YOUR_CALM too_many_pings error means you have exceeded the keepalive rate or keepAliveWithoutCalls is not permitted. See [gRFC A8](https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md#server-enforcement) for more information.

**Comment by XiaoWeiKIN** [comment]
@ejona86 thanks
