### ISSUE TITLE
GRPC using DomainSocketAddress, server side fine, client side errors with java.net.ConnectException: connect(..) failed: Address family not supported by protocol family

### ISSUE THREAD

**Issue by Hellblazer** [grpc/grpc-java#9431]
### What version of gRPC-Java are you using?
1.48.1

### What is your environment?
Java 17
Apple MBP M1

### What did you expect to see?
A successful round trip of a trivial rpc server over unix domain sockets

### What did you see instead?
Using domain sockets with Netty, the server side starts up successfully.  The domain socket file exists and was created by the server starting.  However, when the client runs, it errors out with:

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at domain.DomainSocketReproTest.smokin(DomainSocketReproTest.java:62)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol family: target/smokin.socket
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol family

### Steps to reproduce the bug
This [repository](https://github.com/Hellblazer/GrpcDomainSocketTest) contains the test case I used to reproduce this problem. 

The test class [DomainSocketReproTest](https://github.com/Hellblazer/GrpcDomainSocketTest/blob/main/src/test/java/domain/DomainSocketReproTest.java#L26).

This is the full stack trace:
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at test.TestItGrpc$TestItBlockingStub.ping(TestItGrpc.java:157)
	at domain.DomainSocketReproTest.smokin(DomainSocketReproTest.java:62)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol family: target/smokin.socket
Caused by: java.net.ConnectException: connect(..) failed: Address family not supported by protocol family
	at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155)
	at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128)
	at io.netty.channel.unix.Socket.connect(Socket.java:313)
	at io.netty.channel.kqueue.AbstractKQueueChannel.doConnect0(AbstractKQueueChannel.java:719)
	at io.netty.channel.kqueue.KQueueSocketChannel.doConnect0(KQueueSocketChannel.java:102)
	at io.netty.channel.kqueue.AbstractKQueueChannel.doConnect(AbstractKQueueChannel.java:704)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.connect(AbstractKQueueChannel.java:550)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
	at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:538)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:293)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Hellblazer** [comment]
lol.  I fixed this by using:

io.netty.channel.kqueue.KQueueDomainSocketChannel instead of: io.netty.channel.kqueue.KQueueSocketChannel

hope this helps someone looking for this on ye intertubes.
