### ISSUE TITLE
 Fatal Exception: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hoi-nx** [grpc/grpc-java#9448]
### What version of gRPC-Java are you using?
Environement:
*  runtimeOnly 'io.grpc:grpc-netty-shaded:1.48.1'
    implementation 'io.grpc:grpc-protobuf:1.48.1'
    implementation 'io.grpc:grpc-stub:1.48.1'
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'
### What is your environment?

Window with java 8
IDE: intellij

### Steps to reproduce the bug
Exception
```
Following Fatal Exception occurs shortly after displaying in-app message:
 java.lang.ArrayIndexOutOfBoundsException: 1420
	at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:481)
	at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:228)
	at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:86)
	at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:72)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:91)
	at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:105)
	at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
	at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:398)
	at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:406)
```

**Comment by sergiitk** [comment]
We need more details to look into this. I don't see gRPC in the stack trace. Was it existing application that you updated? Or you're creating something new?

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen. This seems unlikely to be a gRPC bug though.
