### ISSUE TITLE
okhttp `maxConnectionIdleTimer_respondWithError ` is flaky

### ISSUE THREAD

**Issue by YifeiZhuang** [grpc/grpc-java#9503]
[logs](https://github.com/grpc/grpc-java/runs/8121580486?check_suite_focus=true)
```
io.grpc.okhttp.OkHttpServerTransportTest > maxConnectionIdleTimer_respondWithError FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
        at java.base@11.0.16.1/java.lang.Object.wait(Native Method)
        at java.base@11.0.16.1/java.io.PipedInputStream.read(PipedInputStream.java:326)
        at java.base@11.0.16.1/java.io.PipedInputStream.read(PipedInputStream.java:377)
        at app//okio.Okio$2.read(Okio.java:140)
        at app//okio.RealBufferedSource.request(RealBufferedSource.java:72)
        at app//okio.RealBufferedSource.require(RealBufferedSource.java:65)
        at app//io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:120)
        at app//io.grpc.okhttp.OkHttpServerTransportTest.verifyGracefulShutdown(OkHttpServerTransportTest.java:1104)
        at app//io.grpc.okhttp.OkHttpServerTransportTest.maxConnectionIdleTimer_respondWithError(OkHttpServerTransportTest.java:206)

```

**Comment by ejona86** [comment]
Java 8 failure: https://github.com/grpc/grpc-java/runs/8238718680?check_suite_focus=true
