### ISSUE TITLE
Direct Memory Leak on 1.31.1

### ISSUE THREAD

**Issue by liujinyu0107** [grpc/grpc-java#9540]
when I use grpc-java  1.31.1  ,then an error occured. detail msg as follow
```
Caused by: io.grpc.netty.shaded.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 2097152 byte(s) of direct memory (used: 534774039, max: 536870912)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:742)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:697)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at io.grpc.netty.shaded.io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.grpc.netty.shaded.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:123)
	at io.grpc.netty.shaded.io.grpc.netty.NettyWritableBufferAllocator.allocate(NettyWritableBufferAllocator.java:51)
	at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:227)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:168)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:141)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:65)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream.writeMessage(DelayedStream.java:252)
	at io.grpc.internal.ClientCallImpl.sendMessageInternal(ClientCallImpl.java:544)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:528)
	at io.grpc.stub.ClientCalls$CallToStreamObserverAdapter.onNext(ClientCalls.java:364)
```

**Comment by YifeiZhuang** [comment]
> Is it possible that you are sending large messages at a high frequency? RPCs will queue waiting to be sent, and if you > queue too many you will see such out of memory errors.

> If you are doing unary RPCs, you may consider limiting yourself to X concurrent RPCs (note this is different from the server's max concurrent). If doing streaming RPCs you can observe flow control.

similar issues seem frequent, e.g. #2710.

**Comment by liujinyu0107** [comment]
> 

thanks,   I am doing streaming at a high frequency. How can I avoid this problem or how to flow control ?

**Comment by YifeiZhuang** [comment]
you might noticed there is an example for manual flow control for streaming calls: https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/manualflowcontrol
 @ejona86 do we have suggested way to profile or monitor this problem?

**Comment by ejona86** [comment]
"Do not send when `isReady()` is false" is the main recommendation, which also implies using `setOnReadyHandler()` to know when to check if it becomes true again.

1.31.1 is two years old, so we wouldn't spend any time investigating a bug. But if you are doing streaming and not calling `isReady()`, lack of flow control is almost certainly the problem.

**Comment by liujinyu0107** [comment]
> you might noticed there is an example for manual flow control for streaming calls: https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/manualflowcontrol @ejona86 do we have suggested way to profile or monitor this problem?

okay,thanks very much

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
