### ISSUE TITLE
NameResolver should explicitly state that methods executed in SynchronizationContext must not throw

### ISSUE THREAD

**Issue by baltiyskiy** [grpc/grpc-java#9541]
When a `NameResolver` implementation throws from `start(Listener)`, it leads to a panic in `ManagedChannelImpl` because of unhandled exception in `SynchronizationContext`.  After that, the channel becomes unusable.

The suggestion is to make the no-throw contract for `NameResolver.start()` explicit.

Example stack trace:

```
                at io.grpc.NameResolver.start(NameResolver.java:105)
                at io.grpc.internal.ForwardingNameResolver.start(ForwardingNameResolver.java:48)
                at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:415)
                at io.grpc.internal.ManagedChannelImpl$ChannelStreamProvider$1ExitIdleModeForTransport.run(ManagedChannelImpl.java:505)
                at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
                at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
                at io.grpc.internal.ManagedChannelImpl$ChannelStreamProvider.getTransport(ManagedChannelImpl.java:509)
                at io.grpc.internal.ManagedChannelImpl$ChannelStreamProvider.newStream(ManagedChannelImpl.java:539)
                at io.grpc.internal.ClientCallImpl.startInternal(ClientCallImpl.java:258)
                at io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:191)
                at io.grpc.ForwardingClientCall.start(ForwardingClientCall.java:32)
                at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:332)
                at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:306)
                at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:218)
```

**Comment by YifeiZhuang** [comment]
Thank you for the suggestion.
I believe the error handling of Nameresolution is that errors should only be notified through listener.onError().
PRCs and name resolution happens in parallel, RPCs are queued until name resolution is successful. Notifying onError cleans up queued RPCs to avoid memory exhaustion.
Unhandled exception is considered severe failure. It causes channel panic that makes the channel useless.

**Comment by baltiyskiy** [comment]
Thank you for clarification! The point of this issue is to state this in the documentation.

**Comment by baltiyskiy** [comment]
By the way, is it OK that when the channel panics, it is transitioned to state {{ConnectivityState.TRANSIENT_FAILURE}}? The documentation for this {{ConnectivityState}} reads: 

> Channels in this state will eventually switch to the CONNECTING state and try to establish a connection again.

But the panic state is the final state, this channel will never become CONNECTING again. Maybe it's the wrong state?

**Comment by baltiyskiy** [comment]
Note: in our app, the channel is mandatory, so if the channel is in panic, the app is unusable. So we need to react to this situation. One way would be to listen to state changes and, say, restart the app. But `TRANSIENT_FAILURE` must be a recoverable problem, and we wouldn't want to restart the app on a recoverable problem; looks like it was designed for cases where one can simply use the channel and it will eventually self-heal.

**Comment by YifeiZhuang** [comment]
>  is it OK that when the channel panics, it is transitioned to state ConnectivityState.TRANSIENT_FAILURE? 

Not really. We were talking about managedChannel panic. ManagecChannel is used by application to send RPCs and once it is panic it is not usable. Application has to create new ManagedChannels.

The ConnectivityState is for subchannels (per each connection, aka transport) at Load balancer layer. Subchannels states frequently transients, e.g. TRANSIENT_FAILURE may go to IDLE.

**Comment by baltiyskiy** [comment]
I see that there's `ManagedChannelImpl.channelStateManager()`, and there's observable state on the level of `ManagedChannel`: `notifyWhenStateChanged()` and `getState()`. Both of them work on the level of `ManagedChannel`, not the subchannel level.
