### ISSUE TITLE
Cannot compile Android targets

### ISSUE THREAD

**Issue by carl-mastrangelo** [grpc/grpc-java#959]
When trying to do a `gradle build` from a clean client, I get the following error:

```
Creating configuration testReleasePublish.
Creating configuration testReleaseProvided.
Creating configuration testReleaseWearApp.
Build tools null missing. Downloading...
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:98)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy11.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:488)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
...


Cause 1: java.lang.NullPointerException: Cannot invoke method startsWith() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:88)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.jakewharton.sdkmanager.internal.PackageResolver.resolveCompileVersion(PackageResolver.groovy:101)
	at com.jakewharton.sdkmanager.internal.PackageResolver.resolve(PackageResolver.groovy:60)
	at com.jakewharton.sdkmanager.internal.PackageResolver$resolve$0.call(Unknown Source)

...
Cause 2: java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:444)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:415)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)

....

* Where:
Build file '/tmp/grpc-java/android/delegate.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'android'.
> org/gradle/api/publication/maven/internal/DefaultMavenFactory
```

When running with --stacktrace:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/publication/maven/internal/DefaultMavenFactory
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:88)
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:57)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
```

**Comment by louiscryan** [comment]
Will revert my PR and I've suggested Simon hold off on https://github.com/grpc/grpc-java/pull/957 until this is resolved

**Comment by carl-mastrangelo** [comment]
I think I know why its breaking.  Based on [this thread](https://discuss.gradle.org/t/getting-android-compilesdkversion-is-missing-error-gradle-build/9858), it looks like com.github.dcendents:android-maven-plugin:1.2  depends on some internal maven or gradle classes for gradle 2.2.  I am running 2.5, which apparently doesn't have those classes.  Bumping the dependency to com.github.dcendents:android-maven-gradle-plugin:1.3 fixes the issue.

**Comment by louiscryan** [comment]
Good to know

**Comment by ejona86** [comment]
@carl-mastrangelo, you should really use gradlew in order to avoid problems like this. I don't have gradle installed, but have an alias and it works well:

```
alias gradle='"$(git rev-parse --show-toplevel)/gradlew"'
```
