### ISSUE TITLE
HELP NEEDED!!!!CAN'T SOLVE IT FOR 2 DAYS!!!

### ISSUE THREAD

**Issue by Ha-Dj** [grpc/grpc-java#9663]
When I try to use a simple example to test grpc like: client send "name" to server to get a response like "hello name". I found this error:
ERROR 1993 --- [ault-executor-0] io.grpc.internal.SerializingExecutor     : Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@5e51b2c5

java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
	at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.0-jre.jar:na]
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:374) ~[grpc-stub-1.42.2.jar:1.42.2]
	at fdu.edu.grpc_server.service.Service.hello(Service.java:17) ~[classes/:na]
	at fdu.edu.grpc_server.proto.grpcServiceGrpc$MethodHandlers.invoke(grpcServiceGrpc.java:220) ~[classes/:na]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.42.2.jar:1.42.2]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[grpc-api-1.42.2.jar:1.42.2]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[grpc-api-1.42.2.jar:1.42.2]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[grpc-api-1.42.2.jar:1.42.2]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[grpc-api-1.42.2.jar:1.42.2]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:340) ~[grpc-core-1.42.2.jar:1.42.2]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) ~[grpc-core-1.42.2.jar:1.42.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.42.2.jar:1.42.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.42.2.jar:1.42.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_352]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_352]

It seems the server can receive the name , but can't send a response throw responseObserver.onNext(res)! 
PLEASE HELP ME ! It makes me despair!!

[grpc_server.zip](https://github.com/grpc/grpc-java/files/9896234/grpc_server.zip)
[grpc_client.zip](https://github.com/grpc/grpc-java/files/9896235/grpc_client.zip)

**Comment by Ha-Dj** [comment]
Maybe it is caused by my MAC M2. ??? CAN SOMEONE HELP ME?

**Comment by Ha-Dj** [comment]
I successfully solved this problem.

**Comment by sanjaypujare** [comment]
> I successfully solved this problem.

Can you describe what the root cause was?
