### ISSUE TITLE
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

### ISSUE THREAD

**Issue by martinwbw** [grpc/grpc-java#9672]
I've set up a local tensorflow serving endpoint and am able to access it through the python grpc client.
When I'm trying the grpc java client, however, I'm seeing the following error
```log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/bid-agent/bid-agent.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:282)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:200)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:166)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:284)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:160)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:100)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:802)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:738)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:630)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:577)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:504)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:119)
	at org.slf4j.reload4j.Reload4jLoggerFactory.<init>(Reload4jLoggerFactory.java:66)
	at org.slf4j.reload4j.Reload4jServiceProvider.initialize(Reload4jServiceProvider.java:35)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:152)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:422)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:408)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at example.bidagent.tensorflowServing.TensorflowClient2.<clinit>(TensorflowClient2.java:18)
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at tensorflow.serving.PredictionServiceGrpc$PredictionServiceBlockingStub.predict(Unknown Source)
	at example.bidagent.tensorflowServing.TensorflowClient2.main(TensorflowClient2.java:96)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
Caused by: io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f

	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

The client code is as follows:
```
        ManagedChannel channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext().build();
        PredictionServiceGrpc.PredictionServiceBlockingStub stub = PredictionServiceGrpc.newBlockingStub(channel);
        Model.ModelSpec.Builder modelSpecBuilder = Model.ModelSpec.newBuilder();
        modelSpecBuilder.setName(modelName);
        modelSpecBuilder.setSignatureName("serving_default");
        Predict.PredictRequest.Builder builder = Predict.PredictRequest.newBuilder();
        builder.setModelSpec(modelSpecBuilder);
        Predict.PredictRequest request = builder.build();
        Predict.PredictResponse response = stub.predict(request);
```

There was a previous answer https://github.com/grpc/grpc-java/issues/2905#issuecomment-293625616 but I don't get the HTTP 1 vs 2 version part. 
My current localhost endpoint is HTTP 1.1 and it's working well when I access it through my python client.
```
 % curl -I localhost
HTTP/1.1 503 Service Unavailable
Date: Thu, 03 Nov 2022 19:25:38 GMT
Server: Apache/2.4.54 (Unix) LibreSSL/3.3.6
Connection: close
Content-Type: text/html; charset=iso-8859-1
```
How should I resolve my problem? Thanks

**Comment by ejona86** [comment]
> My current localhost endpoint is HTTP 1.1

gRPC clients generally don't support HTTP 1.1. gRPC mostly uses HTTP/2. 

Can you share a snippet of the python grpc client Channel creation? Because Java and Python should be essentially the same here. (The important part in the Java snippet was `ManagedChannelBuilder.forAddress(host, port).usePlaintext().build();`.)

**Comment by ejona86** [comment]
No response to provide more information, so closing. More information can be provided and then we can reopen.
