### ISSUE TITLE
Failed resolution of: Lio/grpc/protobuf/lite/ProtoLiteUtils

### ISSUE THREAD

**Issue by michaellee8** [grpc/grpc-java#9677]
### What version of gRPC-Java are you using?

Current latest, 1.50.2

### What is your environment?
Ubuntu 20.04 LTS Developing Android SDK 32 app

### What did you expect to see?

Grpc calls using protobuf-javalite and grpc-lite should work. Tried to add `api("io.grpc:grpc-protobuf-lite:${grpcVersion}")` too but still won't work.

### What did you see instead?

Got following error during the call `java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/protobuf/lite/ProtoLiteUtils`

### Steps to reproduce the bug

Hook up a sample project in accordance to https://github.com/grpc/grpc-kotlin/blob/master/examples/android/build.gradle.kts, which a sample can be found here. https://gitlab.com/hkdse-practice/chinese/frontend/android-sample/-/blob/94d7521690a9269cabd748526435a63a18761864/app/build.gradle.kts

```
                  Process: gg.dsepractice.chinese.frontend.sample, PID: 20335
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lio/grpc/protobuf/lite/ProtoLiteUtils;
                                                                                                    	at gg.dsepractice.chinese.v1alpha1.CoreServiceGrpc.getListArticlesMethod(CoreServiceGrpc.java:37)
                                                                                                    	at gg.dsepractice.chinese.v1alpha1.CoreServiceGrpcKt$CoreServiceCoroutineStub.listArticles(CoreServiceProtoGrpcKt.kt:103)
                                                                                                    	at gg.dsepractice.chinese.v1alpha1.CoreServiceGrpcKt$CoreServiceCoroutineStub.listArticles$default(CoreServiceProtoGrpcKt.kt:100)
                                                                                                    	at gg.dsepractice.chinese.frontend.sample.MainViewModel.fetchArticleList(MainViewModel.kt:141)
                                                                                                    	at gg.dsepractice.chinese.frontend.sample.MainActivityKt$MainScreen$1$3$1.invokeSuspend(MainActivity.kt:83)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.BroadcastFrameClock@61eab28, StandaloneCoroutine{Cancelling}@c254041, AndroidUiDispatcher@8b659e6]
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.grpc.protobuf.lite.ProtoLiteUtils" on path: DexPathList[[dex file "/data/data/gg.dsepractice.chinese.frontend.sample/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~0EwvYp_olKfcNugX7MqR6Q==/gg.dsepractice.chinese.frontend.sample-YU7sj1_71BT5sLCbx8WbDg==/base.apk"],nativeLibraryDirectories=[/data/app/~~0EwvYp_olKfcNugX7MqR6Q==/gg.dsepractice.chinese.frontend.sample-YU7sj1_71BT5sLCbx8WbDg==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 18 more
```

**Comment by ejona86** [comment]
Seems it is explicitly excluded in the build file.
```
            exclude(group = "io.grpc", module = "grpc-protobuf-lite")
```

**Comment by michaellee8** [comment]
> Seems it is explicitly excluded in the build file.
> 
> ```
>             exclude(group = "io.grpc", module = "grpc-protobuf-lite")
> ```

Damn it it was excluded due to fixing other issues previously. Fault on my side here. Big thanks for pointing this out.
