### ISSUE TITLE
How can I troubleshoot a "description=Exception deserializing request!"

### ISSUE THREAD

**Issue by lmcdasi** [grpc/grpc-java#9701]
I'm having an intermitent issue during a load there there in the stream onError I have the following exception:

2022-11-18T01:24:16.676Z <> {thread=grpc-thread-1} ERROR: [c.n.m.c.c.CMSO] Processing onError. Exception during session with status Status{code=INTERNAL, description=Exception deserializing request!, cause=null}.
io.grpc.StatusRuntimeException: INTERNAL: Exception deserializing request!
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at net.devh.boot.grpc.client.metric.MetricCollectingClientCallListener.onClose(MetricCollectingClientCallListener.java:59)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.opentracing.contrib.grpc.TracingClientInterceptor$1$2.onClose(TracingClientInterceptor.java:228)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

I do not really know how I could troubleshoot that. Any suggestions please ? Thank you.

**Comment by sanjaypujare** [comment]
`Exception deserializing request!` this is happening on the server. Can you check the server side logs and paste them here if  possible? That might give you some clues.

**Comment by lmcdasi** [comment]
On server side these are the logs:
2022-11-19T20:53:19.190Z <> {span=,requestId=,clientRequestId=,thread=grpc-default-executor-0} ERROR: [i.grpc.internal.SerializingExecutor] Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@4d671a34
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
        at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:307)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:318)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:301)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:102)
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:627)
        at c.n.r.m.c.v1.CM.<init>(CM.java:45)
        at c.n.r.m.c.v1.CM$1.parsePartialFrom(CM.java:1226)
        at c.n.r.m.c.v1.CM$1.parsePartialFrom(CM.java:1220)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
        at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
        ... 10 common frames omitted

**Comment by lmcdasi** [comment]
What I noticed in tcpdump is that the issue seems to occur on a "HTTP2 segment of a reassambled PD...". That is the one that triggers the protobuf error which triggers the stream re-establishment:
![image](https://user-images.githubusercontent.com/947517/202955439-3d366ce1-109e-4a18-8224-6098547a14a1.png)

**Comment by lmcdasi** [comment]
One of my protos is:
message Command {
  string command_id = 1;
  google.protobuf.Any command = 2;
  string realm_id = 3;
}
Is it possible that the Any in between cause an issue ?

**Comment by lmcdasi** [comment]
Sorry to spam - I just realized something. When the server reports:
"
**2022-11-21T04:28:13.741Z <> {span=,requestId=,clientRequestId=,thread=grpc-default-executor-0} ERROR: [i.grpc.internal.SerializingExecutor] Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@3088887f
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
**
"
There is no error reported into the onError handler.

So in case of stream, how the server will know that an existing stream is no longer valid & it must wait for the a new stream to be established before continuing ?!?

On the client it is 'known' from the onErro handler but on the server it is not.

**Comment by lmcdasi** [comment]
I have opened a bug. I think there is an asynchronous issue at the grpc level.

**Comment by sanjaypujare** [comment]
Can you reference the bug here?

**Comment by lmcdasi** [comment]
I was wrong. In the end it is an error in the app.
