### ISSUE TITLE
gRPC works fine on my mac but throws exception when I deployed the war on azure linux app service, how can I resolve this?

### ISSUE THREAD

**Issue by dardison** [grpc/grpc-java#9773]
It seems I am using **grpc**, I didn't know it before today, what I am using is Firebase Admin SDK for Java and us I get noticed because of this error Firebase use grpc.

My app is a Java Server app deployed on a Tomcat 8.5 Server and that connects with Firebase thru Firebase Admin SDK.
Everything works fine while I running on my localhost Tomcat instance on my mac but when I deployed to an Azure app service, which is a Linux Alpine 3.9 I receive the exception of the stacktrace below:

```
2022-12-22 18:56:25,126 ERROR BaseQueueProcessCallback:41 - Error en ejecucion cola:java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
com.google.cloud.firestore.FirestoreException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at com.google.cloud.firestore.FirestoreException.forIOException(FirestoreException.java:94)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:91)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:81)
        at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
        at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:365)
        at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:72)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:72)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:65)
        at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
        at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
        at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:64)
        at com.areateclab.survey.server.firebase.FirebaseDAO.getDB(FirebaseDAO.java:36)
        at com.areateclab.survey.server.firebase.FirebaseDAO.createDocument(FirebaseDAO.java:42)
        at com.areateclab.survey.server.queue.survey.SurveyQueueProcess.execute(SurveyQueueProcess.java:26)
        at com.areateclab.survey.server.queue.survey.SurveyQueueProcess.execute(SurveyQueueProcess.java:15)
        at com.areateclab.survey.server.queue.QueueRecord.execute(QueueRecord.java:49)
        at com.areateclab.survey.server.queue.QueueProcessConsumer.run(QueueProcessConsumer.java:59)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:141)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:89)
        ... 20 more
Caused by: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:246)
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:146)
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:95)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$DefaultProtocolNegotiator.newNegotiator(NettyChannelBuilder.java:623)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:529)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyChannelTransportFactoryBuilder.buildClientTransportFactory(NettyChannelBuilder.java:188)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:360)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:133)
        at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:126)
        ... 21 more
``` 

### Versions involved
- Java 8
- Tomcat v8.5
- Firebase Admin SDK v8.1.0
- Linux Alpine 3.9

### Versions of grpc and netty founded
- When search my dependencies for grpc this was the resulted versions
![DDFCCD55-8286-4DCE-B019-5AB97503B706](https://user-images.githubusercontent.com/1153392/209221800-bd7a68f2-158d-4a53-bbd0-08df3c73fb33.jpeg)
- When search my dependencies for netty this was the resulted versions
![FB5959F9-138C-4413-BEF7-92C75B24AB96](https://user-images.githubusercontent.com/1153392/209221927-2c6f48c2-8700-4305-bcbb-428399aa43c6.jpeg)

I was searching in google with not much success about the issue, most of the few links I found talk about missing libraries but I couldn't found missing libraries in my environment.
Also I tried adding this library that at first was not present in my environment but the error remains:
```
<dependency>
	        <groupId>io.netty</groupId>
	        <artifactId>netty-tcnative-boringssl-static</artifactId>
	        <version>2.0.34.Final</version>
</dependency>
```
Any help you could give me I will appreciated, I have no clue about how can I resolve the issue.

**Comment by sanjaypujare** [comment]
Did you report this to the Firebase Admin SDK team? They should be able to help you. For one the grpc version used is old (1.39) I would recommend using a newer version - 1.51.1 is the latest but the Firebase Admin SDK folks can comment on that.

**Comment by ejona86** [comment]
Alpine. See https://github.com/grpc/grpc-java/issues/8751#issuecomment-1015502588 and click the link to see the LD_PRELOAD workaround to get gcompat to work for tcnative.

You don't mention the exact version and distributor of Java 8, but newer versions of each do work without tcnative. Is have to dig to learn exactly when. So either you are using too old a version of something of you are using a different JDK build that does something a bit different for TLS.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
