### ISSUE TITLE
ConnectException with invalid argument while send grpc message.

### ISSUE THREAD

**Issue by dwmarcuskim** [grpc/grpc-java#9905]
Hi, I'm currently working with java grpc server on google cloud platform (i.e. GCP), and client  on both cloud-side and local machine.
However, even I tested with same code, request on cloud machine does not works, with exception below. (I've hidden my call stacks)
```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[App.jar:?]
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[App.jar:?]
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[App.jar:?]
		// My call stacks
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: /[ADDRESS]:[PORT]
Caused by: java.net.ConnectException: connect(..) failed: Invalid argument
        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:155) ~[App.jar:?]
        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:128) ~[App.jar:?]
        at io.netty.channel.unix.Socket.connect(Socket.java:351) ~[App.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773) ~[App.jar:?]
        at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:144) ~[App.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758) ~[App.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600) ~[App.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342) ~[App.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653) ~[App.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632) ~[App.jar:?]
        at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54) ~[App.jar:?]
        at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:157) ~[App.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655) ~[App.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61) ~[App.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637) ~[App.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[App.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[App.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[App.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[App.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[App.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[App.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[App.jar:?]
        ... 1 more
```
I'm using `grpc-stub`, `grpc-protobuf`, `grpc-netty` with version 1.52.1, jdk 8 on client side and jdk 17 on server side.
IP address  or filewall does not seems wrong, since telnet works fine with ip address I used. Is there any possibility that ManagedChannelBuilder provides wrong information to netty backend?

**Comment by YifeiZhuang** [comment]
>> `Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Invalid argument: /[ADDRESS]:[PORT]` 

The name resolver does the resolution and then use netty to start connection. Did you use your own name resolver plugins?
Ref previous issue: https://github.com/grpc/grpc-java/issues/9367

**Comment by ejona86** [comment]
I expect the ADDRESS and PORT in ` /[ADDRESS]:[PORT]` were replaced by the user to hide their internal information. Although the "Invalid argument" error is strange. Best guess is the host doesn't support IPv6 but an IPv6 address was used (but the same issue could apply to IPv4, although I think on GCP everything still has IPv4 addresses).

Was the address an IPv6 address?

**Comment by dwmarcuskim** [comment]
Yes, I hidden address and port. And address was IPv4, like 10.0.8.17:8080

**Comment by ejona86** [comment]
Okay, then "Invalid argument" is strange, unless the host doesn't support IPv4. But I'd expect you would already know if your machines don't support IPv4, and you said telnet worked fine.

Seems the machine is Linux. I doubt Alpine could cause this sort of failure. You could try `-Dio.netty.transport.noNative=true` or excluding `io.netty:netty-transport-native-epoll` from your dependency tree to remove the `io.netty.channel.epoll` classes. That'd use NIO instead which might give different results. But it is strange.

**Comment by dwmarcuskim** [comment]
Seems like I found cause. `-Dio.netty.transport.noNative=true` option show me another exception, and there was HTTP2 related exception in server side. With anothe research, I found that GCP load balancer proxy grpc HTTP/2 request to HTTP/1.x, and this could be the reason why netty couldn't reach the endpoint.
For now, grpc could not be my option.☹

**Comment by ejona86** [comment]
GCP LB can do HTTP/2 to the backend. https://cloud.google.com/load-balancing/docs/https#using_grpc_with_your_applications .

TIL it requires TLS for HTTP/2 to the backend, but that's not as bad as it sounds because you can use any certificate. A self-signed certificate or a test certificate isn't that bad to set up.

**Comment by dwmarcuskim** [comment]
I'm currently using GKE(Google Kubernetes Engine) as my deployment. And since GKE automatically generates LB, I'm not really familiar to how to initialize it as I want. Probably I will try this later.

**Comment by ejona86** [comment]
This will probably help: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-http2

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
