### ISSUE TITLE
Question: https://grpc.io/docs/languages/java/quickstart/#run-the-example

### ISSUE THREAD

**Issue by donhuvy** [grpc/grpc-java#9908]
I read https://grpc.io/docs/languages/java/quickstart/#run-the-example

![image](https://user-images.githubusercontent.com/1328316/220521747-6ce268fd-65cf-4835-b83e-2b461c34d34e.png)

```java
Microsoft Windows [Version 10.0.19045.2604]
(c) Microsoft Corporation. All rights reserved.

C:\Users\admin\Downloads\grpc-java-1.53.0\examples>gradle installDist

BUILD SUCCESSFUL in 25s
22 actionable tasks: 22 executed
C:\Users\admin\Downloads\grpc-java-1.53.0\examples>dir
 Volume in drive C is OS
 Volume Serial Number is E2F9-6397

 Directory of C:\Users\admin\Downloads\grpc-java-1.53.0\examples

22/02/2023  11:18 SA    <DIR>          .
22/02/2023  11:18 SA    <DIR>          ..
22/02/2023  11:18 SA    <DIR>          .gradle
09/02/2023  05:49 SA    <DIR>          android
22/02/2023  11:18 SA    <DIR>          build
09/02/2023  05:49 SA             3.911 BUILD.bazel
09/02/2023  05:49 SA             6.619 build.gradle
09/02/2023  05:49 SA    <DIR>          example-alts
09/02/2023  05:49 SA    <DIR>          example-gauth
09/02/2023  05:49 SA    <DIR>          example-hostname
09/02/2023  05:49 SA    <DIR>          example-jwt-auth
09/02/2023  05:49 SA    <DIR>          example-orca
09/02/2023  05:49 SA    <DIR>          example-servlet
09/02/2023  05:49 SA    <DIR>          example-tls
09/02/2023  05:49 SA    <DIR>          example-xds
09/02/2023  05:49 SA    <DIR>          gradle
09/02/2023  05:49 SA             8.070 gradlew
09/02/2023  05:49 SA             2.763 gradlew.bat
09/02/2023  05:49 SA             4.254 pom.xml
09/02/2023  05:49 SA             9.175 README.md
09/02/2023  05:49 SA               267 settings.gradle
09/02/2023  05:49 SA    <DIR>          src
09/02/2023  05:49 SA             1.686 WORKSPACE
               8 File(s)         36.745 bytes
              15 Dir(s)  91.353.567.232 bytes free

C:\Users\admin\Downloads\grpc-java-1.53.0\examples>build\install\examples\bin\hello-world-client
thg 2 22, 2023 11:24:41 SA io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Will try to greet world ...
thg 2 22, 2023 11:24:41 SA io.grpc.examples.helloworld.HelloWorldClient greet
WARNING: RPC failed: Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/[0:0:0:0:0:0:0:1]:50051
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
        at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)
}
C:\Users\admin\Downloads\grpc-java-1.53.0\examples>java -version
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

C:\Users\admin\Downloads\grpc-java-1.53.0\examples>javac -version
javac 19.0.2

C:\Users\admin\Downloads\grpc-java-1.53.0\examples>gradle -version

------------------------------------------------------------
Gradle 8.0.1
------------------------------------------------------------

Build time:   2023-02-17 20:09:48 UTC
Revision:     68959bf76cef4d28c678f2e2085ee84e8647b77a

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19.0.2 (Oracle Corporation 19.0.2+7-44)
OS:           Windows 10 10.0 amd64

C:\Users\admin\Downloads\grpc-java-1.53.0\examples>date
The current date is: 22/02/2023
Enter the new date: (dd-mm-yy)

C:\Users\admin\Downloads\grpc-java-1.53.0\examples>
```

Please guide me how to avoid this error!
Related https://stackoverflow.com/questions/75528279/run-grpc-java-example-connection-refused-no-further-information-localhost-0

**Comment by ejona86** [comment]
"Connection refused" means the server refused the connection. You need to run `hello-world-server` from one terminal and `hello-world-client` from another. The server probably wasn't running.

**Comment by ejona86** [comment]
Seems like this is resolved. If not, comment, and it can be reopened.
