### ISSUE TITLE
Address family not supported by protocol for GRPC Netty

### ISSUE THREAD

**Issue by rocksnslopes** [grpc/grpc-java#9911]
Is there a reason why I would get this error when deployed to a remote server, but not when I'm running locally?

Wrapped by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Address family not supported by protocol: /somegrpcservice-grpc.abc.com:443
Wrapped by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
    at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
    at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
    at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
    
 Some things I've already tried:

- Various version of io.grpc:grpc-netty-shaded from 1.30.0 to 1.53.0
- Running Ncat from the remote host and successfully connecting
- Setting system property: -Djava.net.preferIPv4Stack=true

None of these seemed to make a difference. Appreciate if anyone else has any ideas. Thanks!

**Comment by rocksnslopes** [comment]
Found the solution to this which seems to be unrelated to grpc netty.  I was incorrectly packaging my far jar:  https://stackoverflow.com/questions/73286776/grpc-unsupportedaddresstypeexception-but-only-when-packaged-with-shadowjar
