### ISSUE TITLE
AsyncServletOutputStreamWriterConcurrencyTest.linCheck is flaky

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#9917]
https://source.cloud.google.com/results/invocations/2bccfd5c-0f4c-460a-ba75-b75eef2d34ae
```
org.jetbrains.kotlinx.lincheck.LincheckAssertionError:
= The execution has hung, see the thread dump =
Execution scenario (parallel part):
| maybeOnWritePossible() | flush(false) |
| maybeOnWritePossible() | write(true)  |
| maybeOnWritePossible() | flush(true)  |
| maybeOnWritePossible() | write(true)  |
| maybeOnWritePossible() | write(false) |
| maybeOnWritePossible() | flush(true)  |

Thread-0:
	sun.misc.Unsafe.park(Native Method)
	java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	java.lang.Thread.run(Thread.java:748)
Thread-1:
	sun.misc.Unsafe.park(Native Method)
	java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
	java.lang.Thread.run(Thread.java:748)

	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt:50)
	at org.jetbrains.kotlinx.lincheck.LinChecker$Companion.check(LinChecker.kt:210)
	at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt)
	at io.grpc.servlet.AsyncServletOutputStreamWriterConcurrencyTest.linCheck(AsyncServletOutputStreamWriterConcurrencyTest.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/899c33c0-7319-4fb7-ac9d-51371e9f7aff

**Comment by ejona86** [comment]
https://source.cloud.google.com/results/invocations/50c52048-553c-438e-96d6-2fa23ed737c1

```
org.jetbrains.kotlinx.lincheck.LincheckAssertionError:
= The execution has hung, see the thread dump =
Execution scenario (parallel part):
| maybeOnWritePossible() | flush(true)  |
| maybeOnWritePossible() | flush(false) |
| maybeOnWritePossible() | write(true)  |
| maybeOnWritePossible() | flush(true)  |
| maybeOnWritePossible() | flush(true)  |
| maybeOnWritePossible() | flush(false) |

Thread-1:
	java.lang.System.identityHashCode(Native Method)
	java.util.IdentityHashMap.hash(IdentityHashMap.java:295)
	java.util.IdentityHashMap.put(IdentityHashMap.java:426)
	io.grpc.servlet.AsyncServletOutputStreamWriter$WriteState.<init>(AsyncServletOutputStreamWriter.java:271)
	io.grpc.servlet.AsyncServletOutputStreamWriter$WriteState.withReadyAndDrained(AsyncServletOutputStreamWriter.java:281)
	io.grpc.servlet.AsyncServletOutputStreamWriter.runOrBuffer(AsyncServletOutputStreamWriter.java:226)
	io.grpc.servlet.AsyncServletOutputStreamWriter.flush(AsyncServletOutputStreamWriter.java:153)
	io.grpc.servlet.AsyncServletOutputStreamWriterConcurrencyTest.flush(AsyncServletOutputStreamWriterConcurrencyTest.java:139)
	java.lang.Thread.run(Thread.java:748)
Thread-0:
	java.lang.Thread.yield(Native Method)
1io.grpc.servlet.AsyncServletOutputStreamWriterConcurrencyTest.maybeOnWritePossible(AsyncServletOutputStreamWriterConcurrencyTest.java:147)
	...
```
