### ISSUE TITLE
android-interop has been failing since 2023-03-10

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc-java#9966]
https://source.cloud.google.com/results/invocations/a1941e76-cf06-43bc-b448-7eb19b47d6a1 .
```
+--------------+------------------------+------------------------+
|   OUTCOME    |    TEST_AXIS_VALUE     |      TEST_DETAILS      |
+--------------+------------------------+------------------------+
| Passed       | Nexus6-21-en-portrait  | 2 test cases passed    |
| Passed       | Nexus6-22-en-portrait  | 2 test cases passed    |
| Passed       | Nexus6P-23-en-portrait | 2 test cases passed    |
| Passed       | Nexus6P-25-en-portrait | 2 test cases passed    |
| Passed       | Nexus6P-26-en-portrait | 2 test cases passed    |
| Passed       | Nexus6P-27-en-portrait | 2 test cases passed    |
| Inconclusive | Nexus6P-24-en-portrait | Infrastructure failure |
+--------------+------------------------+------------------------+
```
 It is flaky with both API 24 and 25. Here's a case both failed: https://source.cloud.google.com/results/invocations/1dc17abd-fa5d-40b8-9d04-57b63c1250b1

Log from Firebase:
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.selfupdate.INTENT_PACKAGE_INSTALL_COMMIT.com.android.vending flg=0x10 (has extras) } in com.google.android.finsky.selfupdate.a.m@d30afed
     FATAL EXCEPTION: main
Process: com.android.vending, PID: 5408
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.selfupdate.INTENT_PACKAGE_INSTALL_COMMIT.com.android.vending flg=0x10 (has extras) } in com.google.android.finsky.selfupdate.a.m@d30afed
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.SecurityException: Caller has no access to session 1263296841
	at android.os.Parcel.readException(Parcel.java:1683)
	at android.os.Parcel.readException(Parcel.java:1636)
	at android.content.pm.IPackageInstaller$Stub$Proxy.abandonSession(IPackageInstaller.java:304)
	at android.content.pm.PackageInstaller.abandonSession(PackageInstaller.java:369)
	at com.google.android.finsky.selfupdate.a.m.onReceive(SourceFile:2170)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
	... 7 more
```

**Comment by temawi** [comment]
Looks like we are not the only ones having this issue. Flutter is seeing the same exception with `Nexus6P-25-en-portrait`: https://github.com/flutter/flutter/issues/123331

**Comment by ejona86** [comment]
Looks like the last flaky build was 2023-03-20. I think we can call this fixed.
